### ISSUE TITLE
Executor logger does not get parameters from Pea (no log_sse can be activated for Executors)

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1012]
**Describe the bug**
Since logger in `Executor` is instantiated by just giving the `name` as parameter, it can't receive `log_sse` parameter and therefore will never pass the logs to be processed by the Dashboard. 

**Solutions possible**:
- Proper forwarding the parameter.
- Access Pea's logger from the `Drivers` logger (which is a property accessing the pea's)

**Comment by hanxiao** [comment]
this should be solved in #1029

**Comment by JoanFM** [comment]
> this should be solved in #1029

Yes, I think so
