### ISSUE TITLE
Change `replica_id` argument to `pea_id` argument and change PeaRoleType accordingly

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1013]
**Describe the problem**
Right now, Pea has the `PeaRoleType Replica` and an argument called `replica_id`, which can be a little missleading ans in sync with the PR #699 , it shoule be adapted accordingly.

This issue is about keeping names aligned

**Comment by HelioStrike** [comment]
@JoanFM I'd like to take this up.

**Comment by JoanFM** [comment]
Hey @HelioStrike we would love to have your contribution.

**Comment by JoanFM** [comment]
Hey @HelioStrike , please be aware that we change the description and title of the issue to expect the name `pea_id`.

**Comment by HelioStrike** [comment]
@JoanFM Alright, will make the changes. Should I change `PeaRoleType.REPLICA` to `PeaRoleType.PEA`?

**Comment by JoanFM** [comment]
> @JoanFM Alright, will make the changes. Should I change `PeaRoleType.REPLICA` to `PeaRoleType.PEA`?

I would expect to have these Roles:
```
class PeaRoleType(BetterEnum):
    """ The enum of a Pea role

    """
    SINGLETON = 0
    HEAD = 1
    TAIL = 2
    PARALLEL = 3
```

Once we have it working like this we can see what is the best naming for this `PARALLEL` one

**Comment by HelioStrike** [comment]
@JoanFM Looking at the code, it looks like `replica_id` goes way beyond the scope of `pea.py`. Currently I wrote the rather hacky line, in `BasePea::__init__`:
```
self.args.pea_id = args.replica_id
```
Should I try to go upwards from `pea.py` and try to change things there too?
