### ISSUE TITLE
Chunk2DocRankDriver does not preserve parent_id when building the new matches

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1014]
**Describe your problem**

In the `Chunk2DocRankDriver`, non `parent_id` info is filled in. This makes bilevel `traversal_paths=['cc', 'c']` impossible.

```python
        if match_idx:
            match_idx = np.array(match_idx, dtype=np.float64)

            docs_scores = self.exec_fn(match_idx, query_chunk_meta, match_chunk_meta)
            for doc_hash, score in docs_scores:
                r = context_doc.matches.add()
                r.id = self.hash2id(doc_hash)
                r.granularity = context_doc.granularity
                r.adjacency = context_doc.adjacency + 1
                r.score.ref_id = context_doc.id  # label the score is computed against doc
                r.score.value = score
                r.score.op_name = exec.__class__.__name__
```

Same in the `jina/drivers/search.py` and all the places that use `.matches.add()`

![image](https://user-images.githubusercontent.com/2041322/94919751-44839d80-04b5-11eb-98f5-fb4f36c5a567.png)

`test_chunk2doc_ranker_driver_traverse_apply_larger_range` is skipped for now due to this problem.

**What is your guess?**

Unless, after the first traverse, it queries a `KVIndexer` to fill in the details of the `matches`, e.g. `parent_id`. There is no way to directly use arbitrary level `traversal_paths` in a row, i.e. `traversal_paths=['ccc', 'cc', 'c']`

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
@JoanFM I realized the problem is that one must use `CompoundIndexer` before the ranker, as it equips `KVSearchDriver`. So that matches returned by `CompoundIndexer` will have full information.

**Comment by maximilianwerk** [comment]
> @JoanFM I realized the problem is that one must use `CompoundIndexer` before the ranker, as it equips `KVSearchDriver`. So that matches returned by `CompoundIndexer` will have the full information.

But how would the `CompoundIndexer` help with the missing information about the parent document? I think the only solution is as you pointed out to have a intersecting `Chunk2DocRankDriver` and `KVIndexer`. Or we would need also a `parent` field in the `Document`, where the actual parent `Document` is put. Then we could before ranking do one `KVIndexer` run which iteratively go through all the parents. A `traversal_paths` could look like `['m','mp','mpp','mppp]` in order to get the information about all matches, all the parents and parents parents and parents parents parents of the matches.

**Comment by nan-wang** [comment]
AFAIK, there are two solutions to this issue:
- add `KVIndexer` right after each `Chunk2DocRankDriver`
- convert `parent_id` into a list so that we can directly traverse back

**Comment by nan-wang** [comment]
> > @JoanFM I realized the problem is that one must use `CompoundIndexer` before the ranker, as it equips `KVSearchDriver`. So that matches returned by `CompoundIndexer` will have the full information.
> 
> But how would the `CompoundIndexer` help with the missing information about the parent document? I think the only solution is as you pointed out to have a intersecting `Chunk2DocRankDriver` and `KVIndexer`. Or we would need also a `parent` field in the `Document`, where the actual parent `Document` is put. Then we could before ranking do one `KVIndexer` run which iteratively go through all the parents. A `traversal_paths` could look like `['m','mp','mpp','mppp]` in order to get the information about all matches, all the parents and parents parents and parents parents parents of the matches.

**Comment by FionnD** [comment]
### Updated requirements for this issue: 
This is still a problem and there is no solution yet. We don't yet support this behavior natively. As a subtask, we could make an example that shows a user how to do this (not naively). You could alter the Wikipedia example, break the page down into a paragraph, and into sentences. 

Acceptance criteria: 
A working example on our example repo explains this behavior.
