### ISSUE TITLE
can not run on pypy3.7 as pypy does not fully support numpy and grpcio

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1020]
**Describe your problem**

Pypy 3.7 is out so the python version is good.

Problems:
- Can not install grpcio: https://github.com/grpc/grpc/issues/16578
- Installing numpy no problem. but running `import numpy as np` gives:

```
    raise RuntimeError(msg)
RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
RankWarning: Polyfit may be poorly conditioned
```

ps, installing `numpy` via:
- `pypy -m pip install numpy`
- `pypy -m pip install --extra-index-url https://antocuni.github.io/pypy-wheels/manylinux2010 numpy -U`

both failed

**What is your guess?**

- `numpy` is relatively well-discussed, i think there must be existing solution. 
- `grpcio` is only required on the client & gateway, internal peapods do not require it. We can decouple it using cherry-picked pip dependency
- However, it is unclear if other dependencies work properly on PyPy.

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
We should check this again with the newest `grpcio` dependencies that we have
