### ISSUE TITLE
Redirection of links in docs not working

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#1030]
I was looking at the change logs [here](https://docs.jina.ai/chapters/CHANGELOG.html), the redirection of links such as RELEASE NOTE 0.0.4 is not working in my browser.

This also happens [here](https://docs.jina.ai/chapters/CONTRIBUTING.html#-making-your-first-submission).

Tested on safari & chrome.

**Comment by danielkomaz** [comment]
I updated the links within the CHANGELOG.md and CONTRIBUTING.md because they were i the wrong format "001" instead of "0-0-1"
Also fixed a few other broken links in hub/build-pod-image.md and hub/publish-your-pod-image.md

**Comment by jancijen** [comment]
This remains a problem because there  is a GitHub worflkow (see commits with message `chore(docs): update TOC`) which automatically re-generate `CONTRIBUTING.md` and `CHANGELOG.md`.
