### ISSUE TITLE
check whether a doc has already been indexed

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1055]
**Describe the feature**
check whether a doc has already been indexed

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by jaibhageria** [comment]
@nan-wang I would like to take this issue up as part of Hacktoberfest, but can you please explain the task with some more context?

**Comment by Bhairavi-shah** [comment]
I would like to work on this. How can I help?

**Comment by JoanFM** [comment]
Hello @Bhairavi-shah ,
Thank you for your interest, but this issue has already been handled.

**Comment by JoanFM** [comment]
Closed by #1064 #1070
