### ISSUE TITLE
Add portuguese translation

### ISSUE THREAD

**Issue by fernandakawasaki** [jina-ai/jina#1058]
**Describe the feature**
I would like to add translation for the README.md doc.
(I know there is a portuguese translation for the tutotial, but there isn't one for the README.md file on the root)

**Comment by bwanglzu** [comment]
hi @fernandakawasaki that would be great! let us know if you have any questions.

**Comment by fernandakawasaki** [comment]
My translation is for Brazilian Portuguese only, and there are some differences between other Portuguese speaking countries. How should I name the file? It is usually specified as 'pt-BR', but it wouldn't follow the pattern of the other files.

**Comment by nan-wang** [comment]
hi, there. Thanks for your initiatives. Let's follow the convention of using the `Locale` convention and use `README.pt_BR.md`

FYI, https://docs.moodle.org/dev/Table_of_locales

**Comment by bwanglzu** [comment]
@nan-wang do you think there're too many readmes in jina root folder? maybe at certain point, we should move it to `.github/readme/..` except the english one.
