### ISSUE TITLE
weak reference driver works while deepcopied drivers do not

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1071]
related to #1068

Note that the issue reported #1068 is not due to: "avoid the bounding RouteDriver to the ControlRequest". This ticket clarifies what it is.

The issue is about using weak reference somehow works and fail without it. To elaborate, check `tests/unit/executors/test_route_exec.py`

```python
def test_load_driver():
    b = BaseExecutor.load_config(os.path.join(cur_dir, 'yaml/route.yml'))
    print(b._drivers)

    c = BaseExecutor.load_config('_route')
    assert len(b._drivers['ControlRequest']) == len(c._drivers['ControlRequest'])
    print(c._drivers)
```

gives `b._drivers`
```
{'ControlRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c4d0>,
                    <jina.drivers.control.ControlReqDriver object at 0x10e85c510>],
 'IndexRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c590>],
 'SearchRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c550>],
 'TrainRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c610>]}
```

and `c._drivers`

```
{'ControlRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>,
                    <jina.drivers.control.ControlReqDriver object at 0x10e85c5d0>],
 'IndexRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>],
 'SearchRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>],
 'TrainRequest': [<jina.drivers.control.RouteDriver object at 0x10e85c9d0>]}
```

The combinations are the same, but note that in `b._drives` `RouteDriver` are four *different* objects (look at their memory ref), whereas in `c._drivers` `RouteDriver` the same object!

Note, it is easy to understand why `b` gives four and `c` gives one: it is in YAML deserialization and it is **reasonable and expected**.

What I don't understand is why `c` works but `b` not

_Originally posted by @hanxiao in https://github.com/jina-ai/jina/pull/1068#issuecomment-707359610_

**Comment by JoanFM** [comment]
The question is, should `Drivers` be singletons? Since they have no state and they are shared inside a Process? This may make sense

**Comment by JoanFM** [comment]
This is due to the YAML loader, it only sees one instance in this later case

**Comment by JoanFM** [comment]
This `problem` is well understood and will not be an issue with upcoming changes. I am closing for now.
