### ISSUE TITLE
Find a better way of communication between `ContainerPea` and `BasePea`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1074]
**Describe the feature**
Right now `BasePea` only knows when `ContainerPea` is ready (or any other needed communication by reading a specific message in its logstream).

This logic is really fragile and we should find a better way of communicating with the `ContainerPea` to have a reliable way to communicate.

So for instance, `BasePea` uses `events` to communicate between processes, with `ContainerPea` we may need to have some sort of socket based communication method or some `docker` built-in logic

**Comment by hanxiao** [comment]
control port is reserved for this purpose

**Comment by JoanFM** [comment]
Then it should be used to communicate that Pea is ready, instead of reading from the logs a specific message. In the code seems that no clear way was found at the time it was implemented

**Comment by hanxiao** [comment]
I guess this is because ctrl port use ipc protocol by default, which is not contain-pass-through. And I didn't have time to work on this details. Feel free to improve ctrl port, as it is needed in `jinad` and remote control
