### ISSUE TITLE
Add Ukrainian translation

### ISSUE THREAD

**Issue by Syarol** [jina-ai/jina#1119]
**Describe the feature**
Hi! I would like to add Ukrainian translation for the README.md doc.

**Comment by bwanglzu** [comment]
hi @Syarol that would be great! Please check #553 for how to contribute, also the [Locale](https://docs.moodle.org/dev/Table_of_locales) convention. Let us know if you have any questions.

**Comment by JoanFM** [comment]
Closed by #1124
