### ISSUE TITLE
Jina can't run after installed by pip

### ISSUE THREAD

**Issue by matadorhong** [jina-ai/jina#1122]
**Describe your problem**

           JINA@6835[E]:theses modules or classes can not be imported ['jina.drivers.querylang.queryset', 'jina.drivers.querylang.queryset.dunderkey', 'jina.drivers.cache', 'jina.drivers.convert', 'jina.drivers.craft', 'jina.drivers.helper', 'jina.drivers.querylang.queryset.lookup', 'jina.drivers.querylang', 'jina.drivers.querylang.filter', 'jina.drivers.querylang.slice', 'jina.drivers.search', 'jina.drivers.encode', 'jina.drivers.querylang.sort', 'jina.drivers.rank', 'jina.drivers.evaluate', 'jina.drivers.querylang.select', 'jina.drivers.querylang.reverse', 'jina.drivers.reduce', 'jina.drivers.control', 'jina.drivers.querylang.queryset.helper', 'jina.drivers.index']. You can use `jina check` to list all executors and drivers
           JINA@6835[E]:theses modules or classes can not be imported ['jina.executors.indexers.vector', 'jina.executors.evaluators', 'jina.executors.indexers.cache', 'jina.executors.evaluators.rank.precision', 'jina.executors.evaluators.decorators', 'jina.executors.rankers', 'jina.executors.crafters', 'jina.executors.requests', 'jina.executors.indexers', 'jina.executors.encoders.numeric', 'jina.executors.evaluators.rank.recall', 'jina.executors.devices', 'jina.executors.compound', 'jina.executors.decorators', 'jina.executors.encoders', 'jina.executors.encoders.tfserving', 'jina.executors.evaluators.rank', 'jina.executors.encoders.helper', 'jina.executors.indexers.keyvalue', 'jina.executors.metas', 'jina.executors.encoders.frameworks', 'jina.executors.clients']. You can use `jina check` to list all executors and drivers
           JINA@6835[W]:due to the missing dependencies or bad implementations, ['jina.hub.crafters.audio.SlidingWindowAudioSlicer', 'jina.hub.encoders.image.ImageKerasEncoder', 'jina.hub.indexers.keyvalue.MongoDBIndexer', 'jina.hub.encoders.nlp.TransformerTorchEncoder', 'jina.hub.encoders.nlp.LaserEncoder', 'jina.hub.crafters.audio.AudioSlicer', 'jina.hub.rankers.BiMatchRanker', 'jina.hub.encoders.numeric.CompressionVaeEncoder', 'jina.hub.encoders.numeric.RandomGaussianEncoder', 'jina.hub.encoders.numeric.FeatureAgglomerationEncoder', 'jina.hub.encoders.image.ImagePaddlehubEncoder', 'jina.hub.indexers.vector.ZarrIndexer', 'jina.hub.crafters.audio.AudioMonophoner', 'jina.hub.crafters.nlp.TikaExtractor', 'jina.hub.indexers.keyvalue.RedisDBIndexer', 'jina.hub.crafters.image.CenterImageCropper', 'jina.hub.encoders.video.VideoPaddleEncoder', 'jina.hub.encoders.nlp.TextPaddlehubEncoder', 'jina.hub.encoders.image.ImageOnnxEncoder', 'jina.hub.rankers.TfIdfRanker', 'jina.hub.encoders.nlp.FarmTextEncoder', 'jina.hub.crafters.nlp.PDFExtractorSegmenter', 'jina.hub.indexers.keyvalue.LevelDBIndexer', 'jina.hub.encoders.image.BigTransferEncoder', 'jina.hub.encoders.nlp.OneHotTextEncoder', 'jina.hub.crafters.nlp.JiebaSegmenter', 'jina.hub.crafters.image.ImageFlipper', 'jina.hub.encoders.numeric.RandomSparseEncoder', 'jina.hub.indexers.vector.FaissIndexer', 'jina.hub.encoders.numeric.FastICAEncoder', 'jina.hub.crafters.image.ImageResizer', 'jina.hub.encoders.image.CustomKerasImageEncoder', 'jina.hub.encoders.nlp.TransformerTFEncoder', 'jina.hub.rankers.BM25Ranker', 'jina.hub.rankers.LevenshteinRanker', 'jina.hub.crafters.audio.AudioNormalizer', 'jina.hub.crafters.image.FiveImageCropper', 'jina.hub.encoders.image.CustomImageTorchEncoder', 'jina.hub.encoders.audio.MFCCTimbreEncoder', 'jina.hub.encoders.numeric.IncrementalPCAEncoder', 'jina.hub.encoders.nlp.UniversalSentenceEncoder', 'jina.hub.crafters.image.SlidingWindowImageCropper', 'jina.hub.encoders.nlp.FlairTextEncoder', 'jina.hub.encoders.audio.ChromaPitchEncoder', 'jina.hub.indexers.vector.SptagIndexer', 'jina.hub.crafters.nlp.Sentencizer', 'jina.hub.crafters.nlp.SlidingWindowSegmenter', 'jina.hub.crafters.nlp.DeepSegmenter', 'jina.hub.crafters.image.TorchObjectDetectionSegmenter', 'jina.hub.rankers.MaxRanker', 'jina.hub.crafters.image.RandomImageCropper', 'jina.hub.indexers.vector.NmsLibIndexer', 'jina.hub.encoders.numeric', 'jina.hub.encoders.video.VideoTorchEncoder', 'jina.hub.rankers.MinRanker', 'jina.hub.encoders.audio.Wav2VecSpeechEncoder', 'jina.hub.indexers.vector.MilvusIndexer', 'jina.hub.crafters.audio.AudioReader', 'jina.hub.indexers.vector.AnnoyIndexer', 'jina.hub.indexers.vector.NGTIndexer', 'jina.hub.indexers.vector.ScannIndexer', 'jina.hub.crafters.numeric.ArrayStringReader', 'jina.hub.crafters.image.ImageCropper', 'jina.hub.encoders.image.ImageTorchEncoder', 'jina.hub.crafters.image.ImageNormalizer', 'jina.hub.crafters.numeric.ArrayBytesReader', 'jina.hub.encoders.numeric.TSNEEncoder', 'jina.hub.crafters.image.ImageReader'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers

**What is your guess?**

---

**Environment**

CentOS 7
Anaconda 5.3.0/ python 3.7
**Screenshots**

**Comment by nan-wang** [comment]
hi, @matadorhong Thanks for the comments. Would you please paste the logs of `jina check`?

**Comment by tkhabia** [comment]
I am also facing this error.
UserWarning: due to the missing dependencies or bad implementations, ['jina.hub.segmenters.image.FaceNetSegmenter', 'jina.hub.encoders.nlp.CLIPTextEncoder', 'jina.hub.encoders.image.FaceNetEncoder', 'jina.hub.classifiers.image.CLIPZeroShotClassifier'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers

the jina check output is given by 
[jina_check.txt](https://github.com/jina-ai/jina/files/6393210/jina_check.txt)
