### ISSUE TITLE
Invalid doc Id if id length is `odd`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1125]
**Describe the bug**
When overriding the `docs` through the `client` using `override_doc_id=False`, it fails when generating the `keys` to index these documents in `indexers`.

Stacktrace:

```
  File "/jina/proto/uid.py", line 69, in id2hash
    return bytes2hash(id2bytes(value))
  File "/jina/proto/uid.py", line 57, in id2bytes
    return unhexlify(value)
binascii.Error: Odd-length string
```

**Comment by hanxiao** [comment]
none `hex` string will throw error

**Comment by JoanFM** [comment]
> none `hex` string will throw error

Then it should be documented that even if you do `override_doc_id=False`, you have to make sure that not any string is valid.

With the addition of incremental indexing documentation, I willl try to push to add some documentation on how DocIDs are handled

**Comment by hanxiao** [comment]
note that https://docs.jina.ai/api/jina.proto.uid.html already provides some explaination

**Comment by hanxiao** [comment]
caveats:

ok:

```
>>> uid.bytes2id(uid.id2bytes('abcd'))
'abcd'
```

not ok:

```
>>> uid.hash2id(uid.id2hash('abcd'))
'abcdffffffffffff'
```

not ok:

```
>>> uid.hash2id(uid.bytes2hash(uid.id2bytes('abcd')))
'abcdffffffffffff'
```

**Comment by hanxiao** [comment]
wrapping uid as a class and set `digest_size` as init args, this looks like a way to go. Also, `doc.id` has to be fixed-size string

**Comment by JoanFM** [comment]
Documentation added with incremental indexing
