### ISSUE TITLE
Fix paths for Codecov

### ISSUE THREAD

**Issue by yartem** [jina-ai/jina#1129]
**Problem**
Codecov report doesn't show line-by-line coverage: `GitHub API: Forbidden`

**Details**
On the [main page](https://github.com/jina-ai/jina), click the Codecov badge, then go to Files:
![image](https://user-images.githubusercontent.com/7501517/96848142-b91a7e00-145c-11eb-8da8-31f0c474e976.png)

If you click on any file, you'll see:
![image](https://user-images.githubusercontent.com/7501517/96848191-ca638a80-145c-11eb-835a-b29ae28d388b.png)

Help page: https://docs.codecov.io/docs/fixing-paths

**Note**
Detailed coverage report needed for https://github.com/jina-ai/jina/issues/692

**Comment by JoanFM** [comment]
Hello @yartem ,

Thanks for raising the issue, is this happening to you for any `file`? It is weird since I can see the line-by-line coverage report for every file.

**Comment by yartem** [comment]
Yes, this is happening to me for any file I click (not a directory). Maybe the problem is permissions and so you can see it because you logged in?

**Comment by JoanFM** [comment]
> Yes, this is happening to me for any file I click (not a directory). Maybe the problem is permissions and so you can see it because you logged in?

May you try logging in to `codecov` with your github?

**Comment by yartem** [comment]
Cool, this was the problem, codecov didn't allow anonymous access. Thank you @JoanFM !

**Comment by JoanFM** [comment]
You are welcome @yartem happy to have the community look at the coverage !!
