### ISSUE TITLE
`_is_latest_version` always throws exception as we use `packaging` in it

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1160]
hmm, then this makes `_is_latest_version` unusable, we also use `packaging` in it. need a workaround in another PR

_Originally posted by @hanxiao in https://github.com/jina-ai/jina/pull/1150#issuecomment-716460101_

**Comment by maximilianwerk** [comment]
Apparently, `pytest` has `packaging` as a dependency. That might be the reason, we haven't discovered it beforehand.

**Comment by hanxiao** [comment]
this is solved in #1164
