### ISSUE TITLE
Community: We want your examples!

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#1161]
Jina has a whole bunch of examples on our [examples repo](https://github.com/jina-ai/examples). But we're always hungry for more. more. MORE!

If you've built something with Jina, we want to see it and help get it out there! Reply to this issue with a link to your repo and we'll get back to you asap.

Note: Be sure to include `jina` in your `requirements.txt`!

**Comment by ArushiSinghal** [comment]
@alexcg1 interested.

**Comment by alexcg1** [comment]
> @alexcg1 interested.

Great to hear! A good first step would be joining our [Slack community](http://slack.jina.ai) and discussing it with us there :smile:

**Comment by pswu11** [comment]
Close for now since we have some discussions about how to structure our examples

**Comment by alexcg1** [comment]
@pswu11 let's reopen this. We still want to keep community active and building. Our own examples are another matter

**Comment by Anushka-codergirl** [comment]
Interested!

**Comment by alexcg1** [comment]
@Anushka-codergirl go for it!

**Comment by Bug-Reaper** [comment]
Examples are the best documentation you can give developers. Examples that revolve around a specific feature are always insanely helpful. 

Perhaps someone can audit the landscape of current examples to get an idea of which additions could be most helpful.

**Comment by KhushiChaudhary744** [comment]
Hi, I am Khushi Chaudhary, a contributor to OpenForce 2022. I would like to work on this issue. 

I plan to audit the landscape of current examples to get an idea of which additions could be most helpful. communicate regarding this on slang then making a PR as soon as I am done with resolving the issue. Thank you.

**Comment by aryabasu17** [comment]
Hi, I am Arya Basu , a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you"

**Comment by alexcg1** [comment]
Sure @aryabasu17 @KhushiChaudhary744

We'd love to see some examples leveraging:

- Jina 3.0+
- [Jina Hub Executors](https://hub.jina.ai) - especially the [sandbox](https://docs.jina.ai/how-to/sandbox/) feature
- [Document stores](https://docarray.jina.ai/advanced/document-store/)
- [Finetuner](https://finetuner.jina.ai)

Rather than making a PR, the best way to do examples is to create your own repo and share a link in this thread

**Comment by alexcg1** [comment]
All participants: @joeyouss is your best contact person for this
