### ISSUE TITLE
Question: jina-bot

### ISSUE THREAD

**Issue by juzhiyuan** [jina-ai/jina#1166]
**Describe the question**

May I know how to implement the jina-bot[1]? It's really a cool bot to maintain @jina-ai repository.

[1] https://github.com/jina-bot

**Comment by maximilianwerk** [comment]
Hey @juzhiyuan,

thanks a lot for your questions. The jina-bot is a robot github user. We use github actions/workflows. They are defined in the `.github/workflows` subdirectory of each repository. See an example here:

https://github.com/jina-ai/jina/blob/master/.github/workflows/contributors.yml

When you define a github action, there must be someone who performs it. That is defined via `token: ${{ secrets.JINA_DEV_BOT }}`. And for this secret we then use the secret of the jina-bot. For more information about secrets, see:

https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets

Cheers

Maximilian

**Comment by juzhiyuan** [comment]
Wow! This will save my life! Thanks, @maximilianwerk !
