### ISSUE TITLE
feat: add hub component when running docker

### ISSUE THREAD

**Issue by theUnkownName** [jina-ai/jina#1171]
**Describe the feature**
Add the hub component when building docker from jina:devel

**Your proposal**
When building a docker image currently the hub is being skipped. 
This behaviour is intentional and was previously [introduced](https://github.com/jina-ai/jina/pull/883) due to this [problem](https://github.com/jina-ai/jina-hub/pull/295#issuecomment-683279092). However, it would be nice to bring it back when using the `devel` tag.

**Comment by nan-wang** [comment]
Do you mean to run all the hub tests in jina?

**Comment by JoanFM** [comment]
> Do you mean to run all the hub tests in jina?

The point is that to build `docker` examples we cannot be based on `FROM jinaai:jina` because the jina image itself do not contain the `hub executors`. This is intentional for the `jinaai/jina:latest` but we could have them for `devel`
