### ISSUE TITLE
add Evaluator to jina hub new

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1178]
**Describe the feature**

```
jina hub new
```

```
Select executor_type:
1 - Encoder
2 - Crafter
3 - Indexer
4 - Ranker
```

As one can see, the new type of `EvaluateExecutor` introduced in `0.7` is still missing in this wizard.

**Your proposal**
1. design pattern on the Evaluator need to be summarized in the template
2. template needs to be added to https://github.com/jina-ai/cookiecutter-jina-hub

Ref on cookiecutter syntax: https://cookiecutter.readthedocs.io/ 

---

**Environment**

**Screenshots**

**Comment by theUnkownName** [comment]
This is solved with this [PR](https://github.com/jina-ai/cookiecutter-jina-hub/pull/2)
