### ISSUE TITLE
more translations coming in, shall we move non-english Readmes into .github to clean up the root folder a bit?

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1212]
**Describe your problem**

originally proposed by @bwanglzu 

**What is your guess?**

Options:
- `.github/`
- `.github/i18n/`
- ...

What is the best practice here?
---

**Environment**

**Screenshots**

**Comment by alexcg1** [comment]
I'll get on this

**Comment by Roshanjossey** [comment]
Another suggestion `.github/translations/Readme.*`
