### ISSUE TITLE
is there any way to get jina logs while indexer is running ?

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/jina#1231]
**Describe the feature**
I'm trying to create jina reset api for our internal use. so, is there any way to get indexer progress ?

**Your proposal**
```
def progress():
    pass

f = Flow().load_config("flow-index.yml")

with f:
    f.index_lines(
        progress_fun=progress
)
````
somthing like this ?

**Comment by hanxiao** [comment]
i see, good point!

**Comment by JoanFM** [comment]
Using output_fn one should be able to count the number of documents already processed right?. This combining with how many you are planning to index or query should give you the information to have this feature.

**Comment by hanxiao** [comment]
@Kavan72 use `output_fn`, it will be called on every `batch_size`

**Comment by Kavan72** [comment]
okay, let me try this

**Comment by Kavan72** [comment]
@hanxiao from `output_fn` is working. but one thing i've notice is, jina call `output_fn` before it's processed. So, problem is when last docs is processing that time my progress will show done.

**Comment by hanxiao** [comment]
nope, check your progress code then. `output_fn` is implemented in the correct order

https://github.com/jina-ai/jina/blob/e488bbeb17be33e2601aa7882d050a24f1f7ce49/jina/clients/python/__init__.py#L127-L134

**Comment by Kavan72** [comment]
Ohh okay got it, my bad thank you
