### ISSUE TITLE
clarify meaning of 'score'

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#1255]
**Describe the bug**

From a discussion with @JoanFM , it seems like there is a bit of confusion around the `score` field.

- In the context of chunk comparisons (at the Indexer level) it means `distance`. Thus, **smaller is better**
- In the context of documents (as parents of `chunks`) it means `similarity`. Or at least, in the context of `MinRanker` (https://github.com/jina-ai/jina-hub/blob/f92276c1c4a38ef9ac34a16c4065b5d360805600/rankers/MinRanker/__init__.py#L12), **larger is better**. 

Thus there is nothing wrong with the output of the below example (from multires lyrics example):

![image](https://user-images.githubusercontent.com/8330330/98240250-6a470b00-1f69-11eb-986c-fc09ade9074a.png)

However, this is **confusing**. The problem, to me, is a matter of documentation / conflicting definitions for the `score` field. 

As originally discussed in https://github.com/jina-ai/jina/issues/1224

**Describe how you solve it**

Possible solutions:

- documentation 
- changing the name it by document / chunk. Document would be "similarity" (?), while chunk should be "distance". AFAIK, protobuf represents them with the same object, so that wouldn't work
- adding another field to the list of `match` and list of `chunk` that represents the method use to generate the `score` field. 

Something like 

```python
 "method": "MinRanker"  # or "Indexer
```

in the output

![image](https://user-images.githubusercontent.com/8330330/98564389-9a194a00-22ac-11eb-8395-8e5d0bcb0dba.png)

**Environment**

```
jina                          0.7.8
jina-proto                    0.0.75
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.4
protobuf                      3.13.0
proto-backend                 cpp
grpcio                        1.33.2
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Linux
platform-release              5.4.0-52-generic
platform-version              #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/cristian/code/jina/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)
```

**Screenshots**

**Comment by JoanFM** [comment]
I think something similar to what you describe of the `method` used to calculate the `score` is currently in place. The `op_name` in the `NamedScore`

```
message NamedScore {
    float value = 1; // value
    string op_name = 2; // the name of the operator/score function
    string description = 3; // text description of the score
    repeated NamedScore operands = 4; // the score can be nested
    string ref_id = 5; // the score is computed between doc `id` and `ref_id`
}
```

**Comment by hanxiao** [comment]
yes, our protobuf already support it. The ranker creator should write that semantic into the `description` just like writing comment. It's a best practice thing when extending with Jina. I'd suggest enforcing this best practice from now.

**Comment by JoanFM** [comment]
I do think is already being added @cristianmtr , can you check if you see it inside the `score` object inside `matches` at any level?

**Comment by hanxiao** [comment]
just fyi, you can simply add `r.score.description = exec.__doc__` in the `RankDriver` at `jina/drivers/rank.py:178` to make it more descriptive.

But then every score now carries a long description, could be less network-efficient. This is the tradeoff you never the less have to make. Or you don't make the decision and add an option and let the user decide.

**Comment by cristianmtr** [comment]
Couldn't we maybe find a way to make them all fit one direction? Either all are **lower is better** or all are **higher is better**?

**Comment by hanxiao** [comment]
unfortunately, no. Not universally everywhere. Same goes with tf, pytorch, where `score` is always task-specific, you as the user say what is best, `loss` & `distance` is at low-level, it is lower the better.

**Comment by JoanFM** [comment]
@cristianmtr maybe we can add some part in the documentation having a little discussion on `score`.

**Comment by cristianmtr** [comment]
Yeah, I guess we can do that. Is there a known list of rankers/sorters and whether they are **lower** or **higher is better**?

**Comment by JoanFM** [comment]
> Yeah, I guess we can do that. Is there a known list of rankers/sorters and whether they are **lower** or **higher is better**?

this list will evolve, so I would keep it `conceptual`

**Comment by cristianmtr** [comment]
I will try to write up something after reading through the code.

Another possible approach: since all the classes that run any of the scoring / measure know their metric (right?), we could perhaps have them invert it so as to match one specific direction (lower or higher). 

E.g. NumpyIndexer knows it uses cosine dist. It measures distances between vectors. It gets the lowest nr as top result, right? We could then do `1 - score` to map it so that **higher is better.** 

It might be problematic in the cases where we don't know the upper bound of a scoring/ranking function (not sure which examples might fit here)
