### ISSUE TITLE
Remove variable *args and **kwargs from Executors methods signatures

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1285]
**Describe the problem**

I have seen that many contributors get confused by the presence of `*args` and `**kwargs` in the signatures of the `BaseExecutors`.

It feels for them that they can add or extract parameters without respecting the base class signature (while no driver will provide those parameters).

I think removing these arguments from the signatures can help clarify this. It could also be good to remove them from the `executors` in the `hub`.

**Comment by hanxiao** [comment]
They were added on purpose, but NOT for extracting parameters. They were added for compatibility. Without `*args` and `**kwargs`, BaseClasses will NOT suppress the error of extra/unknown kwargs. Suppressing the error at the executor **interface level** is important for the framework to be stable and immutable.

**Comment by JoanFM** [comment]
yes, no big priority, I was talking about `craft`, `encode` and so on and not the __init__, but it is true that there is some loss of generalization.
