### ISSUE TITLE
test_helloworld.py::test_helloworld is misleading 

### ISSUE THREAD

**Issue by bio-howard** [jina-ai/jina#1304]
**Describe your problem**
I think that test
`def test_helloworld(tmpdir):
    subprocess.check_call(['jina', 'hello-world', '--workdir', str(tmpdir)])`
https://github.com/jina-ai/jina/blob/master/tests/integration/test_helloworld.py
Doesn't "really" test if we are calling hello-world. The result tells if jina hello-world was called and any option which accepts --workdir parameter was executed properly. It makes a risk that other script will be executed, it won't be hello-world and it will still pass the test.

**What is your guess?**
Test which is executing this command is a must. I would suggest to change name or add more meaningful description and add  new test which checks if it's "really" hello world script being executed.

---

**Environment**

n/a
**Screenshots**

n/a

**Comment by bio-howard** [comment]
I have solution for this problem. Should I commit to this task or create new issue?

**Comment by nan-wang** [comment]
hi, @bio-howard Thanks for your issue. You can make a PR and link the PR with this issue. You might want to check out the  [Github official doc](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords).

**Comment by bio-howard** [comment]
It's here https://github.com/jina-ai/jina/pull/1305
