### ISSUE TITLE
setting top_k from the client is not working

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1316]
**Describe the bug**
The integration test of running Southpark example fails. 

https://github.com/jina-ai/examples/pull/259/checks?check_run_id=1422319675

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
this issue is not solved

**Comment by JoanFM** [comment]
> this issue is not solved

This issue was thought to be solved at syntax sugar level. it is impossible to adapt to the exact Flow the user will be using.

So no solution can be universal
