### ISSUE TITLE
Refactoring document creation and access in unit tests 

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1329]
**Describe the feature**

Some unit tests, e.g. the ones related to drivers (and especially `RankDriver`) are not very well designed.

- They use low-level Document protobuf, handcrafting document attributes. This is depreciated as [Primitive Type is now main data type interface for Jina low-level ops](https://hanxiao.io/2020/11/22/Primitive-Data-Types-in-Neural-Search-System/).
- They assertion involves meta information `doc.id`, `doc.parent_id`, and based on implicit logic. This is particular true for some mocked Ranker.
- They are not 1:1 corresponding to the layer they should test.

This makes those test fragile and error-prone. I have patched all tests in the last few weeks at least 2~3 times, whereas **in principle those low-level refactoring should not trigger the refactoring on the tests refactoring, as they are not on the same layer.**

**Your proposal**

This is a team effort that requires continuous support:
- Everyone should be familiar with the Jina primitive types
- Everyone should know how to design a good unit test

The first step is to use `random_docs_new_api` instead of `random_docs`, and then think about how to refactor existing tests with [the new Jina data types](https://hanxiao.io/2020/11/22/Primitive-Data-Types-in-Neural-Search-System/). 

---

**Environment**

**Screenshots**

**Comment by bwanglzu** [comment]
> The first step is to use random_docs_new_api instead of random_docs
Done in #1356
