### ISSUE TITLE
top_k not working from Python client

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina#1330]
**Describe the bug**
top_k set via python client is failing in current southpark [test](https://github.com/jina-ai/examples/pull/289/checks?check_run_id=1441373067)

**Comment by JoanFM** [comment]
I think it may be related to the new `jina primitive types`

**Comment by bhavsarpratik** [comment]
Han has made new `QueryLang` changes in the queryset in `flow.search`. Our test are also passing.

**Comment by bwanglzu** [comment]
duplicate to #1316

**Comment by hanxiao** [comment]
this issue is not solved.
