### ISSUE TITLE
jina-bot merged a PR without any reviewer approved

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#1344]
**Describe the bug**
1. I raised a small PR to updated tests, see #1336 from feature branch
2. jina-bot committed some changes to my feature branch (see screenshot blow)
3. jina-bot merged the PR directly while no reviewer approved.

![image](https://user-images.githubusercontent.com/9794489/100109663-5a399180-2e6c-11eb-8e9b-bdf9527f3cdb.png)

**Comment by cristianmtr** [comment]
Closed as it was fixed as a part of fixing the TOC GH Action https://github.com/jina-ai/jina/issues/1321 https://github.com/technote-space/toc-generator/issues/280
