### ISSUE TITLE
Use pathlib for paths

### ISSUE THREAD

**Issue by bhavsarpratik** [jina-ai/jina#1349]
**Problem**
Since we are using a lot of `os.path` for directory/filepath operations, we can move to cleaner `pathlib` operations.

**Suggestion**
Replace all path related operations in core modules and test with pathlib's path

**Comment by amrit3701** [comment]
Hi @bhavsarpratik 

I am working on this issue. Please assign it to me. 

Thanks

**Comment by bhavsarpratik** [comment]
Hi @amrit3701, let us know asap if you are going to create a PR for this as it is an urgent task

**Comment by hanxiao** [comment]
@jina-ai/engineering please do not do any pathlib refactoring anymore. Not worth it, as none of **_our_** methods accepts `Path`-like object as arg. As a consequence, I observe this pattern `str->Path->str` in a lot of places in the tests. What's the purpose of doing this if you eventually have to convert it into `str`? for just saving `+'/'+`? 

![image](https://user-images.githubusercontent.com/2041322/102929913-bf000000-449b-11eb-8312-1dc044547116.png)

Please do not do this anymore, anywhere in the code. @bwanglzu @bhavsarpratik 
I would appreciate it if someone can revert these changes.

**Comment by bwanglzu** [comment]
Thanks for the clarification, I’ll revert the changes tomorrow
