### ISSUE TITLE
Flow search always return 50 results with random top_k set

### ISSUE THREAD

**Issue by leonwanghui** [jina-ai/jina#1350]
**Describe your problem**

Hi all, I have setup a jinabox.js environment and create several image search apps, but I found that no matter how I set `top_k`, the search result would always be 50.

**What is your guess?**

After digging out the source code, I found that the default value of top_k for `Flow.search()` method is 50, so I'm wondering if the `top_k` parameter hasn't been passed to Flow gateway when setting up Flask server.

---

**Environment**

v0.7.11

**Screenshots**

![image](https://user-images.githubusercontent.com/24707117/100217542-888f9d80-2f4e-11eb-901e-0657c80009eb.png)

BTW, I think the `time_out` parameter is also not working here.

**Comment by nan-wang** [comment]
This issue is partly related to #1316

**Comment by JoanFM** [comment]
Hey @imsergiy can you describe what is the `timeout` setting trying to achieve? It is not clear how it should behave from a core perspective

**Comment by JoanFM** [comment]
Hello @leonwanghui ,

This issue should be fixed in master! You could check with master or wait for the next minor release.

Thanks for raising awareness of this problem.
