### ISSUE TITLE
how to make a self-trained model as service using jina?

### ISSUE THREAD

**Issue by shuangt** [jina-ai/jina#1374]
I have trained a model myself, and the structure is different from the current models, how to make my model as serviceusing jina?

**Comment by JoanFM** [comment]
Hello @shuangt.

This is possible with jina. You just need to define your own encoder executor.
- In this executor you can load the model inside the post init method
- Implement the method `def encode ...`.

You can even encapsulate it in a docker container to ease the boileeplate of downloading models and so.

I think a good example for it would be a VSEImageEncoder or VSETextEncoder that you can find in the hub.

I hope this helps.

**Comment by hanxiao** [comment]
try `jina hub new`, full walkthough with Mindspore: https://hanxiao.io/2020/10/28/Mindspore-powered-Neural-Search-in-Jina/

**Comment by shuangt** [comment]
> Hello @shuangt.
> 
> This is possible with jina. You just need to define your own encoder executor.
> 
> * In this executor you can load the model inside the post init method
> * Implement the method `def encode ...`.
> 
> You can even encapsulate it in a docker container to ease the boileeplate of downloading models and so.
> 
> I think a good example for it would be a VSEImageEncoder or VSETextEncoder that you can find in the hub.
> 
> I hope this helps.

thanks

**Comment by shuangt** [comment]
> try `jina hub new`, full walkthough with Mindspore: https://hanxiao.io/2020/10/28/Mindspore-powered-Neural-Search-in-Jina/

 Thanks, I'll try it out.

**Comment by shuangt** [comment]
> Mindspore

Is the tutorial only for Mindspore, or it also works for tensorflow?

**Comment by shuangt** [comment]
> try `jina hub new`, full walkthough with Mindspore: https://hanxiao.io/2020/10/28/Mindspore-powered-Neural-Search-in-Jina/

Is the tutorial only for Mindspore, or it also works for tensorflow?

**Comment by JoanFM** [comment]
> > try `jina hub new`, full walkthough with Mindspore: https://hanxiao.io/2020/10/28/Mindspore-powered-Neural-Search-in-Jina/
> 
> Is the tutorial only for Mindspore, or it also works for tensorflow?

The tutorial is about how to add a new executor, in this case the example uses `Mindspore` just as an example, but it can be easily adapted to your own needs and dependencies.
