### ISSUE TITLE
Change timeout settings when building a docker image for neural-network-based rankers using jina hub

### ISSUE THREAD

**Issue by yuanbit** [jina-ai/jina#1412]
I am building a custom ranker using Transformer-based models. When I try to build a docker image using jina hub, ```jina hub build FinBertQARanker/ --pull --test-uses```, I get the following error:

![image](https://user-images.githubusercontent.com/12972261/101458364-15672d80-3937-11eb-9570-8fa5092a4cf7.png)

I have already downloaded the models in the docker file and the post_init is only loading them.

Is it possible to allow the users to change the timeout settings?

**Comment by maximilianwerk** [comment]
Do I understand correctly, that loading the model takes more than three hours? That should be plenty of time in any case. Can you describe a use-case where we should allow this taking more than three hours?

**Comment by yuanbit** [comment]
The error says the timeout was after 10000 ms not 3 hours. Where did the 3 hours come from?

**Comment by maximilianwerk** [comment]
> The error says the timeout was after 10000 ms not 3 hours. Where did the 3 hours come from?

Nevermind, I read 10000s which would be roughly three hours. For 10s I totally agree with you argument, that loading and setting up the model may take a bit longer.

There is the the possibility to set `timeout_ready` when adding a Pod to a Flow. That should be the right thing to use. See for example https://github.com/jina-ai/examples/blob/master/multires-lyrics-search/flows/query.yml

**Comment by JoanFM** [comment]
Yes @maximilianwerk , the problem is at the time of using `jina hub build` and --test-uses` which tests if your image can be part of a `Flow`. In that case, this `timeout_ready` parameter does not seem to be exposed.
