### ISSUE TITLE
contribute to unit tests on Jina primitive data type

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#1420]
If anyone from the community is interested in contribute to Jina, but don't know where to start, this is a good starting point: contribute to tests.

We have pre-defined a test named [test_querylangset.py](https://github.com/jina-ai/jina/blob/master/tests/unit/types/sets/test_querylangset.py), with methods and docstrings, all you need to do is to:

1. Read the code and have a bit knowledge on [Jina Primitive Data Types](https://hanxiao.io/2020/11/22/Primitive-Data-Types-in-Neural-Search-System/), and get to read the source code of [QueryLangSet](https://github.com/jina-ai/jina/blob/master/jina/types/sets/querylang.py).
2. Fill the test methods with your pytest knowledge.

**Comment by bwanglzu** [comment]
Before contributing, please take a look at #553 , comment in this ticket and we'll assign the issue to you :)

**Comment by StutiV** [comment]
Hello, @bwanglzu . I'd like to contribute, can you assign me this issue?

**Comment by bwanglzu** [comment]
@StutiV great! Let me know if you have any questions.

**Comment by StutiV** [comment]
@bwanglzu Can you elaborate this issue? It'll really help me get started, I'm new to open source. Thank you!

**Comment by bwanglzu** [comment]
@StutiV I'm not sure what's the problem you have, or you could join our [slack channel](http://slack.jina.ai/) and talk with me directly

**Comment by xjxgyc** [comment]
I find that in [QueryLangSet](https://github.com/jina-ai/jina/blob/master/jina/types/sets/querylang.py), method `build()` in `class QueryLangset` has some problems, its content:
```
def build(self):
        """Build a doc_id to doc mapping so one can later index a Document using
        doc_id as string key
        """
        self._docs_map = {d.id: d for d in self._querylangs_proto}
```
it is similar with method `build()` in [`DocumentSet`](https://github.com/jina-ai/jina/blob/master/jina/types/sets/document.py), and read the `QueryLang` source code, `QueryLang` has not id attribute. Can you give some tips to fix the problems?

At the same time, test `QueryLangset`, it use `RepeatedCompositeContainer` to construct QueryLangset Instance, in `DocumentSet` use  union of `RepeatedCompositeContainer` and `sequence`; but in  [Jina Primitive Data Types](https://hanxiao.io/2020/11/22/Primitive-Data-Types-in-Neural-Search-System/), `QueryLangset` and `DocumentSet` almost similar, I wonder that differences in initialization of `QueryLangset` and `DocumentSet`, where do I find the explanation?

**Comment by bwanglzu** [comment]
@xjxgyc thanks for your message, good catch! Are you taking care of this issue? You can skip the `:meth:build` for the time being.

>At the same time, test QueryLangset, it use RepeatedCompositeContainer to construct QueryLangset Instance, in DocumentSet use union of RepeatedCompositeContainer and sequence; but in Jina Primitive Data Types, QueryLangset and DocumentSet almost similar, I wonder that differences in initialization of QueryLangset and DocumentSet, where do I find the explanation?

Compared with `QueryLangSet`, `DocumentSet` has more usage so we  support `sequence` to this type, maybe in the future we'll do the same thing to `QueryLangSet`, but it's not supported at the moment.

**Comment by bwanglzu** [comment]
I'll take over
