### ISSUE TITLE
Add NamedScore primitive type

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1431]
**Describe the feature**
Adding NamedScore primitive type would allow to add score access through `Document` primitive type, useful in client side to provide expected scores for proper evaluation (see `NDCGEvaluation`) which requires `score.value` relevance for comparision

PR #1430 trying to add it, but testing fails

**Comment by maximilianwerk** [comment]
I vote for note having (many) reflection in the primitive types classes for more explicit and user-friendly interface.

**Comment by JoanFM** [comment]
> I vote for note having (many) reflection in the primitive types classes for more explicit and user-friendly interface.

Sure, I was just trying to have it pass the tests ... I am not sure why is failing (not in local)
