### ISSUE TITLE
Custom Driver

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1444]
**Describe the feature**
The ability to add custom drivers or a new driver that fits our needs.

**Why?**
When using the EncodeDriver, the encode method of our executor is called for every document of our IndexRequest. (Unfortunately, all available executable drivers inherit from the BaseRecursiveDriver.) This is a problem, because we want to encode all sentences at once. Otherwise, the index-runtime is way too long. We use the sentence-transformers library which offers a much faster encoding of multiple sentences at one shot.

So in a nutshell, we need a Driver that executes the encoder with all the documents of the request only once.

Our custom encode-executor:
```
from jina.executors.encoders import BaseEncoder
from jina.helper import cached_property

class SentenceEncoder(BaseEncoder):
    def __init__(self,
            model_name: str = 'xlm-r-distilroberta-base-paraphrase-v1',
            max_words: int = 128,
            device: str = None, # None (auto), cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu, xla
            *args,
            **kwargs):
        super().__init__(*args, **kwargs)
        self.model_name = model_name
        self.max_words = max_words
        self.device = device

    @cached_property
    def model(self):
        from sentence_transformers import SentenceTransformer
        return SentenceTransformer(self.model_name, device=self.device)

    def encode(self, data: 'np.ndarray', *args, **kwargs) -> 'np.ndarray':  # IS CALLED FOR EVERY DOCUMENT OF THE REQUEST
            return self.model.encode(data)
```

It would be great if someone could help us. We really need this in order to apply jina.ai in our firm.
Thank you!

**Comment by JoanFM** [comment]
Hey @janandreschweiger;

You can add custom drivers the same way you add custom executors using the py_modules parameter in the metas of the pod yaml definition.

**Comment by JoanFM** [comment]
As per the need of such a driver, you can control with batch_size the amount of documents that are encoded at once.

Is your document of the semantic unit that you want to embed to?

**Comment by JoanFM** [comment]
you can use the @batching decorator that controls how many documents of the request are considered at the same time for the function execution and which is specifically targeted for encoding in batches.

**Comment by janandreschweiger** [comment]
Hey @JoanFM, thanks for helping me out again.

**Batching**
Unfortunately, using the batching decorator doesn't change anything:
```
# other code
    @batching(batch_size = 64)
    def encode(self, data: 'np.ndarray', *args, **kwargs) -> 'np.ndarray':
        print(f"Encoding document with {data.shape[0]} sentences")
        return self.model.encode(data)
```
Output of index-request:
Encoding document with 9 sentences
Encoding document with 1 sentences
Encoding document with 4 sentences
Encoding document with 9 sentences
Encoding document with 8 sentences
Encoding document with 4 sentences
Encoding document with 16 sentences
Encoding document with 21 sentences
Encoding document with3 sentences
...

To answer your question. We want to encode sentences (=chunks) of multiple documents. But, as you can see the encoder is still executed on each document individually.

**Custom Driver**
I also tried to add a custom driver:
```
...
requests:
  on:
    IndexRequest:
      - !SentenceEncoderDriver
        metas:    
          py_modules: sentence_encode_driver.py
    SearchRequest:
      - !EncodeDriver {}
```
However, I get the following error for my new driver SentenceEncoderDriver:
`could not determine a constructor for the tag '!SentenceEncoderDriver'`

**Comment by JoanFM** [comment]
> Hey @JoanFM, thanks for helping me out again.
> 
> **Batching**
> Unfortunately, using the batching decorator doesn't change anything:
> 
> ```
> # other code
>     @batching(batch_size = 64)
>     def encode(self, data: 'np.ndarray', *args, **kwargs) -> 'np.ndarray':
>         print(f"Encoding document with {data.shape[0]} sentences")
>         return self.model.encode(data)
> ```
> 
> Output of index-request:
> Encoding document with 9 sentences
> Encoding document with 1 sentences
> Encoding document with 4 sentences
> Encoding document with 9 sentences
> Encoding document with 8 sentences
> Encoding document with 4 sentences
> Encoding document with 16 sentences
> Encoding document with 21 sentences
> Encoding document with3 sentences
> ...
> 
> To answer your question. We want to encode sentences (=chunks) of multiple documents. But, as you can see the encoder is still executed on each document individually.
> 
> **Custom Driver**
> I also tried to add a custom driver:
> 
> ```
> ...
> requests:
>   on:
>     IndexRequest:
>       - !SentenceEncoderDriver
>         metas:    
>           py_modules: sentence_encode_driver.py
>     SearchRequest:
>       - !EncodeDriver {}
> ```
> 
> However, I get the following error for my new driver SentenceEncoderDriver:
> `could not determine a constructor for the tag '!SentenceEncoderDriver'`

Ok I see, so your problem is that you want to encode in the same batch "chunks" of different "documents" right? Then for this you will indeed need to add a custom driver.

Your syntax for adding py_modules is wrong though. Driver has no metas parameters. you need to add it in the metas of the executor that will be used by this driver. Like in the same place where u are adding your custom executor.

**Comment by JoanFM** [comment]
It is however a nice feature to think of @hanxiao having some sort of an "accumulator" at driver level to accumulate more DocumentSet to be passed to the executors. Important when these executors work on different levels than root.

**Comment by geckgecko** [comment]
@JoanFM Thank you it finally works!!!

In case you're interested in the implementation:
```
from jina.drivers.encode import EncodeDriver
from jina.types.sets.document_set import DocumentSet

class SentenceEncodeDriver(EncodeDriver):
    def __call__(self, *args, **kwargs):
        doc_set = DocumentSet([])
        for doc in self.docs:
            for chunk in doc.chunks:
                doc_set.append(chunk)
        self._apply_all(doc_set, *args, **kwargs)
```
I know the implementation is a little bit brutal. It would be much cleaner to build up a new driver from the BaseDriver class.

**Comment by JoanFM** [comment]
> @JoanFM Thank you it finally works!!!
> 
> In case you're interested in the implementation:
> 
> ```
> from jina.drivers.encode import EncodeDriver
> from jina.types.sets.document_set import DocumentSet
> 
> class SentenceEncodeDriver(EncodeDriver):
>     def __call__(self, *args, **kwargs):
>         doc_set = DocumentSet([])
>         for doc in self.docs:
>             for chunk in doc.chunks:
>                 doc_set.append(chunk)
>         self._apply_all(doc_set, *args, **kwargs)
> ```
> 
> I know the implementation is a little bit brutal. It would be much cleaner to build up a new driver from the BaseDriver class.

Happy to help; it is definitely something to consider; also something that can seamlessly do it while mantaining the traversal structure

**Comment by janandreschweiger** [comment]
BTW @geckogecko is my colleague.

Should I now close this issue or should I just leave it open?

In addition: Is there any possibility how one can index a document during query time (We use Jina with Faiss)? I'm asking because we have a question-answering system. I think that would be an important feature for many users.

**Comment by JoanFM** [comment]
> BTW @geckogecko is my colleague.
> 
> Should I now close this issue or should I just leave it open?
> 
> In addition: Is there any possibility how one can index a document during query time (We use Jina with Faiss)? I'm asking because we have a question-answering system. I think that would be an important feature for many users.
> 
> Thank you again!

Cool!! 

I think we can close this issue and open a new one reformulating the feature request (mentioning that you are interested in applying executor to chunks of different documents at the same time)

As per index while querying, it is not possible at the moment, but is definitely something to be considered for the near future.

**Comment by janandreschweiger** [comment]
Cool, sounds great.

**Comment by JoanFM** [comment]
Opened #1493

**Comment by JoanFM** [comment]
Hey @janandreschweiger , #1483 has been merged and you may be interested in testing it. You can set a batch size at driver level so that you can profit from the `batching` even at `chunk` level without needing your custom Driver
