### ISSUE TITLE
Delete indexed documents

### ISSUE THREAD

**Issue by nero-nazok** [jina-ai/jina#1447]
**Describe the feature**
The ability to delete indexed documents.

**Application**
We offer a Q&A bot, that is able to answer questions based on our knowledge base. However our knowledge base changes everyday. Sometimes documents change or are removed, because they are outdated. Without the ability to delete indexed documents we would have to re-index everything again, making Jina impractical for a real world application.

As deleting documents is such a basic feature, it is probably already possible in one or the other ways. I just couldn't find any information on this in the documentation.

If there is really no implementation, I could build a custom indexer, that deletes documents if a custom flag is set in the IndexRequest. Nevertheless, I think that Jina should support it out of the box.

It would be great if someone could help me out. I am always thankful for your great support!

**Comment by janandreschweiger** [comment]
Hi @nero-nazok!
Deleting and updating documents are also important features for us, so I had a look at the source code.

KeyValue Indexes already have these functions implemented:
- update(keys, values, *args, **kwargs)
- delete(keys, *args, **kwargs)

But unfortunately, vector indexes don't. I also think that atleast deleting documents should be part of the framework itself. You get update for free, by just deleting and reindexing the document.

Could someone have a look on this?

**Comment by JoanFM** [comment]
Hello @nero-nazok and @janandreschweiger.

Thank you very much for the interest in jina and for the suggestion. Updating and deleting are two features that we are currently working on. As @janandreschweiger can see, the interfaces are there and we will soon deliver the full feature.

So please stay tuned

**Comment by nero-nazok** [comment]
Thank you @JoanFM for your response. Deleting documents (and its vectors) is a really important feature for us. Do you think it will be possible until mid-January?

**Comment by maximilianwerk** [comment]
> Thank you @JoanFM for your response. Deleting documents (and its vectors) is a really important feature for us. Do you think it will be possible until mid-January?

Yes, it will be. There might be some caveats then, which we will communicate, but in principle it will be possible.

**Comment by nero-nazok** [comment]
That's awesome.
You are really moving fast. Keep it up!

Is it ok if I leave this issue open until this feature is available? Just in case we have some questions or problems.

**Comment by JoanFM** [comment]
> That's awesome.
> You are really moving fast. Keep it up!
> 
> Is it ok if I leave this issue open until this feature is available? Just in case we have some questions or problems.

Sure, no problem!

**Comment by nero-nazok** [comment]
Updating & deleting documents is finally possible!
Thank you @JoanFM and @maximilianwerk 🥳
