### ISSUE TITLE
update Document id at __enter__ rather than __exit__

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#1451]
Given the `with` syntax, if we do:
```python
with Document() as doc:
    for i in range(9):
        with Document() as match:
            match.score.value = i
            print(match.parent_id) # empty
            print(match.score.ref_id) # empty
            doc.matches.append(match)
```
Since `id` of the document is None, the matches (also chunks) can not be referenced to it's parent doc. (and the document id will only be updated at `__exit__`)

Proposed solution:
```python
class Document():
    ...
    def __enter__(self):
        if not self._document.id:
            self.update_id()
        return self

    def __exit__(self, ...):
        pass
    ...
```

**Comment by JoanFM** [comment]
Hey @bwanglzu; this will be outdated once this #1440 is merged I think.

**Comment by theUnkownName** [comment]
Yes, this will be changed with the #1440 PR. So th `id` will never be None, it will be either set by the client, or if nothing was set, a random one will be created.
