### ISSUE TITLE
Driver handling Reduce and Route logic together

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1468]
**Describe the bug**
When investigating #1302 I found that the issue was not that IDLE was not handled by ControlReqDriver but that we were not using `RouteDriver` in the `HeadPea`. So then, how can I use `HeadPea` to `Reduce`  incoming messages and at the same time to `Route` inside the `Pod`?

**Comment by JoanFM** [comment]
this could be handled by allowing Composition of ControlDrivers. In comparison with ExecutableDrivers, sequential application does not seem to make much sense

**Comment by hanxiao** [comment]
can you add a minimum test case to show this problem?

**Comment by JoanFM** [comment]
I did @hanxiao added in #1469

**Comment by JoanFM** [comment]
Test added in #1469
