### ISSUE TITLE
EncodeDriver to be able to use batching even when chunks are involved

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1493]
**Describe the feature**
Coming from #1444 .

The user is trying to index documents with a small amount of chunks per documents. 

With current features, the batching of the encoder is not fully applied because the driver only encodes together `chunks` of the same `parent` document, thus losing a lot of the benefits that batching would provide in terms of speed.

It would be cool to have the ability of batching irrespective of the granularity level

**Comment by janandreschweiger** [comment]
Hi @JoanFM,
I just wanted to mention that we were able to reduce the index-time from whopping 531 seconds to just 82 seconds.
We used a custom driver to fetch all documents at once. In addition, we replaced the TransformerTorchEncoder with the sentence-transformers library, which speeds up encoding dramatically.

Furthermore, I think there is no documentation of who one can add a custom driver.

**Comment by JoanFM** [comment]
> Hi @JoanFM,
> I just wanted to mention that we were able to reduce the index-time from whopping 531 seconds to just 82 seconds.
> We used a custom driver to fetch all documents at once. In addition, we replaced the TransformerTorchEncoder with the sentence-transformers library, which speeds up encoding dramatically.
> 
> Furthermore, I think there is no documentation of how one can add a custom driver.

Interesting, so you did a new Executor or slightly adapted one of ours?

As per documentation on that part I will create an issue. 

Thanks

**Comment by tadej-redstone** [comment]
> Hi @JoanFM,
> I just wanted to mention that we were able to reduce the index-time from whopping 531 seconds to just 82 seconds.
> We used a custom driver to fetch all documents at once. In addition, we replaced the TransformerTorchEncoder with the sentence-transformers library, which speeds up encoding dramatically.
> 
> Furthermore, I think there is no documentation of how one can add a custom driver.

Regarding slowness of TorchEncoder: it's because currently all inputs are padded to max length, which slows encoding dramatically for short sequences. I have a PR almost ready addressing that :)

**Comment by nero-nazok** [comment]
Sounds great @JoanFM. Yes I created a completely new executor.

**Comment by janandreschweiger** [comment]
I accelerated it with a completely new executor.

**Comment by JoanFM** [comment]
@janandreschweiger,

a new PR to TransformerTorchEncoder has been merged which significantly improves performance.

**Comment by JoanFM** [comment]
Closed by #1483
