### ISSUE TITLE
Faiss index documents without reloading the query-flow

### ISSUE THREAD

**Issue by nero-nazok** [jina-ai/jina#1498]
Hi Jina team,

we now use your framework in production for our question-and-answer tool.

The problem is that some users already claimed that they cannot query their newly created questions. This is, because we only index documents during the night. Thus, I wanted to ask if it is possible to index documents without reloading the query-flow.

We have a flask webserver with two singletons:
- index-flow
- query-flow
From my understanding both flows instantiate a FaissIndexer. So the index-flow only needs to call the FaissIndexer.add(vecs) of the query-flow. And indexing at query-time would finally be possible.

It would be great if someone could help us out with this problem.
Thank you!

**Comment by janandreschweiger** [comment]
Hey @nero-nazok, we also need this feature. From my point of view, the problem is that there are two FaissIndexer instances, which load all vectors. So in order to enable searching and indexing at the same time, both flows should live in the same process with a single FaissIndexer.

Maybe someone from the Jina team could have a look on this?

**Comment by nero-nazok** [comment]
You are right @janandreschweiger. Two FaissIndexer doubles the consumed memory.

**Comment by JoanFM** [comment]
Hey @nero-nazok,

This is currently not possible. Right now the Faiss Index is only created in memory at query time, while at Index time behaves as the NumpyIndexer.

It is definitely an interesting feature to look at, but not currently available.

**Comment by nero-nazok** [comment]
Thanks for your reply @JoanFM. So I just need to extend the FaissIndexer to do the following at index-time:
1. get the faiss_index instance of the query-flow
2. call the faiss_index.add(vecs) method

**Comment by janandreschweiger** [comment]
Yes @nero-nazok, that should do the job.
Does anyone know how one can get the faiss_index instance?

**Comment by JoanFM** [comment]
> Thanks for your reply @JoanFM. So I just need to extend the FaissIndexer to do the following at index-time:
> 
> 1. get the faiss_index instance of the query-flow
> 2. call the faiss_index.add(vecs) method

That is not possible since they live in isolated processes.

**Comment by ace-kay-law-neo** [comment]
Interprocess communication would be possible.
Is it likely that such a feature will be available in 2021 @JoanFM?

**Comment by nan-wang** [comment]
> Interprocess communication would be possible.
> Is it likely that such a feature will be available in 2021 @JoanFM?
hi, @ace-kay-law-neo I'm afraid not. Query-time and index-time are independent of each other. There is no concrete plan to enable querying while at index time. That is a trade-off between flexibility and easy-maintenance we've made when design Jina.

**Comment by nero-nazok** [comment]
Thanks for your reply @nan-wang.

We found an easy solution:
1. use a single flow for indexing & querying
2. add the vector with faiss_idx.add at runtime

However, using a single flow may has some drawbacks:
1. sometimes a pod is used only for indexing or querying
2. deleting & updating documents becomes maybe more complicated

For now I will close this issue and wait for your delete and update feature. I'll keep an eye on it and probably post the solution here if it is still feasible.

Thanks everyone for your interest and support!

**Comment by janandreschweiger** [comment]
That would be nice @nero-nazok. We're still interested in this feature!
