### ISSUE TITLE
Questions regarding MongoDBIndexer

### ISSUE THREAD

**Issue by ace-kay-law-neo** [jina-ai/jina#1502]
He Jina team, I had a look at the MongoDBIndexer. Some things however remained unclear.

**MongoDB-Id vs Jina-Id**
MongoDBs id is a 24byte hex number. Jina's id is only of the size 16. How does this work together? Is there some internal translation?

**MongoDB only?**
Does the indexer store all information in the database or has it some data (e.g. the Id translation) stored locally like the BinaryPbIndexer indexer from which it inherits.

**Switch between Indexer**
Is it possible to switch between MongoDBIndexer and BinaryPdIndexer based on the document. Or does one need to write a custom executor therefor.

Thanks!!!

**Comment by janandreschweiger** [comment]
I'm particularly interested in the ID-question. I'd would be cool to use the mongo _id as the jina document id. Unfortunately, there jina restricts us to 16 characters. Can someone have a look on this one?

**Comment by cristianmtr** [comment]
> I'm particularly interested in the ID-question. I'd would be cool to use the mongo _id as the jina document id. Unfortunately, jina restricts us to 16 characters. Can someone have a look on this one?

I am not an expert in Mongo, but the test suite wrote for the indexer works. What is the issue that you're experiencing with the id being only 16 characters?

Unfortunately at the moment Jina IDs are calculated in a specific way.

In the next release we are going to allow custom ids that can be of any length (as they are no longer hashes of the content):

```
In [8]: a = Document(id='a'*24)
In [9]: a.id
Out[9]: 'aaaaaaaaaaaaaaaaaaaaaaaa'
```

> Switch between Indexer
> Is it possible to switch between MongoDBIndexer and BinaryPdIndexer based on the document. Or does one need to write a custom executor therefor.

No, not at the moment. And I'm not sure what the use case would be here

**Comment by janandreschweiger** [comment]
Thank you @cristianmtr! Custom ids would be great. Will they be available in 0.8.x or 0.9.0

**Comment by cristianmtr** [comment]
> Thank you @cristianmtr! Custom ids would be great. Will they be available in 0.8.x or 0.9.0?

Seems like it's there in `0.8.11`

**Comment by deepankarm** [comment]
Hello @janandreschweiger, glad to see your interest in Jina.

Mongo allows us to set [custom ids](https://docs.mongodb.com/manual/core/document/#the-id-field) during insert. As long as it is unique, we can set a simple integer to be the id. Is there any specific issue you're facing with `id` of size 16?


![image](https://user-images.githubusercontent.com/9050737/102755334-3fd3d480-4394-11eb-8b6f-da45ef40d9c9.png)

**Comment by janandreschweiger** [comment]
Cool! Thank you @cristianmtr and @deepankarm!

**Comment by janandreschweiger** [comment]
No @deepankarm, there isn't any issue in particular. We just already have a mongo-db database with documents and now want to use jina for search. So it is nice that we don't need to change our mongo-ids

**Comment by ace-kay-law-neo** [comment]
Thanks for resolving my questions!!!
Have a nice day.
