### ISSUE TITLE
Add documentation to add custom Drivers

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1504]
Furthermore, I think there is no documentation of how one can add a custom driver.

_Originally posted by @janandreschweiger in https://github.com/jina-ai/jina/issues/1493#issuecomment-748571237_

**Comment by gabbyprecious** [comment]
Can I work on this?

**Comment by JoanFM** [comment]
> Can I work on this?

Sure, documentation needs to be added here: `docs/chapters/extend/driver.rst`.

Do you know what is the good way to add this?

**Comment by FionnD** [comment]
This is a duplicate of issue https://github.com/jina-ai/jina/issues/2085 
Closing
