### ISSUE TITLE
Faiss: Normalization for cosine similarity

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1509]
Hi jina team!

The most common metric for semantic search is the cosine similarity. When using Faiss we don't have the cosine-similarity, but we can do the following:
1. normalize the vectors before adding them
2. using the inner_product

Unfortunately, the FaissIndexer has no normalize option. But, this could actually be implemented easily. One just needs to call the normalize_L2 method before they are adding or training the faiss-index:
```
# other code
if self.normalize:
    faiss.normalize_L2(training_vectors)
index.train(training_vectors)

# other code
if self.normalize:
    faiss.normalize_L2(vectors)
index.add(vectors)

# other code
```

- Explanation: https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#how-can-i-index-vectors-for-cosine-similarity
- Code: https://github.com/facebookresearch/faiss/issues/61#issuecomment-415658504

**Comment by nero-nazok** [comment]
Hi @janandreschweiger,

This is awesome, I always thought that I use the inner product is the cosine similarity. But, you are right the vectors have to be normalized.

A problem may be that this method uses batching:
```
    @batching
    def build_partial_index(self, vecs: 'np.ndarray', index):
        index.add(vecs.astype(np.float32))
```
I am not sure, but I guess that the faiss.normalize_L2 has to be applied on all vectors at once. Could someone have a look on this?

**Comment by JoanFM** [comment]
> Hi jina team!
> 
> The most common metric for semantic search is the cosine similarity. When using Faiss we don't have the cosine-similarity, but we can do the following:
> 
> 1. normalize the vectors before adding them
> 2. using the inner_product
> 
> Unfortunately, the FaissIndexer has no normalize option. But, this could actually be implemented easily. One just needs to call the normalize_L2 method before they are adding or training the faiss-index:
> 
> ```
> # other code
> if self.normalize:
>     faiss.normalize_L2(training_vectors)
> index.train(training_vectors)
> 
> # other code
> if self.normalize:
>     faiss.normalize_L2(vectors)
> index.add(vectors)
> 
> # other code
> ```
> 
> * Explanation: https://github.com/facebookresearch/faiss/wiki/MetricType-and-distances#how-can-i-index-vectors-for-cosine-similarity
> * Code: [facebookresearch/faiss#61 (comment)](https://github.com/facebookresearch/faiss/issues/61#issuecomment-415658504)

Hey @janandreschweiger,

that is a really great finding.

Would you like to provide a PR in the hub? you can add this logic depending on the metric (distance) of the FaissIndexer?

**Comment by janandreschweiger** [comment]
Of course @JoanFM! But I need an answer regarding @nero-nazok's comment. Do I have to apply normalization on all vectors at once? And if, is it even possible, because of the batching?

**Comment by JoanFM** [comment]
> Of course @JoanFM! But I need an answer regarding @nero-nazok's comment. Do I have to apply normalization on all vectors at once? And if, is it even possible, because of the batching?

I think normalization is to guarantee norm 1 so should be indepensent if you do it one by one or in batches. 

I do not see a reason why this should be a problem

**Comment by janandreschweiger** [comment]
Perfect @JoanFM I will do that.

**Comment by akhilanaz** [comment]
My model gives unit vectors as output, and using this I have created a vector matrix  and applied FAISS.normaliseL2( ) function on it.
Since the search vector is also a unit vector, faiss normalization cannot be applied on it. This search gives distances rom a range 212.00. Can you please let me know what causes this threshold for minimum distance.
