### ISSUE TITLE
pr commitlint is broken

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#1511]
**Describe the bug**

I've disabled it as it kept failing https://github.com/jina-ai/jina/pull/1510/checks?check_run_id=1588875343#step:7:10 even though the linting is passing in `ci.yml` workflow https://github.com/jina-ai/jina/pull/1510/checks?check_run_id=1588897306#step:5:9

**Comment by hanxiao** [comment]
it is broken only on `pull_request_target` event, seems related to https://github.com/wagoid/commitlint-github-action/issues/66

**Comment by cristianmtr** [comment]
Seems like this has been fixed and now it's only part of `ci.yml`
