### ISSUE TITLE
Should we allow to load a Flow from a string based yaml? This can be useful in `jinad`.

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1517]
Should we allow to load a Flow from a string based yaml? This can be useful in `jinad`.

![image](https://user-images.githubusercontent.com/9050737/102798592-58b1a980-43d7-11eb-82fd-d861807735ea.png)

_Originally posted by @deepankarm in https://github.com/jina-ai/jina/issues/1516#issuecomment-749060947_

**Comment by hanxiao** [comment]
fyi, it supports already, https://docs.jina.ai/chapters/cli/jina-pea.html?highlight=uses

**Comment by JoanFM** [comment]
> fyi, it supports already, https://docs.jina.ai/chapters/cli/jina-pea.html?highlight=uses

But this is a Pea and not a Flow right?

**Comment by hanxiao** [comment]
> But this is a Pea and not a Flow right?

Right, it does not support atm

**Comment by deepankarm** [comment]
There's a support, but looks buggy.

![image](https://user-images.githubusercontent.com/9050737/102800574-12aa1500-43da-11eb-9dd9-cb4ca5da2963.png)
