### ISSUE TITLE
top_k no longer works for search

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1521]
Hi Jina team,

I think I found a bug in the recent version. Jina returns 50 documents for top_k=10.
It is either a bug or just has to be updated in the documentation. Downgrading resolved the issue.

Thank you!

**Comment by hanxiao** [comment]
the last release make `top_k` related to `SliceQL` driver's `end` only. If you don't use `SliceQL` in any part of your flow, then `top_k` has no effect.

if you are using `VectorSearchDriver` somewhere in your pipeline, you can use the following code to make `top_k` related to `VectorSearchDriver` again, e.g.

```python
topk_ql = QueryLang(VectorSearchDriver(top_k=5, priority=1))

f.search(random_docs(...), on_done=..., queryset=[topk_ql])
```

**Comment by hanxiao** [comment]
0.8.12 fixed it

**Comment by janandreschweiger** [comment]
Thanks @hanxiao!
