### ISSUE TITLE
Indexing error

### ISSUE THREAD

**Issue by annaakhil** [jina-ai/jina#1523]
**When I tried to index the data I was getting an error**
                      
                  gateway@722[E]:callback() may not work properly due to the bad response: encoder-1(TransformerTorchEncoder) throws TypeError("batch_text_or_text_pairs has to be a list (got <class 'numpy.ndarray'>)")

**Environment**

**Screenshots**
              
![image](https://user-images.githubusercontent.com/49350396/102854408-7bc87180-4448-11eb-9f13-68ba85774b3a.png)

**Comment by Kavan72** [comment]
@annaakhil can you pls provide transformer and jina version ? for jina you can use this `jina --version-full`

**Comment by annaakhil** [comment]
@Kavan72 
jina version:
jina                          0.5.5
jina-proto                    0.0.59
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.32.0
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Linux
platform-release              4.19.128-microsoft-standard
platform-version              #1 SMP Tue Jun 23 12:58:10 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/akhil/.local/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_TEST_FAISS               (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)

can you please send me the command for checking the transformers version?

**Comment by Kavan72** [comment]
there is no separate command to check transformers version, but you can use `pip freeze`(pip or pip3 depend on you python environment) to check all installed libraries version

and btw are you using trying to run any jina's example or just for testing purpose because your jina version is outdated ?

**Comment by tadejsv** [comment]
Hi - this has been solved by a few recent PRs. Please upgrade to the lastest version of jina.

**Comment by annaakhil** [comment]
@Kavan72  
i am using transformers==4.1.1 .
I want to integrate with rasa chatbot so I am just checking how this jina works by taking an example that I found out in Github.
I installed the latest jina version only but while installing cookie-cutter it was taking jina 0.5.5 version

**Comment by Kavan72** [comment]
you need to upgrade your jina.

**Comment by annaakhil** [comment]
@kavan thank you so much, it's working.

**Comment by annaakhil** [comment]
@tadejsv thank you for the response, I have updated the jina and it is working.

**Comment by JoanFM** [comment]
Closing this issue as it seems to have been solved
