### ISSUE TITLE
Flow or AsyncFlow for custom Rest-API

### ISSUE THREAD

**Issue by ace-kay-law-neo** [jina-ai/jina#1528]
Hey Jina team,
we have build a custom Rest-API with FastAPI for Jina. The API provides among some other commands Jina's search & index.
I now not really sure if we need to use the AsyncFlow or the regular synchronous Flow.

Moreover, is it right way to define the two flows as singletons?
```
app = FastAPI()
flow_search = Flow.load_config('search-flow.yml')
flow_index = Flow.load_config('index-flow.yml')

@app.post('/search')
def search(query: str):
    res = flow_search.search_lines([query], top_k=10)
    # ...
```

Thanks for your support!

**Comment by deepankarm** [comment]
Hello @ace-kay-law-neo,

We've been working on [jinad](https://github.com/jina-ai/jinad), a FastAPI based server to allow remote workflows in Jina. Feel free to try different endpoints for Flow creation, deletion etc. The API docs can be found [here](http://api.jina.ai/jinad/).

Each Flow in jinad lives as a singleton & is accessed using a `flow_id`. If you have further questions about the endpoints or need more clarity in the docs, please create issues in the [jinad repo](https://github.com/jina-ai/jinad/issues). 

For index/search operations, jina already has a [gRPC based Client](https://docs.jina.ai/api/jina.clients.html?#module-jina.clients) that can be used for `gRPC-gateway` based Flows, whereas for `REST-gateway` based Flows (again based on FastAPI), we have the docs [here](https://docs.jina.ai/chapters/restapi/index.html). We are also adding advanced features lilke streaming for REST -gateway soon. 

Thanks!

**Comment by ace-kay-law-neo** [comment]
Wow thanks for your great answer @deepankarm! We will definitely try out jinad. 

We don't want to use the Jina's rest-API, because we need some custom functionalities. So we will probably have a FastAPI interface that makes search/query calls with the gRPC based client (asyncFlow.search_lines).

Thanks again for helping us out!!
