### ISSUE TITLE
Getting gRPC error while indexing

### ISSUE THREAD

**Issue by Aaina-bajaj** [jina-ai/jina#1534]
**Describe the bug**
 getting gRPC error while indexing;  **gRPC error: StatusCode.UNAVAILABLE failed to connect to all addresses
the ongoing request is terminated as the server is not available or closed already**

**Describe how you solve it**

---  jina hello-world

**Environment**
 jina                          0.8.11
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.34.0
pyyaml                        5.3.1
python                        3.8.5
platform                      Linux
platform-release              4.4.0-19041-Microsoft
platform-version              #488-Microsoft Mon Sep 01 13:43:00 PST 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /usr/local/lib/python3.8/dist-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)

**Screenshots**

![image](https://user-images.githubusercontent.com/21350661/102975202-b05e2b00-4525-11eb-9b4e-1bd039d5e1f5.png)

**Comment by Aaina-bajaj** [comment]
Hey,

I am also getting the same issue at the time of indexing while trying example 'Southpark-incremental-indexing'. Is it something that I need to install?

Thank you!

**Comment by deepankarm** [comment]
Hi @Aaina-bajaj,  Glad to see your interest in trying Jina. 

I see that you're using WSL.  Is this WSL1 or WSL2?  Can you also help me understand if you have any proxies set in your machine?

**Comment by Aaina-bajaj** [comment]
Hey @deepankarm,

I am using Ubuntu 20.04 LTS application on Windows 10. So I believe, it's WSL1. Also, I don't any proxies.

**Comment by deepankarm** [comment]
[Here's](https://askubuntu.com/a/1267099) how you can verify the WSL version. Currently, jina is supported on [WSL 2](https://docs.jina.ai/chapters/install/os/on-wsl.html). While we test for this issue in WSL1, could you try updating to WSL2 and retest?

**Comment by Aaina-bajaj** [comment]
Hey, Thanks for the quick follow-up. It worked.

**Comment by rrlcs** [comment]
Hi @deepankarm, I'm facing the same issue on Ubuntu 22.04. I'm not using WSL

**Comment by JoanFM** [comment]
hey @rrlcs ,

can u add a new ticket with ur problem and how u can reproduce?
