### ISSUE TITLE
unsupported mode -t

### ISSUE THREAD

**Issue by annaakhil** [jina-ai/jina#1537]
**while running python3 app.py -t index -n 1000 I am getting an error** 

Traceback (most recent call last):
  File "app.py", line 62, in <module>
    raise NotImplementedError(f'unsupported mode {sys.argv[1]}')
NotImplementedError: unsupported mode -t

**Environment**
jina                          0.8.2
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.32.0
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Linux
platform-release              4.19.128-microsoft-standard
platform-version              #1 SMP Tue Jun 23 12:58:10 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/akhil/.local/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)

![image](https://user-images.githubusercontent.com/49350396/103061220-aba28100-45d0-11eb-9d25-2cd790bcb519.png)

**Comment by deepankarm** [comment]
Hello @annaakhil, looks like you're trying one of the examples. Can you please point me there, so that I can take a look?

**Comment by annaakhil** [comment]
@deepankarm I am trying to do indexing for a CSV file that contains two columns when I am indexing the data by default. it is taking only 500 so the results are not good at all while doing the search so I tried indexing more docs by passing  export $MAX_DOCS=1200 but it is giving another error.
![image](https://user-images.githubusercontent.com/49350396/103066867-bdd7eb80-45df-11eb-8339-d829201b6a66.png)
so I thought of using this command python3 app.py -t index -n 1000 to index more data but getting the issue.

**Comment by deepankarm** [comment]
Please change it to `export MAX_DOCS=1200`.

From the previous error, it looks like `-t` is taken as the 1st arg, not `index`. Please let me know from where you'd picked the `app.py` file from.

**Comment by annaakhil** [comment]
@deepankarm I got when I created a new jina project using cookiecutter.

**Comment by deepankarm** [comment]
Thanks for sharing, @annaakhil. [Here's](https://github.com/jina-ai/cookiecutter-jina/tree/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D#run) how you run from a cookiecutter template.

**Comment by annaakhil** [comment]
@deepankarm thank you so much, MAX_DOCS is working now -:).
