### ISSUE TITLE
Example 'Southpark-incremental indexing' is not returning answers while quering; **ValueError('mmap length is greater than file size')**

### ISSUE THREAD

**Issue by Aaina-bajaj** [jina-ai/jina#1538]
**Describe the bug**
I tried this jina example with my demo data. it got indexed properly, but while quering, it's not returning any result.

**indexer@2355[E]:ValueError('mmap length is greater than file size')**

**Describe how you solve it**
 To index:  python3 app.py -t index
To query:  python3 app.py -t query

---

**Environment**
jina                          0.8.11
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.34.0
pyyaml                        5.3.1
python                        3.8.5
platform                      Linux
platform-release              4.19.128-microsoft-standard
platform-version              #1 SMP Tue Jun 23 12:58:10 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /usr/local/lib/python3.8/dist-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)

**Screenshots**
 Indexed files:
![image](https://user-images.githubusercontent.com/21350661/103082907-38fdc980-4601-11eb-988c-4dfc45f72a13.png)

Query result:
![image](https://user-images.githubusercontent.com/21350661/103083117-9e51ba80-4601-11eb-965d-c5d9d2f57f6c.png)

**Comment by JoanFM** [comment]
Hey @Aaina-bajaj , can u check if adding a parameter to the indexer `batch_size` to a value smaller than the number of `indexed` documents?

**Comment by JoanFM** [comment]
Hey @Aaina-bajaj , can u check with new versions if u still suffer this error?

**Comment by Aaina-bajaj** [comment]
Hey @JoanFM,
Yes, it is working correct with new version. Thank You!
