### ISSUE TITLE
Return results for asyncFlow.search

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1540]
Hey Jina team,

we've added you framework to our fastapi server. Unfortunately, one can only access the search-results via the on_done callback.
Therefore, it would be great if the results of the asyncFlow.search method would be returned directly.

This example illustrates our dilemma:
```
@router.post('/search')
def search(query: str):
    res = await asyncFlow.search_lines([query]) # should return search-result
    return res
```

**Comment by hanxiao** [comment]
i see, should be easy to fix.

**Comment by janandreschweiger** [comment]
Thank you @hanxiao!

**Comment by hanxiao** [comment]
@janandreschweiger please note that #1816 reverts #1541
