### ISSUE TITLE
test_hub_build_push_push_again is either buggy or flaky

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1542]
**Describe the bug**

FAILED tests/integration/hub_usage/test_hub_usage.py::test_hub_build_push_push_again

```
HubIO@4333[E]:Error when trying to push image jinahub/pod.encoder.dummy_mwu_encoder:0.0.6-0.8.14: TypeError("'str' object is not callable")
```

https://github.com/jina-ai/jina/pull/1541/checks?check_run_id=1610583362#step:5:7282

Plus, this skip condition looks very strangely written, how comes condition a string?

https://github.com/jina-ai/jina/blob/822d07506b7a1243532e0405d4323c1dc929508f/tests/integration/hub_usage/test_hub_usage.py#L123-L124

**Describe how you solve it**

I'm disabling this test until it is fixed.

---

**Environment**

**Screenshots**

**Comment by deepankarm** [comment]
@rutujasurve94 Thought https://github.com/jina-ai/jina/pull/1492 resolved this. Can you please take a look?

**Comment by rutujasurve94** [comment]
Hi, raised PR: https://github.com/jina-ai/jina/pull/1560 for this. Should work with this fix
