### ISSUE TITLE
async input_fn

### ISSUE THREAD

**Issue by ace-kay-law-neo** [jina-ai/jina#1543]
It would be nice if the input_fn attribute could be an async method (or generator). This is especially useful if the data is retrieved via an async library (like motor for mongodb).
```
async def input_fn():
    cursor = db.documents.find({ })
    async for entry in cursor:
        with Document() as d:
            d.text = entry["text"]
        yield d

flow.index(input_fn=input_fn)
```

**Comment by janandreschweiger** [comment]
I agree with that @ace-kay-law-neo. This feature would be helpful.

Nevertheless, I think you could iterate over the cursor syncronously with cursor.delegate.

**Comment by ace-kay-law-neo** [comment]
Thank you very much @janandreschweiger!

**Comment by ace-kay-law-neo** [comment]
I reopened this issue, because we now use purely asynchronous libraries within the input_fn.

**Comment by hanxiao** [comment]
make sense.

**Comment by hanxiao** [comment]
Hi all, I'm working on this feature, just to clarify some thoughts here.

The high-level interface is fine, but on the lower-level, we use `batch_iterator` for request generation, which fills a number of documents to each request. Hence,
- from this batch to the next batch, they are "sequential & sync".
- inside each batch, the document filing is "async"
Is that what you pictured?

**Comment by hanxiao** [comment]
@ace-kay-law-neo @janandreschweiger fyi this feature is added and rolled out in `v0.9.23`. Example: https://github.com/jina-ai/jina#asynchronous-input
