### ISSUE TITLE
Rankers cannot handle long custom ids

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#1553]
Hi Jina team,

it's awesome that you now support custom ids. We use MongoDB in combination with jina, so our id-length is 24 instead of 16.
This is a problem, because the Chunk2DocRanker and some RankDrivers assume that the id is of type np.int64.

Please have a look:
- https://github.com/jina-ai/jina/blob/bf97c36ba65c08f620d504ed556ca508fdf2368f/jina/executors/rankers/__init__.py#L92
- https://github.com/jina-ai/jina/blob/bf97c36ba65c08f620d504ed556ca508fdf2368f/jina/drivers/rank/aggregate/__init__.py#L201-L203

An update that fixes our error would be awesome.
```
OverflowError: Python int too large to convert to C long
```

**Comment by nero-nazok** [comment]
Hi @janandreschweiger!
I also want to use MongoDB, so this issue is of interest to me. In order to really support custom-ids the type should be changed to np.object.

**Comment by janandreschweiger** [comment]
I prototyped a custom AggregateMatches2DocRankDriver and SimpleAggregateRanker that overcome this issue by:
- changing np.int64 to np.object
- changing the id-conversion from int() to str()

```
import numpy as np
from collections import defaultdict, namedtuple
from jina.drivers.rank.aggregate import AggregateMatches2DocRankDriver
from jina.executors.rankers import Chunk2DocRanker
from jina.types.document import Document
from jina.types.score import NamedScore

# EXECUTOR
class CustomSimpleAggregateRanker(Chunk2DocRanker):
    """
    :class:`SimpleAggregateRanker` aggregates the score of the matched doc from the matched chunks.
    For each matched doc, the score is aggregated from all the matched chunks belonging to that doc.
    """
    @staticmethod
    def sort_doc_by_score(r):
        """
        Sort a list of (``doc_id``, ``score``) tuples by the ``score``.
        :return: an `np.ndarray` in the shape of [N x 2], where `N` in the length of the input list.
        """
        r = np.array(r, dtype=[
            (Chunk2DocRanker.COL_MATCH_PARENT_HASH, np.object),
            (Chunk2DocRanker.COL_SCORE, np.float64)]
                     )
        return np.sort(r, order=Chunk2DocRanker.COL_SCORE)[::-1]

    AGGREGATE_FUNCTIONS = ['min', 'max', 'mean', 'median', 'sum', 'prod']

    def __init__(self, aggregate_function: str, is_reversed_score: bool, *args, **kwargs):
        """
        :param: aggregate_function: defines the used aggregate function and can be one of:
        [min, max, mean, median, sum, prod]
        :param: is_reverse_score: True if a large score of the matched chunks mean a lower score of the matched doc,
        othewise: False
        """
        super().__init__(*args, **kwargs)
        self.is_reversed_score = is_reversed_score
        if aggregate_function in self.AGGREGATE_FUNCTIONS:
            self.np_aggregate_function = getattr(np, aggregate_function)
        else:
            raise ValueError(f'The aggregate function "{aggregate_function}" is not in "{self.AGGREGATE_FUNCTIONS}".')

    def _get_score(self, match_idx, query_chunk_meta, match_chunk_meta, *args, **kwargs):
        scores = match_idx[self.COL_SCORE]
        aggregated_score = self.np_aggregate_function(scores)
        if self.is_reversed_score:
            if aggregated_score == -1:
                raise ValueError(f'Setting "is_reversed_score" to True does not allow to have an aggregated document '
                                 f'score of -1.')
            aggregated_score = 1. / (1. + aggregated_score)
        return self.get_doc_id(match_idx), aggregated_score

# DRIVER
class CustomAggregateMatches2DocRankDriver(AggregateMatches2DocRankDriver):
    def _extract_query_match_info(self, match: Document, query: Document):
        return self.QueryMatchInfo(match_parent_id=str(match.parent_id),
                                   match_id=str(match.id),
                                   query_id=str(query.id),
                                   score=match.score.value)
    
    def _apply_all(self, docs: 'DocumentSet', context_doc: 'Document', *args, **kwargs) -> None:
        if context_doc is None:
            return

        match_idx = []
        query_meta = {}
        match_meta = {}
        parent_id_chunk_id_map = defaultdict(list)
        matches_by_id = defaultdict(Document)
        query_meta[str(context_doc.id)] = context_doc.get_attrs(*self.exec.required_keys)
        for match in docs:
            match_info = self._extract_query_match_info(match=match, query=context_doc)
            match_idx.append(match_info)
            match_meta[str(match.id)] = match.get_attrs(*self.exec.required_keys)
            parent_id_chunk_id_map[str(match.parent_id)].append(str(match.id))
            matches_by_id[str(match.id)] = match

        if match_idx:
            match_idx = np.array(match_idx,
                dtype=[
                    (Chunk2DocRanker.COL_MATCH_PARENT_HASH, np.object),
                    (Chunk2DocRanker.COL_MATCH_HASH, np.object),
                    (Chunk2DocRanker.COL_DOC_CHUNK_HASH, np.object),
                    (Chunk2DocRanker.COL_SCORE, np.float64)
                ])

            docs_scores = self.exec_fn(match_idx, query_meta, match_meta)
            # This ranker will change the current matches
            context_doc.ClearField('matches')
            self._insert_query_matches(query=context_doc,
                parent_id_chunk_id_map=parent_id_chunk_id_map,
                chunk_matches_by_id=matches_by_id,
                docs_scores=docs_scores)
```
Although this works, it would be great if a jina developer with more experience could fix it.

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

Would it be possible to have a PR with these changes?

It could be a good way to discuss the changes? and maybe we can agree to merge it?

**Comment by janandreschweiger** [comment]
I agree with you @JoanFM. I will open a PR.

**Comment by nero-nazok** [comment]
Thanks @JoanFM and @janandreschweiger for fixing it!

**Comment by JoanFM** [comment]
Hey @janandreschweiger,

Thanks for the contribution!.If it is okey, I will wait for next week before merging, to have some colleagues that were heavily involved with the redesign of DocumentID to have a better thought about this.

**Comment by janandreschweiger** [comment]
Sure @JoanFM take the time you need. I just want that this issue is solved in one or the other way.

**Comment by ace-kay-law-neo** [comment]
Hm, this is problem is bugging us for four days now. If it takes another week, we'll use the prototype you posted above in the mean time.

**Comment by maximilianwerk** [comment]
Hey, @janandreschweiger @ace-kay-law-neo 

after discussing it several times internally, here are our findings: We will not be able to allow arbitrary lengths custom ids for now. The reason for that is, that our indexers (and probably more parts of our code) heavily rely on ids, which fits into `int64` for performance reasons. Regarding your problem with the ranker, we see, that we do not fit yet your requirements and will take fixing this into our roadmap. We are well aware, that the Rankers are not yet perfectly designed and will address this in the future. As a concrete suggestion for your problem:

You could either use a hash function to get ids of a good size (e.g. `Document(id=hash(mongo_id), tags={'mongo_id': mongo_id})`) and remember this hash outside. Another probably preferable solution is: You can just C&P our `Chunk2DocRanker` and adapt the `group_by_doc_id` function to take the `query_chunk_meta` or `match_chunk_meta` instead of the given column in the `match_idx` array.

As I said above, we see your use case and are happy to integrate it into our future refactoring of Rankers. Anyhow, I cannot yet give you any time estimations.

@lusloher FYI

**Comment by geraldwinkler** [comment]
Hey @maximilianwerk and @JoanFM, I have the same problem.
I will go with @janandreschweiger`s solution for now. When do you think that this issue will be resolved? (e.g. two weeks, a month)

**Comment by maximilianwerk** [comment]
> Hey @maximilianwerk and @JoanFM, I have the same problem.
> I will go with @janandreschweiger`s solution for now. When do you think that this issue will be resolved? (e.g. two weeks, a month)

Hey @lsgrep @janandreschweiger @ace-kay-law-neo 

I spend some time this week, refactoring the code and am almost finished enabling longer `ids` for good. You can expect the feature to be merged during the next week.

Cheers and have a wonderful weekend!

**Comment by maximilianwerk** [comment]
The feature is merged to master. We simplified the `id` concept again and you should be able to use arbitrary `id` length now. Anyhow, there is one catch: In the first batch of documents you index, you should already provide ids of the wished `max_length` that you will use. Otherwise, the indexers will expect max length to be 16 chars (or whatever is the maximum `id` length in your first batch).

I will close this issue. We would be happy about feedback on this solution.
