### ISSUE TITLE
PR#1361 test is misleading, reverting

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1575]
**Describe the bug**

This test is misleading as `HubIO._test_build` does not accept image as `str`

```python
image, log = self._client.images.build(...)
```

Please read Docker SDK carefully and please notice that:

> The first item is the :py:class:`Image` object ...

Mentioned here: https://github.com/jina-ai/jina/pull/1361#pullrequestreview-560556769

Based on this questionable test, I worry about the effectiveness of PR#1361

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
In #1539 I removed the test introduced by #1361 as it didn't test properly - rthe test itself is buggy. Please clarify the purpose of #1361  and redesign the test. @rutujasurve94

**Comment by rutujasurve94** [comment]
Redesigning this test, updating on this issue thread.
