### ISSUE TITLE
jina hub list gives 600+ hub images?

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1585]
**Describe the bug**

On `master`, do `jina hub list`
![image](https://user-images.githubusercontent.com/2041322/103531120-fe115680-4e88-11eb-92b3-1b5bfb429e3a.png)

Quite some duplicated names there.

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by cristianmtr** [comment]
This is probably due to the different versions available for every module, as part of the Hub Updater work. These should be listed with just the last version only. 

@rutujasurve94 Does the new Hub API support searching/filtering in this way?
