### ISSUE TITLE
chunk error

### ISSUE THREAD

**Issue by annaakhil** [jina-ai/jina#1590]
**Describe the bug**
Getting an error in chunk  while running index command 

**Environment**
0.8.2
akhil@DESKTOP-PCQSBOH:~/experiment2$ jina --version-full
jina                          0.8.2
jina-proto                    0.0.76
jina-vcs-tag                  (unset)
libzmq                        4.3.3
pyzmq                         1.19.4
protobuf                      3.14.0
proto-backend                 cpp
grpcio                        1.32.0
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Linux
platform-release              4.19.128-microsoft-standard
platform-version              #1 SMP Tue Jun 23 12:58:10 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /home/akhil/.local/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DB_COLLECTION            (unset)
JINA_DB_HOSTNAME              (unset)
JINA_DB_NAME                  (unset)
JINA_DB_PASSWORD              (unset)
JINA_DB_USERNAME              (unset)
JINA_DEFAULT_HOST             (unset)
JINA_DISABLE_UVLOOP           (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_CONFIG               (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_RANDOM_PORTS             (unset)
JINA_SOCKET_HWM               (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_WARN_UNNAMED             (unset)

**Screenshots**
![image](https://user-images.githubusercontent.com/49350396/103607982-42136280-4f40-11eb-8317-1cd13aa76483.png)

**Comment by nan-wang** [comment]
hi, @annaakhil Would you please provide more details about your usage? How does your flow look like?
