### ISSUE TITLE
executors from Jina hub are not included at docs.jina.ai

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1607]
**Describe the bug**
executors from Jina hub are not included at docs.jina.ai

FYI, The list of hub images are listed in 
https://github.com/jina-ai/jina/blob/master/docs/chapters/all_exec.md 

During cd, this is created by
https://github.com/jina-ai/jina/blob/master/.github/workflows/cd.yml#L43

This is different from the https://docs.jina.ai/_modules/index.html, which is generated by sphinx.

When building the docs, the submodules are included
https://github.com/jina-ai/jina/blob/master/docs/conf.py#L6
https://github.com/jina-ai/jina/blob/master/.github/workflows/cd.yml#L24

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
i removed them intentionally. Because hub docstrings are at very low quality in general

**Comment by nan-wang** [comment]
https://jinaai.slack.com/archives/C018QC78L84/p1609917102129800

> the best way to put it is separating the Hub autodocs from the core autodocs into two sections, without messing up the core's docs quality. I'm sure it can be done. But I couldn't find a solution in short time. Will mark it as an issue on GH
