### ISSUE TITLE
content hash should be computed from list of fields and not based on removing fields from computation

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1615]
In the same way allowlists are encouraged in security, it is more stable and robust to keep a positive logic of the fields to be included in the content hash computation

**Comment by hanxiao** [comment]
we have this feature before, seems get removed during refactoring?

https://github.com/jina-ai/jina/blob/00ea808dd951ed350f2e8c27d1fdcffc3470da77/jina/proto/uid.py#L36-L49

**Comment by JoanFM** [comment]
> we have this feature before, seems get removed during refactoring?
> 
> https://github.com/jina-ai/jina/blob/00ea808dd951ed350f2e8c27d1fdcffc3470da77/jina/proto/uid.py#L36-L49

Before we had a mask to exclude, I mean a mask to include, more mantainable .

**Comment by hanxiao** [comment]
then, i suggest add both `include, exclude` as args.

**Comment by JoanFM** [comment]
> then, i suggest add both `include, exclude` as args.

that would be ambiguous

**Comment by hanxiao** [comment]
it will not
