### ISSUE TITLE
Separate Segmenter from Crafter

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1618]
**Describe the feature**
Have `BaseSegmenter` not inherit from `BaseCrafter` and change its method from `craft` to `segment`

**WARNING**
This can affect examples and hub executors. Hub executors structure must be adapted

checklist:
- [x] a cartoon character for Segmenter is missing, @design_team
- [x] Jina 101 does not cover it, @pswu11 plan to rewrite before 1.0, so please inform @pswu11  about this new component
- [x] Jina hub new 's dependent cookiecutter should be updated to reflect this (https://github.com/jina-ai/cookiecutter-jina-hub/pull/4)
- [x] Jina Hub repo's file structure should be updated to reflect this (Done)
- [x] Doc needs to reflect that as well.
- [x] Jina examples need to be changed accordingly

**Comment by FionnD** [comment]
@alexcg1  @pswu11 I'm guessing all the remaining tasks are on your team side? If so can you close the issue, please?

**Comment by pswu11** [comment]
@FionnD 

- for the cartoon - it's on me 
- for Jina 101, it's on me
- for reflecting on docs.jina.ai (except for Jina 101), I believe it's on the Engineering team or? @alexcg1 
- examples @alexcg1 do you know who is the owner?

**Comment by JoanFM** [comment]
In examples is being taken care for

**Comment by alexcg1** [comment]
1. @JoanFM what example is segmenter being used for?
2. Re docs.jina.ai, I believe @FionnD is taking point on overall structure, while @jina-ai/engineering handle individual docs

**Comment by JoanFM** [comment]
> 1. @JoanFM what example is segmenter being used for?
> 2. Re docs.jina.ai, I believe @FionnD is taking point on overall structure, while @jina-ai/engineering handle individual docs

In `multires`

**Comment by FionnD** [comment]
I can't see any point in the current docs that will need to be updated to reflect this. If anyone notices something I've missed please let me know.

**Comment by pswu11** [comment]
@FionnD

**Comment by pswu11** [comment]
@FionnD 

For example here: 
https://docs.jina.ai/_modules/jina/executors/crafters.html#BaseCrafter.craft
in the comments of BaseCrafter it mentioned that 
```
It can be used for preprocessing,
    segmenting etc.
```
since it's now separated so no more segmenting here?

And here https://docs.jina.ai/_modules/jina/executors/segmenters.html#BaseSegmenter.segment
`the :func:craft here works on doc-level info` <= maybe the function name is wrong here?
