### ISSUE TITLE
Cannot uninstall PyYAML

### ISSUE THREAD

**Issue by FionnD** [jina-ai/jina#1621]
**Describe the bug**
For a user installing Jina who already have PyYAML installed (this is a default library installed in conda environments), Jina will fail to install and throw the following error. 

`Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

This occurs because pip attempts to uninstall PyYAML before it updates and reinstalls. However, uninstalling a distutisl package is no longer supported since pip 10. ([Reference](https://stackoverflow.com/questions/49911550/how-to-upgrade-disutils-package-pyyaml)) 

A current solution is to use 
`pip install jina --ignore-installed`

**Describe how you solve it**
To be done. A solution in the requirement file to only update and not reinstall is required. 

---

**Environment**
Jina 0.9.2
Python 3.7.3
Conda 4.6.11

**Screenshots**

**Comment by hanxiao** [comment]
This issue is here for SEO purpose. @nan-wang do not count this as an engineering-work in the Sprint, this looks out of the scope, it is either conda, pip, or PyYAML related, not really jina.

**Comment by FionnD** [comment]
Update: 
After trying this again, it no longer seems to be an issue. 

If someone has anaconda, please see if you can install Jina successfully and let us know here!
