### ISSUE TITLE
use `.name` for retrieving the executors' name

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1634]
```suggestion
                evaluation.op_name = f'{self.exec.name}@{self.exec.eval_at}'
            else:
                evaluation.op_name = self.exec.name
```

I think we can simply use `.name` attribute of the executor - one of the `metas` attribute of any `Executor`. Also, since `eval_at` is kind of `BaseRankingEvaluator` specific, the `BaseRankingEvaluator` could just have the following somewhere in `__init__` of `post_init`:

```
if self.eval_at:
   self.name += f`@{self.eval_at}`
```

_Originally posted by @hanxiao in https://github.com/jina-ai/jina/pull/1623#discussion_r553503135_

**Comment by JoanFM** [comment]
I would not apply this change, changing the `self.name` dynamically, makes it hard to have a logic where drivers relate to executor by name

**Comment by nan-wang** [comment]
fair point.
