### ISSUE TITLE
when using `WebSocketClient`, `Flow().add().add(needs='gateway')` hangs forever

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1638]
**Describe the bug**

originally from #1551 

when using `WebSocketClient`, the following flow fails `Flow().add().add(needs='gateway')` by hanging forever.

Minimum example:
```python
from jina import Flow, Document

f = Flow(restful=True).add().add(needs='gateway').needs_all()
with f:
    f.index([Document()])
```

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by nan-wang** [comment]
In `1.0.5`, this bug can't be reproduced.
