### ISSUE TITLE
jina hub list is broken

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1641]
**Describe the bug**

`jina hub list` gives

```
          HubIO@34558[I]:searching...
          HubIO@34558[E]:unknown error: Bad Gateway
          HubIO@34558[I]:searching takes 3 seconds (3.49s)
```

**Describe how you solve it**

Please revert `pytest.skip` in `tests/unit/docker/test_hub_list.py` after the fix

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
the url to access is down.

https://hubapi.jina.ai

**Comment by hanxiao** [comment]
@nan-wang this is considered as `uptime`/reliability/SLA, can you please note it? So the next we have this uptime discussion, we know what are we talking about

**Comment by deepankarm** [comment]
https://github.com/jina-ai/cloud-ops/pull/54 fixed this.

**Comment by JoanFM** [comment]
> [jina-ai/cloud-ops#54](https://github.com/jina-ai/cloud-ops/pull/54) fixed this.

@deepankarm can u do a PR reactivating the hub list tests?

**Comment by deepankarm** [comment]
> > [jina-ai/cloud-ops#54](https://github.com/jina-ai/cloud-ops/pull/54) fixed this.
> 
> @deepankarm can u do a PR reactivating the hub list tests?

@JoanFM I'll re-enable the tests once https://github.com/jina-ai/jina/issues/1585 gets fixed.
