### ISSUE TITLE
`logstream` endpoint does not generate ReDoc

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1643]
**Describe the bug**

Upstream issue: https://github.com/tiangolo/fastapi/issues/1983

Affected `daemon/api/endpoints/logs.py`:
```python
router.add_websocket_route(path='/logstream/{log_id}',
                           endpoint=LogStreamingEndpoint)
```

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by deepankarm** [comment]
Possible solution - 
https://www.asyncapi.com/
