### ISSUE TITLE
remove 'meta_info' from DocumentProto

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1647]
**Describe the feature**
meta_info was deprecated time ago but was not yet removed

**Comment by hanxiao** [comment]
just a note, simple deletion is enough, no need for shifting all index by `-1`. It's in fact considered as the best practice not to change the offset of protobuf, as the offset is used for back&forward-compatability
```proto
    // some binary meta information of this Doc in bytes
    bytes meta_info = 7;
```
