### ISSUE TITLE
install jina[nlp] error 

### ISSUE THREAD

**Issue by conanchen** [jina-ai/jina#1659]
**Describe the bug**
install error 

pip3 install "jina[nlp]"

**Describe how you solve it**

**Environment**
$ python3 --version
Python 3.8.7

$ pip3 install "jina[nlp]"

**Screenshots**
Collecting sentencepiece<=0.1.91
  Using cached sentencepiece-0.1.90-cp38-cp38-macosx_10_6_x86_64.whl (1.0 MB)
  Using cached sentencepiece-0.1.86-cp38-cp38-macosx_10_6_x86_64.whl (1.0 MB)
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/56/7z40q2wn3s3gmffsvlj1h81c0000gp/T/pip-install-bbu64z3q/sentencepiece_57f19d9c3f94464f87f828681ea74f15/setup.py'"'"'; __file__='"'"'/private/var/folders/56/7z40q2wn3s3gmffsvlj1h81c0000gp/T/pip-install-bbu64z3q/sentencepiece_57f19d9c3f94464f87f828681ea74f15/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/56/7z40q2wn3s3gmffsvlj1h81c0000gp/T/pip-pip-egg-info-pqicg_qm
         cwd: /private/var/folders/56/7z40q2wn3s3gmffsvlj1h81c0000gp/T/pip-install-bbu64z3q/sentencepiece_57f19d9c3f94464f87f828681ea74f15/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/56/7z40q2wn3s3gmffsvlj1h81c0000gp/T/pip-install-bbu64z3q/sentencepiece_57f19d9c3f94464f87f828681ea74f15/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nan-wang** [comment]
hi, there. It seems out of the scope of `jina`. Is this ticket related to your case? https://github.com/google/sentencepiece/issues/386
