### ISSUE TITLE
Flow termination in jinad is really slow

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#1661]
**Describe the bug**
For a remote Flow with multiple remote Pods, when a **DELETE** request is sent to terminate a Flow, it takes a lot of time (at times ~20secs)

**Describe how you solve it**
This happens as the log-streaming (both server & client) don't get cancelled properly. Can create serious implications when Console consumes it. 

---

**Comment by hanxiao** [comment]
From what you described ~20s, I think it is because the terminate signal is not properly handled, hence fallback to 5s `timeout_ctrl`. Each Pod takes 5s, so 20s I guess you have 4 pods (include gateway).

**Comment by deepankarm** [comment]
`JinadRuntime` doesn't use `send_ctrl_message` to send terminate signal. It sends  a **/DELETE POD** request. The issue is with the logging endpoint as the websocket server is in a `forever sending mode` until a timeout. My guess is, client disconnection needs to be handled properly.
