### ISSUE TITLE
save_config not working for `TransformerTorchEncoder`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#1670]
**Describe the bug**
Tests fail for https://github.com/jina-ai/jina-hub/pull/2158 due to some problems when dumping this executor with `JAML`

**Comment by JoanFM** [comment]
This is very weird, because it seems to appear in hub builds but not to be consistent

**Comment by tadejsv** [comment]
@JoanFM, I came to the bottom of this. The problem appears here

https://github.com/jina-ai/jina/blob/321a890ba85cb8c0266b239bc0e7ea34bccf7ae0/jina/executors/__init__.py#L58-L73

See the line 65 there? Well, what happens is the following: by the time the **local** `TransformerTorchEncoder` is imported (and thus registered), then **jina package** `TransformerTorchEncoder` has already been imported, and thus registered. This means that `'TransformerTorchEncoder'` in `reg_cls_set`, and this the whole if statement will be skipped - leading to `store_init_kwargs` args not getting saved, and this not being part of the yaml dump.

Can you take it from here? One way to fix it would be to remove the if statement, but I am not sure this has any wider consequences, so I would prefer someone other than me do this PR.

PS: The statement is also not getting executed on the following two executors: `TransformEncoder` and `ChromaPitchEncoder`. I have checked and there are in fact two different executors with the same class name in the code.

**Comment by tadejsv** [comment]
PS: you can consistently reproduce the problem with the code from #1527 , just replace `TransformerTFEncoder` with `TransformerTorchEncoder`

**Comment by tadejsv** [comment]
Also, in local testing I can confirm that replacing the line 65 with `if True:` fixes the problem.

**Comment by JoanFM** [comment]
> @JoanFM, I came to the bottom of this. The problem appears here
> 
> https://github.com/jina-ai/jina/blob/321a890ba85cb8c0266b239bc0e7ea34bccf7ae0/jina/executors/__init__.py#L58-L73
> 
> See the line 65 there? Well, what happens is the following: by the time the **local** `TransformerTorchEncoder` is imported (and thus registered), the **jina package** `TransformerTorchEncoder` has already been imported, and thus registered. This means that `'TransformerTorchEncoder'` is already in `reg_cls_set`, and this the whole if statement will be skipped - leading to `store_init_kwargs` args not getting saved, and this not being part of the yaml dump.
> 
> Can you take it from here? One way to fix it would be to remove the if statement, but I am not sure this has any wider consequences, so I would prefer someone other than me do this PR.
> 
> PS: The statement is also not getting executed on the following two executors: `TransformEncoder` and `ChromaPitchEncoder`. I have checked and there are in fact two different executors with the same class name in the code.

Really appreciate it, will take from here!!!
