### ISSUE TITLE
_check_on_gpu method of BaseExecutor does not properly check for GPU.

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#1672]
Here's the method in question:

https://github.com/jina-ai/jina/blob/d40aee59615b34e39a8dbad538f50343d2bed46e/jina/executors/__init__.py#L129-L137

This method checks for `nvcc`, which is the CUDA compiler. However, in a lot of cases, only prebuilt CUDA binaries are installed, without the compiler. In fact, this is the case for the recommended way of installing pytorch. Say you have this image

``` dockerfile
FROM continuumio/miniconda3 AS conda

RUN conda install pytorch cudatoolkit=11.0 -c pytorch

FROM nvidia/cuda:11.0-base-ubuntu20.04

# Prepare shell and file system
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 SHELL=/bin/bash
ENV PATH /opt/conda/bin:$PATH
SHELL ["/bin/bash", "-c"]

# Copy over conda and bashrc, install environment
COPY --from=conda /opt/ /opt/
RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc
```

Here, executing `nvcc --version` will return nothing. However, this image has a perfectly working CUDA installation, as you can see
``` python
>>> import torch
>>> torch.cuda.is_available()
True
```

## Solution

I propose one of two things:
- Replace `['nvcc', '--version']` with `['nvidia-smi']`. This can cause "false positives" - i.e. user uses base CUDA image and forgets to install CUDA. But that's his mistake, and he will spot it easily when torch/tf complains no CUDA is available ;) Better than the current situation when the user is prevented from using a working CUDA installation
- Remove this check entirely. More or less the same reason as above - I mean if user wants to use a GPU it's his responsibility to ensure things work, and error from DL packages will make it clear that CUDA is missing

**Comment by JoanFM** [comment]
> Here's the method in question:
> 
> https://github.com/jina-ai/jina/blob/d40aee59615b34e39a8dbad538f50343d2bed46e/jina/executors/__init__.py#L129-L137
> 
> This method checks for `nvcc`, which is the CUDA compiler. However, in a lot of cases, only prebuilt CUDA binaries are installed, without the compiler. In fact, this is the case for the recommended way of installing pytorch. Say you have this image
> 
> ```dockerfile
> FROM continuumio/miniconda3 AS conda
> 
> RUN conda install pytorch cudatoolkit=11.0 -c pytorch
> 
> FROM nvidia/cuda:11.0-base-ubuntu20.04
> 
> # Prepare shell and file system
> ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 SHELL=/bin/bash
> ENV PATH /opt/conda/bin:$PATH
> SHELL ["/bin/bash", "-c"]
> 
> # Copy over conda and bashrc, install environment
> COPY --from=conda /opt/ /opt/
> RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
>     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
>     echo "conda activate base" >> ~/.bashrc
> ```
> 
> Here, executing `nvcc --version` will return nothing. However, this image has a perfectly working CUDA installation, as you can see
> 
> ```python
> >>> import torch
> >>> torch.cuda.is_available()
> True
> ```
> 
> ## Solution
> I propose one of two things:
> 
> * Replace `['nvcc', '--version']` with `['nvidia-smi']`. This can cause "false positives" - i.e. user uses base CUDA image and forgets to install CUDA. But that's his mistake, and he will spot it easily when torch/tf complains no CUDA is available ;) Better than the current situation when the user is prevented from using a working CUDA installation
> * Remove this check entirely. More or less the same reason as above - I mean if user wants to use a GPU it's his responsibility to ensure things work, and error from DL packages will make it clear that CUDA is missing

I would definitely agree on the second, let the responsibility on user side

**Comment by florian-hoenicke** [comment]
Thanks a lot for finding this. The current implementation prevents some users from using gpu in their environment.
The first solution has no false negatives (does not prevent users from using gpu who can use gpu) but has some true negatives which is helpful.
