### ISSUE TITLE
TypeError('zip argument #2 must support iteration')

### ISSUE THREAD

**Issue by yiouyou** [jina-ai/jina#1684]
**Describe the bug**

Here is what I've done to modify the "[jina-wikipedia-sentences](https://github.com/alexcg1/jina-wikipedia-sentences)" example, and try to apply it from English to Chinese:

1. Change the requirements.txt to add paddlehub and paddlepaddle
```
jina[devel,torch,hub]==0.9.0
transformers==3.5.1
kaggle==1.5.10
paddlehub==1.7.1
paddlepaddle==1.8.5
```

2. Change encode.yml to TextPaddlehubEncoder, and try to choose chinese-roberta-wwm-ext-large model
```
!TextPaddlehubEncoder
with:
  model_name: chinese-roberta-wwm-ext-large
```

3. Prepared some Chinese text data
```
[zh-input_20.txt](https://github.com/jina-ai/jina-hub/files/5810429/zh-input_20.txt)
```

4. 'python app.py index' is done successfully

5. However, 'python app.py search' meets some error when search some Chinese words in example.html:

![image](https://user-images.githubusercontent.com/14249712/104493769-7f4ab500-5610-11eb-8819-a239f4996a4e.png)

Any idea why?

Thanks!
**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
I think the problem is about `hub` submodule having still old crafters

**Comment by JoanFM** [comment]
> **Describe the bug**
> 
> Here is what I've done to modify the "[jina-wikipedia-sentences](https://github.com/alexcg1/jina-wikipedia-sentences)" example, and try to apply it from English to Chinese:
> 
> 1. Change the requirements.txt to add paddlehub and paddlepaddle
> 
> ```
> jina[devel,torch,hub]==0.9.0
> transformers==3.5.1
> kaggle==1.5.10
> paddlehub==1.7.1
> paddlepaddle==1.8.5
> ```
> 
> 1. Change encode.yml to TextPaddlehubEncoder, and try to choose chinese-roberta-wwm-ext-large model
> 
> ```
> !TextPaddlehubEncoder
> with:
>   model_name: chinese-roberta-wwm-ext-large
> ```
> 
> 1. Prepared some Chinese text data
> 
> ```
> [zh-input_20.txt](https://github.com/jina-ai/jina-hub/files/5810429/zh-input_20.txt)
> ```
> 
> 1. 'python app.py index' is done successfully
> 2. However, 'python app.py search' meets some error when search some Chinese words in example.html:
> 
> ![image](https://user-images.githubusercontent.com/14249712/104493769-7f4ab500-5610-11eb-8819-a239f4996a4e.png)
> 
> Any idea why?
> 
> Thanks!
> **Describe how you solve it**
> 
> **Environment**
> 
> **Screenshots**

Hey @yiouyou , can u try if this also happens with version 0.9.13?

**Comment by JoanFM** [comment]
Hey @yiouyou , can you let me know how many documents you are indexing and how many `shards` are you using?

**Comment by yiouyou** [comment]
The problem seems go way by adding more documents.

**Comment by JoanFM** [comment]
> The problem seems go way by adding more documents.

Even with the small amount of documents #1689 should have fixed this, you are welcome to try with the latest version

**Comment by yiouyou** [comment]
"TypeError('zip argument #2 must support iteration')" It showed up again. I'm using 400 song's lyrics now. The detail steps are listed  in https://github.com/jina-ai/examples/issues/350
