### ISSUE TITLE
missing docs/usage for `force_register`

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1709]
**Describe the feature**

When user tries to override an executor class from the core/hub, it must use `force_register=True` as the class attribute.
Example: `tests/unit/test_exectype.py`

Nowhere in the docs.jina.ai speaks about it.

original issue from here: https://github.com/jina-ai/jina-hub/pull/295#issuecomment-683279092
solved in here: https://github.com/jina-ai/jina/pull/883
mentioned in 0.6 release note here: https://github.com/jina-ai/jina/issues/997

Could be related to #1702 #1527 

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by tadejsv** [comment]
I think a better solution than `force_register` would be to register components with the full path (as done in #1702 ), and then the user can explicitly use the custom components in the flow.

**Comment by JoanFM** [comment]
I agree with @tadejsv , In the PR #1702 I do not remove the `force_register` but it may be unnecessary if using the complete module + name as qualified id.

As seen in #1527 this is a problem with actual hub executors and not only by overriding classes
