### ISSUE TITLE
Error in basic-feed-data

### ISSUE THREAD

**Issue by FionnD** [jina-ai/jina#1736]
Reproduced both on binder and locally. 

Third cell of the notebook fails on this error: 

`FlowBuildLevelError: build_level check failed for <function BaseFlow._get_client at 0x7fda41803700>, required level: 1, actual level: 0`

FYI, I would like to know the background to this issue for who ever fixes it!

**Comment by nan-wang** [comment]
@FionnD Would you please specify which code block is broken?

**Comment by FionnD** [comment]
Sorry @nan-wang I should have added more info. 

Using this [notebook ](https://mybinder.org/v2/gh/jina-ai/jupyter-notebooks/main?filepath=basic-feed-data.ipynb), the final cell (third) throws the error I pasted above. Do you also have this issue?

**Comment by cristianmtr** [comment]
I ran that. This fixed it

```
with f:
    f.index_lines(['hello world!', 'goodbye world!'])  # index textual data, each element is a document
```

**Comment by cristianmtr** [comment]
Is this notebook provided in Jina somewhere, so I can fix that cell?

**Comment by nan-wang** [comment]
> Is this notebook provided in Jina somewhere, so I can fix that cell?

@cristianmtr Thanks for helping out on this!
Here is the todo list

- [ ] Fix the notebook at https://github.com/jina-ai/jupyter-notebooks/blob/main/basic-feed-data.ipynb
- [ ] Fix the readme at https://github.com/jina-ai/jina/blob/master/README.md#feed-data
