### ISSUE TITLE
How can I obtain the indexing and searching time programmatically?

### ISSUE THREAD

**Issue by antoniolanza1996** [jina-ai/jina#1750]
**Describe your proposal/problem**
Hey folks, I usually read the indexing and searching time directly on my terminal when the Flow is running. However, can I "capture" the value (e.g. `50.21s` in the screenshot below) with an async callback and handle by myself for further processing?

**Screenshots**
![Schermata 2021-01-21 alle 18 43 46](https://user-images.githubusercontent.com/40452030/105389835-9db83e00-5c18-11eb-960d-9756d0ef8fb2.png)

**Comment by JoanFM** [comment]
Hello @antoniolanza1996 ,

Do you want to handle it at  `request` level or at `document` level? 

If you want control at `request` level, you can read from the response the `routes` from the `messages` envelopes, and add them up (these routes express the Pods a `request` passes through).

If you want to have the control at `document` level, you can add a `tag` with the timestamp when generating the document and compare the timestamp when getting it back.

```python
with Flow.load_config('flow.yml') as f:
    f.index(input_fn=input_generator(), on_done=callback_computing_time)
```

**Comment by antoniolanza1996** [comment]
Thanks. I've noted that the value printed on terminal is computed like:
```python
def callback_computing_time(resp):
  gateway_info = resp.to_json()['routes'][0]
  seconds = gateway_info['endTime']-gateway_info['startTime'] #clearly after date conversion
```
This is what you call `request` level, isn't it?

And what do you mean with document level? How can I use a `tag` in Jina?

**Comment by JoanFM** [comment]
Hey @antoniolanza1996 ,

Yes, this is the `request` level I talk about, however I think the `first` route only talks about the first time the `gateway` receives request.

Maybe it can make more sense to do:

```python
routes  = resp.to_json()['routes']
start = routes[0]['startTime']
end = routes[-1]['endTime']
```

As for the documents, what you could do is:

```python
from jina import Document
def input_generator():
   with Document() as d:
       d.(text, blob, buffer) = your data 
       d.tags['fireTime'] = time.now()
   yield d

def callback_computing_time(resp):
     for doc in resp.(search, index).docs:
        start = doc.tags['fireTime']
        end = time.now()
```

This second one may not be purely accurate as per Jina system itself, but it could account for the time a document is waiting to be fetched by the Flow.

I hope this helps!

**Comment by antoniolanza1996** [comment]
Hey @JoanFM ,
make sense what you are calling `document` level. Thank you for the snippet of code.

About `request` level, yesterday I've noted that `routes[-1]` has only `startTime` and it was equal to `routes[0]['endTime']`. However, with the same code of yesterday, `resp.to_json()` now throws an error:
`jina.excepts.BadClientCallback: uncaught exception in callback print_on_done(): AttributeError("'NoneType' object has no attribute 'DESCRIPTOR'")`

I'm trying to figure out where is the problem, but I didn't change the request in `index_lines` function. Is there another strategy to obtain `routes` array?

**Comment by JoanFM** [comment]
Would `resp.routes` work?

**Comment by antoniolanza1996** [comment]
It works, but `resp.routes` is a `google.protobuf.pyext._message.RepeatedCompositeContainer` and I've to deserialise it in JSON format to work with.

Following your [implementation](https://github.com/jina-ai/jina/blob/master/jina/types/request/__init__.py#L186), `MessageToJson(resp.routes)` continues to throw an error. Thus, I've tried:
```python
from google.protobuf.json_format import MessageToDict
jsonObj = MessageToDict(resp)
```
and it seems to work. If this error persists with your `to_json()` abstraction, probably you may consider switching `MessageToJson` with `MessageToDict`.
