### ISSUE TITLE
Hub builds broken

### ISSUE THREAD

**Issue by tadej-redstone** [jina-ai/jina#1777]
It seems that hub builds are broken (see [here](https://github.com/jina-ai/jina-hub/pull/2773) for example), and the error seems to be related to #1732. I suspect that there's some problem with label encoding to strings (some special characters such as `). But this needs to be checked - unfortunately with the current error reporting the whole stack is not printed.

Broadly, this shows two more issues:
- testing needs to be updated, because neither unit nor integration PR caught this
- error reporting needs to be improved, because without seeing the whole stack it is not possible to pinpoint the issue in some cases.

**Comment by JoanFM** [comment]
hey @tadej-redstone , let's first revert #1732 and then try to see how the problem can be better solved?

**Comment by tadej-redstone** [comment]
I think first it should be checked what the problem is. You can go ahead and revert, but the final solution will still probably involve the same design (passing labels to docker sdk)

**Comment by JoanFM** [comment]
> I think first it should be checked what the problem is. You can go ahead and revert, but the final solution will still probably involve the same design (passing labels to docker sdk)

totally agree

**Comment by tadej-redstone** [comment]
Experimenting locally I think I found the problem and solution: `dockerfile_path` should simply equal `Dockerfile`. But it would still be great to have tests that catch this.
