### ISSUE TITLE
can not run natively on macOS Silicon / ARMv8

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1781]
**Describe the bug**

It is an upstream problem. This means we can neither provide a native macOS silicon version nor ARMv8 in Docker image for now. Note, running under Rosetta 2 is fine, as it simply simulates x86/64

- Protobuf (in particular, `protoc` does not support armv8, there is no prebuilt wheel).  https://github.com/protocolbuffers/protobuf/issues/5154#issuecomment-421574629 
- There is an ongoing PR to protobuf https://github.com/protocolbuffers/protobuf/issues/7999, https://github.com/protocolbuffers/protobuf/pull/8196 (most promising one, also include 3.9), https://github.com/protocolbuffers/protobuf/pull/8280

- gRPC also has no wheel(https://github.com/grpc/grpc/issues/21283), but at least has to be manually compiled via:
```
GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=8
pip install grpcio
```

**Know Issues on Rosetta2**
- `urllib/request.py` throws 
```
Fatal Python error: Bus error

Thread 0x000000030b2a4000 (most recent call first):
```

workaround, use `no_proxy='*'` in os env. ref: https://bugs.python.org/issue28342

**References**
- https://github.com/danburkert/prost/issues/420
- https://github.com/grpc/grpc/issues/25082

---

**Environment**

**Screenshots**

**Comment by FionnD** [comment]
protocolbuffers/protobuf#8280 has now been merged. ✅
