### ISSUE TITLE
👷 Limited support on Python 3.9 releases

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#1801]
## 🎉 Python 3.9 support

Starting `v0.9.22` Jina starts to provide Python 3.9 initial support. PR #1802 enabled this support. 

You can use `pip install jina` or `docker run jinaai/jina:latest-py39` to use Jina in Python 3.9 environment. This applies to Jina extensions such as `daemon`, `devel`; details on the version naming can be [found here](https://github.com/jina-ai/jina/blob/master/RELEASE.md). PyPi packages and Docker images will be updated accordingly.

## 👷 Known issues

In this initial support, there are few known issues:
- ~~**Slower speed** due to lack of C++ protobuf backend. We are pushing forward [~this PR~](https://github.com/protocolbuffers/protobuf/pull/8196) [this PR](https://github.com/protocolbuffers/protobuf/pull/8280) on the upstream. Once this PR is merged on the upstream we will be able to install protobuf directly from precompiled wheel~~
- tba

We will work with the community and the upstream to solve these known issues in the next couple of weeks.

**Comment by cristianmtr** [comment]
FYI TF2 does not support Py3.9 yet but are working on it.

https://github.com/tensorflow/tensorflow/issues/44485
