### ISSUE TITLE
About resource usage of multi-shards and multi-pods modes in k8s deployment

### ISSUE THREAD

**Issue by innerNULL** [jina-ai/jina#1805]
Hi, here is one thing I needs to make sure.

As my understanding, one way to improve the pipline's degree of parallelism is using multiple shards during encoding and indexing stage, as my observation, on single physical machine, each shard corresponds to a single jina-pod (**which is also a single python process**).

So my question is, when I deploy jina-pipline on k8s in multi-shard mode, if each jina-pod corresponding to a single k8s pod？Or these jina-pods correspond to several python processes in one k8s-pod?

**Comment by nan-wang** [comment]
@innerNULL hi, there. Yes, the example at https://github.com/jina-ai/cloud-ops/tree/master/k8s_example/demo_k8s_flow just shows the usage of deploy one **Jina Pod** in one *k8s pod*. In this case, each parallel/shards corresponding to one process. We have plans to work on deploying one **Jina Pea** in one **k8s pod**. This has a high priority after the 1.0.0 release.

**Comment by innerNULL** [comment]
> https://github.com/jina-ai/cloud-ops/tree/master/k8s_example/demo_k8s_flow

@nan-wang Thanks for reply, so this means when deploying on k8s, each pods only have one data shard, and we needs consider the parallel/shards number carefully in case the single shard size larger than the pod's RAM limit?
