### ISSUE TITLE
Client hangs in docker compose environment

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#1806]
**Steps to reproduce:**

- checkout branch from https://github.com/jina-ai/cloud-ops/pull/80
- build Docker image `docker build -f debianx.Dockerfile -t stress_example_image_search $PATH_TO_JINA_REPO`
- start docker-compose `docker-compose -f docker-compose.yml --project-directory . up  --build -d`
- start flow for indexing: `python app.py --jinad index`
- connect to container called `flow`
- install requirements for client.py there: `pip install click jina[devel]==0.9.20`
- run client to send data to flow `python code/client.py -t index -n 20 -c 1 -h 0.0.0.0 -l 0 -r 100 -c 1`

**Error**

Client seems to hang with no response back from the Flow. This happens no matter what configuration you use

```
# python client.py -t index -n 20 -c 1 -h 0.0.0.0 -l 0 -r 100 -c 1
task = index; port = 45678; load = 0; nr = 20; concurrency = 1
Will end at 2021-01-27T10:08:44.551263
Process index-0 is still alive. Will wait...
Process 0: Running function index with 20 docs...
           JINA@420[S]:input_fn is valid
indexing!!!
         Client@420[S]:connected to the gateway at 0.0.0.0:45678!
index |█                   | 📃      0 ⏱️ 0.0s 🐎 0.0/s      0      batchindex ...
```

You can stream the logs from the indexer container to see that it receives the data correctly. You can even check the size of the indexers and see that they are indeed increasing.

**Comment by florian-hoenicke** [comment]
For me locally it fails at the docker build step.
```
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 3, in <module>
    import re
  File "/usr/local/lib/python3.7/re.py", line 124, in <module>
    import enum
  File "/usr/local/lib/python3.7/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/jina/types/__init__.py)
```

**Comment by nan-wang** [comment]
> For me locally it fails at the docker build step.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/pip", line 3, in <module>
>     import re
>   File "/usr/local/lib/python3.7/re.py", line 124, in <module>
>     import enum
>   File "/usr/local/lib/python3.7/enum.py", line 2, in <module>
>     from types import MappingProxyType, DynamicClassAttribute
> ImportError: cannot import name 'MappingProxyType' from 'types' (/jina/types/__init__.py)
> ```
> 
> I tried to build it in `stress-example/image_search`

@florian-hoenicke 
I have this trouble when debugging the unit tests. The reason is that `jina.types` module overwrites the built_in `types`. Would you please elaborate more on how to reproduce this?

**Comment by hanxiao** [comment]
> The reason is that jina.types module overwrites the built_in types.

I also have this import error occasionally, but cant reproduce consistently across different Pycharms (i work on three desktops, some works some not at random)
