### ISSUE TITLE
Right after starting a flow, GET logs sends 404

### ISSUE THREAD

**Issue by imsergiy** [jina-ai/jina#1812]
**Describe the bug**
This is likely due to the `logging.log` file not yet being created under `{workspace_id}/{flow_id}`.

**Describe how you solve it**
Ideally, when starting a flow, the daemon would send a successful response only after the flow is fully ready to interact with, including logstream. This would make the API more deterministic in the sense that we would not need to document any additional caveats or quirks instructing developers to figure out when a flow is "fully ready".

**Comment by deepankarm** [comment]
This won't be fixed with the current integration of fluentd + jinad because of reasons explained in https://github.com/jina-ai/jina/pull/2279#pullrequestreview-628624569

**Comment by alexcg1** [comment]
Do we want to close this issue?

**Comment by deepankarm** [comment]
Fixed in #2473
