### ISSUE TITLE
Status websocket stream in daemon

### ISSUE THREAD

**Issue by imsergiy** [jina-ai/jina#1813]
**Describe the feature**
It would be really nice to have some kind of `/status` or `/alerts` websocket stream that notified the console of any changes to global jinad state or flow/pea/pod states. This would allow us to know when jinad is killed, when flows are updated or killed from any client, when errors happen in the daemon during runtime, etc. In a cloud environment, this could enable push notification via email/SMS. This is especially crucial for situations when multiple clients may be connected to the daemon simultaneously either by different developers or by one developer having multiple tabs open so that the state of the flows is always in sync.

**Your proposal**
For example, if files are added to a workspace, a message is sent:
```JSON
{
  "type": "workspaces_updated",
  "workspace_id": "8d1e1c70-6b90-4f07-be1d-302d6b404848"
}
```
Console would then know to `GET` new workspace state from `/workspaces/{workspace_id}`

If the websocket connection is broken at any point by the daemon, console can immediately notify the user to reconnect.

**Comment by BastinJafari** [comment]
I would say this is fairly important. When I launched a flow and didn't get any logs immediately, I thought that there would be a bug in the front end and searched for it for a while. In most software, the user is getting a log with any kind of action, so it is likely that others will also tend to think that something isn't working.
