### ISSUE TITLE
Enable the user to choose which Dockerfile to use

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1822]
**Describe the feature**
`jina hub build` does **NOT** offer the option for choosing Dockfile 

**Your proposal**
`jina hub build --file gpu.Dockfile`
`jina hub build -f gpu.Dockfile`

---

**Environment**

**Screenshots**

**Comment by tadej-redstone** [comment]
What should be taken into account here is that different dockerfile should also get different tags. `gpu.Dockerfile`, for example, should have a tag ending in `gpu`.

**Comment by nan-wang** [comment]
@tadej-redstone Yes. As for jina core, the task is to enable to choose which docker file to use when running `jina hub build`. As for how to use the tags, I'd prefer to do it at https://github.com/jina-ai/action-hub-builder

**Comment by FionnD** [comment]
@nan-wang 
Should we add this information to docs.jina.ai?
