### ISSUE TITLE
Storing Vectors

### ISSUE THREAD

**Issue by annaakhil** [jina-ai/jina#1827]
Hello guys, are the vectors of the documents stored in binary format or numerical format? because  I want to retrieve the respective embeddings for the respective documents. 
**Screenshots**
Something like this
![image](https://user-images.githubusercontent.com/49350396/106455378-243f0c00-64b2-11eb-9acb-fe3be0f63a33.png)

**Comment by nan-wang** [comment]
@annaakhil hi, there. It is stored in binary format. There is no straightforward way to do so because under the hood the vectors and the input texts are stored separately by `VectorIndexer` and `KVIndexer`.

In your case, you need to know the `key` of the Document when storing the vector.

```
from jina.executors.indexers import BaseIndexer
save_abspath = 'where/your/index/is/saved'
keys = ['key1', 'key2']
with BaseIndexer.load(save_abspath) as indexer:
    ret = indexer.query_by_key(keys)
    print(ret)
```

**Comment by annaakhil** [comment]
@nan-wang Thanks but instead of text can I get the id and vectors
![image](https://user-images.githubusercontent.com/49350396/106559009-c90d2800-654a-11eb-8d26-5923523b996f.png)
Vectors are getting saved in the embed_vecs variable and doc ids in docs_pts. I would like to retrieve that information, how can I do it? Do I need to import any indexers? or call any function?

**Comment by nan-wang** [comment]
@annaakhil Is the following codes what you want to do? 

```python
from jina.executors.indexers.vector import NumpyIndexer

from jina.executors.indexers import BaseIndexer

import numpy as np

num_data = 5
num_dim = 128
vec_idx = np.array([_idx for _idx in range(num_data)], dtype=(np.str_, 16))
np.random.shuffle(vec_idx)
vec = np.random.random([num_data, num_dim])

with NumpyIndexer(metric='euclidean', index_filename='np.test.gz') as indexer:
    indexer.add(vec_idx, vec)
    indexer.save()
    save_abspath = indexer.save_abspath

with BaseIndexer.load(save_abspath) as indexer:
    for key, expected_vec in zip(vec_idx[:2], vec):
        retrieved_vec = indexer.query_by_key(key, top_k=1)
        np.testing.assert_array_equal(retrieved_vec.squeeze(), expected_vec) 
```

**Comment by annaakhil** [comment]
**@nan-wang yeah I already tried implementing this code from jina/unit/test_numpyindexer.py but I am getting an error as 
_AttributeError: 'NumpyIndexer' object has no attribute 'query_by_key'_**

![image](https://user-images.githubusercontent.com/49350396/106713934-24a9e500-6621-11eb-9929-4a6cfce06322.png)

**Comment by nan-wang** [comment]
@annaakhil What's you jina version after `jina -vf`?

**Comment by nan-wang** [comment]
`query_by_key` is introduced this week by #1829

**Comment by annaakhil** [comment]
@nan-wang I updated to the latest version, but I am getting an error **TypeError: 'numpy.int64' object is not iterable**
![image](https://user-images.githubusercontent.com/49350396/106723403-16fa5c80-662d-11eb-9735-815125c7a052.png)
![image](https://user-images.githubusercontent.com/49350396/106723657-59bc3480-662d-11eb-83aa-b49dfce53537.png)

**Comment by nan-wang** [comment]
@annaakhil Would you please paste your codes here? I can not reproduce your issue.

**Comment by annaakhil** [comment]
@nan-wang 
**from jina.executors.indexers.vector import NumpyIndexer

from jina.executors.indexers import BaseIndexer

import numpy as np

num_data = 5
num_dim = 128
vec_idx = np.array([_idx for _idx in range(num_data)])
print(vec_idx)
np.random.shuffle(vec_idx)
vec = np.random.random([num_data, num_dim])

with NumpyIndexer(metric='euclidean', index_filename='np.test.gz') as indexer:
    indexer.add(vec_idx, vec)
    indexer.save()
    save_abspath = indexer.save_abspath

with BaseIndexer.load(save_abspath) as indexer:
    for key, expected_vec in zip(vec_idx[:2], vec):
        retrieved_vec = indexer.query_by_key(key, top_k=2)
        np.testing.assert_array_equal(retrieved_vec.squeeze(), expected_vec)**

This is the error
![image](https://user-images.githubusercontent.com/49350396/106927453-2e723c00-6738-11eb-8be9-b9c1caf351e4.png)

**Comment by nan-wang** [comment]
@annaakhil hi, there. I notice that you are using `int` for the `id` instead of `string`. 
![image](https://user-images.githubusercontent.com/4329072/107139946-d450c100-6959-11eb-8f1a-915ed5dff194.png)

In the code snippet I posted, I define the `np.array` to use `np.str`

> vec_idx = np.array([_idx for _idx in range(num_data)], dtype=(np.str_, 16))

**Comment by FionnD** [comment]
Hi @annaakhil

Did Nan comment solve your issue? If so, I will close this ticket :)
