### ISSUE TITLE
Error during jina hub build

### ISSUE THREAD

**Issue by yuanbit** [jina-ai/jina#1830]
There is an error when building a custom executor using jina hub build as reported [here](https://github.com/yuanbit/jina-financial-qa-search/issues/2).

**Comment by nan-wang** [comment]
@JoanFM I guess `COL_MATCH_HASH` is deprecated

**Comment by JoanFM** [comment]
> @JoanFM I guess `COL_MATCH_HASH` is deprecated

@yuanbit u mean @nan-wang ?

**Comment by nan-wang** [comment]
@JoanFM Any idea about where `COL_MATCH_HASH` is defined? It doesn't look like a built-in property in jina.

**Comment by yuanbit** [comment]
I saw that ```COL_MATCH_HASH``` has been renamed to ```COL_MATCH_ID```. It is working now.

**Comment by JoanFM** [comment]
> @JoanFM Any idea about where `COL_MATCH_HASH` is defined? It doesn't look like a built-in property in jina.

I think somewhere in the BaseRanker executors
