### ISSUE TITLE
Sphinx configuration failed to ignore lint exceptions

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#1952]
**Describe the bug**

![image](https://user-images.githubusercontent.com/4329072/108069451-577ebf00-709e-11eb-8c00-819c50a85133.png)

reference:
https://docs.jina.ai/api/jina.jaml.parsers.base.html#jina.jaml.parsers.base.VersionedYAMLParser.parse

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by bwanglzu** [comment]
good catch, thanks @nan-wang !I'll do a quick fix

**Comment by bwanglzu** [comment]
seems the workaround above is not working

**Comment by bwanglzu** [comment]
figured our adding two dots together with two blank links would fix the issue:
![image](https://user-images.githubusercontent.com/9794489/108195254-cea46980-7117-11eb-9267-06398df3c1e2.png)
