### ISSUE TITLE
Better debug logs in Jina

### ISSUE THREAD

**Issue by samjoy** [jina-ai/jina#1964]
**Describe the feature**
Is it possible to provide better debug logging in Jina? We could monitor what data is going in and out of each driver and executor. This could be very useful.

**Your proposal**
Maybe, in the yml file for each pod there can be a debug attribute that can be set to True/False against the executor and  every driver included.

**Environment**
- jina 1.0.0
- jina-proto 0.0.78
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.20.1
- protobuf 3.14.0
- proto-backend cpp
- grpcio 1.35.0
- pyyaml 5.4.1
- python 3.8.5
- platform Linux
- platform-release 5.4.0-65-generic
- platform-version #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
- architecture x86_64
- processor x86_64
- jina-resources /home/samjoy/miniconda3/envs/lyrics-1/lib/python3.8/site-packages/jina/resources
* JINA_ARRAY_QUANT (unset)
* JINA_BINARY_DELIMITER (unset)
* JINA_CONTRIB_MODULE (unset)
* JINA_CONTRIB_MODULE_IS_LOADING(unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EXECUTOR_WORKDIR (unset)
* JINA_FULL_CLI (unset)
* JINA_IPC_SOCK_TMP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_POD_NAME (unset)
* JINA_RAISE_ERROR_EARLY (unset)
* JINA_RANDOM_PORTS (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_SOCKET_HWM (unset)
* JINA_VCS_VERSION (unset)
* JINA_WARN_UNNAMED (unset)
* JINA_WORKSPACE (unset)

**Comment by BastinJafari** [comment]
Have you checked out https://dashboard.jina.ai/#/logs ?
You can filter logs by pod and also by kind (SUCCESS, WARNING, etc.).

**Comment by samjoy** [comment]
I would like to know what data is going in and out of every executor and driver. It would help me know how the data is being manipulated and thus if I am applying the correct parameters in the yaml file. For example, I want to see the output on applying a FilterQL on a data point. 
I had quite a complex workflow which did not work as expected.

**Comment by JoanFM** [comment]
@samjoy ,

As a potential debugging tool , u can try to add the driver called: `LogInfoDriver` at the end of every Pod's list of Drivers to see how every `Document` in the `request` passing through that driver looks (they will be printed in console). This is so far what may fit the best what you ask for.

**Comment by samjoy** [comment]
Hi @JoanFM , you told me over slack that LogInfoDriver is too noisy. Thus, you recommended that I raise this feature request for better logging.

**Comment by JoanFM** [comment]
> Hi @JoanFM , you told me over slack that LogInfoDriver is too noisy. Thus, you recommended that I raise this feature request for better logging.

I know, it is just a comment, we are looking into better ways of logging and debugging

**Comment by samjoy** [comment]
I will have a look at LogInfoDriver. Thanks

**Comment by hanxiao** [comment]
@samjoy fyi, add `--quiet` was added to Pea, Pod, Flow. You can suppress logs from a particular Pod by
```yaml
!Flow
pods:
  - uses: blah
    quiet: true
  - uses: ...
```

**Comment by samjoy** [comment]
Awesome. Thank you @hanxiao I will look into it.

**Comment by FionnD** [comment]
@samjoy did Han suggest solve your issue? 

If so, could we close this issue?

**Comment by samjoy** [comment]
I guess LogInfoDriver will do, thought the logs are a bit noisy. Its fine for now.
