### ISSUE TITLE
Delete document with all its chunks (vectors)

### ISSUE THREAD

**Issue by nero-nazok** [jina-ai/jina#1986]
Hi everyone! Our documents (indexed via BinaryPbIndexer) typically consist of many chunks (indexed via NumpyIndexer). How can we now delete a document with all its chunks just by the document-id? Maybe an own delete-flow would be an option.

In addition, I am also interested in doing this permanently as it was requested in this [issue](https://github.com/jina-ai/jina/issues/1984). Reindexing really is a pain we face.

I think there should definitely be an example for the deletion of documents. It would be of interest to me to see how to delete documents in the [multires-lyrics-search](https://github.com/jina-ai/examples/tree/master/multires-lyrics-search) example.

Thanks Jina team!

**Comment by maximilianwerk** [comment]
Dear @nero-nazok ,
thanks a lot for your request.

For now our design decision is, that if you want to delete chunks, you have to keep track of their `id`s. If you delete a Document you then have to delete the chunks manually.

We were well aware of the consequences of this decision. Furthermore, we plan to address this in the future. Anyhow, retrieving the chunk ids from a document id is non-trivial. We might introduce something like a `ChildIdIndexer`. The placement of it in a `DeleteFlow` would be before the actual indexer (but also afterwards, since we need to update the `ChildIdIndexer` itself after a successful deletion). Since Jina in principal does not prevent multiple Indexers, the design of Flows might become even harder. That's why we did not implemented it straight away.

That said, we will have another iteration on the CRUD operations quite soon.

Regarding the permanent deletion request: Which size will your indexes roughly have? How often do you delete documents and how fast do they have to be really deleted? Would a nightly batch-rebuild of the index itself be a feasible solution?

**Comment by nero-nazok** [comment]
Thanks for your reply @FionnD!

We really look forward to this feature. And yes we delete, add and update documents only at night so that would be fine. We only want to avoid reindexing everything again, as it requires us to crawl through all the data again.

**Comment by geraldwinkler** [comment]
@maximilianwerk We also have documents that are made up of chunks. So this is definitely a priority for us.

**Comment by ace-kay-law-neo** [comment]
Hey @maximilianwerk! Are there any plans, when it will be possible to delete all the chunks of a document just by the document-id?

My team really looks forward to this feature. Thank you!

**Comment by maximilianwerk** [comment]
> Hey @maximilianwerk! Are there any plans, when it will be possible to delete all the chunks of a document just by the document-id?
> 
> My team really looks forward to this feature. Thank you!

Hey @ace-kay-law-neo ,

the current refactoring of the indexers will result in a solution, where it is way easier to target the same index multiple times in a Flow. With this, it will be possible to implement the design I suggested above. We will update in our documentation how to do it, once it is implemented and aim to have this refactoring done until end of April. It will come with several other database-like features, so stay tuned and excited.

As a consequence, the newly created indexing paradigm will not be backward compatible and you might need to reindex all your data once. Just out of curiosity: Would that be a big hassle for you?

All the best!

**Comment by ace-kay-law-neo** [comment]
Hey @maximilianwerk,

thanks for your kind response. No, reindexing all the data just one time wouldn't be a big deal.
I would be grateful if you could give us an update, once this feature is available. We will ship our search-system three to four weeks from now. Do you think this feature is published until then, or do we have to write a custom implementation?

Thanks again for your support! It's really cool how powerful Jina's CRUD operations already are.

**Comment by maximilianwerk** [comment]
> Hey @maximilianwerk,
> 
> thanks for your kind response. No, reindexing all the data just one time wouldn't be a big deal.
> I would be grateful if you could give us an update, once this feature is available. We will ship our search-system three to four weeks from now. Do you think this feature is published until then, or do we have to write a custom implementation?
> 
> Thanks again for your support! It's really cool how powerful Jina's CRUD operations already are.

Hey @ace-kay-law-neo,

unfortunately I cannot guarantee, that this feature is production ready in the next two weeks. If no unforeseen obstacle is in our way, it will be ready for extensive testing in two weeks and I'd love to see you as our first live-testers :crossed_fingers: Anyhow, as it is with bigger features and design changes, unforeseen obstacles are quite common. Once we merged the major code changes to master, we will let you know.

Currently this is worked on in #2224 and #2260

**Comment by alexcg1** [comment]
Hey @ace-kay-law-neo @geraldwinkler we'd love to have proper chat about this with you! Are you on our [community Slack](https://slack.jina.ai)? Let's coordinate there and arrange a call!

**Comment by ace-kay-law-neo** [comment]
Hey @alexcg1 that's super nice of you. However, 2 days ago we fortunately found another way to resolve this problem in the mean time. So we don't need to pressure you and your team for this feature. We now collect all the chunk-ids and save them in our mongo-database. Thanks for all your support so far! We really appreciate all the effort you and your colleagues put into this framework.

**Comment by maximilianwerk** [comment]
That's great. Still, we would love to have a chat with you some time for half an hour. Since you use Jina in production, your feedback would be of great value for us to steer our further development.

**Comment by ace-kay-law-neo** [comment]
Hey @maximilianwerk, sorry for the late reply. I somehow don't get notified anymore by github when someone mentions me. My founder already had a meeting with some of your colleagues yesterday. In essence following features are of interest to us:

1. Restrict Search Space: Restricting the search space for each user (e.g. Users can only search their own emails.)
2. Search & Index at the same time: Also bringing the index from the file-system to mongo-db.
3. Stress-Tests (including the FaissIndexer): small query-time on a large search space
4. CTR: reranking by click-though-rate

However, we already discussed these points with your colleagues. Anyway thanks for the great support. We have been following Jina for about 7 months now and are impressed by your progress. We will launch our product powered by Jina in about 2 weeks. A huge thank you from our team.

**Comment by alexcg1** [comment]
@ace-kay-law-neo are we good to close out this issue?

**Comment by nero-nazok** [comment]
Hey @alexcg1 and @maximilianwerk, sorry for the inactivity lately.

When migrating to Jina v2 we will move our index-data from the filesystem to a more reliable data storage e.g. mongodb. It would be great if Jina would support the full deletion of documents (including its chunks) out of the box.
