### ISSUE TITLE
mime type sniff for audio/wav

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/jina#1998]
**Describe the bug**

Change from this  [PR](https://github.com/jina-ai/jina/commit/b2c2a97cef06a8f75a0227199a8948bf8152a4ce) will fail the audio-search example because the mime type is set to a wrong value (text/plain).
![image](https://user-images.githubusercontent.com/44033547/108609544-8d70bb80-739c-11eb-8c0c-fa257073e6d3.png)
![image](https://user-images.githubusercontent.com/44033547/108610544-59999400-73a4-11eb-8022-a2dab3ae3fbb.png)

**Describe how you solve it**

Why we have text/plain type? There is exception at `self.uri = value`.
![image](https://user-images.githubusercontent.com/44033547/108609766-3bc93080-739e-11eb-8cb0-cc6edfad3734.png)

Dig in deeper, the exception is from the following codes. Here value is "audio/wav" and not in types.maps.values(). Still 'r' is None.
![image](https://user-images.githubusercontent.com/44033547/108609819-96fb2300-739e-11eb-88c8-f8c7d307b5f5.png)

**Root reason: Chrome** browser will attach `audio/wav` to `.wav` file.
For audio/wav type data, since it is not in python mime-types if we want to keep the change of PR [#1982](https://github.com/jina-ai/jina/commit/b2c2a97cef06a8f75a0227199a8948bf8152a4ce). We need to set the correct mime-type (which is audio/x-wav) before we convert uri to buffer.

Potential solution:
https://github.com/jina-ai/jina/pull/1999
---

**Environment**

- jina 1.0.2
- jina-proto 0.0.78
- jina-vcs-tag (unset)
- libzmq 4.3.3
- pyzmq 1.19.5
- protobuf 3.14.0
- proto-backend cpp
- grpcio 1.34.1
- pyyaml 5.3.1
- python 3.7.6
- platform Darwin
- platform-release 19.5.0
- platform-version Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020;
  root:xnu-6153.121.2~2/RELEASE_X86_64
- architecture x86_64
- processor i386
- browser: Chrome Version 88.0.4324.182 (Official Build) (x86_64)

**Screenshots**

Correct:
![image](https://user-images.githubusercontent.com/44033547/108609563-a5483f80-739c-11eb-9d38-88c285d99426.png)
Wrong:
![image](https://user-images.githubusercontent.com/44033547/108609645-46cf9100-739d-11eb-81f1-0b3344712241.png)

**Comment by hanxiao** [comment]
I dont quite understand the logic here. why is this considered as a bug in the core, AudioExample should just change accordingly.

**Comment by Yongxuanzhang** [comment]
> I dont quite understand the logic here. why is this considered as a bug in the core, AudioExample should just change accordingly. 

If we search the audio in Chrome, the results cannot be recognized because we wrongly guess the mimetype in jina core as shown in the screenshots. Regarding changing the audio example, did you mean that we need to change mimetype at the frontend？
