### ISSUE TITLE
Async Websocket

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2023]
Maintenance  
Background: The pull request 1865 resulted in WebSocket gateway being blocked. 

Tasks:  
Investigate what steps are needed to fix the gateway and report back here.  
Implement the steps. 

Acceptance criteria:  
This ticket is done when: The gPRC gateway is fully functional as it was before PR 1865 was merged.

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7025831

**Comment by FionnD** [comment]
I am closing this issue because it's not on the current roadmap
