### ISSUE TITLE
Avoid dumping _drivers parameters when serializing executor

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2039]
**Describe the bug**
When jina executor is serialized, it also serializes the `driver` which does not allow to change the `Drivers` parameters when reloaded.

Specially important for `indexers`

**Comment by davidbp** [comment]
We have seen that this is beyond a simple fix and would require a major refactor of code.
We just got to Jina V1 so the suggestion is to warn users about driver serialization and close this issue. 
This is done in https://github.com/jina-ai/jina/pull/2111

**Comment by FionnD** [comment]
@davidbp is #2111 done, so this issue is done for the moment?
