### ISSUE TITLE
Design discussion on Workspaces.

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2065]
# **[Research ticket]**

Workspaces are an important infrastructural concept in Jina. They are present locally [via workdir] and on the cloud when created using JinaD.  Going forward, we need to design an architecture for workspaces that aligns between core and console. 

<p></p>

Slide deck: [**https://docs.google.com/presentation/d/1UAUXzKzPWytvmkM7RNk8rwMz19mxcaOvOkIDYqClcZU/edit#slide=id.gc071880748_0_0**](https://docs.google.com/presentation/d/1UAUXzKzPWytvmkM7RNk8rwMz19mxcaOvOkIDYqClcZU/edit#slide=id.gc071880748_0_0)

<p></p>

**Some notes:** 

- By default, the workspace is provided by the flow

- Optionally, a user could give a suffix or more 

- Workspaces can be shared across the flow. For distributed pods, you have the five independent workspaces but are named the same. Because the name comes from the Flow level. JinaD is setting the workspace ID. The flow gets the workspace id and sets that workspace for all pods and peas. 

- Conflix between JinaD and terrraform. 

<p></p>

## Acceptance Criteria

- This ticket is done when: The google slide deck contains information about how workspaces are used in Elasticsearch and Terraform. Explaining how distribution works, hierarchy works. 

- This ticket is done when: When a sufficient number of different customer use cases has been considered, and a proposed architecture has been added to the slide. These use cases should include running Jina locally, running Jina on the cloud via JinaD, running Jina on the cloud distributed via JinaD. 

- This ticket is done when: A proposal has been added to the slide deck for how naming convention should work. 

- This ticket is done when: Once the above two tasks are done. The PM has been notified and a meeting with team leads + CTO/CEO has been setup. 

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7103827

**Comment by FionnD** [comment]
Hey @serge-m 

You were "nominated" to help research use cases for the workspace from a frontend point of view.  Would you be up to taking this ticket?

**Comment by FionnD** [comment]
Following the meeting on Friday, this issue is now closed and moved onto the new step.
