### ISSUE TITLE
Validate no zombie processes with Daemon

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2067]
# Maintenance

Gateway & Daemon logic (closing) > Needs Testing

# Acceptance Criteria

- This ticket is done when: Closing the gateway via JinaD has been tested and any bug found are reported. 

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7026192

**Comment by deepankarm** [comment]
https://github.com/jina-ai/jina/pull/2473 moves all jina objects into their separate containers and `docker stop` by default cleans all the "zombies". Closing this.
