### ISSUE TITLE
Enable systemd based daemon deployment to cloud.jina.ai with CD

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2068]
**Describe the feature**  
Using AWS cfn/terraform templates to deploy latest daemon code can be deployed to cloud.jina.ai.  
┆Issue is synchronized with a GitHub issue by Unito

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/6941850

**Comment by deepankarm** [comment]
- Published official [jina module in Terraform registry](https://registry.terraform.io/modules/jina-ai/jinad-aws/jina/latest)
- [Gets used internally](https://github.com/jina-ai/jina-terraform/tree/main/custom-jinad-deployment) with remote backend, custom dns.
- cloud.jina.ai enabled with every release with [tag.yml](https://github.com/jina-ai/jina/pull/2099).
