### ISSUE TITLE
Insert and update should return the passed value

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2069]
# Feature Request
According to best practices for RESTAPI and gPRC. A user would expect that when they call an insert or update endpoint, the value they passed would be returned to them to confirm it has been successfully inserted or updated. This allows a QA process on their side. 

As a user interacting with executor via the REST API, I expect when I index a value, it should return the value to me if it was successfully inserted. When I update a value, it should also return the updated value. For the updated value, this only applies to full updates, not partial updates. 

# Acceptance Criteria
* This ticket is done when: When a value is passed to the post/index endpoint in the RESTAPI. If it has been successfully indexed, the value is returned to the user. 
* This ticket is done when: When a value is passed to the update endpoint in the RESTAPI. If it has been successfully updated, the value is returned to the user. 
* This ticket is done when: The redoc API has been updated to reflect this change. 

# Subtasks
*  Clarify if behavior of failing is in scope
*  In case yes: implement behavior when failing
*  Write test for index endpoint for KVIndexer and VectorIndexer (or find one that already test it)
*  Write test for update endpoint (or find one that already test it)
*  Clarify in documentation, that the `CompoundIndexer` can never return embeddings by design
*  if functionality is missing: implement it

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7040553

**Comment by theUnkownName** [comment]
> - [ ] Write test for update endpoint (or find one that already test it) 
> - [ ] Write test for index endpoint for KVIndexer and VectorIndexer (or find one that already test it)

This already exists in `test_crud.py`. A list of Documents already exists and are updated with a different list of random Docs. The test check wether the incoming data belongs on the original or updated list accordingly.

**Comment by theUnkownName** [comment]
At the moment there is no clean way to access the embeddings as shown [here](https://github.com/jina-ai/jina/pull/2219). This is because they are excluded during indexing time to avoid having them in the `KVIndexer`. This will be easily solved with the new Indexer approach

**Comment by FionnD** [comment]
Since https://github.com/jina-ai/docs/pull/195 is merged, and #2229 is done, this ticket is done now?

**Comment by FionnD** [comment]
Moving this issue back to backlog waiting on SQL indexer outcome
