### ISSUE TITLE
Deploy Jina with K8

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2073]
# Feature request

As a user of Jina, I want to be able to deploy Jina pods into a large K8 based cluster. I want to documentation guide to explain how to do this. 

<p></p>

## Acceptance Criteria

- This ticket is done when: We are able to support deploying Jina into a K8 based cluster. It should be clear on our documentation website if there is any limitations or untested aspects of this. 

- This ticket is done when: We have a guide on our documentation site explaining how to deploy Jina into a k8 cluster.

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7039747

**Comment by FionnD** [comment]
@nan-wang i'm closing this issue and we can reopen once you have more requirements on what we need for K8 support. Is that okay? I want to keep the backlog clean ;)
