### ISSUE TITLE
Tunning Flow Example

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2077]
# Feature request
Leverage current example / dataset, showcase what hyperparameter optimization is improving > different punctuation

# Acceptance Criteria
- [ ] A new example is added to the example repo. Which include a detailed Readme. 
- [ ] A blog post is written which includes a higher-level overview. 
- [ ] The Core README has been updated with an example

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/6941788

**Comment by FionnD** [comment]
@maximilianwerk are you working on this? If so can I put it into in-progess?
