### ISSUE TITLE
Configure pre-commit hooks for linting and code formatting

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2078]
**Reasons, argumentation:**

- consistent code makes it easier to read

- no time wasted in PR code review over proper indentation or formatting

- standardized means lower barrier to entry for onboarding

**Steps, tasks**

- configure git pre-commit hooks for auto formatting with `black`

- maybe also a linting/warning tool, like `flake8`

- will require a PR with a complete re-formatting by `black` of the entire codebase

- add to `Contributing.md`

- add to CI to make sure any new PR follows the standard

**Also, we want to make sure that there are warnings in place for** 

- missing docstrings

- dead code and functions (with `vulture`)

- missing type annotations

- missing line feed at EOF

These can be discussed, but it will help us ensure best practices 

<p></p>

To do  
- [x] Add precommit and CI for black @https://github.com/jina-ai/jina/pull/2036

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/6941853

**Comment by cristianmtr** [comment]
PR for black: #2036
