### ISSUE TITLE
Chinese Text Example (update / redo)

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2080]
# Feature Request / Maintenance

For our Chinese users, we should have a working example they can use. Please review this [PR](https://github.com/jina-ai/examples/pull/394). 

# Acceptance Criteria

- This ticket is done when: When the PR #394 is sufficiently working. 

- This ticket is done when: When PR #394 has a good README in Chinese.

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7024700

**Comment by Yongxuanzhang** [comment]
Is it linked to a wrong PR? Should be this one https://github.com/jina-ai/examples/pull/394 I think.
