### ISSUE TITLE
FIX - Chunk

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2088]
As per the [following slack discussion](https://jinaai.slack.com/archives/C018QCARHNG/p1611563667015900), we no longer use the word chunk generally. Expect when we are talking about Recursive Document Representation or certain types of ranker. 

The task for this ticket is to search and place all existing documentation for the word chunk and replace it with a document. Unless it used in the above-mentioned context.

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/6941852

**Comment by JoanFM** [comment]
https://github.com/jina-ai/docs/pull/168
