### ISSUE TITLE
input_fn -> inputs

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2091]
We change the input_fn parameter to inputs.  
Reason: It is possible to provide more datatypes than functions like Iterables for instance.

before:  
def index(self, input_fn: InputFnType,

after:  
def index(self, inputs: InputType,

Reference: Keras is using inputs as well.  
keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")

In contrast to input, inputs is not shadowing a built-in.

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7141155

**Comment by nan-wang** [comment]
fixed by #2054
