### ISSUE TITLE
Distributed Peas inside a Pod

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2093]
# Feature Request
As a user of Jina, I want to be able to have a pod that includes distributed [remote] peas. 

<p></p>

This is technically possible, but must be exposed to the user. [https://docs.google.com/presentation/d/1A3ydbFwlE30RyVjtfuK81NpgwgdR1iQ7pyA2tPfdlGY/edit](https://docs.google.com/presentation/d/1A3ydbFwlE30RyVjtfuK81NpgwgdR1iQ7pyA2tPfdlGY/edit%7Csmart-link) 
# Acceptance Criteria
- This ticket is done when: You have created the arguments and define how the arguments to have a different host for a Pea than its Pod works. (Currently, Pods and Peas' pods are tight together)
- This ticket is done when: Guarantee that these arguments are properly passed also to RemotePods if it is needed.
- This ticket is done when: integration tests for jinad showing this structure has been added. 
- This ticket is done when: A guide on how to use the arguments has been added to docs.jina.ai 

<p></p>

<p></p>

<p></p>

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/6941810

**Comment by lusloher** [comment]
connected to https://github.com/jina-ai/jina/issues/2092

**Comment by JoanFM** [comment]
We still need to write a guide in `docs.jina.ai` on how to use this feature @bwanglzu

**Comment by bwanglzu** [comment]
I'll create a new PR for the blog, in docs repo. cc @JoanFM

**Comment by bwanglzu** [comment]
the explanation of this feature will be in another ticket #2084
