### ISSUE TITLE
Optimizing CraftDriver

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2096]
## Context

Need discussion & design work; focus on driver interface

Topics:

- New driver or refactor current drivers

- Where batching needs to happen

- Design so that we avoid adding new drivers

- **How many drivers should we provide; how to better provide default drivers**

Dependent on Traversal driver refactoring

<p></p>

Since the refactoring of Drivers, Crafters have the possibility to get all the flattened documents in one shot.

If we allow from a `DocumentSet` to extract all `given` attributes for each of their documents, then Crafters could profit from `batching`.

This ticket would imply changing all Crafters to allow handling documents in batches.

- This ticket could be easily extended, to have every executor interface handle batches

- Or we could have an optional Mixin to add to Executors if wanted that adapt the custom exec interface to work with batches

<p></p>

<p></p>

<p></p>

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7017887

**Comment by JoanFM** [comment]
I will call as this is handled in #2097
