### ISSUE TITLE
REST API - search - missing attribute

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2103]
When calling the REST API for search where we don't get matches, the matches attribute is not included in the response. 
`
with flow: \#restful == True
    res = requests.post('http://0.0.0.0:{flow.port_expose}/api/search', documents)
`
UAC
- all attributes of a document are included in the response - even if they are empty lists or dictionaries

**Comment by FionnD** [comment]
**Maintenance**
When a user calls the search endpoint in the REST API, they would expect that all attributes are included. Regardless of if there are values for those attributes or not. 


with flow: \#restful == True res = requests.post('http://0.0.0.0:{flow.port_expose}/api/search', documents)
``  
**Acceptance Criteria**
This ticket is done when: If a user uses the search endpoint in the restapi,  all attributes of a document are included in the response - even if they are empty lists of dictionaries

**Comment by noopurdhawan** [comment]
Hi guys! I am currently looking into this, and I am going to make a PR on this issue soon.  So, can you please assign this issue to me? 
It would be helpful if anyone could share an example of the response to the post request.

**Comment by FionnD** [comment]
Hi @noopurdhawan , 

Great! Thanks for helping out! @florian-hoenicke do you think you could give an example of the response?

**Comment by florian-hoenicke** [comment]
@deepankarm is this maybe solved already?

**Comment by FionnD** [comment]
@deepampatel to review this issue and decide what steps are needed.

**Comment by deepampatel** [comment]
Seems you wanted to tag @deepankarm

**Comment by deepampatel** [comment]
just tried it, to simulate a query with no matches, i tried to query an empty index, this raises and adds a stack trace to response.
But no  empty `matches` list in the response

**Comment by FionnD** [comment]
uh yes sorry I meant @deepankarm ! :D but thank you for the checking anyway. @deepankarm is this is hard to fix?

**Comment by deepankarm** [comment]
@florian-hoenicke, I think this is true for gRPC based requests too. Can you check that?

**Comment by JoanFM** [comment]
What is the status of this issue @florian-hoenicke @deepankarm ??
