### ISSUE TITLE
allow programmatic overridding of yaml config

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#2105]
Atm we have some tests in core that create a workspace in hardcoded paths (based on `resources`), like https://github.com/jina-ai/jina/blob/fd01fd2d12c55bf7d61c9875f7727ac970e9b3e7/tests/integration/crud/simple/test_crud_readme.py#L8

This leads to tests failing and time wasted trying to debug it until you realize that it was reusing the workspace from an older local run. In CI we don't have this problem. We should not have tests that do this, I propose.

The problem is that we are using this `_index.yml` from resources which has a hardcoded path. Is there any way to override the metas of the indexer programatically in Python?

**Comment by FionnD** [comment]
Following the refinement meeting today, there needs to be a design discussion for how we solve this ticket.

Specifically focusing on how we solve the issue `_index` issue. This needs some creative thinking on how we add the workspaces.

I have set up a 30-minute meeting to discuss solutions. To make the meeting as quick as possible, if you have thoughts beforehand please post them here ⬇️

**Comment by cristianmtr** [comment]
Investigating this now. Will update this comment with findings

**Comment by cristianmtr** [comment]
#2162 partially fixes this for one specific test. We can use this approach on a per-test basis.

However, we still want in the future to be able to override / specify context args / env. vars. from Python to override any YAML config. Should keep this issue open

**Comment by JoanFM** [comment]
Closing this issue, as landscape for `executors` and `configuration` will heavily change

**Comment by cristianmtr** [comment]
> Closing this issue, as landscape for `executors` and `configuration` will heavily change

Will that address this issue?

**Comment by JoanFM** [comment]
> > Closing this issue, as landscape for `executors` and `configuration` will heavily change
> 
> Will that address this issue?

I would reopen later given the new semantics, since quite likely all these observations will be outdated

**Comment by cristianmtr** [comment]
> > > Closing this issue, as landscape for `executors` and `configuration` will heavily change
> > 
> > 
> > Will that address this issue?
> 
> I would reopen later given the new semantics, since quite likely all these observations will be outdated

But the underlying point is still valid

**Comment by JoanFM** [comment]
ok let's reopen then

**Comment by cristianmtr** [comment]
@JoanFM we can do this now with override_with and override_metas, right?

**Comment by JoanFM** [comment]
yes @cristianmtr
