### ISSUE TITLE
Image Logger (Driver / Indexer)

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2112]
# Feature improvement ticket

<p></p>

Background discussed can be found here: <https://jinaai.slack.com/archives/C0183GCN8AK/p1613652002117100>

This would be useful for debugging image processing (similar to `LogInfoDriver`)

Would require the implementation of a new Driver and a new Indexer

<p></p>

An initial version of the driver can be found here: <https://github.com/jina-ai/TUM-workshop/blob/fe58151c87e5a56568f8093755b5d96ed2b1d5ee/components.py#L12>

<p></p>

There will be a task to add this to the core repo, along with tests. 

<p></p>

There should be a discussion about if this is indexer or driver or both. Please sync with Max initially to answer this question. If there is a need for further discussion pull in Joan and Nan. 

<p></p>

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7057227

**Comment by JoanFM** [comment]
I think, maybe instead of extending the drivers for this purpose, we should encourage and expand the usage of `hanging` pods to analyze traffic in the middle of the Flow.

This could also be seen as a good debugging tool

**Comment by cristianmtr** [comment]
> I think, maybe instead of extending the drivers for this purpose, we should encourage and expand the usage of `hanging` pods to analyze traffic in the middle of the Flow.
> 
> This could also be seen as a good debugging tool.

Like debugging breakpoints, or is there something else you had in mind?

**Comment by JoanFM** [comment]
The same way we can have hanging Pods to be used potentially for evaluation, we can use these Pods to extract the messages from the Flow, to be analyzed separately?
