### ISSUE TITLE
AsyncFlow | TypeError: object async_generator can't be used in 'await' expression

### ISSUE THREAD

**Issue by nero-nazok** [jina-ai/jina#2120]
**The Bug**
Following error is raised when awaiting the index() method of the AsyncFlow using the latest Jina release (1.0.7):
`TypeError: object async_generator can't be used in 'await' expression`

**Reproduce**
```
from jina import AsyncFlow, Document

async def index_helper(input_fn):
    flow = AsyncFlow.load_config(path)
    with flow as f:
        await f.index(input_fn)  # <-- PROGRAMM FAILS HERE
```
When I downgrade jina to 0.9 or I remove the await before the f.index everything works fine.

**Comment by deepankarm** [comment]
Hello @nero-nazok,

This was one of the breaking changes introduced in https://github.com/jina-ai/jina/pull/1816. `f.index(...)` is an async generator now, hence the usage would be ([docs](https://github.com/jina-ai/jina#asynchronous-flow))

```python
with f:
   async for resp in f.index(input_fn):
      handle(resp)
```
