### ISSUE TITLE
incorrect usage of NotImplementedError

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#2123]
**Describe your proposal/problem**

In our codebase we've many places defining `NotImplementedError`, while it's not correctly used.
Found together with @Yongxuanzhang , it is incorrectly used, and make our codebase hard to test.

According to the [documentation]():

> This exception is derived from RuntimeError. In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method, or while the class is being developed to indicate that the real implementation still needs to be added.

Check the screenshot below to find an example usage in our codebase, it should be a `ValueError` or customised exception, such as `RequestTypeError`

![image](https://user-images.githubusercontent.com/9794489/110271203-d1340980-7fc7-11eb-88cb-6564d5ce1f56.png)

---

**Comment by Yongxuanzhang** [comment]
Yeah, so to address this issue we can search our codebase to make sure w use `NotImplementedError ` correctly? Seems like a good-first-issue.

**Comment by FionnD** [comment]
Good catch guys! I see this a medium priority maintenance issue. I've added it to the team backlog for when we have time, in the mean time community support is most welcome on this!

**Comment by bsherifi** [comment]
Hi guys! I am currently looking into this, and I am going to make a PR on this issue soon. However, I wanted to know, is there a specific condition that should be met to let us know when NotImplementedError is incorrectly used? That would be helpful in order for me to know which ones to remove (replace with other exceptions).

**Comment by bwanglzu** [comment]
Hi @bsherifi , great to have you here!

Whenever it's an abstract base method, such as 
```python
class BaseEncoder(...):
    def encode(self, data):
        """This is an abstract method, needs to be implemented in the subclass."""
        raise NotImplementedError("Error Message")
```
We should raise `NotImplementedError`.

While in the above screenshot, we already have some "code logic" defined inside the function, then it shouldn't be a `NotImplementedError`.

**Comment by bsherifi** [comment]
Thanks a lot @bwanglzu  

That was my initial thought on this, and I'm glad u clarified it even more. Maybe you or @FionnD can mark the status "in progress" for this issue since I've already started working on it this morning. Thanks again!

**Comment by bwanglzu** [comment]
@bsherifi super happy you'd like to contribute this one! Ask any question whenever you encounter any issues!

**Comment by FionnD** [comment]
Done @bsherifi, thanks for contributing!

**Comment by bwanglzu** [comment]
great work @bsherifi , thanks for your contribution!

**Comment by bsherifi** [comment]
> great work @bsherifi , thanks for your contribution!

thank you @bwanglzu, glad to be of help!
