### ISSUE TITLE
REST API - "oneof" validation

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2132]
The behavior of the `oneof` type in the protobuf definition can not be mapped to pydantic models.
There are request to address this issue:
samuelcolvin/pydantic#656
samuelcolvin/pydantic#619

As long as this feature does not exist, we should make our custom solution.

Please validate the request to check that the client obeys the `oneof` rules.

**Comment by FionnD** [comment]
Good morning @florian-hoenicke ! 🌤️ 

Is this a ticket for the future, or is it only related to the issue #2104  ?

**Comment by florian-hoenicke** [comment]
Hi @FionnD ! Yes this is something for the future. It was out of scope for that pr.
