### ISSUE TITLE
Problem running my-first-jina-app. When I run to [this step](https://docs.jina.ai/chapters/my_first_jina_app/#index-flow) `python app.py -t index` error occurs

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2151]
When I run to [this step](https://docs.jina.ai/chapters/my_first_jina_app/#index-flow) `python app.py -t index` error occurs
```
/jina_env/lib/python3.7/site-packages/jina/importer.py:267: UserWarning: due to the missing dependencies or bad implementations, ['jina.hub.encoders.nlp.CLIPTextEncoder'] can not be imported if you are using these executors/drivers, they wont work. You can use `jina check` to list all executors and drivers
  f'due to the missing dependencies or bad implementations, '
Traceback (most recent call last):
  File "app.py", line 62, in <module>
    raise NotImplementedError(f'unsupported mode {sys.argv[1]}')
NotImplementedError: unsupported mode -t
```
;( , follow this guide  `python app.py -t index` contain` -t`, but in `app.py` not implement that, I remove -t , It's run. 
Waste your time :(

_Originally posted by @huanbd in https://github.com/jina-ai/jina-hub/issues/5785#issuecomment-796634466_

**Comment by FionnD** [comment]
This issue originally comes from this ticket https://github.com/jina-ai/jina-hub/issues/5785#issuecomment-796634466

**Comment by FionnD** [comment]
I tried to reproduce this issue but couldn't. Closing the issue for the moment.
