### ISSUE TITLE
Allow batching in indexers

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2156]
# Feature Request | Maintenance

Based on the work in this [issue](https://github.com/jina-ai/jina/issues/2097), further work is required to implement the changes into the indexers.  

# Acceptance Criteria

- This ticket is done when: It will be possible to batch in a query  for Indexers (Vector and KV). This includes;

  - BaseKVIndexer 

  - BaseNumpyIndexer

  - BaseVectorIndexer

  - `NumpyIndexer`

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7283329

**Comment by JoanFM** [comment]
This should include more `indexers` in the `hub`

**Comment by JoanFM** [comment]
@FionnD @nan-wang this is a breaking change for those clients (which we now we have) that inherit their own indexer implementation. 

Would you prefer to add a workaround to support old one? (It would not be big trouble though and easy to adapt)

**Comment by FionnD** [comment]
Anything that prevents breaking changes is good from a product point of view ❤️
