### ISSUE TITLE
Allow batching in selected hub executors

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2157]
# Feature Request | Maintenance

Based on the work in this [issue](https://github.com/jina-ai/jina/issues/2097), further work is required to implement the changes into all drivers and hub executors 

# Acceptance Criteria

- Go driver per driver, allowing batching to each of them. For each of them go to its executors in the hub add [@single](https://github.com/single) decorator added in [#2098](https://github.com/jina-ai/jina/pull/2098).

-  For each of the drivers in previous step, refactor its executors that can be batched into using batch decorators

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7283330

**Comment by JoanFM** [comment]
The segmenters where it was more important are fixed. New refactoring will change everything, closing it now
