### ISSUE TITLE
🚨 BREAKING CHANGES 1.0-> 1.1

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2168]
# 🚨 BREAKING CHANGES 1.0 -> 1.1

This issue is created to keep track of breaking changes between `1.0` and `1.1` (scheduled release on {{ date }})

## Breaking Changes & Migration Guide
| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1975 | Yes |  |

- Remove the CLI option `--optimize-level` 

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #2033 | Yes  | |

- Remove unused `PipelineEncoder`

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1296 | Yes  | |

- Replace `is_merge` argument with `is_update` in `KVSearchDriver`.

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1973  | Yes  | |

- Rename the column names in `BaseRanker`

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #1985  | Yes  | |

- Refactor CLI for running `jina hello-world`. `jina hello-world` is deprecated. `jina hello mnist`, `jina hello chat-bot` are added

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #2003  | Yes  | |

- Remove `PipeLogger`

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #2044  | Yes  |  #2061|
| #2061  | Yes  |  |

- Add keyword `jtype` to represent YAML tag

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
| #2050  | Yes  |  |

- Replace `DockerKwargsAppendAction` with `KVAppendAction` in CLI 

----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
|  #2122 | Yes  | |

- Rename `--silent-remote-logs` to `--quiet-remote-logs`.

## Template
----

| PR |  Rolled Out? | Override |
| --- | --- | --- |
|  | Yes  | |

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.0 </td>
<td> 1.1 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
old codes
```

</sub> </td>
<td> <sub> 

```python
new codes
```

</sub> </td>
</tr>
</table>

---

**Comment by JoanFM** [comment]
the required traversal paths for Chunk2DocRanker

**Comment by florian-hoenicke** [comment]
In case it is merged, this one would cause a breaking change:
https://github.com/jina-ai/jina/pull/2198

**Comment by cristianmtr** [comment]
This one would be a breaking change too, if we do merge it https://github.com/jina-ai/jina/pull/2242

It would break loading a Flow from a previous version, as the pea ids would not align anymore

**Comment by nan-wang** [comment]
> This one would be a breaking change too, if we do merge it #2242
> 
> It would break loading a Flow from a previous version, as the pea ids would not align anymore

#2242 replaces #2143 which is merged after 1.0. Plus, would you elaborate on aligning pea ids? @cristianmtr

**Comment by cristianmtr** [comment]
> > This one would be a breaking change too, if we do merge it #2242
> > It would break loading a Flow from a previous version, as the pea ids would not align anymore
> 
> #2242 replaces #2143 which is merged after 1.0. Plus, would you elaborate on aligning pea ids? @cristianmtr

Sure. Before pea ids started at index `1` when `parallel > 1`. This would cause some issues/further effort in the ongoing dump/reload feature. There was also no reason why it was like that. It was only a question of going through a lot of our tests and fixing them to not rely on this path.
