### ISSUE TITLE
Research how to allow NumpyIndexer to handle sparse vectors

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2183]
# Feature Request

This ticket is a sub compound of implementing sparse vector functionality to Jina. Currently, there is some low-level code implementation to support sparse vectors.  Over the course of this epic we will implement the remaining logic. Main goal is to be able to build a fully neural search system where embedding representations are `sparse vectors`. This will support certain usecase like TD-IDF, and provide the functionitilty for graph embedding in the future. 

<p></p>

For this ticket, you should research what steps need to be taken to allow the current numpyindexer to handle sparse vectors.  Provided these steps are reasonable, you should implement them. Otherwise, we should have a design discussion about them. 

# Acceptance Criteria

- The numpyindexer should be able to handle sparse vectors. 

<p></p>

<p></p>

<p></p>

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7331499

**Comment by bwanglzu** [comment]
Given the fact that supporting sparse vectors in numpy indexer needs tremendous refactoring, we will not invest time on this ticket, but use ANN to index & query
