### ISSUE TITLE
Create TF-IDF encoder for sparse vectors

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2184]
# Feature Request

This ticket is a sub compound of implementing sparse vector functionality to Jina. Currently, there is some low-level code implementation to support sparse vectors.  Over the course of this epic we will implement the remaining logic. Main goal is to be able to build a fully neural search system where embedding representations are `sparse vectors`. This will support certain usecase like TD-IDF, and provide the functionitilty for graph embedding in the future. 

<p></p>

<p></p>

# Acceptance Criteria

- We need to be able to embed `documents` into `sparse` vector representations.

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7331505

**Comment by davidbp** [comment]
This was done in #7458 and further improved in  #7789, #7775, #7684
