### ISSUE TITLE
Integration tests for all sparse vectors compounds

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2186]
# Maintenance Ticket

<p></p>

For the four tickets. 

1. Allow sparse vectors to be stored 

2. Allow NumpyIndexer to handle sparse vectors 

3. Create encoder for sparse vectors 

4. Create ANN for sparse vectors 

<p></p>

A suite of integration tests should be written to test end to end functionality of these features.

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/7331517

**Comment by JoanFM** [comment]
NumpyIndexer should only be considered if changes are minimal
