### ISSUE TITLE
Regression test for all three hello-world demos

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#2193]
**Describe the feature**

hello-world examples are important, if it breaks for a first-time user, then we lose this user.

The current tests on hello-world is not enough, it does not check (1) if index/search is successful (2) the sanity of retrieved results. 

**Your proposal**

Please add regression test for three hello-world.

---

**Environment**

**Screenshots**

Tasks: 
- [x] helloworld 
- [x] multimodal
- [x] chatbot
- [x] ci/cd pipeline

**Comment by JoanFM** [comment]
Example for multimodal can be taken from reverted change in #2178. It was reverted for other reasons, but the test would still be valid

**Comment by bwanglzu** [comment]
glad to work on it with other engineers.

**Comment by JoanFM** [comment]
Multimodal helloworld has already been added, please add the other integration tests in the same subfolders

**Comment by JoanFM** [comment]
One thing to be aware of.

Adding these tests, make the tests dependant on the `hub` submodule, which will bring to a situation where the tests in core do not pass because the hub needs an update and the hub will not be updatable because the new core version is not released

**Comment by JoanFM** [comment]
@bwanglzu can u make sure the helloworld examples tests are moved to their own folder independent of integration tests? Like this we can easily skip it when necessary much easier

**Comment by bwanglzu** [comment]
@JoanFM I will
