### ISSUE TITLE
Convert Driver error during running Cross and Multi modal example with `1.0.10`

### ISSUE THREAD

**Issue by rutujasurve94** [jina-ai/jina#2194]
**Describe the bug**
Convert Driver throws `Module Not Found` error during running Cross and Multi modal example with `1.0.10`

![image](https://user-images.githubusercontent.com/9448002/111427971-e6720c00-871c-11eb-8592-5f4e5067b863.png)

This is an issue with Jina version `1.0.10`, potential reason could be renaming of `convert` driver to `convertdriver`.

Blocks indexing of docs in Cross and Multi modal search examples.

**Comment by JoanFM** [comment]
the file should be called convert and not convertdriver

**Comment by FionnD** [comment]
@rutujasurve94 please reach out to Max on Monday about this issue. He offered to guide you on implementing the solution if you are interested?

**Comment by rutujasurve94** [comment]
@FionnD yes sure
