### ISSUE TITLE
⚠️ Refactor rename length attribute to siblings - breaking change

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2201]
As requested by @hanxiao, the length attribute needs to be changed to siblings.
This implies breaking changes in the

examples
hub
documentation

**Comment by florian-hoenicke** [comment]
@hanxiao as discussed with @JoanFM,
The `length` attribute is neither used in the hub nor in the examples.
Should we delete the attribute instead of renaming?
If this attribute is meaningful to someone, they can have it within the tags of the document.

**Comment by JoanFM** [comment]
it is not so easy to have it as tags of the document, but anyway, I do not think is enforced and this enforcement can be too costly.

I think we have the risk of users assuming this always holds true and have missleading information

**Comment by florian-hoenicke** [comment]
@JoanFM Okay I see, it is not even always set correctly

@hanxiao would you agree to remove the length parameter completely?
