### ISSUE TITLE
Indexing with examples (crossmodal) halts due to insufficient resources

### ISSUE THREAD

**Issue by rutujasurve94** [jina-ai/jina#2202]
Indexing using:
` python app.py -t index -n 100 -s 2 -d 'f8k' -m clip` for cross modal search example with 12 GB RAM allocated for Docker and 6 cores. The indexing hangs after the 11th IndexRequest from Gateway.

**Screenshots**
<img width="1302" alt="Screenshot 2021-03-18 at 12 13 17 PM" src="https://user-images.githubusercontent.com/9448002/111584094-6c588a80-87e3-11eb-9f3d-563f49b6c682.png">

**Comment by Huffon** [comment]
Same issue. But is this related to computation resources?

**Comment by FionnD** [comment]
@bwanglzu to try and reproduce

**Comment by FionnD** [comment]
Hi @bwanglzu 
Did you manage to do this?

**Comment by bwanglzu** [comment]
working on this today @FionnD

**Comment by bwanglzu** [comment]
lower down the request size with jina 1.0 should resolve the issue. While during debugging, figured out another bug, after 1.1.7 release.

**Comment by FionnD** [comment]
Is there a PR for that bug?

**Comment by FionnD** [comment]
For the request size issue, can you open a PR with the [same troubleshooting tips, please? ](https://github.com/jina-ai/examples/pull/615). Then we can close this issue.
