### ISSUE TITLE
Input-generators are not longer working for delete!

### ISSUE THREAD

**Issue by nero-nazok** [jina-ai/jina#2214]
**Version**
Jina 1.0.8: everthing works as expected
Jina 1.0.11 (latest): no documents are deleted

**Description**
I use an async generator as input. Unfortunately, this does no longer work for delete. Async generators still work for indexing. When performing the delete no error is raised, but jina just deletes no documents. When I pass the ids as a plain list everything works fine.

**Code sample**
```
async def input_fn():
  for id in [...]:  # provide the ids here!! (I retrieve them from a database.)
    yield id

with AsyncFlow.load_config('./flow.yml') as f:
    async for entry in f.delete(input_fn):
        print(entry)
```

**Comment by cristianmtr** [comment]
I'm not sure I understand how it ever worked for issue an async generator for the list of ids. The code on the Flow has not changed between 1.0.8 and 1.0.11

**Comment by florian-hoenicke** [comment]
@nero-nazok does a synchronous generator function work for you?
like this:
~~async~~ 
```
def input_fn():
  for id in [...]:  # provide the ids here!! (I retrieve them from a database.)
    yield id

with AsyncFlow.load_config('./flow.yml') as f:
    async for entry in f.delete(input_fn):
        print(entry)
```

**Comment by ace-kay-law-neo** [comment]
@nero-nazok I ran into the exact same problem. I use docker and somehow a stale, cached jina-version was used. Deleting the image & rebuilding solved it.

**Comment by nero-nazok** [comment]
Thank you @ace-kay-law-neo deleting & rebuilding resolved the problem. Sorry for taking your time @cristianmtr and @florian-hoenicke.
