### ISSUE TITLE
Introduce replicas

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2235]
Reload pod during flow execution.

A variety of upcoming features need query while indexing or query while training...
Our approach is to have a separation between the data layer for the crud operations and the query instances.
Following our approach, we need to create two query instances as replicas - one for answering the incoming queries and one for building up the new index.

We discussed 4 possible implementations each on a different abstraction level.

~1. a thread within an executor
2. a thread within ZedRuntime
3. recreating entire peas
4. recreating entire pods~
5. creating a new abstraction inside a Pod, on top of Peas -- **Replica**

# Update 24.03.2021

@JoanFM came up with the idea of a new Replica abstraction level between pods and peas. The implementation is changed accordingly as shown in the following slides: 

https://docs.google.com/presentation/d/1SdEopa7vjiHKjBfsnzha4WmRBXqWpSGTR4Njx00-XIE/edit?usp=sharing

- [x] replica level is introduced
- [x] replica can be reloaded (shut down and start)
- [ ] we have a fixed number of replicas
- [ ] when not using replicas, nothing is changed to our current pea configuration
- [ ] always make the most simple configuration (never configure peas which are not needed)
- [ ] rename parallel to shards
- [ ] when `use before` or `use after` is configured head and tail do not merge into pea
- [ ] no major breaking changes. All yaml configurations are still valid and behave the same way.
- [ ] documentation about replicas
- [ ] naming convention and logging for replica and pea are discussed and adjusted: 
e.g. recv ControlRequest  from ctl▸pod0/replica1/pea1/ZEDRuntime▸⚐
- [ ] peas close asynchronously using send_message_async, ongoing requests are not failing
- [ ] new peas are created asynchronously 
- [ ] replica can be terminated at any point of time without causing deadlocks.  https://github.com/jina-ai/jina/issues/2255 (needs to be merged into `master`)
- [ ] separated workspaces for replicas (take worspace from configuration and append '_{replica_id}'
- [ ] no errors are shown in the output
- [ ] flow.plot() for visualization of parallel and replicas (wait until implementation is done)
- [ ] REST endpoint for the rolling update functionality is made
- [ ] add replicas to cli auto complete
- [ ] rename parallel to shards

**Comment by FionnD** [comment]
Following a chat with team leads / CTO this morning. We will _not_ mention replicas in 1.2 release notes, but rather way until they are correctly documented which will likely be in 1.3.

**Comment by JoanFM** [comment]
Flow Plot has been tested to capture the replication structure?
