### ISSUE TITLE
How can i integrate a BERT based executor with anserini to construct a compose indexer ?

### ISSUE THREAD

**Issue by svjack** [jina-ai/jina#2238]
I have used anserini to generate a index by lucene and can use https://github.com/castorini/pyserini/blob/98f323659c8a0a5d8ef26bb3f6768458a34e3eb9/pyserini/vectorizer/_base.py
to generate its dense representation.
And i also want to integrate this with BERT executor, as [your example](https://github.com/jina-ai/examples/tree/master/chinese-text-search) do.
Which part should i actually care about ?
all about program entry point of query anserini style dense generate , merge scores between anserini and BERT.
define my own segment func ,
driver’s exec_fn overwrite in multi class.

Thank you.

**Comment by svjack** [comment]
I also want to have a brief introduction about the underlying logic of deal with long form text.
with some aggregate class defined in jina’s rank dir(which may relate with show some info about ‘parent’ doc)

**Comment by nan-wang** [comment]
hi, @svjack Would you please share your codes somewhere? So that we can take a look together. Jina has quite flexible usages and you can always plug Jina into your pipeline.

**Comment by svjack** [comment]
> hi, @svjack Would you please share your codes somewhere? So that we can take a look together. Jina has quite flexible usages and you can always plug Jina into your pipeline.

Can you explain some logic of after set yaml path in volumes in https://github.com/jina-ai/jina/blob/e4bda7a872d2e24356e8aa2afc5f17df04dcd16e/jina/peapods/runtimes/container/__init__.py
the truly init logic of use BaseExecutor.load_config in your code.
All about the recycle of its construction.

**Comment by svjack** [comment]
Take segmenter as a example.
it seems like call load_executor in https://github.com/jina-ai/jina/blob/640daf4d389768be216dac4125ef4e837ee65d23/jina/peapods/runtimes/zmq/zed.py
after init Pod.
How can i debug my code after retrieve Pod from Flow (by getitem),
i can use BaseExecutor.load_config as an indirectly way, how can i
do it from Flow as entry ?

**Comment by svjack** [comment]
And can you explain your with closure usage in this project.
Where is your “release” logic in the code (all about Flow and Pod)?

**Comment by svjack** [comment]
> Take segmenter as a example.
> it seems like call load_executor in https://github.com/jina-ai/jina/blob/640daf4d389768be216dac4125ef4e837ee65d23/jina/peapods/runtimes/zmq/zed.py
> after init Pod.
> How can i debug my code after retrieve Pod from Flow (by getitem),
> i can use BaseExecutor.load_config as an indirectly way, how can i
> do it from Flow as entry ?

I don’t want to send requests to debug. but use class

**Comment by svjack** [comment]
I think i can call start of Pod to explore pea. from Flow

**Comment by bwanglzu** [comment]
@svjack HI, thanks so much for your message! Would you like to submit a draft pull request on what you proposed, i.e. `BaseSegmenter` and we'll see how it differs from the current implementation and why our test suit did not find the bug.

**Comment by JoanFM** [comment]
Hey @svjack,

I do not understand your problem.

It seems that u want to extract an executor from a Flow instance. But that is not possible because Executors are instantiated in different Processes than the main one containing Flow.

So Flow does not have access to the Executor in memory

**Comment by FionnD** [comment]
I'm closing this issue. If the question is not answered please reopen :)
