### ISSUE TITLE
Minor error in the README.md

### ISSUE THREAD

**Issue by carlosb1** [jina-ai/jina#2247]
**Describe the bug**

I see an minor problem in the README.md, 

```
import numpy
from jina import Document

d0 = Document(id='🐲', embedding=np.array([0, 0]))
d1 = Document(id='🐦', embedding=np.array([1, 0]))
d2 = Document(id='🐢', embedding=np.array([0, 1]))
d3 = Document(id='🐯', embedding=np.array([1, 1]))

d0.chunks.append(d1)
d0.chunks[0].chunks.append(d2)
d0.matches.append(d3)
d0.plot()  # simply `d0` on JupyterLab`
```

it can not be `np`.

**Describe how you solve it**
Well. very easy to fix... use `numpy` or  `as np`

**Comment by bwanglzu** [comment]
@carlosb1 nice catch appreciate that! Would you like to fix this for us and become a contributor?

**Comment by bwanglzu** [comment]
thanks so much @carlosb1 ! I'll close this issue!
