### ISSUE TITLE
Support Dynamic QueryLang

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2250]
**[Design discussion / refinement meeting needed]** 

<p></p>

**Currently:** You have a shop with ten categories (shoes, bags, coats etc). When a user searches your index for shoes, you only want to return shoes. To design this use case you would need to create a unique YAML file per category which accepts each unique tag and creates a unique index.  
``  
`index_shoes.yml  
index_bags.yml``````

**Feature request:**

<p></p>

You have a shop with a hundred categories. A user searches for shoes, and you only want to return shoes.  
You should be able to create one pod. The YAML file should dynamically accept a tag and choose which of the hundred indexes to retrieve from.!FilterQL with:  lookups: {'tags__label':'user_query_tag'}`  

<p></p>

**Design discussion questions** 

1. Can new indexes be created or will the YAML only accept a pre-defined list of tags? 

2. How does the YAML accept the tags? Rest API? 

3. Will this be implemented for all drivers?

**Comment by lusloher** [comment]
Link to subfeature: https://jinaai.productboard.com/feature-board/planning/features/6941835

**Comment by JoanFM** [comment]
I think this can be handled by.

1. Adding at Document or Request level a 'collection' label. (preferably Request level)
2. Create a new CompoundIndexer that creates one NumpyIndexer per collection when arrives. (It is like a redirection)
3.  At query time, target also the set of collections accepted in the Query Request.

**Comment by FionnD** [comment]
Closing this issue till we have the next meeting.
