### ISSUE TITLE
Fix length -> sibling

### ISSUE THREAD

**Issue by lusloher** [jina-ai/jina#2254]
Based on the PR which renamed the length attribute to sliding, the following tasks need to be completed to ensure Jina is up to date. 

### Acceptance Criteria
This ticket is done when: You have reviewed the doc and updated any reference to length. 
This ticket is done when: You have reviewed the hub modules and fixed any which used length. The bimatchranker is one.

**Comment by lusloher** [comment]
Link to feature: https://jinaai.productboard.com/feature-board/planning/features/7471604

**Comment by FionnD** [comment]
@florian-hoenicke how does this look to you? Everything that needs to be done is captured?

**Comment by florian-hoenicke** [comment]
https://github.com/jina-ai/jina-hub/pull/7456
https://github.com/jina-ai/jina-hub/pull/7457
https://github.com/jina-ai/docs/pull/224
@FionnD yes, as soon as these prs went through, it is done

**Comment by nan-wang** [comment]
> [jina-ai/jina-hub#7456](https://github.com/jina-ai/jina-hub/pull/7456)
> [jina-ai/jina-hub#7457](https://github.com/jina-ai/jina-hub/pull/7457)
> [jina-ai/docs#224](https://github.com/jina-ai/docs/pull/224)
> @FionnD yes, as soon as these prs went through, it is done

merged
