### ISSUE TITLE
Refactor `BaseNumpyIndexer` to work with a vector of indices

### ISSUE THREAD

**Issue by davidbp** [jina-ai/jina#2286]
Refactor `BaseNumpyIndexer` to improve speed (and probably memory):

- Instead of storing a vector of booleans equal to the dataset size, store only the indices that users want to remove (or want to keep).

##### What is the  benefit?

The benefits are twofold:
     - Faster index time in a numpy array (see benchmark below)
     - Less operations in the codebase that cost execution time
     
There are many places  where there is the need to iterate over all the examples in memory that would not be needed:

- **`_add function`**:  `self.valid_indices = np.concatenate(  (self.valid_indices, np.full(len(keys), True)) )`
- **`_raw_ndarray`**: `deleted_keys = len(self.valid_indices[self.valid_indices == False]) `
- **`int3ext_id`**:  `deleted_keys = len(self.valid_indices[self.valid_indices == False])`

#### Benchmark 

```python
import numpy as np
import pandas as pd

sizes = np.linspace(1000,100_000, 10)

flags_times = []
indices_times = []
for s in sizes:
    s = int(s)
    x = np.random.rand(s)
    print(f'Number elements = {s}')
    indices = np.random.choice(len(x), size= s//4, replace=False)
    
    # slicing using vector of booleans
    flag = np.zeros(len(x), dtype=bool)
    flag[indices]=True
    
    print('boolean flag:')
    t_flag = %timeit -o x[flag]

    # slicing using directly the coordinates
    print('vector of indices:')
    t_indices = %timeit -o x[indices]
    
    flags_times.append(t_flag.average)
    indices_times.append(t_indices.average)

df = pd.DataFrame({'boolean flag': flags_times,
                   'vector of indices': indices_times})

df.index =sizes
df = df*10**6
df.plot(title='slicing with vector of booleans vs vector of indices', 
        xlabel='Number of elements in the array',
        ylabel='time (ms)')
```

Output:

![scalability](https://user-images.githubusercontent.com/4223580/113878571-021b8000-97ba-11eb-9f27-ae5253c2c844.png)

Note: The speed benefit slicing in  multidimensional arrays is less noticeable (almost irrelevant) but the memory costs and other array iterations might be removed.

**Comment by JoanFM** [comment]
What about querying while filtering only valid entries?

**Comment by davidbp** [comment]
> What about querying while filtering only valid entries?

I did not point out anything related to this. I think it is possible to rewrite the code doing 'the same' .

**Comment by JoanFM** [comment]
Sure, just notice when implementing this, to make sure that query time does not suffer

**Comment by JoanFM** [comment]
the point of having an array of booleans I guess is to have a quick lookup for quick query

**Comment by FionnD** [comment]
@davidbp is this part of the ongoing EPIC on sparse vectors?

**Comment by davidbp** [comment]
> @davidbp is this part of the ongoing EPIC on sparse vectors?

No, not realted

**Comment by JoanFM** [comment]
Looking at this, I think it makes sense, even more when we are separating Indexing and Querying totally.

**Comment by FionnD** [comment]
@JoanFM let's talk about this in standup tomorrow.

**Comment by FionnD** [comment]
Hi Guys, 

What the status of this? Is it something we have time to work on now? 

CC @davidbp @JoanFM

**Comment by JoanFM** [comment]
no, plus with 2.0 may not be relevant anymore

**Comment by FionnD** [comment]
If 2.0 remove it, can I close it?

**Comment by JoanFM** [comment]
yes
