### ISSUE TITLE
Split Indexers into DBMS and Query

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#2289]
Continuation of https://github.com/jina-ai/jina/pull/2260

The core indexers (and eventually Hub Indexers) should no longer inherit from `BaseIndexer` directly, but either from `DBMSIndexer`, or from `QueryIndexer`.

**Comment by FionnD** [comment]
Hey @cristianmtr 

We need more information within the requirements of this ticket if I am to add it to the backlog. So it's easier for someone to pick up downstream. Can you either update it or jump on a call with me and we'll do it together?

**Comment by FionnD** [comment]
I will close this issue on Monday afternoon if there's no update. 🌵

**Comment by cristianmtr** [comment]
This is going be done in 2.0, from what I understand. 

Right, @maximilianwerk @JoanFM ?

We've talked about it in meetings, I remember. Indexers should be either of type DBMS (write interface is `ids, vecs, metas`) or of type Query (write-once and  inteface `(ids, vecs)` or `(ids, metas)`). Right now
