### ISSUE TITLE
Cannot run fashion demo

### ISSUE THREAD

**Issue by assist726** [jina-ai/jina#2290]
running with 
`
docker run -v "$(pwd)/j:/j" jinaai/jina hello fashion --workdir /j && open j/hello-world.html
`

This process takes about a minute and then ends up stuck with the following logs:

If I docker exec it appears that there is no html file generated in the j folder either

`
     index/tail@34[I]:#sent: 58 #recv: 59 sent_size: 103.7 MB recv_size: 104.8 MB
index |███████████████████ | 📃  60416 ⏱️ 45.3s 🐎 1332.3/s     59   requests    45 seconds (45.36s)
        gateway@48[I]:#sent: 59 #recv: 59 sent_size: 30.4 MB recv_size: 104.8 MB
        ✅ done in ⏱ 45 seconds 🐎 1331.8/s
        gateway@ 1[S]:terminated
        index/1@45[I]:recv ControlRequest  from ctl▸index/1/ZEDRuntime▸⚐
     index/head@26[I]:recv ControlRequest  from index/1▸index/head/ZEDRuntime▸⚐
     index/head@26[I]:#sent: 120 #recv: 121 sent_size: 112.7 MB recv_size: 112.6 MB
        index/1@45[I]:#sent: 61 #recv: 30 sent_size: 51.8 MB recv_size: 55.7 MB
        index/1@45[I]:The dealer index/1 can not unsubscribe from the router. In case the router is down this is expected.
  VectorIndexer@45[I]:indexer size: 29696 physical size: 14.5 MB
  VectorIndexer@45[S]:artifacts of this executor (vecidx) is persisted to /j/chunk_indexer-1/vecidx-1/vecidx.bin
KeyValueIndexer@45[I]:indexer size: 29696 physical size: 67.7 MB
KeyValueIndexer@45[S]:artifacts of this executor (chunkidx) is persisted to /j/chunk_indexer-1/chunkidx-1/chunkidx.bin
  VectorIndexer@45[I]:no update since 2021-04-08 08:26:20, will not save. If you really want to save it, call "touch()" before "save()" to force saving
KeyValueIndexer@45[I]:no update since 2021-04-08 08:26:20, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        index/1@45[I]:no update since 2021-04-08 08:25:33, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        index/1@ 1[S]:terminated
        index/0@42[I]:recv ControlRequest  from ctl▸index/0/ZEDRuntime▸⚐
     index/head@26[I]:recv ControlRequest  from index/0▸index/head/ZEDRuntime▸⚐
     index/head@26[I]:#sent: 121 #recv: 122 sent_size: 112.7 MB recv_size: 112.6 MB
        index/0@42[I]:#sent: 63 #recv: 31 sent_size: 53.0 MB recv_size: 57.0 MB
        index/0@42[I]:The dealer index/0 can not unsubscribe from the router. In case the router is down this is expected.
  VectorIndexer@42[I]:indexer size: 30304 physical size: 14.8 MB
  VectorIndexer@42[S]:artifacts of this executor (vecidx) is persisted to /j/chunk_indexer/vecidx-0/vecidx.bin
KeyValueIndexer@42[I]:indexer size: 30304 physical size: 69.2 MB
KeyValueIndexer@42[S]:artifacts of this executor (chunkidx) is persisted to /j/chunk_indexer/chunkidx-0/chunkidx.bin
  VectorIndexer@42[I]:no update since 2021-04-08 08:26:20, will not save. If you really want to save it, call "touch()" before "save()" to force saving
KeyValueIndexer@42[I]:no update since 2021-04-08 08:26:20, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        index/0@42[I]:no update since 2021-04-08 08:25:33, will not save. If you really want to save it, call "touch()" before "save()" to force saving
        index/0@ 1[S]:terminated
     index/tail@34[I]:recv ControlRequest  from ctl▸index/tail/ZEDRuntime▸⚐
     index/tail@34[I]:#sent: 60 #recv: 60 sent_size: 104.8 MB recv_size: 104.8 MB
     index/tail@34[I]:no update since 2021-04-08 08:25:33, will not save. If you really want to save it, call "touch()" before "save()" to force saving
     index/tail@ 1[S]:terminated
     index/head@26[I]:recv ControlRequest  from ctl▸index/head/ZEDRuntime▸⚐
`

**Comment by cristianmtr** [comment]
I couldn't reproduce this locally. Ran same command. 

What's your docker version?

```
$ docker --version
Docker version 20.10.5, build 55c4c88
```

Did you have the jina image already cached locally?

**Comment by assist726** [comment]
> I couldn't reproduce this locally. Ran same command.
> 
> What's your docker version?
> 
> ```
> $ docker --version
> Docker version 20.10.5, build 55c4c88
> ```
> 
> Did you have the jina image already cached locally?

Docker version 20.10.5, build 55c4c88

Same as yours, and the Jina image was pulled today using :latest

**Comment by cristianmtr** [comment]
Can you paste more logs from the run? Also can you try with a different folder (might be some permissions problems?)

**Comment by JoanFM** [comment]
Hey @assist726 ,

Could you see if the issue appeared after indexing, or after doing all the searches?

It seems that the Jina Flow was closed properly actually ...

**Comment by assist726** [comment]
@cristianmtr @JoanFM Bizarrely re running it today and it's now working, nothing has changed in my environment.

It previous never got to the search and only indexed, thanks for the help in any case!
