### ISSUE TITLE
No documents are found with BinaryPbIndexer in 1.1.2

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/jina#2295]
**Versions**
1.0.11: everything works as expected
1.1.2: BinaryPbIndexer doesn't find any documents

**Detailed description**
He Jina team, when I upgrade to 1.1.2 and reindex my dataset, the BinaryPbIndexer no longer works. It doesn't raise any errors, but I just can't find any documents. Just as a remark, I use custom ids which always consist of 33 characters. Where there any changes for the BinaryPbIndexer, the KVIndexDriver or the KVSearchDriver?

**Comment by JoanFM** [comment]
Hello @janandreschweiger,

This is very weird. Are you sure you removed the workspace before reindexing? Are there any logs or something u can find? When u load the `search` flow  specially?

**Comment by janandreschweiger** [comment]
Hallo @JoanFM, thanks again for helping me out. I tried it again a few minutes ago and removed the workspace properly. The strange thing is that everything works fine for version 1.0.11 and there are no error in the logs. I added some custom logs in the drivers to make sure that error isn't caused by my code.

**Indexing:**
```
doc_idx@75[I]:recv IndexRequest  from gateway▸crafter/ZEDRuntime▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸doc_idx/ZEDRuntime▸⚐
MY CUSTOM LOG: Successfully indexed 15541c57d504d4b7fa8d65a605365be02
```

**Search-Flow-Loading:**
```
        encoder@18[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
        encoder@18[I]:input tcp://0.0.0.0:44987 (PULL_BIND) output tcp://0.0.0.0:37875 (PUSH_CONNECT) control over tcp://0.0.0.0:56127 (PAIR_BIND)
      chunk_idx@21[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
      chunk_idx@21[I]:input tcp://0.0.0.0:37875 (PULL_BIND) output tcp://0.0.0.0:40301 (PUSH_CONNECT) control over tcp://0.0.0.0:55091 (PAIR_BIND)
SentenceEncoder@18[I]:post_init may take some time...
SentenceEncoder@18[I]:post_init may take some time takes 0 seconds (0.00s)
SentenceEncoder@18[S]:successfully built SentenceEncoder from a yaml config
         ranker@24[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
         ranker@24[I]:input tcp://0.0.0.0:40301 (PULL_BIND) output tcp://0.0.0.0:59797 (PUSH_CONNECT) control over tcp://0.0.0.0:53689 (PAIR_BIND)
        doc_idx@27[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
        doc_idx@27[I]:input tcp://0.0.0.0:59797 (PULL_BIND) output tcp://0.0.0.0:53123 (PUSH_BIND) control over tcp://0.0.0.0:40513 (PAIR_BIND)
SimpleAggregateRanker@24[I]:post_init may take some time...
SimpleAggregateRanker@24[I]:post_init may take some time takes 0 seconds (0.00s)
        encoder@ 7[S]:ready and listening
SimpleAggregateRanker@24[S]:successfully built SimpleAggregateRanker from a yaml config
        gateway@30[I]:starting jina.peapods.runtimes.asyncio.grpc.GRPCRuntime...
        gateway@30[I]:input tcp://0.0.0.0:53123 (PULL_CONNECT) output tcp://0.0.0.0:44987 (PUSH_CONNECT) control over ipc:///tmp/tmpql1p3hs2 (PAIR_BIND)
SearchDocIndexer@27[I]:post_init may take some time...
SearchDocIndexer@27[I]:post_init may take some time takes 0 seconds (0.00s)
        gateway@30[S]:GRPCRuntime is listening at: 0.0.0.0:34147
SearchDocIndexer@27[S]:successfully built SearchDocIndexer from a yaml config
   NumpyIndexer@21[I]:post_init may take some time...
   NumpyIndexer@21[I]:post_init may take some time takes 0 seconds (0.00s)
   NumpyIndexer@21[S]:restore NumpyIndexer from /var/huforce/fs/workspace/wrap_idx-0/wrap_idx.bin
BinaryPbIndexer@21[I]:post_init may take some time...
BinaryPbIndexer@21[I]:post_init may take some time takes 0 seconds (0.00s)
BinaryPbIndexer@21[S]:restore BinaryPbIndexer from /var/huforce/fs/workspace/chunk_idx-0/chunk_idx.bin
CompoundIndexer@21[I]:post_init may take some time...
CompoundIndexer@21[I]:post_init may take some time takes 0 seconds (0.00s)
CompoundIndexer@21[S]:successfully built CompoundIndexer from a yaml config
      chunk_idx@ 7[S]:ready and listening
         ranker@ 7[S]:ready and listening
        doc_idx@ 7[S]:ready and listening
        gateway@ 7[S]:ready and listening
      AsyncFlow@ 7[I]:5 Pods (i.e. 5 Peas) are running in this Flow
```

**Search:**
```
 doc_idx@27[I]:recv SearchRequest  from gateway▸encoder/ZEDRuntime▸chunk_idx/ZEDRuntime▸ranker/ZEDRuntime▸doc_idx/ZEDRuntime▸⚐
 doc_idx@27[I]:indexer size: 0
MY CUSTOM LOG: Search could not find 15541c57d504d4b7fa8d65a605365be02
```

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

I believe it could be due to this PR 
 (https://github.com/jina-ai/jina/pull/2243).

Will try to fix this asap. Could you provide a minimal flow example where u see this happening?

**Comment by janandreschweiger** [comment]
Sure @JoanFM.

**Index-Flow:**
```
!AsyncFlow
pods:
  crafter:
    uses: craft-pod.yml
  encoder:
    uses: encode-pod.yml
  chunk_indexer:
    uses: chunk-pod.yml
  doc_indexer:
    uses: doc-pod.yml
```

**Search-Flow:**
```
!AsyncFlow
with:
  return_results: true
pods:
  encoder:
    uses: encode-pod.yml
  chunk_indexer:
    uses: chunk-pod.yml # chunks are found correctly
  ranker:
    uses: rank-pod.yml
  doc_indexer:
    uses: search-pod.yml # documents cannot be found
```

Although both the chunk-indexer and the doc-indexer use the BinaryPbIndexer only the documents cannot be found. The only difference is that I use custom ids for the doc-indexer.

**Comment by janandreschweiger** [comment]
Hey @JoanFM, this PR is most probably the cause of my issue. I just tested it with Jina v1.1.0 and everything works as expected.

**Comment by JoanFM** [comment]
I guess the structure is similar to the wikipedia example?

Could you pleaae share a snapshot of the files encountered in the workspace after indexing? and let us know how many shards you are using?

**Comment by janandreschweiger** [comment]
Sure @JoanFM. I don't have any shards-settings, so I assume I only use one. I will provide you with my workspace in a few hours, because I have to attend a meeting.

**Comment by janandreschweiger** [comment]
Hey @JoanFM. Sorry for letting you wait. We had some severe issues that needed to be addressed. I have uploaded my workspace after indexing, as requested by you:
https://github.com/janandreschweiger/jina_workspace

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

Looking at your workspace, it seems that the issue is that the name of the executor in the search Flow is not the same as the one at index time, therefore the Executor is not able to load the executor metadata to successfully interpret the index.

Can you check if that is correct?

**Comment by JoanFM** [comment]
So in the index-pod.yml and the search-pod.yml should have the same name.

**Comment by janandreschweiger** [comment]
@JoanFM sure I will try it out.

**Comment by janandreschweiger** [comment]
Hey @JoanFM, I just tried that and got an error. This is because we have two different custom executors for search and indexing. I could fix this issue by merging the two doc-idxs, but this would end up in a mess.

Everything worked fine in version 1.1.0. Thus, I'd like to ask you if the coming releases will resolve these issues or we must fix it ourselves by an unpleasant merge.

**Comment by JoanFM** [comment]
Hey @janandreschweiger,.

Could you send (if possible) the 2 indexer yaml files? To see what can be causing the issue?

In theory just by ensuring they have the same name, it should work. But it is weird that this behavior changed  in 1.1.2 ...

**Comment by janandreschweiger** [comment]
Index:
```
!BinaryPbIndexer
with:
  index_filename: doc.gz
  delete_on_dump: true
metas:
  name: doc_idx_file  # a customized name
  workspace: $PATH_WORKSPACE
  py_modules:
    - preprocess_doc.py
    - index_driver.py
    - update_driver.py
    - delete_driver.py
requests:
  on:
    IndexRequest:
      - !IndexFileDriver
        with:
          traversal_paths: ['r']
    UpdateRequest:
      - !UpdateFileDriver
        with:
          traversal_paths: ['r']
    DeleteRequest:
      - !DeleteFileDriver
        with:
          traversal_paths: ['r']
```

Search:
```
!SearchDocIndexer
with:
  index_filename: doc.gz
metas:
  name: doc_idx_search  # a customized name
  workspace: $PATH_WORKSPACE
  py_modules:
    - executor.py
    - driver.py
requests:
  on:
    SearchRequest:
      - !SearchDocDriver
        with:
          traversal_paths: ['m']
```

**Comment by janandreschweiger** [comment]
I have already tried to set the same name in the meta's @JoanFM. But this causes another issue. The search-indexer is not created using the custom python files, but loaded from the workspace. So in fact the index-idx is also used for search, which of course cannot work.

**Comment by JoanFM** [comment]
Can u just make sure that the name under `metas` is the same in both cases? Have u already tried that?

**Comment by JoanFM** [comment]
Okey, understood. I see the problem. It is stranged it used to work, but the potential problem could be that the python files may be part of the indexer dump. 

I have no explanation though on why this used to work and does not work anymore.

It should be fixed soon

**Comment by janandreschweiger** [comment]
Ok thank you @JoanFM, so should we just wait for the next release?

**Comment by JoanFM** [comment]
We will try to fix soon. Just to validate the hypothesis.

Could you do 2 things?.

1. Name the 2 metas with the same name.
2. Add executor.py and driver.py also in the py modules of the index pod

This may let you work in the meanwhile

**Comment by JoanFM** [comment]
It may not work, I realized the 2 executors are of different class. I am surprised this used to work before latest release. 

Would it be a big problem to index using SearchDocIndexer?

**Comment by janandreschweiger** [comment]
You mean merging them in a single indexer? It would break our clean design, but we can do it yes.

**Comment by janandreschweiger** [comment]
If this issue cannot be easily resolved by you, we will do it.

**Comment by JoanFM** [comment]
Hey @janandreschweiger,

To better help us identify the issue. Could you try to see if putting `read_only: True` in the doc indexer pod inside the flow.yml?

**Comment by JoanFM** [comment]
Hey @janandreschweiger,

Thinking of what you are seeing I only see one explanation why it was working before and not now (and why u were forcing different names in `metas` of the `executor`.

Let me know if I am correct:
1. U have the `SearchDocIndexer` class that does some specifics querying actions that `BinaryPbIndexer` does not, but that works with the same files as `BinaryPbIndexer`. 
2. U keep different `metas` names to avoid the Search Pod to deserialize `BinaryPbIndexer` and force u to work with that `indexing` class invalidating your `search-specific` executor.

I think the problem must be:
- `SearchDocIndexer` has some logic to load the files that are generated by `BinaryPbIndexer`. The naming convention of these files have changed in the PR I mentioned in one of the firsts comments:
Before u could find the files under:

`$WORSKPACE_PATH/doc_idx_file`

And now the files must be found under:

`$WORSKPACE_PATH/doc_idx_file-0`

Could you confirm my assumptions are correct? If so, the only adaptation you need to do is to adapt the way you load the `index` files to the new naming convention.

**Comment by janandreschweiger** [comment]
Yes @JoanFM, I can confirm. We have to do that, because some documents are stored in the workspace (BinaryPbIndexer) and some are stored in our mongo-database. I will try that out in the afternoon. Thank you!

**Comment by janandreschweiger** [comment]
Hey @JoanFM, I now had a look on it. As I explained earlier we store documents in the database and in the workspace. Our search-indexer extends the BinaryPbIndexer for searching the database as well. But for searching the workspace we rely on the BinaryPbIndexer. So how can I tell the BinaryPbIndexer to load the files from doc_idx_file-0? The index_filename parameter is definitely the wrong parameter.

**Comment by JoanFM** [comment]
Can you try to combine the `index_filename` with the `get_file_from_workspace()` method?

**Comment by janandreschweiger** [comment]
Thanks for your quick response @JoanFM. A plain BinaryPbIndexer searches the workspace. So I need to know how I can tell a BinaryPbIndexer where the index-files are and I haven't found any information in the docs about that.

**Comment by JoanFM** [comment]
Getting `get_file_from_workspace(self.index_filename)` would make sure that it accesses the path corresponding to the corresponding shard.

**Comment by janandreschweiger** [comment]
Right @JoanFM, with this function I get the right path. But how can I set this path in the BinaryPbIndexer. We just have a BinaryPbIndexer and call its query method. We don't do the searching ourselves. Sorry when there is a misunderstanding.

**Comment by JoanFM** [comment]
I am not sure I see the problem. With this call does the example work with new version?

Jina constructs the path taking into account 3 things:
- The index filename, the workspace path and the shard id.

**Comment by janandreschweiger** [comment]
I think Jina also takes the index-name (e.g. doc_idx_search) which is specified in the meta into account, which is different from the index-filename (e.g. doc.gz).

My workspace looks like this:
```
workspace/
   doc_idx_file-0/
      doc.gz
      doc.gz.head
      doc_idx_file.bin
   doc_idx_search-0/
      doc.gz
      doc.gz.head
```
I'm sorry but I don't know what I should be doing. Should I overwrite the get_file_from_workspace method or should I give the search-idx and the index-idx the same name? Of course I can call the get_file_from_workspace method, but that doesn't effect anything.


I am sorry I don't understand what I should be doing.

**Comment by JoanFM** [comment]
Nothing to be sorry about @janandreschweiger. It is a little cumbersome, and for your usecase (separating index and query in 2 classes) is not a really good design (Although I think it makes a lot of sense and is something we are looking into).

I will look deeper into it and see what is the best solution for you while we look at a better solution.

**Comment by JoanFM** [comment]
It could be useful if u could share some details about rhe SearchDocIndexer implementation, specially about the part where data is loaded or index file is looked for

**Comment by janandreschweiger** [comment]
Sure @JoanFM. Here is our implementation:

**Index-DocIdx**
pod.yml:
```
!BinaryPbIndexer
with:
  index_filename: doc.gz
  delete_on_dump: true
metas:
  name: doc_idx_file
  workspace: $PATH_WORKSPACE
```

**Search-DocIdx**
pod.yml:
```
!SearchDocIndexer
with:
  index_filename: doc.gz
metas:
  name: doc_idx_search
  workspace: $PATH_WORKSPACE
  py_modules:
    - executor.py
    - driver.py
requests:
  on:
    SearchRequest:
      - !SearchDocDriver
        with:
          traversal_paths: ['m']
```

driver.py:
```
from typing import Iterable
from jina.drivers.search import KVSearchDriver
from jina import Document

from debug import logger

class SearchDocDriver(KVSearchDriver):
    def _apply_all(self, doc_sequences: Iterable['DocumentSet'], *args, **kwargs) -> None:
        for docs in doc_sequences:
            miss_idcs = []  # missed hit results, some search may not end with results. especially in shards
            mongo_id_to_idx = { }
            
            for idx, doc in enumerate(docs):
                if doc.id[0] == '0':
                    mongo_id_to_idx[doc.id[9:]] = idx
                    miss_idcs.append(idx)
                else:
                    serialized_doc = self.exec_fn(jina_id=doc.id)
                    if serialized_doc:
                        doc.MergeFrom(Document(serialized_doc)) # merge!
                    else:
                        miss_idcs.append(idx)

            mongo_ids = [*mongo_id_to_idx]
            if mongo_ids:
                for conversation in self.exec_fn(mongo_ids=mongo_ids):
                    mongo_id = str(conversation['_id'])
                    del conversation['_id']
                    idx = mongo_id_to_idx[mongo_id]
                    docs[idx].MergeFrom(Document(id=9*'0' + mongo_id, tags=conversation))
                    miss_idcs.remove(idx)

            if miss_idcs:
                # delete non-existed matches in reverse
                for j in reversed(miss_idcs):
                    del docs[j]
                logger.log_warning(f'Search could not find {len(miss_idcs)} documents!')
```

executor.py:
```
from jina.executors.indexers.keyvalue import BinaryPbIndexer
from typing import List, Dict, Union
import os

from db.db import get_database

class SearchDocIndexer(BinaryPbIndexer):
    def query(self, jina_id: str = None, mongo_ids: List[str] = None):
        if jina_id:
            return super().query(jina_id)  # serialized document
        
        if mongo_ids:
            return self.query_mongo(mongo_ids)  # conversations cursor

    def query_mongo(self, mongo_ids: List[str]):
        from bson.objectid import ObjectId
        mongo_object_ids = [ObjectId(mongo_id) for mongo_id in mongo_ids]     

        db = get_database()
        return db.conversations.delegate.aggregate([
            { '$match': { 'active': True, '_id': { '$in': mongo_object_ids } } },
            { '$addFields': { 'replies': {
                '$filter': {
                    'input': "$replies",
                    'as': 'reply',
                    'cond': "$$reply.active"
                }
            } } },
            { '$project': { 'type': 1, 'title': 1, 'state': '$stateInfo.state', 'num_replies': { '$size': '$replies' } } }
        ])
```

Thanks for helping us out again @JoanFM!

**Comment by janandreschweiger** [comment]
@JoanFM I have spoken to some of my colleagues. 

**Now (3 Doc Indexers):**

Database-Index-Idx (db)
File-Index-Idx (workspace)
Search-Idx (db+workspace)

It is technically possible to merge them. My colleagues decided to split them back then, as we would otherwise have a strange mix-up:

**Possible (2 Doc Indexers):**
Database-Index-Idx (db) # cannot be merged
File-Index-Idx (workspace) <- merge -> Search-Idx (db+workspace)

**Comment by JoanFM** [comment]
Hey @janandreschweiger,

Finally I understood what is the problem and why it was working before and not now. 

The problem your implementation had (and was hidden) is that it could have never worked in the presence of `shards`.

Let me explain:

- Jina currently takes 3 things into consideration to know where to store the `data` of an `executor`. (`workspace_path, `name of executor` and `shard_id`). (This makes sure that every executor and every of its shards work in a separate space.
- Before the change in #2243 , when no `sharding` was specified, the `shard` and the `name` of the index was not considered to create the subfolder, but in #2243 we unify this and consider first shard to be `pea_id` (shard_id) = 0 even when a single pea is used. @FionnD @rutujasurve94 @cristianmtr this needs to go into the `breaking changes`
- This is why it was working for you in the absence of sharding configuration, but you could have never scaled it to use more shards.

This is something that we have discussed internally and this issue u are facing gives more arguments to us to decouple Indexing and Querying (which is not naturally achieved right now).

While we figure out how to improve this, the quickest solution (quick fix) for you would be to add this method to ur `SearchDocIndexer`:

```
    def post_init(self):
        super().post_init()
        self.name = 'doc_idx_file'
```

This could make it work while we come for a better solution to the underlying design problem.


Sorry for the inconvenience, it was a very weird combination of factors which made this work in the past and fail now.

**Comment by JoanFM** [comment]
#2306 this PR tries to add a test showing that the proposed change can make it work

**Comment by janandreschweiger** [comment]
That's awesome @JoanFM! Sorry for writing back so late, I was on vacation. I will try it out today.
Thanks for all your effort!

**Comment by janandreschweiger** [comment]
@JoanFM Thank you!!! It works :heart:

**Comment by janandreschweiger** [comment]
Thank you @JoanFM It works! :heart:
