### ISSUE TITLE
avoid dumping executors

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2299]
As per #2295, the user is trying to use different Executor class at Index time and at Query time for KVIndexers.

In VectorIndexers this is allowed using the ref_indexer composition pattern, which is not contemplated in BinaryPbIndexer.

As a longer term solution, I am not sure if avoiding serializing executors would provide more flexibility out of the box avoiding some of these problems.

**Comment by FionnD** [comment]
@JoanFM what's the purpose of this issue?

**Comment by JoanFM** [comment]
To be held until Executor API refactor

**Comment by FionnD** [comment]
Then that is out of scope for this release (1.3)?

**Comment by JoanFM** [comment]
lets discuss on Thursday, but I would say so
