### ISSUE TITLE
Send gateway info in GET /flows with jinad

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#2330]
**Describe the feature**
Currently only flow parser args are sent back in the response. It would be useful to have info from gateway (gRPC/WS, port etc).

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACOREV1-983) by [Unito](https://www.unito.io)

**Comment by opumm** [comment]
@deepankarm It would great if you can attach a sample `response` body.
And if you had any other suggestions.

I am planning to contribute to Jina. and I found this issue interesting.

**Comment by deepankarm** [comment]
Fixed in #2473
