### ISSUE TITLE
Add unittests of CompoundPod showing ports/hosts and sockets configuration

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2337]
**Describe the feature**
Add a unittest in `CompoundPod` to test heavily which ports/hosts/socket configurations are set.

Right now, The argument parsing of these components is not so clean, and having such a test, would help refactoring in a safer way in the future

**Comment by JoanFM** [comment]
Linked PR #2347

**Comment by FionnD** [comment]
Closed in #2347
