### ISSUE TITLE
fix naming of pods and replicas in logs

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#2363]
See tests.unit.peapods.pods.test_compound_pods.test_pod_naming_with_parallel

Pod should be `replica`

**Comment by JoanFM** [comment]
The current naming is:

`CompoundPod` as a `Pod` receives the `name` from input `args`.

The inner Pods inherit the `name` plus add an `idx` depending on their replica-id. What would be the naming you would expect?

In the `test`, u see Pod because the --name argument says so.

**Comment by cristianmtr** [comment]
The idea is to make the logs look like 

```
        replica-0/pea-1@109904[I]:starting jina.peapods.runtimes.zmq.zed.ZEDRuntime...
        replica-0/pea-1@109904[I]:input tcp://0.0.0.0:39103 (DEALER_CONNECT) output tcp://0.0.0.0:57387 
```

Maybe it's not a good first issue. I haven't looked at where specifically the changes would need to be done. I was only thinking that a PR for this would be fairly detached from the core, and wouldn't require a lot of overhead for understanding the internals

**Comment by FionnD** [comment]
Ah yes I see your logic, that's fair enough. An experienced developer might take it.

**Comment by properGrammar** [comment]
Hi All, I've been digging into this, and believe I've nailed down how to make this happen. Before I prepare the PR, I have a few questions:

1 - The easiest solution here is not simply a matter of tweaking logging settings, but involves altering the object names. Is this an acceptable tradeoff to resolve this issue? (I'm assuming it is, as the current solution is also implemented this way, but just want to make sure nothing else depends on the current naming convention.)
2 - Currently, in the case where the object name does not yet exist, it is just assigned the index number for a name. Would you like "replica-" and "pea-" to be prepended in these cases or no?
3 - Do you want "pea-" to be prepended when the Pea name is "head" or "tail"? (I'm assuming not, but just checking.)

I should be able to have something whipped up fairly quickly after hearing back from you on these questions. Cheers!

**Comment by properGrammar** [comment]
As you can see, I went about with the PR; I hope I followed the commit style correctly.

I assumed that the answer to the above questions was: 1. Yes 2. No 3. No. I look forward to any followup herein. Be Well
