### ISSUE TITLE
PeaType metaclass weird behavior, why does this not work?

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2371]
**Describe the bug**
Something is weird with the `PeaType` metaclass.

It seems that `peas` from inside a `list` cannot be properly started.

See tests added in #2364 .

Why one of the tests do not pass?

**Comment by FionnD** [comment]
@JoanFM is this still weird?

**Comment by JoanFM** [comment]
yes, it is still weird.

**Comment by JoanFM** [comment]
Seems to be fixable via approach in #2688
