### ISSUE TITLE
Add the jina-hub schema to api.jina.ai

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2375]
**Describe the feature**
Add the jina-hub schema to api.jina.ai

https://github.com/jina-ai/jina-hub/pull/7460#pullrequestreview-632400427

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by Kelton8Z** [comment]
I believe the schema is already there at https://github.com/jina-ai/api/blob/master/schemas/hub_executor_schema.json

**Comment by nan-wang** [comment]
@Kelton8Z Yes, you are right.
