### ISSUE TITLE
🚨 BREAKING CHANGES 1.2 -> 1.3

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2378]
# 🚨 BREAKING CHANGES 1.2 -> 1.3

This issue is created to keep track of breaking changes between `1.2` and `1.3` (scheduled release on 2020.5.26)

## Breaking Changes & Migration Guide

| PR |  Rolled Out? | Override |
| #2355  | Yes | --- |

- Replace `DocumentSet` with `DocumentArray`
- Replace `QueryLangSet` with `QueryLangArray`
- 

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.2 </td>
<td> 1.3 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
from jina import DocumentSet, QueryLangSet
```

</sub> </td>
<td> <sub> 

```python
from jina import DocumentArray, QueryLangArray
```

</sub> </td>
</tr>
</table>

---

## Template
| PR |  Rolled Out? | Override |
| --- | --- | --- |
| |  | |

<table stype="margin-left:auto;margin-right:auto;">
<tr>
<td> </td>
<td> 1.2 </td>
<td> 1.3 </td>
</tr>
<tr>
<td> </td>
<td> <sub> 

```python
old codes
```

</sub> </td>
<td> <sub> 

```python
new codes
```

</sub> </td>
</tr>
</table>

---

**Comment by FionnD** [comment]
@nan-wang this can be closed right? Since 1.3 is released?
