### ISSUE TITLE
flow.index_lines fails when list of string is passed

### ISSUE THREAD

**Issue by yamanahlawat** [jina-ai/jina#2380]
**Describe the bug**

I have a list of around 2000 strings `Iterable[str]`. I am using Jina Flow like this

```
with search_flow: 
    search_flow.index_lines(lines=data, batch_size=16, size=docs_count)
```
where docs count is 2k. Notice here I am passing `lines=data` to the `index_lines` function, where `data` is the `Iterable[str]`
As soon as It starts indexing, it returns the following error.

```
Traceback (most recent call last):
  File "/home/default/.virtualenvs/backend-hHi_FZ2s/lib/python3.8/site-packages/jina/clients/request/__init__.py", line 57, in request_generator
    for batch in batch_iterator(data, request_size):
  File "/home/default/.virtualenvs/backend-hHi_FZ2s/lib/python3.8/site-packages/jina/helper.py", line 278, in batch_iterator
    chunk = tuple(islice(data, batch_size))
  File "/home/default/.virtualenvs/backend-hHi_FZ2s/lib/python3.8/site-packages/jina/clients/sugary_io.py", line 72, in _input_lines
    yield from _input_ndjson(lines)
  File "/home/default/.virtualenvs/backend-hHi_FZ2s/lib/python3.8/site-packages/jina/clients/sugary_io.py", line 90, in _input_ndjson
    value = json.loads(line)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Describe how you solve it**
After some debugging, I found out that, the `_input_lines` function in `jina/clients/sugar_io.py` has a default value for `line_format` field i.e. `json`. Indexing with a list of strings used to work in Jina version 0.9.1.

---

**Environment**
```
- jina 1.2.1
- jina-proto 0.0.81
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.20.2
- protobuf 3.15.8
- proto-backend cpp
- grpcio 1.37.1
- pyyaml 5.4.1
- python 3.8.5
- platform Linux
- platform-release 5.4.0-72-generic
- platform-version #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021
- architecture x86_64
- processor x86_64
````
**Screenshots**
![Screenshot from 2021-05-05 01-20-54](https://user-images.githubusercontent.com/12144602/117062093-a30d4480-ad40-11eb-9898-00f6c50255be.png)

**Comment by JoanFM** [comment]
hey @yamanahlawat 

may you try using any value of line_format parameter that is not json or csv?

**Comment by yamanahlawat** [comment]
@JoanFM In my use case, its always List of strings `Iterable[str]`

**Comment by JoanFM** [comment]
I think that if line_format is different than 'json' or 'csv', it will default to read the values as Iterable of strings

**Comment by yamanahlawat** [comment]
In `CRUDFlowMixin` at `jina/flow/mixin/crud.py` the `index_lines` function also has a default value of `json`, I think which causes this error

**Comment by JoanFM** [comment]
could you try this?:

```
with search_flow: 
    search_flow.index_lines(lines=data, request_size=16, size=docs_count, line_format='plain')
```

**Comment by yamanahlawat** [comment]
Thanks. this works, but also any other value.
```
with search_flow:
    search_flow.index_lines(lines=data, batch_size=16, line_format='anyValue', size=docs_count)
```
probably we can close this.

**Comment by JoanFM** [comment]
Maybe we can make it clear in the docstring. You are welcome to provide a clarification for it if you would like to contribute.

**Comment by yamanahlawat** [comment]
Sure. I'll create a PR
