### ISSUE TITLE
Put replica deactivate/close logic solemnly into Pod

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#2383]
As mentioned in my other comment, I believe this should be one command towards the replica and the replica itself cares about the deactivate/close order of its Peas. The CompoundPod should not need to orchestrate these calls.

_Originally posted by @maximilianwerk in https://github.com/jina-ai/jina/pull/2344#discussion_r627164704_

**Comment by 0969397110** [comment]
https://t.me/bg/2k7WLzrBMVYXAAAAtSjJsWKwOJ4
