### ISSUE TITLE
Unify the naming and type for the `shape` field in DenseNdArray and SparseNdArray

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#2438]
**Describe the feature**
In `jina.proto`, the shape field in DenseNdArray and SparseNdArray are naming differently and using different types. 

```
message DenseNdArrayProto {
...
    // the shape (dimensions) of the array
    repeated uint32 shape = 2;
...
}

message SparseNdArrayProto {
...
    // A 1-D int64 tensor of shape [ndims], which specifies the dense_shape of the sparse tensor.
    repeated int64 dense_shape = 3;
}
```

**Your proposal**

- [ ] unify the type to  `repeated int64`
- [ ] unify the name to `shape`

---
<!-- Optional, but really help us locate the problem faster --
**Environment**
- jina 1.2.0
- jina-proto 0.0.81
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.20.3
- protobuf 3.17.0
- proto-backend cpp
- grpcio 1.37.1
- pyyaml 5.4.1
- python 3.8.5
- platform Darwin
- platform-release 20.3.0
- platform-version Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021;
  root:xnu-7195.81.3~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- jina-resources /Users/nanwang/.pyenv/versions/3.8.5/lib/python3.8/site-
  packages/jina/resources
* JINA_ARRAY_QUANT (unset)
* JINA_BINARY_DELIMITER (unset)
* JINA_CONTRIB_MODULE (unset)
* JINA_CONTRIB_MODULE_IS_LOADING(unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EXECUTOR_WORKDIR (unset)
* JINA_FULL_CLI (unset)
* JINA_IPC_SOCK_TMP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_POD_NAME (unset)
* JINA_RAISE_ERROR_EARLY (unset)
* JINA_RANDOM_PORTS (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_SOCKET_HWM (unset)
* JINA_VCS_VERSION (unset)
* JINA_WARN_UNNAMED (unset)
* JINA_WORKSPACE (unset)

**Screenshots**
![image](https://user-images.githubusercontent.com/4329072/118748923-26757c80-b88f-11eb-9326-61ba46ab0dab.png)

**Comment by FionnD** [comment]
@nan-wang put tasks here

**Comment by nan-wang** [comment]
tasks added.
