### ISSUE TITLE
Unable to run Jina on Raspberry Pi 4

### ISSUE THREAD

**Issue by navanchauhan** [jina-ai/jina#2447]
I installed Jina using the installation instructions in the docs and I was unable to run even the Jina command without the error

```
free(): invalid pointer
Aborted
```

I have tried installing Jina from master branch, 1.2.4, and from pip. Yet, the problem persists 

---

**Environment**
Can't actually run this command. 

Latest version of Raspbian OS (aarm64), on a RPi4. Python 3.7.3

**Screenshots**

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/29234112/118821194-a114bb00-b8d4-11eb-9b65-de65338f5860.png">

**Comment by FionnD** [comment]
Hi @navanchauhan 

Thanks for raising the issue, and sorry to hear it happened! 

One of our team will try and reproduce the issue, it might take some time to get our hands on a Raspberry PI. It might take some time to get back to you, but we will!

**Comment by hanxiao** [comment]
arm64 should be supported, let me check

**Comment by alexcg1** [comment]
I've got a Raspberry Pi Zero. I can try to test this tomorrow

**Comment by navanchauhan** [comment]
After leaving the Pi 0 to build overnight (I should setup a cross-compile toolchain :p ), it did install jina but is having other issues and of them is probably because I used python3.9 to install it.

I have now tested installing jina using pip on x86_64, armv6l and aarch64. It installs without errors on all three platforms but does not run on aarch64 and throws invalid pointer issue. 

p.s the docs don't mention It but I had to install `libmupdf-dev and libfreetype6-dev` on all platforms for PyMuPDF2 when pip could not install the wheel and had to manually build it.

**Comment by alexcg1** [comment]
Good point on how long it'll take! If it needs an overnight build I'd best wait til next week to test! Long weekend coming up here, and dragging my external monitor from office to home would be...well, it'd be a drag :sweat_smile: 

As for Python version, 3.7 or 3.8 are officially supported

**Comment by alexcg1** [comment]
Right, progress update:

`jina -v` throws `Illegal instruction` after `RuntimeWarning` about my protobuf backend. That warning just seems to be a standard thing when not using C++ protobuf backend I guess.

This is on a Raspberry Pi Zero

**Comment by alexcg1** [comment]
FWIW I ran Jina 0.5 as well to see if this was a recent issue. But exact same result

**Comment by alexcg1** [comment]
Running through `gdb` I get:

```
Program received signal SIGILL, Illegal instruction.
0xb67dc728 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
```

**Comment by alexcg1** [comment]
Same result on 1.2.4

**Comment by hanxiao** [comment]
hi all, actually the best way to use jina on arm device is *not* install from scratch but directly using Docker image.

if you go to this page, https://hub.docker.com/r/jinaai/jina/tags?page=1&ordering=last_updated

you will find all images are `armv6`, `armv7` ready, as we already compiled it in CD, so you don't have to compile it again.

![image](https://user-images.githubusercontent.com/2041322/119233197-68861300-bb5a-11eb-80a0-ba90305bd003.png)

Try pull one of the docker image into your numpy and run it.

**Comment by alexcg1** [comment]
Roger that @hanxiao . I'll give it a shot later today

**Comment by alexcg1** [comment]
So, I'm trying Jina in Docker on my Raspberry Pi Zero. So far, a lot of silent fails.

- It downloads just fine
- Running `docker run -v "$(pwd)/j:/j" jinaai/jina hello-world --workdir /j`: CPU spins up, no output, `j` dir created but not populated
- Running `docker run -v "$(pwd)/j:/j" jinaai/jina hello fashion --workdir /j`: same result
- Running `docker run -it jinaai/jina sh`: same result

**Comment by navanchauhan** [comment]
Whoops, there are no images for arm64:

```
admin@pi4:~ $ sudo !!
sudo docker run -it jinaai/jina sh
Unable to find image 'jinaai/jina:latest' locally
latest: Pulling from jinaai/jina
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.
```

Even if the official method is to use Docker images, shouldn't jina still run on a clean system with all the requirements satisfied?

**Comment by alexcg1** [comment]
@navanchauhan even if Jina's code is platform-agnostic, there's no guarantee our (very few) dependencies will run perfectly :cry: And one incorrectly-working dependency dooms everything.

Raspberry Pi Zero runs on [armv6](https://www.elektronik-kompendium.de/sites/raspberry-pi/2105231.htm) and Docker runs there but I think I wasn't getting great results. I'm heading to office again today so I can check there.

**Comment by alexcg1** [comment]
fwiw, I can't even get a shell on Jina running in Docker on a Raspberry Pi Zero.

Command: `docker run -it --entrypoint /bin/sh jinaai/jina`

- On my Thinkpad X1 Carbon I get a shell.
- On Raspberry Pi Zero I get a short pause then dumped back to shell with no output.

**Comment by alexcg1** [comment]
Even `-vvv` for verbose output gives me nothing

**Comment by FionnD** [comment]
Should we re-open this issue @alexcg1 ?

**Comment by alexcg1** [comment]
I'm not sure running on armv6 is a priority. I can't see anyone running Jina on a Pi Zero for any practical reasons. It wouldn't really work IRL due to puny memory/CPU. For testing it IRL, best case scenario is it crashes or hangs due to lack of memory. But it shouldn't throw `illegal instruction` or just fail silently (like Docker did).

But like I said, no need to re-open issue. No real practical use except for bragging "hey, we can run Jina on a RaspPi Zero!" (but not actually do anything useful with it)

**Comment by FionnD** [comment]
Should we remove it from docs so? 

And I'll dismantle my super computer of Pi's

**Comment by navanchauhan** [comment]
Will you be only removing references for armv6l (i.e. Pi Zero), because RPis 3/4 make good quick setup devices to try and prototype even if it doesn't make sense to use them in production

**Comment by alexcg1** [comment]
I think removing support needs discussion. It's just my opinion that it's not worth us pushing a lot of effort into supporting an architecture (like armv6/rasp pi zero) where Jina wouldn't work in a practical sense. Note: If it actually did even barely work I wouldn't recommend removing support. It's just it's already broken and it's an impractical use case.

Having said that I fully support running Jina on a Pi 3/4. Those have enough grunt that Jina could actually do something practical.

@hanxiao thoughts?

**Comment by hanxiao** [comment]
it is closed because it is supported by that pr

**Comment by hanxiao** [comment]
https://github.com/jina-ai/jina/issues/2447#issuecomment-852152151
this PR is about support on ARMv8 *not* ARMv6, ARMv8 is already supported by #2506  @navanchauhan  please try `pip install --pre` again

@alexcg1 @FionnD Please do not mix the discussion on ARMv6 & ARMv8 just because they are all RPi. They are different architectures. Each arch must be compiled and installed differently.

**Comment by navanchauhan** [comment]
I am having build errors now ugh. I'll try in a clean virtual environment and let it run overnight

**Comment by hanxiao** [comment]
I posted an issue on the upstream https://github.com/grpc/grpc/issues/26457
