### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Arthur-Milchior** [jina-ai/jina#2456]
On https://docs.jina.ai/chapters/what_neural_search/
you wrote:
> You want to understand why you’re getting your those results

I suspect the last "your" should be deleted.

I would have done a PR, but I can't find the link to this document. The github link on the footer links to the toplevel place, which is not helpful here

**Comment by FionnD** [comment]
Fixed in https://github.com/jina-ai/docs/pull/277/files

**Comment by Arthur-Milchior** [comment]
Yeah, I finally found out the correct repository. I still believe that's a problem that your documentation links to a github repo which is not your documentation repo however
