### ISSUE TITLE
chatbot helloworld is tested, not covered in codecov

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#2481]
we have system test for chatbot, while codecov ignored chatbot completely (we lose 141 lines of code coverage):

![image](https://user-images.githubusercontent.com/9794489/119571629-dc6e2880-bdb1-11eb-8901-3ae70b22be86.png)

**Comment by FionnD** [comment]
Is this ticket to add test coverage for the chatbot?

**Comment by hanxiao** [comment]
i think Bo means it is tested already but the codecov does not count for some reason

**Comment by bwanglzu** [comment]
true..I'll figure it out, why codecov ignored our chatbot system test
