### ISSUE TITLE
Gateway information in routes list can be wrong

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#2500]
**Context**
As part of of the `Message` envelope we keep track of all peas touching a message as it passes through a `Flow`. This is done in the [routes field](https://github.com/jina-ai/jina/blob/c7e45999cc40fb220cea5fe3774d4156049ec67e/jina/types/message/__init__.py#L323) of the Envelope.
After a request has completed in the Gateway, those routes are copied to the response to the client. A simplified example of such a response with routes can be seen in the [Flow cookbook](https://github.com/jina-ai/jina/blob/c4a93181a0756d2b157b1dd888bf26b4245158da/.github/2.0/cookbooks/Flow.md#curl-with-http-request).

**Describe the bug**
The current code assumes that the combination of pod/pod_id are unique as they are used as keys in some intermediate processing dict:
[`routes = {(r.pod + r.pod_id): r for m in msgs for r in m.envelope.routes}`](https://github.com/jina-ai/jina/blob/c7e45999cc40fb220cea5fe3774d4156049ec67e/jina/types/message/__init__.py#L426)

Unfortunately this assumption is wrong for the Gateway pod because it can be part of a Flow multiple times when we have [intra parallel executions](https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Flow.md#intra-parallelism-via-needs) (e.g. document and vector indexing parts of a Flow). In this case the processing can branch at the Gateway and one message is send to each parallel execution branch of the Flow. This means the Gateway will be added multiple times to the routes list, each time overwriting the previous entry.
Especially in a distributed setting the execution order of parallel branches of a Flow is not guaranteed.

Lets consider this simplified example:
```
Flow()
    .add(name='a1', needs='gateway')
    .add(name='a2')
    .add(name='b1', needs='gateway')
```
The execution order can happen like this (_tx_ are timestamps):
_client - gateway (t0) - a1 (t1) - a2  (t2) - gateway (t3) - b1 (t4) - gateway (t5) - client_

The correct route file would look like this
```
{'pod': 'gateway', 'pod_id': '37f4610e-7e81-4b08-8581-a6d7ec3ed915', 'start_time': 't0', 'end_time': 't5'}
{'pod': 'a1', 'pod_id': 'd6bd5907-2980-436c-bbd7-2cb9a6f0de23', 'start_time': 't1', 'end_time': 't1'}
{'pod': 'a2', 'pod_id': 'a0f8429b-0fa1-41d5-abcb-39171e4939db', 'start_time': t2', 'end_time': 't2'}
{'pod': 'gateway', 'pod_id': '37f4610e-7e81-4b08-8581-a6d7ec3ed915', 'start_time': 't3', 'end_time': 't5'}
{'pod': 'b1', 'pod_id': '1cabbd1c-262a-4ffc-be16-c4e289a3dade', 'start_time': 't4', 'end_time': 't4'}
{'pod': 'gateway', 'pod_id': '175e0f74-d4de-40f0-8801-adfc5b410e35', 'start_time': 't5'}
```

Due to this bug this will not actually happen and the result will be this:
```
{'pod': 'a1', 'pod_id': 'd6bd5907-2980-436c-bbd7-2cb9a6f0de23', 'start_time': 't1', 'end_time': 't5'}
{'pod': 'a2', 'pod_id': 'a0f8429b-0fa1-41d5-abcb-39171e4939db', 'start_time': t2', 'end_time': 't2'}
{'pod': 'gateway', 'pod_id': '37f4610e-7e81-4b08-8581-a6d7ec3ed915', 'start_time': 't3'}
{'pod': 'b1', 'pod_id': '1cabbd1c-262a-4ffc-be16-c4e289a3dade', 'start_time': 't4', 'end_time': 't4'}
{'pod': 'gateway', 'pod_id': '175e0f74-d4de-40f0-8801-adfc5b410e35', 'start_time': 't5'}
```
So the first gateway entry is missing, because it gets overwritten by the gateway entry added at _t3_.
Additionally the gateway entry at _t3_ has no end_time and the end_time of a1 is actually not its end time, but the end time of the missing gateway. So the end_time of a1 was incorrectly overwritten, assuming that it was the gateway at _t0_.
This happens by this piece [`self.envelope.routes[0].end_time.GetCurrentTime()`](https://github.com/jina-ai/jina/blob/c7e45999cc40fb220cea5fe3774d4156049ec67e/jina/types/message/__init__.py#L415).
We assume here that the first entry in the routes list is always the first Gateway entry. This is not true, because it was overwritten and effectively changed the start_time of the gateway entry from _t0_ to _t3_. The routes list is sorted by start_time at [some point](https://github.com/jina-ai/jina/blob/c7e45999cc40fb220cea5fe3774d4156049ec67e/jina/types/message/__init__.py#L429) which means the _t3_ Gateway entry actually gets put in the middle of the list and is no longer the first entry.

***Effects of the bug***
1. First entries in the routes list can have wrong end_time field
2. Missing end_time for the Gateway entry
3. Missing one entry for the first Gateway pod

**Impact**
The impact of the bug is most likely rather low as the routes list seems to be used only for reasoning about the mechanics of a Flow and time tracking. The processing itself is correct. So I see the following low severity impacts of this bug.
1. Users could be confused if they look at the routes fields for understanding their Flows
2. Our stress tests can yield wrong timing information as Gateway timing is missing and firs entry in routes list can have wrong end_time.

**Additional observations**:
1. The routes list claims to list information about **Pods**, but it should probably be **Peas**?

**Comment by cristianmtr** [comment]
Another strange behavior here is with regards to naming and identity. We see that the 'gateway' name is used in several places in the code, but with different `pod_id`s. When logging this you can see it's added at `join_all`, the last entry in the Flow (say a `doc_idx`), and at the [AsyncPrefetchCall](https://github.com/jina-ai/jina/blob/c7e45999cc40fb220cea5fe3774d4156049ec67e/jina/peapods/runtimes/asyncio/grpc/async_call.py#L20)

On top of that, this `pod_id` is misleading, as it's actually the identity at the Pea level. This can be seen in non-Singleton Pods (with Head/Shards/Tail), where each of them would have their own `pod_ids`, thus actually being `pea_ids`.

**Comment by hanxiao** [comment]
very good job @jacobowitz

**Comment by jacobowitz** [comment]
This got fixed as a side effect of https://github.com/jina-ai/jina/pull/2551
Verified with this test https://github.com/jina-ai/jina/pull/2760
