### ISSUE TITLE
Bug: REST Api not returning status

### ISSUE THREAD

**Issue by jakob1111996** [jina-ai/jina#2522]
I think I found a bug in the latest release candidates rc4 and rc5.
When using the REST API, I saw that the status field in the response json is empty. 

To reproduce: pip install -e .[http] in master branch
```python
from jina import Flow, Executor

with Flow(port_expose="45678").add(uses=Executor) as f:
    f.use_rest_gateway()
    f.block()
```
Then, using cURL:
```sh
curl --verbose --request POST -d '{"mode": "search",  "data": []}' -H 'Content-Type: application/json' 'http://localhost:45678/search'
```

The response then looks like:
```
{
  "request_id": "a9f4dc00-220c-4de0-b8dc-81d7ed98a584",
  "data": {},
  "header": {
    "exec_endpoint": "/search"
  },
  "routes": [
      ... (left out)
  ],
  "status": {}
}
```

I would expect the status to look like this:
```
"status": {
    "code": "SUCCESS",
    "description": ""
  }
```
I get the correct response using v2.0.0rc2 via pip install -e .[http]
I get no status using the current master, rc3 or rc4 via pip install -e .[http]

**Comment by FionnD** [comment]
@deepankarm just highlighting this to you?

**Comment by hanxiao** [comment]
this is default behavior in protobuf, 

use `Flow(..., including_default_value_fields=True)` and try again
