### ISSUE TITLE
Consider moving all imports to the top of the files

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#2550]
As found for this issue https://github.com/jina-ai/jina/issues/2527 makes me wonder if we should move away from import in inner functions.

As said there, used with threads can lead to deadlocks: 

- If we do the inner imports to avoid cyclic dependencies -> We should refactor the code to avoid them

- If we do to minimize the import of external dependencies except for specific features (like scipy for sparse) -> Have a global variable to know if dependency exists.

**Comment by hanxiao** [comment]
that will revert all the effort we reduce the loading speed https://github.com/jina-ai/jina/pull/2510

**Comment by JoanFM** [comment]
Then we cannot support Threads and Processes Pods mixed up

**Comment by hanxiao** [comment]
https://stackoverflow.com/questions/6078712/is-it-safe-to-fork-from-within-a-thread/6079669#6079669

**Comment by hanxiao** [comment]
> https://github.com/jina-ai/jina/issues/2550#issuecomment-852985928
this is fine to me
