### ISSUE TITLE
Website bug

### ISSUE THREAD

**Issue by CPTensil** [jina-ai/jina#2643]
The installation for Jina on windows has a documentation link (on the home page) 
![image](https://user-images.githubusercontent.com/82115501/121899035-07350800-ccf2-11eb-845f-0eda77230c74.png)

that leads to nowhere. https://docs.jina.ai/chapters/install/on-wsl.html

Is this intentional?

**Comment by alexcg1** [comment]
Thanks for spotting that! We just (like yesterday) redirected docs.jina.ai to our new docs site.

@pswu11 can you fix this? Just redirect it to https://docs1.jina.ai/chapters/install/on-wsl.html until we can work out how best to migrate that data

**Comment by pswu11** [comment]
@alexcg1 I'll take care of it

**Comment by pswu11** [comment]
url is updated!
