### ISSUE TITLE
Define parameters on executor level

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#2647]
Assume two encoders share parameter names - like batch_size or traversal_path.
When sending the following request, it is not possible to have different batch sizes or traversal_path for both of the  encoders.

```
results = f.post(
    on='/search',
    parameters={'batch_size': 32},
...
```

**Comment by JoanFM** [comment]
This is specially `important` for `public shared executors`, where the user won't have capacity to rewrite its behavior
