### ISSUE TITLE
introduce using id to access doc within doc array in document cookbook

### ISSUE THREAD

**Issue by Kelton8Z** [jina-ai/jina#2649]
The behavior that 
with `docarray = DocumentArray([Document(id=1)])`, 
`'1' in docarray` gives True and `docarray['1']` gives that document

is unexpected and should be introduced in cookbook

**Comment by JoanFM** [comment]
not unexpected, but needs to be well documented in cookbook

**Comment by Gamol123** [comment]
D

**Comment by Kelton8Z** [comment]
already documented in the latest cookbook
