### ISSUE TITLE
can not set sparse matrix as content of the document

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#2652]
please check the screenshot below:

![A53ABB05-25E9-4ED6-A074-B2D8BBB9EAFE](https://user-images.githubusercontent.com/9794489/122024384-acbaab00-cdc8-11eb-8a48-6baf0eaeefdb.png)

**Comment by hanxiao** [comment]
how about `d.blob=mat`? does it work?

**Comment by JoanFM** [comment]
> how about `d.blob=mat`? does it work?

Yes, and I am fixing this
