### ISSUE TITLE
Learn the basics page not available.

### ISSUE THREAD

**Issue by ParthJadhav** [jina-ai/jina#2693]
Learn the basics page is down or not available.

I have tried to access it from -
https://jina.ai/#get_started

And I was redirected to -
https://101.jina.ai

Which gives me 404 Error.

I don't need it. Just informing :smiley:

**Comment by FionnD** [comment]
Thanks for letting us know @ParthJadhav! We'll get that fixed asap cc @alexcg1

**Comment by ParthJadhav** [comment]
Nice !

**Comment by FionnD** [comment]
This is now fixed.
