### ISSUE TITLE
How to use docker?

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/jina#2695]
**Describe your proposal/problem**

## I want to use docker running a simple case.

**What I need**

I hope you can give me a complete example to run a simple case. If you can give data and demo, that is better. And I want to know how can I enter in the jina-ai docker using `run docker -it jina  /bin/bash`. 

**Screenshots**

![image](https://user-images.githubusercontent.com/33524866/122490325-55107f80-d014-11eb-9039-db0f53e84da2.png)

**Comment by xiaoxiongfeng** [comment]
use `--entrypoint`, the images' entrypoint is  `jina`

**Comment by mapleeit** [comment]
Hi @xiaoxiongfeng You are right. Entrypoint is jina. So if you want to try an example. You can just say docker run -it jinaai/jina:master hello fashion. This will start the internal example of fashion.

**Comment by xiaoxiongfeng** [comment]
> Hi @xiaoxiongfeng You are right. Entrypoint is jina. So if you want to try an example. You can just say
> 
> ```
> docker run -it jinaai/jina:master hello fashion
> ```
> 
> This will start an internal fashion example.

I know, but I want to know the detailed process, not the `docker run -it jinaai/jina:master hello fashion`; Or where is the detailed process; thanks

**Comment by xiaoxiongfeng** [comment]
> Hi @xiaoxiongfeng You are right. Entrypoint is jina. So if you want to try an example. You can just say
> 
> ```
> docker run -it jinaai/jina:master hello fashion
> ```
> 
> This will start an internal fashion example.

I know, but I want to know the detailed process, not the `docker run -it jinaai/jina:master hello fashion`; Or where is the detailed process; thanks

**Comment by xiaoxiongfeng** [comment]
I know it run the code in jina/helloworld, but how?
