### ISSUE TITLE
document granularity off when building chunks bottom up

### ISSUE THREAD

**Issue by Kelton8Z** [jina-ai/jina#2715]
e.g. With 
```python
from jina import Document

text = 'blah'
doc = Document(
    id='root1',
    text=text,
    chunks=[
        Document(
            id='chunk11',
            text=text,
            chunks=[
                Document(id='chunk111', text=text),
                Document(id='chunk112', text=text),
            ]
        ),
        Document(id='chunk12', text=text),
        Document(id='chunk13', text=text),
    ]
)
```

`doc.plot()` gives the attached image which has granularity at 1 for all chunks

**Screenshots**
![image](https://user-images.githubusercontent.com/22567795/122757527-4eab2d80-d2ca-11eb-8bdd-78de2d369504.png)

and printing flow response shows the same problem

![image](https://user-images.githubusercontent.com/22567795/122758975-0987fb00-d2cc-11eb-9698-2d77ee20f537.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200498270493800) by [Unito](https://www.unito.io)

**Comment by JoanFM** [comment]
It is not the plot the problem. It is the creation.

**Comment by Kelton8Z** [comment]
> It is not the plot the problem. It is the creation.

I just realized after printing flow response

**Comment by JoanFM** [comment]
I believe this is due to the fact that when the `latest` chunks are built, it detects its parent as granularity 0. 

So building from the largest depth to the shallowest, it will have this problem.

**Comment by JoanFM** [comment]
@bwanglzu can u share ur thoughts on why is not doable

**Comment by bwanglzu** [comment]
it looks not correct while we can hardly change this. Remember the `granularity` of chunks are set to `ref_doc + 1`, which means at init time, the `Document` will try to find it's parent document, then add 1 to it's parent document's `granularity`. 

In this case, all the documents are created in one line, and at chunk creation time, it didn't know anything about it's parent (root) document. So these chunks will be initialised as a root.

I would say it is not a recommended way to create Jina `Document`, it might mess up recursive document structure. Let's create `Documents` and it's `Chunks` with a more deterministic manner:

```python
d = Document(text='blah')
d.chunks.append(Document(text='chunk1')  # append one chunk
d.chunks.extend([Document(text='chunk2'), Document(text='chunk3')]). # append more chunks
```

**Comment by JoanFM** [comment]
> it looks not correct while we can hardly change this. Remember the `granularity` of chunks are set to `ref_doc + 1`, which means at init time, the `Document` will try to find it's parent document, then add 1 to it's parent document's `granularity`.
> 
> In this case, all the documents are created in one line, and at chunk creation time, it didn't know anything about it's parent (root) document. So these chunks will be initialised as a root.
> 
> I would say it is not a recommended way to create Jina `Document`, it might mess up recursive document structure. Let's create `Documents` and it's `Chunks` with a more deterministic manner:
> 
> ```python
> d = Document(text='blah')
> d.chunks.append(Document(text='chunk1')  # append one chunk
> d.chunks.extend([Document(text='chunk2'), Document(text='chunk3')]). # append more chunks
> ```

Great explanation!

**Comment by JoanFM** [comment]
> it looks not correct while we can hardly change this. Remember the `granularity` of chunks are set to `ref_doc + 1`, which means at init time, the `Document` will try to find it's parent document, then add 1 to it's parent document's `granularity`.
> 
> In this case, all the documents are created in one line, and at chunk creation time, it didn't know anything about it's parent (root) document. So these chunks will be initialised as a root.
> 
> I would say it is not a recommended way to create Jina `Document`, it might mess up recursive document structure. Let's create `Documents` and it's `Chunks` with a more deterministic manner:
> 
> ```python
> d = Document(text='blah')
> d.chunks.append(Document(text='chunk1')  # append one chunk
> d.chunks.extend([Document(text='chunk2'), Document(text='chunk3')]). # append more chunks
> ```

Maybe we can add some line in the `Document` cookbook about this?

**Comment by bwanglzu** [comment]
@JoanFM maybe in write clean JIna code do and don't section?

**Comment by JoanFM** [comment]
> @JoanFM maybe in write clean JIna code do and don't section?

feels like the perfect place

**Comment by tadejsv** [comment]
I think this could be solved if when updating its own granularity, the document would update the granularity of all its chunks as well?

**Comment by JoanFM** [comment]
I think this is really dangerous, I would not do this as it is also a performance problem.
