### ISSUE TITLE
Move from requests to aiohttp in JinaD

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#2746]
**Describe the bug**
All REST requests to mini-jinad currently are done using `requests` module., which blocks the event-loop on main-jinad. We should use `aiohttp` to send async requests.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200510406202377) by [Unito](https://www.unito.io)

**Comment by duxiaoyao** [comment]
As async http client, [HTTPX](https://www.python-httpx.org/) should be a better option over aiohttp. FYI.

**Comment by jacobowitz** [comment]
@duxiaoyao 
Thank you for the suggestion! We have to stick with aiohttp for now though as we are already using this in rest of Jina alot and we want to keep the number of external dependencies as low as possible. HTTPX is not used by us atm.

**Comment by deepankarm** [comment]
While working with @Kelton8Z to enable examples using jinad, I noticed that, if there's a case where mini-jinad container waits to download hub image, Flow creation takes time. During that, jinad server gets completely blocked. This needs to be fixed as soon as possible,
