### ISSUE TITLE
construct document from dict issues 

### ISSUE THREAD

**Issue by Kelton8Z** [jina-ai/jina#2755]
1. `Document(dict(location=(1,0)))`, which follows the cookbook, raises badDocType error while `Document(dict(location=[1,0]))` works
1. Given a random nonempty ndarray `arr,` `Document(dict(blob=arr)` gives `unhashable type: 'numpy.ndarray'` and `google.protobuf.json_format.ParseError` while `Document(blob=arr)` works

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200515130467095) by [Unito](https://www.unito.io)

**Comment by hanxiao** [comment]
you can directly construct doc using kwargs, i.e. `Document(key1=value1, key2=value2, key3=value3)`.

e.g.  the following work
```python
>>> from jina import Document
>>> d = Document(location=(1,0))
>>> 
```



`Document(dict(...))` is possible but this `dict` must be generated from `Protobuf.MessageToDict`

**Comment by CatStark** [comment]
Closing this issue since it was solved
