### ISSUE TITLE
Support inline file uploads

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#2767]
JinaD checks the Flow definition for files to upload to the workspace.

Not all legal syntax are supported. Especially inline and dict syntax dont seem to work

This should work I think and does not because the file _my_exec.py_ is not uploaded to the workspace:

```
exec_description = {'jtype': 'MyExecutor', 'metas': {'py_modules': 'my_exec.py'}}
f = Flow().add(name='myexec1', uses=exec_description)
```

**Comment by deepankarm** [comment]
We used to support inline Flow building before using JinaD, but that got removed & we only support flow building using yaml files now. This probably needs to be documented somewhere.
