### ISSUE TITLE
Add Local Remote Local for dynamic routing

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#2782]
It should be possible again to have a remote Pod inside a local Flow. This was disabled by dynamic routing.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200529170193915) by [Unito](https://www.unito.io)

**Comment by akforum2204** [comment]
Hello how are you

**Comment by akforum2204** [comment]
Hi

**Comment by JoanFM** [comment]
Can you add more details about this? how is it not possible?
