### ISSUE TITLE
[FEATURE] Need to add Installation Video

### ISSUE THREAD

**Issue by amino19** [jina-ai/jina#2814]
**Describe the feature**

It's not comfortable for beginners (user), to go directly with installation process of `Jina`. :slightly_frowning_face: 

**Your proposal**

We must provide a guidance with video reference, that must be in README.md :slightly_smiling_face: 

- - -

**Environment**

Linux, WSL2, Mac

**Screenshots**

<img width=50% src="https://user-images.githubusercontent.com/75872316/123907322-59815480-d993-11eb-8dd1-fbfc3acb1168.png">

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200479679796904/1200540546764695) by [Unito](https://www.unito.io)

**Comment by alexcg1** [comment]
Hey @amino19 , thanks for the feedback!

What in particular do you feel is difficult? At least compared to any other Python package?

because if the whole video is just `pip install jina` then I don't think it'll be very long :laughing:

**Comment by amino19** [comment]
@alexcg1 : Sir, basically, I think the installation process must include `pip` & `docker`! Satisfy video length + process via both. :slightly_smiling_face:

**Comment by amino19** [comment]
@JoanFM: Is that done by someone?
Previously, participating in MLH hackathons, we face a lot of these issues for installation.

I hope, you will take some major actions towards this, _without ignoring!!!_
Also, if the video has already been there on YT platform, pl share it as a reference in README.md.

Thanks! :slightly_smiling_face:
