### ISSUE TITLE
Old Jina documentation is missing

### ISSUE THREAD

**Issue by arjunramesan01** [jina-ai/jina#2823]
I wanted to learn about rankers used in Jina, but the support document is missing
URL : https://docs.jina.ai/v1.0.7/chapters/ranker/

**Comment by bwanglzu** [comment]
hi @arjunramesan01 in case you're still using jina 1.x, checkout [this](https://docs1.jina.ai/v1.0.7/chapters/ranker/) link. But we suggest you to switch to jina 2.0.

**Comment by arjunramesan01** [comment]
thanks
