### ISSUE TITLE
[Documentation] "What is Neural Search" hyperlink is restricted 

### ISSUE THREAD

**Issue by chintanckg** [jina-ai/jina#2849]
http://jina.ai/2020/07/06/What-is-Neural-Search-and-Why-Should-I-Care.html 

![image](https://user-images.githubusercontent.com/13482558/124381794-f9b3e200-dce1-11eb-8715-6e888dafae18.png)

![image](https://user-images.githubusercontent.com/13482558/124381814-12bc9300-dce2-11eb-9670-fc2daa9b29e9.png)

**Comment by alexcg1** [comment]
@gitcommitshow can you look into this? Looks like this might only happen in India

**Comment by deepankarm** [comment]
@chintanckg I'm connecting from India & this works for me. Confirmed with friends too :)
