### ISSUE TITLE
feat: add isort to pre-commit 

### ISSUE THREAD

**Issue by EyaRhouma** [jina-ai/jina#2862]
**Describe your proposal/problem**
Add `isort` pre-commit to automatically order imports alphabetically and separate them into sections. Rather than manually following `standard import order` as suggested in the [Code Review Guidelines]( https://github.com/jina-ai/jina/blob/master/.github/CODE_REVIEW_GUIDELINES.md#tldr-for-pyguide)

**Comment by bwanglzu** [comment]
hi @EyaRhouma thanks for your issue, I think we decided to not do it in the near future.
