### ISSUE TITLE
Minimum Working Example Jina 2.0 - Name Error, __file__ not found

### ISSUE THREAD

**Issue by bobub** [jina-ai/jina#2899]
**Describe the bug**
Hi, the minimum working example for Jina 2.0 does not fully run in Colab. Specifically, the flow cell throws a name error as it cannot find the __file__, which is the source code itself.

I'm referring to:
https://colab.research.google.com/github/jina-ai/jupyter-notebooks/blob/main/2.0-readme-38l.ipynb

**Comment by tiwari93** [comment]
I am also facing same issue.

![image](https://user-images.githubusercontent.com/49356997/125032180-35b4c180-e0ab-11eb-8c2b-d43d12e4a7f9.png)

**Comment by cristianmtr** [comment]
Hey @bobub @tiwari93 

Yes, the `__file__` variable will not work in notebooks.

Thanks for pointing these out. We will fix them these days :)
