### ISSUE TITLE
Fetching meta data...

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/jina#2912]
**Describe the bug**

![image](https://user-images.githubusercontent.com/33524866/125185464-849f5a00-e257-11eb-93ec-680dbe680cc8.png)
This problem happends a lot, and it is not my question, because I do not change anything. I think I must download something from Jina,  is there a way to save it locally? I think a stable environment is very important.
**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by nan-wang** [comment]
This is due to the internet connection issue.

**Comment by xiaoxiongfeng** [comment]
![image](https://user-images.githubusercontent.com/33524866/125187832-20cf5e00-e264-11eb-8c8e-305f085fb036.png)
![image](https://user-images.githubusercontent.com/33524866/125187857-39d80f00-e264-11eb-867f-b3ac406ea702.png)

**Comment by niuzs-alan** [comment]
Hey, Thanks for your feedback.

I checked the backend service yesterday, it worked.
And It works on my laptop both with `sysproxy` or not now.

Could you plz check your internet and try it again?

**Comment by mapleeit** [comment]
@xiaoxiongfeng Could you execute this command and print the result here? `curl -v https://api.jina.ai/hub/hubble.json`

**Comment by CatStark** [comment]
Hi @xiaoxiongfeng, is your problem solved? otherwise we can help on this

**Comment by CatStark** [comment]
I am closing this since it looks its stalled. But we can re open if necessary :)
