### ISSUE TITLE
Remote replicas

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#2923]
Allow for CompoundPods Replicas to be on separate machines.

**Comment by JoanFM** [comment]
and have dump reload mechanism work in distributed setting

**Comment by jacobowitz** [comment]
We should probably think about a generic approach so that we can also do the same for shards? Basically any pod type which can be controlled by a CompoundPod?

**Comment by JoanFM** [comment]
peas in Pods can be in different machines

**Comment by JoanFM** [comment]
His will be handled in `pea_hosts` refactoring for starRouting
