### ISSUE TITLE
Streamlit & Jina RuntimeError: context has already been set

### ISSUE THREAD

**Issue by georgeamccarthy** [jina-ai/jina#2957]
**Describe the bug**
## Streamlit & Jina RuntimeError: context has already been set
If I create the file app.py and insert
```
import streamlit as st
import jina
```

and run through `streamlit run app.py`
I get the error `RuntimeError: context has already been set`
Traceback:
```
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.9/site-packages/streamlit/script_runner.py", line 338, in _run_script
    exec(code, module.__dict__)
File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 2, in <module>
    from jina import Document
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.9/site-packages/jina/__init__.py", line 26, in <module>
    _set_start_method('fork')
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.9/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
```

### Followed steps suggested by Deepankar (Jina AI) on Slack/Support
> 1. Try creating a conda env/venv with python 3.7/3.8 to see if that works.
> 2. In jina/__init__.py file found in /Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.9/site-packages/jina/__init__.py , try commenting out the following.

```
 21 # DO SOME OS-WISE PATCHES
 22 if _sys.version_info >= (3, 8, 0) and _platform.system() == 'Darwin':
 23     # temporary fix for python 3.8 on macos where the default start is set to "spawn
 24     # https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-meth
 25     from multiprocessing import set_start_method as _set_start_method
 26
 27     _set_start_method('fork')
```

All of the above steps still produced the same error apart from (2.) which resulted in a different error `ValueError: signal only works in main thread`
Traceback
```
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 1, in <module>
    from jina import Document
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/jina/__init__.py", line 108, in <module>
    _signal.signal(_signal.SIGINT, _signal.default_int_handler)
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
```

---

**Environment**
➜ jina --version-full
- jina 2.0.7
- jina-proto 0.0.84
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.20.2
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.38.1
- pyyaml 5.4.1
- python 3.8.10
- platform Darwin
- platform-release 20.5.0
- platform-version Darwin Kernel Version 20.5.0: Sat May 8 05:10:31 PDT 2021;
  root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
- architecture x86_64
- processor i386
- uid 32988875906896
- session-id 849f7d60-e56c-11eb-83b6-1e00d23adf50
- uptime 2021-07-15T13:59:38.065217
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Screenshots**

**Comment by JoanFM** [comment]
Hello @georgeamccarthy.

This seems to relate to some work we have been looking at in the past times.

Could you please try to comment from Jina the lines:

```python
 21 # DO SOME OS-WISE PATCHES
 22 if _sys.version_info >= (3, 8, 0) and _platform.system() == 'Darwin':
 23     # temporary fix for python 3.8 on macos where the default start is set to "spawn
 24     # https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-meth
 25     from multiprocessing import set_start_method as _set_start_method
 26
 27     _set_start_method('fork')
```
and see if the `Jina` app still works?

**Comment by georgeamccarthy** [comment]
That stops there error and produces a new one:

`ValueError: signal only works in main thread`

```
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 1, in <module>
    from jina import Document
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/jina/__init__.py", line 108, in <module>
    _signal.signal(_signal.SIGINT, _signal.default_int_handler)
File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
```

**Comment by georgeamccarthy** [comment]
Tried

```
import streamlit as st
import multiprocessing
print(f' {multiprocessing.get_start_method()}')
```

The output is `spawn`

**Comment by georgeamccarthy** [comment]
If I edit out the section 

> ```python
>  21 # DO SOME OS-WISE PATCHES
>  22 if _sys.version_info >= (3, 8, 0) and _platform.system() == 'Darwin':
>  23     # temporary fix for python 3.8 on macos where the default start is set to "spawn
>  24     # https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-meth
>  25     from multiprocessing import set_start_method as _set_start_method
>  26
>  27     _set_start_method('fork')
> ```

and in `app.py` write

```
def main():
    import streamlit as st
    import multiprocessing
    from jina import Client, Document

if __name__ == '__main__':
    from multiprocessing import set_start_method
    set_start_method('fork')
    main()
```

When running `streamlit run app.py` the error is

```
2021-07-15 20:42:16.897 Traceback (most recent call last):
  File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/site-packages/streamlit/script_runner.py", line 349, in _run_script
    exec(code, module.__dict__)
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 8, in <module>
    set_start_method('fork')
  File "/Users/georgeamccarthy/opt/anaconda3/envs/jina/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

Note that just running `python app.py` produces no errors.

**Comment by bwanglzu** [comment]
i managed to reproduce this error on my mac, get exactly the same result as @georgeamccarthy , the code:

```python
import streamlit as st
from jina import Flow

if __name__ == '__main__':
    with Flow().add() as f:
        f.block()
```

**Comment by bwanglzu** [comment]
did some search on streamlit side, seems also related to [this](https://github.com/streamlit/streamlit/issues/1012#issue-554457159) one

**Comment by bwanglzu** [comment]
okay, I was checking @alexcg1 's example, thinks he already have a nice way to use Jina to play with streamlit:

1. you develop Jina as a backend project, independently.
2. you write a streamlit project with python, this project is used to interact with the Jina backend app.

this is what @alexcg1 done
1. [Jina app store](https://github.com/alexcg1/jina-app-store-example) example with pure Jina, no streamlit involved, serve as backend.
2. [Jina app store frontend](https://github.com/alexcg1/jina-app-store-frontend) point the connection string and parameters, and use `requests` to interact with Jina. and use `streamlit run app.py` inside front-end project.

**Comment by alexcg1** [comment]
I like being frontend agnostic on these things. My Streamlit frontend is quick and dirty and good enough. But if someone wants to create something better, more power to them!

Think of it as separation of church and state or something like that 😜

**Comment by bwanglzu** [comment]
@georgeamccarthy do you think the above workaround can solve your problem?

**Comment by bwanglzu** [comment]
@georgeamccarthy let me know if you need further help, I'll close this one.

**Comment by hanxiao** [comment]
This should be solved in https://github.com/jina-ai/jina/pull/3062

@georgeamccarthy  could you please do the following

- `pip install --pre jina` (update Jina to latest master, i.e. prerelease)
- set env `JINA_MP_START_METHOD="spawn"` in the console session **before starting Jina & Python**?
   ```bash
   export JINA_MP_START_METHOD=spawn
   python your_jina_app.py
   ```
   or 
   ```bash
   JINA_MP_START_METHOD=spawn python your_jina_app.py
   ```
  either should work.

A reproducible example can be found in the PR body of https://github.com/jina-ai/jina/pull/3062

**Comment by georgeamccarthy** [comment]
> @georgeamccarthy do you think the above workaround can solve your problem?

I've been using this and it's worked fine. However, it would be quite nice to pass DocumentArrays to the frontend instead of json datata especially when prototyping.

> This should be solved in https://github.com/jina-ai/jina/pull/3062
> 
> 
> 
> @georgeamccarthy  could you please do the following

Thanks, I'll try it!

**Comment by georgeamccarthy** [comment]
Reset environment
---
`source venv/bin/activate`
`python --version` shows Python 3.9.6
`pip freeze` has no packages installed

Install packages
---
Then `pip install jina streamlit`
Now `pip freeze` shows

```
altair==4.1.0
appnope==0.1.2
argon2-cffi==20.1.0
astor==0.8.1
async-generator==1.10
attrs==21.2.0
backcall==0.2.0
base58==2.1.0
bleach==3.3.1
blinker==1.4
cachetools==4.2.2
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
click==7.1.2
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
entrypoints==0.3
gitdb==4.0.7
GitPython==3.1.18
grpcio==1.39.0
idna==3.2
ipykernel==6.0.3
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jedi==0.18.0
jina==2.0.16
Jinja2==3.0.1
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
MarkupSafe==2.0.1
matplotlib-inline==0.1.2
mistune==0.8.4
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
numpy==1.21.1
packaging==21.0
pandas==1.3.1
pandocfilters==1.4.3
parso==0.8.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.1
prometheus-client==0.11.0
prompt-toolkit==3.0.19
protobuf==3.17.3
ptyprocess==0.7.0
pyarrow==5.0.0
pycparser==2.20
pydeck==0.6.2
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
PyYAML==5.4.1
pyzmq==22.1.0
requests==2.26.0
Send2Trash==1.7.1
six==1.16.0
smmap==4.0.0
streamlit==0.85.1
terminado==0.10.1
testpath==0.5.0
toml==0.10.2
toolz==0.11.1
tornado==6.1
traitlets==5.0.5
tzlocal==2.1
urllib3==1.26.6
validators==0.18.2
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
```

Minimum failing `app.py`
---

Running `app.py` with `streamlit run app.py` (not `python app.py`).
```
import streamlit as st
from jina import Document

st.write('Hello world!')
```

---

Throws error.

```
2021-08-03 12:24:40.360 Traceback (most recent call last):
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/venv/lib/python3.9/site-packages/streamlit/script_runner.py", line 350, in _run_script
    exec(code, module.__dict__)
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 3, in <module>
    from jina import Client, Document
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/venv/lib/python3.9/site-packages/jina/__init__.py", line 128, in <module>
    _signal.signal(_signal.SIGINT, _signal.default_int_handler)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```
---

Ran `export JINA_MP_START_METHOD=spawn`

Error:
```
UserWarning: multiprocessing start method is set to `spawn` (raised from /Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/venv/lib/python3.9/site-packages/jina/__init__.py:44)
2021-08-03 12:28:49.573 Traceback (most recent call last):
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/venv/lib/python3.9/site-packages/streamlit/script_runner.py", line 350, in _run_script
    exec(code, module.__dict__)
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/app.py", line 3, in <module>
    from jina import Document
  File "/Users/georgeamccarthy/Documents/workspace/python/jina-st-tets/venv/lib/python3.9/site-packages/jina/__init__.py", line 128, in <module>
    _signal.signal(_signal.SIGINT, _signal.default_int_handler)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

---

Ran `export JINA_MP_START_METHOD=spawn streamlit run app.py`

Error:

```
export: not valid in this context: app.py
```
