### ISSUE TITLE
Better logging with hub-push

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3011]
Failling in CD for `hub-push`

`HubIO@46[E]:Error while pushing session_id=73221246-e94f-11eb-9972-0242ac120002: 
Exception("Build failed. Detail: Command failed: docker --tlsverify -H=tcp://localhost:2376 --tlscacert=/certs/ca/cert.pem --tlscert=/certs/client/cert.pem --tlskey=/certs/client/key.pem build -t jinahub/***:v16 .\nThe command '/bin/sh -c pip install .' returned a non-zero code: 1\n")
Error: Process completed with exit code 1.`

REASON:

The user-provided Dockerfile missed some modules. We need better logging, the error info we provide is not user-friendly

**Comment by mapleeit** [comment]
https://github.com/jina-ai/hubble/commit/259c9b0983668d5f0d09a47765b4d51585d97d47
