### ISSUE TITLE
Using jina with docker-compose?

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3012]
I would like to know if it is possible to use jina with docker-compose - in the sense that we have one flow container, and each executor would be inside its own container.

I think docker-compose it _the most_ popular "local deployment" tool for multi-part applications and jina should support it. It would also give users a better understanding of how different parts of jina communicate with each other, which would enable a smoother transitions to more sophisticated deployments (kubernets, docker-swarm...)

**Comment by Rubix982** [comment]
High five here! I'm trying to do something similar with some code base that I have. I could not find an example that made maybe a full stack application with `jina` as a backend talking to a frontend that were both built with `docker-compose`.

... Although from a perspective of designing data intensive applications, I kind of get where you're coming with "in the sense that we have one flow container, and each executor would be inside its own container". Cool problem to work on, I would say.
