### ISSUE TITLE
How to deal with duplicate data?

### ISSUE THREAD

**Issue by JaheimLee** [jina-ai/jina#3014]
Hello everyone, I want to know how jina deal with duplicate data? For example, before indexing a new text, I want to make sure this text is not already in my DocumentArrayMemmap. What I thought is dong a match and make sure the top-1 text is not the same one before indexing. But it's not an elegant way. Thanks!

**Comment by bwanglzu** [comment]
@JaheimLee there is an easy way to do this:

```python
>>> from jina import Document, DocumentArray
>>> d = Document(text='test a')
>>> d2 = Document(text='test b')
>>> da = DocumentArray([d, d2])
>>> da
<jina.types.arrays.document.DocumentArray length=2 at 4418036016>
>>> d3 = Document(text='test a')
>>> d3.content_hash
'603f0a09311a02fb'
>>> d.content_hash
'603f0a09311a02fb'
>>> all_content_hashes = [d.content_hash for d in da]
>>> d.content_hash in all_content_hashes
True
```

**Comment by JaheimLee** [comment]
> @JaheimLee there is an easy way to do this:
> 
> ```python
> >>> from jina import Document, DocumentArray
> >>> d = Document(text='test a')
> >>> d2 = Document(text='test b')
> >>> da = DocumentArray([d, d2])
> >>> da
> <jina.types.arrays.document.DocumentArray length=2 at 4418036016>
> >>> d3 = Document(text='test a')
> >>> d3.content_hash
> '603f0a09311a02fb'
> >>> d.content_hash
> '603f0a09311a02fb'
> >>> all_content_hashes = [d.content_hash for d in da]
> >>> d.content_hash in all_content_hashes
> True
> ```
> 
> the content hash won't change until you change the content of the Document

Thanks a lot!
