### ISSUE TITLE
Add delete-all interface to `JinaDClient`

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#3024]
**Describe the feature**
Implement client methods for the following endpoints:
- DELETE /workspaces
- DELETE /flows
- DELETE /pods
- DELETE /peas

**Comment by sandipanpanda** [comment]
Can you assign this to me? I want to fix this issue.

**Comment by AnudeepGunukula** [comment]
Hi i am interested in this project, i would like to work on this issue.

**Comment by deepankarm** [comment]
@AnudeepGunukula awesome. Looking forward to a PR :)

**Comment by AnudeepGunukula** [comment]
Hi, please let me know  what is the location of the jinadclient module
and where should i start working from ?

**Comment by deepankarm** [comment]
@AnudeepGunukula [Here's the JinaDClient module](https://github.com/jina-ai/jina/tree/master/daemon/clients). Please add a `clear` method to `base.py` that should sent a `DELETE` request to `self.store_api`.  Don't forget to add tests for the same.

**Comment by AnudeepGunukula** [comment]
Thankyou, for the details, i will start working on it and try to implement the methods.

**Comment by deepankarm** [comment]
I've assigned the issue to you. Looking forward to a PR :)

**Comment by AnudeepGunukula** [comment]
@if_alive   
 async def clear(self):
        async with aiohttp.request(method='DELETE',url=f'{self.store_api}') as response:
             if response.status == HTTPStatus.OK:
                 return await response.json()

Hi deepankarm, i have just implemented the sample method . kindly let me know what are the needed changes
so that i can work on that

**Comment by AnudeepGunukula** [comment]
![clear](https://user-images.githubusercontent.com/55506841/128387596-b829524b-bbfd-47f6-b48f-316f1eb43ef6.PNG)
Hi deepankarm, i have just implemented sample method, which makes a delete call to api
kindly let me know, what i need to add more to function.
so that i can work on that

**Comment by deepankarm** [comment]
Sounds good, please [follow the guidelines to create a PR](https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#-making-your-first-submission).

**Comment by AnudeepGunukula** [comment]
Hi, deepankarm. please let me know the modifications.
 so that i can work on that and make new commits to the pr.

**Comment by AnudeepGunukula** [comment]
Hi @deepankarm, i had made a new pr with the both clear and test method.
i had closed the old pr with wrong commit message.
The new pr is #3142 , kindly let me know the modifications.
