### ISSUE TITLE
DocumentArrayMemmap OSError: [Errno 22] Invalid argument when reloading file

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#3026]
running the following snippet twice should result in `OSError: [Errno 22] Invalid argument `
```python
from jina.types.arrays.memmap import DocumentArrayMemmap
from jina import Document
dam = DocumentArrayMemmap("my_dam")
d = Document()
dam.append(d)
dam[0] = Document()

print(dam[0])
```

when computing `self._start`, a none entry is considered the last used document block and it's values (all are -1) are used to compute `self._start`

**Comment by bwanglzu** [comment]
i can reproduce the error when running it first time (run the command 2 times). @alaeddine-13 are you able to fix this?

**Comment by alaeddine-13** [comment]
@bwanglzu was fixed by https://github.com/jina-ai/jina/pull/3002
