### ISSUE TITLE
DocumentArray.match on itself produces recursive results

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#3034]
**Describe the bug**

```python
from jina import DocumentArray, Document
```

```python
import numpy as np
```

```python
da = DocumentArray([Document(embedding=np.array([1,2,3])), 
                    Document(embedding=np.array([1,0,1])),
                    Document(embedding=np.array([1,1,2]))])
```

Now match against itself.

```python
da.match(da)
```

Check the structure of the first document, this looks correct.

```python
da[0]
```

<img src="https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyNGRkM2NjYnfX19JSUKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNsYXNzRGlhZ3JhbQogICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgNjNlfkRvY3VtZW50fiAuLj4gIjEvMyIgYjQ4fkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyBiNDh+RG9jdW1lbnR+eworaWQgMGJjNmZiYWEtZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCAxN2ZmMTkxOGQwCitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CjYzZX5Eb2N1bWVudH4gLi4+ICIyLzMiIDM1YX5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgMzVhfkRvY3VtZW50fnsKK2lkIDBiYzcxMjUyLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggMTc5NDYzOTQxNworc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQo2M2V+RG9jdW1lbnR+IC4uPiAiMy8zIiAyYTl+RG9jdW1lbnR+OiBtYXRjaGVzCmNsYXNzIDJhOX5Eb2N1bWVudH57CitpZCAwYmM3MGIxOC1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIGRiM2E1MmU5NmIKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KY2xhc3MgNjNlfkRvY3VtZW50fnsKK2lkIDBiYzZmYmFhLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2NvbnRlbnRfaGFzaCAzMmZlZjkxMmY0Cn0="/>

Now check the structure of the second document, this looks weird already. As it includes the *modified version* of first document, not the original first document.

```python
da[1]
```

<img src="https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyNGRkM2NjYnfX19JSUKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNsYXNzRGlhZ3JhbQogICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWVkfkRvY3VtZW50fiAuLj4gIjEvMyIgY2U5fkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyBjZTl+RG9jdW1lbnR+eworaWQgMGJjNzBiMTgtZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCA4ODQzMjI2NDVmCitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CmFlZH5Eb2N1bWVudH4gLi4+ICIyLzMiIDkzOH5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgOTM4fkRvY3VtZW50fnsKK2lkIDBiYzcxMjUyLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggN2Y4YzMyODA3Yworc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQphZWR+RG9jdW1lbnR+IC4uPiAiMy8zIiBkZDV+RG9jdW1lbnR+OiBtYXRjaGVzCmRkNX5Eb2N1bWVudH4gLi4+ICIxLzMiIDk0YX5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgOTRhfkRvY3VtZW50fnsKK2lkIDBiYzZmYmFhLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggMTdmZjE5MThkMAorc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQpkZDV+RG9jdW1lbnR+IC4uPiAiMi8zIiA3YzZ+RG9jdW1lbnR+OiBtYXRjaGVzCmNsYXNzIDdjNn5Eb2N1bWVudH57CitpZCAwYmM3MTI1Mi1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIDE3OTQ2Mzk0MTcKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KZGQ1fkRvY3VtZW50fiAuLj4gIjMvMyIgOGYxfkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyA4ZjF+RG9jdW1lbnR+eworaWQgMGJjNzBiMTgtZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCBkYjNhNTJlOTZiCitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CmNsYXNzIGRkNX5Eb2N1bWVudH57CitpZCAwYmM2ZmJhYS1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIDFlODZlMTdkMDIKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KY2xhc3MgYWVkfkRvY3VtZW50fnsKK2lkIDBiYzcwYjE4LWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2NvbnRlbnRfaGFzaCBiZDliYzY0OGU2Cn0="/>

This recursion goes on and on, and the third Document now looks even more complicated.

```python
da[2]
```

<img src="https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyNGRkM2NjYnfX19JSUKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNsYXNzRGlhZ3JhbQogICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZjBifkRvY3VtZW50fiAuLj4gIjEvMyIgN2Q3fkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyA3ZDd+RG9jdW1lbnR+eworaWQgMGJjNzEyNTItZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCAyZDExZmJlYWU0CitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CmYwYn5Eb2N1bWVudH4gLi4+ICIyLzMiIGYwMX5Eb2N1bWVudH46IG1hdGNoZXMKZjAxfkRvY3VtZW50fiAuLj4gIjEvMyIgMDM0fkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyAwMzR+RG9jdW1lbnR+eworaWQgMGJjNmZiYWEtZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCAxN2ZmMTkxOGQwCitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CmYwMX5Eb2N1bWVudH4gLi4+ICIyLzMiIDE1Mn5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgMTUyfkRvY3VtZW50fnsKK2lkIDBiYzcxMjUyLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggMTc5NDYzOTQxNworc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQpmMDF+RG9jdW1lbnR+IC4uPiAiMy8zIiBmMTh+RG9jdW1lbnR+OiBtYXRjaGVzCmNsYXNzIGYxOH5Eb2N1bWVudH57CitpZCAwYmM3MGIxOC1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIGRiM2E1MmU5NmIKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KY2xhc3MgZjAxfkRvY3VtZW50fnsKK2lkIDBiYzZmYmFhLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggODI4ZjIzZDA0ZQorc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQpmMGJ+RG9jdW1lbnR+IC4uPiAiMy8zIiBhMmV+RG9jdW1lbnR+OiBtYXRjaGVzCmEyZX5Eb2N1bWVudH4gLi4+ICIxLzMiIDMzZX5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgMzNlfkRvY3VtZW50fnsKK2lkIDBiYzcwYjE4LWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggODg0MzIyNjQ1Zgorc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQphMmV+RG9jdW1lbnR+IC4uPiAiMi8zIiAyODh+RG9jdW1lbnR+OiBtYXRjaGVzCmNsYXNzIDI4OH5Eb2N1bWVudH57CitpZCAwYmM3MTI1Mi1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIDdmOGMzMjgwN2MKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KYTJlfkRvY3VtZW50fiAuLj4gIjMvMyIgMDhjfkRvY3VtZW50fjogbWF0Y2hlcwowOGN+RG9jdW1lbnR+IC4uPiAiMS8zIiA3N2R+RG9jdW1lbnR+OiBtYXRjaGVzCmNsYXNzIDc3ZH5Eb2N1bWVudH57CitpZCAwYmM2ZmJhYS1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIDE3ZmYxOTE4ZDAKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KMDhjfkRvY3VtZW50fiAuLj4gIjIvMyIgZDA2fkRvY3VtZW50fjogbWF0Y2hlcwpjbGFzcyBkMDZ+RG9jdW1lbnR+eworaWQgMGJjNzEyNTItZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCAxNzk0NjM5NDE3CitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CjA4Y35Eb2N1bWVudH4gLi4+ICIzLzMiIDNiNH5Eb2N1bWVudH46IG1hdGNoZXMKY2xhc3MgM2I0fkRvY3VtZW50fnsKK2lkIDBiYzcwYjE4LWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2FkamFjZW5jeSAxCitjb250ZW50X2hhc2ggZGIzYTUyZTk2Ygorc2NvcmVzKDxjbGFzcyAnamluYS50eXBlcy5zY29yZS5tYXAuTmFtZWRTY29yZU1hcHBpbmcnPikKfQpjbGFzcyAwOGN+RG9jdW1lbnR+eworaWQgMGJjNmZiYWEtZgorZW1iZWRkaW5nKDxjbGFzcyAnbnVtcHkubmRhcnJheSc+KQorYWRqYWNlbmN5IDEKK2NvbnRlbnRfaGFzaCAxZTg2ZTE3ZDAyCitzY29yZXMoPGNsYXNzICdqaW5hLnR5cGVzLnNjb3JlLm1hcC5OYW1lZFNjb3JlTWFwcGluZyc+KQp9CmNsYXNzIGEyZX5Eb2N1bWVudH57CitpZCAwYmM3MGIxOC1mCitlbWJlZGRpbmcoPGNsYXNzICdudW1weS5uZGFycmF5Jz4pCithZGphY2VuY3kgMQorY29udGVudF9oYXNoIDQyNzY1MzY5NDMKK3Njb3Jlcyg8Y2xhc3MgJ2ppbmEudHlwZXMuc2NvcmUubWFwLk5hbWVkU2NvcmVNYXBwaW5nJz4pCn0KY2xhc3MgZjBifkRvY3VtZW50fnsKK2lkIDBiYzcxMjUyLWYKK2VtYmVkZGluZyg8Y2xhc3MgJ251bXB5Lm5kYXJyYXknPikKK2NvbnRlbnRfaGFzaCA1YmE5M2E4YTBjCn0="/>

As it is always recursion, matching against itself quickly becomes unusable.

```python
from jina import DocumentArray
from jina.logging.profile import TimeContext
from tests import random_docs

for j in range(1, 8):
    da = DocumentArray(list(random_docs(2 * j)))
    with TimeContext(f'da.match(da), where len(da)={len(da)}'):
        da.match(da)
```

```text
da.match(da), where len(da)=2 ...	da.match(da), where len(da)=2 takes 0 seconds (0.00s)
da.match(da), where len(da)=4 ...	da.match(da), where len(da)=4 takes 0 seconds (0.02s)
da.match(da), where len(da)=6 ...	da.match(da), where len(da)=6 takes 0 seconds (0.09s)
da.match(da), where len(da)=8 ...	da.match(da), where len(da)=8 takes 0 seconds (0.42s)
da.match(da), where len(da)=10 ...	da.match(da), where len(da)=10 takes 2 seconds (2.09s)
da.match(da), where len(da)=12 ...	da.match(da), where len(da)=12 takes 9 seconds (9.88s)
da.match(da), where len(da)=14 ...	da.match(da), where len(da)=14 takes 50 seconds (50.28s)
```

---

**Environment**

**Screenshots**

**Comment by tadejsv** [comment]
Here are the findings of my research on this issue. The core of the problem is how matches are added to the document. Consider this example (does not use the `match` function at all):

```python
import numpy as np
from jina import Document, DocumentArray

docs = DocumentArray(
    [
        Document(id='1', embedding=np.array([1, 2])),
        Document(id='2', embedding=np.array([2, 1])),
    ]
)

docs[0].matches = [docs[0], docs[1]]
docs[1].matches = [docs[1], docs[0]]

assert len(docs[1].matches[1].matches) == 2
assert len(docs[1].matches[1].matches[0].matches) == 0
assert len(docs[1].matches[1].matches[1].matches) == 0
```

What happens is actually pretty logical - the second match of the document with id `2` (which is document with id `1`) has itself two matches. This happens because we first add two matches to document with id `1`, and then add this document as a match.

What was more puzzling to me is that after that level, the recursion stops. I discovered that this happens because when you add a match, it actually creates a copy of the document - not a reference to it https://github.com/jina-ai/jina/blob/8f01fcec00d7d5be04360940e3661fdff3aae93b/jina/types/arrays/match.py#L31

Now back to the `match` method. We can see the problem appears here https://github.com/jina-ai/jina/blob/2302e456165810c9d9f8d6df1505a0aabd2edc76/jina/types/arrays/neural_ops.py#L78-L84

The problem is that the `d` documents that are being added have previously gotten matches themselves. So these matches must be somehow cleared. I can think of some possible solutions:
- check if the document (`d`) is actually in `self` - if that is the case, before adding it, create a copy and clear matches on the copy
- just create a copy of all documents from `darray` before starting the procedure
- something else?

Here we should be careful, as it seems a lot of copies are already being created in the background, and we would not want to add more, for performance and efficiency reasons.

I would hand this over at this point to @bwanglzu, as he has a better understanding of the core than I do.

**Comment by bwanglzu** [comment]
I don't really have a beautiful solution, but 
> check if the document (d) is actually in self - if that is the case, before adding it, create a copy and clear matches on the copy
sounds the best for us.
