### ISSUE TITLE
The name of the HTML file needs change. 

### ISSUE THREAD

**Issue by rudranshsharma123** [jina-ai/jina#3054]
**Describe the bug**

The name of the HTML file generated when running `jina hello fashion` is demo.html instead of hello-world.html as suggested in the code. Because of which the example crashes resulting in the error as depicted by the screenshot attached.

**Describe how you solve it**

By simply opening the demo.html page manually, does the trick and opening demo.html while running a server also works!
The code here needs a change https://github.com/jina-ai/jina/blob/master/jina/helloworld/fashion/helper.py#L146 
(I got help one the amazing slack community)
---

**Environment**

I was running Jina on WSL-2 running Ubuntu 20.04 LTS distro. 
- jina 2.0.13
- jina-proto 0.0.85
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.1
- protobuf 3.17.3
- proto-backend cpp
- grpcio 1.39.0
- pyyaml 5.3.1
- python 3.8.5
- platform Linux
- platform-release 5.10.16.3-microsoft-standard-WSL2
- platform-version #1 SMP Fri Apr 2 22:23:49 UTC 2021
- architecture x86_64
- processor x86_64
- uid 91755995782
- session-id 044a3c62-f14d-11eb-9ee4-00155d156286
- uptime 2021-07-30T21:14:24.961099
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset) 

**Screenshots**

![image](https://user-images.githubusercontent.com/67827010/127678110-8a6b032a-ae89-48d4-921d-daebe3a1561b.png)

**Comment by vj-codes** [comment]
Can I work on this?

**Comment by Roshanjossey** [comment]
I guess this need change in documentation as well
https://github.com/jina-ai/jina/blame/master/.github/pages/hello-world.md#L21

**Comment by sayantani11** [comment]
Can I work on this?

**Comment by JoanFM** [comment]
This has been clarified in the `documentation`
