### ISSUE TITLE
`traverse_flat` does not wok on ChunkArray or MatchArray

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3068]
Example:

```python
from jina import Document
d = Document(chunks=[Document()], matches=[Document()])

d.matches.traverse_flat() # Will break
d.chunks.traverse_flat() # Will break
```

Here's the error (for chunks)
```
  File "<stdin>", line 1, in <module>
  File "/home/tadej/miniconda/envs/dpr_reader/lib/python3.8/site-packages/jina/types/arrays/traversable.py", line 91, in traverse_flat
    return self._flatten(leaves)
  File "/home/tadej/miniconda/envs/dpr_reader/lib/python3.8/site-packages/jina/types/arrays/traversable.py", line 95, in _flatten
    return cls(list(itertools.chain.from_iterable(sequence)))
TypeError: __init__() missing 1 required positional argument: 'reference_doc'
```

**Comment by JoanFM** [comment]
This is because `traverse_flat` does not accept extra kwargs, but I am feeling this should not exist for `MatchArray` and `ChunkArray` but since they are inherited from `DocumentArray` it is weird

**Comment by tadejsv** [comment]
Yes, I am aware this is the reason. But I think that methods inherited from superclass should work on the subclass

**Comment by JoanFM** [comment]
I think the problem is `flatten` should not be a `classmethod` but a `staticmethod` generating a `DocumentArray`. 

So `make` _flatten an abstract method that needs to be overwritten by the class that implements the `mixin` and have this `_flatten` only at `DocumentArray` level.
