### ISSUE TITLE
flow.plot()

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3072]
1. `flow.plot('some.png')` does not create a png. Instead, it creates a file called `some.png` which contains an `svg`. https://github.com/jina-ai/jina/pull/3074
2. `svg` plot can not be displayed in pycharm

**Comment by JoanFM** [comment]
Apparently `svg` is not considered. Not sure why.

```python
        image_type = 'svg'
        if output and output.endswith('jpg'):
            image_type = 'jpg'
```

**Comment by JoanFM** [comment]
I think this might be a limitation from `mermaid`

**Comment by JoanFM** [comment]
yes, see this 
```https://mermaid.ink/png/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ``` 

does not work, while

```
https://mermaid.ink/svg/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
```
work.

**Comment by JoanFM** [comment]
Can u check if the branch on #3074 works?

**Comment by florian-hoenicke** [comment]
Good job fixing the png issue.
The pycharm related issue still exists:
Steps to reproduce:
```
from jina import Flow
f = Flow().add().add()
f.plot('test.svg')
```
![image](https://user-images.githubusercontent.com/11627845/127904247-d49794df-f75c-4259-b3e8-cd966717fd32.png)

**Comment by JoanFM** [comment]
I think this issue is a `Pycharm` issue not a Jina one

**Comment by JoanFM** [comment]
I will close this issue.
