### ISSUE TITLE
A match should have a property referring to its reference doc

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3086]
Right now, chunks of documents have `parent_id`. But matches do not have any property referring to their reference doc - even though `MatchArray` has it.

**Comment by JoanFM** [comment]
This is a `Score` property.

**Comment by tadejsv** [comment]
Can you explain?

**Comment by JoanFM** [comment]
`NamedScoreProto` has `ref_id` property to refer to which documentID u are a match of

**Comment by tadejsv** [comment]
Ok, but I do not see `NamedScoreProto` or `NamedScore` being used anywhere?

And in the end, what I want to do is to find out what document a match is refering to. I think this should be a document property, not a score property, just like with chunk documents.

**Comment by JoanFM** [comment]
This is used when u add matches u are supposed to add a score. I do not think it should be since one can be a match of multiple documents

**Comment by tadejsv** [comment]
But currently this is not done anywhere, not even in `DocumentArray.match()`. Also, I think it would be better to copy the match (this was actually the default until 3 days ago) every time it is added to the `matches` array of some document - otherwise things can get really confusing.

**Comment by tadejsv** [comment]
Wait, you are right - it is actually used.

**Comment by tadejsv** [comment]
Ok, it is actually not. Every single indexer we have simply sets the score to a numeric value and that's it.

**Comment by JoanFM** [comment]
Then it should be used

**Comment by tadejsv** [comment]
Not sure this is a good design - I raised this issue in the slack chanel

**Comment by CatStark** [comment]
We won't continue with this because then we would need to always copy when adding matches, which is not the case. https://github.com/jina-ai/jina/pull/3148
