### ISSUE TITLE
pea_id not set in metas

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3089]
The IndexSearcher relies on pea_id.
 However, the metas are not set correctly when starting the executor via CLI.
 
 ```
jina executor --uses config --pea_id=2
 ```
 
 ```
  File "/workspace/__init__.py", line 56, in __init__
    ids, vecs = import_vectors(dump_path, str(self.metas.pea_id))
AttributeError: 'types.SimpleNamespace' object has no attribute 'pea_id'
```

**Comment by JoanFM** [comment]
can u try ```pea-id 2```

**Comment by JoanFM** [comment]
or `uses_metas`

**Comment by florian-hoenicke** [comment]
ah sorry. Yes, I did not use the equals sign. I did pea-id 2.
It works with `override_metas`.

**Comment by JoanFM** [comment]
`pea_id` should not be part of `metas`, this is part of `runtime_args` and for a good reason. To abstract the functional part of the executor witht he implementaiton details to be hidden.
