### ISSUE TITLE
metas - code refactoring

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3094]
replace 
`override_metas` and  `override_with` 
with
`uses_metas` and `uses_with`

**Comment by soumik2012** [comment]
hey @florian-hoenicke can I take this issue

**Comment by JoanFM** [comment]
I believe this is alrrady in the core

**Comment by JoanFM** [comment]
And it was made in a way that it was backward compatible with override_* naming. I will close this issue.
