### ISSUE TITLE
Remove the setting by document id completely

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3121]
We need an use-case for the following:

 Remove the setting by document id completely. Or at least, we should get a very clear picture, what the output of the following code should be:

```
d1 = Document(id=1, text='hello')
d2 = Document(d1, copy=True)

da = DocumentArray()
da.append(d1)
da.append(d2)
d1.text = 'world'
da[0].text => 'world'
da[1].text => 'hello'
da[d1.id].text => ???
```
This can happen when we bubble up matches from a lower layer to a higher layer. Then the matches of a Document can easily be the same Document with the same id twice.

**Comment by JoanFM** [comment]
This is needed by `graph-document` so I would say we cannot remove this

**Comment by JoanFM** [comment]
Also the `fill_embedding` endpoints for `SimpleIndexer` use it. I think we should close this issue @maximilianwerk

**Comment by mohtasham9** [comment]
we can't remove, as it is needed by `SimpleIndexer` and `graph-document`.  It is better to close the issue.

**Comment by maximilianwerk** [comment]
OK, I will close the issue. Anyhow, the problem of unexpected behavior stays.
