### ISSUE TITLE
docker:// syntax no longer supported

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#3124]
Did we discontinue using `--uses docker://foo:latest`?

on latest master I get

``` ZEDRuntime@45681[E]:fail to load config from docker://foo:latest, if you are using docker image for --uses, please use "docker://YOUR_IMAGE_NAME"
Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/jaml/helper.py", line 160, in parse_config_source
    tmp = json.loads(path)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cristian/code/jina/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 85, in _load_executor
    runtime_args=vars(self.args),
  File "/home/cristian/code/jina/jina/jaml/__init__.py", line 510, in load_config
    stream, s_path = parse_config_source(source, **kwargs)
  File "/home/cristian/code/jina/jina/jaml/helper.py", line 164, in parse_config_source
    raise BadConfigSource(path)
jina.excepts.BadConfigSource: docker://foo:latest```

works on 2.0.16

**Comment by hanxiao** [comment]
### 🆕 New Features

 - [[```fa7c4770```](https://github.com/jina-ai/jina/commit/fa7c4770a4377247c8e1ea5739fb051df64140b1)] __-__ add data request handler (#3105) (*Joan Fontanals*)
 - [[```4e14b19e```](https://github.com/jina-ai/jina/commit/4e14b19eb3c7f4a6cc98034555431c2d0abe526b)] __-__ __daemon__: rolling update via client (#3111) (*Deepankar Mahapatro*)
 - [[```3329576f```](https://github.com/jina-ai/jina/commit/3329576f66833c542cc410570c6025d8fa7781fe)] __-__ change default entrypoint and allow runtimes in main process (#2985) (*Joan Fontanals*)
 - [[```990a51d6```](https://github.com/jina-ai/jina/commit/990a51d6a69a40146e6705eb0b8e6caf841a6fcc)] __-__ __executor__: add uses-requests cli to override requests in Executor (#3092) (*Han Xiao*)
 - [[```3ff5fe98```](https://github.com/jina-ai/jina/commit/3ff5fe98fc9f52ebc0dc7221edf4a9a79e9bf3cf)] __-__ connect to pred config (#3051) (*Maximilian Werk*)

### 🐞 Bug fixes

 - [[```01564f94```](https://github.com/jina-ai/jina/commit/01564f946174255741ef75a2addc2c7637dbe9e0)] __-__ __http__: tag update (#3108) (*Deepankar Mahapatro*)
 - [[```55df38f7```](https://github.com/jina-ai/jina/commit/55df38f7aa52630b9371aaac344e56267c9c91b2)] __-__ delete and list workspaces (#3102) (*Deepankar Mahapatro*)
 - [[```44054eea```](https://github.com/jina-ai/jina/commit/44054eeaec1a005f7897dfa5a4c090710539d341)] __-__ add sparse support (#3097) (*David Buchaca Prats*)

### 🧼 Code Refactoring

 - [[```2aee8360```](https://github.com/jina-ai/jina/commit/2aee8360ba401a6ed58ae497c47f5f6df6515ff3)] __-__ improve document update method (#3112) (*Wang Bo*)
 - [[```c69d97bf```](https://github.com/jina-ai/jina/commit/c69d97bf5fd44a7a7b4bd3e8f0a859e11d98fde2)] __-__ remove attribute (#3117) (*Joan Fontanals*)
 - [[```ed3ff21e```](https://github.com/jina-ai/jina/commit/ed3ff21eddf1c00b71a17de58fc06e52b975e1a4)] __-__ change bind to all inbound (#3069) (*Sebastian Lettner*)

### 📗 Documentation

 - [[```f9755fd7```](https://github.com/jina-ai/jina/commit/f9755fd7b150857ea9dcef79853e8c23454a3604)] __-__ added add method configs (#3066) (*Maximilian Werk*)
 - [[```6a58fdef```](https://github.com/jina-ai/jina/commit/6a58fdefb09cc8e0be0bd63f223ed01f191e50b8)] __-__ fix guy - person (#3115) (*cristian*)

### 🍹 Other Improvements

 - [[```bc85e73a```](https://github.com/jina-ai/jina/commit/bc85e73ae25ece635d21130d0f8e2c99dea3452e)] __-__ __contributor__: update contributors (*Jina Dev Bot*)
 - [[```ee1b8d12```](https://github.com/jina-ai/jina/commit/ee1b8d12e1e573c26fc62ca6fb15abc80493da12)] __-__ __docs__: update TOC (*Jina Dev Bot*)
 - [[```066c2938```](https://github.com/jina-ai/jina/commit/066c29386cb94d4cee1a7e8eeb56938e579ef957)] __-__ __version__: the next version will be 2.0.17 (*Jina Dev Bot*)
