### ISSUE TITLE
Fix module imports + test relative imports + remove redundant patch + update docs

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3143]
1. The module importing in `PathImporter` should be fixed - the name passed in `spec_file_from_location` and `spec_name` **need** to match, otherwise you mess up relative imports (and possibly more)
https://github.com/jina-ai/jina/blob/b099fc3027e521a5100102710423ebf2003b6701/jina/importer.py#L180-L201

2. We should test importing using relative paths when `__init__.py` is imported - should work automatically without any extra imports, and for any file structure within the module

3. Importing sub-modules by absolute name (e.g. `from submodule import a` instead of `from .submodule import a`) is an anti-pattern - it mixes together running the code as module vs running from main. Since relative imports work (see point 2), the patch that enables this is not needed - https://github.com/jina-ai/jina/pull/2953 needs to be reversed

4. Documentation should be updated - importing several `pymodules` should **not** be encouraged, how to take advantage of normal python modules/file structure should be shown. Also, we might start encouraging putting all the code in `executor/` folder - this follows the structure of normal python modules/packages, as well as enables all 3 types of execution (local/console, pytest (import) and jina)

**Comment by JoanFM** [comment]
Can u provide an example in the documentation  where u would change how something would be recommended?

**Comment by tadejsv** [comment]
Yes, I plan to make PRs that address the points here

**Comment by JoanFM** [comment]
About putting executors inside `executor/` path. This I think direcly collides with the way `JinaD` expects `python` files to be added into `workspace`. @deepankarm @mapleeit

**Comment by cristianmtr** [comment]
btw in order to reproduce the `jinahub`-specific error, you can remove this line and run `jina executor --uses docker://foo:latest` (where foo is the image of the executor) https://github.com/jina-ai/executors/blob/main/jinahub/indexers/searcher/compound/FaissPostgresSearcher/Dockerfile#L12
