### ISSUE TITLE
AttributeError: module 'mmap' has no attribute 'PROT_READ'

### ISSUE THREAD

**Issue by agarwalsourabh55** [jina-ai/jina#3154]
**Describe the bug**

**Describe how you solve it**

---

**Comment by numb3r3** [comment]
@agarwalsourabh55 The `PROT_READ`  is Unix-specific. You're likely working with Windows?

**Comment by agarwalsourabh55** [comment]
@nummb3r3 Yes....So how to imlemet this in window ..any idea?

**Comment by agarwalsourabh55** [comment]
@numb3r3  Yes.....SO how to implement it with windows any idea?

**Comment by JoanFM** [comment]
Hey @agarwalsourabh55 ,

Windows is currently not supported. We recommend you to use `WSL`.

**Comment by JoanFM** [comment]
Hey @agarwalsourabh55 ,

Since `Windows` is not currently supported, I am going to close the issue. However, we recommend to install `Windows Subsystem for Linux` (WSL) https://docs.microsoft.com/en-us/windows/wsl/install-win10 to work with jina
