### ISSUE TITLE
Table to see when to use DA, DAM or specific Hub indexer

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3155]
As a user I want to have a table to know the limitation of `DA`, `DAM` 
We need to see a number, a bound or a table, like:

For less than 1M docs -> work with `DAM`
For 1K docs -> work with `DA` 

PR: https://github.com/jina-ai/benchmark/pull/35

Note: To compare with a hub indexer should be a different ticket

**Comment by JoanFM** [comment]
Table can be found in https://benchmark.jina.ai/docs/indexer_comparison/
