### ISSUE TITLE
Make jina available on conda-forge

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3160]
- check that all jina dependencies are on conda (forge)
- create a small script that converts jina's dependencies to conda recipe yaml to create multiple packages for each extras (see here for an example https://github.com/conda-forge/dvc-feedstock/blob/master/recipe/meta.yaml)
- publish package to conda forge
- automate this process - bot could update the recipe and submit a PR to jina's conda-forge feedstock repo on each jina update (needed only because of dependencies)

**Comment by CatStark** [comment]
Duplicate https://github.com/jina-ai/jina/issues/3169
