### ISSUE TITLE
DocumentArray construction from list of dictionaries

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3165]
It would be handy to create a DocumentArray from a list of dictionaries. At the moment it is just possible to create it from a list of documents.

**Comment by JoanFM** [comment]
Why cant u simply construct the list of Docs from a list of Dictionaries?

**Comment by florian-hoenicke** [comment]
@JoanFM I can but it is more convenient. I had a list of dictionaries. So it is less work for me to directly pass this list and let the document array do the document creation.

**Comment by JoanFM** [comment]
Yes, but then when should this end? Every potential input of Document should be matched into the constructor of DocumentArray?

**Comment by florian-hoenicke** [comment]
I think if we create a `DocumentArray(something)`, it should expect another document array or an iterator.
For each element in the iterator, it calls the Document constructor `Document(...)`. The Document can be constructed from another document or from a dictionary

**Comment by JoanFM** [comment]
Will close the issue until a more convincing necessity arises
