### ISSUE TITLE
[Documentation] SVGs With GitHub's Dark Theme

### ISSUE THREAD

**Issue by Rubix982** [jina-ai/jina#3166]
**Describe the bug**
Because GitHub has introduced the dark mode, it is harder to read the documentation on GitHub since the figures are in the SVG format, for example,

- [jina/.github/2.0/cookbooks/Document.md](https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Document.md)

![image](https://user-images.githubusercontent.com/41635766/129469797-46ed498f-fc37-487d-9d91-621a736c9d98.png)

![image](https://user-images.githubusercontent.com/41635766/129469815-471c2fd9-0224-40f2-98b7-32f42430405a.png)

- [jina/.github/2.0/cookbooks/Executor.md](https://github.com/jina-ai/jina/blob/master/.github/2.0/cookbooks/Executor.md)

![image](https://user-images.githubusercontent.com/41635766/129469830-806b6b93-8c8b-4925-8e0e-011b2667d322.png)

![image](https://user-images.githubusercontent.com/41635766/129469836-978d083a-585c-4cff-adba-aa39cbd48a57.png)

**Describe how you solve it**
An easy solution would be to convert the SVGs to PNGs with a white background. I would be happy to open a PR for this. :smile: 

This can be labelled as a `good first issue`, and `documentation`.

---

Documentation inside the [Cookbooks](https://github.com/jina-ai/jina/tree/master/.github/2.0/cookbooks).

**Environment**
N/A

**Screenshots**
PFA at the top.

**Comment by CatStark** [comment]
Hi @Rubix982, 
Thanks for bringing this up. And sure thing, go ahead with the PR

**Comment by Rubix982** [comment]
Thanks, @CatStark!

**Comment by JoanFM** [comment]
This seems to be good in the current `README.md`
