### ISSUE TITLE
Polling does not have to be set manually

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3187]
When writing a flow for searching on shards, we currently have to specify the attribute polling='all'.
    It would be more convenient if this attribute is set automatically when using shards.
   If you use `replicas` polling should be set to `any` implicitly.

    ```
    with Flow().add(
            uses=...,
            uses_after=...,
            shards=3,
            polling='all'
    ) as f:
        f.search(docs, on_done=callback)
        ```

**Comment by JoanFM** [comment]
> ```
> When writing a flow for searching on shards, we currently have to specify the attribute polling='all'.
> It would be more convenient if this attribute is set automatically when using shards.
> ```
> 
> If you use `replicas` polling should be set to `any` implicitly.
> 
> ```
> ```
> with Flow().add(
>         uses=...,
>         uses_after=...,
>         shards=3,
>         polling='all'
> ) as f:
>     f.search(docs, on_done=callback)
>     ```
> ```

This is curently not doable, because `shards` is `parallel` when scaling up other executors that are not `indexers`. 

This may come when we refactor `Pea/Pods` but cannot be done at this stage

**Comment by CatStark** [comment]
So we put this in the backlog? not something we'll work with any time soon right? @florian-hoenicke

**Comment by florian-hoenicke** [comment]
@JoanFM could we not just set polling according to if the user types shards or replicas?
I feel like this would just be a few lines of code.

**Comment by JoanFM** [comment]
Since CompoundPod will likely disappear very soon, I think is undesired. Right now parallel is used for having multiple encoders for instance. 

I think in rhe future may be clarified, but I would not touch this at this moment
