### ISSUE TITLE
Raise error when using grpc data runtime with shards

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3197]
The new GrpcDataRuntime (https://github.com/jina-ai/jina/blob/master/jina/peapods/runtimes/grpc/__init__.py) does not support sharding at the moment. Thus a Flow should not specify this runtime and a sharded pod at the same time.

Right now this will not raise any error, but silently produce unexpected behavior. This is undesirable and the Flow should rather check this condition and raise an appropriate error so that the user can fix its Flow configuration.

**Comment by unnati914** [comment]
Can I take up this issue?
Thank you!

**Comment by maximilianwerk** [comment]
@unnati914 sure. If you have any questions, please join our [slack](https://slack.jina.ai/) and ask in the #contributor channel. :)

**Comment by unnati914** [comment]
tysm :)

**Comment by jacobowitz** [comment]
@unnati914 thx for picking it up!

As an example, this Flow definition is not working and should raise an error:

`Flow(grpc_data_requests=True).add(shards=2)`

**Comment by jacobowitz** [comment]
@unnati914 
Are there any updates on this one? Can I assist you with anything?

**Comment by bhattalok49** [comment]
hi, can  i work on this issue ?

**Comment by CatStark** [comment]
Hi @bhattalok49, i think @unnati914 is unavailable at the moment so yes you can work on this :) I'll re assign it to you

**Comment by RaghavPrabhakar66** [comment]
@CatStark Can I work on this issue?

**Comment by jacobowitz** [comment]
@bhattalok49 did not react, so I guess its fine.

Thank you @RaghavPrabhakar66 :) If you have any question, I am happy to help. Here or via our community slack
