### ISSUE TITLE
Flow assigns conflicting ports

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3201]
I encountered a problem during benchmarking when running Flows on one machine with a high number of shards (64 in my case).
In that case there are sometimes port conflicts, because the Flow assigns the same port to multiple shards, which does not work on the same machine.
Of course that behaviour would be fine if all of those shards would live on different machines, which should be the case for a real deployment. Thus this issue is unlikely to happen in reality, but is still annoying for testing and the likes.

I would expect the Flow to assign non overlapping ports from its pool of ports as long as it possible (the pool not being exhausted) and only reuses ports if necessary. If deemed necessary one could also try to check where a Pea is running and prevent overlapping ports only where necessary, but that is a more complicated solution.

**Comment by sayantani11** [comment]
@jacobowitz I would like to contribute to the project but since this will be my first, I would require some help. If you could help me how to proceed and give a insight to the task.

**Comment by hanxiao** [comment]
Misconception, we are randomly assigning port. No we do not.

Actually, the port assignment logic has been there since 0.3 or even earlier https://github.com/jina-ai/jina/blob/21a3dfa44b51d700bf94165cb8011eb893637d7a/jina/helper.py#L378 I believe the problem is why the logic there is not enough then?

**Comment by jacobowitz** [comment]
@hanxiao 
I think the problem is that there is no coordination? The more peas we have, the larger is the probability to hit a conflict if said peas run on the same host?

**Comment by jacobowitz** [comment]
@sayantani11 
Thank you for help! Mayeb hold off on this ticket for a couple of days until we can clarify how we actually want the solution to work. I think atm there are a bit too many questions mark.
