### ISSUE TITLE
tutorials disappeared from your website

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/jina#3202]
Tutorials disappeared from your website:

🚶‍ Walkthroughs
How to Build Hello World Chatbot > [(https://jina.ai/2021/06/28/tutorial.html)]
Create Your Own Executor > [https://jina.ai/2021/07/15/tutorial-executors.html]

Refers to readme.md

**Comment by Roshanjossey** [comment]
Hi @tommykoctur, thank you for reporting this. I'll work on fixing this today.

**Comment by tommykoctur** [comment]
Thank you
