### ISSUE TITLE
Install jina via git and not pip

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3247]
In these two we use `pip` to install jina, lets change this to install via `git`

https://github.com/jina-ai/cloud-ops/blob/75e370c2d88874e78ac500ade4f62537d9e2f1ed/scripts/deb-systemd.sh#L24

https://github.com/jina-ai/cloud-ops/blob/f3e55e88c9b496889f830cfb25aaadeec7b55bdb/stress_test_trigger/cloud_ymls/daemon-stress-test-infra.yml#L499

**Comment by JoanFM** [comment]
Closed by https://github.com/jina-ai/cloud-ops/pull/117
