### ISSUE TITLE
Flow.plot() doesn't work

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#3270]
**Describe the bug**
Given the following `index.yml` and `executor.py`, `Flow.load_config('flow.yml').plot()` will generate [an invalid image](https://mermaid.ink/svg/JSV7aW5pdDogeyd0aGVtZSc6ICdiYXNlJywgJ3RoZW1lVmFyaWFibGVzJzogeyAncHJpbWFyeUNvbG9yJzogJyMzMkM4Q0QnLCAnZWRnZUxhYmVsQmFja2dyb3VuZCc6JyNmZmYnLCAnY2x1c3RlckJrZyc6ICcjRkZDQzY2J319fSUlCmdyYXBoIExSCmdhdGV3YXkoImdhdGV3YXkiKTo6OkdBVEVXQVkgLS0+IHBvZDAoInBvZDA8YnI+KHsianR5cGUiOiAiTXlFeGVjdXRvciIsICJtZXRhcyI6IHsicHlfbW9kdWxlcyI6IFsiZXhlY3V0b3IucHkiXX19KSIpOjo6UE9ECnBvZDAoInBvZDA8YnI+KHsianR5cGUiOiAiTXlFeGVjdXRvciIsICJtZXRhcyI6IHsicHlfbW9kdWxlcyI6IFsiZXhlY3V0b3IucHkiXX19KSIpOjo6UE9EIC0tPiBnYXRld2F5X0VORChnYXRld2F5KTo6OkdBVEVXQVkKY2xhc3NEZWYgUE9EIGZpbGw6IzMyQzhDRCxzdHJva2U6IzAwOTk5OQpjbGFzc0RlZiBJTlNQRUNUIGZpbGw6I2ZmNjY2Nixjb2xvcjojZmZmCmNsYXNzRGVmIEpPSU5fSU5TUEVDVCBmaWxsOiNmZjY2NjYsY29sb3I6I2ZmZgpjbGFzc0RlZiBHQVRFV0FZIGZpbGw6IzZFNzI3OCxjb2xvcjojZmZmCmNsYXNzRGVmIElOU1BFQ1RfQVVYX1BBU1MgZmlsbDojZmZmLGNvbG9yOiMwMDAsc3Ryb2tlLWRhc2hhcnJheTogNSA1CmNsYXNzRGVmIHBlYSBmaWxsOiMwMDk5OTksc3Ryb2tlOiMxRTZFNzM=)

```yaml
jtype: Flow
version: '1'
executors:
  - uses:
      jtype: MyExecutor
    py_modules:
      - executor.py
```

```python
from jina import Executor, requests


class MyExecutor(Executor):
    @requests
    def foo(self, docs, **kwargs):
        print('hello')
```

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
wrong YAML syntax, fake issue.

```yaml
executors:
  - uses: BaseExecutor
```
