### ISSUE TITLE
Kubernetes - add unit tests

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3293]
Currently, the Kubernetes feature is just tested via 3 integration tests.
Please add unit tests as well.

Modules that require unit test coverage:
- [ ] https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8slib/kubernetes_deployment.py (https://github.com/jina-ai/jina/pull/3367)
- [x] https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8slib/kubernetes_tools.py (https://github.com/jina-ai/jina/pull/3359)
- [x] https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8s.py (https://github.com/jina-ai/jina/pull/3358)

**Comment by slettner** [comment]
Two PRs missing. Reopening.

**Comment by slettner** [comment]
One PR missing. Reopening.
