### ISSUE TITLE
Kubernetes - more information to the user when starting the flow

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3298]
https://www.notion.so/florian-hoenicke-522cf250dd754a7283adf141a60d5923

**Comment by jacobowitz** [comment]
This breaks now here https://github.com/jina-ai/jina/issues/3431

**Comment by gaocegege** [comment]
I am wondering what port/ip address should we show. As you know the podIP does not work since you cannot access outside.

**Comment by jacobowitz** [comment]
I would still show the podIP and would leave it to the user to make sure its reachable. If you run a Pod in any other private context, the same would happen.

**Comment by gaocegege** [comment]
SGTM.

**Comment by JoanFM** [comment]
@florian-hoenicke is this still valid? Can u describe it better?
