### ISSUE TITLE
Kubernetes - parameterize template files

### ISSUE THREAD

**Issue by slettner** [jina-ai/jina#3328]
With https://github.com/jina-ai/jina/issues/3291, we introduce having custom templates.
As a user, it is not possible to also pass values to the templates via the Jina Flow API.

I.e. the values need to be in the file directly which leads to 
- duplicating template files for different pods (if they need different values)
- potential inconsistency between those duplicates that can lead to errors. E.g. varying namespace names.

**Code Snippets**

Current API
````python
flow = Flow(name='test-flow', infrastructure='K8S')
    .add(name='test_executor', k8s_custom_resource_dir='some/path')  
````

Requested API (suggestion)
````python
flow = Flow(name='test-flow', infrastructure='K8S')
    .add(name='test_executor', k8s_custom_resource_dir='some/path', additional_deployment_args={'cpu_limit': '1'})  
````
The `additional_deployment_args` should then be passed to the template file before the resource is created in the cluster.

**Comment by slettner** [comment]
WIP Branch: https://github.com/jina-ai/jina/tree/feat-k8s-yml-templates

**Comment by JoanFM** [comment]
Hello @slettner ,

Is this still work in progress? @florian-hoenicke is this something we want to work on?

**Comment by florian-hoenicke** [comment]
At the moment there are more important things to work on. Let's reopen this once we see the demand.

**Comment by JoanFM** [comment]
Closing until demand arises
