### ISSUE TITLE
Add  `get_docs_batch_generator` for DocumentArray

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3333]
This is probably the most used function from jina commons. I think it would make sense to add it to jina - maybe not as a DocumentArray method, but as a util somewhere. Would enable us to eliminate jina commons requirement from a lot of executors

**Comment by sauravgarg540** [comment]
I would like to work on this issue.

**Comment by agarwalrounak** [comment]
Hey @sauravgarg540, I am already working on this issue and have made some progress. I guess I should have commented here to get it assigned to me. Sorry for not doing that. Is it okay with you if I go ahead?

**Comment by sauravgarg540** [comment]
Hey @agarwalrounak,  It is always good to comment on the issue first and wait till it is assigned to you. This also prevents such conflicts.

**Comment by tadejsv** [comment]
@agarwalrounak if you are working on it, please open a draft PR with your progress so far.

**Comment by agarwalrounak** [comment]
@tadejsv Sure, I will do so.

**Comment by agarwalrounak** [comment]
Hi @tadejsv, I have opened a PR #3386 for this purpose. Looking forward to your review.
