### ISSUE TITLE
Kubernetes -  Flow usage as seemless as native Flow

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#3334]
When creating a K8s Flow, I would like to use it as a native Flow:
```

flow = Flow(
    name='test-flow',
    port_expose=8080,
    infrastructure='K8S',
).add(...)

flow.start()

flow.post(
    on='/index',
    inputs=[Document(text=str(i), embedding=np.random(128)) for i in range(100)],
    show_progress=True,
)
```

For this we need several sub-tasks:

- [ ] automatic port-forwarding when the gateway is deployed and ready
- [x] Use K8sPod as context manager, implement proper `wait_start_success` and `close` logic
- [x] Add readinessProbe through control Request

**Comment by jacobowitz** [comment]
I think the port forwarding is questionable? That is a debug mechanism you should use while developing and not for production so I would not do that automatically from code? The rest is fine, especially the readyness check we need

**Comment by 7yaqivo** [comment]
Too bad

**Comment by maximilianwerk** [comment]
Hmm I see. Would you be fine with an argument `automatic_port_forwarding` which defaults to `False`?

**Comment by jacobowitz** [comment]
That would be an option, but for me that does not really belong in our code base conceptually speaking (not even sure its possible).
Port forwarding is some hack you do on our computer (like a SSH tunnel) to reach a remote entity in K8s. I think that hack should be up to the user and not be built into our application.

**Comment by jacobowitz** [comment]
but I think what we actually should do is: Enable the user to change the service type for the gateway to LoadBalancer
This would be needed for a production deployment without portforwarding

**Comment by hanxiao** [comment]
I prefer the consistent `with` context manager experience as we taught people in docs, so this feature (which I guess is only about a proper deconstructor) needs to be implemented.

https://github.com/jina-ai/jina/pull/3357#discussion_r703318054

**Comment by jacobowitz** [comment]
the destructor we need as well, agreed.

But I think we should at least also look into the readiness checks in kubernetes and if they are actually doing anything meaningful atm. Although these are two completely different things so lets split them  into two tickets?

**Comment by JoanFM** [comment]
Readiness checks maybe can be done by us by using `Control port` to check for `status`

**Comment by gaocegege** [comment]
> Readiness checks maybe can be done by us by using `Control port` to check for `status`

I am wondering if we could use Kubernetes built-in readiness probe?

**Comment by JoanFM** [comment]
> > Readiness checks maybe can be done by us by using `Control port` to check for `status`
> 
> I am wondering if we could use Kubernetes built-in readiness probe?

Actually, the readiness probe of Kubernetes should be changed by default to check the status endpoint
 the point here is if jina local to the user would have access to this information

**Comment by JoanFM** [comment]
To clarify the scope. No need to use http for readiness. Readinesa should be checked by hitting the control port of the Runtime. Liveness will be equivalent but if a problem or bottleneck is encounteres we will find a solution
