### ISSUE TITLE
fluent - Failed to get the environment variables in fluent.conf

### ISSUE THREAD

**Issue by gaocegege** [jina-ai/jina#3378]
https://www.notion.so/gaocegege-156e5e92d82841bd9881dc3d1d0faed6

**Comment by gaocegege** [comment]
/cc @hanxiao 

Seems that the change is imported here https://github.com/jina-ai/jina/commit/889f11370cad698a7cce10f7f8362477f1947edf#diff-bee2b3da7b63620c370591585e6727eed9824407d277d006cd473c859c140fb5R17

**Comment by gaocegege** [comment]
I think it can be one of the good-first-issues

**Comment by CatStark** [comment]
Hi @gaocegege thanks for looking into this. I just labeled it as `good first issue`

**Comment by RaghavPrabhakar66** [comment]
Hi, I would like to this issue. Any steps on how to reproduce the bug.

**Comment by gaocegege** [comment]
Just run

```
docker run --pull always --add-host host.docker.internal:host-gateway \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /tmp/jinad:/tmp/jinad \
           -p 8000:8000 \
           --name jinad \
           -ti --entrypoint bash jinaai/jina:master-daemon
```

**Comment by rajathpatel23** [comment]
Hi All, anybody working on this issue, if not I would like to work on this one

**Comment by JoanFM** [comment]
Hello @rajathpatel23,

There is nobody working on this issue. You are more than welcome to work on this. It would also be great if @gaocegege could also review the work and u can keep him in the loop.

**Comment by gaocegege** [comment]
Please @gaocegege when the PR is ready to review.

**Comment by rajathpatel23** [comment]
Thank you @JoanFM , I will work on this one and send in for review once done

**Comment by CatStark** [comment]
Hi @rajathpatel23 , so cool you want to contribute with us :D is there anything we can help you to get started?

**Comment by rajathpatel23** [comment]
Hi @CatStark , I am working on this issue. I tried creating a branch, pushing it to the repo here, however I have not been able to push it fully. I am new to open source contribution and hence would like to request help

**Comment by rajathpatel23** [comment]
Hi @CatStark , I have opened an MR for this issue. however, I was not able to reproduce the issue that is seen here, however I tried checking the syntax for `fluent.conf` files, and it seems we needed to parse `workspace` as `log_id` as environment variables
