### ISSUE TITLE
Cannot Run chatbot and multimodal

### ISSUE THREAD

**Issue by Vibha111094** [jina-ai/jina#3389]
Hi,
I was trying to run the demo for chatbot and multimodal but I get the error that port 8080 is already in use. I am trying this on colab.

Environment
jina 2.0.23
![](https://user-images.githubusercontent.com/16645902/132943675-08e7670d-68a5-4dd1-bfb7-4d77bb432a4c.png)

**Comment by agarwalrounak** [comment]
Hi @Vibha111094! The error usually means that the 8080 port is already in use by some other process in your environment. You could kill the existing process if it is not useful.

**Comment by CatStark** [comment]
Hi @Vibha111094 , was this solved with @agarwalrounak comment?

**Comment by Vibha111094** [comment]
As I was running in colab.. I was not really able to do it. Its a
limitation I guess...

**Comment by JoanFM** [comment]
Hello @Vibha111094 ,

Was the issue solved? Did u manage to run the examples?
