### ISSUE TITLE
Pass arguments to `jina hub new`

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3393]
Right now when using `jina hub new` the only option is to do everything interactively. It would be great if some commands could be passed as options, to CLI, for example `--name=MyExecutor`

**Comment by sauravgarg540** [comment]
Hey @tadejsv, I would like to work on this issue.

**Comment by CatStark** [comment]
Hi @sauravgarg540 feel free to open a PR you would like to help
