### ISSUE TITLE
Kubernetes - Support NodePort service

### ISSUE THREAD

**Issue by gaocegege** [jina-ai/jina#3419]
Describe the feature

Now Jina requires a port-forward to expose the clusterIP service port to the host.

It's trivial. If we need to expose it manually, should we consider using the NodePort service? At least it should be configurable.

BTW, I think we could introduce a CRD to manage Jina pods instead of managing them in Jina core manually. Personally, I do not think it is necessary and cloud-native. We just run Jina on top of Kubernetes, not build Jina with Kubernetes.

**Comment by jacobowitz** [comment]
Sounds reasonable, although the node running the gateway pod needs to have a public IP and appropriate firewall rules set up then.
I think besides NodePort service we should also support LoadBalancer, which can also be useful in other cases.
Generally its already possible to provide custom templates for the service/deployment defintions via the `--k8s-custom-resource-dir` parameter. But we also need to have separate templates for gateway and regular pods, not sure that is easily doable atm? @florian-hoenicke will know more.

Besides custom templates, both NodePort and LoadBalancer services should be possible to configure more conveniently for the gateway.

**Comment by gaocegege** [comment]
> I think besides NodePort service we should also support LoadBalancer, which can also be useful in other cases.


SGTM

**Comment by JoanFM** [comment]
This requirement is updated with the new approach
