### ISSUE TITLE
Reduce the amount of log messages displayed in hello-world example

### ISSUE THREAD

**Issue by HungUnicorn** [jina-ai/jina#342]
**Describe the feature**
As a user who wants to try it out at the first time, I would like to see less log messages when running the hello-word example  (https://github.com/jina-ai/jina#jina-hello-world-). It currently displays a lot of log messages that wouldn't interest hello-world user.

```
...

BiMatchRanker@128[I]:post initiating, this may take some time...
  BiMatchRanker@128[I]:post initiating, this may take some time takes 0.001 secs
  BiMatchRanker@128[S]:successfully built BiMatchRanker from a yaml config
         ranker@128[I]:setting up sockets...
         ranker@128[I]:input tcp://0.0.0.0:34349 (PULL_BIND) 	 output tcp://0.0.0.0:59429 (PUSH_CONNECT)	 control over tcp://0.0.0.0:59483 (PAIR_BIND)
         ranker@128[S]:ready and listening
   DocPbIndexer@131[I]:post initiating, this may take some time...
   DocPbIndexer@131[I]:post initiating, this may take some time takes 0.000 secs
   DocPbIndexer@131[S]:restore DocPbIndexer from /j/doc_indexer.bin
        doc_idx@131[I]:setting up sockets...

....
```

**Describe your proposal**
Probably set a more suitable log level for the hello-world example

**Comment by policeme** [comment]
note, jina logging level follow python logging level, if you want to reduce the logging message. 
just set the `os.environ('JINA_LOG_VERBOSITY')='ERROR'` or `os.environ('JINA_LOG_VERBOSITY')='CRITICAL'`.

**Comment by hanxiao** [comment]
@HungUnicorn thanks for the feedback! will consider reduce the log intensity for hello-world

**Comment by hanxiao** [comment]
We decide not to proceed on this issue. The main reason is that the [dashboard](https://github.com/jina-ai/dashboard) already provides the functionalities of grouping and prettify the logs. The user can simply run `jina hello-world --logserver` and view much cleaner and structured logs in the dashboard.
