### ISSUE TITLE
Kubernetes - Support graceful deletion 

### ISSUE THREAD

**Issue by gaocegege** [jina-ai/jina#3420]
**Describe the feature**

It is hard to delete the flow now. Users have to delete the namespace directly to delete all resources.

**Comment by jacobowitz** [comment]
@gaocegege thx for reporting this issue :) I completely agree that this is a needed feature. Han also mentioned it here in the past https://github.com/jina-ai/jina/issues/3334#issuecomment-915853961

I will add it to our roadmap. I am a bit busy the next days unfortunately, but maybe somebody else can pick it up. If nobody does it, I will when I am available again.

Fyi @florian-hoenicke

**Comment by florian-hoenicke** [comment]
Thanks for raising the issue. It will be handled in this ticket:
https://github.com/jina-ai/jina/issues/3334
