### ISSUE TITLE
Kubernetes - Wait ready fails

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3431]
[This change](https://github.com/jina-ai/jina/pull/3410/files) changed the readiness check for Pods done by the Flow. 

It also removed this check:

`if self.args.infrastructure == InfrastructureType.K8S:
    self.logger.info('🎉 Kubernetes deployment done!')
 else:`

Now we always try to print the Flow info table with host/port information. For a K8s pod this is [not implemented](https://github.com/jina-ai/jina/blob/master/jina/peapods/pods/k8s.py#L69) though.

Creating any K8s Flow like this one `Flow(name='flow', infrastructure='K8S')` now leads to this output

```
 deploy_gateway@157752[I]:🔋	Create Service for "gateway" with image "gateway" pulling from "jinaai/jina:master-py38-standard"
 deploy_gateway@157752[I]:🐳	Create Deployment for "jinaai/jina:master-py38-standard" with replicas 1 and init_container False
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tobias/code/jina_fresh/jina/flow/base.py", line 1485, in _get_address_table
    + colored(f'{self.host}:{self.port_expose}', 'cyan', attrs='underline'),
  File "/home/tobias/code/jina_fresh/jina/flow/base.py", line 1439, in host
    return self._pod_nodes[GATEWAY_NAME].host
  File "/home/tobias/code/jina_fresh/jina/peapods/pods/k8s.py", line 69, in host
    raise NotImplementedError
NotImplementedError
          flow8@157752[I]:🎉 Kubernetes Flow is ready to use!
```

I am also surprised that the Flow actually seems to start and is not aborted due to the error.

**Comment by JoanFM** [comment]
This problem is only a matter of plotting, This should be easily fixed

**Comment by jacobowitz** [comment]
Related to https://github.com/jina-ai/jina/issues/3452

**Comment by JoanFM** [comment]
The reason why `is_ready` fails silently is because `wait_ready` runs in a separate thread and seems that exceptions are not captures there
