### ISSUE TITLE
We should rename it to rolling restart.

### ISSUE THREAD

**Issue by maximilianwerk** [jina-ai/jina#3442]
https://www.notion.so/maximilianwerk-91ee42b20606466ebc59e7cb228d30fc

**Comment by Aditya-Jha2002** [comment]
Hey everyone, I would like to take up this issue. Can I get assigned to this?

**Comment by CatStark** [comment]
HI @Aditya-Jha2002 you can take it if you want, can you link the PR you make to this issue please?

**Comment by JoanFM** [comment]
When changed, make sure backward compatibility is mantained

**Comment by JoanFM** [comment]
I am  not sure rolling restart is a good name, since u can run it with a different set of arguments
