### ISSUE TITLE
Kubernetes - publish gateway

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#3446]
make the gateway public,
introduce a parameter to prevent gateway from being exposed
print out public IP when starting the flow

**Comment by jacobowitz** [comment]
This is related to https://github.com/jina-ai/jina/issues/3419

**Comment by jacobowitz** [comment]
please reflect changes done here in this issue as well https://github.com/jina-ai/jina/issues/3334

**Comment by JoanFM** [comment]
I think this is not valid anymore
