### ISSUE TITLE
docs: clean-up section on workspace

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#3462]
https://www.notion.so/cristianmtr-ea23d3d8bf204040bfee4c730c78eb4a

**Comment by cristianmtr** [comment]
Not sure what this task is. The URL in the notion doesn't exist.

**Comment by cristianmtr** [comment]
@CatStark Do you know, by any chance?

**Comment by CatStark** [comment]
It was solved, good that you closed it.
