### ISSUE TITLE
Verify terminate behavior of runtimes

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3508]
We want all runtimes (ZEDRuntime and GrpcDataruntime) to finish processing data requests before terminating. So if a runtime receives a terminate signal, it should stop accepting new requests and finish all pending requests. This way we lose no messages. Of course there needs to be some timeout we wait for this pending messages to be procssed.

We believe this should already be implemented, but want to double check this and add integration tests if they dont exist yet.

**Comment by JoanFM** [comment]
Validate against regular terminate signals and against SIGKILL and SIGTERM signals sent by OS as this should be a great proxy for what K8s actually does

**Comment by CatStark** [comment]
Closed by 3598
