### ISSUE TITLE
Scores with value 0 are not printed

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/jina#3520]
https://www.notion.so/tadejsv-c7a98ea294804ebfa7c6594c78005dac

**Comment by JoanFM** [comment]
I believe we had a discussion about wether or not add this option in the dict,

`including_default_value_fields`, that would fix this, but it may have some affection over our API.

@hanxiao do u recall such a discussion?

**Comment by JoanFM** [comment]
To be moved to docarray if still applies
