### ISSUE TITLE
Kubernetes dependency not installed in Executor images

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3536]
Since 2.1.5 jina is broken in K8s, because the kubernetes dependency is missing from all executor images.
This is because kubernetes is only part of `standard` and not part of `core`. 

We either need to install `standard` in hubble or add kubernetes to `core`.

**Comment by JoanFM** [comment]
I do believe most of our `Executors` use `standard`

**Comment by tadejsv** [comment]
@JoanFM no, they all use `perf`

**Comment by JoanFM** [comment]
and perf does not use standard?

**Comment by tadejsv** [comment]
No, it goes like this: `core < perf < standard`

**Comment by JoanFM** [comment]
We can add then to perf, but @mapleeit this is an example of what was discussed the other day
