### ISSUE TITLE
UserWarning: ignored unknown argument: ['2'].  when adding `prefetch` to `Flow`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#3538]
https://www.notion.so/JoanFM-91cf68a5b1d04f00a33ba0f6e3de7ee7

**Comment by gauthamsuresh09** [comment]
Hi @JoanFM, I would like to work on this issue

**Comment by JoanFM** [comment]
> Hi @JoanFM, I would like to work on this issue

Hey @gauthamsuresh09 , It would be great if u can help here. I will assign to you the issue and u can link to this when you open the PR.

Thank you very much!

**Comment by gauthamsuresh09** [comment]
Sure, thanks @JoanFM
