### ISSUE TITLE
add cache for speeding up querying

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#356]
**Describe the feature**
add cache for speeding up querying

**Your proposal**
cache for pods, peas, and, shades

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
caching in this architecture is non-trivial, and if badly designed bring more chaos than benefits. 

Until we have clear pattern observed in real-world scenario which can be cached and which not, I suggest we do not move on this issue.

**Comment by zjbit** [comment]
i found the example of jina save the index file on local disk, if i wang to speed up the query, for example, storing the index in memory cache with facebook faiss, can this be work with jina?

**Comment by hanxiao** [comment]
> i found the example of jina save the index file on local disk, if i wang to speed up the query, for example, storing the index in memory cache with facebook faiss, can this be work with jina?

You have a misunderstanding about in-memory index, and is not relevant to this cache issue. We are not doing on-disk search.

A typical search system we have two modes: index and search, now think about this:

- In the *index mode*, you store a lot of things. If you put all of them in memory, it will explode. But most importantly, it is *meaningless*. You never do any query in the **index mode**.
- In the *query model*, Jina loads index from local shards into **memory** and run parallel search. It is the design from the very beginning.

I'm pretty sure later if you look at Jina code, you will understand why do we implement it like this.
