### ISSUE TITLE
introduce the concept of `field` to support multimodal search

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#357]
**Describe the feature**
In the case of multi-modal search, one needs have chunks for both images and texts. We need one way to tell from which type of chunks the query should be made. Currently, we can use the `meta_info` field to do this, however, `meta_info` can be used to do various jobs. Plus, I consider this use case as a very common usage for jina. 

**Your proposal**
add the `description` field in the chunks' definition so that one can differentiate various types of chunks.

---

**Environment**

**Screenshots**

**Comment by kbarresi** [comment]
I think this is really important to have - I can imagine a lot of use cases would have "documents" that need to be indexed with a structure to them, e.g.:

```json
{
  "id": 12345,
  "name": "Title of My Document",
  "summary": "This is the content of my document. I would want to search on this, and the title."
}
```

You might want to search the `name` or `summary` field, or even both (e.g. perform ranking with a 25% boost on similarity to the `name` field), and then return the full document (including the `id`) or parts of it.

I think something similar to the way ElasticSearch does it would be perfect; a single document with multiple fields that can be indexed and searched upon in different ways.

**Comment by hanxiao** [comment]
This one needs a carefully design as it involves multiple modalities. Perhaps a [JEP](https://docs.jina.ai/chapters/jep/main.html) to write down the thoughts first

**Comment by hanxiao** [comment]
we should refer to MIME/Multipart types, which indicate a category of document broken into pieces, often with different MIME types; they can also be used — especially in email scenarios — to represent multiple, separate files which are all part of the same transaction. They represent a composite document.

**Comment by canetcesc** [comment]
Regardless of the multi-modal scenario, @kbarresi ’s suggestion of indexing json multi-field, structured documents (text only) with the possibility of boosting specific fields would be useful in the project that I am working on. Is this captured by any JEP? #466 does not seem to include boosting in it and I’m not entirely sure if it solves the problem of multi-field documents (I haven’t seen an actual example).

**Comment by canetcesc** [comment]
Oh sorry, I just found the JEP document here: https://github.com/jina-ai/jina/blob/5a54bb8674bbed45156fa08b3c11d255a0202b93/docs/chapters/jep/jep-3/index.rst

That is great, the only thing that I am missing is:

- Ability to boost certain fields. Eg: Title is more important than Summary when searching for “painter”, but you don’t completely drop the dSummary, you just score matches as less relevant than on title.

- Ability to search on multiple fields simultaneously. Eg: give me all the “painter” books written between 2015 and 2020 where genre is one of “arts”, “crafts”, and/or “hobbies”.

**Comment by lusloher** [comment]
JIRAC-5
