### ISSUE TITLE
windows10/py3.8 error in jina demo

### ISSUE THREAD

**Issue by shixinglingguihua** [jina-ai/jina#3584]
**Describe the bug**

** here is min bug
envs:
sys: window10
python: python==3.8 installed from anaconda
jina: jina version is 2.1.5 <= pip install -u jina& pip install "jina[demo]"

while run 【jina hello fashion】 in cmd, screen print some errors after the python thread download fashion-mnist data：
【⠹ 0/4 waiting executor0 executor1 executor2 gateway to be ready... gateway@5736[E]:NotImplementedError() during <class 'jina.peapods.runtimes.gateway.grpc.GRPCRuntime'> initialization
add "--quiet-error" to suppress the exception details】
**

**Comment by JoanFM** [comment]
Hey @shixinglingguihua, thanks for reporting the bug. Isn't there more information in the stacktrace that can help us to find the root of the problem?

**Comment by JoanFM** [comment]
https://github.com/tornadoweb/tornado/issues/2608

**Comment by deepankarm** [comment]
@shixinglingguihua  @TITC we implemented a fix in #3679. Can you guys retry the demo in your python 3.8 environment? Please update jina to the latest development version using `pip install -U --pre jina`.

**Comment by JoanFM** [comment]
Can u check the solution proposed here?

https://github.com/xlwings/xlwings/issues/1315
