### ISSUE TITLE
log management

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#359]
**Describe the feature**
Test jina with the log management packages so that we ensure logs in production won't blow up the disk.

**Your proposal**
Test jina with the log management packages so that we ensure logs in production won't blow up the disk.

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
why is this needed? our logger by default is not output to disk anyway

**Comment by hanxiao** [comment]
note that we also need to consider the dashboard API when refactoring/adding functions to the logger
