### ISSUE TITLE
Error from installed（in docker）

### ISSUE THREAD

**Issue by AllenZYJ** [jina-ai/jina#361]
when i install jina by pip in docker （centos+python3.7）

 root@eaf9d4cc6f1b>>pip install jina
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting jina
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/4a/c4/42f66dc01c461915eed36eeeeb13b2e3fe8534d001d6088502bcec9347ea/jina-0.1.2.tar.gz (134 kB)
     |████████████████████████████████| 134 kB 16.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i48yq978/jina/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i48yq978/jina/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-795u73ch
         cwd: /tmp/pip-install-i48yq978/jina/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-i48yq978/jina/setup.py", line 17, in <module>
        raise OSError('Jina requires Python 3.7 and above, but yours is %s' % sys.version_info)
    TypeError: not all arguments converted during string formatting
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

maybe cause by python-version？python3.7

**Comment by hanxiao** [comment]
you python maybe 3.7 but your pip is for python 2
try `pip3 install jina` then
