### ISSUE TITLE
investigate flaky tests `daemon` `distributed`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#3610]
**Problem description**
These tests have been failing very often and with no apparent reason, plus not reproducible in local:

`tests/distributed/test_topologies*`

**Comment by JoanFM** [comment]
```
FAILED tests/distributed/test_topologies/test_topologies.py::test_r_l_r_simple[2]
FAILED tests/distributed/test_topologies/test_topologies.py::test_r_r_r_simple[2]
```

**Comment by jacobowitz** [comment]
I've added a debug PR for ci: https://github.com/jina-ai/jina/pull/3622/checks?check_run_id=3846544273
