### ISSUE TITLE
Write a blog on - "what is neural search and how does Jina use neural search?"

### ISSUE THREAD

**Issue by joeyouss** [jina-ai/jina#3642]
Jina uses the idea of neural search. But how does it do this? . If you are a beginner, we recommend the video - https://www.youtube.com/watch?v=Ex6vYQoTbdE&t=94s to learn about neural search and Jina.
As a contributor , you need to write a blog on the topic explaining your understanding of neural search and Jina.

How do I make a contribution to this issue?
Publish your blog on a blogging website - medium/hashnode/ any good blogging website and comment the link here and we will review it !

**Comment by Priyanshi-Sharma-142** [comment]
https://medium.com/@priyanshi142/neural-search-using-jina-2c17e7a9a482
My blog.

**Comment by anshika361** [comment]
I have written my blog can u check it

https://jinaai.blogspot.com/2021/10/getting-started-with-jina-ai-neural.html

**Comment by joeyouss** [comment]
Hi @anshika361 @Priyanshi-Sharma-142  , the blogs look great. 
If or not they qualify for Advocate swags will be told by @alexcg1 
Meanwhile here :
The swag form - https://jina.ai/blog/swag/
