### ISSUE TITLE
Write a blog on - "Jina and open source - what actually Jina is"

### ISSUE THREAD

**Issue by joeyouss** [jina-ai/jina#3643]
New to Jina? Looking for learning about Jina? Why not share your journey with others !!
Any beginner can get started here - https://github.com/jina-ai/jina and read our documentation on - https://docs.jina.ai 

Run our examples - https://github.com/jina-ai/jina#run-quick-demo which will help you understand how it all works !

Next, document your journey in a blog and write down your understanding of what Jina is .

Publish the blog on a blogging website - medium/hashnode etc. and comment here the link to your blog.

Comment on this issue to get assigned !

**Comment by codeswithroh** [comment]
I am interested

**Comment by joeyouss** [comment]
hey @codeswithroh this looks great !!, do you need an image for blog?

**Comment by SachinRaghuvanshi2003** [comment]
Hey! I'm interested.
