### ISSUE TITLE
Build using Jina : Shazam using Jina - enter an audio and search which song is it !

### ISSUE THREAD

**Issue by joeyouss** [jina-ai/jina#3650]
At Jina, we build crazy fun things using Jina and one such example is the[ meme search. ](https://examples.jina.ai/memes/)
Meme search allows you to upload a meme of your choice and renders many similar memes to your meme !. 

If you are interested in getting your hands on coding with Jina and creating something, this is the issue for you. 

**Idea:**
Create a search hinge for songs using Jina 

**What It does?**
Upload an audio and check which song is it !!

**What is the tech stack?**
- Jina for backend
- Streamlit for frontend (or any other front end framework you prefer)
- Dataset ? - feel free to use any !

To help you get started , we have a list of simple examples created using Jina here - https://github.com/alexcg1/simple-jina-examples

**How do I get started if I am a beginner?**
- Read Jina's GitHub repo
- Run our examples to get a better understanding - https://github.com/jina-ai/jina#run-quick-demo
- Go through the docs, they have everything you need!

**I am stuck, I need help !!**
We hear you, drop into our [discord channel](https://discord.gg/Dbn3ESC5n2) and post your queries there , introduce yourself and get to meet some amazing people building Jina and contributing to Jina !

**What if you have no idea what Jina is or neural search is?**
Try - https://www.youtube.com/watch?v=Ex6vYQoTbdE , we created a video explaining everything about what is neural search and Jina !

**Do I get Swags?**
We love appreciating good work in open source and every project you create/every contribution you make will be rewarded with some amazing swags. Find out more at - https://jina.ai/blog/swag/

**Comment by arya312** [comment]
I found this project very intriguing, I would love to work on it :P
