### ISSUE TITLE
Blogs for Jina - have an idea ? share it, write it !

### ISSUE THREAD

**Issue by joeyouss** [jina-ai/jina#3656]
We at Jina are fans of the written word. And , if you are a beginner in neural search and OSS, what better than starting out with documentation and blogs ?
How to make a contribution?

Comment below this issue the topic you have in mind for writing a blog. The topic should revolve around - neural search/Jina/Jina-OSS etc. (basically about Jina)

What can it be about? It could be a tutorial or about your contribution to Jina or anything ! (let's get creative)

After your topic is approved, we create an issue for you and allow you to make a PR for the same.!

PS- there is no limit on the number of people this issue can get assigned to hence feel free to comment more than one idea !

**Comment by joeyouss** [comment]
hey @Parth00010 , thanks for the efforts but jinabox is not in use currently.

**Comment by Parth00010** [comment]
Ohh..should i delete it from the post?

**Comment by joeyouss** [comment]
yes ! also, I suggest researching a bit more about Jina

**Comment by codeswithroh** [comment]
@joeyouss Did you check my blog? And when will I receive the label?

**Comment by codeswithroh** [comment]
Yeah, I raised few issues while running the examples and they got solved by the `Jina` community as well. I can write another blog about the issues that I raised.

**Comment by joeyouss** [comment]
I would suggest including them in the same blog
