### ISSUE TITLE
The server is not getting started while following the Fuzzy grep example from the docs

### ISSUE THREAD

**Issue by codeswithroh** [jina-ai/jina#3662]
While following [this](https://docs.jina.ai/tutorials/fuzzy-grep/#fuzzy-grep-in-30-lines) from the docs, I noticed that the server is not getting started.

After running this piece of code
```
from jina import Document

with f:
    f.post('/index', (Document(text=t.strip()) for t in open(__file__) if t.strip()))  # index all lines of _this_ file
    f.block()  # block for listening request
```
The output is stuck at this for over `30 mins`
```
 0/3 waiting executor0 executor1 gateway to be ready...        gateway@9557[W]:CORS is enabled. This service is now accessible from any website!
           Flow@6635[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		HTTP
	🏠 Local access:	0.0.0.0:12345
	🔒 Private network:	192.168.43.168:12345
	💬 Swagger UI:		http://localhost:12345/docs
	📚 Redoc:		http://localhost:12345/redoc
```
The basic `searching` method is working from the `Swagger UI`  that opens at `localhost:12345` but since, the server is not completing, I am not able to `create any client` with this
```
from jina import Client, Document
from jina.types.request import Response

def print_matches(resp: Response):
    for idx, d in enumerate(resp.docs[0].matches[:3]):
        print(f'[{idx}][{d.scores["euclidian"].value:2f}:"{d.text}"')

c= Client(protocol="http", port= 12345)
c.post('/search', Document(text='Document(id=something)'), on_done= print_matches)
```
After running the above code, it shows pending since, the server is not being completed.

- Steps to reproduce the error:
    - Try the pieces of code from [this](https://docs.jina.ai/tutorials/fuzzy-grep/#fuzzy-grep-in-30-lines)
    - After running [this](https://docs.jina.ai/tutorials/fuzzy-grep/#query-from-python) you will be able to see the problem mentioned above.

**Comment by JoanFM** [comment]
Also u can try to run the example by installing Jina from the version on this PR #3670 . It should get more info on the observed error
