### ISSUE TITLE
peas_hosts parameter not working correctly

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3665]
The argument `peas_hosts` is currently not working correctly, at least in some cases (local Flow, multiple peas_hosts).

E.g. this Flow won't work `f = (Flow()
     .add(name='distributed_replicas', replicas=2, peas_hosts=['10.0.0.1', '10.0.0.2']))`

There are multiple problems with this, the biggest conceptual problem is that remote peas cant connect back to a local head/tail. 
We should probably wait for star routing to fix this as a side effect.

discovered while working on this https://github.com/jina-ai/jina/pull/3630

**Comment by JoanFM** [comment]
We will remove `peas-hosts`
