### ISSUE TITLE
send_message interface of grpclet should be sync

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3735]
The `send_message()` interface in the Grpclet is async at the moment and the GrpcDataRuntime uses this to create tasks for the calls. This is a bit weird because all the asyncio functionality is actually capsulated by the Grpclet (it creates and manages asyncio task) and there is no need to expose this.

So we should make the send_message interface sync and all of their uses. At the moment this is quite a bit of work because we also have to unify it with the zmqlet and some test mocks. This includes also uses in ZEDRuntime and the Gateway runtimes.

We should wait with this one until star routing is done so that we have to change less.

**Comment by CatStark** [comment]
Closed because of Star Routing
