### ISSUE TITLE
GPU running in parallel

### ISSUE THREAD

**Issue by bwanglzu** [jina-ai/jina#3746]
As a developer of the executor, I would like to have each parallel running on different GPU otherwise the PaddlePaddle will start N processes on each GPU. N is the number of parallels.

- [ ] reproduce multiple gpus resource error
- [ ] multiple gpus in parallel, each pea should have 1 gpu, num_parallel could > num_gpus.
- [ ] (optional) need investigate why gpu is not fully used.

**Comment by CatStark** [comment]
Closing because this will be solved on executor level.
