### ISSUE TITLE
Trying out jina-helloworld but not running result as expected！

### ISSUE THREAD

**Issue by BingHo1013** [jina-ai/jina#375]
**Describe your problem**
When installing Jina -Hello world, after it runs for a while, the pop up of search result was not showing as expected. It seems some dependency packages installation was required even when trying the demo. 

**What is your guess?**
Hello-world needs dependency installation of pip install lz4, which shall be packed in jina-hello world when installing. This may help run the demo smoother and not popping up issues when newbies try.

**Environment**
jina                          0.1.6
jina-proto                    0.0.20
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.18.4
protobuf                      3.11.3
proto-backend                 cpp
grpcio                        1.28.1
ruamel.yaml                   0.16.10
python                        3.8.2
platform                      Darwin
platform-release              19.4.0
platform-version              Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
architecture                  x86_64
processor                     i386
jina-resources                /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)

**Screenshots**
![image](https://user-images.githubusercontent.com/61045304/80972398-a7aecc80-8e50-11ea-82a8-002ba81d4a42.png)
![image](https://user-images.githubusercontent.com/61045304/80972332-906fdf00-8e50-11ea-8886-181e5bf2ff2e.png)

**Comment by hanxiao** [comment]
The recent update on Saturday breaks `latest`, you can try the following for now

```bash
docker run -v "$(pwd)/j:/j" jinaai/jina:devel hello-world --workdir /j && open j/hello-world.html  # replace "open" with "xdg-open" on Linux
```

**Comment by hanxiao** [comment]
aha, okay i thought 0.1.7 was published after I solved the dependencies issue, but it was actually published before that

![image](https://user-images.githubusercontent.com/2041322/80975577-8f27bd80-8e22-11ea-9374-01b04a8ebf8c.png)

**Comment by hanxiao** [comment]
solved by bumping version. You can now update jina docker image via `docker pull jinaai/jina` and then do 
```bash
docker run -v "$(pwd)/j:/j" jinaai/jina:devel hello-world --workdir /j && open j/hello-world.html  # replace "open" with "xdg-open" on Linux
```
