### ISSUE TITLE
Improve request handling on runtime termination

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3777]
As shown [here](https://github.com/jina-ai/jina/pull/3736) we dont handle requests between Pods gracefully during termination.
This is especially undesirable in a K8s setting where Pods can come and go.
The problem is that we send messages in a 'fire and forget' style (create asyncio tasks in the background) along the Flow and it is hard to figure out which message failed, when and where. Essentially this means that we are losing some messages between Jina Pods when a K8s Pod is killed/restarted etc.

In PR #3736 there are also tests showcasing this. Those tests are failing and are disabled but should not be.
After star routing this behaviour should be changed, as it is easier to spot errors (as the rpc should always come back with a meaningful result).

So the scope of this issue is:
* Enable the disabled tests and make sure no messages are lost during Pod recreation
* Make sure the same holds true when a container dies in K8s (and not the pod)

**Comment by jacobowitz** [comment]
This is still an issue

**Comment by CatStark** [comment]
Is this still an issue? @JoanFM @jacobowitz It's been here for sometime, should we discuss it soon?
