### ISSUE TITLE
DocumentArrayMemmap grows when matched against while traversing on chunks

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#3809]
The problem is that DocumentArrayMemmap keeps a buffer of Docs in memory that try to keep track of wether a document is updated or not. By default, when chunks and matches are accessed from a Doc, they are flagged for update (their version is updated). Therefore the DAM will try to update them and append them to the end of the body file.

This means that every match call doubles the size of DAM when the right hand size is traversed on matches or chunks.

On the other hand, there is some problem that may have the same root where the underlying DocumentArrayMemmap seems to be corrupted when stored to disk.

I think this is a design problem, and DocumentArrayMemmap should only be used for writing to and not for updating or anything. This would also imply that `match` cannot be used with DocumentArrayMemmap on the left hand side. This would not be a big problem because Executors process docs in requests via DocumentArray

**Comment by nan-wang** [comment]
Create an index and start serving,

```python
from jina import Document, DocumentArray, Executor, Flow, requests
import numpy as np

f = Flow(port_expose=45678).add(
    uses='jinahub://SimpleIndexer/v0.4',
    uses_with={'match_args': {'traversal_rdarray': ['c', ]}})

da = DocumentArray()

for _ in range(2000):
    d = Document(embedding=np.random.rand(512))
    for j in range(5):
        c = Document(embedding=np.random.rand(512))
        d.chunks.append(c)
    da.append(d)
with f:
    f.post(on='/index', inputs=da, request_size=100)
    f.block()
````

query with a client and sent request every 1 second,

```python
import numpy as np


def gen_doc():
    while True:
        doc = Document(embedding=np.random.rand(512))
        print(f'sent doc')
        time.sleep(1)
        yield doc


if __name__ == '__main__':
    c = Client(host='0.0.0.0', port=45678)
    c.post(on='/search', inputs=gen_doc(), parameters={'limit': 10000}, request_size=1)

```


We will see that after indexing, the disk usage is 49 Mb. With the query sent every 1 sec the disk usage increases,

```bash
➜  workspace git:(master) ✗ du -h
 49M    ./SimpleIndexer/0
 49M    .
➜  workspace git:(master) ✗ du -h
 49M    ./SimpleIndexer/0
 49M    .
➜  workspace git:(master) ✗ du -h
 51M    ./SimpleIndexer/0
 51M    .
➜  workspace git:(master) ✗ du -h
 53M    ./SimpleIndexer/0
 53M    .
➜  workspace git:(master) ✗ du -h
 54M    ./SimpleIndexer/0
 54M    .
➜  workspace git:(master) ✗ du -h
 55M    ./SimpleIndexer/0
 55M    .
➜  workspace git:(master) ✗ du -h
 56M    ./SimpleIndexer/0
 56M    .
➜  workspace git:(master) ✗ du -h
 57M    ./SimpleIndexer/0
 57M    .
➜  workspace git:(master) ✗ du -h
 58M    ./SimpleIndexer/0
 58M    .
➜  workspace git:(master) ✗ du -h
 59M    ./SimpleIndexer/0
 59M    .
```
