### ISSUE TITLE
Hello World - Chatbot

### ISSUE THREAD

**Issue by franperic** [jina-ai/jina#3837]
**Description**
I run into the following error when running the chatbot example. 
I believe the error stems from the data import. But I am not sure how to fix this.

---

**Environment**
- jina 2.1.13
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.3
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.41.1
- pyyaml 6.0
- python 3.8.2
- platform Darwin
- platform-release 20.2.0
- platform-version Darwin Kernel Version 20.2.0: Wed Dec 2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 119394988126771
- session-id e7014ab0-39a4-11ec-8dd8-6c96cfdaf233
- uptime 2021-10-30T19:14:54.891845
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Logs**
DONE ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00 181.8 step/s 2 steps done in 0 seconds
           Flow@67201[I]:🎉 Flow is ready to use!                                                   
        🔗 Protocol:            GRPC
        🏠 Local access:        0.0.0.0:54836
        🔒 Private network:     192.168.0.34:54836
        🌐 Public address:      144.2.107.48:54836
⠹ Working... ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00 estimating...            JINA@67201[C]:inputs is not valid! BadDocType('fail to construct a document from {\'source\': \'ABC Australia\', \'url\': \'https://www.abc.net.au/triplej/programs/hack/coronavirus-covid-19-frequently-asked-questions/12063976\', \'question\': "What\'s closed?", \'answer\': \'Physical distancing is the reason the Federal Government has closed pubs, indoor sporting venues and churches across Australia.\\nThe situation with schools varies state by state. Queensland, South Australia, Western Australia, Tasmania and Northern Territory will keep schools open for the children of essential workers but will began to implement pupil-free days in the coming weeks. Victoria and ACT schools are already on break. NSW schools remain open but students are encouraged to stay at home.\\nThe Prime Minister has said all "non-essential"" travel within Australia should be cancelled. Western Australia and South Australia have closed their borders - any arrivals after Tuesday afternoon\', \'wrong_answer\': \' March 24\', None: [\' will be required to self-isolate for 14 days.\']}, if you are trying to set the content you may use "Document(content=your_content)"')
Traceback (most recent call last):
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/jina/types/document/__init__.py", line 283, in __init__
    self._pb_body.tags.update(
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/google/protobuf/internal/well_known_types.py", line 801, in update
    _SetStructValue(self.fields[key], value)
TypeError: None has type NoneType, but expected one of: bytes, unicode

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/jina/clients/request/__init__.py", line 58, in request_generator
    for batch in batch_iterator(data, request_size):
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/jina/helper.py", line 208, in batch_iterator
    chunk = tuple(islice(iterator, batch_size))
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/jina/types/document/generators.py", line 148, in from_csv
    yield Document(value, field_resolver)
  File "/Users/franperic/Library/Caches/pypoetry/virtualenvs/hack4good-jina-w0CVWkZi-py3.8/lib/python3.8/site-packages/jina/types/document/__init__.py", line 299, in __init__
    raise BadDocType(
jina.excepts.BadDocType: fail to construct a document from {'source': 'ABC Australia', 'url': 'https://www.abc.net.au/triplej/programs/hack/coronavirus-covid-19-frequently-asked-questions/12063976', 'question': "What's closed?", 'answer': 'Physical distancing is the reason the Federal Government has closed pubs, indoor sporting venues and churches across Australia.\nThe situation with schools varies state by state. Queensland, South Australia, Western Australia, Tasmania and Northern Territory will keep schools open for the children of essential workers but will began to implement pupil-free days in the coming weeks. Victoria and ACT schools are already on break. NSW schools remain open but students are encouraged to stay at home.\nThe Prime Minister has said all "non-essential"" travel within Australia should be cancelled. Western Australia and South Australia have closed their borders - any arrivals after Tuesday afternoon', 'wrong_answer': ' March 24', None: [' will be required to self-isolate for 14 days.']}, if you are trying to set the content you may use "Document(content=your_content)"
indexed & imported data

**Comment by hanxiao** [comment]
seems our csv parser goes wrong, will fix it soon

**Comment by hanxiao** [comment]
rolled out in 2.2.2, please `pip install -U jina`
