### ISSUE TITLE
Improve Flow documentation

### ISSUE THREAD

**Issue by CatStark** [jina-ai/jina#3850]
We have misleading information about the Flow as shown [here](https://github.com/jina-ai/jina/issues/3848). We need to update this.

**Comment by starlightknown** [comment]
hello, I would like to work on this issue if possible

**Comment by CatStark** [comment]
Hi @starlightknown ,

Thanks a lot for helping us! :D and sure thing it is possible. Let us know when you start working on it so we can link your PR to the issue

**Comment by starlightknown** [comment]
Sure, could I get some directions on how to get started with it. I'll start working on it

**Comment by CatStark** [comment]
Hi @starlightknown , I was talking with the team and someone internally is already working on this since deep knowledge of the Flow is needed. But thank you so much for your message! Hope you can still find something else that sparks your interest :)
