### ISSUE TITLE
workspace issue

### ISSUE THREAD

**Issue by winstonww** [jina-ai/jina#3857]
For example, if we do the following:

```python
Flow().add(uses='jinahub+docker://SimpleIndexer', uses_metas={'workspace': '/tmp'}') with f:
    ...
```
workspace is not created in the specified directory. Yet, the following:

```python
class MyExecutor(Executor):
    @requests
    def foo(self, **kwargs):
         print(self.workspace)

Flow().add(uses=MyExecutor, uses_metas={'workspace': '/tmp'}) with f:
    ...
```
works.

**Comment by JoanFM** [comment]
Can u check where is the workspace created in the first case?

**Comment by winstonww** [comment]
Yep, for me it is at the place where the script is started

**Comment by JoanFM** [comment]
So can u compare in both cases where the workspace is stored?

**Comment by winstonww** [comment]
EDIT: I am currently reproducing this issue  with `jinahub+docker` with `volumes`:

```python
Flow().add(uses='jinahub+docker://SimpleIndexer', uses_metas={'workspace': '/tmp'}, volumes='/tmp:/tmp') with f:
    ...
```
The following is the results:

<img width="771" alt="Screen Shot 2021-11-03 at 3 31 54 PM" src="https://user-images.githubusercontent.com/13983591/140023079-665fe98d-9e4f-441f-9fd2-7618414e81bb.png">


The flow launches the following:
```
/usr/local/bin/jina executor --uses config.yml --name executor0 --workspace /Users/winstonwong/jina --identity 480f3359-752f-45ac-b0a5-04f0efae3b5c --workspace-id bb69e642-04a0-4ca1-8003-8021af0d8320 --zmq-iden
tity 9c222235-7130-40b3-89f2-85ad2ac379ed --port-ctrl 52562 --uses-metas {"workspace": "/tmp"} --port-in 52563 --port-out 52564 --hosts-in-connect --socket-in ROUTER_BIND --socket-out ROUTER_BIND --native --num-part 1 --dynamic-
routing-out --dynamic-routing-in --runs-in-docker --upload-files --noblock-on-start
```

` --workspace /Users/winstonwong/jina` is stored in `self.workspace` in `flow/base.py`.

**Comment by winstonww** [comment]
To make things clearer, here is comparison of the actual vs expected behavior:

Case 1:
```python
class MyExecutor(Executor):
    @requests
    def foo(self, **kwargs):
         print(self.workspace)

Flow().add(uses=MyExecutor, uses_metas={'workspace': '/tmp'}) with f:
     f.index()
 ```
 
 Expected behavior/output:
`workspace: /tmp`

Actual behavior/output:
`workspace: /tmp`


Case 2
```python
Flow().add(uses='jinahub+docker://SimpleIndexer', uses_metas={'workspace': '/tmp'}) with f:
    ...
```

 Expected behavior:
SimpleIndexer's `workspace` should be located in `/tmp`

Actual behavior/output:
SimpleIndexer's `workspace` is located in `/Users/winstonwong/jina`

**Comment by JoanFM** [comment]
The `uses_metas` seems to be properly passed to the `Executor`. This `uses_metas` is the way to override the default `workspace` passed to the `Runtime`. All these `logs` do not provide valid information.

Please make sure u index data and check where the `data` is stored to validate wether or not the workspace is properly created.

**Comment by winstonww** [comment]
Yep, `data` is created in the `workspace`. I will close this non-issue.
