### ISSUE TITLE
try_startup_search

### ISSUE THREAD

**Issue by EliaLesyk** [jina-ai/jina#3906]
**Describe your proposal/problem: Use Jina for start-up data**

I'm applying Jina AI for neural search within the database of start-up descriptions since it might give better results than simple search.
---

**Environment**

- jina 2.4.2
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.4
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.41.1
- pyyaml 6.0
- python 3.9.1
- platform Darwin
- platform-release 20.6.0
- platform-version Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101
- architecture x86_64
- processor i386
- uid 32986996461122
- session-id 02034d3e-423f-11ec-b2c5-1e006234ce42
- uptime 2021-11-10T16:58:12.213919
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Screenshots**

**Comment by JoanFM** [comment]
Hello @EliaLesyk,

Thanks for trying out Jina. Is there a specific issue that you are having where you may need some help?

**Comment by EliaLesyk** [comment]
Hi @JoanFM,
I'd be grateful for help with correctly merging my pull request from this fork: https://github.com/EliaLesyk/jina/tree/example-startup-search-3906. It includes my suggestion for the application of Jina.
It's my first pull request, so I'm afraid of adding some mess to public repositories.

**Comment by JoanFM** [comment]
Hi @EliaLesyk ,

This fork of yours is an example, not a feature to add to the framework. It cannot be merged into jina core. But it is valid on its own as an example of usage

**Comment by EliaLesyk** [comment]
Hi @JoanFM,

That's what I have also had in mind but wasn't sure. Thank you very much for a super prompt reply!
