### ISSUE TITLE
Clean up parser structure

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#3939]
The parser structure with all its mixins and specific parsers has become a bit messy at this point.
Example: The gateway parser does not contain the pod parser, although a gateway is also a pod. This means the gateway does not have some of the pod args (like peas_hosts) and inside the pod we always need to check for the existence of certain args. That is fairly clunky.

As part of this ticket one should do the following:

- [ ] Double check which args belong in which mixin. Move them if necesary, remove redundant or obsolete args
- [ ] Double check which parser mixins belong in which parser, move them as necessary. Also check if the mixin structure could be simplified a bit (we have a lot of parser mixins now)
- [ ] Double check which parser is used in which context and adapt if necessary

**Comment by deepankarm** [comment]
Few known issues:

1. Pea on remote with `HeadRuntime` doesn't understand polling args, as `polling` is only available for `pod_parser` and JinaD while creating a Pea removes all unknown args.
2. Pea on remote with `GatewayRuntime` is not possible right now, as the distributed args are not enabled for `gateway_parser`.
