### ISSUE TITLE
Executor: endpoints should merge parameters from shards

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/jina#3946]
**Describe the feature**

As an Executor developer, I would like that, when I return a dictionary (e.g. on a `/status`-type endpoint) and have `parallel > 1`, this dictionary is not overridden by the last shards, but instead is **merged** somehow. 

**Your proposal**

Instead of returning just a dictionary, return a dictionary of dictionaries perhaps, with pea_ids as keys. The default dictionary could be duplicated as the top-level entries too, to maintain backwards-compatibility.

Something like, perhaps:

```
{
  'last_sync': '2021-11-17T15:05:14.137362',
  'psql_docs': 10.0,
  'pea_id': 0.0,
  'hnsw_docs': 3.0,
  'pea_0': {
    'last_sync': '2021-11-17T15:05:14.137362',
    'psql_docs': 10.0,
    'pea_id': 0.0,
    'hnsw_docs': 3.0
  },
  ...
  'pea_2': {
    'last_sync': '2021-11-17T15:05:14.137362',
    'psql_docs': 10.0,
    'pea_id': 2.0,
    'hnsw_docs': 3.0
  },          
}

```

---

Reproduce scenario with:

start docker PSQL:

`docker run -e POSTGRES_PASSWORD=123456  -p 127.0.0.1:5432:5432/tcp postgres:13.2`                                                                                                                                                                        

and then run:

```python
import numpy as np
from jina import DocumentArray, Flow, Document


def get_documents(nr=10, index_start=0, emb_size=7):
    random_batch = np.random.random([nr, emb_size]).astype(np.float32)
    for i in range(index_start, nr + index_start):
        d = Document()
        d.id = f'aa{i}'  # to test it supports non-int ids
        d.embedding = random_batch[i - index_start]
        yield d


def main():
    emb_size = 10

    docs = DocumentArray(get_documents(emb_size=emb_size))

    with Flow().add(
            uses='jinahub://HNSWPostgresIndexer/test-cristian',
            uses_with={
                'dim': emb_size
            },
            parallel=3,
            polling='all',
            install_requirements=True,
            uses_after='jinahub+docker://MatchMerger/v0.2'
    ) as f:
        # test for empty sync from psql
        result = f.post('/status', None, return_results=True)
        result = dict(result[0].parameters)
        print(result)
        f.post('/index', docs)
        f.post('/sync')
        search_docs = DocumentArray(
            get_documents(index_start=len(docs), emb_size=emb_size))

        result = f.post('/search', search_docs, return_results=True)
        search_docs = result[0].docs
        assert len(search_docs[0].matches) > 0

        result = f.post('/status', None, return_results=True)
        result = dict(result[0].parameters)
        print(f'## result = {result}')


if __name__ == '__main__':
    main()
```

notice that the output is

```
...
## result = {'last_sync': '2021-11-17T15:05:14.137362', 'psql_docs': 10.0, 'pea_id': 0.0, 'hnsw_docs': 3.0}
```

meaning it's only returned from one `pea` / shard.

`/status` endpoint code is:

```python
    @requests(on='/status')
    def status(self, **kwargs):
        """
        Get information on status of this Indexer inside a Document's tags
        """
        psql_docs = self._kv_indexer.size
        hnsw_docs = self._vec_indexer.size
        last_sync = self._vec_indexer.last_timestamp
        last_sync = last_sync.isoformat()
        status = {
            'psql_docs': psql_docs,
            'hnsw_docs': hnsw_docs,
            'last_sync': last_sync,
            'pea_id': self.runtime_args.pea_id
        }
        return status
```

**Comment by JoanFM** [comment]
This behavior right now is coherent with the current `Executor` usage. If no `MatchMerger` is added in `uses_after`, the Runtime simply returns the last `message` received if polling=ALL. 

This would be doable, but I would like to know if this is coherent with how thing work right now.


However, if somebody wants to take this, this should be worked on in the `DataRequestHandler`

**Comment by cristianmtr** [comment]
> This behavior right now is coherent with the current `Executor` usage. If no `MatchMerger` is added in `uses_after`, the Runtime simply returns the last `message` received if polling=ALL.
> 
> This would be doable, but I would like to know if this is coherent with how thing work right now.
> 
> However, if somebody wants to take this, this should be worked on in the `DataRequestHandler`

Yes, this works as expected now. 

The requirement would be to the DataHandler handle parameters being returned, without overridding them directly. Similar to how we have docs_matrix, we could have `parameters_list`. Maybe some other design/name/type/structure, but something in that direction.
