### ISSUE TITLE
关于搜索语法

### ISSUE THREAD

**Issue by nightwind2020** [jina-ai/jina#396]
**Describe the feature**

搜索：`^ having {v}`
得到：
> Having started the process,
> Having said that, etc.

--

搜索：`to * surprise`
得到：
> to our surprise
> to his surprise, etc.

**Your proposal**

看介绍，Jina 是一个相比 Elasticsearch 更接近 NLP 的搜索引擎。但是没有在文档里找到这方面的信息。我是这方面的新手，可能是没理解到。
请问 Jina 可以并且适合实现，POS占位符+正则表达式，这样的搜索语法吗？

**Comment by hanxiao** [comment]
你好，你提到的这种需求用ES即可实现。Jina非符号化(symbolic) 搜索引擎，正则等不属于Jina范围内。
