### ISSUE TITLE
hello-world in C/S is considerably slower than in Flow API

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#399]
**Describe your problem**

https://github.com/jina-ai/examples/tree/master/helloword-in-cs

**What is your guess?**

Something wrong with the gateway async?

---

**Environment**

**Screenshots**

**Comment by maximilianwerk** [comment]
Even thought this might not be the real problem, calling
```
while True:
    pass
```
is pretty ressource intensive and blocks one cpu completely. Changing the `pass` to `time.sleep(1)` gave a ~20% speed boost. It is not the world, but already something.

**Comment by hanxiao** [comment]
aha, thanks for pointing that out! let me try threading.Event().wait() then

**Comment by hanxiao** [comment]
yep, I can confirm this is the problem. Using the threading.Event().wait() gives speed at 1739.8/s which is identical to using it in Flow API

**Comment by hanxiao** [comment]
A complete example is provided in https://github.com/jina-ai/examples/tree/master/helloworld-in-cs
