### ISSUE TITLE
Cannot dump imageblob to bytesio

### ISSUE THREAD

**Issue by Stubatiger** [jina-ai/jina#4008]
**ENV**

Python 3.9
jina 2.5.0

**Describe the bug**

If i try to dump an image blob to a io.bytesio object an error is thrown

```python
from jina import Document
import io
d =  Document(uri='steam_data/image_store/8c/5b/8c5b265b9c533636.png')
output = io.BytesIO() 

(
    d
    .load_uri_to_image_blob()
    .dump_image_blob_to_file(output)
)
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_12013/123594708.py in <module>
      5 
      6 (
----> 7     d
      8     .load_uri_to_image_blob()
      9     .dump_image_blob_to_file(output)

~/miniconda3/envs/steam3.9/lib/python3.9/site-packages/jina/types/document/mixins/image.py in dump_image_blob_to_file(self, file, channel_axis)
    100             blob = _move_channel_axis(self.blob, channel_axis, -1)
    101             buffer = _to_png_buffer(blob)
--> 102             fp.write(buffer)
    103         return self
    104 

AttributeError: 'nullcontext' object has no attribute 'write'
```

**Describe how you solve it**

Here 
https://github.com/jina-ai/jina/blob/99b1e1dba1562659be679735912564150c08fe3b/jina/types/document/mixins/image.py#L98

the returned object of the context is not used in this line
```python
 with fp:
```
if we change the code to
```python
with fp as fp_cxt:
    blob = _move_channel_axis(self.blob, channel_axis, -1)
    buffer = _to_png_buffer(blob)
    fp_cxt.write(buffer)
```

it seems to work for my case.
Im not sure of the broader consequences though, as i dont know what the nullcontext is used for here

**Comment by JoanFM** [comment]
Hey @Stubatiger ,

> Thanks for finding the issue. Would u please raise a PR to fix the issue along with a test to show the fix?

**Comment by Stubatiger** [comment]
Sure, ill give it a try on the weekend :o)

**Comment by CatStark** [comment]
Hi @Stubatiger , thanks a lot for your contribution! Did you have time to check Joan's feedback? or is there anything else you need from our side to continue with the PR?

**Comment by JoanFM** [comment]
Issue to be moved to `docarray` if still valid
