### ISSUE TITLE
Trying to index fashionpedia images

### ISSUE THREAD

**Issue by programmeddeath1** [jina-ai/jina#4028]
Hii
I am trying to index fashionpedia images (val images 2020 - https://github.com/cvdfoundation/fashionpedia)

Its around 3200 images.

I tried to run jina indexing using the DocumentArray.from_files to index and load the images. I am running on gpu colab and 
it is showing Error -  and 1 day 9 minutes to index and process.
Is this normal for only  3200 images? Do i need to pre-process and reduce the size of the images?

**Comment by makram93** [comment]
Hi @programmeddeath1,

Thank you for trying out Jina. I have created a minimum working example [here](https://colab.research.google.com/drive/1LlrXQ3TpBd9Je46LQy836aJSGXfMzlrF?usp=sharing) and`DocumentArray.from_files` seems to be working for me. Please give it a try and let me know if you face any problems.

**Comment by CatStark** [comment]
Hi @programmeddeath1 , was your question solved by @makram93? if that's the case I'll close this issue :)
