### ISSUE TITLE
minor tweak to `metric_name` in `match`

### ISSUE THREAD

**Issue by winstonww** [jina-ai/jina#4053]
Currently, we have a situation where we wanted to match docs with DPR embeddings with the cosine metric. But it would be very useful to label the score as something like `"dpr"` rather than `"cosine"` to differentiate the scores sine we need to use this score for posterior calculation in the match merger, and the score name "cosine" might have already been taken. However, the following is not supported at the moment:

```python
import numpy as np
from jina import Document, DocumentArray
doc1 = Document(embedding=np.array([1,2,3]))
match_docs = DocumentArray([Document(embedding=np.array([0,0,1]))])
doc1.match(match_docs, metric_name='dpr', metric='cosine')
```

It would be awesome if we can have this for the match function.

**Comment by JoanFM** [comment]
To be moved to `docarray` if applies
