### ISSUE TITLE
Document has issues.

### ISSUE THREAD

**Issue by mirfan899** [jina-ai/jina#4056]
Tutorial on Open Domain Question Answer bot(https://docs.jina.ai/tutorials/question-answering-bot/) has some issues.
I tried to run the open domain question tutorial and got issues with some variable names i.e.

```python
query_flow = Flow(
    # Create vector representations from query
    ).add(name="query_transformer", uses=TextEncoder
    # Search the index for matching generated questions
    ).add(name="query_indexer", uses=MyIndexer)

with query_flow: 
    indexing_flow.post(on="/query", inputs=user_queries, on_done=print)
```
Here it should be `query_flow` not `indexing_flow`.

Another mistake is the `MyIndexer` variable name. In tutorial you have `SimpleIndexer` not `MyIndexer`. Also it is not clear which imports you are using in your tutorial. Causes issues to import which module from which package i.e. `defaultdict` is in both pydantic and `typing` package.
**Environment**

- jina 2.6.2
- docarray 0.0.2
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.4
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.42.0
- pyyaml 6.0
- python 3.8.10
- platform Linux
- platform-release 5.11.0-38-generic
- platform-version #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021
- architecture x86_64
- processor x86_64
- uid 102803166992703
- session-id 3987190d-5b5c-11ec-9e5d-5d7fba40193f
- uptime 2021-12-12T23:00:20.072242
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
**Screenshots**

**Comment by gvondulong** [comment]
Will look into this tomorrow. 
Have a good evening.

**Comment by gvondulong** [comment]
@mirfan899 Thank you for raising this issue. 
Your points are all very valid. Our codebase has moved on, so I was not able to fix it today. 
Once the related issues are solved (likely tomorrow), I will get back to you!

**Comment by gvondulong** [comment]
Hi @mirfan899, 
thank you again for reaching out! I have fixed the problems and used your feedback to generally improve the tutorial. 
The issue should be fixed. Here is a PR with the changes, in case you want to have a look. https://github.com/jina-ai/jina/pull/4064
We are always happy to see people building stuff with Jina and strive to make that as easy as possible for you! 
Feel free to reach out any time again and until then: Happy hacking!
