### ISSUE TITLE
AttributeError: 'TextEncoder' object has no attribute 'metas'

### ISSUE THREAD

**Issue by mirfan899** [jina-ai/jina#4057]
I tried to run the tutorial https://docs.jina.ai/tutorials/question-answering-bot, after setting up the environment I got following error on indexing the docs.

```shell
JINA@35146[W]:The given arguments {'random_seed'} are not defined in `QuestionGenerator.__init__`
⠧ 3/4 waiting text_encoder to be ready...           JINA@35147[W]:The given arguments {'parameters'} are not defined in `TextEncoder.__init__`
           Flow@35110[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:41385
	🔒 Private network:	192.168.6.104:41385
   text_encoder@35147[E]:AttributeError("'TextEncoder' object has no attribute 'metas'")
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/plp/environments/OpenJina/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/home/plp/environments/OpenJina/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/home/plp/environments/OpenJina/lib/python3.8/site-packages/jina/peapods/runtimes/zmq/zed.py", line 221, in _handle
    self._data_request_handler.handle(
  File "/home/plp/environments/OpenJina/lib/python3.8/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 139, in handle
    msg.request.parameters.to_dict(), self._executor.metas.name
AttributeError: 'TextEncoder' object has no attribute 'metas'

Process finished with exit code 0

```

Here is `encoder.py` code.
```python
from jina import Executor, Document, DocumentArray, DocumentArrayMemmap, requests
import torch
from sentence_transformers import SentenceTransformer
from typing import Tuple


class TextEncoder(Executor):

    def __init__(self, **kwargs):
        self.model = SentenceTransformer(
            'paraphrase-mpnet-base-v2', device="cpu", cache_folder=".")

    @requests(on=['/search', '/index'])
    def encode(self, docs: DocumentArray,
               traversal_paths: Tuple[str] = ('r',), **kwargs):
        """Wraps encoder from sentence-transformers package"""
        target = docs.traverse_flat(traversal_paths)

        with torch.inference_mode():
            embeddings = self.model.encode(target.texts)
            target.embeddings = embeddings

```

Here is my `index.py` code
```python
from jina import DocumentArray
from jina import Flow
from jina import Document

from encoder import TextEncoder
from executor import QuestionGenerator
from indexer import SimpleIndexer


example_sentences = [
    "Document is the basic data type that Jina operates with",
    "Executor processes a DocumentArray in-place",

    "Jina uses the concept of a flow to tie different executors together"
]

docs = DocumentArray([Document(content=sentence) for sentence in example_sentences])

indexing_flow = Flow(
# Generate potential questions using doc2query
).add(name="question_transformer",
      uses=QuestionGenerator,
      uses_with={"random_seed": 12345}
# Create vector representations for generated questions
).add(name="text_encoder",
      uses=TextEncoder,
      uses_with={"parameters": {"traversal_paths": ["c"]}}
# Store embeddings for all generated questions as index
).add(name="my_indexer",
      uses=SimpleIndexer
)

with indexing_flow:
    # Run the indexing on all extracted sentences
    indexing_flow.post(on="/index", inputs=docs, on_done=print)
```

**Environment**

jina 2.6.2
docarray 0.0.2
jina-proto 0.1.0
jina-vcs-tag (unset)
libzmq 4.3.4
pyzmq 1.21.4
protobuf 3.19.1
proto-backend cpp
grpcio 1.42.0
pyyaml 6.0
python 3.8.10
platform Linux
platform-release 5.11.0-38-generic
platform-version flow is setting __default_host__ in an arbitrary way #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021
architecture x86_64
processor x86_64
uid 102803166992703
session-id 3987190d-5b5c-11ec-9e5d-5d7fba40193f
uptime 2021-12-12T23:00:20.072242
ci-vendor (unset)
JINA_ARRAY_QUANT (unset)
JINA_CONTROL_PORT (unset)
JINA_DEFAULT_HOST (unset)
JINA_DEFAULT_TIMEOUT_CTRL (unset)
JINA_DISABLE_UVLOOP (unset)
JINA_FULL_CLI (unset)
JINA_HUBBLE_REGISTRY (unset)
JINA_HUB_CACHE_DIR (unset)
JINA_HUB_ROOT (unset)
JINA_K8S_USE_TEST_PIP (unset)
JINA_LOG_CONFIG (unset)
JINA_LOG_ID (unset)
JINA_LOG_LEVEL (unset)
JINA_LOG_NO_COLOR (unset)
JINA_LOG_WORKSPACE (unset)
JINA_MP_START_METHOD (unset)
JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
JINA_POD_NAME (unset)
JINA_RANDOM_PORT_MAX (unset)
JINA_RANDOM_PORT_MIN (unset)
JINA_VCS_VERSION (unset)

**Comment by JoanFM** [comment]
Hello @mirfan899 ,

Sorry for the inconvenience,

the `TextEncoder` is missing the `super().__init__(**kwargs)` call to initialize the arguments from the `Executor` base class.

@gvondulong can you please take a look? thanks!

**Comment by gvondulong** [comment]
Hi @JoanFM and @mirfan899, 
I was working on this yesterday and found a number of issues in the code. The updated version is next to finished and should be published today. 
Thanks again @mirfan899 for raising the issue and helping us to make the tutorial better for everyone!

**Comment by gvondulong** [comment]
FYI @mirfan899 I raised a [PR](https://github.com/jina-ai/jina/pull/4064/files), that addresses the issues you pointed out and generally seeks to generally improve the tutorial on how to build a QA bot with Jina. 
Thank you again for raising this issue! We are always happy to see people, who are eager to use Jina to build cool stuff and it is our task to make that as easy as possible.
