### ISSUE TITLE
Rotated KeyFrames image sprite

### ISSUE THREAD

**Issue by shersoni610** [jina-ai/jina#4105]
Hello

I used the KeyFrames extraction code provided on the web. However, when I use 

d.chunks.plot_image_sprites('mov.png')

The images in the mov.png are rotated by 90 degrees. Is there a way to get the correct
rotation automatically?

**Comment by makram93** [comment]
Hi @shersoni610,

Thank you for trying out Jina and raising this issue. Can you share the jina version? Also please share the code snippet to reproduce this.

**Comment by JoanFM** [comment]
Hey @shersoni610 , can you try this in the new `docarray` project?

This issue would be relevant there.

Thanks
