### ISSUE TITLE
using clip-ViT-B-32-multilingual-v1 with CLIPImageEncoder

### ISSUE THREAD

**Issue by servusoft** [jina-ai/jina#4109]
**Describe the feature**

The clip-vit-base-patch32 model from openai has a restriction, its trained with English and not support another languages.

**Your proposal**

The clip-ViT-B-32 from sentence_transformers has an multilingual text encoder (clip-ViT-B-32-multilingual-v1)
My question is, are the text-embeddings from CLIPTextEncoder('clip-vit-base-patch32') the same as from SentenceTransformer('clip-ViT-B-32')?
Or, its possible to create only a replacement for CLIPTextEncoder to using multiligual searches based on SentenceTransformer together with CLIPImageEncoder?

---

An example for using multilingual SentenceTransformer is here:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/image-search/Image_Search-multilingual.ipynb

**Environment**

- jina 2.6.3
- docarray 0.0.3
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.4
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.43.0
- pyyaml 6.0
- python 3.9.7
- platform Linux
- platform-release 4.9.0-4-amd64
- platform-version #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23)
- architecture x86_64
- processor x86_64
- uid 236733139088675
- session-id af8cbcd0-67ca-11ec-b748-d74ebaa97523
- uptime 2021-12-28T11:41:16.633736

**Screenshots**

**Comment by makram93** [comment]
Hi @servusoft, 

Thank you for trying out Jina. You are right, `clip-vit-base-patch32` supports only English.

To answer your question, the text-embeddings from `CLIPTextEncoder('clip-vit-base-patch32')` are the same as from `SentenceTransformer('clip-ViT-B-32')`. As mentioned [here](https://www.sbert.net/examples/applications/image-search/README.html) `SentenceTransformer` is a wrapper for `OpenAI CLIP` and under the hood of `CLIPTextEncoder` we implement CLIP model from [huggingface](https://huggingface.co/openai/clip-vit-base-patch32#model-version) which uses the model `'openai/clip-vit-base-patch32'` taken from `OpenAI CLIP`.

In order to support multiligual based on SentenceTransformer you can use [`TransformerSentenceEncoder`](https://hub.jina.ai/executor/nh1ucuki) to get the text embeddings. You can use this together with CLIPImageEncoder for multilingual searches. 

Hope this helps.

**Comment by servusoft** [comment]
Many thanks for reply, makram93!

As I your understood, the flow with **TransformerSentenceEncoder**
```
flow = Flow() \
    .add(name="text_encoder", 
		uses='jinahub://TransformerSentenceEncoder/v0.1',
        uses_with={'model_name': 'clip-ViT-B-32'}) \
    .add(name="indexer", uses='jinahub://SimpleIndexer')
```
serve the same results as the flow with **CLIPTextEncoder**?
	
```
flow_search = Flow() \
     .add(name="text_encoder", 
		uses='jinahub://CLIPTextEncoder/v0.1') \
     .add(name="indexer", uses='jinahub://SimpleIndexer')
flow_search    
```

**Comment by makram93** [comment]
> As I your understood, the flow with **TransformerSentenceEncoder**
> 
> ```
> flow = Flow() \
>     .add(name="text_encoder", 
> 		uses='jinahub://TransformerSentenceEncoder/v0.1',
>         uses_with={'model_name': 'clip-ViT-B-32'}) \
>     .add(name="indexer", uses='jinahub://SimpleIndexer')
> ```
> 
> serve the same results as the flow with **CLIPTextEncoder**?
> 
> ```
> flow_search = Flow() \
>      .add(name="text_encoder", 
> 		uses='jinahub://CLIPTextEncoder/v0.1') \
>      .add(name="indexer", uses='jinahub://SimpleIndexer')
> flow_search    
> ```

Yes, they are same. Just replace `clip-ViT-B-32` with `clip-ViT-B-32-multilingual-v1` when using `TransformerSentenceEncoder` for multilingual.

**Comment by servusoft** [comment]
> Yes, they are same. Just replace `clip-ViT-B-32` with `clip-ViT-B-32-multilingual-v1` when using `TransformerSentenceEncoder` for multilingual.

thank you very much @makram93, it works fine!

I have another question: 
Is there a similar way to configure CLIPImageClassifier to work with multilingual labels?

**Comment by makram93** [comment]
> I have another question: Is there a similar way to configure CLIPImageClassifier to work with multilingual labels?

CLIPImageClassifier uses single model for text-image classification and in the example that you shared, two different models are used. However, you can try using CLIPImageClassifier with the `clip-ViT-B-32-multilingual-v1`. The other option would be to write your own executor extending the CLIPImageClassifier logic, using two different models for classification with multilingual labels.

**Comment by servusoft** [comment]
It looks like we need to write a new executor. The CLIPModel does not work with "sentence-transformers/clip-ViT-B-32". Here indexing will be with "clip-ViT-B-32" and search with "clip-ViT-B-32-multilingual-v1" models. 

I'll try to write with a name like CLIPImageClassifierML. If I need help, I will contact you. 

I am delighted about Jina platform! With a few lines of code, its possible to create a documented and pruction ready AI service!

Should I close the ticket?

**Comment by makram93** [comment]
@servusoft, I am excited and looking forward to your application. We are always happy to see people, who are eager to use Jina to build cool stuff and it is our task to make that as easy as possible.

I am closing this ticket now. Do create a new issue or post on our community Slack for quick support.
