### ISSUE TITLE
Document method `.dict()` fails

### ISSUE THREAD

**Issue by gmastrapas** [jina-ai/jina#4114]
**Describe the bug**

Conversion to dict, does not seem to work

```
import numpy as np
from jina import Document
doc = Document(id='foo', blob=np.random.rand(3, 16, 16))
doc.dict()
```
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/gmastrapas/Desktop/jina-ai/research-image-retrieval-fashion/.venv/lib/python3.9/site-packages/docarray/helper.py", line 47, in _f
    old_fn_name = inspect.stack()[1][4][0].strip().split("=")[0].strip()
TypeError: 'NoneType' object is not subscriptable
```

**Environment**
- jina 2.6.3
- docarray 0.0.3
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.4
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.42.0
- pyyaml 6.0
- python 3.9.7
- platform Darwin
- platform-release 21.1.0
- platform-version Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 190070690681122
- session-id e78ebb92-698e-11ec-bd7e-acde48001122
- uptime 2021-12-30T18:38:23.163611
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Comment by JoanFM** [comment]
Check if still relevant in `docarray`
