### ISSUE TITLE
update `from_files` usage in documentation

### ISSUE THREAD

**Issue by winstonww** [jina-ai/jina#4146]
Saw in a couple of places in our documentations and also in eaps/solutions that: 
```python
from jina.types.document.generators import from_files
```
 is used. Now that `docarray` becomes a separate module, should we update the documentation to replace the imports to: 
```python
from docarray.document.generators import from_files
```
or would it make sense to import `docarray`'s `from_files` into jina so users can import `from_files` from Jina (like in the case of `Document`/`DocumentArray`/`Executor`...etc) ?

**Comment by JoanFM** [comment]
Hey @winstonww please make sure it is still relevant in `docarray` and open there if needed
