### ISSUE TITLE
windows10/py3.8 error in jina demo hello fashion

### ISSUE THREAD

**Issue by khuzaemah** [jina-ai/jina#4175]
**Describe your proposal/problem**

I can install jina ai with wsl ubuntu in windows, but I cannot running demo like jina hello fashion. I don't know why.
I clone jinai ai github with https://github.com/jina-ai/jina.git
---

**Environment**

I'm using wsl windows ubuntu, using text editor visual studio code
**Screenshots**

⠏       DONE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━ 0:00:46 80.5 step/s 39 steps done in 46 seconds
E0115 13:20:54.680967900    3926 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227654.680226900","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:20:56.163553100    3939 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227656.162975500","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:20:57.448176400    3953 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227657.447367400","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:20:58.598774400    3967 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227658.598136100","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:20:59.262457500    3975 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227659.261988800","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:21:03.288089900    3981 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227663.285622500","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
E0115 13:21:04.625733100    3993 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227664.625474400","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
⠋ 0/4 waiting executor0 executor1 executor2 gateway to be ready...E0115 13:21:05.961618900    4008 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1642227665.961465300","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
           Flow@3744[E]:Flow is aborted due to ['executor0', 'executor1', 'executor2'] can not be started.
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses (raised from /usr/lib/python3/dist-packages/apport/report.py:13)
Traceback (most recent call last):
  File "/home/emah/.local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/home/emah/.local/lib/python3.8/site-packages/cli/__init__.py", line 116, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/home/emah/.local/lib/python3.8/site-packages/cli/api.py", line 185, in hello
    hello_world(args)
  File "/home/emah/.local/lib/python3.8/site-packages/jina/helloworld/fashion/app.py", line 80, in hello_world
    with f:
  File "/home/emah/.local/lib/python3.8/site-packages/jina/flow/base.py", line 990, in __enter__
    return self.start()
  File "/home/emah/.local/lib/python3.8/site-packages/jina/flow/base.py", line 1037, in start
    self._wait_until_all_ready()
  File "/home/emah/.local/lib/python3.8/site-packages/jina/flow/base.py", line 1119, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStar
![error jina ai](https://user-images.githubusercontent.com/58174184/149611820-a8937e2f-9d06-4ecf-b7e2-fdfd03622155.jpg)
t

**Comment by JoanFM** [comment]
Hello @khuzaemah ,

Are you sure that no other services may be using the ports?

Have u been able to track down the meaning of this error? It seems like an upstream error

**Comment by JoanFM** [comment]
Have u tried to run it more than once? It seems that some services are trying to `bind` to already used ports.

It could be:
1. That the port exposed is already used by some part of the system
2. That you were unlucky and Jina assinged the same port to different Executors.

**Comment by JoanFM** [comment]
Hello @khuzaemah ,

May u be able to run this with `JINA_LOG_LEVEL=DEBUG` environment variable set

**Comment by vincetrep** [comment]
Hi @JoanFM,

I'm having a similar issue to @khuzaemah.

I'm running WSL on windows 10: on GNU/Linux
Python 3.9 installed
trying to run the multimodal demo.

I've iterated a couple of times and different ports were selected, all with the same results.

Any ideas?

Thanks,

Vincent

Stack trace:

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

▶️  /home/user/.local/bin/jina hello multimodal
🔧️                            cli = hello
                   download-proxy = None
🔧️                          hello = multimodal
🔧️                 index-data-url = https://static.jina.ai/multimo
🔧️                    port-expose = 8080
🔧️             unblock-query-flow = False
🔧️                        workdir = 8382a93e0d8c44efb2c1d5f88161bf

⠙       DONE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━ 0:00:27 404.5 step/s 112 steps done in 27 seconds
⠋ 4/10 waiting encodeText encodeImage imageIndexer keyValueIndexe to be ready...E0214 08:46:05.581127200    7598 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1644846365.581116400","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
           Flow@7553[I]:🎉 Flow is ready to use!
        🔗 Protocol:            GRPC
        🏠 Local access:        0.0.0.0:55682
        🔒 Private network:     10.0.0.73:55682
        🌐 Public address:      23.233.181.148:55682
⠸      ERROR ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00 0% ETA: 0 seconds      GRPCClient@7553[E]:gRPC error: StatusCode.UNAVAILABLE failed to connect to all addresses
the ongoing request is terminated as the server is not available or closed already
Traceback (most recent call last):
  File "/home/vincenttrepanier/.local/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/cli/__init__.py", line 116, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/cli/api.py", line 193, in hello
    hello_world(args)
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/helloworld/multimodal/app.py", line 63, in hello_world
    f.index(inputs=DocumentArray.from_csv(fp), request_size=10, show_progress=True)
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/clients/mixin.py", line 77, in post
    return run_async(
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/helper.py", line 1222, in run_async
    return asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/clients/mixin.py", line 57, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 78, in _get_results
    raise rpc_ex
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 51, in _get_results
    async for resp in stub.Call(req_iter):
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/grpc/aio/_call.py", line 326, in _fetch_stream_responses
    await self._raise_for_status()
  File "/home/vincenttrepanier/.local/lib/python3.9/site-packages/grpc/aio/_call.py", line 236, in _raise_for_status
    raise _create_rpc_error(await self.initial_metadata(), await
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1644846368.721949500","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3134,"referenced_errors":[{"created":"@1644846368.721948400","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"

**Comment by JoanFM** [comment]
Hello @vincetrep and @khuzaemah ,

Could you give it a try with the new Jina 3.0 version?

**Comment by JoanFM** [comment]
what is the version of jina in this success case?

**Comment by CatStark** [comment]
Hi @khuzaemah is this still an issue? Otherwise I'll proceed to close this issue :)

**Comment by khuzaemah** [comment]
I am success using it, thank you

**Comment by CatStark** [comment]
Cool! :) I'll close the issue then.
