### ISSUE TITLE
The multimodal demo cannot be accessed from  localhost

### ISSUE THREAD

**Issue by golubovic** [jina-ai/jina#4182]
Following steps are taken:

1) I have installed latest 'jinaai/jina:latest-devel' (Jina (v2.6.4))
2) Upon running Docker container and starting the demo 'jina hello multimodal' error comes up that transformers, torch and torchvision libraries are missing
3) I have pip installed all 3 missing libraries and committed container
4) Start the image again with allocated ports 'docker run -it --expose 8080 -p 8080:8080 --entrypoint=/bin/bash jinaai/jina:latest-devel-mladen'
5) Try to access the demo from a local browser with no success (I have tried accessing http://localhost:8080/multimodal and many other intuitive URL's with no success). Terminal window screenshot is given below
6) Accessing http://localhost:8080/docs renders the page as expected. However, if I try to run POST /post hollo world example it errors out too (screenshot given below).

![jina terminal](https://user-images.githubusercontent.com/4633191/150039265-31844fd0-0531-4a98-8b58-9171a2e6ddbc.JPG)
![post hello world](https://user-images.githubusercontent.com/4633191/150039275-42a4f3d2-a68f-4ae7-ada2-cbb1c368c90e.JPG)
S

**Comment by JoanFM** [comment]
Hey @golubovic ,

I have a question, what is the response you get? Is it just an empty response or something stating that the port was not reachable?

**Comment by golubovic** [comment]
Hi @JoanFM,

Please find screenshots with various urls I have tried in order to access Swagger UI for the multimodal demo. Let me know if you wish me to perform any particular test. My terminal logs are attached as well.
[terminal.txt](https://github.com/jina-ai/jina/files/7906283/terminal.txt)

![jina2](https://user-images.githubusercontent.com/4633191/150365629-d770529b-56d6-451e-a134-c42b4585ebad.JPG)
![jina4](https://user-images.githubusercontent.com/4633191/150365631-06e9896f-50e8-451a-8b67-461a32765377.JPG)
![jina3](https://user-images.githubusercontent.com/4633191/150365634-4b11399f-ee6f-49e0-81f8-734fa333112a.JPG)
M

**Comment by golubovic** [comment]
Hi @JoanFM 

I have tried the following as my browser URL's:
http://localhost/usr/local/lib/python3.7/site-packages/jina/helloworld/multimodal/static/index.html
http://localhost:8080/usr/local/lib/python3.7/site-packages/jina/helloworld/multimodal/static/index.html

none works, please let me know how you wish me to access the HTML page running on my local Docker container from my browser.

JINA_HOME is not setup, echo won't print it. I have attached screenshot of docker container env variables. I have verified that the index.html file does exist in this location '/usr/local/lib/python3.7/site-packages/jina/helloworld/multimodal/static/index.html
![jina11](https://user-images.githubusercontent.com/4633191/150370387-0782110c-c500-4a12-a315-445ff2f75737.JPG)
/

**Comment by JoanFM** [comment]
It is not `http`.

You should try this.

```file:///usr/local/lib/python3.7/site-packages/jina/helloworld/multimodal/static/index.html```

**Comment by golubovic** [comment]
I have tredit with string above by pasting it in the browser with no success, please see screenshot below:
1) VSC proves that file does exist in a given path (VSC is attached to the local container)
2) I have ensured that permissions aren't the problem by running chmod 777 'root@0935da7f3662:/usr/local/lib/python3.7/site-packages/jina# chmod -R 777 ./ ' 
![jina111](https://user-images.githubusercontent.com/4633191/150373093-c43f9657-0500-46a5-b4a1-1b60f9334a8d.JPG)

**Comment by JoanFM** [comment]
This path does not exist in your local machine, this path you are extracting from your `docker container`.

You need to find what is the equivalent path in your local Windows jina installation. Maybe you can simply copy-paste it to your local folder call it multimodal-jina.html, and open it from there

**Comment by golubovic** [comment]
I don't have local windows Jina installation. I have installed the docker container only by running 'docker run -it jinaai/jina:latest-devel' this has successfully downloaded the image from repository during the first run.

As stated in my first post as pytorch, pytrorchvision and transformers were missing in jina:latest-devel I have added them and committed to the container named 'jina:latest-devel-mladen'.

newly created image I have started with adequate port mappings 'docker run -it --expose 8080 -p 8080:8080 --entrypoint=/bin/bash jinaai/jina:latest-devel-mladen'. The entrypoint switch was added to the docker run command to ensure that contender doesn't exit immediately.

In a meantime, I have extended the PATH env variable to contain a directory of index.html, didn't change anything...

I am not sure why adding index.html path on my local Windows machine would change anything as that HTML page should invoke some Jina functionality which is solely contained in the local Docker container. This however, may be down to my lack of understanding of how things work.

**Comment by JoanFM** [comment]
That `html` help will help you sending the correct `data` to the REST API as it is expected by the example.

Being able to open it in your local system (where your browser runs) will help us identify where the problem may come from

**Comment by golubovic** [comment]
Hey @JoanFM,

The issue is solved, I have copied start.html file from the Docker container to my local Windows machine. I have then dragged & Dropped the start.html file into the browser. The page has opened, I have tested the demo by querying string 'grass' and placing weight to Text only, it has worked (please see below).  My browser URL shows file:///C:/Users/M200240/tg/me/ml/images/jina/index.html which is the path where I have persisted file on my local Windows hard drive (stating this just in case that someone reads this thread).

Thanks for the agile replies!!! :)
Mladen

![jina 1111](https://user-images.githubusercontent.com/4633191/150381836-664a70a8-30e7-4161-8005-70d9d1aef921.JPG)

**Comment by JoanFM** [comment]
Hey @golubovic ,

It was a pleasure to help you!
