### ISSUE TITLE
Throwing error when using All-in-one style Executor on MacOS M1

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/jina#4183]
**Describe the bug**
Copy this code snippet from https://docs.jina.ai/fundamentals/flow/#minimum-working-example

```python
from jina import Flow, Document, Executor, requests


class MyExecutor(Executor):

    @requests(on='/bar')
    def foo(self, docs, **kwargs):
        print(docs)


f = Flow().add(name='myexec1', uses=MyExecutor)

with f:
    f.post(on='/bar', inputs=Document(), on_done=print)
```

Throwing error `Flow@92889[E]:Flow is aborted due to ['myexec1'] can not be started.` on MacOS

**Describe how you solve it**

---

**Environment**

master branch

**Screenshots**

<img width="1440" alt="Screen Shot 2022-01-19 at 11 22 58 AM" src="https://user-images.githubusercontent.com/4194287/150058090-160f7731-8dd8-4ccc-a43b-831683be7c50.png">

**Comment by JoanFM** [comment]
can u please set `JINA_LOG_LEVEL` to `DEBUG` so that we can see more details

**Comment by mapleeit** [comment]
Felix already found the reason. It was caused by the `https_proxy`. @numb3r3

**Comment by JoanFM** [comment]
Then, let's close

**Comment by numb3r3** [comment]
close by https://github.com/jina-ai/jina/pull/4189
