### ISSUE TITLE
Unstable CI test result

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/jina#4185]
**Describe the bug**
Same PR, just rerun 2 times. 

https://github.com/jina-ai/jina/actions/runs/1716387908/attempts/1
https://github.com/jina-ai/jina/actions/runs/1716387908/attempts/2

The 2nd one succeeded, but 1st one threw errors.

This happens almost for each PR, which significantly decrease the faith on test result. 

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
One of the causes is being addressed in #4139
