### ISSUE TITLE
jina is not compatible with windows operating system

### ISSUE THREAD

**Issue by Tunmisesuliat** [jina-ai/jina#419]
**Describe your problem**
 I noticed that gina is not compatible with Windows. And I use a windows system. I was not able to run the hello world on windows. Even though I could install Jina with pip. I also ran Jina on docker, but running "docker run jinaai/jina hello-world" and "docker run -p 5000:5000 -v ./tmp:/workspace jinaai/jina:devel hello-world --workdir /workspace --logserver" i got the message "You should see a "hello-world.html" opened in your browser, if not you may open file:///workspace/hello-world.html manually" but no file was opened, and no html file was created. After days of trying and testing with the source code,, it started downloading the Fashion-MNIST training and test data, but got terminated at a point with "EOFError: Ran out of input" and "OSError: [WinError 87] The parameter is incorrect" error. i am still testing locally on windows, but no success yet. 
![Screenshot (32)](https://user-images.githubusercontent.com/39378295/81813337-3f7e7b80-951f-11ea-8bc8-aff303edd88a.png)
![Screenshot (33)](https://user-images.githubusercontent.com/39378295/81813497-718fdd80-951f-11ea-8c9b-66d3b3db6bd9.png)

**What is your guess?**
 i think the error occurs during the process of downloading and decompressing Fashion-MNIST training and test data. i checked through the hello-world helper file so as to know if any of the modules was not compatible with windows. I noticed the gzip module, and changed that to zipfile and also changed "urllib.request.urlretrieve" which was said to become deprecated soon to "urllib.request.urlopen" so as to specify a timeout. I am sure that the problem is beyond these, maybe most of the dependencies used are not compatible with windows.  

---

**Environment**
jina                          0.1.11
jina-proto                    0.0.21
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.18.4
protobuf                      3.11.3
proto-backend                 python
grpcio                        1.11.0
ruamel.yaml                   0.16.10
python                        3.8.2
platform                      Windows
platform-release              10
platform-version              10.0.18362
architecture                  AMD64
processor                     Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
jina-resources                C:\projects\JINA\practice\venv\lib\site-packages\jina\resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)

**Screenshots**

**Comment by hanxiao** [comment]
We don't support Windows as written in the docs. You can use docker to run it on Windows
https://docs.jina.ai/chapters/install/via-pip.html#on-windows-and-other-os
