### ISSUE TITLE
Upgrade Uvicorn

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#4227]
We had to [pin Uvicorn to <=0.16.0](https://github.com/jina-ai/jina/blob/master/extra-requirements.txt#L30) because we saw hanging tests in CI.
Ideally this should not be necessary. Investigate why this happens, fix the root cause and allow usage of newer uvicorn versions.

**Comment by JoanFM** [comment]
this had tests failing, not only timeouts
