### ISSUE TITLE
Glb files missing in data/* when run 3d mesh search demo

### ISSUE THREAD

**Issue by Jecksu** [jina-ai/jina#4253]
hi, I am trying to run complete code of Search Similar 3D Meshes from https://docs.jina.ai/datatype/mesh/mesh-search/ . However i don't have protype rifle model in data/ and have no idea how to download them ? Is there any download link for these models?thanks:)

---

**Environment**

macos:12.2
python：3.9.10
conda:4.11.0
jina:2.2.2

**Comment by winstonww** [comment]
Hi @Jecksu , thanks for your interest. The rifle model is from the ShapeNet dataset [here](https://shapenet.org). You can directly download from the official website. Hope this helps.
