### ISSUE TITLE
Error with hello-world demo

### ISSUE THREAD

**Issue by YueLiu-jina** [jina-ai/jina#430]
**Describe your problem**

When I first run:
"docker run -v "$(pwd)/j:/j" jinaai/jina hello-world --workdir /j && xdg-open j/hello-world.html"
on Linux, I met an exception(below in the screenshot) and the program got stuck for about 10 minutes before I terminated it. When I run this code again, no exception and error occurred, and I got the correct html result.

In addition, there are warnings about a missing dependency called 'lz4' package. But missing this dependency didn't affect anything.

**What is your guess?**

---

**Environment**

Centos 7 on VMware 15.5 with Docker version 19.03.8

**Screenshots**

![exception](https://user-images.githubusercontent.com/64522311/82292504-9d0e3e80-99dd-11ea-9fff-9aef4c83e15f.png)
![lz4 package](https://user-images.githubusercontent.com/64522311/82292512-a26b8900-99dd-11ea-8b92-9b7ac0cb23a2.png)

**Comment by hanxiao** [comment]
- run again and see it is not reproducible
- for `lz4` and other dependencies, please refer to https://docs.jina.ai/chapters/install/via-pip.html#cherry-pick-extra-dependencies
