### ISSUE TITLE
co-op demo with mindspore

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#431]
**Describe the feature**
port one cv demo into jina using mindspore

**Your proposal**
ref. https://www.mindspore.cn/tutorial/en/master/advanced_use/computer_vision_application.html?highlight=feature

Implement two encoders, one in NLP, one in CV with Mindspore and add them to [the executor family](https://github.com/jina-ai/jina/tree/master/docs/chapters/101#family-of-executors) of Jina.

Would be great if anyone can provide some pretrained models, this will greatly speedup the dev process and onboarding for new developers.

| No. | Task Description | Issue ID |
| --- | ---------------- | -------- |
| 1   |    CV model           |          |
| 2   |   NLP model               |         |
| 3   |  Add a tutorial to [examples](https://github.com/jina-ai/examples)      |          |

---

**Environment**

**Screenshots**

**Comment by alexcg1** [comment]
Are we in touch with Mindspore already? If not I can reach out

**Comment by hanxiao** [comment]
The mindspore team is working on refactoring their modelzoo. Last time they suggested me to wait until their model zoo is stable. 

I'm in the mindspore TSC, we keep in good contact.

**Comment by nan-wang** [comment]
![image](https://user-images.githubusercontent.com/4329072/87768305-82760b80-c84e-11ea-86e1-95af116773bc.png)
OS X support is still missing from mindspore side.

**Comment by nan-wang** [comment]
Unfortunately, `mindspore.model_zoo` provides the implementations of various models rather than the trained models. One still needs to train the model. :(

Reference:
https://github.com/mindspore-ai/mindspore/tree/master/model_zoo

**Comment by hanxiao** [comment]
trained or no trained, it is just a checkpoint. We don't unit test those models anyway in Jina core. A simple `MindsporeModel` wrapper would be sufficient for accomplishing this issue.
