### ISSUE TITLE
add one audio encoder

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#432]
**Describe the feature**
wavenet, mfcc?

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by easwica** [comment]
hi @hanxiao , this is Halyna from AngelList (you responded to my application and answered that I need to make a pull request to a repo in order to proceed to the next steps of interview).
don't you mind if I'll take the implementation of wavenet encoder as the pull request for me to work on?

**Comment by hanxiao** [comment]
hi, yeah, sure please go ahead. I hope there is a pretrained model out there for wavenet, this will greatly speedup the dev-process.

**Comment by easwica** [comment]
great! I've already found one pertained model together with the code, https://github.com/r9y9/wavenet_vocoder , but looks like it's been a while since this repo was updated, hope everything works there and it will help ;)

**Comment by nan-wang** [comment]
> great! I've already found one pertained model together with the code, https://github.com/r9y9/wavenet_vocoder , but looks like it's been a while since this repo was updated, hope everything works there and it will help ;)

hi, there. The pretrained model is quite outdated and based on tf 1.x. You might need to use tfserving executor or wrap up everything into a docker image. We've just add support to wrap a tf serving client into an executor at [PR-414](https://github.com/jina-ai/jina/issues/414). Please refer to [jina-hub](https://github.com/jina-ai/jina-hub) for more information about docker images .
