### ISSUE TITLE
Add a ranker powered by text matching models

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#434]
**Describe the feature**

Add a ranker powered by text matching models 

**Your proposal**
- the ranker takes texts from query chunks and match chunks and call the model to calculate the matching scores

---

**Environment**

**Screenshots**

**Comment by avhirupc** [comment]
Do you mean something like [Deep Rank](https://arxiv.org/pdf/1710.05649.pdf) , which takes in query and document and outputs a relevance score for ranking? 

If not, Isn't this already supported in one of the examples?
* [https://github.com/jina-ai/examples/tree/master/southpark-search](url) where matching between query and document based distilbert embedding is already implemented & ranked based on cosine similarity

**Comment by celis** [comment]
.

**Comment by celis** [comment]
Hi @nan-wang,  can you provide more details about what you call  text matching models?, I see already implemented some tf-idf and bm25 rankers

**Comment by hanxiao** [comment]
i remove this feature from 0.4 as 
- not clear what does this mean
- 0.4 does not plan for this
