### ISSUE TITLE
Add "isolated hubble" tests to do integration test of core with hubble

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4352]
**Describe the feature**
We have a problem that we do not have proper e2e tests with `hubble`.

We should test the following user journey:

- Start a fake Hubble
- jina hub push
- jina hub pull 
- use it in Flow
- Make it work
- Other behavior we may want to test of interacting with core

**Comment by JoanFM** [comment]
Also `hubble` should make sure to run these `tests` before deploying a new version

**Comment by mapleeit** [comment]
Do you want that this test lives in core's codebase or an isolated place? @JoanFM 

We had this intergration test before. https://github.com/jina-ai/hub-integration/blob/main/.github/workflows/baseline-test.yml

**Comment by CatStark** [comment]
We should announce in slack core and Hubble if it fails. 
If it doesn't fails post it automatically in a different channel

**Comment by mapleeit** [comment]
Waiting for two slack webhooks for core and hubble. @deepankarm 
Otherwise it's done.

**Comment by mapleeit** [comment]
Done
