### ISSUE TITLE
index and search with PostgreSQL database

### ISSUE THREAD

**Issue by snaaz21** [jina-ai/jina#4370]
Hi,

I want to use the PostgreSQL database to do indexing and searching. 
If we have app.py, index_flow.yml, and search_flow.yml what should I add into these scripts to work with the database,

I tried (https://github.com/jina-ai/example-video-qa/tree/fix-versions) but faced the error given below:
`ValueError: could not broadcast input array from shape (1024,) into shape (768,)`

I am new to this, please suggest something here?

**Comment by JoanFM** [comment]
Hello @snaaz21 ,

You can check the option to use this `executor` from the `Hub` https://hub.jina.ai/executor/dvp0845a

so a Flow like this:


```python
from jina import Flow

f = Flow().add(...).add(uses='jinahub+docker://HNSWPostgresIndexer')
with f:
   ...
```

should do it

**Comment by snaaz21** [comment]
I tried indexing and searching by script given below:

`from jina import Flow, Document, DocumentArray
from hnswpsql import HNSWPostgresIndexer
f = Flow().add(uses=HNSWPostgresIndexer)

with f:
    resp = f.post(on='/index', inputs=DocumentArray([
                    Document(text='train passing by'),
                    Document(text='A printer'),
                    Document(text='Camel Sound'),
                    Document(text='Cat purring'),
                    Document(text='Cat Sound'),
                    Document(text='bicycle bell ringing')
                ]), return_results=True)
    print(f'{resp}')
    resp = f.post(on='/search', inputs=DocumentArray([
        Document(text='train passing by'),
        Document(text='A printer'),
        Document(text='Camel Sound'),
        Document(text='Cat purring'),
        Document(text='Cat Sound'),
        Document(text='bicycle bell ringing')
    ]), return_results=True)
    print(f'{resp}')`
    
    It is giving error given below:
    `executor-hnsw-postgres-0.6/executor/temp.py
⠋ 0/2 waiting executor0 gateway to be ready...   psql_indexer@32719[W]:No data in PSQL to sync into HNSW. Skipping
HnswlibSearcher@32719[W]:No data received in HNSW.sync. Skipping...
HNSWPostgresIndexer@32719[I]:Rebuilt HNSW index with 0 docs
           Flow@32701[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:42783
	🔒 Private network:	172.20.10.3:42783
[<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 139752971179064>]
ef_query:  50
limit: 10
      executor0@32719[E]:AttributeError("'NoneType' object has no attribute 'shape'")
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 226, in _handle
    peapod_name=self.name,
  File "/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 165, in handle
    field='groundtruths',
  File "/lib/python3.7/site-packages/jina/executors/__init__.py", line 194, in __call__
    self, **kwargs
  File "/lib/python3.7/site-packages/jina/executors/decorators.py", line 106, in arg_wrapper
    return fn(*args, **kwargs)
  File "/executor-hnsw-postgres-0.6/executor/hnswpsql.py", line 350, in search
    self._vec_indexer.search(docs, parameters)
  File "/executor-hnsw-postgres-0.6/executor/hnswlib_searcher.py", line 139, in search
    if embeddings_search.shape[1] != self.dim:
AttributeError: 'NoneType' object has no attribute 'shape'
[<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 139752971180072>]

Process finished with exit code 0
`

It is not saving embedding nad co info in the database, the screenshot of the table is attached below;
![IMG_2062](https://user-images.githubusercontent.com/28730512/154980797-02a61add-bd68-4340-bb40-25a7c9490a31.jpg)

**Comment by JoanFM** [comment]
You need `embeddings` in your `Documents`, otherwise the `HNSW` index cannot be built

**Comment by snaaz21** [comment]
Hi,

I tried image search from audio using database, scripts are given below;

**app_db.py**

`from jina.types.document.generators import from_files
from jina import DocumentArray, Flow
import os
import glob
from jina import Document


def input_docs(data_path):
    for fn in glob.glob(os.path.join(data_path, '*')):
        doc = Document(uri=fn, tags={'filename': fn})
        doc.load_uri_to_image_blob()
        yield doc

def check_query(resp):
    for d in resp.docs:
        print(f'\ninput_audio: {d.uri}, len-of-chunks:{len(d.chunks)}')
        for m in d.matches:
            print(f'score: {m.scores["cosine"].value:.6f}, {m.uri}')


def main():
    docs_test = DocumentArray(from_files('AudioCLIP/demo/audio/*.wav'))

    f = Flow.load_config('flow_index_db.yml')

    print('f: ', f)
    with f:
        resp= f.post(on='/index', inputs=input_docs('/home/saima/Projects/R_And_D/AudioCLIP/demo/images'), return_results=True)
        print(f'{resp}')

    print('Indexing completed...')

    f = Flow.load_config(('flow_search_db.yml'))
    with f:
        print('Starting searching...')
        f.post(on='/search', inputs=docs_test, on_done=check_query)

if __name__ == '__main__':
    main()
    `

**flow_index_db.yml**
jtype: Flow
version: '1'
executors:
 - name: 'image_encoder'
   uses: AudioCLIPImageEncoder
   py_module : 'AudioCLIPImageEncoder/executor/audioclip_image.py'
 - name: 'indexer'
   uses: HNSWPostgresIndexer
   py_modules: 'executor-hnsw-postgres-0.6/executor/hnswpsql.py'
   install_requirements: True
   uses_with:
     total_shards: 1
     startup_sync: False
     port: 5432
     username: 'postgres'
     password: '123456'
     database: 'postgres'
     table: 'kv_indexer'
   needs: 'image_encoder'

**flow_search_db.yml**
jtype: Flow
version: '1'
executors:
  - name: 'audio_segmenter'
    uses: AudioSegmenter
    uses_with:
      window_size: 4
      stride: 2
    py_modules:
      - executors.py
  - name: 'audio_encoder'
    uses: AudioCLIPEncoder
    py_module : 'AudioCLIPEncoder/executor/audio_clip_encoder.py'
    uses_with:
      traversal_paths: 'r'
    needs: 'audio_segmenter'
  - name: 'indexer'
    uses: HNSWPostgresIndexer
    py_modules: executor-hnsw-postgres-0.6/executor/hnswpsql.py
    install_requirements: True
    uses_with:
      total_shards: 1
      startup_sync: False
      port: 5432
      username: 'postgres'
      password: '123456'
      database: 'postgres'
      table: 'kv_indexer'

By using the above **app_db.py** script I am able to do indexing, the screenshot of the table is attached below;
![emd_db](https://user-images.githubusercontent.com/28730512/155082559-1ece0ae7-3d76-455e-85ef-46a9c8f8e97d.jpg)



But while searching, it is throwing the below error; why is that so?

virtualenvs/jina_env_2.5.4/bin/python3.7 R_And_D/audio-image-ir/app2_db.py
f:  <jina.flow.base.Flow object at 0x7f94184999e8>
⠙ 1/3 waiting image_encoder indexer to be ready...    psq_handler@15196[I]:Using existing table
⠼ 2/3 waiting image_encoder to be ready...UserWarning: Failed to load image Python extension: virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/image.so: undefined symbol: _ZNK2at10TensorBase21__dispatch_contiguousEN3c1012MemoryFormatE (raised from virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/io/image.py:11)
⠸ 2/3 waiting image_encoder to be ready...UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum. (raised from virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/transforms/transforms.py:288)
           Flow@15177[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:50721
	🔒 Private network:	172.20.10.3:50721
UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.) (raised from virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/transforms/functional.py:126)
[<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 140274008683576>]
Indexing completed...
⠹ 1/4 waiting audio_segmenter audio_encoder indexer to be ready...    psq_handler@15266[I]:Using existing table
⠏ 3/4 waiting audio_encoder to be ready...UserWarning: Failed to load image Python extension: virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/image.so: undefined symbol: _ZNK2at10TensorBase21__dispatch_contiguousEN3c1012MemoryFormatE (raised from virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torchvision/io/image.py:11)
           Flow@15177[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:46061
	🔒 Private network:	172.20.10.3:46061
	🌐 Public address:	None:46061
Starting searching...
UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.) (raised from R_And_D/audio-image-ir/AudioCLIPEncoder/executor/audio_clip_encoder.py:99)
UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.) (raised from virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/torch/nn/functional.py:718)
ef_query:  50
limit: 10
        indexer@15266[E]:ValueError('Query documents have embeddings with dimension 1024, which does not match the dimension of the index (0)')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 285, in _msg_callback
    processed_msg = self._callback(msg)
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 271, in _callback
    msg = self._post_hook(self._handle(self._pre_hook(msg)))
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 226, in _handle
    peapod_name=self.name,
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 165, in handle
    field='groundtruths',
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/executors/__init__.py", line 194, in __call__
    self, **kwargs
  File "virtualenvs/jina_env_2.5.4/lib/python3.7/site-packages/jina/executors/decorators.py", line 106, in arg_wrapper
    return fn(*args, **kwargs)
  File "R_And_D/audio-image-ir/executor-hnsw-postgres-0.6/executor/hnswpsql.py", line 350, in search
    self._vec_indexer.search(docs, parameters)
  File "R_And_D/audio-image-ir/executor-hnsw-postgres-0.6/executor/hnswlib_searcher.py", line 141, in search
    'Query documents have embeddings with dimension'
ValueError: Query documents have embeddings with dimension 1024, which does not match the dimension of the index (0)

Process finished with exit code 0

**Comment by JoanFM** [comment]
Hey @snaaz21 ,

Would you mind trying to set `startup_sync` parameter to `True` in the `flow-search`?

**Comment by snaaz21** [comment]
by setting up `startup_sync` to `True` in the `flow_search`, error coming below;

jina_env_2.5.4virtualenvs/jina_env_2.5.0/bin/python3.7 jina_env_2.5.4R_And_D/audio-image-ir/app2_db.py
f:  <jina.flow.base.Flow object at 0x7f4274ed1588>
⠼ 2/3 waiting image_encoder to be ready...UserWarning: Failed to load image Python extension: jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/image.so: undefined symbol: _ZNK2at10TensorBase21__dispatch_contiguousEN3c1012MemoryFormatE (raised from jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/io/image.py:11)
⠹ 2/3 waiting image_encoder to be ready...UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum. (raised from jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/transforms/transforms.py:288)
           Flow@18349[I]:🎉 Flow is ready to use!
	🔗 Protocol: 		GRPC
	🏠 Local access:	0.0.0.0:35037
	🔒 Private network:	172.20.10.3:35037
UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.) (raised from jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/transforms/functional.py:126)
[<jina.types.request.Response ('request_id', 'data', 'header', 'routes', 'status') at 139923375600696>]
Indexing completed...
⠹ 1/4 waiting audio_segmenter audio_encoder indexer to be ready...    psq_handler@18436[I]:Using existing table
⠸ 1/4 waiting audio_segmenter audio_encoder indexer to be ready...        indexer@18436[C]:can not load the executor from HNSWPostgresIndexer
        indexer@18436[E]:ExecutorFailToLoad() during <class 'jina.peapods.runtimes.zmq.zed.ZEDRuntime'> initialization
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 78, in _load_executor
    extra_search_paths=self.args.extra_search_paths,
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/jaml/__init__.py", line 613, in load_config
    return JAML.load(tag_yml, substitute=False)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/jaml/__init__.py", line 90, in load
    r = yaml.load(stream, Loader=JinaLoader)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/jaml/__init__.py", line 452, in _from_yaml
    return get_parser(cls, version=data.get('version', None)).parse(cls, data)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/jaml/parsers/executor/legacy.py", line 73, in parse
    runtime_args=data.get('runtime_args', {}),
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/executors/decorators.py", line 60, in arg_wrapper
    f = func(self, *args, **kwargs)
  File "jina_env_2.5.4R_And_D/audio-image-ir/executor-hnsw-postgres-0.6/executor/hnswpsql.py", line 132, in __init__
    self._sync()
  File "jina_env_2.5.4R_And_D/audio-image-ir/executor-hnsw-postgres-0.6/executor/hnswpsql.py", line 208, in _sync
    self._vec_indexer.index_sync(iterator, batch_size)
  File "jina_env_2.5.4R_And_D/audio-image-ir/executor-hnsw-postgres-0.6/executor/hnswlib_searcher.py", line 373, in index_sync
    this_batch_embeds[this_batch_size] = vec
ValueError: could not broadcast input array from shape (1024) into shape (0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/peapods/peas/__init__.py", line 81, in run
    cancel_event=cancel_event,
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/peapods/runtimes/zmq/zed.py", line 72, in __init__
    self._data_request_handler = DataRequestHandler(self.args, self.logger)
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 67, in __init__
    self._load_executor()
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/peapods/runtimes/request_handlers/data_request_handler.py", line 91, in _load_executor
    raise ExecutorFailToLoad from ex
jina.excepts.ExecutorFailToLoad
⠋ 2/4 waiting audio_encoder indexer to be ready...UserWarning: Failed to load image Python extension: jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/image.so: undefined symbol: _ZNK2at10TensorBase21__dispatch_contiguousEN3c1012MemoryFormatE (raised from jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/torchvision/io/image.py:11)
           Flow@18349[E]:Flow is aborted due to ['indexer'] can not be started.
Traceback (most recent call last):
  File "jina_env_2.5.4R_And_D/audio-image-ir/app2_db.py", line 55, in <module>
    main()
  File "jina_env_2.5.4R_And_D/audio-image-ir/app2_db.py", line 44, in main
    with f:
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/flow/base.py", line 1126, in __enter__
    return self.start()
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/flow/base.py", line 1175, in start
    self._wait_until_all_ready()
  File "jina_env_2.5.4virtualenvs/jina_env_2.5.0/lib/python3.7/site-packages/jina/flow/base.py", line 1259, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart

Process finished with exit code 1

**Comment by JoanFM** [comment]
Could u share some small set of data for us to reproduce on our end?

**Comment by snaaz21** [comment]
> Could u share some small set of data for us to reproduce on our end?

I am using the dataset is inside audio and images dataset folder from [AudioClip](https://github.com/AndreyGuzhov/AudioCLIP/tree/master/demo)

**Comment by numb3r3** [comment]
Hey @snaaz21 

Could you try to explicitly specify the dimension (`dim: 1024`)  in the flow search yaml:
```
uses_with:
      total_shards: 1
      startup_sync: True
      dim: 1024
      port: 5432
      username: 'postgres'
      password: '123456'
      database: 'postgres'
      table: 'kv_indexer'
```

**Comment by snaaz21** [comment]
> 

yes it worked, Thanx

**Comment by snaaz21** [comment]
For another type of dataset for the neural, for that also Do I need to specify the dimensions explicitly?

**Comment by numb3r3** [comment]
yes, it is required to explicitly specify the dimension num

**Comment by snaaz21** [comment]
> Hey @snaaz21 can we then considered this issue solved?

yes, I am closing the issue
