### ISSUE TITLE
Switch like mechanism

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4372]
**Describe the feature**

a missing feature in the core, a conditioning .switch
```
.add(...)
.switch({
   'some_filter_syntax_e_g_on_mime_type_equals_jpg': similar_to_add_args_to_make_an_executor1,  # case 1: executor
   'some_filter_syntax_e_g_on_mime_type_equals_text': similar_to_add_args_to_make_an_executor2,  # case 2: executor
})
.add()

```

It would be very useful to have a `switch-like` mechanism to allow branches of a Flow to only get substet of `Documents` without needing to add "artifitical" filters.

```python
from jina import Flow

filter1 = {}
f = Flow().add(name='exec1').add(name='exec2', needs='exec1').add(name='exec3', needs = ('exec1', filter1))
```

Steps to be done in DocArray:
 1 - Implement and document an official Query Language (I suggest the one from PQLite)

Steps to be done in Core:

0 - Describe YAML interface to set these `needs` => This may affect the Pythonic interface decision
Option 1: Solution in Gateway:
 1 - Add conditions argument to gateway parser that is a dictionary to `executor_name` -> Filter dict:
 2 - Make sure Flow fills this condition when starting gateway (or when dumping to k8s or docker compose)
 3 - Add in TopologyGraph condition in each node
 4 - In _wait_previous_and_send, apply conditions if needed

Option 2: Solution in Gateway:
 1 - Add condition argument to runtime
 2 - Make sure Flow fills this condition when starting executor (or when dumping to k8s or docker compose)
 3 - Add filter application in DataRequestHandler before calling `Executor` method

Properly document the new feature

Logic in Executor
UPVOTE:
 - Easier to implement
 - Gateway remains clean (No dependency, no serialization)
 - Configuration lives where it makes sense

WEAK POINTS:
 - Bandwith?????: Why receive things I do not care
 - Expressiveness when External Exectutor is used (I may not know how people want to call me)

Logic in Gateway:
UPVOTE:
 - Total expressiveness with External Included
 - Bandwith, do not send what does not need to be sent

 WEAK POINT:
  - Gateway adds dependency
  - Gateway needs serialization/deserialization

Create a new Pod that will get all the filterings
UPVOTE:
 - Keeps all the expressiveness of the option of the gateway
 - Does not add a dependency on Gateway

 WEAK POINT:
  - Does not solve extra seri/deserialization
  - Adds more entities to the game (another point of failure ...)

**Comment by hanxiao** [comment]
order-preserving problem as pointed in https://github.com/jina-ai/docarray/issues/125#issuecomment-1049512586

and potential solution as discussed in the meeting
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/2041322/155504630-b666e05b-df56-4d3d-8101-308aa454e337.png">
