### ISSUE TITLE
Docs CD should be triggered on release and not on push

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4397]

**Comment by JoanFM** [comment]
What is the problem here? Can you add more details?

**Comment by samsja** [comment]
regarding @jacobowitz issue https://github.com/jina-ai/jina/pull/4384/commits where he need to wait for 3.1 to update the docs. I need to investigate what is going on but it seems than some docs are deployed even without release just on push

**Comment by JoanFM** [comment]
Some docs are released manually by me by running a custom github action.
