### ISSUE TITLE
Improve Documentation on Flow YAML configuration

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4415]
**Describe the feature**
We need better documentation on Flow YAML , and add `load_config` and `save_config` as primary API methods of Flow

**Comment by iamhardikat11** [comment]
Can you describe more about this issue?

**Comment by soma2000-lang** [comment]
@JoanFM  I am working on this issue, please assign me this

**Comment by JoanFM** [comment]
Hey @soma2000-lang ,

Someone in the team is already working on it, but if you have something to commit, feel free to share. But I guess is going to be hard for an external contributor to provide detailed explanation

**Comment by soma2000-lang** [comment]
@JoanFM  I want to try and proper give a pr within 2 days
