### ISSUE TITLE
add an indexer saving id-protobuf to key-value databases

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#442]
**Describe the feature**
add an indexer saving id-pb to key-value databases with multi-thread. Currently, the python wrapper of `leveldb` don't have full features and doesn't support multi-thread. 

**Your proposal**
A better way would be wrapping up a database client into the indexer. This can also quickly be generalized to other key-value databases.

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
multi-thread IO is confusing, on HDD it is always one W/R at a time.

**Comment by hanxiao** [comment]
i remove this from 0.4, as
- not clear what does this mean
- not in the plan
