### ISSUE TITLE
A spelling mistake on the website

### ISSUE THREAD

**Issue by Raxtz** [jina-ai/jina#4440]
**Describe the bug**

There is a spelling mistake on the website https://learn.jina.ai/beginner/.
"DocumentaArray" should be "DocumentArray".

---

**Screenshots**

![1646649033(1)](https://user-images.githubusercontent.com/57084600/157014582-8e5abcf6-8a14-4f92-b895-46069de2e4c3.png)

**Comment by Rushijaviya** [comment]
One more spelling mistake is there.
"Pythorch" should be "PyTorch"

![Screenshot 2022-03-07 195041](https://user-images.githubusercontent.com/59735978/157051995-7ffa37a8-e558-4d36-a373-b91083e8297a.png)

**Comment by alexcg1** [comment]
Thanks @Raxtz @Rushijaviya ! @Shubhamsaboo assigning this to you bud!

**Comment by Palakvlog** [comment]
Hi, I am  Palak Goyal a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.
Thank you.

**Comment by Shubhamsaboo** [comment]
Hey @Raxtz, thanks for pointing it out! 

@Palakvlog the issue has been taken care of and resolved! Thank you for your interest! 

Please keep an eye on other open issues.
