### ISSUE TITLE
Enhancing the search feature     type/feature-request

### ISSUE THREAD

**Issue by thanusree182** [jina-ai/jina#4456]
**Describe the feature**
I did not witness this search feature in any search engine I have used, but I wish It would help a lot. My idea is that a person should be able to search text present in the image when an image is given as input.
**Screenshots**
![Screenshot (502)](https://user-images.githubusercontent.com/86425534/157472026-fd7fc246-65f7-4e68-b585-1cac244c5555.png)

In the above screenshot, I want to search for text present in the image, but rather it is searching for similar images. I feel it would be helpful if we could add this new feature.

**Comment by SHIKHER09** [comment]
hello, Can I work on it

**Comment by thanusree182** [comment]
Yes, currently I am not working on it.
