### ISSUE TITLE
Project Idea: Graphic Illustration Search

### ISSUE THREAD

**Issue by induviduality** [jina-ai/jina#4457]
**Describe your proposal/problem**

**Pain point:**
Designers, especially aspiring designers, use Illustrations and graphics that are freely available online for their UI designs. Although, finding an apt illustration for your design is hard. Not always are the illustrations available as complete sets. Hence, designers spend a lot of time looking for illustrations that are the closest match to the styles they have adopted in their design. It is not assured that the designer may find the closest, most ideal match that they need either. This may lead to UI elements looking out of place and not as pleasing as it could be.

**Solution and Project Idea:**
The idea is to build an app that searches for digital graphics and illustrations using Jina's image search. Through the app, users must be able to search using the image of an illustration as reference. Jina would then pull up images of similar styles and colour schemes as the reference image via Image-to-Image search.

**Comment by sadab-halim** [comment]
Hi, I am Sadab Halim, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you
