### ISSUE TITLE
Annoy or Faiss examples

### ISSUE THREAD

**Issue by AnShengqiang** [jina-ai/jina#446]
**Describe the feature**
I tried default index on 1000000 data, it is slow🥺.
I want to use annoy or faiss to speed up🙋, but don't know how to start🥺. 
Maybe an example (or just a YAML file) about faiss or annoy will be great, thanks🙏.

**Comment by hanxiao** [comment]
1. please understand the index speed and query speed are two different things, read https://github.com/jina-ai/jina/issues/356#issuecomment-632562190 and I'd like to remind you change it to Annoy at index time will *not* speed up.
2. Use AnnoyIndexer
```yaml
!AnnoyIndexer
with:
      index_filename: vec.gz
```

Please refer to [examples](https://learn.jina.ai) and docs on how to use the this YAML, e.g. in Flow, Pods 

https://docs.jina.ai/chapters/yaml/yaml.html
https://docs.jina.ai/chapters/yaml/yaml.html#compoundexecutor-yaml-syntax
https://docs.jina.ai/chapters/flow/README.html

**Comment by AnShengqiang** [comment]
@hanxiao Thanks, that helps a lot! ♪(･ω･)ﾉ
