### ISSUE TITLE
[FR] Make uvloop optional so that jina can work in Windows?

### ISSUE THREAD

**Issue by eterna2** [jina-ai/jina#4481]
uvloop is not supported in windows, and is not a requirement for asyncio - it is just an accelerator. 

Is it possible to make `uvloop` an optional dependencies? i.e. `pip install jina[uvloop]` so that jina can be installed in windows environment?

**Comment by JoanFM** [comment]
It is already not needed. Install on Windows works. If it does not work for you please report what are the issues being seen
