### ISSUE TITLE
renaming input_condition to when

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#4490]
i notice the new switch use `input_condition` (btw our `.post` use plural `inputs` as arg, so a bit inconsistency here) as the syntax, which seems a bit long to me, how about just **`when`** ?

so you will have:
```python
 .add(..., when={})
```

it is still early as 3.2 just release <24h and no one has adopted it yet so changing it won't have too much aftermath. it maybe painful but comparing to doing it later, much easier

Ref: https://jinaai.slack.com/archives/C018F60RBL5/p1647418227903129

**Comment by JohannesMessner** [comment]
Good point, I thought about this too, and ultimately went for clarity over brevity.

I like `when` a lot, nice and short, and it implicitly tells the user that the filter will be applied to the input. Just one concern:

- We want users to intuitively realize that the features are closely related to the feature in DocArray and that it uses the same QL, and there in the docs it is called `condition`. The inconsistency between the two could be confusing.

If we're okay with that then I am happy to change it.
