### ISSUE TITLE
JEP-3 for multimodal search

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#450]
**Describe the feature**
make a draft for supporting multimodal search

**Your proposal**
check details at [issue-357](https://github.com/jina-ai/jina/issues/357
)
---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
This JEP is over ambitious, and it needs to be decomposed into two JEPs: first MIME support, second MIME multipart support. The latter could map to the multimodal search.

As a side-effect, the ingest API/gateway may change as well.

I'm drafting the first step.
