### ISSUE TITLE
Expose Executor as a Service as First class citizen in Documentation.

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4502]
**Describe the feature**
Right now we have added `Executor.serve` method and we are seeing increasing interest in serving a single `Executor` as an isolated service.

After `Head` is removed as a result of the `service mesh` introduction, this will be even more performant, and `gateway` remains a useful entity in the picture. 

I think code-wise perspective, I belive the only needed thing is to add a method `Executor.to_k8s_yaml()` and `Executor.to_docker_compose_yaml` that under the hood create a simple `Flow` and call its `to_*` method.

The main work would be in documentation and storytelling about exposing this as a first-class option of `Jina`.

**Comment by JoanFM** [comment]
Blocked by #4503

**Comment by JohannesMessner** [comment]
Seems like a good thing to do.
I see some conceptual overlap with external Executors, and we probably need to be careful to make the distinction clear.

**Comment by JoanFM** [comment]
> Seems like a good thing to do. I see some conceptual overlap with external Executors, and we probably need to be careful to make the distinction clear.

Good point, did not think about it, but it would be the biggest blocker

**Comment by jacobowitz** [comment]
Let's restrict this for now to gRPC? Otherwise it will be more complicatd to integrate as external Executor

**Comment by JohannesMessner** [comment]
> Let's restrict this for now to gRPC? Otherwise it will be more complicatd to integrate as external Executor

Makes sense. Remind me, did we land on `serve`d executors being the only recommended way of doing external Execs from now on?

**Comment by JohannesMessner** [comment]
> Also we may want to think about exposing serve as part of CLI? 
Agree

**Comment by jacobowitz** [comment]
We somehow should be able to deploy this with and without a gateway?
