### ISSUE TITLE
Wrong link on learn.jina.ai

### ISSUE THREAD

**Issue by ZiniuYu** [jina-ai/jina#4523]
**Describe your proposal/problem**

---

https://learn.jina.ai/beginner

Under the "Manipulate Data with DocArray" part in the beginner section of Jina tutorial, there is a link to images demo which seems wrongly configured to audio demo. 🤣

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/21340127/159435031-185a05c3-d26b-4cad-a8f7-4a6a3abca7f7.png)

**Comment by hanxiao** [comment]
is there a progress on it?

**Comment by ZiniuYu** [comment]
Was fixed here-> https://github.com/jina-ai/learning-portal/pull/55#issue-1187704765
