### ISSUE TITLE
add jina health check to jina ping

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4544]
We want user to be able to use the jina health checks as now it is only a internal tools.

- [ ] document the jina health checks
- [ ] merge jina health check and jina ping (see further)

**Comment by startakovsky** [comment]
@samsja What is this issue? I assume I cannot join slack, but I would be interested in familiarizing myself with these issues as I'm considering contributing here.

**Comment by samsja** [comment]
Hey, we are glad that you want to contribute ! You can definitely work on this issue if you want to

To give you some context:

We recently added some health check to jina ( see here) : https://github.com/jina-ai/jina/blob/84089a0287933ec07b165d32498abc92d6f95898/jina/resources/health_check/gateway.py#L33)
For example if you have setup a flow you can check if it is healthy by doing the following command:

```python
from jina import Flow, Client

if __name__ == '__main__':
    f = Flow(port=12345).add()
    with f:
        f.block()

```

```bash
python -m jina.resources.health_check.gateway localhost:12345 grpc
```

At the same time we have a `ping` option in the cli which kind of doing the same things so we would like the fuse both functionality so that 

```bash
jina ping localhost 12345 
```
call the health check under the hood:

it means that the `NetworkChecker` here https://github.com/jina-ai/jina/blob/84089a0287933ec07b165d32498abc92d6f95898/jina/checker.py#L6 need to be rewrite so that the ping command https://github.com/jina-ai/jina/blob/84089a0287933ec07b165d32498abc92d6f95898/cli/api.py#L120 is up to date with the health checking


Let me know if you want to work on this issue and if you need any help

**Comment by samsja** [comment]
This tickets is out of dated since the last health check PR https://github.com/jina-ai/jina/pull/4848
