### ISSUE TITLE
Early fail of a Flow if one of the executor fails

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#4563]
The following logs show a behavior where the gateway is failed because of a conflict of port; yet the CLIP executor is still spawning and loading (downloads tons of data and would take 1min); Finally the Flow complains about the failed gateway and abort it. 

Then why don't we cancel the CLIP executor loading and the whole Flow immediately?

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/2041322/160804821-f1da195e-81b8-4865-88e6-020e6ffe7ebf.png">

Expected behavior:
- All executors including Gateway starts in parallel
- Cancel every parallel job if anyone is failed. One fails, fails the whole flow.

I remember I implemented this part from spawning executors one-by-one to spawning all executors in parallel. We still want the latter behavior. It is much faster. Yet, I suggest we add early-stop to save time on loading big flow.

**Comment by JoanFM** [comment]
The current behavior is:

- All Pods, including Gateway are spawned.
- The main process (the Flow one) starts a Thread checking the status of the pods.
- When the thread finishes, if one of the Pods fails to start, it cancels all the rest.

We can be faster and more reactive at finishing after an Exception found
