### ISSUE TITLE
gateway proactively sends request that will be rejected by executor

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#4576]
```python
from jina import Flow, Executor, requests


class MyExec1(Executor):

    @requests(on='/m1')
    def foo(self, **kwargs):
        print(self.__class__)


class MyExec2(Executor):

    @requests(on='/m2')
    def foo(self, **kwargs):
        print(self.__class__)


f = Flow().add(name='m1', uses=MyExec1).add(name='m2', uses=MyExec2, needs='gateway').needs_all()

with f:
    f.post('/m2')
```

and I get
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/2041322/161492122-a8c0bcf0-1eb9-4b75-9c0f-90e08c3dca2c.png">

which basically says the request is also sent to `m1` and got rejected at `m1`, which is unnecessary for gateway to send it in the first place.

I would expect the gateway keeps a registry of Executors' endpoints, and before sending first check if it is necessary. Otherwise it introduces extra latency.

## Background

I want to route request differently according to the user request's `parameters`. However, this feature is not there according to  https://docs.jina.ai/how-to/flow-switch/ and I come up with the above workaround, which turns out also suboptimal.

**Comment by JoanFM** [comment]
I do not agree, it is impossible almost and not very cloud native for gateway to have so much details about the Executors Endpoints. They live totally isolated from each other

**Comment by jacobowitz** [comment]
yes the problem here is that the routes are defined on the Executor level. That information is not available at Gateway level, because its part of the Executor's code and not the Flow's configuration.
In some cases this could be achived by tricks, but if the Executor is containerized, the Gatewa most likely does not even have a way of accessing the code and check the routes.

**Comment by JoanFM** [comment]
Also, in Kubernetes, u may do a `Rolling Update` updating the configuration of the Executor, which could change this configuration and then gateway would be out of sync. I would suggest closing this issue, and think only about the filter by parameters.
