### ISSUE TITLE
Support Flow filter feature on things other than the `inputs`, such as `parameters`.

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/jina#4577]
how can i implement condition by parameters in Jina core? I guess I can't by reading this https://docs.jina.ai/how-to/flow-switch/
Then this feature seems incomplete to me.
Background, i want to route request differently according to the user request's parameters.

https://jinaai.slack.com/archives/C01C8DRQHFW/p1648971576484009

**Comment by hanxiao** [comment]
needs further thinking before action

**Comment by JoanFM** [comment]
I would not act upon it until clearer need from community or project
