### ISSUE TITLE
Gateway error: received an empty stream from the client

### ISSUE THREAD

**Issue by Jackal1586** [jina-ai/jina#4593]
**Description**

I encountered an error in ```flow.post``` method while trying to run ```python app.py -t index``` in **multires-lyrics-search** after cloning this repository: [examples](https://github.com/jina-ai/examples). The error message was: ```gateway@61291[E]:receive an empty stream from the client! please check your client's inputs, you can use "Client.check_input(inputs)"```. 

---

**Environment**

- jina 2.0.18
- jina-proto 0.0.85
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.5
- protobuf 3.20.0
- proto-backend cpp
- grpcio 1.44.0
- pyyaml 6.0
- python 3.7.13
- platform Linux
- platform-release 5.10.105-1-MANJARO
- platform-version #1 SMP PREEMPT Fri Mar 11 14:12:33 UTC 2022
- architecture x86_64
- processor
- uid 5025763201072
- session-id 7d472a12-b722-11ec-a806-049226d49030
- uptime 2022-04-08T15:58:49.863145
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
* JINA_MP_START_METHOD (unset)

**Comment by JoanFM** [comment]
My guess is that the paths are not well set and then nothing is being sent through the client

**Comment by Jackal1586** [comment]
Can you please specify which paths you meant here?

**Comment by hanxiao** [comment]
jina is probably too old?

**Comment by Jackal1586** [comment]
I tried this one:

Environment:
- jina 2.6.4
- docarray 0.0.4
- jina-proto 0.1.0
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.22.3
- protobuf 3.20.0
- proto-backend cpp
- grpcio 1.44.0
- pyyaml 6.0
- python 3.8.13
- platform Linux
- platform-release 5.10.105-1-MANJARO
- platform-version #1 SMP PREEMPT Fri Mar 11 14:12:33 UTC 2022
- architecture x86_64
- processor
- uid 5025763201072
- session-id 03fb9b4e-b730-11ec-8402-049226d49030
- uptime 2022-04-08T17:35:39.404769
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)


Error: ModuleNotFoundError: Dependencies listed in requirements.txt are not all installed locally, this Executor may not run as expect. To install dependencies, add `--install-requirements` or set `install_requirements = True`

-------------------------------------------------------

Couldn't try `jina~=3.0` as it didn't satisfy `jina-commons`'s requirement.

Am I missing something here?

**Comment by JoanFM** [comment]
Hey @Jackal1586 ,

As u see in the requirements, the multires-lyrics-search is requiring `jina[standard]==2.0.18`. Have u tried with this version?

**Comment by JoanFM** [comment]
But most importantly, have you run the preliminary steps to make sure that the `dataset` is downloaded correctly and placed in the expected path?

**Comment by JoanFM** [comment]
Hey @Jackal1586 , could you try putting some printline in this line https://github.com/jina-ai/examples/blob/d8f903278597254bd96b1ed64fe8c9feefaa265c/multires-lyrics-search/helper.py#L11 and check what is the path it is searching for? And validate there is indeed data in that folder?

**Comment by JoanFM** [comment]
Can you make sure that there is at lease one document being generated? Like does this generator even `yields` once?

**Comment by Jackal1586** [comment]
It yielded nothing, I put a counter there. The counter value is `0`.

**Comment by JoanFM** [comment]
This is now related to the `version` problem.

**Comment by JoanFM** [comment]
You are working with a version of Jina that does not match the one expected by the `Executor`

**Comment by Jackal1586** [comment]
I see. Thank you for the guidance. Now which version should I go for? Any version above `2.6.4` gave me error about `jina-commons`'s dependency is not resolved.

**Comment by JoanFM** [comment]
I believe, what you need is to fix the versions of every Hub Executor to an older version that is not on 3.0

**Comment by Jackal1586** [comment]
Ok, let me try this. I will post update on this issue after doing this change.

**Comment by Jackal1586** [comment]
After lot of trail and error, I did the following acts. 

I tried to change Hub Executor versions in `flows/index..yml` according to [these instructions](https://docs.jina.ai/fundamentals/flow/create-flow/?highlight=flow%20yml). I cloned [Sentencizer](https://github.com/jina-ai/executors/tree/main/jinahub/segmenters/Sentencizer), [TransformerTorchEncoder](https://github.com/jina-ai/executor-text-transformers-torch-encoder), and [SimpleIndexer](https://github.com/jina-ai/executor-simpleindexer). And reverted to commit before the "migrating to 3.0" related commits.  

The `flows/index..yml` looks as following:

```
jtype: Flow # We define the flow used for indexing here
version: '1' # yml version
with: # Parameters for the flow
    workspace: $JINA_WORKSPACE # Workspace folder
executors: # Now, define all the executors that are used
    - name: segmenter # The first executor splits the input text into sentences which are stored as chunks in the original documents
      uses: MySentencizer # The type of the executor is Sentencizer, we download it from the hub as a docker container
      py_modules: /home/zarzis/code/python/examples/multires-lyrics-search/deps/executors/jinahub/segmenters/Sentencizer/sentencizer.py
    - name: encoder # Then, compute the embeddings of the sentences in this executor
      uses: TransformerTorchEncoder #'/data/sbmaruf/zarzis/examples/multires-lyrics-search/executor-text-transformers-torch-encoder'          # We use a TransformerTorchEncoder from the hub
      py_modules: /home/zarzis/code/python/examples/multires-lyrics-search/deps/executor-text-transformers-torch-encoder/transform_encoder.py
      volumes: '~/.cache/huggingface:/root/.cache/huggingface' # Mount the huggingface cache into the docker container
      uses_with: # Override some parameters for the executor
          pooling_strategy: 'cls' # This is the pooling strategy that is used by the encoder
          pretrained_model_name_or_path: distilbert-base-cased # The ML model that is used
          max_length: 96 # Max length argument for the tokenizer
          device: 'cpu' # Run the executor on CPU - For GPU, we would have to use another container!
          default_traversal_paths: ['c'] # Compute the embeddings on the chunk level - the sentences created before
    - name: indexer # Now, index the sentences and store them to disk.
      uses: SimpleIndexer # We use a simple indexer for that purpose (not in docker, but using source codes - there are some bugs with docker for this executor)
      py_modules: /home/zarzis/code/python/examples/multires-lyrics-search/deps/executor-simpleindexer/executor.py
      uses_metas: # Set some meta arguments for this executor
          workspace: $JINA_WORKSPACE # Define the workspace folder for the executor
      uses_with: # Override parameters for the executor
          default_traversal_paths: ['c'] # Store the sentences on disk - this means on chunk level
    - name: root_indexer # Additionally to the sentences, we also need to store the original songs which are not split into sentences
      uses: 'jinahub+docker://LMDBStorage' # Therefore, we use a LMDBStorage indexer
      volumes: $JINA_WORKSPACE_MOUNT # Again, mount the workspace
      uses_with: # Override some parameters for the LMDBStorage
          default_traversal_paths: ['r'] # Now, we store the root documents, not the sentence chunks
      needs: [gateway] # We can start this at the beginning - in parallel to the sentence flow
    - name: wait_both # Now, we wait for both the root indexing and the sentence path to finish
      needs: [indexer, root_indexer] # Continue once these two executor are finished
```

I then had to install `transformers`, and `torch`. Also `jina==2.6.4` for mitigating the error: `ImportError: 'DocumentArrayMemmap' not found in 'jina'`. Then the indexing started without any errors. 
--------------------------------------------
During the indexing, 

```
⠋ Working... ━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:00 estimating... Task exception was never retrieved
future: <Task finished name='Task-9' coro=<BaseStreamer._stream_requests.<locals>.iterate_requests() done, defined at /home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/peapods/stream/base.py:132> exception=BadRequestType('fail to construct a <class \'jina.types.routing.table.RoutingTable\'> object from {\n  "active_pod": "start-gateway",\n  "pods": {\n    "encoder": {\n      "expected_parts": 1,\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "indexer"\n        }\n      ],\n      "port": 48585,\n      "port_out": 35639,\n      "target_identity": "15ee9637e0294f819c46bf4a32e34108"\n    },\n    "end-gateway": {\n      "expected_parts": 1,\n      "host": "0.0.0.0",\n      "port": 35313,\n      "port_out": 47053,\n      "target_identity": "384e6622f9c94f89ba4e33aee1c6eda0"\n    },\n    "indexer": {\n      "expected_parts": 1,\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "wait_both"\n        }\n      ],\n      "port": 54523,\n      "port_out": 44047,\n      "target_identity": "790bbe84f4bd416398e98869ba2d4dbe"\n    },\n    "root_indexer": {\n      "expected_parts": 1,\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "wait_both"\n        }\n      ],\n      "port": 42339,\n      "port_out": 35519,\n      "target_identity": "2429dd24ed504e7d9dd6e07e4c4289bb"\n    },\n    "segmenter": {\n      "expected_parts": 1,\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "encoder"\n        }\n      ],\n      "port": 47817,\n      "port_out": 33495,\n      "target_identity": "7dc61fa137dd487eac722986a4027235"\n    },\n    "start-gateway": {\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "segmenter"\n        },\n        {\n          "pod": "root_indexer"\n        }\n      ],\n      "port": 35313,\n      "port_out": 47053,\n      "target_identity": "384e6622f9c94f89ba4e33aee1c6eda0"\n    },\n    "wait_both": {\n      "expected_parts": 2,\n      "host": "0.0.0.0",\n      "out_edges": [\n        {\n          "pod": "end-gateway"\n        }\n      ],\n      "port": 48669,\n      "port_out": 59563,\n      "target_identity": "750ea7525fff4c19a7d982e70969473c"\n    }\n  }\n}')>
Traceback (most recent call last):
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/types/routing/table.py", line 134, in __init__
    json_format.Parse(graph, self._pb_body)
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/google/protobuf/json_format.py", line 436, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool,
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/google/protobuf/json_format.py", line 461, in ParseDict
    parser.ConvertMessage(js_dict, message, '')
TypeError: ConvertMessage() takes 3 positional arguments but 4 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/peapods/stream/base.py", line 142, in iterate_requests
    future: 'asyncio.Future' = self._handle_request(request=request)
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/peapods/stream/base.py", line 75, in _handle_request
    asyncio.create_task(self.iolet.send_message(self._convert_to_message(request)))
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/peapods/stream/gateway.py", line 24, in _convert_to_message
    return Message(None, request, 'gateway', **vars(self.args))
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/types/message/__init__.py", line 68, in __init__
    self.envelope = self._add_envelope(*args, **kwargs)
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/types/message/__init__.py", line 235, in _add_envelope
    envelope.routing_table.CopyFrom(RoutingTable(routing_table).proto)
  File "/home/zarzis/anaconda3/envs/jina/lib/python3.8/site-packages/jina/types/routing/table.py", line 144, in __init__
    raise BadRequestType(
jina.excepts.BadRequestType: fail to construct a <class 'jina.types.routing.table.RoutingTable'> object from {
  "active_pod": "start-gateway",
  "pods": {
    "encoder": {
      "expected_parts": 1,
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "indexer"
        }
      ],
      "port": 48585,
      "port_out": 35639,
      "target_identity": "15ee9637e0294f819c46bf4a32e34108"
    },
    "end-gateway": {
      "expected_parts": 1,
      "host": "0.0.0.0",
      "port": 35313,
      "port_out": 47053,
      "target_identity": "384e6622f9c94f89ba4e33aee1c6eda0"
    },
    "indexer": {
      "expected_parts": 1,
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "wait_both"
        }
      ],
      "port": 54523,
      "port_out": 44047,
      "target_identity": "790bbe84f4bd416398e98869ba2d4dbe"
    },
    "root_indexer": {
      "expected_parts": 1,
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "wait_both"
        }
      ],
      "port": 42339,
      "port_out": 35519,
      "target_identity": "2429dd24ed504e7d9dd6e07e4c4289bb"
    },
    "segmenter": {
      "expected_parts": 1,
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "encoder"
        }
      ],
      "port": 47817,
      "port_out": 33495,
      "target_identity": "7dc61fa137dd487eac722986a4027235"
    },
    "start-gateway": {
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "segmenter"
        },
        {
          "pod": "root_indexer"
        }
      ],
      "port": 35313,
      "port_out": 47053,
      "target_identity": "384e6622f9c94f89ba4e33aee1c6eda0"
    },
    "wait_both": {
      "expected_parts": 2,
      "host": "0.0.0.0",
      "out_edges": [
        {
          "pod": "end-gateway"
        }
      ],
      "port": 48669,
      "port_out": 59563,
      "target_identity": "750ea7525fff4c19a7d982e70969473c"
    }
  }
}
```
It was stuck here for 2 hours. I am at a loss about fixing it. Can you please help me on my next course of actions?

**Comment by JoanFM** [comment]
Hey @Jackal1586 ,

What is the version of `protobuf` that you are using? Can u try installing `protobuf==3.13.0`?

**Comment by Jackal1586** [comment]
`protobuf` version was `3.20.1`. after chaning it to `protobuf==3.13.0` it worked. Indexing was done. Then I tried to run the simple frontend provided in `static` directory, also ran `python app.py -t query`. But I am unable to enable `cors` from any place. Tried in `flows/query.yml`, `app.py`, and `Flow` library too. How should I enable cors in this case? 

For reference, I am providing my current environment [here](https://paste.ubuntu.com/p/gfH2KYdkwp/).

**Comment by JoanFM** [comment]
Have u checked this part of documentation?

https://docs.jina.ai/fundamentals/flow/flow-api/?highlight=enable%20cors#enable-cross-origin-resource-sharing-cors

**Comment by Jackal1586** [comment]
I only read parts related to cors and experimented accordingly. Like using `Flow`'s constructor one, and in yml `cors: True`. It didn't work for me.

**Comment by JoanFM** [comment]
Ah well, this is because `cors` was properly enabled after 3.x and not in 2.6.4

**Comment by Jackal1586** [comment]
Then what should be my next course of action if I want to run the full cycle as shown in `multires-lyrics-search`? I mean I need to enable `cors` at some point, right?

**Comment by JoanFM** [comment]
You should migrate your Flow to 3.3.x with the Executor versions compatible with 3.x and also the client code adapted.

**Comment by Jackal1586** [comment]
Ok, let me study the documentation related to migration, and experiement. I will post my results.

**Comment by xiaoxiongfeng** [comment]
> Hey @Jackal1586 ,
> 
> What is the version of `protobuf` that you are using? Can u try installing `protobuf==3.13.0`?

I solve the same question by your way,thanks

**Comment by withoutanybug** [comment]
my code is like `        for row in it.islice(reader, num_docs):
            if row[-1] == 'ENGLISH':` but I still got the error `gateway@70406[E]:receive an empty stream from the client! please check your client's inputs, you can use "Client.check_input(inputs)"`
what can I do to fix it?
