### ISSUE TITLE
Docs: Update Core Architecture map

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/jina#4617]
The map on the website (https://docs.jina.ai/fundamentals/architecture-overview/) always shows a `head`, but in the new Jina versions there is no head if there is no sharding.
Updated internal version is here: https://docs.google.com/presentation/d/1uBaSlTAyexQuHSnUctSt1wrrQxF3_kOB7F_z9wTrx-Y/edit#slide=id.g1132894e381_0_44

**Comment by hanxiao** [comment]
fixed https://docs.jina.ai/fundamentals/architecture-overview/
