### ISSUE TITLE
Epic: Improve reliability

### ISSUE THREAD

**Issue by jacobowitz** [jina-ai/jina#4622]
We want to improve the behavior of core from a reliability perspective.  This covers mostly error modeling, handling and reporting.

**This includes taking on these known issues:**

1. Error reporting for Flows failing to start is confusing. It includes multiple different stack traces. Only one of them usually is relevant and our users easily get lost.
2. Errors during DataRequest processing are reportedly very awkward at the moment. Some of those errors get caught automatically by gRPC and reported back as `Unexpected <class...` errors
3. If a Kubernetes Pod is killed, we may lose some messages in the process
4. Gateway/Head/Workers are not protected against being overloaded. Clients sending too fast might crash instances
5. We have generally good test coverage, but no chaos/load system test in K8s

To solve the above issues we want to do the following things. The list is ordered by priority:

- [x] #4624
- [x] #4625
- [x] #4626
~~ #4627~~ cancelled
~~  #4628 ~~cancelled
- [x] #4629
- [x] #4630
~~ #4631~~ cancelled
- [x] #4654
- [x] #4657
- [x] https://github.com/jina-ai/jina/issues/4817
- [x] #4763
- [x] #4767
- [x] #4877
- [x] #4878

**Comment by alaeddine-13** [comment]
What about retry logic in case of failures ?
I believe a main benefit of star routing is to be able to retry the request since we now properly implement a client-server pattern

**Comment by jacobowitz** [comment]
we have some retry logic already and we should a bit more clever one (like if you know that the target died). But I would try to do to much retry logic ourselves, because its very hard to know which requests to retry and which not, how often etc.
With a service mesh this can even be defined by the user, which might be better

**Comment by jacobowitz** [comment]
I read a bit about the the throttling part and I am not sure anymore we should inlclude that into Jina. Especially the service meshes are usually able to do that, so it would be unnecessary to reinvent the wheel here.
