### ISSUE TITLE
Make sure envs are passed to Head and Gateway

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4634]
**Solution to be implemented:**

- Make sure envs are passed to Gateway from the Flow
- Make sure the envs passed to a Pod are also sent to the Head Runtime

**Comment by deepankarm** [comment]
Updating `@env.setter` to do `p.update_pod_args()` like in `@workspace.setter` ([here](https://github.com/jina-ai/jina/blob/daff84402a5cd8f0f2a3c17c4aa42be89bf4d658/jina/orchestrate/flow/base.py#L1761)) would set the env for head. For gateway, it seems, we need to update `_common_kwargs`. 

```python
def setenv(flow: Flow, value: Dict):
    for k, v in flow:
        v.args.env = value
        v.update_pod_args()
    flow._common_kwargs.update({'env': value})
```

But `flow.to_k8s_yaml()` doesn't seem to consider env vars for Head & Gateway.

**Comment by deepankarm** [comment]
Another issue

```python
from jina import Flow, Executor, requests

f = f'''jtype: Flow
with:
    protocol: http
    env:
        a: b
executors: 
    - uses: jinahub+docker://Sentencizer
'''

flow = Flow.load_config(f)
print(flow.gateway_args.env)
# None
```
