### ISSUE TITLE
Document the usage of `extra_search_paths` to load Executor

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4648]

**Comment by JoanFM** [comment]
Specially important for Windows usage

**Comment by JohannesMessner** [comment]
It is mentioned here: https://docs.jina.ai/fundamentals/flow/create-flow/?highlight=extra_search_paths#add-executors-from-different-sources
Are there other uses for it? And what are its implications for Windows? I'd be happy to document it, but am not familiar with the feature myself

**Comment by JoanFM** [comment]
Ok, will close then

**Comment by JohannesMessner** [comment]
Ok, but if Windows user need to use this for some reason then it would be good to add that info imo
