### ISSUE TITLE
Parsing invalid Executor YAML does not fail properly

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/jina#4654]
If a `.yml` that does not define an Executor is passed to `uses=`, it will be parsed into a dict instead of an actual Executor. This dict is then treated like an Executor in the worker runtime ~~, which then fails of course, leading to a cryptic error message.~~

The behaviour has changed (I believe as a consequence of exec endpoint discovery), now no error is given at all.

**To Reproduce:**

Define invalid YAML:

`invalid.yml`:
```yaml
invalidkey: hello
```

Then try to use it:

```python
f = Flow().add(
        uses='invalid.yml',
    )

with f:
  f.index(inputs=[Document()])
```

**Comment by JoanFM** [comment]
Please put less priority to this ticket. Priority on reliability and robustness should go in the `communication layer`
