### ISSUE TITLE
Json decode error while request to service running with docker-compose

### ISSUE THREAD

**Issue by jerrychen1990** [jina-ai/jina#4678]
Json Decode error while request to service running with docker-compose

I flow the doc about run jina with docker compose : https://docs.jina.ai/how-to/docker-compose/
everything goes well and the service starts.
when I try to send index request with code:
```

from docarray import DocumentArray

indexing_documents = DocumentArray.from_files('./imgs/*.jpg').apply(
    lambda d: d.load_uri_to_image_tensor()
)

indexed_docs = client.post('/index', inputs=indexing_documents)

print(f'Indexed Documents: {len(indexed_docs)}')
```
and get a json decoding exception like this:

```
Exception in thread Thread-61:
Traceback (most recent call last):
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/helper.py", line 1299, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/clients/mixin.py", line 147, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/clients/base/http.py", line 124, in _get_results
    raise e
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/site-packages/jina/clients/base/http.py", line 77, in _get_results
    r_str = await response.json()
  File "/Users/chenhao/opt/anaconda3/envs/jina/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://192.168.3.14:8080/post')
```
---

**Environment**
docker version on server side: Docker version 20.10.14, build a224086
jina env on client side:
- jina 3.3.6
- docarray 0.12.2
- jina-proto 0.1.8
- jina-vcs-tag (unset)
- protobuf 3.20.0
- proto-backend cpp
- grpcio 1.45.0
- pyyaml 6.0
- python 3.10.2
- platform Darwin
- platform-release 21.4.0
- platform-version Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 62645640789571
- session-id 1dc88474-c469-11ec-8edc-38f9d32a7e43
- uptime 2022-04-25T15:27:08.830576
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Screenshots**
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/6780752/165040868-dff3bcd1-0d54-4fb4-b495-aafb84198acd.png">
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/6780752/165040929-4075bf19-4f3b-498e-b3cb-0a96529abe0b.png">

**Comment by JoanFM** [comment]
may u show the Flow and how it was created and started?

**Comment by jerrychen1990** [comment]
> 

I flow the jina's [doc](https://docs.jina.ai/how-to/docker-compose/#example-indexing-and-searching-images-using-clip-image-encoder-and-pqliteindexer) exactly

**Comment by jerrychen1990** [comment]
below is the content of docker-compose.yml
version: '3.3'
networks:
  jina-network:
    driver: bridge
services:
  encoder-rep-0:
    image: jinahub/0hnlmu3q:62660a2cf6c0356ffc8dd04f
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - encoder/rep-0
    - --uses
    - config.yml
    - --port
    - '8081'
    - --replicas
    - '2'
    - --uses-metas
    - '{}'
    - --native
    - --workspace
    - /app/.jina/executor-workspace
    healthcheck:
      test: python -m jina.resources.health_check.pod localhost:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    volumes:
    - /Users/chenhao/.jina/executor-workspace:/app
    networks:
    - jina-network
  encoder-rep-1:
    image: jinahub/0hnlmu3q:62660a2cf6c0356ffc8dd04f
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - encoder/rep-1
    - --uses
    - config.yml
    - --port
    - '8081'
    - --replicas
    - '2'
    - --uses-metas
    - '{}'
    - --native
    - --workspace
    - /app/.jina/executor-workspace
    healthcheck:
      test: python -m jina.resources.health_check.pod localhost:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    volumes:
    - /Users/chenhao/.jina/executor-workspace:/app
    networks:
    - jina-network
  indexer-head:
    image: jinaai/jina:3.3.6-py38-standard
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer/head
    - --port
    - '8081'
    - --runtime-cls
    - HeadRuntime
    - --pod-role
    - HEAD
    - --shards
    - '2'
    - --connection-list
    - '{"0": ["indexer-0:8081"], "1": ["indexer-1:8081"]}'
    - --uses-metas
    - '{}'
    - --native
    healthcheck:
      test: python -m jina.resources.health_check.pod localhost:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    networks:
    - jina-network
  indexer-0:
    image: jinahub/pn1qofsj:6262e83bec902a04cc0466db
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer-0
    - --uses
    - config.yml
    - --port
    - '8081'
    - --shards
    - '2'
    - --uses-metas
    - '{}'
    - --uses-with
    - '{"dim": 512}'
    - --native
    - --workspace
    - /app/.jina/executor-workspace
    healthcheck:
      test: python -m jina.resources.health_check.pod localhost:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    volumes:
    - /Users/chenhao/.jina/executor-workspace:/app
    networks:
    - jina-network
  indexer-1:
    image: jinahub/pn1qofsj:6262e83bec902a04cc0466db
    entrypoint:
    - jina
    command:
    - executor
    - --name
    - indexer-1
    - --uses
    - config.yml
    - --port
    - '8081'
    - --shard-id
    - '1'
    - --shards
    - '2'
    - --uses-metas
    - '{}'
    - --uses-with
    - '{"dim": 512}'
    - --native
    - --workspace
    - /app/.jina/executor-workspace
    healthcheck:
      test: python -m jina.resources.health_check.pod localhost:8081
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    volumes:
    - /Users/chenhao/.jina/executor-workspace:/app
    networks:
    - jina-network
  gateway:
    image: jinaai/jina:3.3.6-py38-standard
    entrypoint:
    - jina
    command:
    - gateway
    - --polling
    - ANY
    - --port
    - '8080'
    - --expose-endpoints
    - '{}'
    - --protocol
    - HTTP
    - --graph-description
    - '{"encoder": ["indexer"], "start-gateway": ["encoder"], "indexer": ["end-gateway"]}'
    - --deployments-addresses
    - '{"encoder": ["encoder:8081"], "indexer": ["indexer-head:8081"]}'
    - --pod-role
    - GATEWAY
    expose:
    - '8080'
    ports:
    - 8080:8080
    healthcheck:
      test: python -m jina.resources.health_check.gateway localhost:8080 http
      interval: 2s
    environment:
    - JINA_LOG_LEVEL=INFO
    networks:
    - jina-network

**Comment by JoanFM** [comment]
Hello @jerrychen1990,

I have identified the problem and we are working on a fix. Thanks so much for pointing this out.

In the meanwhile, I suggest you can follow with your work by making sure that the `replicas` argument of each Deployment is set to 1.

We will keep you posted on when this is solved

**Comment by JoanFM** [comment]
Hello @jerrychen1990,

The issue should have been fixed and the next patch should have it working.
