### ISSUE TITLE
test: have jina-now tests running on ci

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#4691]
**Describe the feature**
As a Jina Now contributor, I would like to avoid breaking changes on our cloud infrastructure. Please run Jina-Now tests on the ci of Core and Hubble.

**Proposal**
You can use our end-2-end integration tests (10min). https://github.com/jina-ai/now/blob/main/tests/integration/test_end_to_end.py

**Comment by JoanFM** [comment]
Jina Now should have jina as dependency and every jina upgrade should be a PR to jina now
