### ISSUE TITLE
Loading a dockerized executor never ends

### ISSUE THREAD

**Issue by bottledmind** [jina-ai/jina#4707]
**Describe the bug**
Running `python app.py` results in endless `3/4 waiting for executor1 to be ready...`
This is a dockerized executor I'm trying to use
The full project is here https://github.com/bottledmind/jina-issues

**Describe how you solve it**  
Works fine with dockerized executor

**Environment**
```
- jina 3.3.13
- docarray 0.13.0
- jina-proto 0.1.8
- jina-vcs-tag (unset)
- protobuf 3.20.1
- proto-backend cpp
- grpcio 1.43.0
- pyyaml 6.0
- python 3.7.11
- platform Linux
- platform-release 5.13.0-40-generic
- platform-version #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
- architecture x86_64
- processor x86_64
- uid 241531861464880
- session-id e236b906-c60e-11ec-84fa-dbac04cdf730
- uptime 2022-04-27T12:46:16.778228
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)
```

**Comment by JoanFM** [comment]
Hello @bottledmind ,

thanks for opening the issue, could you add some more details about how you build your containerized Executor?

Thanks!

**Comment by bottledmind** [comment]
@JoanFM Oh, yeah, my bad
I ran `docker build -t my_containerized_executor .` from encoder dir

**Comment by JoanFM** [comment]
but where is the `Dockerfile` @bottledmind ?

**Comment by bottledmind** [comment]
@JoanFM It's in the `encoder` directory

**Comment by JoanFM** [comment]
Hey @bottledmind , I have identified the issue,

It is something we have been suffering int he last days and we thought we solved but we did not.

Will open a ticket so that you can keep track of the progress.

**Comment by JoanFM** [comment]
@bottledmind , in the meanwhile, may u try to use 3.3.11 and forcing this version in the Dockerfile requirements?

**Comment by bottledmind** [comment]
@JoanFM changed the versions and still getting same issue

**Comment by JoanFM** [comment]
I am releasing a new patch `3.3.14` that I believe can fix the issue. 

Remember to remove the docker images and all after that. It should be ready very soon

**Comment by JoanFM** [comment]
Related to #4708

**Comment by JoanFM** [comment]
Hello @bottledmind ,

I think this is fix by using `jina 3.3.15`. Remember to rebuild the docker image

**Comment by bottledmind** [comment]
@JoanFM 
Yeah, I got it working, but is the console supposed to freak out like this?
![image](https://user-images.githubusercontent.com/60937565/165566532-dd3d871b-20d3-4bb5-be35-46f30d9841a7.png)

**Comment by bottledmind** [comment]
Those were tqdm logs from tensorflow, i guess. But these..
![image](https://user-images.githubusercontent.com/60937565/165567742-730fc7dc-25ec-4435-9547-301b9469b9b0.png)

**Comment by hanxiao** [comment]
will address it today
