### ISSUE TITLE
Client.encode() does not close file descriptors used.

### ISSUE THREAD

**Issue by MrBeeMovie** [jina-ai/jina#4725]
I am calling .encode() multiple times and it seems as though file descriptors are being opened but not closed which results in this error after running for a period of time.

```
E0429 15:10:27.741673000 4681657856 wakeup_fd_pipe.cc:39]              pipe creation failed (24): Too many open files
E0429 15:10:27.744256000 4681657856 ev_poll_posix.cc:1415]             Skipping poll because of no wakeup fd.
E0429 15:10:27.744857000 4681657856 ev_posix.cc:228]                   No event engine could be initialized from all
```

when running `lsof | wc -l` I start to get crazy numbers of open files after a while.

You can run this test code with clip-server running to expose leak as fast as possible:

```python
from clip_client import Client


c = Client("grpc://localhost:51000")

while True:
   c.encode([" "]) 
```

**Comment by hanxiao** [comment]
A better visualization on diff

```python
import os
import subprocess
import sys
import webbrowser
from difflib import HtmlDiff

from jina import Flow, Client

pid = os.getpid()
print('pid', pid)
before = subprocess.getoutput(f'lsof -p {pid}')
with Flow() as f:
    c = Client(port=f.port)
    for _ in range(10):
        c.post('/')
    after = subprocess.getoutput(f'lsof -p {pid}')

with open('diff.html', 'w') as fp:
    fp.writelines(HtmlDiff().make_file(before.split('\n'), after.split('\n')))

webbrowser.open('file://' + os.path.realpath('diff.html'), new=2)


```


<img width="1616" alt="image" src="https://user-images.githubusercontent.com/2041322/166095488-a07ba663-9454-4145-9b36-fb377872a950.png">

**Comment by hanxiao** [comment]
Related issue to help core team:

https://github.com/QuarkChain/pyquarkchain/issues/411#issuecomment-484720553
https://github.com/python/cpython/issues/77262#issuecomment-1093779482

**Comment by MrBeeMovie** [comment]
@hanxiao Thank you so much for your efforts! Hope this gets fixed soon.

**Comment by jacobowitz** [comment]
I think our `run_async` helper function is at fault here. I got an even simpler mwu to reproduce with this:

`import psutil

from jina.helper import run_async


async def do_something():
    result = []
    result.append('hello')

for i in range(1):
    run_async(do_something)

p = psutil.Process()
print(p.num_fds())`

**Comment by jacobowitz** [comment]
A workaround for now is to use the Client in its [async version](https://docs.jina.ai/fundamentals/flow/client/#async-python-client)

In this case we dont use `https://docs.jina.ai/fundamentals/flow/client/#async-python-client` and there should be no file descriptors being leaked

**Comment by MrBeeMovie** [comment]
> A workaround for now is to use the Client in its [async version](https://docs.jina.ai/fundamentals/flow/client/#async-python-client)
> 
> In this case we dont use `run_async` and there should be no file descriptors being leaked

Thank you, I will try that. Thank you for your help!
