### ISSUE TITLE
Publish Github release after Docker / pypi push

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#4748]
We publish a new GitHub release before actually pushing the new docker images. This is wrong, and annoying for downstream. Here's how it can be solved. 

- Move [create-release](https://github.com/jina-ai/jina/blob/master/.github/workflows/tag.yml#L85) into a new workflow yaml, and add `token` validation like in `Manual Docker Build`. 
- In [Manual Docker Build](https://github.com/jina-ai/jina/blob/2ce767517532ebbf85ade4b84cfba0f7bb69c4f9/.github/workflows/force-docker-build.yml), after `Build and push`, trigger `create-release` if `triggered_by` is `TAG`.

**Comment by mrtrkmn** [comment]
Hi 
Can I take this issue to resolve ?

**Comment by nan-wang** [comment]
@deepankarm Can this be solved by changing this line?

https://github.com/jina-ai/jina/blob/master/.github/workflows/tag.yml#L86

```diff
-     needs: update-doc
+    needs: update-docker
```

**Comment by nan-wang** [comment]
I think the major issue is `create-release` and `update-docker` are executed in parallel. 

![image](https://user-images.githubusercontent.com/4329072/168208463-95b26d49-cad5-409c-a757-04eda817d94a.png)
