### ISSUE TITLE
Document the Flow yaml spec 

### ISSUE THREAD

**Issue by deepankarm** [jina-ai/jina#4749]
We need a place in [docs.jina.ai](https://docs.jina.ai/), where detailed Flow yaml spec is documented.  An example from [eksctl docs](https://eksctl.io/usage/schema/). 

Here's how it is rendered.

- [schema.md](https://github.com/weaveworks/eksctl/blob/main/userdocs/src/usage/schema.md) refers to `<script type="module" src="../schema.js"></script>`
- [schema.js](https://github.com/weaveworks/eksctl/blob/main/userdocs/src/usage/schema.js) reads a schema.json file & renders the actual HTML schema.
- `schema.json` is an OpenAPI specification for the allowed fields. 

We have a `jina export-api` CLI, but it isn't a valid OpenAPI schema. So we either have to add a spec that follows openapi & use something similar to eksctl for rendering the HTML or, use the existing schema to render the HTML. 

- [x] manual generation (https://github.com/jina-ai/jina/pull/4795)
- [ ] autogeneration

**Comment by mapleeit** [comment]
> We have a jina export-api CLI, but it isn't a valid OpenAPI schema. 

"OpenAPI schema" should be "JSON schema", right? 

I saw the result of `jina export-api --schema-path ./test.json` is already a valid JSON schema (based on JSON schema DRAFT7)

So we only need render which can convert JSON schema to a HTML.

**Comment by JoanFM** [comment]
First we can start by just adding the `documentation` as it was in `docs` of `v1`, and then see how to autogenerate the schemas better
