### ISSUE TITLE
How to use the same executor multiple times in flow

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/jina#4793]
**Describe your proposal/problem**
I am using multiple local executors. One of them is LMDB. I would like to access LMDB twice in my flow, but without running two executors but just one. (to save RAM). 

    - name: chunk_match_db_filler
      uses:
        jtype: LMDBStorage
        py_modules:
          - executors/lmdb_storage.py
      uses-with:
        default_traversal_paths: ['cm']

    - name: ranker
      uses:
        jtype: IRanker
        py_modules:
          - executors/ranker.py
      uses-with:
        dim: 768

    - name: root_match_db_filler
      uses:
        jtype: LMDBStorage
        py_modules:
          - executors/lmdb_storage.py
      uses-with:
        default_traversal_paths: ['rm']

It will spin two lmdb_storage.py executors on different ports. 

**Environment**
- jina 2.3.0
- jina-proto 0.0.86
- jina-vcs-tag (unset)
- libzmq 4.3.4
- pyzmq 1.21.2
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.43.0
- pyyaml 6.0
- python 3.9.7
- platform Darwin
- platform-release 21.4.0
- platform-version Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
- architecture x86_64
- processor i386
- uid 187356575441618
- session-id 1e72271a-d5ce-11ec-9a61-aa665a2022d2
- uptime 2022-05-17T12:42:58.194194
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_K8S_USE_TEST_PIP (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_ID (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_POD_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

**Comment by JoanFM** [comment]
Hey @tommykoctur ,

You may want to follow this documentation:

https://docs.jina.ai/how-to/external-executor/?highlight=external+executor&utm_source=jina#how-to-use-external-executors
