### ISSUE TITLE
how to add grpc endpoint in the Flow

### ISSUE THREAD

**Issue by szpnygo** [jina-ai/jina#4831]
like this

Flow().add(uses="grpc://10.10.1.7:8080", name="my_exec")

or http

Flow().add(uses="http://10.10.1.7:8080", name="my_exec")

Then I can deploy the executor in the k8s and use it easy

BTW: I don't want to use the Linkerd in the simple situation

**Comment by JoanFM** [comment]
Hey @szpnygo ,

you may find this piece of documentation useful.

https://docs.jina.ai/how-to/external-executor/?highlight=external%20executor#adding-external-executors

This is the way u can add already spawned Executors to a Flow

**Comment by JoanFM** [comment]
Please not that this would be equivalent to your first solution because it would be using grpc

**Comment by szpnygo** [comment]
> Hey @szpnygo ,
> 
> you may find this piece of documentation useful.
> 
> https://docs.jina.ai/how-to/external-executor/?highlight=external%20executor#adding-external-executors
> 
> This is the way u can add already spawned Executors to a Flow

Sorry, I didn't read the documentation carefully, thanks
