### ISSUE TITLE
what's the syntax for connecting to TLS enabled external executor via a Flow?

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#4838]
When connecting to a external executor we can't use host unpacking.

The following will break. When trying to connect to the host. The host unpacking feature is only available for the Client so far.

```python
from jina import Flow
from docarray import DocumentArray

f = Flow().add(host='grpcs://host.wolf.jina.ai', external=True)
```
To achieve the same you should do:

```python
f = Flow().add(host='host.wolf.jina.ai', tls=True external=True)
```

https://jinaai.slack.com/archives/C018F60RBL5/p1653650604811799

**Comment by samsja** [comment]
from jina import DocumentArray, Flow
```
f = Flow().add(tls=True, host='host.wolf.jina.ai', external=True)
```

work but as soon as we add a port or a `/` at the end of the host it failed because it ignores the tls
