### ISSUE TITLE
pdf search 

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/jina#4853]
**Describe your proposal/problem**

.add(
            uses="jinahub://CLIPEncoder",
            install_requirements=True,
            name="encoder",
            uses_with={"traversal_paths": "@c"},
        )

Is there an explanation of this concept here, Can it be used in Chinese? thanks. 
---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
Hey @xiaoxiongfeng , what is the exact concept?

You may find this link useful https://hub.jina.ai/executor/29r2b26t

**Comment by alexcg1** [comment]
The encoder takes a piece of data (e.g. text/image/audio/video) and converts it into a vector embedding, something the computer can understand more natively. This lets our search engine easily find similar data.

In the case of CLIPEncoder, it can take image or text and generate an embedding from that. I think it only works for English though.

I don't know of any encoder that can handle both Chinese text AND images. For Chinese text alone, perhaps [TransformerTorchEncoder](https://hub.jina.ai/executor/u9pqs8eb) with a [Chinese language model](https://huggingface.co/models?pipeline_tag=fill-mask&sort=downloads&search=chinese)?

**Comment by JoanFM** [comment]
Hey @xiaoxiongfeng,

I am going to close this issue as per the response from @alexcg1,

If you still have the same problem just do not hesitate to reopen this ticket or a new one with more details and explanation
