### ISSUE TITLE
There are no images saved here

### ISSUE THREAD

**Issue by xiaoxiongfeng** [jina-ai/jina#4857]
**Describe your proposal/problem**

https://github.com/alexcg1/example-pdf-search/ 

convert-im6.q16: no images defined `../data/metadata/covers/rabbit.pdf.png' @ error/convert.c/ConvertImageCommand/3258.

chunk.save_image_tensor_to_file(
                            f"{image_chunk_dir}/{chunk.id}.png"
                        )

Maybe the image is not saved
---

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
Hey @xiaoxiongfeng, would you be able to provide more details, how can we reproduce the issue? what jina version are you running?

**Comment by alexcg1** [comment]
Hey @xiaoxiongfeng, I've replied in the issue queue on the PDF search repo
