### ISSUE TITLE
Redundant DocumentArrayMemmap import in __init__.py  

### ISSUE THREAD

**Issue by davismartens** [jina-ai/jina#4862]
**Describe the bug**
According to the [docs](https://docs.jina.ai/get-started/migrate/), `DocumentArrayMemmap` is no longer part of Jina 3. 

In __init__.py (line 199) there is still a reference to the import which throws an error. Is this a bug?

`from docarray import Document, DocumentArray ,DocumentArrayMemmap`

**Comment by hanxiao** [comment]
are you sure? you must be looking at some other branch/tags. such thing won't exist as it for sure break CICD

**Comment by davismartens** [comment]
I found the issue.
