### ISSUE TITLE
food for thought

### ISSUE THREAD

**Issue by monikabishnoi29** [jina-ai/jina#4863]
Idea: [DESCRIBE WHAT YOUR IDEA OF THE SEARCH APP IS]

What is the tech stack? [MENTION ALL TECHNOLOGIES YOU WISH TO USE]

Motivation behind this idea?

**Comment by JoanFM** [comment]
Hey @s,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
