### ISSUE TITLE
2 Idea Proposals

### ISSUE THREAD

**Issue by Namya13Jain** [jina-ai/jina#4871]
**Idea1**:
 I have thought of developing a Mobile Application which would contain information on various health
problems which the females of different age groups might face. An elaborative information
would be provided on the causes and symptoms as well.  A detailed dietary plan would be provided along with some
exercises and yogasanas. I have thought to include this because a person can live a healthy life by
opting for some healthy lifestyle changes. The first special feature would be that all this information
would be available in _22 regional languages apart from Hindi and English._ This feature is
specially made to target people who might not be too fluent in English and Hindi.
         Along with opting for a healthy lifestyle, some medication is always beneficial to eradicate a
problem. A comprehensive tracking system would be developed using Artificial Intelligence and
Machine Learning which would get the details of all the nearby hospitals and clinics along with the
details of the gynecologists . I have incorporated this feature keeping in mind that still a major portion of Indians are not very familiar with the technology of GPS and Google Maps. 
      The people booking consultation through our platform would avail a special discount of 25% on consultation fee.
         The next issue is the cost of Medical Tests which may even start from thousands of rupees.  
      We would be providing a 50% discount on these tests at our partnered labs. This would allow even low
income people to get the best treatment .
         Personal assistance would be available on our helpline number where the customers can discuss
their issues and seek help from the doctors. They can also share their grievances if they are facing
any social harassment regarding their Menstrual health and we would be helping them.
       Talking about the condition of Rural Areas where people may not have proper internet connectivity
and desktops at their places, I have thought of a special plan to tackle all such issues. I would be
taking the help of the Government to allocate funds for installing tablets in the local dispensaries so
that the people can come there to seek information . A special female nurse would also be appointed
to assist the people in operating the tablets and also helping them in the various health issues.
Campaigns would be done to create awareness about the same so that every woman can seek
benefit from the same.

What is the tech stack?

- I wish to use flutter for creating the frontend of the app and firebase for its backend development. 
- Use of python for Machine Learning and Artificial Intelligence . 

Motivation behind this idea?
One day, my mother told me that one lady in our neighborhood was facing the problem of irregular
periods postpartum and her family members did not get her checkup done as they were not ready to
even discuss it with anyone. She was also facing many other problems like backache, pain in the
lower abdomen ,etc. They were hesitating in discussing a normal body change which that lady was experiencing. Later on ,some of my classmates also said that their menstrual health is neglected and often not addressed in their families . At that time , I realized that menstrual health is a serious issue that needs to be addressed. So, this motivated me to come up with this mobile application.

**Idea 2:**
I have thought of developing a search engine for School  and University Students which would provide them all the resources they require to kickstart their career at one place in a single click. 
 In this, I have thought of sorting the resources age wise and topic wise. This will save their time searching them manually. It would also help them to know about other aspects and information which they might not already know. It will open new avenues for their career and help them choose the best for themselves. 
   E copies of textbooks and Self Help books can be made available on the platform so that they can learn at a faster pace and help them in their holistic  development. 
    Some relevant contacts can also be shared so that the students can connect with them on various platforms and seek guidance because a mentor can help in making the path easier. 

What is the Tech Stack?
I have thought of using Python, Machine Learning and Artificial Intelligence. 

 Motivation behind this idea?
I am the first University generation in my family and I know that  proper guidance and help can make your path towards reaching your goals easier. I had to spend a lot of time searching for the various resources and opportunities myself and I wasn't on any social media platform till last year. So I had to do everything myself which consumed a lot of time and energy which I could have utilized in doing something more productive. There might be many more students like me facing the same issues. So I decided to help them all by proposing this idea.

**Comment by JoanFM** [comment]
Hey @Namya13Jain,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
