### ISSUE TITLE
Novel Recommendation System

### ISSUE THREAD

**Issue by aku1310** [jina-ai/jina#4872]
### Idea
The idea of this project is to provide the user with a list of novels that matches the setting of the song they use as the input.

### What is the tech stack? 
Python, React.js, HTML/CSS, PHP, etc.

### Motivation behind this idea?
Songs are so inspiring, in-fact it is such a powerful tool that they are used in everything ranging from a person listening to music while studying to patriotic songs in armies. Music invokes our imagination and creates a scenario corresponding to the kind of music one is listening. Now what if one gets a list of novels that creates the same sense of adventure as the song one listens to. This project aims to do the same.

**Comment by JoanFM** [comment]
Hey @aku1310,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
