### ISSUE TITLE
Recipe Recommendation System

### ISSUE THREAD

**Issue by aaheli8** [jina-ai/jina#4874]
Idea: The user will enter the available ingredients and based on the input, recipes will be recommended.  

What is the tech stack? 
Python, Machine Learning Libraries and Flask. 

Motivation behind this idea?
The motivation behind this idea is that many a time we want to try new recipes but cannot do it due to the limited availability of ingredients at home.  This recommendation system will help utilise the available ingredients and let us cook delicious food by using those ingredients only.  This system will also help to cook healthy foods and try new recipes from across the world.

**Comment by JoanFM** [comment]
Hey @aaheli8,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
