### ISSUE TITLE
Plant Classifier

### ISSUE THREAD

**Issue by shru1032** [jina-ai/jina#4881]
**Idea:** 
The idea is to crerate an application that will take the pictures of a plant and identify it. The application would return the name of the plant as well as other relevant information about the plant like where is it found, what are it's medicinal benifits, etc. 

**What is the tech stack?** 
I'm planning to use ML models, Jina AI, Python, Flutter etc.

**Motivation behind this idea?**
Plants and flowers have always been fascinating for me since childhood. Getting to see new plants always used to create a curiosity about it and I believe there would be more children like me who adore plants. Having a search engine to satisfy this curiosity of mine and many others would be great.

**Comment by kaad01** [comment]
#4889 This one seems very close to your Idea. I'm interested in both of your Ideas. I would start working on this in 2 months.

**Comment by JoanFM** [comment]
Hey @shru1032,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks

@kaad01 we would still be interested on hearing about your project when is done!
