### ISSUE TITLE
Chatbot Song Recommender System

### ISSUE THREAD

**Issue by shru1032** [jina-ai/jina#4882]
**Idea**
The idea is to create a chatbot that will analyse the sentiment of the user through the conversation and would recommend songs that are relevant for that emotion. 

**What is the tech stack?** 
I wish to use Python, AI/ML, Tone Analyzer API, etc to implement this.

**Motivation behind this idea?**
Having a chatbot that you can have a conversation with and that also recommends songs for you to listen to is like having a friend who is always there for you no matter what. Doesn't that sound good? A "Pocket-friend", What else does one need?

**Comment by JoanFM** [comment]
Hey @shru1032,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
