### ISSUE TITLE
Video Search System.

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [jina-ai/jina#4887]
Idea : 
A web app that provides user with an option to search movies or web series or any videos with input as dialogues or screenshots or short video clips. The user can upload the screenshots and then the web app would provide the links to the output results.

What is the tech stack?
Python, Web frameworks including HTML, CSS, JS, Django etc, JINA AI, Neural Networks.

Motivation behind this idea?
Most of us often tend to forget the names of the series or movies we have watched few weeks before , but we do remember some of the shorts and one might also have screenshots. It also happens with educational materials, most of the times we randomly watch some videos and sometimes they prove to be very helpful but we forget the channel name and then it becomes quite difficult to search that video again. So if the user wants to watch that particular video again and if he has the screenshots or short videos or recalls the lines then on the basis of that the app can help in finding out the video.

**Comment by JoanFM** [comment]
Hey @Vaishnavi-Markunde,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
