### ISSUE TITLE
Enhanced Search Engine

### ISSUE THREAD

**Issue by Vaishnavi-Markunde** [jina-ai/jina#4888]
### Idea:
The idea here is to develop a search engine for mute people. The search bar would have an option to **search by action** for people who are aphonic. This would open up camera to record user's actions and use AI to understand sign language and search accordingly.

### What is the techstack?
Python, Jina AI, Django, CNN, AI, and lots of research. 

### Motivation behind this idea.
We already have the options to search by text and voice, but the people who can't speak are not benefited by this voice search technology.  So developing a **search by action** tool would help them in a better way. Also people who are illiterate and can't type or speak would be able to make benefit out of the internet via this tool.

**Comment by JoanFM** [comment]
Hey @Vaishnavi-Markunde,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
