### ISSUE TITLE
Plants Identifier System 

### ISSUE THREAD

**Issue by AaliyahBeg** [jina-ai/jina#4889]
### Idea: 
The basic idea of my search app is that we can upload the picture of a beautiful plant that we spot in our friend's backyard or on our trek basically anywhere else so as to get the name of that plant and hence have an addition in your own garden! ☘️
In addition to this I also would want to add a plant recommender which would recommend the user similar plants to the one whose picture was upload .☘️

### What is the tech stack?
-Python based technologies:
Streamlit , Jina AI and other machine learning libraries.
-Dataset
-The application will be based on neural networks.

### Motivation behind this idea.
One of my mother's favourite activity is to take care of her plants and she loves having beautiful and unique additions to her collection of plants. I have always seen her spell out some very difficult names which might just be difficult to remember or at times she might want to know the name so I think this application would prove to very useful.

**Comment by JoanFM** [comment]
Hey @AaliyahBeg,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks
