### ISSUE TITLE
Personal Tourism Guide

### ISSUE THREAD

**Issue by AaliyahBeg** [jina-ai/jina#4891]
### Idea: 

The idea of this search app is that a user will provide in their previous vacation pictures and enter the destination they plan to go, then the app will do a image-image search i.e. examine the photos entered to get an insight to the kind of places that the user generally likes to go when on a vacation and then give an exhaustive list of the tourist places and spots in the destination place  priority wise as per the users image dataset.

### What is the tech stack? 

-Python based technologies:
Streamlit , Jina AI and other machine learning libraries.
-The application will be based on neural networks.

### Motivation behind this idea?

I am a travel enthusiast but very particular to the places that I would wish to explore , I generally like going to natural places where I connect with nature or to peaceful cafes more than shopping in the middle of a hustling street. Likewise, I believe everyone has their own preferences which is quite evident through the pictures in their photo gallery. Hence, this application will definitely help.

**Comment by JoanFM** [comment]
Hey @AaliyahBeg,

Thanks for your idea, however this issue should be opened in https://github.com/jina-ai/good-first-issues/issues

Thanks

**Comment by joeyouss** [comment]
Hey @AaliyahBeg thank you so much for this idea and describing it in detail. I have moved this idea here https://github.com/jina-ai/good-first-issues/issues/61. Can you comment there so I can assign it to you?

I am interested in having a deeper conversation about this use case which seems interesting right now!

**Comment by AaliyahBeg** [comment]
@joeyouss , Really appreciate that you liked my idea ! Would definitely love working on it.
