### ISSUE TITLE
"Hello World" not found.

### ISSUE THREAD

**Issue by yogeshhk** [jina-ai/jina#4894]
**Describe the bug**
Tried looking for "Hello World" tutorial. First at `https://github.com/jina-ai/jina/blob/master/.github/pages/hello-world.md#jina-hello-world-`. It said
`This cookbook is deprecated. The content is revised and moved to https://docs.jina.ai/get-started/hello-world/`
Even the suggested link was not correct, it went to "Page Not Found".

**Comment by JoanFM** [comment]
Hey @yogeshhk ,

Thanks for the advice, `hello-world` have been recently removed in favour of other more advanced examples as pointed in our README

I will make sure to remove these pages from the repo

**Comment by yogeshhk** [comment]
Thanks @JoanFM
