### ISSUE TITLE
`Flow.add` does not modify in-place

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#4912]
Flow.add  creates a new flow object and adds the Executor, instead of adding in-place and returning.
This behavior makes this code not working:
```python
f = Flow()
f.add(exec1)
f.add(exec2)
```
Also, the docstring of the method add says :
Add a Deployment to the current Flow object and return the new modified Flow object
which is wrong.

**Comment by JoanFM** [comment]
You can use `copy_flow=False` parameter
