### ISSUE TITLE
Docs: Neural search Page not found

### ISSUE THREAD

**Issue by vivekvardhanadepu** [jina-ai/jina#4917]
**Describe the bug**
https://docs.jina.ai/get-started/neural-search/?utm_source=learning-portal gives "page not found" from bootcamp beginner(https://learn.jina.ai/beginner)

**Comment by JoanFM** [comment]
Hey @alexcg1 may u check what is wrong here?

**Comment by vivekvardhanadepu** [comment]
does it take some time to reflect on the bootcamp? As it still gives me "Page not found"

**Comment by Shubhamsaboo** [comment]
Yes, please check back in few hours!

**Comment by Shubhamsaboo** [comment]
It is updated now and reflects on the BootCamp website. @vivekvardhanadepu

**Comment by vivekvardhanadepu** [comment]
thanks!!
