### ISSUE TITLE
No module named 'starlette'

### ISSUE THREAD

**Issue by KonstantinKlepikov** [jina-ai/jina#4932]
**Describe the bug**
No module named 'starlette'
No module named 'aiohttp''

but for http client are required of course

this in jinaai/jina:master-py38 container

**Comment by JoanFM** [comment]
Hey @KonstantinKlepikov ,

may u please describe the exact steps you took?

**Comment by hanxiao** [comment]
https://docs.jina.ai/get-started/install/docker/

most likely you are using wrong image

**Comment by JoanFM** [comment]
u may want to use `perf` perhaps. Otherwise u can install the extra packages that u need
