### ISSUE TITLE
Monitoring: check pending request behavior with failing request

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#4973]
# Context:

Some user notice a weird behavior with the pending request metrics on the Gateway. The number never went down under a given value.

One possible explanation is that some failled request are not properly handled on the counter. 

We need to double check the behavior/implementation and add tests to confirm/infirm the bug.

**Comment by JoanFM** [comment]
What kind of Failures should we care for? Functional and non-functional (Connection issues vs Exceptions being thrown)

**Comment by samsja** [comment]
> 

Both. But I think that the second one is handle properly because the `handle_result` will be called even if the results is an error
