### ISSUE TITLE
Handle 429 errors in client

### ISSUE THREAD

**Issue by JohannesMessner** [jina-ai/jina#4984]
When a 429 (too many requests) happens, the client should be able to report the status of the stream: what requests have been sent, what responses have been received.
The same may apply for other kinds of errors as well.

**Comment by JoanFM** [comment]
Also make sure proper documentation on Client section is added

**Comment by JohannesMessner** [comment]
Blocked because when I try to reproduce I run into the issue that https://github.com/jina-ai/jina/pull/5092 is fixing (I think). Waiting until that is merged, then we can go back to work on this.

**Comment by ZhengLin-Li** [comment]
@JohannesMessner Is this still a problem? as #5092 is merged, now we can come to a conclusion.
