### ISSUE TITLE
I have folowed the steps to start my own server and get bad client err

### ISSUE THREAD

**Issue by dwerkjem** [jina-ai/jina#4996]
**my err is**
 BadClient: something wrong when running the eventloop, result can not be retrieved

---

**Environment**
<- jina 3.6.9
- docarray 0.13.29
- jina-proto 0.1.12
- protobuf 3.19.1
- proto-backend cpp
- grpcio 1.47.0
- pyyaml 6.0
- python 3.9.12
- platform Linux
- platform-release 5.13.0-52-generic
- platform-version #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022
- architecture x86_64
- processor x86_64
- uid 135900331382138
- session-id e0c50776-fc8c-11ec-8e75-7b99c2fa157a
- uptime 2022-07-05T11:04:11.984997
- ci-vendor (unset)
* JINA_AUTH_TOKEN (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEFAULT_WORKSPACE_BASE /home/derek/.jina/executor-workspace
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_HUB_ROOT (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_DISABLE_HEALTHCHECK_LOGS (unset)
* JINA_LOCKS_ROOT (unset)>

**Screenshots**
![Screenshot_20220705_110818](https://user-images.githubusercontent.com/42622294/177389535-3963953f-7d13-4778-be9f-ecc39add0421.png)

**Comment by dwerkjem** [comment]
this might help some one solve this
`(base) derek@derek-ROG-Strix-G15CE-G15CE:~$ jina executor --name torch_indexer --uses config,yml  --native 

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWxxxxxxxxxOMMMMMNxxxxxxxxx0MMMMMKddddddxkKWMMMMMMMMMMMMXOxdddxONMMMM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllo0MMMMMMMM0olllllllllo0MM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOlllllllllllloWMMMMMdllllllllllllldM
MMMMMMMMMMMMXllllllllldMMMMM0lllllllllxMMMMMOllllllllllllloMMMM0lllllllllllllllK
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllllKMMM0lllllllllllllllO
MMMMMMMMMMMMKllllllllldMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMollllllllllllllO
MWOkkkkk0MMMKlllllllllkMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMxlllllllllllllO
NkkkkkkkkkMMKlllllllloMMMMMM0lllllllllxMMMMMOllllllllllllll0MMMMMMWOdolllllllllO
KkkkkkkkkkNMKllllllldMMMMMMMMWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MOkkkkkkk0MMKllllldXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWX00KXMMMMXxk0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM


/home/derek/anaconda3/bin/jina executor --name             
torch_indexer --uses config,yml --native                   
╭──────────────────────┬──────────────────────────────────╮
│             Argument │ Value                            │
├──────────────────────┼──────────────────────────────────┤
│                  cli │ executor                         │
│          compression │ None                             │
│      connection-list │ None                             │
│  disable-auto-volume │ False                            │
│       disable-reduce │ False                            │
│        docker-kwargs │ None                             │
│           entrypoint │ None                             │
│                  env │ None                             │
│   extra-search-paths │ []                               │
│             floating │ False                            │
│         force-update │ False                            │
│                 gpus │ None                             │
│                 host │ 0.0.0.0                          │
│              host-in │ 0.0.0.0                          │
│ install-requirements │ False                            │
│        k8s-namespace │ None                             │
│           log-config │ default                          │
│           monitoring │ False                            │
│                 name │ torch_indexer                    │
│               native │ True                             │
│     noblock-on-start │ False                            │
│    output-array-type │ None                             │
│             pod-role │ WORKER                           │
│              polling │ ANY                              │
│                 port │ 55369                            │
│      port-monitoring │ 59009                            │
│           py-modules │ None                             │
│                quiet │ False                            │
│          quiet-error │ False                            │
│    quiet-remote-logs │ False                            │
│             replicas │ 1                                │
│              retries │ -1                               │
│          runtime-cls │ WorkerRuntime                    │
│             shard-id │ 0                                │
│               shards │ 1                                │
│         timeout-ctrl │ 60                               │
│        timeout-ready │ 600000                           │
│         timeout-send │ None                             │
│         upload-files │ None                             │
│                 uses │ config,yml                       │
│   uses-after-address │ None                             │
│  uses-before-address │ None                             │
│           uses-metas │ None                             │
│        uses-requests │ None                             │
│            uses-with │ None                             │
│              volumes │ None                             │
│            workspace │ None                             │
│         workspace-id │ 91ff0b303f8042818921af225b3efd3b │
╰──────────────────────┴──────────────────────────────────╯
ERROR  torch_indexer@353903 fail to load file dependency                                                                                                                  [07/05/22 17:13:29]
Traceback (most recent call last):
  File "/home/derek/anaconda3/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina_cli/api.py", line 76, in executor
    return executor_native(args)
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina_cli/api.py", line 57, in executor_native
    with runtime_cls(args) as rt:
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py", line 31, in __init__
    super().__init__(args, **kwargs)
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/asyncio.py", line 66, in __init__
    self._loop.run_until_complete(self.async_setup())
  File "/home/derek/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py", line 58, in async_setup
    await self._async_setup_grpc_server()
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/worker/__init__.py", line 68, in _async_setup_grpc_server
    self._data_request_handler = DataRequestHandler(
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 41, in __init__
    self._load_executor(metrics_registry)
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 79, in _load_executor
    self._executor: BaseExecutor = BaseExecutor.load_config(
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/jaml/__init__.py", line 688, in load_config
    stream, s_path = parse_config_source(
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/jaml/helper.py", line 169, in parse_config_source
    comp_path = complete_path(path, extra_search_paths)
  File "/home/derek/anaconda3/lib/python3.9/site-packages/jina/jaml/helper.py", line 218, in complete_path
    raise FileNotFoundError(f'can not find {path}')
FileNotFoundError: can not find config,yml
`

**Comment by JoanFM** [comment]
Can you explain exactly what steps are you following?

**Comment by dwerkjem** [comment]
https://github.com/jina-ai/dalle-flow#server

**Comment by dwerkjem** [comment]
this is the docker err I get wen submiting to the server
![recta](https://user-images.githubusercontent.com/42622294/177503003-80b0dad0-93ce-46d8-9cc9-136c5add05d2.png)

**Comment by JoanFM** [comment]
may you try to start the server by settting environment variable `JINA_LOG_LEVEL = DEBUG`? Also make sure you have enough resources or reduce the number of replicas

**Comment by dwerkjem** [comment]
> may you try to start the server by settting environment variable `JINA_LOG_LEVEL = DEBUG`? Also make sure you have enough resources or reduce the number of replicas

### my specs
```name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 10240 MB
    Total available memory: 10240 MB
    Currently available dedicated video memory: 9278 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 515.48.07
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 515.48.07
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 515.48.07
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20```

**Comment by dwerkjem** [comment]
> may you try to start the server by settting environment variable `JINA_LOG_LEVEL = DEBUG`? Also make sure you have enough resources or reduce the number of replicas

setting "JINA_LOG_LEVEL = DEBUG" by runing `JINA_LOG_LEVEL=DEBUG` didnt seem to do anything

**Comment by JoanFM** [comment]
> > may you try to start the server by settting environment variable `JINA_LOG_LEVEL = DEBUG`? Also make sure you have enough resources or reduce the number of replicas
> 
> ### my specs
> ```
> display: :0  screen: 0
> direct rendering: Yes
> Memory info (GL_NVX_gpu_memory_info):
>     Dedicated video memory: 10240 MB
>     Total available memory: 10240 MB
>     Currently available dedicated video memory: 9278 MB
> OpenGL vendor string: NVIDIA Corporation
> OpenGL renderer string: NVIDIA GeForce RTX 3080/PCIe/SSE2
> OpenGL core profile version string: 4.6.0 NVIDIA 515.48.07
> OpenGL core profile shading language version string: 4.60 NVIDIA
> OpenGL core profile context flags: (none)
> OpenGL core profile profile mask: core profile
> 
> OpenGL version string: 4.6.0 NVIDIA 515.48.07
> OpenGL shading language version string: 4.60 NVIDIA
> OpenGL context flags: (none)
> OpenGL profile mask: (none)
> 
> OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 515.48.07
> OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20```
> ```

make sure that you have all the hardware requirements stated here https://github.com/jina-ai/dalle-flow#hardware-requirements

**Comment by dwerkjem** [comment]
I dont meet all the hardware requirements
