### ISSUE TITLE
the example for CLIPImageclassifier doesn't work

### ISSUE THREAD

**Issue by sk-haghighi** [jina-ai/jina#5002]
**Describe the bug**

**Describe how you solve it**
```python
from docarray import Document, DocumentArray

da = DocumentArray([Document(text='hello')])
r = da.post('jinahub+sandbox://CLIPImageClassifier/latest')

print(r.to_json())
```

**Environment**
jina                        3.6.9

torch                    1.9.0+cpu
torchvision            0.10.0+cpu
transformers        4.9.1

**Screenshots**
Exception in thread Thread-37:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/my_env_p3.9/lib/python3.9/site-packages/jina/helper.py", line 1292, in run
    self.result = asyncio.run(func(*args, **kwargs))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/ubuntu/my_env_p3.9/lib/python3.9/site-packages/jina/clients/mixin.py", line 176, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/ubuntu/my_env_p3.9/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 90, in _get_results
    callback_exec(
  File "/home/ubuntu/my_env_p3.9/lib/python3.9/site-packages/jina/clients/helper.py", line 81, in callback_exec
    raise BadServer(response.header)
jina.excepts.BadServer: request_id: "135e5e93169c4906bf1ac00270cc243c"
status {
  code: ERROR
  description: "AttributeError(\"\'DocumentArrayInMemory\' object has no attribute \'get_attributes\'\")"
  exception {
    name: "AttributeError"
    args: "\'DocumentArrayInMemory\' object has no attribute \'get_attributes\'"
    stacks: "Traceback (most recent call last):\n"
    stacks: "  File \"/usr/local/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py\", line 165, in process_data\n    return await self._data_request_handler.handle(requests=requests)\n"
    stacks: "  File \"/usr/local/lib/python3.8/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py\", line 150, in handle\n    return_data = await self._executor.__acall__(\n"
    stacks: "  File \"/usr/local/lib/python3.8/site-packages/jina/serve/executors/__init__.py\", line 290, in __acall__\n    return await self.__acall_endpoint__(__default_endpoint__, **kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/site-packages/jina/serve/executors/__init__.py\", line 311, in __acall_endpoint__\n    return func(self, **kwargs)\n"
    stacks: "  File \"/usr/local/lib/python3.8/site-packages/jina/serve/executors/decorators.py\", line 216, in arg_wrapper\n    return fn(executor_instance, *args, **kwargs)\n"
    stacks: "  File \"/workspace/clip_image_classifier.py\", line 59, in classify\n    image_batch = docs_batch.get_attributes(\'blob\')\n"
    stacks: "AttributeError: \'DocumentArrayInMemory\' object has no attribute \'get_attributes\'\n"
    executor: "CLIPImageClassifier"
  }
}
exec_endpoint: "/latest"

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/my_env_p3.9/lib/python3.9/site-packages/jina/helper.py:1307, in run_async(func, *args, **kwargs)
   1306 try:
-> 1307     return thread.result
   1308 except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)
Input In [3], in <cell line: 4>()
      1 from docarray import Document, DocumentArray
      3 da = DocumentArray([Document(text='hello')])
----> 4 r = da.post('jinahub+sandbox://CLIPImageClassifier/latest')
      6 print(r.to_json())

File ~/my_env_p3.9/lib/python3.9/site-packages/docarray/array/mixins/post.py:64, in PostMixin.post(self, host, show_progress, batch_size, parameters, **kwargs)
     62     f = Flow(quiet=True, prefetch=1).add(uses=standardized_host)
     63     with f:
---> 64         return f.post(
     65             _on,
     66             inputs=self,
     67             show_progress=show_progress,
     68             request_size=batch_size,
     69             parameters=parameters,
     70             **kwargs,
     71         )
     72 elif _scheme in ('grpc', 'http', 'ws', 'websocket'):
     73     from jina import Client

File ~/my_env_p3.9/lib/python3.9/site-packages/jina/clients/mixin.py:185, in PostMixin.post(self, on, inputs, on_done, on_error, on_always, parameters, target_executor, request_size, show_progress, continue_on_error, return_responses, **kwargs)
    182     if return_results:
    183         return result
--> 185 return run_async(
    186     _get_results,
    187     inputs=inputs,
    188     on_done=on_done,
    189     on_error=on_error,
    190     on_always=on_always,
    191     exec_endpoint=on,
    192     target_executor=target_executor,
    193     parameters=parameters,
    194     request_size=request_size,
    195     **kwargs,
    196 )

File ~/my_env_p3.9/lib/python3.9/site-packages/jina/helper.py:1311, in run_async(func, *args, **kwargs)
   1308     except AttributeError:
   1309         from jina.excepts import BadClient
-> 1311         raise BadClient(
   1312             'something wrong when running the eventloop, result can not be retrieved'
   1313         )
   1314 else:
   1316     raise RuntimeError(
   1317         'you have an eventloop running but not using Jupyter/ipython, '
   1318         'this may mean you are using Jina with other integration? if so, then you '
   1319         'may want to use Client/Flow(asyncio=True). If not, then '
   1320         'please report this issue here: https://github.com/jina-ai/jina'
   1321     )

BadClient: something wrong when running the eventloop, result can not be retrieved

**Comment by JoanFM** [comment]
Hello @sk-haghighi, yes the example will not work because the classifier expects an image and not text to be in the input document.

**Comment by JoanFM** [comment]
This is a problem that we will address by having a warning in the website, thanks for the heads up and I will close this issue
