### ISSUE TITLE
Getting an error regarding the document object attribute

### ISSUE THREAD

**Issue by sk-haghighi** [jina-ai/jina#5003]
**Describe the bug**
I am trying to convert an image to  image_blob but jina says  'Document' object has no attribute 'load_uri_to_image_blob'

**Describe how you solve it**

---

**Environment**
transformers           4.9.1
jina                   3.6.9
torch                  1.9.0+cpu
torchvision            0.10.0+cpu
python 3.9

[](url)
**Screenshots**
 I am wondering if this is a version issue

**Comment by sk-haghighi** [comment]
![Error message](https://user-images.githubusercontent.com/65980606/178159654-1eb2941a-0696-49f8-b0d3-46a1ff5cab81.jpg)

**Comment by sk-haghighi** [comment]
<img width="394" alt="er" src="https://user-images.githubusercontent.com/65980606/178159813-226b2284-d3db-4174-9fb5-0c61b91c60de.PNG">

**Comment by JoanFM** [comment]
Hey @sk-haghighi,

This is indeed a version issue, as the DocumentArray changed its API. We will try to migrate to the newest API as soon as possible

**Comment by JoanFM** [comment]
Hey @sk-haghighi,

A new version of the Executor has been published adapted to the new `Document API` so it should work nbow
