### ISSUE TITLE
deploy-netlify failing

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5020]
**Describe the bug**
deploy-netlify in CI seems to be failing.

Run example:
https://github.com/jina-ai/jina/runs/7433085362?check_suite_focus=true

Similar issue found in other projects https://github.com/pytorch/serve/issues/1744

**Comment by msaroufim** [comment]
Hi @JoanFM did you end up figuring out what the solution to this is? Your PR seemed like a more general feature when I skimmed it
