### ISSUE TITLE
CustomGateway: Allow usage of Flow connectivity from a custom Gateway

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5032]
# Custom Gateway 

We want to allow users to define their own Gateway. 

## Context

The point is that atm many users put a fastAI in front of our gateway to translate the docarray syntax to their own specific needs.
This is an issue since for performance. 

## What could be done

Our gateway is basically two things: an API (grpc or http server) and the core logic to handle the Flow.We could have more flexibility and let the user create their own API to fit to their requirement and logic. 

- [x] refactor code so that the `TopolofyGrapg` the `ConnectionPool` and the `Streamer` live into the same object https://github.com/jina-ai/jina/pull/5031

Left to do:
- [x] Refactor and separate gateway logic from runtime https://github.com/jina-ai/jina/pull/5153
- [x] Rename any BFF to CustomGateway
- [x] Rename `GatewayBFF` into a new name and clarify arguments and API so that it can be useful by user.
- [x] Allow `ContainerPod` to work with a `Gateway`
- [x] investigate whether it is possible to start gateway with local object/module
- [x] Allow users to pass `uses` for the `gateway`. Here we have 2 options: Allow only to pass  a docker image or maybe we can also allow to pass something local (In this case we could assume is a `FastAPI` app or something (it is the most common usage observed so far). https://github.com/jina-ai/jina/pull/5189
- [x] Have a syntax on the Flow side,  maybe `Flow(uses=CustomGateway)`
- [x] Add expose gateway API in Flow API as a separate set of args:
`Flow().config_gateway()` (or add gateway)
- [x] Define the proper user journey to enable this feature both locally and with docker.
- [x] Define how this new docker container or object will receive the parameters that will allow the user to instantiate this `GatewayBFF` and use it.
- [x] Document this
- [ ] Blog post about the feature and what enables

**Comment by alaeddine-13** [comment]
As Documentation was merged, I'm closing this issue
