### ISSUE TITLE
Allow dynamic batching in Executor

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5033]
**Describe the feature**
We have seen that the simple `Request-Response` model with a static `request_size` is limiting in some cases. For instance some `Encoders` would rather accumulate `requests` until a big `enough` batch is accumulated and then all encoded at once. This could be used to improve `throughput` at a potential cost of `latency`.

How can I imagine the Feature:

In `executor.py`:

```python
from jina import Executor, requests, dynamic_batch

class DynamicBatchExecutor(Executor):

    @requests
    @dynamic_batch(batch_size=...) # potentially other arguments
     def foo(self, docs, **kwargs): 
           # decorator makes sure X docs arrive here (X being batch size)
           pass
```

Should the `Executor` do it or allowed to be passed dynamically in the `Runtime`? To be decided as it is more of a UI issue

This would affect the `Req-Response` model in the gateway. How I would solve it without affecting the `Request-Response` model from the client?

- [ ] In our proto, have some field in the `Response` stating that Response is yet to be served.
- [ ] The gateway keeps a map with the `request_id` and the `doc_ids` present there. 
- [ ] The gateway waits for the next Response that is served from that node, and then fires the continuation of all the waiting `Requests` with the appropiate `Documents` attached.

This way, we achieve.

- [ ] Dynamic batching
- [ ] The rest of the Flow and Executors do not realize about this. 
- [ ] The interface with the Client is kept. Single `request-response` model is kept from user perspective

Small hidden implementation details:
- How to deal with the last hanging docs.
- Imagine I have dynamic_batch_size of 50 and I just send 102 Documents. How to handle the 2 remaining Docs? I just have a timeout or something?

**Comment by mister-fahrenheit** [comment]
@JoanFM @JohannesMessner hey!
I am very interested in this feature. Can you tell, what is the progress here?

Also, can you add `timeout` parameter for `@dynamic_batch` which tells Executer to process all pending requests if some of them is older than `timeout` and their amount lower than `batch_size`?

**Comment by JohannesMessner** [comment]
I am currently finishing off some other work and will start with the implementation of this feature this week.
And yes, we will most likely have a mechanism that allows non-complete batches to be processed, a `timeout` seems reasonable.

@mister-fahrenheit do you have any other requirements or wishes for this feature? Anything about your use case that you would want to share? We are always happy to get inspiration from our users for features like this!

**Comment by JohannesMessner** [comment]
Ok perfect, that is exactly what we have in mind and should be nicely covered by this feature. I'll keep you posted on the progress!

**Comment by JohannesMessner** [comment]
Hey @mister-fahrenheit, dynamic batching has been merged and will be in the next release of Jina! Thank you for your input, and thanks to @Jackmin801 and @alaeddine-13 for the great work 🚀

**Comment by mister-fahrenheit** [comment]
@JohannesMessner that's awesome, thank you!
