### ISSUE TITLE
How to build services for indexing and querying in Django

### ISSUE THREAD

**Issue by jfernandrezj** [jina-ai/jina#5063]
**Describe your proposal/problem**
I am implementing a service to index and search a media collection from s3.
Training and searching are both long running processes. 
Im trying to implement them in the best way in Django / DjangoRest, so after retrieval I can get a lot more info from the DB using Django Models.

Tips on:
How to index from S3 directly?
How to design the endpoint in Django / DjangoRest? asgi, opening web sockets...?
Much appreciated

**Comment by samsja** [comment]
Hey @jfernandrezj 

It seems that you question is not directly related to jina and this repo.  Therefore the github issue is not the best place to discuss about your question.

I believe what you want to build can be done using our famework, so you can check the docs and get started.

Feel free to join our [slack channel](https://slack.jina.ai/) to ask your question about django and anything else regarding jina or search :smile:
