### ISSUE TITLE
CI pipeline includes Python 3.9

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#507]
**Describe the feature**

https://docs.python.org/3.9/whatsnew/3.9.html

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
https://pyreadiness.org/3.9/

requiring our five base dependencies to be green

**Comment by bwanglzu** [comment]
Python 3.9 has [released](https://www.python.org/downloads/release/python-390/) on oct 10, shall we reopen this one?
