### ISSUE TITLE
feat: Grafana executor latency breakdown by endpoints

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5085]
As you can see in this graphic, it looks like our executors got faster over time, but it is not the case.
<img width="641" alt="image" src="https://user-images.githubusercontent.com/11627845/186400078-b31478c8-ecf1-4a68-be46-8776d04abc46.png">
The reason why the processing time is increasing is that we first made indexing requests and then search requests. Indexing takes longer for the preprocessing executor because we need to process the videos. Searching is fast, because, we just forward the search text and no huge preprocessing is done.
So, we loose basically all information in this graphic. We don't know how long indexing take and don't know how long search take.

User acceptance criteria:
- [ ] each endpoint which got called will cause a new graphic in the dashboard

**Comment by samsja** [comment]
Thanks @florian-hoenicke for reporting the issue.

We actually already cover this feature. You should use the `jina_receiving_request_seconds` which will have as a labels the `exec_endpoint`. I believe right now your dashboard is just using the wrong metrics `jina_process_request_seconds` More info in the [documentation](https://docs.jina.ai/fundamentals/flow/monitoring-flow/#executor-pods)

Morevover, the jina responsibility about metrics is to expose them. We recommend to use Grafana to visualize it but we do not maintain any official dashboard. Therefore it will be better for us and for future people opening the issue if next you could report the issue at the metrics levels and not at the dashboard levels, i.e. by saying "metrics `jina_abcd` does not support this".

**Comment by samsja** [comment]
Thanks @florian-hoenicke for reporting the issue.

We actually already cover this feature. You should use the `jina_receiving_request_seconds` which will have as a labels the `exec_endpoint`. I believe right now your dashboard is just using the wrong metrics `jina_process_request_seconds` More info in the [documentation](https://docs.jina.ai/fundamentals/flow/monitoring-flow/#executor-pods)

Morevover, the jina responsibility about metrics is to expose them. We recommend to use Grafana to visualize it but we do not maintain any official dashboard. Therefore it will be better for us and for future people opening the issue if next you could report the issue at the metrics levels and not at the dashboard levels, i.e. by saying "metrics `jina_abcd` does not support this".
