### ISSUE TITLE
Raise an error, when set protocol='http',  enable monitoring with replicas and pass a list of port_monitoring separated by a comma to your Flow

### ISSUE THREAD

**Issue by vpegasus** [jina-ai/jina#5086]
**Describe the bug**

In this page: https://docs.jina.ai/fundamentals/flow/monitoring-flow/

 "To enable monitoring with replicas and shards when deploying natively, you need to pass a list of port_monitoring separated by a comma to your Flow."

following this instruction, I set  port_monitoring with value "9090, 9091",  and at the same time, we set **protocol = 'http'**,
raising an error, when start a flow:

**Describe how you solve it**

```
f = Flow(port=16411, protocol='http', monitoring=True, port_monitoring=16412). \
    add(uses='docker://executor_img', replicas=2, port_monitoring='9091,9092')

with f:
    f.block()
```
---

**Environment**

jina version 3.7.14
**Screenshots**

$ python flow.py 
usage: flow.py [-h] [-v] [-vf] [--name] [--workspace] [--log-config] [--quiet] [--quiet-error] [--timeout-ctrl] [--polling] [--uses]
               [--uses-with [KEY: VALUE [KEY: VALUE ...]]] [--uses-metas [KEY: VALUE [KEY: VALUE ...]]] [--uses-requests [KEY: VALUE [KEY: VALUE ...]]]
               [--py-modules [PATH [PATH ...]]] [--port-in] [--host-in] [--native] [--output-array-type] [--prefetch] [--title] [--description] [--cors]
               [--no-debug-endpoints] [--no-crud-endpoints] [--expose-endpoints] [--uvicorn-kwargs [KEY: VALUE [KEY: VALUE ...]]]
               [--grpc-server-kwargs [KEY: VALUE [KEY: VALUE ...]]] [--ssl-certfile] [--ssl-keyfile] [--expose-graphql-endpoint] [--protocol {GRPC, HTTP, WEBSOCKET}]
               [--host] [--proxy] [--port-expose] [--graph-description] [--graph-conditions] [--deployments-addresses] [--deployments-disable-reduce]
               [--compression {NoCompression, Deflate, Gzip}] [--timeout-send] [--runtime-cls] [--timeout-ready] [--env [KEY: VALUE [KEY: VALUE ...]]] [--shards]
               [--replicas] [--port] [--monitoring] [--port-monitoring] [--retries] [--floating]

**flow.py: error: argument --port-monitoring: invalid int value: '9091,9092'**

**Comment by samsja** [comment]
Hey it seems that this is exactly the same issue as this [one](Teil des Entwicklungsteams) So I will close this issue and you can continue to follow the progress on the other issue
