### ISSUE TITLE
Add --exit-exceptions parameter to Executor

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5110]
**Describe the feature**
Add --exit-exceptions parameter to the Executor, such that when Executor raises this Exception from a `bound` method, the Runtime sends `exit(1)` signal so that K8s reschedules the Pod.

Usage example:

```jina executor ... --exit-exceptions CUDA_MEMORY_ERROR,OUT_OF_MEMORY_ERROR```

**Comment by hanxiao** [comment]
just fyi, please use ` --exit-on-exceptions` or other better names, `--exit-exceptions` is just a random name I thraw into the channel.

**Comment by hanxiao** [comment]
Raised by community is added because it was raised by FeverDream besides Degi
