### ISSUE TITLE
Remove field afterwards & before sending back

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#5119]
Feature request from Slack community.

OP: https://jina-ai.slack.com/archives/C0169V26ATY/p1661666644505419

Snippet, full thread see ⬆️ 

> Basically, the feature will be adding a new syntax that allows each Excecutor and the Gateway to post-filter Document according to [this syntax](https://docarray.jina.ai/fundamentals/documentarray/access-attributes/#attribute-selector) before sending to the next one (in Gateway’s case, the next one is the Client).
The feature would looks like:

```
executor:
  - select_after: '[:, 'scores__cosine__value']'
 ```

**Comment by JoanFM** [comment]
This will be solved properly in the context of Custom Gateway

**Comment by JoanFM** [comment]
This is closed as the Custom Gateway allows the user to dynamically remove fields and use their own API
