### ISSUE TITLE
BaseKVIndexer is too lazy, it only loads data on the first query

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#512]
**Describe your problem**

Can't really remember if it is desired behavior or not. Kinda annoying when the first query is slow.

**What is your guess?**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
```text
index [=                   ] 📃    488 ⏱️ 114.5s 🐎 4.3/s     61 batch        doc_idx@14885[I]:received "index" from gateway▸⚐
index [===                 ] 📃    504 ⏱️ 116.8s 🐎 4.3/s     63 batch        gateway@14867[I]:#sent: 63 #recv: 63 sent_size: 613.0 MB recv_size: 1.5 GB
    [116.766 secs]
	✅ done in ⏱ 116.8s 🐎 4.3/s
        gateway@14867[S]:terminated
        gateway@14867[S]:terminated
        doc_idx@14885[I]:received "control" from ctl▸⚐
        doc_idx@14885[I]:break from the event loop
        doc_idx@14885[S]:artifacts of this executor (doc_indexer) is persisted to ./workspace/doc_indexer.bin
        doc_idx@14885[I]:dumped changes to the executor, 117s since last the save
        doc_idx@14885[I]:#sent: 63 #recv: 64 sent_size: 1.5 GB recv_size: 613.0 MB
           Flow@14867[S]:flow is closed and all resources should be released already, current build level is EMPTY
        doc_idx@14885[I]:#sent: 64 #recv: 64 sent_size: 1.5 GB recv_size: 613.0 MB
        doc_idx@14885[S]:terminated
```

**Comment by hanxiao** [comment]
new binary implementation

```
index [===                 ] 📃    504 ⏱️ 87.3s 🐎 5.8/s     63 batch        gateway@15097[I]:#sent: 63 #recv: 63 sent_size: 613.0 MB recv_size: 1.5 GB
    [87.373 secs]
	✅ done in ⏱ 87.4s 🐎 5.8/s
        gateway@15097[S]:terminated
        gateway@15097[S]:terminated
```

**Comment by hanxiao** [comment]
`flush_on_add=True` gives better performance, interesting

**Comment by fhaase2** [comment]
@hanxiao i had a look into this. This should not only concern `BaseKVIndexer`, but rather all indexers that extend from `BaseIndexer `. 

As far as i understand, the decision when to load is currently implemented 
here:

https://github.com/jina-ai/jina/blob/c21a145c929de575448e301961828e97130a6d2e/jina/executors/indexers/__init__.py#L80

Does something speak against calling the loading in the `post_init` method of `BaseIndexer `?

  https://github.com/jina-ai/jina/blob/c21a145c929de575448e301961828e97130a6d2e/jina/executors/indexers/__init__.py#L57

I tried it locally and it works as expected. But i am not sure if it could break something else.

**Comment by hanxiao** [comment]
so far i think the behavior is acceptable especially after `BaseNumpyIndexer` is refactored in #589
