### ISSUE TITLE
Using Jina and Documents with Pytorch Tensors

### ISSUE THREAD

**Issue by nrakltx** [jina-ai/jina#5121]
**Describe your proposal/problem**
Hello,
I wish to create a pipeline with multiple microservices, all of which run on GPU. I want to pass the GPU tensors needed for each Executor through the DocumentArray parameter, specifically with the Document.tensor property. I haven't been able to do this yet since Jina errors nondescriptly about some Numpy array not being runnable. Included is my minimal running example.
```python
from jina import DocumentArray, Executor, Flow, Document, requests, Client
import torch
class FirstExecutor(Executor):
    @requests()
    def execute(self, docs: DocumentArray, **kwargs) -> DocumentArray:
        res = []
        for text in docs.texts:
            # do something with the text
            res.append(Document(tensor=torch.ones((30, 1024, 450), device="cuda:0")))
        return DocumentArray(res)


class SecondExecutor(Executor):
    @requests
    def execute(self, docs: DocumentArray, **kwargs):
        res = []
        for tensor in docs.tensors:
            res.append(Document(text="output")) 
        return DocumentArray(res)


def main():
    f = Flow().add(name="first_exec", uses=FirstExecutor).add(name="second_exec")
    with f:
        c = Client(port=f.port, host=f.host)
        res = c.post("/", Document(text="test"))
        print(res.texts)


if __name__ == "__main__":
    main()
```
This should return "output", and not error/warn about numpy arrays not being writable, but doesn't. I have a GPU (nvidia-smi shows it).
The issue seems to be with some conversion to numpy and back, but I can't figure out anything since there is no stack trace. I get the following output:
```
UserWarning: multiprocessing start method is set to `spawn` (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/jina/__init__.py:48)
⠹ Waiting first_exec second_exec gateway summary... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/4 0:00:00UserWarning: failed to set multiprocessing start_method to `spawn`: RuntimeError('context has already been set') (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/jina/__init__.py:52)
UserWarning: failed to set multiprocessing start_method to `spawn`: RuntimeError('context has already been set') (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/jina/__init__.py:52)
UserWarning: failed to set multiprocessing start_method to `spawn`: RuntimeError('context has already been set') (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/jina/__init__.py:52)
───────────────────────────────────────────────────────────────────────────────── 🎉 Flow is ready to serve! ──────────────────────────────────────────────────────────────────────────────────
╭────────────── 🔗 Endpoint ───────────────╮
│  ⛓     Protocol                    GRPC  │
│  🏠       Local           0.0.0.0:62906  │
│  🔒     Private       10.20.0.108:62906  │
│  🌍      Public    *************:62906  │
╰──────────────────────────────────────────╯
UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.) (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/docarray/proto/io/ndarray.py:149)
UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ../torch/csrc/utils/tensor_numpy.cpp:172.) (raised from /opt/conda/envs/triton_env/lib/python3.8/site-packages/docarray/proto/io/ndarray.py:149)
['']
```

Thank you very much in advance,

NR
---

**Environment**
- jina 3.8.2
- docarray 0.16.2
- jcloud 0.0.35
- jina-hubble-sdk v0.0.0
- jina-proto 0.1.13
- protobuf 4.21.5
- proto-backend upb
- grpcio 1.48.1
- pyyaml 6.0
- python 3.8.13
- platform Linux
- platform-release 4.19.0-21-cloud-amd64
- platform-version #1 SMP Debian 4.19.249-2 (2022-06-30)
- architecture x86_64
- processor
- uid 72572231483500
- session-id 9b733310-2c47-11ed-919f-42010a14006c
- uptime 2022-09-04T11:49:17.739548
- ci-vendor (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD spawn
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
**Screenshots**

**Comment by JoanFM** [comment]
Hello @nrakltx,

Have u read this part of Documentation? maybe you find it helpful.

https://docs.jina.ai/fundamentals/flow/add-executors/?highlight=ndarray#unify-ndarray-types-in-output

**Comment by nrakltx** [comment]
Thanks for the quick response!
This says Jina converts every output to numpy for compatibility, did I understand correctly?
Is there a way to disable this, or to convert to `torch` instead of `numpy`? I tried setting `output_array_type` to `torch` and `pytorch` and it didn't help.
I just want to keep it a torch tensor, hopefully on the GPU too (and ideally without having copies between Executors).

Thanks again!

**Comment by JoanFM** [comment]
Hello @nrakltx,

On the GPU it will be impossible I am afraid, because the DocArray is serialized and sent to the next Executor, which I believe is not possible for the one in GPU. 

Can you try if it works if you do not load the tensor on GPU?

**Comment by nrakltx** [comment]
Tried with both of `torch` and `pytorch` and didn't work either way when device is 'cpu'.
Does this mean the only options is to copy to torch GPU tensor in the beginning of every executor and copy to CPU np array when finishing?

**Comment by JoanFM** [comment]
Sorry for the missleading link, I think the `output_array_type` should not affect here.

**Comment by JoanFM** [comment]
> Thanks for the quick response! This says Jina converts every output to numpy for compatibility, did I understand correctly? Is there a way to disable this, or to convert to `torch` instead of `numpy`? I tried setting `output_array_type` to `torch` and `pytorch` and it didn't help. I just want to keep it a torch tensor, hopefully on the GPU too (and ideally without having copies between Executors).
> 
> Thanks again!

If you want to keep `torch` Tensors you should forget about having `output_array_type` and remember to move to 'cpu' the embeddings before ending the request.

It is impossible not having copies between Executors. These Executors are running in different processes with their own memory space and therefore they do not share the data in memory. 

This is wrong understanding

**Comment by nrakltx** [comment]
Ok, that clears up some things.
So I tried using torch tensors on cpu both on embedding and tensor attributes of document and it still complains about converting to numpy etc., can you help me solve this issue? (minimal code example is the original one just without device="cuda:0").

**Comment by JoanFM** [comment]
Hey @nrakltx .

I am not sure about the warning, but what u are definitely missing is to tell the Flow to use `SecondExecutor` as the Executor for the second one.

```.add(name="second_exec", uses=SecondExecutor)```

**Comment by nrakltx** [comment]
Wow, that was stupid of me. Now when running it with a GPU tensor it seems to implicitly convert it to torch CPU.
Thank you, I'm closing this issue.
