### ISSUE TITLE
ABOUT 'JinaLogger.__init__.<locals>.<lambda>' 

### ISSUE THREAD

**Issue by Elvisambition** [jina-ai/jina#5128]
when i use pickle to dump tfidfvectorizer, it throws AttributeError: Can't pickle local object JinaLogger __init__ "locals""lambda"

**Comment by JoanFM** [comment]
Hello @Elvisambition ,

Where can I see the code of this `TFIDFVectorizer`?

**Comment by JoanFM** [comment]
You can always define the methods:

```python
     def __getstate__(self):

     def __setstate__(self, d):
```

to avoid pickling unpickable objects and to recreate them after unpickling

**Comment by JoanFM** [comment]
Hello @Elvisambition ,

Is this still an issue?

**Comment by JoanFM** [comment]
I will close for now, if you encounter the problem again, please reopen with more details
