### ISSUE TITLE
Error message should propagate through the workflow in the query time

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#513]
**Describe the feature**

Right now a single error in the query time will break the whole system.

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by rutujasurve94** [comment]
Hi! I'd like to contribute to this issue

**Comment by hanxiao** [comment]
❤️ Awesome! thanks for taking the initiative!

Let me explain the issue in more details.

Right now when an `Executor` throws an exception, the `Pod` catches and breaks from the eventloop. No message will be propagated further. The followed `Pod` in this workflow stuck there forever as they work in `recv->handle->send` way. Since there is no receive, nothing happens. The gateway receives nothing and has nothing to return to the client. So everybody stuck there forever.

There are many ways to solve this problem, the simplest way I have in mind is:
- Adding a `status` field in the Protobuf `Envelope`, when a Pod throws a RuntimeError, it changes the `status` to `error`, and propagates the message further. Also better keeps the exception message in the message.
- The followed Pods simply skip the handling part and propagate it further when they see the `error` status in the envelope.
- The gateway returns the error code and message to the client.

**Comment by rutujasurve94** [comment]
Thanks a lot for the leads and details on the issue, I will begin the implementation along these steps and update here

**Comment by rutujasurve94** [comment]
Hello,
I've opened PR: https://github.com/jina-ai/jina/pull/521 for this issue.
**Proposal for the feature:**
-  Changes to Protobuf ```Envelope```: this already has a ```Status``` field where status could be 'Error'. Captured the error's message as well by adding a field  ```error_message``` to this proto.
-  Built the new changes to proto with ```build-proto-with-python.sh``` script in the proto directory,  auto-modifying ```jina_pb2.py```,  ```jina_pb2_grpc.py```.
-  Added an Exception ```PodRunTimeError``` that could be generically used to raise exceptions every time the pod throws a run exception.
-  In pea: Changed the status of the message to error every time a run time exception is thrown in the loop body, propagating the message further.
-  Changed the pea's ```handle``` method: Pods simply skip the handling part and propagate it further when they see the error status in the envelope. 
- Changes to gateway: ```handle``` method: The gateway check's if the received message's envelope has Error status, in this case it returns the error code and message to the client. 

**Further evaluations:**
- [ ] Evaluated the ```msg_callback``` that catches NoExplicitMessage and passes when no message/ partial message is received.  No changes required here
- [ ]  Evaluated the drivers: ```control.py``` and  ```jina_pb2.Request.ControlRequest.STATUS```: also don't require changes.

**CI Checks Status**:
- Checks for lint, installation, unit tests, etc. pass on CI. 
- Requesting permissions for CLA. Pending check on CI for PR-Labeler.

@hanxiao : It would be great to have your review, requesting your feedback on the implementation.

**Comment by policeme** [comment]
if a Exception happened in index time, should we close all pods, and stop indexing?
