### ISSUE TITLE
Change the way to decide if a version is released

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5148]
The way we currently check if a version is released has lead to jCloud outage out of our control, this needs to be refactored.

Link issue:

https://github.com/jina-ai/jina/issues/5145

We may need to change our release procedure

**Comment by samsja** [comment]
More info here : https://www.notion.so/Release-procedure-7b7172cc57984aa4bd8af81ed94d2229

But to sump up:

We stick to: 
- a release with **only fixes** is a **patch** ( 3.12.x)
- a release with ****at least ****one **feature** or one **breaking change** is a **minor** (3.x.0)
- a release with **major API redesign***  is a **major**  (x.0.0)

Nevertheless we reduce the release frequency to produce consistent release and rely on release candidate more often.

Follow up ticket : https://github.com/jina-ai/jina/issues/5266
