### ISSUE TITLE
Metrics on the gateway should always contained a label based on the Executor target

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#5154]
# Context

At the moment the gateway average all of its metrics and does not allow users to make distinction between different Executor.

To give an example:

Lets say we have a flow with two executors, one takes a lot of time to process the other one take few times.

At the moment the `jina_sending_request_seconds` metrics for instance will just average both of them

Actually this was not an issue initially since you can actually do the separation at the at the Executor level but the issue is with external Executor where you will have metrics coming from all the different flow.

# Proposition

Therefore we should rather measure the metrics on gateway level depending on which Executor the request is send.

Note: telemetry and tracing will also fix this problem

**Comment by JoanFM** [comment]
I think then we should duplicate metrics and have `gateway` measure Executor latency regardless of anything

**Comment by samsja** [comment]
gotcha makes sense
