### ISSUE TITLE
Configurable circuit breakers for dependencies

### ISSUE THREAD

**Issue by girishc13** [jina-ai/jina#5158]
**Describe the feature**
Circuit breakers enable upstream and downstream services to gracefully recover from temporary errors. During the recovery phase of the affected service, additional requests will continue to fail until the service can recover. By using circuit breakers, the upstream dependency can pause the traffic for the configured amount of time which allows the recovering downstream dependency to utilize all system resources for recovery rather than handling requests that will eventually fail.

**Your proposal**

I will do some research to find python libraries that can support good configuration and can handle synchronous and asynchronous operations.

---

**Environment**

**Screenshots**

**Comment by Adesoji1** [comment]
@girishc13 import asyncio  from python is what i think might be of help but how do i reproduce the issue?
