### ISSUE TITLE
logserver /profile is broken, dashboard not responding

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#516]
**Describe your problem**

Not sure since when,

![image](https://user-images.githubusercontent.com/2041322/84433605-d463ba00-ac2e-11ea-9f63-4e9cad2c466b.png)

The log stream and flow chart works fine though

![image](https://user-images.githubusercontent.com/2041322/84433643-e6ddf380-ac2e-11ea-9c56-41f3e90e4785.png)

**What is your guess?**

`__profile_queue__` is broken due to recent refactor?

---

**Environment**

**Screenshots**

**Comment by fhaase2** [comment]
Profile endpoint is working. Problem is that log and profile endpoints are sse endpoints and they are blocking each other. 
In dashboard, log request is done first, therefore profile is not working and stays pending.
I am looking into it.
