### ISSUE TITLE
feat: add `if` keyword at Driver/Executor/Pod level

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#518]
**Describe the feature**

> just some random thoughts, not well-organized yet

`if` keywords can be used to filter chunks by its MIME type

```
!EncodeDriver
if: doc.mime_type == 'image/png'
```

It works as a "filter", only docs meet this constraint will be processed.

Can also define syntax at chunk level.

This can be used in crafter/encoder/indexer driver. 

**Your proposal**

if we add a new fields `tags` Map to the doc/chunk-level pb, we can also use `if` to filter doc/chunk bases on the key-value in the `tags` Map.

```
if: doc.tags.created_timestamp >= 2020
if: doc.length < 5
```

basically the change in most of the filter is:

```python
for d in self.req.docs:
   ...
```
to 

```python
for d in self.req.filtered_docs:
   ...
```

likewise for the `chunk` loop.

**`filtered_docs` and `filtered_chunks` are the computed properties that returns an iterator based on `if`.**

Shall we use `eval` to interpret the expression? doesn't sound safe though...

### What about higher level?

Chunk-> Doc -> Request -> Message

Request level: not so many meta info one can filter
Message level: filter based on the info in the envelope. Should `if` still be a property defined at driver level? or at Pod level, or both?

References:

single expression: https://docs.python.org/3/reference/expressions.html

---

**Environment**

**Screenshots**

**Comment by Shandilya21** [comment]
Hi, @hanxiao I am new here. I am interested to work on this issue. Is this issue has taken?

**Comment by fhaase2** [comment]
Elasticsearch is doing something similar using the condition operator (https://www.elastic.co/guide/en/elasticsearch/reference/master/condition-compare.html)
They are using operators such as „gt“, „eq“ and so on for the expression. Is this something that makes also sense for the jina expression?

**Comment by hanxiao** [comment]
@fhaase2 feel free to comment on https://github.com/jina-ai/jina/pull/524
