### ISSUE TITLE
BUG: Round-Robin GPU scheduling does not accept lists of GPUs properly

### ISSUE THREAD

**Issue by mchaker** [jina-ai/jina#5181]
`CUDA_VISIBLE_DEVICES: "RR6:8"` works, but the following are expected to work however do not work:

`CUDA_VISIBLE_DEVICES: "RR1,4"` does NOT work but should work

`CUDA_VISIBLE_DEVICES: "RR1,3,5,7"` does NOT work, but should work

`CUDA_VISIBLE_DEVICES: "RR1,4:6"` does NOT work, but should work

`CUDA_VISIBLE_DEVICES: "RR1,3,5,6:8"` does NOT work, but should work

`CUDA_VISIBLE_DEVICES: "RR0:3,5,7"` does NOT work, but should work

`CUDA_VISIBLE_DEVICES: "RR0:3,5,6:8"` does NOT work, but should work

**Comment by JoanFM** [comment]
Hey @mchaker,

May I ask why do you consider that this should work?

I do not find in the Documentation any explanation on why this should work. Is this a `bug` report or a `feature` request?

**Comment by JoanFM** [comment]
Hey @mchaker,

Would it be good enough to support either `slice syntax` (RRstart:stop:step) or `list syntax` RRA,B,C,D but not a combination of both?

**Comment by mchaker** [comment]
Hi, sorry - @JoanFM yes that would be good -- both individually, but not a combination.
