### ISSUE TITLE
Bug: monitoring sending request time is not precise when using sending multiple requests

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#5182]
# Context

This part of the code is buggy  : https://github.com/jina-ai/jina/blob/8c2d07589468b2fdf5dfccd04f3a2cbfc6482802/jina/serve/networking.py#L336

When the gateway send multiple requests the monitoring consider that it is only once

**Comment by Jackmin801** [comment]
We can't reproduce this because the number of requests is always one
