### ISSUE TITLE
Support StatefulSet for K8s YAML generation

### ISSUE THREAD

**Issue by zac-li** [jina-ai/jina#5194]
**Describe the feature**
In JCloud, we have potential use case where people may use both multiple replicas and EBS as storage type. In this specific case, `Deployment` won't work as it can only do shared volume. But on the other hand, `StatefulSet` supports `volumeClaimTemplates` which can enable each replica has it's own PVC and PV, which is what we want.

**Your proposal**
We request core's K8s YAML generation to be able to generate `StatefulSet` YAML on condition, e.g., when a specific flag is passed in. so at JCloud, we could call this flag when the condition is met, i.e., both multiple replicas and EBS are used.

Ref: https://stackoverflow.com/questions/41583672/kubernetes-deployments-vs-statefulsets

**Comment by JoanFM** [comment]
We will proceed to use `StatefulSet` when `volumes` is requested by the user
