### ISSUE TITLE
chore: draft Release Note v3.9.0...842a585

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#5196]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/2041322/191766438-2fdfc6fc-6b5f-4260-a343-c4d194cfbeee.png">

And use markdown editor or whatever you want to edit the release note

# Release Note

[//]: <> (remove the phrase like "0 new features")
This release contains 5 new features, 0 performance improvements, 6 bug fixes and 6 documentation improvements.  

[//]: <> (Does it have security update? If yes then add the following lines)
It is recommended to upgrade to this version as it contains security updates.

## 💥 Security Updates

[//]: <> (If no security update please remove this session.)

### Display warning messages from hubble request (jina hub push) (#5156)

[//]: <> (Nicely introduce each feature before/after with some code snippet and results)

This new feature will allow users to do XYZ.

To use the new feature, use:

```python

```

which results in:

```text

```

The new feature will provide the following benefits:

- Benefit one
- Benefit two
- Benefit three

## 🚀 Performance

[//]: <> (Nicely introduce each performance improvement before/after with some code snippet and results)

We have made a performance improvement to the system. When running the following code:

The result is 123% faster than before.

-The load time for the system has been significantly reduced.
-The system is now more responsive and faster.
-The overall performance of the system has been improved.

### Increase minimum protobuf version (#5166)

[//]: <> (Nicely introduce each bug fix before/after with some code snippet and results)

- The bug was causing [explain what the bug was causing].
- The new version fixes the bug and [explain what the new version does].

### Labels in flow yaml (#5164)

[//]: <> (Nicely introduce each feature before/after with some code snippet and results)

## 🤟 Contributors

We would like to thank all contributors to this release: Deepankar Mahapatro(@github_user) 
Han Xiao(@github_user) 
Joan Fontanals(@github_user) 
Girish Chandrashekar(@github_user) 
zhangkai(@github_user) 
Nikolas Pitsillos(@github_user) 
AlaeddineAbdessalem(@github_user) 
Andrei Ungureanu(@github_user)

**Comment by JoanFM** [comment]
Let's close this and have this redone for next patch
