### ISSUE TITLE
合作兴趣

### ISSUE THREAD

**Issue by fishfl** [jina-ai/jina#5203]
我们是一个中国工程师团队，叫ai模型市场（aimodelmarket.cn），

我们将打包好的docker镜像卖个客户，以提供在线人工智能API。

我们惊喜的发现，我们的业务和jina-ai有很强的互补性。

如何有兴趣进一步合作，请联系我们 (mailto   :    fishfl@163.com)

期待您的来信。

**Comment by GrandeLisaLi** [comment]
好的，我们会进一步和你联系。
