### ISSUE TITLE
docs(install): minimum and performant installs are the same

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#5210]
**Describe the bug**

From [installation instructions(https://docs.jina.ai/get-started/install/#more-install-options):

In different folders/virtualenvs, run:

- `JINA_PIP_INSTALL_CORE=1 pip install jina`
- `JINA_PIP_INSTALL_PERF=1 pip install jina`

Then run `pip freeze` for each of them and compare output. It's exactly the same. `CORE` installs `lz4` and `uvloop`, where it's specified that only `PERF` should do so

## Solution

Remove one of these options?

**Comment by Nithin1728** [comment]
Hi, I'm new to opensource can I work on this issue

**Comment by alexcg1** [comment]
Hey @Nithin1728 I think our internal engineers are on it
