### ISSUE TITLE
Bug: New type of logging hides info

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5241]
As you can see, the new logging type hides important information from the user. A lot of output is cut off. It makes it much harder to debug.
<img width="460" alt="image" src="https://user-images.githubusercontent.com/11627845/193908102-25df61c5-c540-4cde-830b-6fddbf8f9bf3.png">

UAC
- [ ] all log out put should be readable in case of errors

**Comment by JoanFM** [comment]
Are you sure this is not ur terminal configuration?

**Comment by JoanFM** [comment]
I do not understand what you mean by `new` logging type?

**Comment by florian-hoenicke** [comment]
> Are you sure this is not ur terminal configuration?

Yes, I did not reconfigure the terminal
