### ISSUE TITLE
What is the best solution for segmenting text media?

### ISSUE THREAD

**Issue by tagizaade** [jina-ai/jina#525]
**Describe your problem**
The first option that comes into mind when segmenting a text document to semantic pieces are sentences. If a sentence is small sized it will have a coherent semantic. But for bigger sentences that have combined two or more semantic parts, using one feature vector for whole of it seems not interesting. I had some experiments for Arabic language with  [Arabert](https://github.com/aub-mind/arabert) as my feature generator and the results were rather poor when compared with the classic search techniques such as BM25.

**What is your guess?**
In my opinion for big sentences we should split them to phrases. But it seems we don't have a good tool for doing so right now.  Am I right? Any idea where the problem might be?

**Comment by hanxiao** [comment]
We have the ideas of [Chunks](https://github.com/jina-ai/jina/tree/master/docs/chapters/101#document--chunk), and it's used in our [gif-example](https://github.com/jina-ai/examples/tree/master/tumblr-gif-search).

Regarding the text, we have a [`Crafter` for segmenting long document with punctuations](https://github.com/jina-ai/jina/blob/master/jina/executors/crafters/nlp/split.py) and it is used in [southpark-example](https://github.com/jina-ai/examples/tree/master/southpark-search)

Do you mean you are expecting more sounding algorithm than [`Sentencier`](https://github.com/jina-ai/jina/blob/master/jina/executors/crafters/nlp/split.py#L12)

**Comment by tagizaade** [comment]
Yes I am familiar with chunk's concept. I don't doubt the power of vector similarity for image and sound retrieval. But in the case of text I am a little skeptical.

Consider the following toy example:
"Alex is kind and generous but he is a little bit fiery. "

The semantic of the phrase before "but" is totally different from rest of the sentence and in the case of using simple word vectors or contextualized word vectors and then using some kind of pooling to make a single vector for the whole of the sentence ruins both semantics. So if we search "Alex is generous" the aforementioned  sentence may not be retrieved. 

One question arises and that is: Should the results returned by vector based retrieval cover the results of string match methods like BM25 or comparing them is totally wrong?

If should cover, we must compare them based on some standard benchmarks.
If not, how can we have pros of both methods?

**Comment by hanxiao** [comment]
`Crafter` can be "deep" as well, [`DeepSegment`](https://pypi.org/project/deepsegment/), 

In this case, "Alex is kind and generous but he is a little bit fiery. " can be easily segmented into
- "Alex is kind and generous"
- "but he is a little bit fiery."
- "Alex is kind and generous but he is a little bit fiery. "
, which encodes into three chunk-vectors. In the query time, a multi-chunk query will be measured against all three of them, e.g. https://github.com/jina-ai/jina/blob/master/jina/executors/rankers/bi_match.py#L9

Again, `Ranker` can be "deep" as well. So I wouldn't worry too much about the lack of expressivity. In fact, providing a mature design pattern behind this neural search is exactly what Jina does. 

Regarding the comparison between symbolic-based approach (BM25/tfidf) and Jina, I would say it differs from case to case and also depends on the `crafter`,  `encoder`,  `indexer`, `ranker` one is using. It makes sense to do such comparison for a concrete case, but the result is often not generalizable.
