### ISSUE TITLE
Docs: Font's unreadable in github Dark mode

### ISSUE THREAD

**Issue by DanEdens** [jina-ai/jina#5251]
**Describe your proposal/problem**

Cannot read map while using dark mode. I can switch modes.. but thought I would let you know
---

![image](https://user-images.githubusercontent.com/48360111/194362088-ddc6bcb9-f04b-45de-bb64-ad91d1474b79.png)

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
Hello @DanEdens,

Thanks for reporting, this is a known issue and there is not an easy fix for this.

Will close for now
