### ISSUE TITLE
Will Jina support full-text features including filtering?

### ISSUE THREAD

**Issue by markhuds** [jina-ai/jina#527]
**Describe the feature**

Allow combination of vector search with hard rules / custom scoring based on document metadata. Many applications can benefit from combining the strengths of combining both of these. 

For example: find most visually similar images using vector search on vectors encoded with BiT and constrain and/or boost documents whose caption includes the word "animal" or "mammal" and are uploaded by "johndoe" .

**Your proposal**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
Yes. We are in the progress of implementing features to enable what you described. You can expect some demo in the `v0.3.0` release and more details & docs in `v0.4.0`

Notice that this is a nontrivial feature. It requires multiple sub-features such as `if` (done in #524 ), `filter_by` (done in #504) and workflow pattern improvement (done in #506).

Stay tuned and feel free to contribute ❤️ .

**Comment by markhuds** [comment]
Great to hear! Certainly a complex problem. I am curious about the design. Will the final results necessarily be a subset of the topk results returned from the vector query? ie. search using vector then filter based on conditionals. Elasticsearch implements the opposite pattern: search by text then reorder based on vector. Results are first retrieved using inverted index scoring and then each vector is read from disk and cosine similarity is computed element wise.

I'm not aware of a database or data structure that is well suited to combining both efficient vector nearest neighbor lookups and efficient full-text retrieval so I assume that you will need to use a hybrid where you use one efficient data structure to retrieve the most likely candidates given one algorithm and then perform costly element wise computations for the other search criteria.

I could see the value in a vector search then filter topk approach, but it would also be good to combine this approach with a text search then vector boost approach if possible. Consider a case where you have a hundred million documents with vectors and tags. Retrieving topk=1000 might give approximately the closest vectors but maybe there are 50000 results that are good substitutes. Your thousand might only have 5 out of 100 of the documents which have the tag and are in the top 50000. Some options I can think of to solve this problem are 

1. to increase topk (which also increases the number of random disk seeks and is costly)

2. to somehow use a nearest neighbors data structure that supports indexing (not sure if there is one)

3. to use a hybrid approach that does both the `vector then text` and the `text then vector` approaches and merges their results.
