### ISSUE TITLE
Add versioned Documentation

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5283]
Add versioned documentation.

Documentation page should have a scroll to show documentation of every patch and the master branch

**Comment by AnthonyLe93** [comment]
Hi, I just started out using github and would like to make some contributions to open source-projects. I find this issue might be a good place to start so just wondering if i you can give a bit more instructions on where to start. i have never used Jina before.

**Comment by JoanFM** [comment]
Hey @AnthonyLe93 , this has not much to do with `Jina` as a framework, but on the way we deploy our `Documentation`. If u have experience with a project like that you can give us some hints

**Comment by AnthonyLe93** [comment]
Hi @JoanFM, i know that confluence comes with built-in tools for versioning documents. Not sure if this is what you are after? Page Properties is a built-in feature of Confluence. It allows you to add your own properties to Confluence pages. You can add a property called ‘Version’ and update the value of this property for each new official release.
