### ISSUE TITLE
the training function is missing in the Faiss Indexer

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#530]
**Describe the bug**
the index object initialized by `faiss.index_factory()` should be trained before loading the indexed data. 

**Describe how you solve it**
- implement the `train()` function for `FaissIndexer`

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
note that this is not unnecessarily true. as not all indexer in faiss need to be pretrained.
