### ISSUE TITLE
docs: jina Flow the hard way

### ISSUE THREAD

**Issue by samsja** [jina-ai/jina#5316]
The idea would be to create a how to / tutorials named
`jina Flow the hard way` (named inspire [kubernetes the hard way](https://github.com/kelseyhightower/kubernetes-the-hard-way)  )

The idea would be to show that you can start an X Executor by yourself with the CLI, start the gateway and pass the topology graph and the connection list as cli paramters and the "Flow" will live.

This will gave in depth understanding to whoever want to deep dive in Jina concept. It will help user to understand how we deploy on k8s as well

**Comment by alexcg1** [comment]
I like this! Can you add to our [inbox column](https://github.com/orgs/jina-ai/projects/34/views/1)?

**Comment by samsja** [comment]
> I like this! Can you add to our [inbox column](https://github.com/orgs/jina-ai/projects/34/views/1)?

This ticket is part of team core low hanging fruit day I will finish it asap

**Comment by alexcg1** [comment]
With the renewed focus on Executor, perhaps we could make it more "Jina: The Hard Way" (or "deploying a model: the easy way" :wink: ), bootstrapping from deploying a single ML model to deploying a whole ML pipeline

**Comment by samsja** [comment]
then it is a different subject (which is maybe more interesting) happy to discuss the idea but I believe that the original idea should still exist somewhere
