### ISSUE TITLE
bug: Failed to load configured propagator `tracecontext`

### ISSUE THREAD

**Issue by girishc13** [jina-ai/jina#5320]
**Describe the bug**
An exception is raised by the OpenTelemetry `propagate/__init__.py` with standard `jina` install in google colab.

Error as reported in slack thread.
```
Failed to load configured propagator `tracecontext`
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/opentelemetry/propagate/__init__.py", line 137, in <module>
    iter_entry_points("opentelemetry_propagator", propagator)
StopIteration
ERROR  executor0/rep-0@1678 StopIteration()                                                     [10/26/22 13:21:01]
        add "--quiet-error" to suppress the exception details                                                      
       Traceback (most recent call last):                                                                          
         File "/usr/local/lib/python3.7/dist-packages/jina/serve/runtimes/worker/__init__.py",                     


---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/jina/helper.py in run_async(func, *args, **kwargs)
   1317             try:
-> 1318                 return thread.result
   1319             except AttributeError:

AttributeError: '_RunThread' object has no attribute 'result'

During handling of the above exception, another exception occurred:

BadClient                                 Traceback (most recent call last)
2 frames
/usr/local/lib/python3.7/dist-packages/jina/helper.py in run_async(func, *args, **kwargs)
   1321 
   1322                 raise BadClient(
-> 1323                     'something wrong when running the eventloop, result can not be retrieved'
   1324                 )
   1325         else:

BadClient: something wrong when running the eventloop, result can not be retrieved
```

**Describe how you solve it**

---

The root cause is due to the import of the `extract` method by default in the `WorkerRuntime`. 

Still investigating the steps and environment to reproduce the bug.

**Environment**

- jina 3.11.0
- docarray 0.18.1
- jcloud 0.0.36
- jina-hubble-sdk 0.22.2
- jina-proto 0.1.13
- protobuf 3.20.3
- proto-backend cpp
- grpcio 1.47.2
- pyyaml 6.0
- python 3.7.15
- platform Linux
- platform-release 5.10.133+
- platform-version `#1` SMP Fri Aug 26 08:44:51 UTC 2022
- architecture x86_64
- processor x86_64
- uid 2485378613250
- session-id 42d3365e-55cf-11ed-bb59-0242ac1c0002
- uptime 2022-10-27T08:13:38.149772
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
NV_LIBCUBLAS_DEV_VERSION=11.4.1.1043-1
NV_CUDA_COMPAT_PACKAGE=cuda-compat-11-2
NV_CUDNN_PACKAGE_DEV=libcudnn8-dev=8.1.1.33-1+cuda11.2
PYDEVD_USE_FRAME_EVAL=NO
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.8.4-1+cuda11.2
TCLLIBPATH=/usr/share/tcltk/tcllib1.19
CLOUDSDK_PYTHON=python3
LANG=en_US.UTF-8
NV_LIBNPP_DEV_PACKAGE=libnpp-dev-11-2=11.3.2.152-1
ENABLE_DIRECTORYPREFETCHER=1
HOSTNAME=b90a4499e089
OLDPWD=/
CLOUDSDK_CONFIG=/content/.config
USE_AUTH_EPHEM=1
NV_LIBNPP_VERSION=11.3.2.152-1
NV_NVPROF_DEV_PACKAGE=cuda-nvprof-11-2=11.2.152-1
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
NVIDIA_VISIBLE_DEVICES=all
NV_NVPROF_VERSION=11.2.152-1
NV_LIBCUSPARSE_VERSION=11.4.1.1152-1
DATALAB_SETTINGS_OVERRIDES={"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=172.28.0.2"],"debugAdapterMultiplexerPath":"/usr/local/bin/dap_multiplexer","enableLsp":true}
NV_LIBCUBLAS_DEV_PACKAGE=libcublas-dev-11-2=11.4.1.1043-1
ENV=/root/.bashrc
PAGER=cat
NCCL_VERSION=2.8.4-1
TF_FORCE_GPU_ALLOW_GROWTH=true
JPY_PARENT_PID=59
NO_GCE_CHECK=False
PWD=/content
NVARCH=x86_64
NV_LIBCUSPARSE_DEV_VERSION=11.4.1.1152-1
HOME=/root
KMP_LISTEN_PORT=6000
LAST_FORCED_REBUILD=20221021
CLICOLOR=1
NV_LIBNCCL_PACKAGE_VERSION=2.8.4-1
NV_LIBNCCL_PACKAGE=libnccl2=2.8.4-1+cuda11.2
DEBIAN_FRONTEND=noninteractive
NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
NV_CUDA_LIB_VERSION=11.2.2-1
NV_LIBNPP_PACKAGE=libnpp-11-2=11.3.2.152-1
NV_LIBNCCL_PACKAGE_NAME=libnccl2
LIBRARY_PATH=/usr/local/cuda/lib64/stubs
NV_NVTX_VERSION=11.2.152-1
NV_LIBCUBLAS_VERSION=11.4.1.1043-1
NV_LIBCUBLAS_PACKAGE=libcublas-11-2=11.4.1.1043-1
GCE_METADATA_TIMEOUT=3
NV_CUDNN_VERSION=8.1.1.33
VM_GCE_METADATA_HOST=169.254.169.254
NV_CUDA_CUDART_DEV_VERSION=11.2.152-1
KMP_TARGET_PORT=9000
GLIBCPP_FORCE_NEW=1
TBE_CREDS_ADDR=172.28.0.1:8008
TERM=xterm-color
SHELL=/bin/bash
GCS_READ_CACHE_BLOCK_SIZE_MB=16
NV_NVML_DEV_VERSION=11.2.152-1
PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
MPLBACKEND=module://ipykernel.pylab.backend_inline
CUDA_VERSION=11.2.2
NV_LIBCUBLAS_PACKAGE_NAME=libcublas-11-2
NVIDIA_DRIVER_CAPABILITIES=compute,utility
TBE_RUNTIME_ADDR=172.28.0.1:8011
SHLVL=1
PYTHONPATH=/env/python
NV_LIBCUBLAS_DEV_PACKAGE_NAME=libcublas-dev-11-2
NVIDIA_REQUIRE_CUDA=cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451
NV_LIBNPP_DEV_VERSION=11.3.2.152-1
TBE_EPHEM_CREDS_ADDR=172.28.0.1:8009
NV_CUDA_CUDART_VERSION=11.2.152-1
NV_CUDNN_PACKAGE_NAME=libcudnn8
GLIBCXX_FORCE_NEW=1
PATH=/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin
NV_LIBNCCL_DEV_PACKAGE_VERSION=2.8.4-1
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4
NV_CUDNN_PACKAGE=libcudnn8=8.1.1.33-1+cuda11.2
GIT_PAGER=cat
_=/usr/bin/env

The bug is easily reproduced in [this](https://colab.research.google.com/drive/1IQj6yj4mNpKU9N10xKYSzeClXm9-jUd6#scrollTo=6BXTUb9giVkF) colab notebook.

**Screenshots**

**Comment by JoanFM** [comment]
Anyhow, I think we should make sure that this import does not happen if the `OpenTelmetry` is not activated which seems to be the case

**Comment by girishc13** [comment]
Yes, I cannot reproduce it locally but on colab it's reproducible. I'll add a sample notebook.
