### ISSUE TITLE
feat: find out which docs are which in docs_matrix

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5330]
When pairing with @violenil, we were hitting some limitations of the core. 
It is currently not possible to find out what DocArrays are coming from what executor.
Please implement a mechanism to let us know what the previous executor was for each DocArray.

Example:
Two encoders in parallel and a merger in sequence that has to know what embedding came from what executor

**Comment by violenil** [comment]
![flow_x](https://user-images.githubusercontent.com/55404563/198677306-000a263b-b2fe-4c26-a82b-40e83d16c2f3.png)

**Comment by JoanFM** [comment]
You could have the `disable_reduce` flag and have a `DocumentArrayMatrix` which will allow u to know where the Executor comes from.

**Comment by JoanFM** [comment]
I would like to clarify the scope of this before proceeding. 

If the intention when passing DocumentArray to Executors is to flag Executors, I would say this has to be done with these 2 options:

1 - Either responsability left to the Executor developer to flag the DocArray
2 - The WorkerRuntime flag the Executor in some `__flag__` reserved tag of `DocArray`.

The alternative is to use the `disable_reduce` feature and have the Indexer handle the DocumentArray without flattening, I would assume the Matrix is created in a deterministic order.

**Comment by florian-hoenicke** [comment]
What about the following?:
```
class MergeExecutor(Executor):
    def __init__(self, encoder_names):
        self.encoder_names = encoder_names

    @requests
    def foo(self, docs, parameters, docs_matrix):
        for encoder_name in encoder_names:
             docs = docs_matrix[encoder_name]
             ...
```
Advantages:
- user friendly
- not much effort for the developer of the executor
- does not rely on the order of executors in topology
- if executor is skipped, then it would be hard to know which one if we rely on order
