### ISSUE TITLE
bug: wrong inherited Executor called

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5375]
At Jina now, we are using the inheritance of executors since it allows us to constrain certain behavior on a group of executors.
For instance, we have a BaseIndexer that makes sure all derived indexers like Qdrant/Elastic have the same interface. And if we change the interface, all Indexers are updated with the new behavior.

Now we are experiencing the following issue. 
This is our code (simplified):
```python
from docarray import Document
from jina import Flow

from jina import Executor, requests

class BaseExecutor(Executor):
    @requests()
    def x(self, *args, **kwargs):
        pass


class EnhancedExecutor(BaseExecutor):
    @requests()
    def y(
        self,  *args, **kwargs
    ):
        print('enhanced was called')

with Flow().add(uses=BaseExecutor) as f:
    f.index(inputs=Document())
```

Output:
```
enhanced was called
```

As you can see the `EnhancedExecutor` is called even if the flow is just using the `BaseExecutor`.

UAC
- [ ] Please support inheritance for Executors.

**Comment by JoanFM** [comment]
Can u try without having one of them called `BaseExecutor`? Since this is a special class in our Jina inheritance tree I want to make sure that it is just a very bad coincidence. Does it also happen with `ExecutorBase`and `ExecutorInherited`?

**Comment by JoanFM** [comment]
also, can u run here?

```python
exec = Executor.load_executor(ExecutorInherited)
print(type(exec))
```

**Comment by JoanFM** [comment]
This is even more funny, there is something odd with our `requests` decorator:

```python
from docarray import Document
from jina import Flow

from jina import Executor, requests


class A(Executor):
    @requests()
    def x(self, *args, **kwargs):
        pass


class EnhancedExecutor(A):
    @requests()
    def y(
            self, *args, **kwargs
    ):
        print(f'enhanced was called => {type(self)} => {isinstance(self, EnhancedExecutor)}')


with Flow().add(uses=A) as f:
    f.index(inputs=Document())
```

You see that the call actually gets an instance of `A` and not an instance of `EnhancedExecutor`

**Comment by florian-hoenicke** [comment]
Yes, this is also what we experienced. Just the decorator is incorrectly attached or something

**Comment by JoanFM** [comment]
you can see:

```python
print(f' A => {A.requests}')
```
```shell
 A => {'/default': <function EnhancedExecutor.y at 0x7f51dd51c5f0>}
```
