### ISSUE TITLE
feat: provide new argument to override `service.name` resource attribute for Gateway Runtime

### ISSUE THREAD

**Issue by girishc13** [jina-ai/jina#5387]
**Describe the bug**

The default `gateway/rep-0` service name is used even if the `name` argument to the Flow is provided.

With the default naming, the tracing view looks awkward and unreadable when using external Flow. In the below screenshot, there are two Flows each using the same name to display the spans. Using a custom name would improve the readability and provides the needed context to the user which helps to understand the request flow.
![Screenshot from 2022-11-15 14-24-02](https://user-images.githubusercontent.com/9018501/201930550-29e21765-2cc6-4336-b72d-65829aea7480.png)

**Comment by JoanFM** [comment]
the `flow` name in args has never been considered to be the name of the `Flow`, so I would not consider this a `bug`. Why is this being asked for and by whom?
