### ISSUE TITLE
refactor: refactor deployment and pod classes to avoid implementing different behavior inside `if self.args.pod_role == PodRoleType.TYPE` checks

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5393]
Currently, pod and deployment classes operate on any pod, regardless of the pod type (gateway, head or worker).
However, this is implemented by constantly checking `args.pod_role` for instance:
```python
        def _is_ready():
            if args.pod_role == PodRoleType.GATEWAY:
                return GatewayRuntime.is_ready(
                    runtime_ctrl_address, protocol=args.protocol[0]
                )
            else:
                return AsyncNewLoopRuntime.is_ready(runtime_ctrl_address)
```
We should refactor these classes to better implement these different behaviors (maybe using inheritance)

**Comment by JoanFM** [comment]
Important note: This would imply adding a new class to use composition not inheritance, otherwise our inheritance will blow up
