### ISSUE TITLE
Bind to `host` instead of `default_host`

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5402]
**Describe the bug**
Flow accepts `host` parameter because it inherits from client and gateway but is confusing as shown in #5401

**Comment by alaeddine-13** [comment]
In principle, Flow exposes parameters common to executors and the gateway and are inherited from the Flow. `host` is an important parameter for external executors, therefore, it is exposed by Flow.
We have an issue to document the behavior of parameter inheritance: https://github.com/jina-ai/jina/issues/5353
We can either just document this or make host an exception.

**Comment by wqh17101** [comment]
All 0 monitoring is equivalent to binding all IPs of the machine, that is, it will cause the whole network to monitor, destroying the original three-sided isolation principle of the system, resulting in increased exposure or increasing the risk of lateral attack expansion.

This is a danger setting.
For example, i only want to expose this api internally instead of all the way to this machine.

**Comment by JoanFM** [comment]
Hey @wqh17101, 

I am not sure to understand it.

What Jina is doing when you run Flow locally is to run a server listening to the `port` provided (or a random port) in your local machine.

We do not touch any rules on where your machine is exposed.

**Comment by wqh17101** [comment]
@JoanFM 
As a web service, it can expose your port(api) on any ips on your machine.
So if you set host as 0.0.0.0,every ips will be available to the api. So everyone can reach your machine  by ping can attack your service like DDos.
if you set host as 127.0.0.1,only the calling on the server machine can reach.
You can get some info from https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

Sometimes i want a local-only interface not all network interface to be exposed for the security problem.

**Comment by wqh17101** [comment]
According to the web framework thirdparty software such as `flask` or `pyramid`. It provides the parameter `host` for user to choose which ip to bind to. That is flexible that the users can adjust their host on their own, and the framework will not need to make some limitations.
