### ISSUE TITLE
cherry pick #520's 101 to master

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#542]
**Describe the feature**

In #520 there are quite some revisions on the 101 doc. However, some newly added definitions (e.g. [the definition of neural search system](https://github.com/jina-ai/jina/pull/520/files#diff-d9c234c0ef28a7c7c059b07c4d8d003bL53-R59)) are not accurate and the restructure breaks some HTML markups that we designed, some images are lost. I wasn't pay enough attention until I merged.

**Your proposal**

Cherry pick the text content only and resubmit the PR. Make sure to check the rendered markdown on Github and see if the format is consistent with the current one.

---

**Environment**

**Screenshots**

**Comment by alexcg1** [comment]
Understood. I reformatted/removed some images for general layout purposes (I thought it was too busy). I'll stick to just editing the text for now

**Comment by alexcg1** [comment]
I'll rebranch from master, make the edits, and make a new PR (since original branch was from my alexcg1 github account, not my Jina acct)
