### ISSUE TITLE
Access to the authority management system similar to JWT

### ISSUE THREAD

**Issue by coolmian** [jina-ai/jina#5442]
**Describe your proposal/problem**
How to access the authority management system similar to JWT to protect the server?
How to avoid the waste of computing resources caused by random network attacks on interfaces

I didn't find _token/login_ or similar keywords in the document, except for using Jina AI Cloud

**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
@alaeddine-13 to be highlighted when `CustomGateway` is released

**Comment by coolmian** [comment]
> @alaeddine-13 to be highlighted when `CustomGateway` is released

Thanks. I will read about `CustomGateway`

**Comment by JoanFM** [comment]
Hey @coolmian ,

We have released `CustomGateway`. https://docs.jina.ai/concepts/gateway/customization/#customization

You can check here, there you can implement your own logic before reaching Executors. If you think that is there some particularity that we can cover better in documentation, let us know.

**Comment by coolmian** [comment]
> Hey @coolmian ,
> 
> We have released `CustomGateway`. https://docs.jina.ai/concepts/gateway/customization/#customization
> 
> You can check here, there you can implement your own logic before reaching Executors. If you think that is there some particularity that we can cover better in documentation, let us know.

Thanks. If I have a good idea, I will give it back to you.
