### ISSUE TITLE
bug: wrong number of pods in flow object

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5479]
Flow object has 0 pods but 5 deployments.

Expected: 
`num_pods = deployment_1_num_replicas + deployment_2_num_replicas + ...` 

<img width="218" alt="image" src="https://user-images.githubusercontent.com/11627845/205271967-fd74c065-3d1e-46e2-9d1a-ce5cc3921af6.png">

**Comment by JoanFM** [comment]
The Pods are not seen until u have built the Flow entering the context manager. It will not be fixed otherwise

**Comment by JoanFM** [comment]
Please provide a code to reproduce and if the Flow is not built before, will close

**Comment by florian-hoenicke** [comment]
I need this to know when the flow is up an running. We are creating the flow yaml files, apply the files to the k8s cluster and then have to wait. While waiting, we check the cluster every second. We list the number of ready pods and once the number of ready pods is as we expect, we start indexing.
You mean I have to call f.build()?

**Comment by JoanFM** [comment]
if there is no `f.build` this information will not be there. Also, I do not think is recommended to test this, this should be taken from the `Kubernetes` API on how many ready/replicas is there.

**Comment by florian-hoenicke** [comment]
But consider the following case:
I have a script that 
1. creates the k8s files
2. runs index requests to the flow

I need a way to know the current status of the deployment. 
The state described above in the image should never happen. 5 Deployments with 0 pods. It must be consistent. With the same argument, we could also say why is it 5 deployments and not 0 before the flow enters the context. If these numbers are not correct, then better not to have them at all.

**Comment by JoanFM** [comment]
This API is not to be considered. This is not going to be changed, the maximum we would do is to set these as private. But this should never be the source of truth
