### ISSUE TITLE
bug: indexing flow breaks on network problems

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5480]
The user code for the jina client has to look like this:
```python
for batch in create_batches(da):
    try:
        batch.index(batch)
    except:
        pass
```
Please improve the usability. Something like this should be the functionality of the jina client

**Comment by JoanFM** [comment]
We should have a deeper discussion about this. I am not sure we can ignore all network problems. Plus, It is hard to say when a problem is transient

**Comment by girishc13** [comment]
We can look at the akka framework and reactive/streaming frameworks from Java. Basically each stream operation can 

- by default stop the whole stream on error
- user can define the recovery operation that provides an alternative value so that the stream can continue

**Comment by JoanFM** [comment]
I think that akka framework provides this onError, so I believe u should use the on_error callback given by Jina to accumulate the non-successful requests and decide what to do next
