### ISSUE TITLE
support opentelemetry export more params like headers 

### ISSUE THREAD

**Issue by big-thousand** [jina-ai/jina#5482]
**Describe the bug**

jina init param
<img width="636" alt="image" src="https://user-images.githubusercontent.com/114633619/205478332-40854617-136b-4270-ba4c-d0641b5a16f6.png">

opentelemetry init param
<img width="655" alt="image" src="https://user-images.githubusercontent.com/114633619/205478341-27d5e35e-b68c-4eeb-a0d6-9dfb9a378e48.png">

**Describe how you solve it**

apm like uptrace https://github.com/uptrace/uptrace will need opentelemetry header to collect information, now jina not support pass header to tracer and meter

---

**Environment**

**Screenshots**

**Comment by big-thousand** [comment]
jina export always assume grpc connect is insecure, but it's not right.

Default otel can pick environment to fill param, But jina assume connect is insecure
```
"OTEL_EXPORTER_OTLP_COMPRESSION": "gzip",
"OTEL_EXPORTER_OTLP_TRACES_COMPRESSION":"gzip",
"OTEL_EXPORTER_OTLP_ENDPOINT": "grpc://xxx.uptrace:4317",
"OTEL_EXPORTER_OTLP_TRACES_INSECURE": "false",
"OTEL_EXPORTER_OTLP_INSECURE": "false",
"OTEL_EXPORTER_OTLP_PROTOCOL": "grpc",
```

**Comment by girishc13** [comment]
Thanks for the interest in using the OpenTelemetry features. 

- We will fix the insecure param soon and it should unblock the connectivity with external API providers for OpenTelemetry data. The python library doesn't correctly handle all the cases when providing the endpoint for which we will refactor our tests a bit.
- The headers can still be provided using the environment variable `OTEL_EXPORTER_OTLP_TRACES_HEADERS`. Refer https://github.com/open-telemetry/opentelemetry-python/blob/e4a4410dc046f011194eff78e801fb230961eec8/exporter/opentelemetry-exporter-otlp-proto-grpc/src/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py#L119.
