### ISSUE TITLE
Create a new github repository for load testing Jina Flow

### ISSUE THREAD

**Issue by girishc13** [jina-ai/jina#5516]
Use [Locust](https://locust.io) as the load testing framework and Delivery Hero [Locust helm-charts](https://github.com/deliveryhero/helm-charts/tree/master/stable/locust) for generating Kubernetes deployment templates. Jina Flow deployment will also need to be generated from the repository.

**Comment by girishc13** [comment]
Locust cannot be used due to lack of `asyncio` support which prevents the usage of Jina Client for running requests against the Flow.

**Comment by nan-wang** [comment]
What are the alternatives to Locust? @girishc13

**Comment by girishc13** [comment]
There is the molotov library which is relatively new and supports asyncio. It doesn't have good reporting features but it serves the purposes. I have already integrated this library in the [locust](https://github.com/jina-ai/load-test) repo. I'm waiting for some feedback before closing this ticket.

**Comment by JoanFM** [comment]
This is completed
