### ISSUE TITLE
Pod's driver is overwritten in pub-sub connection

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#552]
**Describe the bug**
`PublishDriver` is used to modify the `num_parts` when the pod is connect to another by the `PUB-SUB` connection. However, `PublishDriver` overwrites the original driver of the pod.

```
first.tail_args.yaml_path = '- !!PublishDriver | {num_part: %d}' % first.tail_args.num_part
```

**Describe how you solve it**
Append the `PublishDriver` to the `yaml_path` instead of overwriting.

---

**Environment**
0.2.9

**Screenshots**

**Comment by hanxiao** [comment]
I don't understand, what is the original driver of the pod?
