### ISSUE TITLE
Thread lock the Jina client (or streamer) using RLock

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5527]
The Jina GRPCClient cannot be used in multiple threads (due to a limitation from grpc: https://github.com/grpc/grpc/issues/25364).

Use [RLock](https://docs.python.org/3/library/threading.html#rlock-objects) to restrict the usage of grpc client within 1 thread at a time and test this in a multi threaded setup (flask).
You can get inspired by this commit https://github.com/jina-ai/jina/commit/af988e9920b6ff35fb3014f32b9b27d86797bd3b

**Comment by JoanFM** [comment]
Why an `RLock` and not a simple `Lock`?

**Comment by alaeddine-13** [comment]
> Why an `RLock` and not a simple `Lock`?

An RLock let's you re acquire the lock from the same thread, therefore it shouldn't harm our async support.
A simple lock means only 1 request can be made at a time

**Comment by JoanFM** [comment]
I see
