### ISSUE TITLE
🔖 Commit Message Guideline for the First Time Contributor

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#553]
First, thanks a lot for your initiative :heart:  The open-source community needs one like you with an open and inclusive mindset.

The first barrier to the first time contributor is writing a correct commit message. We realize many PRs have failed in our CI pipeline simply because of the bad commit messages.

**Importance of a correct commit message**

* We are using `commitlint` to check the style of your commit message as the first step of CI. If this fails, the whole pipeline will fail and skip all tests in the sequel. Very strict, yes, but necessary.
* We are generating [`CHANGELOG.md`](https://github.com/jina-ai/jina/blob/master/CHANGELOG.md) automatically on every new release. Correct commit messages help our users to understand which part is modified/improved.

**What to follow?**

* https://github.com/jina-ai/jina/blob/master/CONTRIBUTING.md#commit-style
* https://www.conventionalcommits.org/en/v1.0.0/

**Common mistakes**

* `doc(101): improved 101 document` - should be `docs(101)`
* `tests(flow): add unit test for flow exception` - should be `test(flow)`
* `DOC(101): Improved 101 Documentation` - all letters should be in lowercase
* `fix(pea): i fix this pea and this looks really awesome and everything should be working now` - too long
* `fix(pea):fix network receive of the pea` - missing space after `:`
* `hello: add hello-world` - type `hello` is not allowed

**Rule of thumb**
Keep it simple, short, don't use too many punctuations, e.g. `,.!?-_`. No need to be too specific.

**What if I commit a message in wrong style?**
You can use `git commit --amend` and then `git push force` to fix it. Note that you need to fix **all** commit messages in a PR, this is because when you merge you merge the whole commit history of your branch into master, not only the last commit.

Hope this help!

**Comment by hanxiao** [comment]
hi @fhaase2 this issue is pinned on top of issue board so that everybody can see that, please do not remove it. 😃

**Comment by tadejsv** [comment]
@hanxiao Please change the instruction from `git push force` to `git push --force`
