### ISSUE TITLE
Environment variable OBJC_DISABLE_INITIALIZE_FORK_SAFETY not set by default on Mac

### ISSUE THREAD

**Issue by saahil** [jina-ai/jina#5555]
The Jina installation script does not set the variable OBJC_DISABLE_INITIALIZE_FORK_SAFETY to YES, while installing on my M1 Mac. As a result, after installation, when the user tries to run a flow locally, the Python interpreter process crashes while trying to start the server. 

**How I solved it**
I solved it by exporting OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES on zsh. 

---

**Environment**
- jina 3.13.1
- docarray 0.20.1
- jcloud 0.1.6
- jina-hubble-sdk 0.29.0
- jina-proto 0.1.13
- protobuf 4.21.12
- proto-backend upb
- grpcio 1.51.1
- pyyaml 6.0
- python 3.11.1
- platform Darwin
- platform-release 22.1.0
- platform-version Darwin Kernel Version 22.1.0: Sun Oct 9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
- architecture arm64
- processor arm
- uid 121687005276591
- session-id 10c00bd8-820c-11ed-94a9-6eac76b929af
- uptime 2022-12-22T16:19:44.863274
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Screenshots**
<img width="2043" alt="image" src="https://user-images.githubusercontent.com/128395/209167372-60a96188-4998-4b4c-97c4-d603b74433b7.png">

**Comment by JoanFM** [comment]
This is weird, jina should have installed it in ur `bashrc` or `zshrc`
