### ISSUE TITLE
jina实现负载均衡，是否需要自己根据需求设置executor的功能

### ISSUE THREAD

**Issue by fqzhao-win** [jina-ai/jina#5575]
**Describe your proposal/problem**

---

我有一个微服务，他的参数是字符串列表，这个微服务用到gpu,我想用jina实现负载均衡，把字符串列表拆成多个固定长度的列表，然后再去调用微服务，然后再拼接结果，这个过程flow可以自动实现嘛
**Environment**

**Screenshots**

**Comment by JoanFM** [comment]
@numb3r3 , perhaps you  can help this community member?

**Comment by numb3r3** [comment]
@wangjunkaiwife Here, I want to clarify your problem to make sure we are on the same page.

For examle, The example input (5 strings): ['abc', 'bcd', 'cde', 'def', 'efh']

What's your expected output result:
**option 1**: each input string example has its own output value, for example, the result is [0, 1, 2, 3, 4, 6]
**option 2**: only one output result is returned based on the output on each input example

**Comment by fqzhao-win** [comment]
option1

**Comment by fqzhao-win** [comment]
For example, if the input is ['abc ',' bcd ',' cde ',' def ',' effh '], I have a microservice to process the input. I copy three microservices on the gpu. If each microservice only processes ['abc', 'bad'] at one time, I want the ['abc ',' bcd ',' cde ',' def ',' effh '] requested by the client to be distributed to the three microservices for processing to obtain [1,2], [3,4], [5,6], and then merge the results into [1,2,3,4,5,6] and return, It refers to the ven worker link architecture of the bert as service

**Comment by fqzhao-win** [comment]
Whether there is a framework to automatically implement the splitting process or whether the executor needs to be customized according to my needs

**Comment by JoanFM** [comment]
Hey @fqzhao-win ,

look at this code snippet (for now without the GPU in order to simplify things):

In this case we are distributing between 3 replicas, the work of computing the length of the input text

```python

from jina import Flow, Executor, requests, DocumentArray, Document

class MyExecutor(Executor):

    @requests
    def foo(self, docs, **kwargs):
        for doc in docs:
            doc.tags['length'] = len(doc.text) # compute the length of the Text


f = Flow().add(uses=MyExecutor, replicas=3)

input_docs = DocumentArray([Document(text='abc'), Document(text='bcd'), Document(text='cde'), Document(text='def'), Document(text='effh')])

with f:
    returned_docs = f.post(on='/', inputs=input_docs, request_size=1, results_in_order=True)

    for doc in returned_docs:
        print(doc.tags['length'])
```

Is this more or less the desired behavior? of course the business logic could change

**Comment by fqzhao-win** [comment]
Thank you very much for your reply. I'll learn this fragment first and contact you if I have any questions

**Comment by fqzhao-win** [comment]
Excuse me, after the flow is started, if 1000 clients send requests at the same time, such as string lists ['abc ',' cde '], ['cfd'], ['cdf '], but my executor can process a list with a maximum length of 5, can flow automatically save up to 5 ['abc', 'cde', 'abc', 'cde', 'abc', 'cde'], send them to the executor, get the results, and then distribute them to each client

**Comment by JoanFM** [comment]
If your Executor at the same time can process only 5 documents, you need to pass `request_size=5` to the client.post method

**Comment by fqzhao-win** [comment]
Thank you, but I want to change my description. After the flow starts, if 1000 clients send requests at the same time, such as string lists ['abc '], ['cde'], ['cfd '], ['efg'], ['nmn '], but my executor can handle lists with a maximum length of 2, the process can automatically save all requests to the buffer, and then take ['cde', 'cfd'], ['efg ',' nmn '] from them and send them to the executor for execution. What I want to know more is whether the framework can cache the data of multiple requests, and then split them and send them to the executor

**Comment by JoanFM** [comment]
It is hard for me to understand what you are asking.

The Flow can handle requests for multiple clients and will load balance the requests to different replicas of the Executors to process
