### ISSUE TITLE
docs: start first project is confusing

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5602]
Content and order of this page is wrong.

https://docs.jina.ai/get-started/create-app/

**Comment by Jake-00** [comment]
I plan to follow the instruction and update the doc description, could you assign to me?

**Comment by Jake-00** [comment]
Hi @JoanFM , coz being busy in work the last two days of this week, so I would come back to this issue in weekend.

**Comment by Jake-00** [comment]
When trying to deploy flow.yml of `hello_jina` project using command `jina cloud deploy ./`, I face with a error called **Failed on building Docker image** as same as proposed in [issue](https://github.com/jina-ai/jina-hubble-sdk/issues/148). 
Proposed method is to change the pytorch version in `requrements.txt` from the issue discussion, which not work for me, could we open this issue again?

**Comment by Nick17t** [comment]
😀😀@Jake-00  thanks for your contribution. @nomagick Please take a look. 😀

**Comment by JoanFM** [comment]
@Jake-00 , can you propose the changes that make it work for u in a PR that we can review? 

Thanks!

**Comment by Jake-00** [comment]
hi @JoanFM 
It still not work and I have not found the exact problem to deal with.

**Comment by Jake-00** [comment]
I try to update jina-hubble-sdk, but it already is the newest version(0.33.1), and the same error still come out.

**Comment by Jake-00** [comment]
here is the whole printing messsage after running command `jina cloud deploy ./`
```
[02/09/23 00:21:25] INFO     envfile .env not found.                                                                                                     normalize.py:128
                    INFO     Loading Flow YAML flow.yml ...                                                                                              normalize.py:147
                    INFO     Pushing following Executors to hubble executor1...                                                                          normalize.py:247
╭─────────────────────────────────────────── Published ────────────────────────────────────────────╮
│                                                                                                  │
│   📛 Name           toyExecutor-MyExecutor-e270717b5a                                            │
│   🔗 Jina Hub URL   https://cloud.jina.ai/executor/252nzz3a/                                     │
│   👀 Visibility     public                                                                       │
│   ❗ Warnings       👇 Process finished with warnings!                                           │
│                     • manifest.yml is deprecated - docs.jina.ai/fundamentals/executor/yaml-sp…   │
│                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
[02/09/23 00:22:53] INFO     Flow is normalized:                                                                                                         normalize.py:348

                             {'jtype': 'Flow', 'version': 1, 'gateway': {'protocol': ['grpc', 'http', 'websocket'], 'port': [54321, 54322, 54323]},      
                             'executors': [{'uses': 'jinahub+docker://252nzz3a/latest', 'name': 'toyExecutor'}]}
                    INFO     Flow written to: D:\tmp\flows\flow-pc4jkbp0.yml                                                                             normalize.py:349
Traceback (most recent call last):
  File "D:\app\file\miniconda\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\app\file\miniconda\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\app\file\miniconda\envs\py39\Scripts\jina.exe\__main__.py", line 7, in <module>
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jina_cli\__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jina_cli\api.py", line 233, in cloud
    getattr(api, args.jc_cli.replace('-', '_'))(args)
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jcloud\api.py", line 20, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "D:\app\file\miniconda\envs\py39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\app\file\miniconda\envs\py39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jcloud\api.py", line 27, in deploy
    return await CloudFlow(path=args.path).__aenter__()
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jcloud\flow.py", line 475, in __aenter__
    await self._deploy()
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jcloud\flow.py", line 140, in _deploy
    raise e
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\jcloud\flow.py", line 115, in _deploy
    async with session.post(
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "D:\app\file\miniconda\envs\py39\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by JoanFM** [comment]
can u try updating your `jcloud` package?

**Comment by Jake-00** [comment]
Hi @JoanFM  
I just have been occupied in other things, feel free to reassign other person. And sorry for the late response.

**Comment by alexcg1** [comment]
@JoanFM wrong how? I'll see what I can do

**Comment by asuzukosi** [comment]
@JoanFM, if this task is not yet done it would be a good first commit for me, although I did go through the tutorial and it worked fine for me, can you explain what exactly is wrong with the current structure of the documentation

**Comment by alexcg1** [comment]
I believe at least one issue requires changes in the code, and that may be better left to the core team.

Namely, afaik the the `jina new` command only works for creating Flows, not Deployments. Since we're making Deployments a first-class citizen (and they're simpler than Flows), they would be a better candidate for what users create in this doc

**Comment by asuzukosi** [comment]
Hello @alexcg1  I have already implemented the feature to allow creation of deployments with ‘jina new’, I’ve also updated the documentation to reflect this change. I’ve done all of that within the PR, is there any other specific change you would want me to make to the PR? Thank you

**Comment by asuzukosi** [comment]
Hello @alexcg1 I have already implemented the feature to allow creation of deployments with ‘jina new’, I’ve also updated the documentation to reflect this change. I’ve done all of that within the latest PR, you can take a look at it and then we can work together to implement this feature

**Comment by alexcg1** [comment]
@asuzukosi what's the # of the PR? @JoanFM have you taken a look at it? You can review code better than I can

**Comment by alexcg1** [comment]
Also @asuzukosi could you tag me as a reviewer in your PR?

**Comment by alexcg1** [comment]
@asuzukosi just saw your PR and left a review. Nice work!

**Comment by asuzukosi** [comment]
@alexcg1 Thank you very much, I'll start working on the feedback now
