### ISSUE TITLE
feat: add argument to remove or preserve root logging handlers

### ISSUE THREAD

**Issue by girishc13** [jina-ai/jina#5629]
**Describe the feature**
JinaLogger removes all root logging handlers preventing output from modules using the root logger. This prevents logging of useful debug/trace logs of the module.

**Your proposal**

Add a new argument `suppress_root_logging` which gives the users the flexibility to switch off (current behavior) or enable root logger to get more useful information.

**Comment by JoanFM** [comment]
Hello @Jake-00,

Thanks for the interest on developing thia feature!!!.

The ticket has already been assinged to you. Please do not hesitate to ask our support.

We will be waiting for your Pull Request to review.

**Comment by Jake-00** [comment]
Sure, I will.
