### ISSUE TITLE
Question: How to discover the dynamic_batching has been enabled？

### ISSUE THREAD

**Issue by coolmian** [jina-ai/jina#5634]
I want to observe the actual length of each batch, but I can't see it in this way.

 I have read the relevant description of the document, but still do not understand its logic

executor.py
```python
class MyExecutor(Executor):
    @requests(on="/bar")
    def bar(self, docs: DocumentArray, **kwargs):
        print(len(docs))  # 1 is displayed here every time
```
client.py
```python

def send():
    c = Client(host='grpc://127.0.0.1:54321')
    a = Document()
    da = c.post('/bar', a)


if __name__ == '__main__':

    tasks = []
    for i in range(10):
        t = Thread(target=send)
        tasks.append(t)

    t0 = time.time()
    for t in tasks:
        t.start()
        t.join()
    print(time.time() - t0)
```
config.yml
```yaml
jtype: MyExecutor
py_modules:
  - executor.py
dynamic_batching:
  /bar:
    preferred_batch_size: 5
    timeout: 500
```

Does _preferred_batch_size_ refer to the length of _DocumentArray_ sent by a single client? Or does it mean that all _Document_ lengths sent by different clients are received at the same time?

If the number of documents I send at one time exceeds _preferred_batch_size_, will it be split into multiple processes?

**Comment by JoanFM** [comment]
Hello @coolmian,

I believe that the problem is that the client does not post to endpoint `bar`. 

The dynamic batching is related to the amount of Documents that an Executor processes at the same time.

**Comment by JoanFM** [comment]
Can you try with thia change:

```python
c.post('bar', a)
```

**Comment by coolmian** [comment]
> Can you try with thia change:
> 
> ```python
> c.post('/bar', a)
> ```

Sorry, my code contains this, so the server can receive the request, but I made a typographical error when copying it. The problem I described still exists. It always prints the number 1

**Comment by JoanFM** [comment]
Now I see, u are actually not parallelizing your threads propery, see that you are calling `join` right after calling thread start, which means no other threads will start before the other ended, so batches will not accumulate, and the timeout will trigger the request anyway

**Comment by JoanFM** [comment]
You should start the task before putting in the task lists, and then join one after the other

**Comment by JoanFM** [comment]
```python
def send():
    c = Client(host='grpc://127.0.0.1:54321')
    a = Document()
    da = c.post('/bar', a)


if __name__ == '__main__':

    tasks = []
    t0 = time.time()
    for i in range(10):
        t = Thread(target=send)
        t.start()
        tasks.append(t)

    for t in tasks:
        t.join()
    print(time.time() - t0)
```

**Comment by Jackmin801** [comment]
Threading is a little weird in CPython: https://docs.python.org/3/library/threading.html
![image](https://user-images.githubusercontent.com/56836461/215327777-241b8348-b91e-4843-aebf-97bddb1cbc9c.png)

So I would generally advise against it. Use multiprocessing map instead.
```python
import multiprocessing as mp

def send(_):
    c = Client(host='grpc://127.0.0.1:12345')
    a = Document()
    da = c.post('/bar', a)

if __name__ == '__main__':
    t0 = time.time()
    with mp.Pool(8) as p:
        p.map(send, range(20))
    print(time.time() - t0)
```

**Comment by coolmian** [comment]
> ```python
> def send():
>     c = Client(host='grpc://127.0.0.1:54321')
>     a = Document()
>     da = c.post('/bar', a)
> 
> 
> if __name__ == '__main__':
> 
>     tasks = []
>     t0 = time.time()
>     for i in range(10):
>         t = Thread(target=send)
>         t.start()
>         tasks.append(t)
> 
>     for t in tasks:
>         t.join()
>     print(time.time() - t0)
> ```

I made such a stupid mistake.
Thank you for your answer. Now I can see dynamic batch processing normally.

**Comment by coolmian** [comment]
> Threading is a little weird in CPython: https://docs.python.org/3/library/threading.html ![image](https://user-images.githubusercontent.com/56836461/215327777-241b8348-b91e-4843-aebf-97bddb1cbc9c.png)
> 
> So I would generally advise against it. Use multiprocessing map instead.
> 
> ```python
> import multiprocessing as mp
> 
> def send(_):
>     c = Client(host='grpc://127.0.0.1:54321')
>     a = Document()
>     da = c.post('/bar', a)
> 
> if __name__ == '__main__':
>     t0 = time.time()
>     with mp.Pool(mp.cpu_count()) as p:
>         p.map(send, range(20))
>     print(time.time() - t0)
> ```

Thank you. 
These codes can also respond normally, but it takes longer than using Threading. 
The response time of 10 concurrent requests is 1.6 seconds(Threading) and 5.9 seconds(multiprocessing ) respectively on my device. 
(This will have different effects under different devices or different number of requests, for reference only.)

**Comment by yuanjie-ai** [comment]
Have you really worked？

**Comment by yuanjie-ai** [comment]
# Server
```
from meutils.pipe import *
from jina import requests, dynamic_batching, Document, DocumentArray, Executor, Deployment, Flow

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('/home/jovyan/MODEL/intfloat_multilingual-e5-base', device='cuda')



class E(Executor):
    
    @requests(on='/encode')
    @dynamic_batching(preferred_batch_size=64, timeout=1_000) # 默认10s
    def func(self, docs: DocumentArray, parameters, **kwargs):
        print('#'*20) # parameters
        embeddings = model.encode(docs.texts, show_progress_bar=True)
        for doc, embedding in zip(docs, embeddings):
            doc.embedding = embedding
        # docs.embeddings = embeddings


f1 = Flow(port=8502).add(uses=E)

with f1:
    # 测试
    # r = f1.post('/', DocumentArray([Document(text='我是中国人')] * 5))
    # print(r[:, 'tags'])
    # r = f1.post('/', [Document(text='我是中国人')]*5)
    # print(r.texts)

    r = f1.post('/encode', DocumentArray([Document(text='我是中国人')] * 5))
    print(r.texts)
    print(r.embeddings)

```

# Client
```
def send():
    c = Client(host='grpc://0.0.0.0:8502')
    a = Document(text='111')
    da = c.post('/encode', a)


if __name__ == '__main__':

    tasks = []
    t0 = time.time()
    for i in range(64):
        t = Thread(target=send)
        t.start()
        tasks.append(t)

    for t in tasks:
        t.join()
    print(time.time() - t0)
```

**Comment by yuanjie-ai** [comment]
# Donot work
![image](https://github.com/jina-ai/jina/assets/20265321/70ae891b-55ae-42ca-af43-c859b563556e)

**Comment by JoanFM** [comment]
Why do you consider it does not work?

**Comment by JoanFM** [comment]
can you please initialize the model inside the Executor __init__ method and avoid having it as a global variable?

**Comment by yuanjie-ai** [comment]
> Why do you consider it does not work?

The server has executed multiple times

**Comment by yuanjie-ai** [comment]
preferred_batch_size=64,

**Comment by yuanjie-ai** [comment]
> can you please initialize the model inside the Executor **init** method and avoid having it as a global variable?

I tried, but I still can't

**Comment by JoanFM** [comment]
can u set the env variable 'JINA_LOG_LEVEL=DEBUG' to see more debug info?

**Comment by yuanjie-ai** [comment]
> can u set the env variable 'JINA_LOG_LEVEL=DEBUG' to see more debug info?

![image](https://github.com/jina-ai/jina/assets/20265321/34846e7d-ac19-4483-a4b2-7b9bd9908d3e)

**Comment by yuanjie-ai** [comment]
> > can u set the env variable 'JINA_LOG_LEVEL=DEBUG' to see more debug info?
> 
> ![image](https://user-images.githubusercontent.com/20265321/243926493-34846e7d-ac19-4483-a4b2-7b9bd9908d3e.png)

Document length less than 3 but executed three times

**Comment by JoanFM** [comment]
Can you please open a new issue and share the exact code to reproduce, this is very weird as it seems that you have 2 Executors in the Flow which does not match the script u shared
