### ISSUE TITLE
 timeout after waiting       and cant download image

### ISSUE THREAD

**Issue by fqzhao-win** [jina-ai/jina#5643]
**Describe the bug**
ERROR  JINA@18408 can not download image, please check your [02/01/23 14:15:02]
       graph and the network connections                                       
WARNI… executor0/rep-0@18408 <jina.orchestrate.pods.Pod     [02/01/23 14:30:37]
       object at 0x000002625912A9C8> timeout after waiting                     
       for 600000ms, if your executor takes time to load,                      
       you may increase --timeout-ready                                        
WARNI… gateway/rep-0@18408 <jina.orchestrate.pods.Pod       [02/01/23 14:30:50]
       object at 0x0000026259156408> timeout after waiting                     
       for 600000ms, if your executor takes time to load,                      
       you may increase --timeout-ready                                        
ERROR  Flow@18408 Flow is aborted due to ['executor0',      [02/01/23 14:30:52]
       'gateway'] can not be started.  

**Describe how you solve it**

now i dont know
---

**Environment**

**Screenshots**

**Comment by fqzhao-win** [comment]
i also have another problem,why does it occupies much more memory using flow than before

**Comment by JoanFM** [comment]
Hello, what is your example? Also, it seems that you are using a very old Jina version

**Comment by fqzhao-win** [comment]
class MyExecutor(Executor):
    @requests
    def foo(self, docs, **kwargs):
        ner_config = {'kg_ner': '1', 'deep_common_ner': '1', 'deep_per_ner': '1'}
        scene = 'common'
        sentences = []
        for index, doc in enumerate(docs):
            print(index)
            sentences.append(doc.text)
        ner_result = entity_recognition.get_entity(sentences)
        for index, doc in enumerate(docs):
            doc.tags['ner'] = ner_result[index]
            print(doc.tags['ner'])
            print(doc.text)
        print(self)
        print('=========一个副本运行结束======')


def main():
    pre_time = time.time()
    f = Flow(protocol='http').add(uses=MyExecutor, replicas=3)
    pre_time2 = time.time()
    print('设置flow的时间')
    print(pre_time2-pre_time)
    f.plot('1.svg')
    input_docs = DocumentArray([Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'), Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),Document(text='王安石是个好人'), Document(text='李白是个好人'), Document(text='范丞丞是个好人'), Document(text='翟潇闻是个好人'), Document(text='刘备是个好人'),])
    # input_docs = DocumentArray([Document(text='杨幂和刘恺威是夫妻')])
    input_docs = DocumentArray.empty(len(sentences))
    input_docs.texts = sentences

    with f:
        time1 = time.time()
        returned_docs2 = f.post(on='/', inputs=input_docs, request_size=20, results_in_order=True)
        time3 = time.time()
        for doc in returned_docs2:
            print(doc.tags['ner'])
        print(time3 - time1)
        f.block()


if __name__ == '__main__':
    main()

**Comment by fqzhao-win** [comment]
I loaded a pytorch model in the executor. Using the executor to load the model in the flow takes more memory than simply loading the model. I don't know why. The specific code is inconvenient to display. Thank you very much for your help

**Comment by fqzhao-win** [comment]
![1675241848594](https://user-images.githubusercontent.com/45990111/215996858-60af67e5-6612-40ac-9d92-1178e6ad7dfa.png)

**Comment by fqzhao-win** [comment]
def main():
    pre_time = time.time()
    f = Flow(protocol='http').add(uses=MyExecutor, replicas=3)
    pre_time2 = time.time()
    print('设置flow的时间')
    print(pre_time2-pre_time)
    f.plot('1.svg')
    # input_docs = DocumentArray([Document(text='杨幂和刘恺威是夫妻')])
    input_docs = DocumentArray.empty(len(sentences))
    input_docs.texts = sentences

    with f:
        time1 = time.time()
        returned_docs2 = f.post(on='/', inputs=input_docs, request_size=20, results_in_order=True)
        time3 = time.time()
        for doc in returned_docs2:
            print(doc.tags['ner'])
        print(time3 - time1)
        f.block()


if __name__ == '__main__':
    main()

**Comment by JoanFM** [comment]
What is this `entity_recognition`? Can you share a reproducible code?

In order to format code u can use (```python your code ```)

**Comment by JoanFM** [comment]
This MyExecutor will not work for me

**Comment by JoanFM** [comment]
Can u send the complete `MyExecutor` code?

**Comment by fqzhao-win** [comment]
I'd like to, but this is the company code. I don't have permission，Thank you very much.

**Comment by JoanFM** [comment]
Okey, but some Minimal Reproducible Example? 

What I believe is the most likely cause is that the Executor does some slow task at `init` time? maybe downloading something and it takes too long. If u could do the download offline, the Executor would start faster and skip the `timeout`. 

Otherwise, you can set the `timeout_ready` parameter to `-1` to avoid the timeout

**Comment by fqzhao-win** [comment]
Sorry, I just saw it, thank you
