### ISSUE TITLE
Where will jina write logs to when it triggers `continue_on_error`?

### ISSUE THREAD

**Issue by wqh17101** [jina-ai/jina#5659]
We use `post` to send request to server with parameter `continue_on_error`.
`if set, a Request that causes an error will be logged only without blocking the further requests.`
So where will it be logged to and what will write to the logs.

**Comment by JoanFM** [comment]
Hello @wqh17101 ,

here logging means that the logger will log the error. You can configure the logger as you want but by default it will log to the terminal of the Client

**Comment by wqh17101** [comment]
@JoanFM TY. So  how to config the logger? Is there any example?

**Comment by JoanFM** [comment]
You could see it in this PR https://github.com/jina-ai/jina/pull/5638/files

The documentation will be there in the next minor

**Comment by wqh17101** [comment]
@JoanFM Great. Thank you.
