### ISSUE TITLE
When the GRPC protocol is used to invoke the jina server, the synchronization request is always blocked.

### ISSUE THREAD

**Issue by crbean** [jina-ai/jina#5666]
**Describe the bug**

When the GRPC protocol is used to invoke the jina server, the synchronization request is always blocked.

**Describe how you solve it**

client.post('/', Document, parameters=XXX, results_in_order=True, continue_on_error=True,max_attempts=3)
---

**Environment**

**Screenshots**

**Comment by crbean** [comment]
There is no related record in the log. When you run the py_spy command to view the current stack, you can find that the thread is blocked.

Thread 33994 (idle)
         select (selectors.py:469)
         _run_once (asyncio/base_events.py:2381)
         run_forever (asyncio/base_events.py:857)
         run_until_complete (asyncio/base_events.py:634)
         run (asyncio/runners.py:300)
         run_async (jina/helper.py:1854)
         post (jina/clients/mixin.py:1041)

**Comment by JoanFM** [comment]
Hello, can you share ur Flow and code to reproduce?

**Comment by crbean** [comment]
f = Flow(port=JINA_PORT, host=JINA_IP, timeout_send=TIMEOUT_SEND).add(uses=XXX, replicas=int(2), host=JINA_IP)

**Comment by JoanFM** [comment]
what is your `JINA_IP` is it localhost?

Also, it is important to know what is the Executor doing.

What do you see when setting `JINA_LOG_LEVEL=TRUE`?

**Comment by crbean** [comment]
JINA_IP is 127.0.0.1
how to know what is the Executor doing?
Does the value of JUNA_LOG_LEVEL need to be set to debug?

**Comment by JoanFM** [comment]
sorry, Debug not True

**Comment by JoanFM** [comment]
Is thr Executor something you develop or u use one from the Hub?

**Comment by wqh17101** [comment]
Yeah,we develop a executor like clip-as-service——using bert to inference which is the model trained by `transformers`

**Comment by JoanFM** [comment]
one thing that is weird is that in the `post` it seems that you are passing a `Document` class and not a `Document` instance

**Comment by JoanFM** [comment]
I would need to see some logs to understand the problem. It is hard to take actions with the information provided

**Comment by wqh17101** [comment]
@JoanFM 
> one thing that is weird is that in the `post` it seems that you are passing a `Document` class and not a `Document` instance
No,it is `DocumentArray([Document(text=text) for text in data_list])`

**Comment by wqh17101** [comment]
> I would need to see some logs to understand the problem. It is hard to take actions with the information provided

Try to collect.

**Comment by wqh17101** [comment]
@JoanFM No,just close it now, and i will open it if i need.

**Comment by JoanFM** [comment]
Will close it for the time being, do not hesitate to reopen an issue for any problem
