### ISSUE TITLE
Fix the code snippet and documentation in the "Deploy to JCloud" section 

### ISSUE THREAD

**Issue by Keertiraj** [jina-ai/jina#5680]
**Describe the bug**
In the section "Deploy to JCloud" of the documentation, "https://docs.jina.ai/get-started/create-app/", when i ran the command, "jina cloud deploy ./", i got below response:

![image](https://user-images.githubusercontent.com/4416580/217835792-4217fcfa-c5d7-4046-aba8-481194c7a08a.png)

I could see 2 issues:

1.  There is no endpoint appearing on the response (which i could use to copy in the command, "c = Client(host='Endpoint')"
2.  There is an error at the end, saying "Got an error from the server: forbidden (unknown tier id: )
You have exceeded your quota. Please clean up your Flow inventory."
3. Code Snippet "c = Client(host='grpcs://1655d050ad.wolf.jina.ai')" is hard coded. The document needs to state that, this host must copied from the response of the command: ""jina cloud deploy ./"

However, when i login into "https://cloud.jina.ai/" the executor is deployed.

**Describe how you solve it**

1.  Fix the code snippet in "Deploy to JCloud".
2. Explain in the documentation, on how to resolve the issue on "...exceeded your quota."
3. In the code snippet, explain to the user that the host needs to populated the response of the command: ""jina cloud deploy ./"

---

**Comment by asuzukosi** [comment]
Hello @JoanFM and @deepankarm , please is this issue still open. I would like to work on it.

**Comment by JoanFM** [comment]
Hey @asuzukosi,

This issue I believe is still open, so if you know how to solve it, go ahead and thanks a lot for the collaboration

**Comment by asuzukosi** [comment]
@JoanFM alright then, I'll get to it
