### ISSUE TITLE
Unable to delete the executor from local CLI command

### ISSUE THREAD

**Issue by Keertiraj** [jina-ai/jina#5683]
**Describe the bug**

I am unable to  delete the Executor which was created by following the steps described in the section "Deploy to JCloud" of the document "https://docs.jina.ai/get-started/create-app/".  Here is the error response i received:

![image](https://user-images.githubusercontent.com/4416580/217871156-f464f179-711e-4d58-a167-530cb0b16180.png)

Also, in the documentation, the below code snippet is hard coded:

`jina cloud remove 1655d050ad`. Here the executor value needs to be dynamic and needs to be reflected in the documentation.

**Comment by asuzukosi** [comment]
@JoanFM and @deepankarm , if this issue is still open I would like to work on it. @Keertiraj please can you give any idea on how to make the executor id dynamic in the documentation.
