### ISSUE TITLE
DocArray v2 Compatibility

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5700]
**Describe the feature**
Epic ticket to track what is needed to guarantee Jina leverages DocArray v2.

- Use `reduce` method of DocArray v2.
- Use `filter` method of v2.
- Enable `http` and `websocket` Flow gateways.
- Enable single Deployment with HTTP protocol with automatic FastAPI routing enabled. 
- Enable interoperability for Encoders and Indexers type of Executors.
- support with protobuf 4 https://github.com/jina-ai/jina/issues/5701
- Default to LegacyDocument on DocArray when from docarray import Document is done

- [x] #5832
- [x] #5833
- [x] #5834
- [x] #5835
- [x] #5836
- [ ] #5837
- [ ] #5838
- [ ] #5839

**Comment by shivamm7** [comment]
Hi @JoanFM , can you please elaborate on what is required to be done in 'Use `reduce` method of DocArray v2'. From what I can understand, the `reduce` method is implemented in DocArray v2 and DocArray is imported in Jina. So, do we need to check the Jina codebase to see where we can replace code and use the `reduce` method instead?
