### ISSUE TITLE
docs: Put Deployment at the center of Documentation

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5712]
**Describe the feature**
In Docs, Flow still has a more prominent role than Deployment, we have to do this shift

**Comment by alexcg1** [comment]
Most of the content is there already, we just need to change focus. So I can take lead on this and @alaeddine-13 can review as needed

**Comment by alexcg1** [comment]
Here are some pages that need updating:

- [Create First Project - Jina 3.14.1 documentation](https://docs.jina.ai/get-started/create-app/)
- [Coding in Python/YAML - Jina 3.14.1 documentation](https://docs.jina.ai/concepts/preliminaries/coding-in-python-yaml/)
- [Clean & Efficient Code - Jina 3.14.1 documentation](https://docs.jina.ai/concepts/preliminaries/clean-code/)
- [Client - Jina 3.14.1 documentation](https://docs.jina.ai/concepts/client/)
- [Docker Compose Support - Jina 3.14.1 documentation](https://docs.jina.ai/cloud-nativeness/docker-compose/)
- [OpenTelemetry Support - Jina 3.14.1 documentation](https://docs.jina.ai/cloud-nativeness/opentelemetry/)
- [Executor Hub - Jina 3.14.1 documentation](https://docs.jina.ai/concepts/executor/hub/)
- [Use - Jina 3.14.1 documentation](https://docs.jina.ai/concepts/executor/hub/use-hub-executor/)
- [YAML Specification - Jina 3.14.1 documentation](https://docs.jina.ai/yaml-spec/) (missing Deployment)
- [Telemetry - Jina 3.14.1 documentation](https://docs.jina.ai/telemetry/)

**Comment by JoanFM** [comment]
Kubernetes support one also

**Comment by alexcg1** [comment]
I'll make a start on this

**Comment by alexcg1** [comment]
> [Create First Project - Jina 3.14.1 documentation](https://docs.jina.ai/get-started/create-app/)

Currently blocked since need:

- `jcloud` to support `Deployment`
- `jina new hello-jina` to create Deployment not Flow
