### ISSUE TITLE
Restructure Orchestration documentation

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5713]
Jina introduces 2 concepts to orchestrate Executors:
* Flow
* Deployment

Previously, as we highlight Executors as standalone services, the role of Deployment was minor because we do not support Jcloud deployments yet.
As JCloud is about to introduce `Deployment` deployment, the Documentation should focus more on Deployment as much as Flow.

We propose to rename the Flow section in the documentation to `Orchestration` or somthing similar (preferrably a naming that indicates what is the purpose behind these 2 concepts, i.e, serving, building, deploying,..)
Then in this section, we would introduce each of Deployment and Flow and basic usage for them.

Then, each `orchestration` feature should be presented/defined regardless of the orchestrator that activates it. The code snippet can be 2 tabs that showcases the feature with Deployment and Flow in conjunction. 
For instance:
```python
From jina import Deployment
Deployment(uses=MyExecutor, replicas=3)
```
and 
```python
From jina import Flow
Flow().add(uses=MyExecutor, replicas=3)
```

Structure:
```
Orchestration/
├── Deployment
 |.       ├ Example
 |.       └YAML spec
├── Flow
 |.       ├ Example
 |.       ├ Flow specific features (don't really have to be in the same sub section)
 |.       └YAML spec
├── Add executor
├── Scale out
├── hot reload
...
└── Instrumentation
```
Additionally, we might need to pull out some features documented in Executor into the orchestration ? (Executor hot reload is mostly controlled within Deployment)

**Comment by nikitashrivastava29** [comment]
Can I get assigned to this? I've gone through the documentation so maybe I'd be able to help out...

**Comment by JoanFM** [comment]
Hey @nikitashrivastava29 ,

This is a very important and in-depth change in our documentation, so we will handle internally. You would be much welcome to review and provide feedback

**Comment by alexcg1** [comment]
This is going to get ugly if we put add equivalent tabs for Deployments as well as Flows. That'll push this to 6 tabs
![image](https://user-images.githubusercontent.com/4182659/223441812-e35cabf3-a4f3-429c-b847-7f70da34968b.png)

otoh, I'd rather not have the content duplicated under both Flows and Deployments, since syncing will be a pain.

One option might be:

```
### Deployment

3 tabs - Deployment, client, CLI

### Flow

3 tabs - Flow, client, CLI
```

It's not exactly elegant, but it's the least bad solution I can think of for now

**Comment by alexcg1** [comment]
@alaeddine-13 regarding:

```
Orchestration/
├── Deployment
 |.       ├ Example
 |.       └YAML spec
├── Flow
 |.       ├ Example
 |.       ├ Flow specific features (don't really have to be in the same sub section)
 |.       └YAML spec
├── Add executor
├── Scale out
├── hot reload
...
└── Instrumentation
```

Are you proposing a 3-level structure? e.g. Orchestration -> Flow -> YAML spec? This will be inconsistent with how we've done things until now, but Sphinx supports it.

Or our existing 2-level structure - Orchestration -> Flow (and YAML spec is contained on Flow page). This will make the Flow page quite long.

**Comment by alexcg1** [comment]
Current progress:

- [ ] Orchestration
	- [ ] deployment
	- [ ] flow
	- [ ] add-executors
	- [ ] scale-out
	- [ ] hot-reload
	- [ ] handle-exceptions
	- [ ] readiness
	- [ ] health-check
	- [ ] instrumentation
	- [ ] troubleshooting-on-multiprocess
	- [ ] yaml-spec
