### ISSUE TITLE
Add ICA to numeric encoders

### ISSUE THREAD

**Issue by JamesTang616** [jina-ai/jina#572]
**Describe the feature**
With the new APIs, we can support ICA encoder.

**Your proposal**
add `ICA` in `executors/encoders/numeric/ica.py`

---

**Environment**
jina                          0.3.1
jina-proto                    0.0.43
jina-vcs-tag                  (unset)
libzmq                        4.3.1
pyzmq                         1.19.0
protobuf                      3.12.2
proto-backend                 cpp
grpcio                        1.30.0
ruamel.yaml                   0.16.10
python                        3.7.3
platform                      Linux
platform-release              3.10.0-957.27.2.el7.x86_64
platform-version              #1 SMP Mon Jul 29 17:46:05 UTC 2019
architecture                  x86_64
processor                     x86_64
jina-resources                /root/anaconda3/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)

**Comment by alexcg1** [comment]
Thanks for the feedback James! Our team will look into this and get back to you soon. In the meantime, feel free to get in touch on our [Slack group](https://jina-ai.slack.com/)
