### ISSUE TITLE
The 'First Project' in the Jina developer guide has bug

### ISSUE THREAD

**Issue by Keertiraj** [jina-ai/jina#5732]
1. Go to the link: https://docs.jina.ai/get-started/create-app/
2. Follow all the instructions till ‘Call /crunch-number endpoint’ section.
3. Copy the code in the documentation for  ‘client.py’ and run python client.py
4. The  exception occurs (image screenshot: error1.png)
![error1](https://user-images.githubusercontent.com/4416580/222412653-15c0d4c4-5013-43ff-822f-34d914b01268.jpeg)

5. Change the code snippet for host to point to localhost:  host='grpcs://0.0.0.0:54321' and run python client.py
6. The  exception occurs (image screenshot: error2.png)![error2](https://user-images.githubusercontent.com/4416580/222412690-174451da-1c39-43fc-9b79-736c1d9a2031.jpeg)

**Comment by AkbarHabeeb** [comment]
@Keertiraj Can you please ensure to add the correct port`Client(host='grpc://0.0.0.0:55186')`

For your kind information, once the server is up, we will get a message saying **🎉 Flow is ready to serve!**  like below
<img width="271" alt="Screenshot 2023-03-04 at 7 14 07 PM" src="https://user-images.githubusercontent.com/20479150/222905835-a5327e8d-a339-4817-b7b7-7d130667040b.png">

Can you get the local port number and add it to the client? It worked for me.

**Comment by npitsillos** [comment]
I can confirm that running the flow locally and sending requests is working as expected, see below.
![image](https://user-images.githubusercontent.com/9141826/223084240-999f3edf-5cd2-4c7e-b45c-afe36c1982ec.png)

![image](https://user-images.githubusercontent.com/9141826/223084297-4abf3f12-6a27-4975-b4f3-ca76cad8e623.png)

**Comment by asuzukosi** [comment]
Hello at @Keertiraj, the flow and client run as two separate processes, your server will need to be running while you execute the client. Also ensure no other service is running on the ports reserved for the Jina flow. Hope this helps
