### ISSUE TITLE
Enable streaming endpoint

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#5739]
**Describe the feature**
Enable for single Deployment to stream responses.

Executor would look like:

```python
from jina import Executor, requests, Document

class StreamingExecutor(Executor):

@requests
def foo(self, docs, **kwargs):
    for doc in docs:
       for ret in self.model.generate(doc.text): 
          yield Document(text=ret)
```

**Comment by asuzukosi** [comment]
Hmm, this is interesting. But how would this kind of executors be supported on http gateways as http does not support streaming?
