### ISSUE TITLE
DocArray v2 support with http and websockets protocols

### ISSUE THREAD

**Issue by alaeddine-13** [jina-ai/jina#5753]
Add support for docarray v2 with http and websockets protocols.
Should also make sure that tensors, when deserialized in the http gateway, do not necessarily get deserilized into torch tensors

**Comment by asuzukosi** [comment]
Hello @alaeddine-13 just to clarify, you mean when DocArrays are being used in executors right? Because I am not certain if DocArrays can be connect through http or websockets natively. For the deserialization do you have any suggestions on what they could be deserialized into?

**Comment by JoanFM** [comment]
Ticket handled in other issues
