### ISSUE TITLE
The link to join the slack community is not working

### ISSUE THREAD

**Issue by asuzukosi** [jina-ai/jina#5754]
Hello, I have been trying to join the slack community but the link on the website and on the repo are not working. It gives the error message that the link is expired. 
![IMG_D312D37B943D-1](https://user-images.githubusercontent.com/34872572/224312523-f6b92ab2-4ccd-4033-8636-cb01ad03293e.jpeg)

**Comment by Nick17t** [comment]
Could you please clear your cookie and try it again?

**Comment by asuzukosi** [comment]
Okay, would try that now

**Comment by asuzukosi** [comment]
Hello @Nick17t just tried it again, its still giving the same response after clearing my cache.

**Comment by alexcg1** [comment]
@JoanFM this isn't my area. Link needs to be re-generated within Slack and that's someone else's domain
