### ISSUE TITLE
Add option on the Jina CLI to allow deployment centric projects by adding a `deployment` flag

### ISSUE THREAD

**Issue by asuzukosi** [jina-ai/jina#5755]
**Describe the feature**
Add option for `jina new` to be either flow centric or deployment centric

**Your proposal**
Add a flag to the `jina new` command to allow optional creation of deployment centric

**Comment by JoanFM** [comment]
Hello @asuzukosi,

Thanks for opening this ticket. Any specific UX that you would like this option to have?

**Comment by asuzukosi** [comment]
Yes, a flag could be added to the `jina new` command `deployment` which would specify that a deployment project is being created and `flow` which would specify that a flow project is being created. It would default to a flow if none are specified to maintain backward compatibility. I would like to work on this if it can be approved.

**Comment by JoanFM** [comment]
Sure, you can work on it

**Comment by asuzukosi** [comment]
Okay, thank you @JoanFM
