### ISSUE TITLE
Replicas don't work in Kubernetes cluster (concurrency is broken)

### ISSUE THREAD

**Issue by Murugurugan** [jina-ai/jina#5788]
**Describe the bug**
My Kubernetes cluster basically ignores replicas. When I try to send 2 requests at the same time concurrently via async, or 2 terminals, it always puts the second request in the queue and only processes stuff 1 by 1, even though I have 2 or more replicas for that executor set. Even if I have 2 replicas of gateways, it is the same issue. I also have problems of sending HTTP post request via a python httpx module, but client from Jina works just fine, which is weird (/post seems to work, but not /test in httpx). I am testing everything locally on Windows WSL2 docker's kubernetes.

I followed the Jina's docs as close as I could and created an executor with __ init__.py, Dockerfile and config.yml, then I made a container from it. I added a simple time.sleep(10) for testing. I tried to play with async def, asyncio, prefetch settings in Flow or Client, none of that changed the issue. Kubernetes pods don't log any errors. I tried to expose it, so I don't have to use portforwarding and so it created LoadBalancer, but still nothing. I tried GRPC or HTTP, doesn't work either way. I don't know what to do, please help.

Executor:
```python
from jina import Executor, requests, DocumentArray
import time

class test_fnc(Executor):
    @requests(on='/test')
    def function(self, docs: DocumentArray, **kwargs):

        time.sleep(10)

        docs[0].text = "test1"
        docs[1].text = "test2"
```

Flow:
```python
from jina import Flow

def main():
    f = (
        Flow(asyncio=True, host="0.0.0.0", port=8080, protocol="http", cors=True)
        .add(uses="docker://test_image", replicas=2)
    )
    
    f.to_kubernetes_yaml('./k8s', k8s_namespace='test_namespace')

    with f:
        f.block()

if __name__ == '__main__':
    main()
```

Client:
```python
import asyncio
from jina import Client, DocumentArray


c = Client(host="localhost", port=80, protocol='http', asyncio = True)

async def test():
    async for resp in c.post(on='/test', inputs=DocumentArray.empty(2), stream=True, results_in_order=False, asyncio=True):
        print(resp.texts)

async def main():
    tasks = [test() for _ in range(2)]
    await asyncio.gather(*tasks)


if __name__ == '__main__':
    asyncio.run(main())
```

This simple HTTP post also doesn't work, it returns {'detail': 'Not Found'}:
```python
import httpx

url = "http://localhost:80/test"
headers = {"Content-Type": "application/json"}
data = {"data": [{"text": ""},{"text": ""}]}

response = httpx.post(url, json=data, headers=headers)

print(response.json())
```

**Environment**
- jina 3.14.1
- docarray 0.21.0
- jcloud 0.2.5
- jina-hubble-sdk 0.35.0
- jina-proto 0.1.13
- protobuf 4.22.1
- proto-backend upb
- grpcio 1.53.0
- pyyaml 6.0
- python 3.11.2
- platform Windows
- platform-release 10
- platform-version 10.0.25324
- architecture AMD64
- processor AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- uid 91757978404
- session-id 09dd7cc7-d392-11ed-a5e2-00155d33a324
- uptime 2023-04-05T11:12:49.650042
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Screenshots**
![k8s_wtf](https://user-images.githubusercontent.com/125469363/230037280-012258ba-093a-473b-8770-c1c760ce86b9.png)

**Comment by JoanFM** [comment]
Hello @Murugurugan ,

Thanks for the issue reported. Would it be possible for you to clarify better what is working and what not, with clear steps to reproduce both cases.

It seems that u are starting a Flow locally and trying to access it but also trying to deploy a Flow in Kubernetes, but is not clear which error or behavior corresponds to each of them.

**Comment by JoanFM** [comment]
sorry, for the httpx issue I did not change the url, u have to call the url `"http://localhost:80/post`

**Comment by JoanFM** [comment]
What do you observe if you do this?

```python
import multiprocessing
import time

from jina import Client, DocumentArray


def test():
    t0 = time.time()
    c = Client(host="localhost", port=80, protocol='http')
    resp = c.post(on='/test', inputs=DocumentArray.empty(2), stream=True, results_in_order=False)
    print(resp.texts)
    print(f' time single client {time.time() - t0}')


def main():
    processes = [multiprocessing.Process(target=test) for _ in range(6)]
    t0 = time.time()
    for p in processes:
        p.start()

    for p in processes:
        p.join()
    print(f' time all clients {time.time() - t0}')


if __name__ == '__main__':
    main()
```

**Comment by JoanFM** [comment]
would it be possible for you to share with us the exact Flow configuration and the exact Kubernetes YAML configurations being deployed?

**Comment by JoanFM** [comment]
Also, have u made sure that you have a `service mesh` installed? https://docs.jina.ai/cloud-nativeness/k8s/#required-service-mesh
