### ISSUE TITLE
demo bug

### ISSUE THREAD

**Issue by yuanjie-ai** [jina-ai/jina#5792]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/20265321/230755410-010283ed-3241-42fc-af68-eb4222dbdf63.png">
from jina import Executor, requests, DocumentArray, Document, Deployment

class MyExecutor(Executor):
    @requests
    def foo(self, docs, **kwargs):
        for d in docs:
            d.text = 'hello world'

with Deployment(uses=MyExecutor) as dep:
    response_docs = dep.post(on='/', inputs=DocumentArray([Document(text='hello')]))
    print(f'Text: {response_docs[0].text}')

**Comment by yuanjie-ai** [comment]
```
from jina import Executor, requests, DocumentArray, Document, Deployment


class MyExecutor(Executor):
    @requests
    def foo(self, docs, **kwargs):
        for d in docs:
            d.text = 'hello world'


with Deployment(uses=MyExecutor) as dep:
    response_docs = dep.post(on='/', inputs=DocumentArray([Document(text='hello')]))
    print(f'Text: {response_docs[0].text}')
```

**Comment by JoanFM** [comment]
What system are you running Jina on?

**Comment by yuanjie-ai** [comment]
mac

**Comment by JoanFM** [comment]
Have you followed the instructions to install stated here?

https://docs.jina.ai/get-started/install/apple-silicon-m1-m2/#on-apple-silicon

**Comment by JoanFM** [comment]
Hey @yuanjie-ai ,

this erorr should be solved by setting this env var:

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
