### ISSUE TITLE
does incremental indexing work or not

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#580]
**Describe the feature**

- `KVIndexer` use `doc_id`/`chunk_id` as key
- `doc_id`/`chunk_id` are generated randomly as I remember
- so, incremental indexing should work since keys are unique
  - (i believe) it's client's responsibility to tell jina when to continuously index, and it's client's responsibility to ensure the uniqueness of each entry
  - otherwise, use [deephash](https://zepworks.com/deepdiff/5.0.0/deephash.html) to determine the uniqueness of the KV pair? 

**Your proposal**

- unit test?
- what to do on duplicate indexing?
- need some warning/logging when work on non-empty index. I think we have already?
- lack of sanity check on different type of index data.

---

**Environment**

**Screenshots**

**Comment by lusloher** [comment]
This will be picked back up in September timeframe
