### ISSUE TITLE
Flow/Deployment would raise timeout warning even if containerized executor is running

### ISSUE THREAD

**Issue by eugene-yh** [jina-ai/jina#5807]
**Describe your problem**

---
I follow the tutorial [here](https://docs.jina.ai/concepts/executor/containerize/) and create my own docker image called "my_exec" for an executor. It works perfectly when I use `jina executor --uses docker://my_exec` to serve the executor and use a Client object to use it. However, serving by using a Flow or a Deployment object would always raise a timeout warning and hang indefinitely as shown in the following screenshots.

My executor needs to load a large neural net to initialize, which takes about 1 minute. I thought this loading time could be the cause of the problem and tried setting `timeout-ready` to -1, but I still cannot get rid of this warning. 

Another possible cause maybe that the entrypoint of my docker image is `ENTRYPOINT ["conda", "run", "-n", "legacy_subtitle_punc", "jina", "executor", "--uses", "config.yml"]` where I activate a conda environment before calling jina instead of calling jina directly. Does this have something to do with the problem? If it is the cause, are there any workarounds that still allow me to use conda? 
 

**Environment**

- jina 3.14.1
- docarray 0.21.0
- jcloud 0.2.6
- jina-hubble-sdk 0.35.0
- jina-proto 0.1.13
- protobuf 3.20.3
- proto-backend cpp
- grpcio 1.47.5
- pyyaml 5.3.1
- python 3.7.16
- platform Linux
- platform-release 3.10.0-957.el7.x86_64
- platform-version #1 SMP Thu Nov 8 23:39:32 UTC 2018
- architecture x86_64
- processor x86_64
- uid 274973452769639
- session-id d8df0eec-da9b-11ed-9f15-fa163ef99967
- uptime 2023-04-14T16:10:40.727171
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Screenshots**

when using Flow to serve the executor (Deployment raises the same warning except that there are no other logs printed):
![爱奇艺20230414155409](https://user-images.githubusercontent.com/52963371/231983318-b89e720c-176f-41f7-90b5-a4dbf2cc47ad.png)

**Comment by JoanFM** [comment]
Hello @eugene-yh ,

can you share the exact code that u run?

**Comment by JoanFM** [comment]
What is the reason for you to use `conda`?

**Comment by eugene-yh** [comment]
> What is the reason for you to use `conda`?

hi @JoanFM, I use conda because my neural net model was trained years ago with tensorflow1.14 and python3.6. It seems like jina only supports python 3.7 and above so I tried python3.7 vanilla on my Centos7.6 machine and met a known issue about libstdc++.so ([link](https://github.com/tensorflow/tensorflow/issues/26378)). It seems the only way to resolve it without modifying system cofigurations is by using conda to install tensorflow for python3.7.

**Comment by JoanFM** [comment]
can u add `JINA_LOG_LEVEL=DEBUG` as env variable before running the script?

**Comment by JoanFM** [comment]
but can't u use conda to install tensorflow in a previous layer of the docker image?

**Comment by eugene-yh** [comment]
> can u add `JINA_LOG_LEVEL=DEBUG` as env variable before running the script?

![爱奇艺20230414171124](https://user-images.githubusercontent.com/52963371/232001163-c11fcfaa-f163-4126-8669-46e8a91a9eea.png)

this is what happens after i add JINA_LOG_LEVEL=DEBUG

**Comment by eugene-yh** [comment]
> but can't u use conda to install tensorflow in a previous layer of the docker image?

Can you show me some referefences on how to do that? I will definitely try it. But it seems to me that it is a problem about activating conda environment rather than installing tensorflow. Am I right?

**Comment by JoanFM** [comment]
and how does ur `flow.yml` look like?

**Comment by eugene-yh** [comment]
my flow.yml:

**Comment by JoanFM** [comment]
no content added

**Comment by eugene-yh** [comment]
my flow.yml:

jtype: Flow
executors:
  \- name: LegacySubtitlePuncNormalization
    uses: docker://my_exec

my script:
`jina flow --uses flow.yml`

**Comment by JoanFM** [comment]
can u try with this Flow?

```yaml
jtype: Flow
executors:
  - name: LegacySubtitlePuncNormalization
    uses: docker://my_exec
    timeout_ready: -1
    env:
      JINA_LOG_LEVEL: DEBUG
```

**Comment by eugene-yh** [comment]
still the same it seems.

![爱奇艺20230414172556](https://user-images.githubusercontent.com/52963371/232005134-e79cfc19-f1b7-4604-a38e-0298d1556fc2.png)

**Comment by eugene-yh** [comment]
a new line after a minute:

![爱奇艺20230414172835](https://user-images.githubusercontent.com/52963371/232005747-260e1728-6a9d-4b47-88f2-74379f6cc4bc.png)

**Comment by JoanFM** [comment]
is there any chance I can get the Dockerfile for your `my_exec`? maybe hiding some details?

**Comment by JoanFM** [comment]
Can you run this?

```shell
docker run -it --entrypoint "conda" my_exec run -n legacy_subtitle_punc jina -v
```

I want to understand what Jina version is running inside there.

**Comment by JoanFM** [comment]
otherwise, to reproduce, I need some dummy version of your `executor_root` folder. Specially the `.tar.gz` if it does not contain any private thing or if you can hide any not-needed details

**Comment by eugene-yh** [comment]
> Can you run this?
> 
> ```shell
> docker run -it --entrypoint "conda" my_exec run -n legacy_subtitle_punc jina -v
> ```
> 
> I want to understand what Jina version is running inside there.

I got 3.14.1 after running it

**Comment by eugene-yh** [comment]
> otherwise, to reproduce, I need some dummy version of your `executor_root` folder. Specially the `.tar.gz` if it does not contain any private thing or if you can hide any not-needed details

I can make a minimal example for this issue. I'll let you know when I'm done.

**Comment by JoanFM** [comment]
also, what is the output od this command?

```shell
docker run -it --entrypoint "ls" my_exec
```

**Comment by eugene-yh** [comment]
hi @JoanFM , here is the code to reproduce the issue. 
[test_issue.tar.gz](https://github.com/jina-ai/jina/files/11233279/test_issue.tar.gz)

**Comment by eugene-yh** [comment]
However, I found a partial solution to this. I changed `ENTRYPOINT ["conda", "run", "-n", "legacy_subtitle_punc", "jina", "executor", "--uses", "config.yml"]` to `ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "legacy_subtitle_punc", "jina", "executor", "--uses", "config.yml"]` and this will make flow not to hang anymore. But, if you use `Ctrl+C` to terminate the service, you will receive the following error indicating that the shutdown signal cannot be received, and I can see that the docker container is still running.

what "--no-capture-output" does (according to [conda's doc](https://docs.conda.io/projects/conda/en/latest/commands/run.html)) is simply allow stdout and stderr to pass. So, does this mean that the communication between the inside and the outside of a jina's executor container is done or partially done through stdout/stderr?

**Comment by JoanFM** [comment]
Hey, no it is not. THe communication is done via the network, by sending `health checks` from the Flow to each Executor

**Comment by JoanFM** [comment]
so what u can check is:

while u are starting the Flow, if u can do `jina ping executor 0.0.0.0:55423` (actually the host can be 0.0.0.0 or the one coming from the Gateway of your docker bridge network`)

**Comment by eugene-yh** [comment]
> However, I found a partial solution to this. I changed `ENTRYPOINT ["conda", "run", "-n", "legacy_subtitle_punc", "jina", "executor", "--uses", "config.yml"]` to `ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "legacy_subtitle_punc", "jina", "executor", "--uses", "config.yml"]` and this will make flow not to hang anymore. But, if you use `Ctrl+C` to terminate the service, you will receive the following error indicating that the shutdown signal cannot be received, and I can see that the docker container is still running.
> 
> ![爱奇艺20230414213924](https://user-images.githubusercontent.com/52963371/232059426-f757c4ad-b4c7-4513-b7e3-93d5785d6918.png)
> 
> what "--no-capture-output" does (according to [conda's doc](https://docs.conda.io/projects/conda/en/latest/commands/run.html)) is simply allow stdout and stderr to pass. So, does this mean that the communication between the inside and the outside of a jina's executor container is done or partially done through stdout/stderr?

hey @JoanFM , I finally found a complete solution that can make the shutdown successful and gracefully. I've done a bit research on conda, and it looks like the reason we are getting the `Shutdown signal was not received for xx seconds` is that `docker.container.kill("SIGTERM")` cannot stop the container whose entrypoint is `conda run`, and it is because `conda run` cannot propagate the SIGTERM signal to its python subprocesses (see [here](https://github.com/conda/conda/issues/10351) and [here](https://github.com/conda/conda/pull/12404), a known issue of conda that hasn't been solved for quite some time)

My solution is therefore to replace `docker.container.kill("SIGTERM")` with `docker.container.stop()` in jina/orchestrate/pods/container.py. The latter also sends "SIGTERM" first but will send "SIGKILL" if there is a timeout, hence a more graceful shutdown IMHO.

However, right now I have to patch jina to make this work. Is it possible for jina to make this revision in the next version? It seems to me that it's quite simple to ensure downward compatibility but at the same time allow using conda successfully.

**Comment by JoanFM** [comment]
Hey @eugene-yh, this is a great finding. You can easily do a PR against Jina to do so, and we would be glad to review and integrate in the system

**Comment by JoanFM** [comment]
Would you like to add such feature?
