### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by SpacedDot** [jina-ai/jina#5818]
**Describe the bug**

1. Create a project: 
jina new hello-jina --type=deployment

2. run
jina deployment --uses deployment.yml

**error:**
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/jina/bin/jina", line 8, in <module>
    sys.exit(main())
  File "/home/user/miniconda3/envs/jina/lib/python3.8/site-packages/jina_cli/__init__.py", line 143, in main
    getattr(api, args.cli.replace('-', '_'))(args)
  File "/home/user/miniconda3/envs/jina/lib/python3.8/site-packages/jina_cli/api.py", line 18, in deployment
    dep = Deployment.load_config(args.uses)
  File "/home/user/miniconda3/envs/jina/lib/python3.8/site-packages/jina/jaml/__init__.py", line 774, in load_config
    no_tag_yml['with'].get('extra_search_paths') or []
AttributeError: 'list' object has no attribute 'get'

**Describe how you solve it**

---

**Environment**

**Screenshots**

![1682060626136](https://user-images.githubusercontent.com/90094434/233564857-89b96e04-9020-40bd-a67b-6c77b3651363.png)

**Comment by JoanFM** [comment]
Thank you very much for the issue report, I will look into the issue

**Comment by JoanFM** [comment]
The issue will be fixed in #5819

**Comment by SpacedDot** [comment]
Got it. I'll close this.

**Comment by yh0608** [comment]
![企业微信截图_96ce464d-beb4-4d75-851f-27f0b96fb557](https://user-images.githubusercontent.com/43535458/233590522-e18cc117-aa59-406e-8cc0-2f3ca33f2fa9.jpg)

**Comment by JoanFM** [comment]
The problem is that we have some flakyness in some tests, but nothing related to this

**Comment by auser** [comment]
I'm hitting this error too from a fresh install/deploy.

Has this been merged yet?

**Comment by JoanFM** [comment]
It will be released soon in the next release
