### ISSUE TITLE
How to Implement Single Machine Multi Process to Improve Concurrency

### ISSUE THREAD

**Issue by yuanjie-ai** [jina-ai/jina#5823]
How to Implement Single Machine Multi Process to Improve Concurrency？

f = Flow(port=12345).add(uses=FooExec, replicas=3).add(uses=BarExec, replicas=2)
<replicas>
don't work!!!

**Comment by JoanFM** [comment]
What do you mean it does not work? 

Doesn't this work?

```python
f = Flow(port=12345).add(uses=FooExec, replicas=3).add(uses=BarExec, replicas=2)
with f:
   f.block()
```

**Comment by yuanjie-ai** [comment]
> 

I use multiple processes to retrieve requests, and the total time is cumulative

**Comment by JoanFM** [comment]
what do you actually do in your code and how do you measure it does not work?

**Comment by JoanFM** [comment]
Can you please share more descriptive example?

**Comment by JoanFM** [comment]
Closing as no example is provided, feel free to reopen with more information
