### ISSUE TITLE
bug: windows grpcio-health-checking>=1.49.0

### ISSUE THREAD

**Issue by florian-hoenicke** [jina-ai/jina#5827]
I get this error: 
```
jina 3.15.1.dev14 depends on grpcio-health-checking>=1.49.0
```

But in the https://github.com/jina-ai/jina/blob/master/extra-requirements.txt
we can see it should be grpcio-health-checking>=1.46.0,<1.48.1:

How can this be explained? On mac, there is no issue

**Comment by JoanFM** [comment]
what are the steps you are using to reproduce?

**Comment by florian-hoenicke** [comment]
reproduce: happens when running gptdeploy on windows.
I fixed it now by setting os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'

**Comment by JoanFM** [comment]
this is not the correct way to fix this issue I believe. There must be something `weird` with `protocol-buffers` versions. This env var will degrade performance
