### ISSUE TITLE
rename `port_grpc`

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#585]
**Describe the feature**

`port_grpc` is used in REST Gateway as well, the name does not fit its purpose.

**Your proposal**

rename it to `port_expose`?

---

**Environment**

**Screenshots**

**Comment by fhaase2** [comment]
I also recognized this. Another solution would be to add an additional parameter e.g. `port_rest`. However, for user its probably better to have only one param.

**Comment by nan-wang** [comment]
When do we expect to deprecate `port_grpc`?
