### ISSUE TITLE
Jina's Client is extremely buggy and slow

### ISSUE THREAD

**Issue by Murugurugan** [jina-ai/jina#5856]
I've encountered a problem in my pipeline when I was trying to have some executors be executed at specific moments, like database writes and reads.. etc, but this meant that these executors can't go inside the Flow DAG pipeline, because I don't want them to be executed sequentially, but only when the stars align.. I need to be able to go back and forth in execution, etc. Basically I need a different type of network topology, something with vast freedom and connectivity, like mesh topology of microservices, at least the backend should work like this, frontend can stay the classic Flow.

There seems to be only 2 solutions for this. Either use Flow conditioning or multiple deployments (or multiple flows).

I quickly figured out flow conditioning is probably pretty useless for my use case and multiple deployments require multiple ports, therefore multiple clients as well. That wouldn't be such a problem with regular 3rd party HTTP requests.. if they actually worked. Well they didn't. After 100s of tests I realized where is the problem. Deployments need the flow to actually have exposed entrypoints, probably because they have no gateway. And something like this, won't work:

`dep = Deployment(protocol=['http'], port=[8081], uses="quick_test/config.yml", entrypoint="/test")`

Anyway, this is where I actually started to lose my mind. Not only that now I had to rethink the whole architecture and make the most logic client-side outside of flows and executors, but I also started to discover that Jina's native Client barely works.

I created a simple deployment like above with executor that only outputs simple text. Then I tested it with this code:

```
s = time.perf_counter()
c = Client(host="localhost", port=8081, protocol='http')
da = c.post('/test', DocumentArray.empty(1))
print(da.texts)
e = time.perf_counter()
print(e-s)
```
And what do I see? Correct result, but in 5 seconds, every single time. After getting furious for a moment I tried to change "localhost" to "127.0.0.1" and it did work actually lowering it to 250 ms. Probably just a bug, because Deployments are kinda a new thing if I understand correctly, anyway.. I needed to lower that latency..

---

So I did try to actually measure what's going on with this code:

```
c = Client(host='http://127.0.0.1:8081')
c.profiling()
```

.. which btw also didn't work everytime, sometimes I had to switch to this instead (for some magical reason):

```
c = Client(host='127.0.0.1:8081', protocol='http')
c.profiling()
```

..and sometimes even that didn't work, so I had to change the whole constellation so the stars can align, because it mostly works with gRPC only...   anyway..

---

20% of the time it gave me this error:

```
...
jina.excepts.BadClient: no such endpoint http://127.0.0.1:8081/post
```

40% of the time it gave me this error:

```
Traceback (most recent call last):
  File "e:\Muru\WORK\MAIN\SYSTEM\client_latency_test.py", line 20, in <module>
    c.profiling()
  File "E:\Muru\venv\Lib\site-packages\jina\clients\mixin.py", line 190, in profiling
    return _render_response_table(r[0], st, ed, show_table=show_table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Muru\venv\Lib\site-packages\jina\clients\mixin.py", line 159, in _render_response_table
    'Gateway-executors network', server_network, server_network / gateway_time
                                                 ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
ZeroDivisionError: division by zero
```

30% of the time it gave me this error:

```
Traceback (most recent call last):
  File "E:\Muru\WORK\main\SYSTEM\client_latency_test.py", line 19, in <module>
    c.profiling()
  File "E:\Muru\venv\Lib\site-packages\jina\clients\mixin.py", line 190, in profiling
    return _render_response_table(r[0], st, ed, show_table=show_table)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Muru\venv\Lib\site-packages\jina\clients\mixin.py", line 132, in _render_response_table
    route[0].end_time.ToMilliseconds() - route[0].start_time.ToMilliseconds()
    ~~~~~^^^
IndexError: list index out of range
```

And finally 10% of the time it gave me the actual answer like this:

```
Roundtrip  79ms  100% 
├──  Client-server network  78ms  99%
└──  Server  1ms  1%
    ├──  Gateway-executors network  1683664004186ms  168366400418600%
    └──  executor  -1683664004185ms  -168366400418500%

Time measured via time.perf_counter(): 104 ms.
```

This last test was when I tried to make it faster by using gRPC. I didn't manage it to go under 60 ms. And what I don't understand is how can it be this slow? If I understand this correctly, executors are basically communicating instantly in 1 ms using gRPC, but when I send the request from client, it takes so much time, is that normal?

I was confused, so I tested my own python gRPC server/client with normal protobufs and it takes just 2 ms to send and receive message. Why is Client.post so slow then? Even regular "3rd party" HTTP post request was way faster than this native one (that 1% of the time it actually worked) - it took about 30 ms.

---

**Environment**
- jina 3.15.2
- docarray 0.21.0
- jcloud 0.2.5
- jina-hubble-sdk 0.35.0
- jina-proto 0.1.17
- protobuf 4.22.1
- proto-backend upb
- grpcio 1.53.0
- pyyaml 6.0
- python 3.11.2
- platform Windows
- platform-release 10
- platform-version 10.0.25324
- architecture AMD64
- processor AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- uid 91762274940
- session-id 651d801a-eeb8-11ed-9b70-00155d75327c
- uptime 2023-05-10T00:25:24.972039
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Comment by JoanFM** [comment]
Hey @Murugurugan ,

Sorry for the experience, I will look into it ASAP.

Can you tell me what is the exact Deployment you are trying to connect to?

I am not sure why you are talking about GRPC while you talk about an HTTP Deployment. With an HTTP Deployment there is no component communicating via gRPC

**Comment by JoanFM** [comment]
My experiment:

I use this in `server.py`:

```python
import os

os.environ['JINA_LOG_LEVEL'] = 'DEBUG'

from jina import Executor, requests, Deployment


class TextExecutor(Executor):

    @requests
    def post(self, docs, **kwargs):
        for doc in docs:
            doc.text = 'test'


dep = Deployment(protocol='http', port=8081, uses=TextExecutor)

with dep:
    dep.block()
```

and on client side:

```python
import os
os.environ['JINA_LOG_LEVEL'] = 'DEBUG'

import time

from jina import Client, DocumentArray

s = time.perf_counter()
c = Client(host="localhost", port=8081, protocol='http')
da = c.post('/test', DocumentArray.empty(1))
print(da.texts)
e = time.perf_counter()
print(e-s)
```

I get all the time 0.07 as result

**Comment by JoanFM** [comment]
Can you run the following?

```python

import os
os.environ['JINA_LOG_LEVEL'] = 'DEBUG'

import time

from jina import Client, DocumentArray

s = time.perf_counter()
c = Client(host="localhost", port=8081, protocol='http')
da = c.post('/test', DocumentArray.empty(1))
print(da.texts)
e = time.perf_counter()
print(e-s)
for _ in range(100):
    s = time.perf_counter()
    da = c.post('/test', DocumentArray.empty(1))
    print(da.texts)
    e = time.perf_counter()
    print(e-s)
```

I would like to see if after the first one it works better

**Comment by JoanFM** [comment]
And what do you get with this?

```python
import os
os.environ['JINA_LOG_LEVEL'] = 'DEBUG'

import time

from jina import Client, DocumentArray

empty_da = DocumentArray.empty(1)
s = time.perf_counter()
c = Client(host="localhost", port=8081, protocol='http')
da = c.post('/test', empty_da)
print(da.texts)
e = time.perf_counter()
print(e-s)

for _ in range(100):
    s = time.perf_counter()
    da = c.post('/test', empty_da)
    print(da.texts)
    e = time.perf_counter()
    print(e-s)

import requests
s = time.perf_counter()

req = {
    "data": [{}],
    "parameters": {}
}
resp = requests.post(url='http://localhost:8081/default', json=req)

print(f' resp {resp.content}')
e = time.perf_counter()
print(e-s)

```

**Comment by JoanFM** [comment]
This is what I get in Linux:

```
['test']
0.10898248699959368
['test']
0.011769082004320808
['test']
0.011453041995991953
['test']
0.010627055002260022
['test']
0.01153672298823949
['test']
0.011217517996556126
['test']
0.011053108013584279
['test']
0.010612120007863268
['test']
0.011045614999602549
['test']
0.011519476989633404
['test']
0.010964082001009956
['test']
0.011012365997885354
['test']
0.011188687989488244
['test']
0.010541165000176989
['test']
0.010776438008178957
['test']
0.011449725992861204
['test']
0.01049561299441848
['test']
0.010651998003595509
['test']
0.011115158995380625
['test']
0.010833978012669832
['test']
0.010872364990063943
['test']
0.011018292992957868
['test']
0.010725624990300275
['test']
0.010813956992933527
['test']
0.011006718996213749
['test']
0.010714828997151926
['test']
0.010924026006250642
['test']
0.010838191010407172
['test']
0.00996307999594137
['test']
0.011684621989843436
['test']
0.011067020997870713
['test']
0.010588671008008532
['test']
0.011267406996921636
['test']
0.011012162009137683
['test']
0.010638407999067567
['test']
0.010643364003044553
['test']
0.01061262100120075
['test']
0.010618576998240314
['test']
0.01041026200982742
['test']
0.011185989002115093
['test']
0.010380391002399847
['test']
0.010836517001735047
['test']
0.01040787500096485
['test']
0.010493641995708458
['test']
0.010610106997773983
['test']
0.010898666005232371
['test']
0.010548381003900431
['test']
0.010603590999380685
['test']
0.01114439099910669
['test']
0.011120484006823972
['test']
0.010301164991687983
['test']
0.010246051009744406
['test']
0.01065213599940762
['test']
0.010105004999786615
['test']
0.01057562899950426
['test']
0.010389155009761453
['test']
0.010957641992717981
['test']
0.010622950998367742
['test']
0.010508103005122393
['test']
0.010567304998403415
['test']
0.010400104001746513
['test']
0.010988701003952883
['test']
0.010670301999198273
['test']
0.010218219002126716
['test']
0.010510945998248644
['test']
0.010379749001003802
['test']
0.009946860998752527
['test']
0.010221970995189622
['test']
0.010163227998418733
['test']
0.011409312995965593
['test']
0.01011558399477508
['test']
0.010344843991333619
['test']
0.010524141995119862
['test']
0.011508722003782168
['test']
0.011767099000280723
['test']
0.010998081008438021
['test']
0.011452699996880256
['test']
0.0114565149997361
['test']
0.010914037004113197
['test']
0.01109352101047989
['test']
0.010872405007830821
['test']
0.01106825600436423
['test']
0.011133032996440306
['test']
0.011137288995087147
['test']
0.011173883991432376
['test']
0.01030526300019119
['test']
0.010830034007085487
['test']
0.010500771008082666
['test']
0.010387678994447924
['test']
0.011549285001819953
['test']
0.010790582004119642
['test']
0.010534425004152581
['test']
0.010570655998890288
['test']
0.010589405006612651
['test']
0.010691502000554465
['test']
0.010578456000075676
['test']
0.010627451003529131
['test']
0.010252741994918324
['test']
0.010317854001186788
['test']
0.011181480003870092
['test']
0.010497372000827454
 resp b'{"data":[{"id":"c3bab1809667ac91e0d6f20fe50bad06","parent_id":null,"granularity":null,"adjacency":null,"blob":null,"tensor":null,"mime_type":null,"text":"test","weight":null,"uri":null,"tags":null,"offset":null,"location":null,"embedding":null,"modality":null,"evaluations":null,"scores":null,"chunks":null,"matches":null}],"parameters":{}}'
0.009073478999198414
```

The first difference can be explained by the fact that the client at the first run, it reads the OpenAPI to understand the models to send.

Then the rest is really comparable to the usage of `requests` client.

**Comment by JoanFM** [comment]
I think there must be some inner networking resolution inside your Windows machine I guess.

**Comment by JoanFM** [comment]
Also I see the results are comparable with simply using `requests`.

**Comment by JoanFM** [comment]
The usage of WSL may impact for sure.

Can I see what is the gRPC solution u are doing?

**Comment by JoanFM** [comment]
Also, can u tell me how to get these `communtcation_pb2` and so on? What is the protobuf? or the already created one?

**Comment by JoanFM** [comment]
can you try with `stream=False` in the `client.post` method?

**Comment by JoanFM** [comment]
I would suggest also you can run your experiment with `Jina's` own Protofile.

**Comment by JoanFM** [comment]
But I would name here things that I see that are different and could explain discrepancies:

- Proto differences: Jina deals with different proto objects that are more complex than the ones in the example.
- Streaming: Jina Client connects through a streaming service in grpc, which I am not 100% sure of the extra complexity or performance penalty.
- Pythonic interface: Jina communicates with DOcArrays which are deserialized and serialized from protobuf to allow Executor users deal with `Pythonic objects` instead of dealing directly with `protobuf` objects (which are hard to work with).

I believe the combination of 1 and 3 can explain most of the penalty.
