### ISSUE TITLE
demo project didn't install requirements.txt

### ISSUE THREAD

**Issue by zhangjunqiang** [jina-ai/jina#5868]
platform: apple mac os x86_64
install:  pip install jina

i had flow the demo guide: https://docs.jina.ai/get-started/create-app/

after "Add logic".
and then modify requirements.txt add line:
```python
torch
torchvision
```
and then exec : 
```bash
jina deployment --uses deployment.yml
```

![image](https://github.com/jina-ai/jina/assets/5388898/5b0f52f9-ab85-44b3-8ac4-9b576639d1ab)

**Comment by JoanFM** [comment]
You need to install the requirements yourself. Maybe is not clear in Documentation and needs clarification?

**Comment by zhangjunqiang** [comment]
> You need to install the requirements yourself. Maybe is not clear in Documentation and needs clarification?

yes. i thought it was installed automatically.

If i used docker-compose or k8s. Will it be installed automatically?
