### ISSUE TITLE
can not start a executor from mwu.yml

### ISSUE THREAD

**Issue by coolmian** [jina-ai/jina#588]
**Describe the bug**

在文档的描述中 https://docs.jina.ai/chapters/extend/mwu.html
使用了错误的文件名mwu.py，它与mwu.yml中的 py_modules参数的值“mwu_encoder.py”不匹配。
否则会报错：
   dummyEncoder@26419[C]:can not start a executor from mwu.yml
   dummyEncoder@26419[S]:terminated
   dummyEncoder@26415[C]:fail to start <class 'jina.peapods.pea.BasePea'> with name dummyEncoder

**Describe how you solve it**

解决办法就是修改mwu.yml中的参数或者修改文件名使其相匹配。

---

**Environment**

**Screenshots**

![image](https://user-images.githubusercontent.com/36444522/85942936-535f2f00-b95f-11ea-842c-46216caf2329.png)

**Comment by alexcg1** [comment]
感谢您的错误报告@coolmian-我们的团队将进行调查并尽快与您联系！
(Thanks for you bug report @coolmian - our team will look into it and get back to you shortly!)

**Comment by hanxiao** [comment]
I believe OP already points out the solution. Could you @coolmian please make a pull request? Greatly appreciated!

**Comment by coolmian** [comment]
> I believe OP already points out the solution. Could you @coolmian please make a pull request? Greatly appreciated!


Sure, I've read it CONTRIBUTING.md.
Should I operate in this  (https://github.com/jina-ai/docs.git)   repository?

**Comment by hanxiao** [comment]
No, the repo `docs` is built and auto updated on every CD.

You change the source of the docs directly from here: https://github.com/jina-ai/jina/tree/master/docs

**Comment by coolmian** [comment]
> 否，`docs`在每张CD上都构建并自动更新了仓库。
> 
> 您可以直接从此处更改文档的来源：[https](https://github.com/jina-ai/jina/tree/master/docs) : [//github.com/jina-ai/jina/tree/master/docs](https://github.com/jina-ai/jina/tree/master/docs)

Thank you for your explanation. I have sent a pull request

**Comment by coolmian** [comment]
> No, the repo `docs` is built and auto updated on every CD.
> 
> You change the source of the docs directly from here: https://github.com/jina-ai/jina/tree/master/docs

Thank you for your explanation. I have sent a pull request
