### ISSUE TITLE
grpc远程调用中，传递的参数为Docarray类型时，客户端调用出现：Message must be initialized with a dict，请教一下是哪里有问题吗？

### ISSUE THREAD

**Issue by sylon14** [jina-ai/jina#5881]
debug时返回的数据如下：
![85b56c2ff21c5fc7eb609f826ad4cf6](https://github.com/jina-ai/jina/assets/42056519/cbc3a51c-ed91-4cf3-bf43-6b66354f45ea)

客户端调用时出现以下问题
：
![c6903555e43e67775b14ea4998dd2fa](https://github.com/jina-ai/jina/assets/42056519/296177f9-67d2-4d92-9e4a-9ddecb44abdb)

我的proto配置是这样的：
![d8ed79eb2b3f3c4575a571753e94c7e](https://github.com/jina-ai/jina/assets/42056519/ab2de079-df89-4a06-9984-efdc21af40d7)

服务端代码：
![c8a3117839f64538ee5a7c4bc8903b1](https://github.com/jina-ai/jina/assets/42056519/36b63da4-b0c0-48b5-afdc-060001d08d40)

客户端代码：
![dd2c160864473115d13123734250f66](https://github.com/jina-ai/jina/assets/42056519/059f3ddf-7b57-452e-82eb-e52b4eae1ef1)

所以想请教一下大佬，这是pb文件配置有问题还是代码有什么问题吗？

**Comment by JoanFM** [comment]
For what I see here, the problem u have is when working with `MyResponse`. I do not think the response can be constructed with such initialization.

May I ask what you are trying to achieve?

**Comment by sylon14** [comment]
@JoanFM 
I want to make a remote call through grpc, and the returned parameter is data of type docarray. I have tried to return data of type string, which can be encapsulated like this.

**Comment by sylon14** [comment]
@JoanFM 
I want to make a remote call through grpc, and the returned parameter is data of type docarray. I have tried to return data of type string, which can be encapsulated like this.
![image](https://github.com/jina-ai/jina/assets/42056519/38cefe75-194f-4133-a449-e2dab32779c4)

**Comment by JoanFM** [comment]
what is result in both cases?

**Comment by JoanFM** [comment]
also, can u explain in detail what you do in your code? I see DocumentArrayProto is empty in ur case? What do u do to make sure it has the right info?

Also, please is better to copy paste the code and not send screenshots so that it is easy for the team to reproduce.

**Comment by sylon14** [comment]
@JoanFM 
Thank you for your help, this problem has been solved now, I looked for the documentation of jina docarray, and finally I modified the proto file, serialized the docarray in the list into bytes, and then deserialized it on the client side.

**Comment by JoanFM** [comment]
Thanks, 

what is the use case you have in mind? and why do not use Jina for it, since Jina uses docarray and grpc to communicate?
