### ISSUE TITLE
Are the render results of Swagger UI in v3.16.0 intended?

### ISSUE THREAD

**Issue by MarvinChung** [jina-ai/jina#5886]
**Describe your proposal/problem**

I want to use the new docarray feature in Jina v3.16.0 to make my swagger UI results look more intuitively. I want to generate an embedding endpoint with the protocal same as OpenAI(Fig 1). I follow the code in v3.16.0 release document (https://github.com/jina-ai/jina/releases/tag/v3.16.0) to generate the swagger UI, the schema of swagger UI adds InputDoc, InputDoc, bar_input_model and bar_output_model (Fig 2). However, the InputDoc is contained in the bar_input_model (Fig. 3) . I would like to have the input schema to be InputDoc instead of bar_input_model, so I could implement it as same as the OpenAI protocal. Also, the example does not match the schema, it only contains data and parameters (Fig. 4). There are many advantages of following the OpenAI API protocal since there are a lot of projects (Langchian) supporting it. I would like to ask for an example of building it with OpenAI API protocal if it is possible. Thanks for you reading, I am new to Jina and looking forward to learn it more !
---

**Environment**

- jina 3.16.0
- docarray 0.30.0
- jcloud 0.2.8
- jina-hubble-sdk 0.36.0
- jina-proto 0.1.27
- protobuf 4.23.0
- proto-backend upb
- grpcio 1.47.5
- pyyaml 6.0
- python 3.9.16
- platform Linux
- platform-release 5.4.0-148-generic
- platform-version #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023
- architecture x86_64
- processor x86_64
- uid 65686581038221
- session-id a6553d79-f7b6-11ed-a75c-3bbdd9544c8d
- uptime 2023-05-21T17:05:36.240652
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES (unset)
* JINA_GRPC_SEND_BYTES (unset)
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Screenshots**

Fig1:
![image](https://github.com/jina-ai/jina/assets/22186310/12087acc-f33b-4752-8792-756b26785a5f)
Fig2:
![image](https://github.com/jina-ai/jina/assets/22186310/ca616890-7c9a-433c-86e2-86031db7a062)
Fig3:
![image](https://github.com/jina-ai/jina/assets/22186310/9f8101aa-a180-498b-9c39-884e96301b40)
Fig4:
![image](https://github.com/jina-ai/jina/assets/22186310/d004ffb6-1c22-49a4-b128-e674306f67d7)

**Comment by JoanFM** [comment]
Hello @MarvinChung,

I am not sure I understand fully the issue. Let me explain a little bit.

Jina is bulit with Executor concept at its center, which expose methods when decorated with @requests, that receive 2 parameters (DocList and parameters dictionary).

Jina exposes these methods with a `Deployment` class  so that clients can connect to it via HTTP and gRPC protocol.

To expose them as HTTP protocol, you need a schema that contains data and parameters, where data is DocList and parameters ara optional parameters for your endpoint. This is why in the SwaggerUI you see these bar_input_model and bar_output_model, along with all the inner Docs.

I am not sure what you say about OpenAI specification, but I do not think is specifically possiblr, but I do not see a problem since communicating with the Jina service seems easy.

About the example being just empty data, it is true it may be a problem, I will look into how we can make it improve.

**Comment by girishc13** [comment]
Jina HTTP schema cannot be 100% compatible with OPEN API specification because the underlying protocols are still handled by docarray which is gRPC oriented design. The internal protocol in the Flow (Gateway and Executors) is also gRPC which is why Jina cannot fully conform to the OPEN API schema. Hope this clarifies some design questions.

**Comment by MarvinChung** [comment]
Thank you for your prompt response. I have managed to find a solution to achieve my objective, but I would like to reiterate my question to ensure clarity.

My objective is to generate a request body that includes only the "model," "input," and "user" parameters, resembling the request body structure of OpenAI's embedding API. I accomplish this by utilizing the custom gateway with FastAPI. To provide you with a reproducible example, here is the relevant code snippet:
```
from jina import DocumentArray, Executor, requests, dynamic_batching, Flow
from sentence_transformers import SentenceTransformer
from docarray import DocumentArray, Document
from typing import Generator, Optional, Union, Dict, List, Any
from pydantic import BaseModel, Field
from jina.serve.runtimes.gateway.http.fastapi import FastAPIBaseGateway
from fastapi import FastAPI
import torch

class UsageInfo(BaseModel):
    prompt_tokens: int = 0
    total_tokens: int = 0
    completion_tokens: Optional[int] = 0

class EmbeddingsRequest(BaseModel):
    model: Optional[str] = None
    input: Union[str, List[Any]]
    user: Optional[str] = None

class EmbeddingsResponse(BaseModel):
    object: str = "list"
    data: List[Dict[str, Any]]
    model: str
    usage: UsageInfo


class sBert(Executor):
    """SBert embeds text into 384-dim vectors using all-MiniLM-L6-v2"""
    def __init__(self, device: str = 'cpu', *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.device = device
        self.model = SentenceTransformer('all-MiniLM-L6-v2', device=device)
        self.model.to(device)  # Move the model to device

    @requests(on='/embeddings')
    @dynamic_batching(preferred_batch_size=4, timeout=200)
    def embeddings(self, docs: DocumentArray, **kwargs):
        
        #"""Add text-based embeddings to all documents"""
        with torch.inference_mode():
            embeddings = self.model.encode(docs.texts)
        docs.embeddings = embeddings


class MyGateway(FastAPIBaseGateway):
    @property
    def app(self):
        app = FastAPI()

        @app.post("/embeddings")
        async def create_embeddings(request: EmbeddingsRequest):
            token_num = 0
            "Creates embeddings for the text"""
            results = []
            errors = []

            if isinstance(request.input, str):
                request.input = [request.input]

            async for docs, error in self.streamer.stream(
                docs=DocumentArray([Document(text=text_input) for text_input in request.input]),
                exec_endpoint='/embeddings',
            ):
                if error:
                    errors.append(error)
                else:
                    for i, doc in enumerate(docs):
                        data = {
                            "object": "embedding",
                            "embedding": doc.embedding.tolist(),
                            "index": i,
                        }
                        results.append(data)

            token_num += sum([len(text_input) for text_input in request.input])
            return EmbeddingsResponse(
                        data=results,
                        model=request.model,
                        usage=UsageInfo(
                        prompt_tokens=token_num,
                        total_tokens=token_num,
                        completion_tokens=None,
                        ),
                    ).dict(exclude_none=True)


        return app


with Flow().config_gateway(uses=MyGateway, port=57012, protocol='http').add(uses=sBert, name='sBert') as flow:
    flow.block()
```
The render results of swagger UI is
![image](https://github.com/jina-ai/jina/assets/22186310/82440b48-b4f0-49ba-8218-569bc456cdc8)
which has the same request body as OpenAI embeddings
![image](https://github.com/jina-ai/jina/assets/22186310/589bee8c-f7d1-48da-a9fb-dccc0a38b153)
and by filling the request body
```
{
  "model": "sBert",
  "input": "hello",
  "user": "User"
}
```
I am able to obtain a response that matches the response from OpenAI's embedding. Currently, I am using docarray < 3.0.0, but I am curious if it is possible to modify the BaseModel from my code for docarray >= 3.0.0. Here is the code snippet in question:
```
class EmbeddingsRequest(BaseModel):
    model: Optional[str] = None
    input: Union[str, List[Any]]
    user: Optional[str] = None


class EmbeddingsResponse(BaseModel):
    object: str = "list"
    data: List[Dict[str, Any]]
    model: str
    usage: UsageInfo
```
I am wondering if it would be feasible to change BaseModel to BaseDoc, like so:
```
class EmbeddingsRequest(BaseDoc):
    model: Optional[str] = None
    input: Union[str, List[Any]]
    user: Optional[str] = None


class EmbeddingsResponse(BaseDoc):
    object: str = "list"
    data: List[Dict[str, Any]]
    model: str
    usage: UsageInfo
```
Ideally, I would like to achieve this without using a custom OpenAPI gateway. If there is an alternative method to accomplish this, I would greatly appreciate your insights. I understand if this request is not compatible with Jina's design. Thank you for taking the time to read and consider my question.

By the way, I would like to inquire whether my code utilizes dynamic batching. I am uncertain if my custom gateway correctly employs the dynamic batching mechanism when passing the document to the sBert executor.

**Comment by JoanFM** [comment]
Hello @MarvinChung ,

You could use `BaseDoc` instead of BaseDoc with some changes (although Jina is not yet fully compatible with DocArray v2).

However, it will not be possible to match the exact OpenAI specification I believe. 

As I say, the HTTP server we aim to map the expected inputs that can be handled by Executor, this is why we need `data` and `parameters`. 

So in summary, I would say that you are making proper use of Jina, whenever you have some specific API needs, we allow you yo develop your own CustomGateway which is what you are doing properly.
