### ISSUE TITLE
License problem!

### ISSUE THREAD

**Issue by wqh17101** [jina-ai/jina#5890]
You use a GPL software aiostream as the dependency.

Watch out that the GPL is contagious. 

Which will cause big problem to a  [Apache-2.0 license](https://github.com/jina-ai/jina/blob/master/LICENSE) project that it will make your project GPL too.

The only way to use GPL  software without being infected is to use the GPL software with process isolation.

**Comment by JoanFM** [comment]
Hey @wqh17101 ,

thanks for reporting this issue, I will take a look at it ASAP

**Comment by JoanFM** [comment]
Hello @wqh17101 ,

The dependency has been removed, thanks a lot for reporting the issue

**Comment by wqh17101** [comment]
It's my pleasure. @JoanFM 
Please release a new version ASAP.
