### ISSUE TITLE
Pea with empty yaml path raises errors

### ISSUE THREAD

**Issue by fhaase2** [jina-ai/jina#591]
**Describe your problem**

When i create a pea with not setting yaml path:
```
args = set_pea_parser().parse_args([ '--runtime', 'thread', '--yaml-path', ''])
            
with BasePea(args):
    pass
```

right now it throws first an warning 
`this BasePea has no executor attached, you may want to double-check if it is a mistake or on purpose (using this BasePea as router/map-reduce)`

and then it fails for the control request, because in this code line executor is not set at all:
https://github.com/jina-ai/jina/blob/576001536ced8ae411e9c7a29873cf989563ddae/jina/peapods/pea.py#L161

I am not sure about the desired behavior here. I think it should be not possible at all to not provide a yaml path, because `BaseExecutor` is needed for control request handling.

**Comment by fhaase2** [comment]
Links to https://github.com/jina-ai/jina/issues/583

**Comment by hanxiao** [comment]
`yaml_path` is by default set to `BaseExecutor` already, as https://github.com/jina-ai/jina/blob/master/jina/main/parser.py#L189

Your usage of BasePea is wrong. The correct usage should be,

```python
args = set_pea_parser().parse_args([ '--runtime', 'thread'])
            
with BasePea(args):
    pass
```

In your code, you explicit set `--yaml-path` to ``, i.e. overriding the default with ``. In this case, you can not expect it work.

Another way to check it is run `jina pea` in CLI.
