### ISSUE TITLE
OSError: can not find an available port in 

### ISSUE THREAD

**Issue by yuanjie-ai** [jina-ai/jina#5967]
Name: jina
Version: 3.19.0
Summary: Multimodal AI services & pipelines with cloud-native stack: gRPC, Kubernetes, Docker, OpenTelemetry, Prometheus, Jaeger, etc.
Home-page: https://github.com/jina-ai/jina/
Author: Jina AI

Name: docarray
Version: 0.35.0
Summary: The data structure for multimodal data
Home-page: https://docs.docarray.org/
Author: DocArray
Author-email: 
License: Apache 2.0

![image](https://github.com/jina-ai/jina/assets/20265321/888b743a-7d33-48b1-b5f4-0d183fdf820c)
---

**Comment by yuanjie-ai** [comment]
![image](https://github.com/jina-ai/jina/assets/20265321/68681d20-0d24-4c0a-bfca-1c03f62ec279)

**Comment by yuanjie-ai** [comment]
The new version of docarray will have problems

**Comment by JoanFM** [comment]
Hello @yuanjie-ai, what happens if u assign urself a port?

```python
Deployment(port=8080, ...)
```

Does this work?

**Comment by JoanFM** [comment]
Also, can you show what is the result of simply doing.

```python
with Deployment():
    pass
```

As per what I see right now there is some issue with the ports binding, somehow Jina is not being able to bind to any of these ports. Have u chefcked ur ports and permission configurations?

**Comment by yuanjie-ai** [comment]
Mac os





发自我的iPhone


------------------ Original ------------------
From: Joan Fontanals ***@***.***&gt;
Date: Tue,Jul 18,2023 5:49 AM
To: jina-ai/jina ***@***.***&gt;
Cc: Betterme ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [jina-ai/jina] OSError: can not find an available port in  (Issue#5967)





 
Also, can you show what is the result of simply doing.
 with Deployment():     pass
 
As per what I see right now there is some issue with the ports binding, somehow Jina is not being able to bind to any of these ports. Have u chefcked ur ports and permission configurations?

**Comment by JoanFM** [comment]
have u tried any of these approaches?

**Comment by yuanjie-ai** [comment]
> Also, can you show what is the result of simply doing.
> 
> ```python
> with Deployment():
>     pass
> ```
> 
> As per what I see right now there is some issue with the ports binding, somehow Jina is not being able to bind to any of these ports. Have u chefcked ur ports and permission configurations?

![image](https://github.com/jina-ai/jina/assets/20265321/8910f2a4-21fe-4145-949c-f9b839da9ab7)

**Comment by JoanFM** [comment]
Is it possible for u to join our discord server with this invite? https://discord.gg/9aHdwUyC

Maybe we can set some paring to debug together

**Comment by JoanFM** [comment]
Also, what is ur Python version?

**Comment by yuanjie-ai** [comment]
3.8



发自我的iPhone


------------------ Original ------------------
From: Joan Fontanals ***@***.***&gt;
Date: Tue,Jul 18,2023 6:17 PM
To: jina-ai/jina ***@***.***&gt;
Cc: Betterme ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [jina-ai/jina] OSError: can not find an available port in  (Issue#5967)

**Comment by JoanFM** [comment]
> Hello @yuanjie-ai, what happens if u assign urself a port?
> 
> ```python
> Deployment(port=8080, ...)
> ```
> 
> Does this work?

can u share the output and logs of running this with `JINA_LOG_LEVEL=DEBUG`

**Comment by JoanFM** [comment]
What do u get running this code?

```python
import socket
import os
import random

unassigned_ports = []
DEFAULT_MIN_PORT = 49153
MAX_PORT = 65535


def reset_ports():
    def _get_unassigned_ports():
        # if we are running out of ports, lower default minimum port
        min_port = int(
            os.environ.get('JINA_RANDOM_PORT_MIN', str(DEFAULT_MIN_PORT))
        )
        max_port = int(os.environ.get('JINA_RANDOM_PORT_MAX', str(MAX_PORT)))
        return set(range(min_port, max_port + 1))

    unassigned_ports.clear()
    unassigned_ports.extend(_get_unassigned_ports())
    random.shuffle(unassigned_ports)


def _check_bind(port):
    with socket.socket() as s:
        try:
            s.bind(('', port))
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            return port
        except OSError as exc:
            print(f'OSError Exception to skip: {exc}. Try next port')
            return None


for idx, _port in enumerate(unassigned_ports):
    if _check_bind(_port) is not None:
        break
raise OSError(
    f'can not find an available port in {len(unassigned_ports)} unassigned ports, assigned already {len(assigned_ports)} ports'
)
```

**Comment by yuanjie-ai** [comment]
> What do u get running this code?
> 
> ```python
> import socket
> import os
> import random
> 
> unassigned_ports = []
> DEFAULT_MIN_PORT = 49153
> MAX_PORT = 65535
> 
> 
> def reset_ports():
>     def _get_unassigned_ports():
>         # if we are running out of ports, lower default minimum port
>         min_port = int(
>             os.environ.get('JINA_RANDOM_PORT_MIN', str(DEFAULT_MIN_PORT))
>         )
>         max_port = int(os.environ.get('JINA_RANDOM_PORT_MAX', str(MAX_PORT)))
>         return set(range(min_port, max_port + 1))
> 
>     unassigned_ports.clear()
>     unassigned_ports.extend(_get_unassigned_ports())
>     random.shuffle(unassigned_ports)
> 
> 
> def _check_bind(port):
>     with socket.socket() as s:
>         try:
>             s.bind(('', port))
>             s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>             return port
>         except OSError as exc:
>             print(f'OSError Exception to skip: {exc}. Try next port')
>             return None
> 
> 
> for idx, _port in enumerate(unassigned_ports):
>     if _check_bind(_port) is not None:
>         break
> raise OSError(
>     f'can not find an available port in {len(unassigned_ports)} unassigned ports, assigned already {len(assigned_ports)} ports'
> )
> ```

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0fab86fdc95d>", line 1, in <module>
    runfile('/Users/betterme/PycharmProjects/AI/MeUtils/meutils/serving/jina/__demo/test.py', wdir='/Users/betterme/PycharmProjects/AI/MeUtils/meutils/serving/jina/__demo')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/betterme/PycharmProjects/AI/MeUtils/meutils/serving/jina/__demo/test.py", line 49, in <module>
    raise OSError(
OSError: can not find an available port in 0 unassigned ports, assigned already 0 ports
```

**Comment by JoanFM** [comment]
Sorry, I have edited the code, can you run it again?

**Comment by yuanjie-ai** [comment]
> Sorry, I have edited the code, can you run it again?

OSError: can not find an available port in 16383 unassigned ports, assigned already 16383 ports

**Comment by JoanFM** [comment]
Do you have prints like this?

```OSError Exception to skip```?

**Comment by deepankarm** [comment]
@yuanjie-ai does assigning ports with the default http server work for you?

```bash
python -m http.server <port>   # defaults to 8000 if port is not passed
```

**Comment by JoanFM** [comment]
Hello @yuanjie-ai , did you manage to take a look at @deepankarm comment?
