### ISSUE TITLE
add spectrogram based encoder for audio

### ISSUE THREAD

**Issue by anish2197** [jina-ai/jina#597]
**Describe the feature**
A CNN encoder which extracts features from images of spectrograms (spectrograms usually give a more complete representation for non-speech sounds as compared to mel-features). 

**Your proposal**
Use the scipy.signal.spectrogram to generate the image of spectrogram and use a pre-trained Keras/Pytorch CNN to extract the features.

Is it a good idea to spend time implementing this?

**Comment by alexcg1** [comment]
Hey Anish, thanks for the issue submission. The team'll look into it and get back to you soon. Extracting features from images of spectograms sounds pretty kick-ass to me :smile:

**Comment by JoanFM** [comment]
Hey @anish2197 

The idea sounds really interesting, 
I think it would make a lot of sense to add it as a hub image at jina-hub.

You can see examples and a guide on how to create them a thttps://github.com/jina-ai/jina-hub

**Comment by anish2197** [comment]
Thanks Joan. I'll look into the guide and try to implement this on jina-hub.
