### ISSUE TITLE
Message Queue for Flow pipeline

### ISSUE THREAD

**Issue by sansmoraxz** [jina-ai/jina#5982]
**Describe your proposal/problem**

This is mostly in terms of Kubernetes but may work with Docker too.

Imagine an `Flow` made up of a bunch of `Executor` (them having stateless replicas). Let's say we want to implement autoscaling to save costs or scale out on increased demand. The currently supported messaging protocols are either not compatible with autoscaling (GRPC) or very difficult and expensive to implement (WS or HTTP).

Message queues give us the freedom to monitor the state of the flow far more easily, and additionally gives more flexibility in terms of scaling (automatic 0 scaling when not in use and release for example the A100 node when not in use).

**Comment by sansmoraxz** [comment]
> 🤔 this autoscaling is directly doable with jina, e.g. https://docs.jina.ai/concepts/jcloud/configuration/#autoscaling-with-jinaai-serverless

This seems to be specific to JCloud unless I am reading it wrong.

Also the format requires the image to be hosted in Jina which might introduce a whole lot of NAT related costs.

**Comment by JoanFM** [comment]
Hey @sansmoraxz,

Thanks for the proposal, we will consider this but be aware that we may not have a lot of resources to implement this at the moment.

**Comment by JoanFM** [comment]
Also, could you share some info as per why it is easier to implement autoscaling with message queues than for this direct messaging protocols?

**Comment by JoanFM** [comment]
Hello @sansmoraxz ,

This sounds like a good idea, we are using this in our cloud service. 

We are currently discussing the best way to enable the community to use our solution or part of it in their Kubernetes cluster.

Anyway, with the `to_kubernetes_yaml` you can add the necessary editions to adapt to KNative.

Thanks for the suggestion.
