### ISSUE TITLE
Hi，guys ,we need scala jina api  

### ISSUE THREAD

**Issue by mullerhai** [jina-ai/jina#6031]
Hi, jina is very popular, we have  large model on spark Estimator, so  want to try jina,could we develop jina scala api

**Comment by JoanFM** [comment]
Hey @mullerhai,

What exactly do u mean by an API? a way to start Deployments and Flows from Scala, or a client in Scala to connect to a Jina service?

**Comment by JoanFM** [comment]
Hello @mullerhai ,

may I understand what is the usecase you are going after? Right now Flows and Deployments are used to instantiate Python based services. So I do not see how much useful it can be to have this API in Scala. How would you expect to use it?
