### ISSUE TITLE
ERROR: Cannot install jina because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by kirandeol** [jina-ai/jina#6039]
When trying to install clip_server, I am getting this error with the jina package. The error showed up a few hours ago (was fine yesterday on September 4).

pip install jina
ERROR: Cannot install jina because these package versions have conflicting dependencies.

The conflict is caused by:
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.40b0 depends on opentelemetry-instrumentation==0.40b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.39b0 depends on opentelemetry-instrumentation==0.39b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.38b0 depends on opentelemetry-instrumentation==0.38b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.37b0 depends on opentelemetry-instrumentation==0.37b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.36b0 depends on opentelemetry-instrumentation==0.36b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.35b0 depends on opentelemetry-instrumentation==0.35b0
    opentelemetry-instrumentation-aiohttp-client 0.33b0 depends on opentelemetry-instrumentation==0.33b0
    opentelemetry-instrumentation-fastapi 0.34b0 depends on opentelemetry-instrumentation==0.34b0

**Comment by k1dave6412** [comment]
check the issue from langflow
opentelemetry-sdk = ">=1.14.0,<1.20.0"

https://github.com/logspace-ai/langflow/issues/866

**Comment by JoanFM** [comment]
Hey @kirandeol ,

We are going to release a patch today with the fix for this. Thanks for reporting

**Comment by JoanFM** [comment]
Closed by #6037

**Comment by JoanFM** [comment]
Patch 3.20.2 should have fixed it

**Comment by kirandeol** [comment]
Working now, thanks so much!
