### ISSUE TITLE
A type check before appending

### ISSUE THREAD

**Issue by ai-naymul** [jina-ai/jina#6045]
**Describe your proposal/problem**

Should we make a type check in the push function on the `request` parameter before appending it to the `_requests` list? @JoanFM 
---

Reference: https://github.com/jina-ai/jina/blob/master/jina/serve/runtimes/worker/batch_queue.py

**Environment**

- jina 3.20.4
- docarray 0.38.0
- jcloud 0.2.16
- jina-hubble-sdk 0.39.0
- jina-proto 0.1.27
- protobuf 4.24.3
- proto-backend upb
- grpcio 1.58.0
- pyyaml 6.0.1
- python 3.11.4
- platform Windows
- platform-release 10
- platform-version 10.0.19045
- architecture AMD64
- 
**Screenshots**

![kutta](https://github.com/jina-ai/jina/assets/68547750/1f7c0e27-d5ad-40c1-b570-8bac4fabe589)

Like that:

![mutta](https://github.com/jina-ai/jina/assets/68547750/c4137ba9-da74-474d-ab60-e455d4b8500e)

**Comment by JoanFM** [comment]
There is no need since noone has yet raised an issue because of this. If you have seen any case where this is a problem, please report and share a way to reproduce.

Thanks for the suggestion

**Comment by ai-naymul** [comment]
> There is no need since noone has yet raised an issue because of this. If you have seen any case where this is a problem, please report and share a way to reproduce.
> 
> Thanks for the suggestion

Got it

**Comment by ai-naymul** [comment]
Should we add a try except block in the `handle_request` function:
![lokka](https://github.com/jina-ai/jina/assets/68547750/90c74c44-37b3-481f-af74-1702b150fa69)

Like that:
![fokka](https://github.com/jina-ai/jina/assets/68547750/716f4264-e80d-4ccd-9a46-31f470772124)

And should we make the shutdown function into two part one for the resource:
![jokka](https://github.com/jina-ai/jina/assets/68547750/8be87775-ff8c-489f-85d1-d329fb68727a)

Like that:
![eokka](https://github.com/jina-ai/jina/assets/68547750/d452b0f8-30df-4a3b-8b2d-c429857ee7c8)


Code reference: [jina/serve/runtimes/servers/load_balancer.py](https://github.com/jina-ai/jina/blob/master/jina/serve/runtimes/servers/load_balancer.py)

**Comment by ai-naymul** [comment]
> Should we add a try except block in the `handle_request` function: ![lokka](https://user-images.githubusercontent.com/68547750/266846005-90c74c44-37b3-481f-af74-1702b150fa69.png)
> 
> Like that: ![fokka](https://user-images.githubusercontent.com/68547750/266846049-716f4264-e80d-4ccd-9a46-31f470772124.png)
> 
> And should we make the shutdown function into two part one for the resource: ![jokka](https://user-images.githubusercontent.com/68547750/266846143-8be87775-ff8c-489f-85d1-d329fb68727a.png)
> 
> Like that: ![eokka](https://user-images.githubusercontent.com/68547750/266846155-d452b0f8-30df-4a3b-8b2d-c429857ee7c8.png)
> 
> Code reference: [jina/serve/runtimes/servers/load_balancer.py](https://github.com/jina-ai/jina/blob/master/jina/serve/runtimes/servers/load_balancer.py)

@JoanFM

**Comment by JoanFM** [comment]
There is no need until any issue appears because of that.
