### ISSUE TITLE
Bi-directional Streaming

### ISSUE THREAD

**Issue by NarekA** [jina-ai/jina#6060]
**Describe the feature**

As I understand it, the current API only supports response streaming. Is there a way to support [bi-directional streaming](https://grpc.io/docs/languages/python/basics/#bidirectional-streaming-rpc)? I imagine it would look like the current streaming API, except the input would be a generator. This would be useful for applications such as chat-bots.

**Your proposal**

```python
# then define the Executor
class MyExecutor(Executor):

    @requests(on='/hello')
    async def task(self, docs: Generator[MyDocument], **kwargs) -> MyDocument:
        for doc in docs:
            yield MyDocument(text=f'{doc.text} output')
```

**Comment by NarekA** [comment]
@JoanFM 2 questions:

1. Is this true for the `stream_doc` method only or the `post` method too?
2. In the example above, the server can save context. Example:
```python
# then define the Executor
class MyExecutor(Executor):

    @requests(on='/hello')
    async def task(self, docs: Generator[MyDocument], **kwargs) -> MyDocument:
        conversation = ""
        for doc in docs:
            conversation += f"\n\n{doc.text}"
            yield MyDocument(text=conversation)
```

Is there a way to do that in the current API? Maybe using executor state?

**Comment by NarekA** [comment]
I'm reading through the code, and as I understand it, all endpoints can be streaming if `GRPC` or `websocket` is enabled. Is this correct. The docs imply that streaming endpoints need to have a single document as the input.

**Comment by JoanFM** [comment]
okey ur point is that u need to keep the context in the stack making sure it arrives at the same replica?

**Comment by NarekA** [comment]
Yes, similar to the example in the GRPC docs for bi-directional streaming:
```python
def RouteChat(self, request_iterator, context):
    prev_notes = []
    for new_note in request_iterator:
        for prev_note in prev_notes:
            if prev_note.location == new_note.location:
                yield prev_note
        prev_notes.append(new_note)
```

**Comment by JoanFM** [comment]
I think with GRPC it may be possible, but I am not sure if in HTTP there is a way to get an stream as input.

**Comment by JoanFM** [comment]
otherwise to get this state IN, you may want to do a nice usage of Stateful Executor but this could feel overkill.

**Comment by NarekA** [comment]
We could have the endpoint be a normal endpoint (same as if the generator was a `DocList`) when the server is http and websocket. 

Also, it would be useful to know how to stream bi-directionally when using the current configuration (IE, does it only work with streaming endpoints, or do normal endpoints keep the connection open too?)

**Comment by JoanFM** [comment]
I will look at it in more detail and come back
