### ISSUE TITLE
How to set GET method?

### ISSUE THREAD

**Issue by xuhaoguang** [jina-ai/jina#6073]
![image](https://github.com/jina-ai/jina/assets/14950705/8a276b4c-8078-42ea-afa6-a1a3e7c3db6b)
This is default POST method, But how can I set it's a GET method?

**Comment by JoanFM** [comment]
Hey @xuhaoguang ,

You do not need to set it, Jina detects that there is a generator being returned and because of that exposes a GET endpoint when served via HTTP.

**Comment by xuhaoguang** [comment]
ehh, But how can I use   _curl "localhost:8080/hc"_    to health_check method, but when I test, jina say I should send a json post data.

**Comment by xuhaoguang** [comment]
![image](https://github.com/jina-ai/jina/assets/14950705/1204e4ec-e982-4d47-bfed-66b99ecaa7d2)

**Comment by JoanFM** [comment]
how are u defining this hc endpoint?

**Comment by xuhaoguang** [comment]
![image](https://github.com/jina-ai/jina/assets/14950705/eddc1a2b-3b41-4990-803b-88d78028fb4e)

**Comment by that-rahul-guy** [comment]
@xuhaoguang Did you find any workaround?
I'm struggling with same.

**Comment by JoanFM** [comment]
@that-rahul-guy what are you trying to do?

**Comment by that-rahul-guy** [comment]
Hi @JoanFM 
I am currently exploring jina as a framework to serve my LangChain Agent-tool architecture application.
As for the GET method I was trying a similar thing what @xuhaoguang shared.

**Comment by reshma045** [comment]
Hey @xuhaoguang, which folder is that file in?
