### ISSUE TITLE
Release Note (3.22.2)

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#6088]
## Release Note (`3.22.2`)

> Release time: 2023-10-20 14:42:15

This release contains 1 bug fix and 5 documentation improvements.

### Fix check graph compatibility nested types (#6085)

A bug was found that prevented Flows from starting when they had Executors with different but compatible schemas. This is now fixed.

## 📗 Documentation Improvements

- Add Jina deployment docs (#6079)
- Fix typos inside docs/cloud-nativeness (#6080)
- Fix typos inside docs/concepts directory (#6082)
- Fix typo inside docs/tutorials (#6083)
- Fix readme code (#6075)

## 🤟 Contributors

We would like to thank all contributors to this release:
- Deepankar Mahapatro (@deepankarm )
- Joan Fontanals (@JoanFM )
- Parikshit Adhikari (@parikshitadhikari )
- Subba Reddy Veeramreddy (@subbuv26 )
- Антон (@BouFFaNTCRiB )
- Abhijit (@AbhiGaunker)

**Comment by scott-martens** [comment]
I don't understand the bug and the description is unhelpful. Can someone explain to me what was wrong?

**Comment by JoanFM** [comment]
there was a bug checking the compatibility of the schemas of different Executors in the same Flow.

**Comment by scott-martens** [comment]
Is this description accurate?
