### ISSUE TITLE
Update the Twitter Logo.

### ISSUE THREAD

**Issue by niranjan-kurhade** [jina-ai/jina#6089]
**Describe your proposal/problem**

In the footer of the docs, we are still using the old logo of Twitter.  https://docs.jina.ai/

---

**Screenshots**
![image](https://github.com/jina-ai/jina/assets/97905637/b33e34ac-8ab6-4637-8eb9-c95ed5c8eb13)

**Solution**
Update the Logo of Twitter to latest logo (X).

**Comment by niranjan-kurhade** [comment]
Please assign this issue to me! I would like to work on it.

**Comment by JoanFM** [comment]
Hello @niranjan-kurhade ,

it would be nice to get your contribution

**Comment by niranjan-kurhade** [comment]
> Hello @niranjan-kurhade ,
> 
> it would be nice to get your contribution

Thanks! Will create a PR soon!

**Comment by AbhiGaunker** [comment]
Even I was looking into this and I was wondering where can I find the these doc related files

**Comment by AbhiGaunker** [comment]
Sir Pls check and approve the code for merging if no issues found. Waiting for your reply

**Comment by AbhiGaunker** [comment]
Thank you

**Comment by niranjan-kurhade** [comment]
Hey @JoanFM, I was assigned this issue and was going to make a PR soon. 🥲

**Comment by JoanFM** [comment]
@nikitashrivastava29 ,

I think the solution provided by @AbhiGaunker does not work, at least on my phone. Perhaps you had a different approach to the solution?

**Comment by niranjan-kurhade** [comment]
> @nikitashrivastava29 ,
> 
> I think the solution provided by @AbhiGaunker does not work, at least on my phone. Perhaps you had a different approach to the solution?

I have been assigned this issue originally, should I make a PR?

**Comment by JoanFM** [comment]
yes please

**Comment by AbhiGaunker** [comment]
Sorry for that @JoanFM @niranjan-kurhade , as discussed before I got the right icon but Forget to update fontawesome version to its latest one. Since older version does not have the new logo we need to change it, I think we have version 5 installed currently

**Comment by JoanFM** [comment]
Hey @AbhiGaunker , can u lead us to how to fix the current issue

**Comment by JoanFM** [comment]
I am reverting the change so far in #6096

**Comment by SkitzAvernal** [comment]
If you guys don’t mind, I’d like a crack at doing this.

**Comment by JoanFM** [comment]
> If you guys don’t mind, I’d like a crack at doing this.

perfect

**Comment by reshma045** [comment]
is the issue solved or still open?

**Comment by JoanFM** [comment]
it is still open

**Comment by niranjan-kurhade** [comment]
> it is still open

Hey @JoanFM, Please check I have made a PR to fix this.

**Comment by shaheer21-sys** [comment]
is this issue still open? if that's the case I'd like to fix it , assign it to me
