### ISSUE TITLE
CI not running all unittests under tests subfolders

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#610]
**Describe your problem**
Jina is not running all unittests under tests subfolders when passing CI. I checked in the CI logs of successfull merged PRs and no reference to those tests are referred and when trying for instance to run the following unittest, it is broken:

tests/executors/crafters/image/test_io.py

**What is your guess?**
In CI command, explicitly *.py pattern is passed and no test discovery is activated.

**Comment by hanxiao** [comment]
this is really important and so bad we didn't find it out earlier.  Please follow on this thread @nan-wang
