### ISSUE TITLE
Error on joining branches: Flow is aborted due to ['gateway'] can not be started.

### ISSUE THREAD

**Issue by jandiers** [jina-ai/jina#6133]
Thank you very much for the excellent effort and time you have invested in Jina!

**Describe the bug**
I ran the [example from the documentation](https://docs.jina.ai/concepts/orchestration/flow/#define-topologies-over-executors) for joining the different branches and noticed that an error occurs:

```python
from jina import Executor, requests, Flow
from docarray import DocList
from docarray.documents import TextDoc

class FooExecutor(Executor):
    @requests
    async def foo(self, docs: DocList[TextDoc], **kwargs) -> DocList[TextDoc]:
        docs.append(TextDoc(text=f'foo was here and got {len(docs)} document'))

class BarExecutor(Executor):
    @requests
    async def bar(self, docs: DocList[TextDoc], **kwargs) -> DocList[TextDoc]:
        docs.append(TextDoc(text=f'bar was here and got {len(docs)} document'))

class BazExecutor(Executor):
    @requests
    async def baz(self, docs: DocList[TextDoc], **kwargs) -> DocList[TextDoc]:
        docs.append(TextDoc(text=f'baz was here and got {len(docs)} document'))

f = (
    Flow()
    .add(uses=FooExecutor, name='fooExecutor')
    .add(uses=BarExecutor, name='barExecutor', needs='fooExecutor')
    .add(uses=BazExecutor, name='bazExecutor', needs='fooExecutor')
    .add(needs=['barExecutor', 'bazExecutor'])
)
```

Running:
```python
with f:
    print(f.post('/', return_type=DocList[TextDoc]).text)
```

Results in:

```
RuntimeWarning: coroutine 'Flow._wait_until_all_ready.<locals>._f' was never awaited (raised from 
/usr/local/lib/python3.10/dist-packages/jina/orchestrate/flow/base.py:1988)

ERROR  Flow@387 Flow is aborted due to ['gateway'] can not be started.                          [01/07/24 19:34:40]

---------------------------------------------------------------------------

RuntimeFailToStart                        Traceback (most recent call last)

[<ipython-input-10-9f7d0fe08cab>](https://localhost:8080/#) in <cell line: 1>()
----> 1 with f:
      2     print(f.post('/', return_type=DocList[TextDoc]).text)

3 frames

[/usr/local/lib/python3.10/dist-packages/jina/orchestrate/flow/base.py](https://localhost:8080/#) in _wait_until_all_ready(self)
   2010                 )
   2011                 self.close()
-> 2012                 raise RuntimeFailToStart
   2013             from rich.rule import Rule
   2014 

RuntimeFailToStart:
```

**Describe how you solve it**
I don't know a solution, but the following code works fine:

```python
f = (
    Flow()
    .add(uses=FooExecutor, name='fooExecutor')
    .add(uses=BarExecutor, name='barExecutor', needs='fooExecutor')
    .add(uses=BazExecutor, name='bazExecutor', needs='fooExecutor')
    # .add(needs=['barExecutor', 'bazExecutor'])
)
```

---

**Environment**

I could reproduce this error on Google Colab as well as on Paperspace Gradient.

- jina 3.23.2
- docarray 0.40.0
- jcloud 0.3
- jina-hubble-sdk 0.39.0
- jina-proto 0.1.27
- protobuf 4.25.1
- proto-backend upb
- grpcio 1.57.0
- pyyaml 6.0.1
- python 3.10.12
- platform Linux
- platform-release 6.1.58+
- platform-version #1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023
- architecture x86_64
- processor x86_64
- uid 2485378613260
- session-id 3df0b26a-ad94-11ee-8fb2-0242ac1c000c
- uptime 2024-01-07T19:37:49.399497
- ci-vendor (unset)
- internal False
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_EARLY_STOP (unset)
* JINA_FULL_CLI (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_GRPC_RECV_BYTES 424
* JINA_GRPC_SEND_BYTES 238
* JINA_HUB_NO_IMAGE_REBUILD (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTOUT_TELEMETRY (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_LOCKS_ROOT (unset)
* JINA_K8S_ACCESS_MODES (unset)
* JINA_K8S_STORAGE_CLASS_NAME (unset)
* JINA_K8S_STORAGE_CAPACITY (unset)
* JINA_STREAMER_ARGS (unset)

**Comment by JoanFM** [comment]
can you run this example with JINA_LOG_LEVEL=debug as environment variable?
