### ISSUE TITLE
Periodical health check of pods/peas

### ISSUE THREAD

**Issue by fhaase2** [jina-ai/jina#633]
**Describe the feature**

As far as i understand, right now the flow makes an initial dry run on startup of the flow. 
An periodical health check of all pods/peas running in a flow might be important to monitor for production purposes. This feature also makes sense for future integration with k8s. 

**Your proposal**

We could extend the `ControlRequest` with e.g. `ControlRequest.HEALTH` and use this to report the health of individual pods/peas?

**Comment by hanxiao** [comment]
it doesn't do `dry_run` by default, #634 add this feature

currently, there is a feature `jina ping` in CLI that does individual pea/pod check.

heartbeat is non-trivial. Please refer to the patterns listed in http://zguide.zeromq.org/php:chapter4#Heartbeating

Towards the cloud-native, this is definitely an important feature, and may lead to advanced feature such as auto-scaling.

**Comment by FionnD** [comment]
Hi! 
I'm closing this issue following the product refinement meeting 10/3/2021. We will reevaluate this feature and decide how we want to deal with this feature going forward. We will welcome thoughts and requirements on this, please leave them in our community slack.
