### ISSUE TITLE
feat: add query language driver

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#640]
**Describe the feature**

- The motivation of `filter` in Jina is to select documents/chunks with some criterion so that the downstream workflow only works on the selected docs/chunks.
- `filter` can be predefined in the flow (for routing); it can also come from the payload of a search query (for filtered searching).

In https://github.com/jina-ai/jina/pull/524, there is a `if` syntax implemented as driver-level filtering that can be used as 

```yaml
!Encode2
requests:
  on:
    IndexRequest:
      - !EncodeDriver
        if: doc.mime_type.startswith('image')
```

Behind the scene, it implements filter in `BaseDriver` with the following:
```yaml
    @property
    def docs(self):
        """Get all docs in the request, filtered by ``if`` when the expression contains ``doc``

        Always use ``self.docs`` instead of ``self.req.docs`` to access filtered docs
        """
        if 'doc' not in self.if_expression and hasattr(self.req, 'docs'):
            yield from self.req.docs
        else:
            for doc in getattr(self.req, 'docs', []):
                if eval(self.compiled_if):
                    yield doc
```

It has many problems:
- Too tightly coupled. I don't think filtering should be part of the features of `BaseDriver`. This prevents us from implementing more advanced filter/select/query language. 
- Unsafe evaluation. In principle, users can send malicious Python code and break the system.
- Limited filtering. No chaining, no select very basic filtering.

**Your proposal**

- Remove `if` syntax from BaseDriver
- Implement `filter` as an independent `FilterDriver`
- `FilterDriver` is responsible for supporting query language, whether it is Django's QuerySe, SQLalchemy, or GraphQL. One can inherit from `FilterDriver` and implement it differently.

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
A simple filter syntax would be like `<key>__<lookuptype>=<value>` where `<key>` is an attribute of the proto and `<lookuptype>` is one of the predefined keywords that specify how to match the `<value>` with the actual value corresponding to the key in each proto object.

These are the currently planned lookup types,

* **exact** exact equality (default)
* **neq** inequality
* **contains** containment
* **icontains** insensitive containment
* **in** membership
* **startswith** string startswith
* **istartswith** insensitive startswith
* **endswith** string endswith
* **iendswith** insensitive endswith
* **gt** greater than
* **gte** greater than or equal to
* **lt** less than
* **lte** less than or equal to
* **regex** regular expression search
* **filter** nested filter

**Comment by hanxiao** [comment]
The `PruneDriver` can be simply a part of `FilterDriver`, as what it does is basically `SELECT`

**Comment by hanxiao** [comment]
References:
- https://github.com/pythonql/pythonql
- https://github.com/naiquevin/lookupy
- https://docs.djangoproject.com/en/3.0/ref/models/querysets/

**Comment by nan-wang** [comment]
By `filtering` in this PR, we mean the filtering the protobuf messages passing between the Pods. With such a filtering mechanism, we are able to make the Pods working on only the **selected** Chunks while streaming all the Chunks.

**Comment by hanxiao** [comment]
https://github.com/myyang/django-pb-model#install

:)
- unify the Pb interface and Django model interface
- can leverage mature Django implementation on QuerySet

:(
- Django has its own License, hard to integrate into Jina
- django-pb-model has limited support on numpy making the queryset pretty standard and not suitable for advanced use case in Jina
- django-pb-model does not have a tracking record on maintenance.

**Comment by hanxiao** [comment]
There are two ways to implement QL here. 

1. Implement QL as a single driver, the query language parsing part happens inside the driver, as `BaseQueryLangDriver` in https://github.com/jina-ai/jina/pull/647/
2. Implement *each Query Operator* as a separate driver. The full query language is realized by user chaining Drivers in a list. QOPs are 
    - filter/where: filter the doc/chunk by its attributes
    - select: select attributes to include in the results
    - limit/take/slicing: take the first k doc/chunk
    - sort/order_by: sort the doc/chunk
    - reverse: reverse the list of collections

In the current implementation, Jina goes for the second option. If we incorporate GraphQL, then it goes for the first option.

While (1) does look cleaner, implementing a new QL is non-trivial. I have surveyed all in-memory ORM/QL/LINQ solution for Python, none of them can be used out-of-the-box. In the worst case, we have to implement a new DSL and its parser.

Option (2) is much easier to implement, we already have some operators go in this direction. However, complex syntax can not be realized, as the QL built with this technique is more a chaining-style, e.g.
```yaml
- !FilterDriver
   with: 
        predicate: id % 2 == 0
- !SortDriver
   with:
         descending: true
- !SelectDriver
   with:
        keys: embeddings
- !LimitDriver
   with:
        length: 5
```

**Comment by JoanFM** [comment]
Option (2) also has the advantage that small independent drivers will be much easier to test.

**Comment by hanxiao** [comment]
Note, the parameter of a Query language driver may also take value from the `Message` proto. As Driver always has access to `self.msg` and `self.req`, this is should not be difficult with some simple parsing.

```yaml
- !LimitDriver
   with:
        length:  {{msg.top_k}}
```
