### ISSUE TITLE
feat: proto Document as recursive structure?

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#648]
**Describe the feature**

I realized that there is some level of consistency between `Document` and `Chunk` in current protobuf definition. I think it's possible to unify these two interfaces and make `Document` recursive.

Example,

![image](https://user-images.githubusercontent.com/2041322/87254779-6278cd80-c485-11ea-90cc-f747f0fb9f28.png)

Doing so will enable chunking & embedding at an arbitrary level, and may improve Jina's generality. 

Some refactoring may be required at Driver level?

**Your proposal**

Something like,

```protobuf
message Document {
    // ...
    repeated Document chunks = 4;
}
``` 

---

**Environment**

**Screenshots**

**Comment by nan-wang** [comment]
what about recursive chunks?
