### ISSUE TITLE
feat(ci): Automatically squash commit messages at Merging time

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#655]
**Describe the feature**
I am a little concerned about how the commit story of jina will get too large and complex.
I think we should have a way to force commit squashing.
We could force the commit message of every merged PR to become the title of the PR + the explanation.
This way we can only force to have the lint for PR messages (thus having a PR template) and not for every single commit of a given branch. I think this woulf make the process of making a contribution much easier and Jina commit history will better represent actual meaningful changes.
Does anyone know a good way to achieve this?

**Comment by JoanFM** [comment]
Would this plugin be a solution?

https://github.com/zachwhaley/squashed-merge-message

**Comment by bhavsarpratik** [comment]
This has squash features
https://github.com/palantir/bulldozer

**Comment by nan-wang** [comment]
> This has squash features
> https://github.com/palantir/bulldozer

Auto merging sounds like a cool feature. I will stay cautious about it for the time being. Considering the fast development we have now, chances are that we want to hold some merging.

**Comment by JoanFM** [comment]
> > This has squash features
> > https://github.com/palantir/bulldozer
> 
> Auto merging sounds like a cool feature. I will stay cautious about it for the time being. Considering the fast development we have now, chances are that we want to hold some merging.

But is not about auto mergint nut about assigning the only one commit per merge, right? Does this tool provide that?

**Comment by hanxiao** [comment]
hi guys, squash merge has been applied to jina repo since a week ago, what is this discussion about?
