### ISSUE TITLE
TransformerTorchEncoder _device error in southpark example

### ISSUE THREAD

**Issue by Burnett1** [jina-ai/jina#656]
**Describe your problem**
Running southpark example with and without "on_gpu: true" in the pod metas now causes below issue

`"TransformerTorchEncoder object has no attribute _device"`

I had this working a month or so ago, updated and am now receiving the message. I saw a pull request merged 2 days ago https://github.com/jina-ai/jina/pull/645 , could this be related?

**Environment**
Latest Jina install via southpark requirements.txt
Running a notebook VM from Google Cloud TensorFlow Enterprise 2.1 (with Intel® MKL-DNN/MKL and CUDA 10.1

**Comment by JoanFM** [comment]
Hello @Burnett1, 
Indeed, this PR #645 should have fixed the issue. Could you please try again with master?

**Comment by Burnett1** [comment]
Hi @JoanFM,

Perfect thanks, I didn't realise 0.3.7 didn't have that fix. Have compiled and tested now with that version and its working as intended. Can close issue now.

Also before you close maybe you can help with some info on then following.

I have tried to find documentation around replicas/shards with GPUSs. Could you clarify/point me to documentation of the impact of increasing replicas on a single machine with a Tesla T4? I have about 520k documents that i need to index and query.

**Comment by JoanFM** [comment]
Hi @Burnett1,

We do not have such specific documentation. Currently some **encoders**, which `**TransformTorchEncoder**` are part of them, support the use of GPU. 

Increasing the number of replicas would increase the number of instances that try to encode **chunks** inside the **encoder**, and each instance will try to move the model to GPU, so I guess it depends on the capacity of the GPU to fit as many models. 

It is definitely a good experiment to have. We would love to hear about your results with that.

I hope you find this insights helpful.
