### ISSUE TITLE
How to use another transformers model

### ISSUE THREAD

**Issue by iedmrc** [jina-ai/jina#662]
**Describe the feature**
Hi, According to this [docs](https://docs.jina.ai/api/jina.executors.encoders.nlp.transformer.html) encoders are limited to: 
` ‘bert-base-uncased’, ‘openai-gpt’, ‘gpt2’, ‘xlm-mlm-enfr-1024’, ‘distilbert-base-cased’, ‘roberta-base’, ‘xlm-roberta-base’, ‘flaubert-base-cased’, ‘camembert-base’, ‘ctrl’.`

How can I run another `bert/gpt2/roberta` etc.. based pretrained model? E.g. German or French or Turkish Bert & Distilbert models? I got an error if I just provide e.g. `dbmdz/distilbert-base-turkish-cased` as model_name.

**Comment by nan-wang** [comment]
hi, @iedmrc Our contributors has made one example for another model from transformers, `hfl/chinese-roberta-wwm-ext`. Maybe it will be help to check it out. In general, it is quite easy to extend. If you have any trouble in extending, feel free to shoot questions.

[https://github.com/jina-ai/examples/blob/master/zh/webqa-search/pods/encoder/transformer_roberta.py](https://github.com/jina-ai/examples/blob/master/zh/webqa-search/pods/encoder/transformer_roberta.py)

**Comment by moosefly123** [comment]
> hi, @iedmrc One of our contributors have made one example for another model from transformers, `hfl/chinese-roberta-wwm-ext`. Maybe it will be helpful to check it out. In general, it is quite easy to extend. If you meet any trouble, feel free to shoot questions.
> 
> https://github.com/jina-ai/examples/blob/master/zh/webqa-search/pods/encoder/transformer_roberta.py

hi~
I met the same trouble like iedmrc and I've checked out the example. 
In the example mentioned by nan-wang, the contributor uses a huggingface-style method to create a model by a shot name of "hfl/chinese-roberta-wwm-ext", which has been uploaded to the remote repository previously as a customized model. Here is my question. How can I use a local pretrained model which I just saved in local path and I can't upload it to some remote repository?
thanks.

**Comment by policeme** [comment]
in your encoder yaml file, add `model_path` in  `with` like this.
```
!TransformerTorchEncoder
with:
    model_path: local_path
balabala
```
if u add like this, your model format must follow huggingface model format

**Comment by iedmrc** [comment]
Hey, here is my `encode.yml`:

```
!TransformerDistilbertTurkishEncoder
metas:
  py_modules: transformer_distilbert_turkish.py

requests:
  on:
    [SearchRequest, IndexRequest]:
      - !EncodeDriver
        with:
          method: encode

```

and `transformer_distilbert_turkish.py` :

```
from jina.executors.encoders.nlp.transformer import TransformerTorchEncoder


class TransformerDistilbertTurkishEncoder(TransformerTorchEncoder):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model_name = '/workspace/model'
        self.tmp_model_path = '/model'
        self.pooling_strategy = 'mean'
        self.max_length = 24

    def get_tokenizer(self):
        from transformers import AutoTokenizer
        _tokenizer = AutoTokenizer.from_pretrained(self.tmp_model_path)
        _tokenizer.padding_side = 'right'
        return _tokenizer

    def get_model(self):
        from transformers import AutoModel
        _model = AutoModel.from_pretrained(self.tmp_model_path)
        self.to_device(_model)
        return _model
```

**Comment by JoanFM** [comment]
Hey guys, clossing this issue.

since the merge of #701, it is possible to use a Transformer model even from a pretrained model saved locally.

**Comment by Singh212dab** [comment]
Can anyone tell me How to control mesage overflow at the Executor?
