### ISSUE TITLE
Out-of-memory while running multires-lyrics-search with larger text files

### ISSUE THREAD

**Issue by cweo** [jina-ai/jina#663]
**Describe your problem**
I'm trying to use your multires-lyrics-search example on bigger text files.
Unfortunately, I'm facing out-of-memory issues and I'm forced to reduce the max-length of distilbert to 32 with half precision to avoid GPU OOM, and obviously the result from the queries are not very fancy.

**What is your guess?**
I tried to put a max_sent_len to the craft.yml file and even with 7, I get an OOM. Therefore, my idea is that every chunk encoded vectors are stored in gpu memory before the _merge. Maybe the encode driver is not taking in account the possibility that all the chunk encoded can not fit into gpu memory.

---

**Environment**
jina                          0.3.7
jina-proto                    0.0.46
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.0
protobuf                      3.12.2
proto-backend                 cpp
grpcio                        1.30.0
ruamel.yaml                   0.16.10
python                        3.7.5
platform                      Linux
platform-release              3.10.0-1127.8.2.el7.x86_64
platform-version              #1 SMP Tue May 12 16:57:42 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /usr/local/lib/python3.7/dist-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)

**Screenshots**
**Steps to reproduce**
* I'm using a rtx 2080ti as gpu
* Use multires-lyrics-search and replace in app.py the input_fn function by:
```python
def input_fn():
    df = pd.read_csv('./sample.csv', encoding='utf-8')
    for row in df.iterrows():
        d = jina_pb2.Document()
        d.tags['ALink'] = row[1]['ALink']
        d.tags['SName'] = row[1]['SName']
        d.tags['SLink'] = row[1]['SLink']
        d.text = row[1]['Text']
        yield d
```
* I'm using batch size of 1, with 1 replica and 1 shard
* In encode.yml use gpu support:
   metas:
      

 on_gpu: True
(Ps: it seems to be the only yml field in the framework that is using "True" instead of "true", the "true" value seems to only launch the pod with gpu support and not running it with it)
* Download my data sample raising the OOM: https://www.swisstransfer.com/d/e23f767a-cbc5-42f3-851b-e456140e2ac7
* run: python app.py index

**Comment by JoanFM** [comment]
Hello @cweo,

Unfortunately, I cannot test with your exact configuration, but I have some insights that might be helpful to you.

What strikes me the most is the length of your documents. When sending these documents for indexing, and with a short **min_sentence_length** like 6, you obtain around 4000 chunks for the document in **sample**.csv. 

I think that this would mean that the model is receiving a batch of 4000 inputs, which counting that **distilbert** is already heavy, can be too big. 

I hope you find this information helpful.

**Comment by cweo** [comment]
Hello @JoanFM,

Thank you a lot for this insight, I didn't know that it was possible to set a batch size for the encoder.

It helps a lot, thank you.
