### ISSUE TITLE
table-of-contents element make docs harder to read

### ISSUE THREAD

**Issue by festeh** [jina-ai/jina#673]
**Describe your problem**
I find it a bit hard to read docs on `https://docs.jina.ai/` because of `table-of-contents` element. It adds a visual clutter that makes me uncomfortable to focus on the content, so I have to set its opacity to 0. I can only suggest to remove it altogether, so docs would look similarly to [transformers](https://huggingface.co/transformers/model_doc/albert.html). But maybe there is a better way?

**Screenshots**
![Screenshot from 2020-07-18 17-12-53](https://user-images.githubusercontent.com/6877858/87854344-03e6a000-c91a-11ea-92b9-244608344084.png)

**Comment by JoanFM** [comment]
Hey @alexcg1 any thoughts on this?

**Comment by alexcg1** [comment]
I'm with @festeh on this. I've found it distracting as well. We *do* need a table of contents however. Any thoughts? More static like [Wikipedia](https://en.wikipedia.org/wiki/Alan_Turing)?

**Comment by alexcg1** [comment]
I'm not sure which of the team chose/built/deployed the doc system, so not sure if it's like that out of the box or if it was a deliberate decision. @hanxiao could you shed some light?

**Comment by hanxiao** [comment]
The original sphinx does not have floating TOC. I added on purpose with a quick hack.

Feel free to improve the layout.

**Comment by nan-wang** [comment]
fixed at #801 . @festeh Now you can fold the TOC bar.
