### ISSUE TITLE
Error handling for bad read_mode in index_files

### ISSUE THREAD

**Issue by festeh** [jina-ai/jina#674]
**Describe your problem**
I'm reading through tutorials now, found a tiny issue with `Flow`'s `index_files` method. If user will occasionally pass bad `read_mode` value, say `r+`, the program will fail without revealing real reason. The problem is [here](https://github.com/jina-ai/jina/blob/cbf9fe99654d98de3f0955df903d52cf1dd15821/jina/clients/python/io.py#L68). 

I suppose that in this case runtime error should be raised.

**Comment by JoanFM** [comment]
Hello @festeh 

Thank you for pointing out this issue, please feel free to open a PR if you feel like fixing the issue.
