### ISSUE TITLE
Update local testing documentation

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#686]
**Describe the bug**
Update the documentation on how to test jina. 

Current used testing framework is not unittest, it is pytest. Plus to run some tests, a test docker image must be built.

`docker build --build-arg PIP_TAG="[devel]" -f Dockerfiles/pip.Dockerfile -t jinaai/jina:test-pip .`

`pip install pytest`
`pip install pytest-xdist`  
`pip install pytest-timeout`
`pip install pytest-cov`
`pytest --cov=jina --cov-report=xml -n 1 --timeout=60 -v tests/unit`

**Comment by nan-wang** [comment]
Shall we make a `README.md` under the `tests` folder and put this information there?

**Comment by JoanFM** [comment]
> Shall we make a `README.md` under the `tests` folder and put this information there?

Seems like a good idea to me

**Comment by Curious-Ujjwal** [comment]
Is the issue currently open?
I would like to work on this.

**Comment by JoanFM** [comment]
Hello @Curious-Ujjwal ,

Sure, it is still a good idea to work on this issue for new contributors to know how to run the tests as the CI does.

You can look at how we use `pytest` in our CI and write a README.md for it under `tests` folder stating that we have unit and integration tests

**Comment by anshulwadhawan** [comment]
Hello,

Can I work on this issue?
