### ISSUE TITLE
Error while running Example using custom indexer...

### ISSUE THREAD

**Issue by Adarsh1999** [jina-ai/jina#690]
**Describe your problem**

Hi Everyone! I recently came across jina and I was surprised by its amazing architecture but when I was running one of its examples which was : pokedex and it ran fine but there in your readme their was a docker script for custom image index and search. So I tried it did as it was written the images were indexed correctly as I was able to see indexers in my workspace folder but after I ran the server and did a curl request( copied from the readme) I got this error here in the attached photos (unknown exception: 'NoneType' object has no attribute 'shape'). So plz can anyone help me out here....
**What is your guess?**
**Maybe where it should return an image it is returning Null response or their indexing is not correct......**

**Screenshots**

![Screenshot (156)](https://user-images.githubusercontent.com/28682167/88087625-d19da280-cba6-11ea-9338-25b469b6a066.png)
![Screenshot (157)](https://user-images.githubusercontent.com/28682167/88087631-d3676600-cba6-11ea-8cab-6bc3c3716699.png)

**Comment by nan-wang** [comment]
hi, @Adarsh1999 This is usually due to the input data is empty. Would you please provide the raw logs and the jina versioning information?
