### ISSUE TITLE
Continuously improve testing and test coverage

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#692]
**Description**
We have to **continuously** push for **quality**, thus we always need to improve our **testing** and **test coverage**. Any improvement of testing is a great **contribution** to **jina**.

If you have no idea how to get started on this, here there are some ideas that could be good to have.

- [ ] **Increase coverage**
Checking the reports on `https://codecov.io/gh/jina-ai/jina` one can see what parts of the code are less tested and we can work together to increase the coverage

- [ ] **Increase the `unitaryism` (I am sure this word does not exist ;)) of unittests.**
Some tests (see, for instance,  test_mime.py, test_segmenter.py) heavily rely on building a Flow to test a functionality. Move those tests under `flow` tests and have the same functionality tested as a simple unittest.
Having a more `unitary` test helps to have better understanding on how pieces of code and classes have to be used.
It also helps to identify potential code quality improvements (It can detect too much coupling between classes and modules) (It should be easy without mocking too many classes to implement these tests) 

- [ ] **Better pytest standards** 
We are trying to improve in our usage of `pytest` features (fixtures, parametrization, etc...) so it can be good to bring old-style tests to this new wave.

**Comment by lusloher** [comment]
Where do we stand on this item?

**Comment by MiaAltieri** [comment]
I'd love to contribute and help to convert either/both test_mime.py or test_segmenter.py into unit tests underneath the flow tests, since their codebase relies heavily on flows. 

I saw that you asked to make sure they have the same functionality tested but as a simple unit tests. They seem like short simple tests already, what can I do to help further simply/unitize them? Is there something you would specifically like to see?

**Comment by winstonww** [comment]
Hi Team,

I'd love to contribute to this issue as well. If I read `https://codecov.io/gh/jina-ai/jina` correctly, the file `jina/peapods/zmq/__init__.py` is currently less tested than the other components. For completeness, I am thinking of adding a unit test to test `Zmqlet`'s `recv_message` method. I have published draft PR #2361  to show this test. If there are any suggestions, please feel free to let me know. Thank you!

**Comment by winstonww** [comment]
> Hi Team,
> 
> I'd love to contribute to this issue as well. If I read `https://codecov.io/gh/jina-ai/jina` correctly, the file `jina/peapods/zmq/__init__.py` is currently less tested than the other components. For completeness, I am thinking of adding a unit test to test `Zmqlet`'s `recv_message` method. I have published draft PR #2361 to show this test. If there are any suggestions, please feel free to let me know. Thank you!

Thanks @JoanFM for reviewing the PR!
