### ISSUE TITLE
Understanding a Jina Cluster

### ISSUE THREAD

**Issue by markhuds** [jina-ai/jina#703]
**Describe your problem**
Hi, I would like some clarification about the way Jina is meant to be interfaced with in a cluster setting. 

I would like to set up a Kubernetes cluster running jina. I imagine being able to monitor this cluster through the dashboard. For instance to create flows for indexing data, view existing indexes, and perform queries against them. From the examples I have seen though, they are single machine and when you run the python apps, jina spins up, does work and exits. How do you create a persistent cluster that is always ready to respond to requests to index and search? I feel like I am missing something. Is there any example of setting up a cluster for jina? And ideally monitoring it using the dashboard?

**What is your guess?**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
No example at the moment. The main reason is that we are not there yet. These features will be implemented in the future version and across multiple product lines.

**Comment by JoanFM** [comment]
Hey @markhuds,

Jina is not yet ready to be deployed as a Kubernetes cluster, but it is ready to be deployed and ready to receive `index` and `search` requests. In the examples normally the Flow is set up and running and a preset of `index` or `search` queries are sent. But you can just create and Build the Flow (even using remote servers) and keep it receiving `index` or `search` requests depending on the kind of Flow. I am not sure if this can answer some of your questions. You can even use the dashboard to monitor these Flows. 

And for the kubernetes cluster, stay tuned to upcoming features!

I hope this helps
