### ISSUE TITLE
Documentation on how to Update Protocol Specification not available in Linux + version stated does not exist

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#705]
**Describe the problem**
I am trying to **Update Protocol Specification** following the steps in https://docs.jina.ai/chapters/proto/modify.html, but the resulting protobuf has some problems when running tests.

My guess is that it is a matter of getting the right corresponding versions between **protoc** and **grpc**, but it is not clear how to do it for Linux and the version stated in the documentation cannot be found in the github link.

**Comment by nan-wang** [comment]
@JamesTang-jinaai Would you please take a look into this?
