### ISSUE TITLE
We want your examples!

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#707]
**Description**

We've got a bunch of tutorials on our [examples repo](https://github.com/jina-ai/examples) but we're always hungry for more!

Have you got a cool dataset you want to showcase? Want to refactor Flows to work your way? Build a Jina example and share it with our community. Even if it's as simple as just switching out a dataset or refactoring the code, we'd love to see what you've got and get it out there for everyone to use.

**Examples:**

* Search [Star Trek scripts](https://www.kaggle.com/gjbroughton/start-trek-scripts)
* Search [cute doggos](https://www.kaggle.com/jessicali9530/stanford-dogs-dataset)
* Search out [the perfect beer for you](https://www.kaggle.com/jtrofe/beer-recipes)

Just follow the format of the examples of what we have already and be sure to document what you're doing!

Your examples would really help be a great contribution to Jina :partying_face:

**Comment by c-shekhar** [comment]
Hey @alexcg1, was going through jina-ai for text search, loved how easy it is to setup and start using the example recipes. Building some more examples will be a good start for me of becoming a regular user of this project.
Would like to start contributing to resolve this issue with the mentioned examples.

**Comment by alexcg1** [comment]
> Hey @alexcg1, was going through jina-ai for text search, loved how easy it is to setup and start using the example recipes. Building some more examples will be a good start for me of becoming a regular user of this project.
> Would like to start contributing to resolve this issue with the mentioned examples.

Great to have you on board! We're currently looking at restructuring our examples, so if you have a new example idea that we haven't built yet then we'd love to help you out!

**Comment by alexcg1** [comment]
We've got plenty of examples for now, and after chatting with @nan-wang and @maximilianwerk maintenance will become  a concern with any more. So I'm closing this now.
