### ISSUE TITLE
Codecoverage does not seem to get accurate delta descriptions on the PR

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#711]
**Describe your problem**
Codecoverage does not seem to make accurate PR comments on the specific impact of a PR on code coverage. 

I have the suspicion that it mixes the impact of the `previous` PR merged into master and the one being analyzed, and I guess it is because that no report is done with `tests` only on `master` branch.

https://docs.codecov.io/docs/comparing-commits

**Comment by hanxiao** [comment]
my guess is codecov should also be run in `cd.yml`

**Comment by JoanFM** [comment]
Yes, do we have a test of master after every merge is done?

**Comment by hanxiao** [comment]
not yet. you can add it

**Comment by JoanFM** [comment]
It seems to be working since #713
