### ISSUE TITLE
use protobuf Struct to serialize document metadata of any type rather than using map[string, string]

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#717]
**Describe the feature**
Right now in jina's proto definition documents contain tags which are maps mapping key-value pairs as a map from string to string. This is flexible enough, but serializing from/to string given any type can be inefficient.

Protobuf has Struct that contains maps from string keys to any arbitrary value. Should jina switch to use those?

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/struct.proto#L52

https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/Struct

https://stackoverflow.com/questions/52966444/is-google-protobuf-struct-proto-the-best-way-to-send-dynamic-json-over-grpc

**Comment by hanxiao** [comment]
this also related to the payload in the query language. #693
