### ISSUE TITLE
is protobuf's FieldMask a better way to implement select/exclude QL driver?

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#720]
**Describe the feature**

Randomly browsing pb docs give me this:

https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
https://github.com/protocolbuffers/protobuf/blob/c0b79c5a398f4eec51ef92784e9d940febdccc52/python/google/protobuf/internal/well_known_types.py#L565

**Your proposal**

Perhaps it's a more "native" way to implement select/exclude QL driver?

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
```python
from google.protobuf.field_mask_pb2 import FieldMask

from jina.proto import jina_pb2
from jina.proto.jina_pb2 import Document

fm = FieldMask(paths=['id'])

d = Document()
d.id = 1
d.text = 'blah'

d2 = Document()


print(d)
print(fm.MergeMessage(d, d2))
print(d2)

exit()
```

--- 

```
id: 1
text: "blah"

None
id: 1
```

**Comment by hanxiao** [comment]
I just realized FieldMask can be very useful and may be related to https://github.com/jina-ai/jina/issues/715

![image](https://user-images.githubusercontent.com/2041322/88482927-a9c28c00-cf64-11ea-99d9-fe81ccde8645.png)
https://medium.com/google-cloud/building-apis-with-grpc-continued-f53b5a5ab850

**Comment by hanxiao** [comment]
for partially modify the message

```
from google.protobuf.field_mask_pb2 import FieldMask

from jina.proto.jina_pb2 import Document

updates = Document()
updates.id = 1
updates.text = 'blah'

old1 = Document()
old1.id = 234
old1.text = 'hello!'

old2 = Document()
old2.CopyFrom(old1)

FieldMask(paths=['id']).MergeMessage(updates, old1)  # mask out id, change only 'text'
print(old1)
FieldMask(paths=['text']).MergeMessage(updates, old2)  # mask out text, change only 'id'
print(old2)

```
---
```
id: 1
text: "hello!"

id: 234
text: "blah"
```

**Comment by hanxiao** [comment]
and can be translated from GraphQL https://rejoiner.io/docs/fieldmasks.html

**Comment by JoanFM** [comment]
It seems as an appropiate way yes, I guess they can do it in a more efficient way. And maybe there is a way to avoid having an extra driver?

**Comment by hanxiao** [comment]
limitations:

```python
FieldMask(paths=['chunks.id']).MergeMessage(updates, old1)
```
 gives:

```
FieldMask(paths=['chunks.id']).MergeMessage(updates, old1)  # mask out id, change only 'text'

```

**Comment by hanxiao** [comment]
This issue becomes irrelevant given the recent refactoring. The technique is interesting though
