### ISSUE TITLE
Is it possible to search on a subset of indexed docs?

### ISSUE THREAD

**Issue by tagizaade** [jina-ai/jina#724]
**Describe the feature**
I had a scenario which needed to search on a subset of documents.
Is it possible for example to filter documents based on their document IDs then search within those filtered docs?

**Comment by nan-wang** [comment]
hi, @tagizaade This is a great feature we'd love to have. Currently, we are working hard on it. Stay tuned!

**Comment by JoanFM** [comment]
Closed as duplicated with #767
