### ISSUE TITLE
Doc identifier is not guaranteed to be unique

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#739]
**Describe your problem**
Doc identifier is not guaranteed to be unique in all system. It could happen that 2 parallel `crafters` may create `chunks` assigning the same id to both of them.

There are 2 points where **ids** are generated: At `SegmentDriver` and at generating request from the `client`. 

**Potential solution**
Since the problem would come when using `KVIndexer` and client only generates documents with `level_depth=0`. We could index in the `KVIndexer` with a combination of `parent_id and id` to guarantee uniqueness. This would work under the assumption that the same `document` is not segmented twice by different `crafters`.

**Comment by hanxiao** [comment]
is setting `RandomUintCounter` as default a solution?

when debugging, use `SimpleCounter`

**Comment by JoanFM** [comment]
> is setting `RandomUintCounter` as default a solution?
> 
> when debugging, use `SimpleCounter`

It is only local right?

**Comment by nan-wang** [comment]
> > is setting `RandomUintCounter` as default a solution?
> > when debugging, use `SimpleCounter`
> 
> Assuming that there are no `conflicts` or `collissions` u mean?
With `RandomUnitCounter`, the chance of collision is `1/4294967295=2.3e-10`. When we go billion-scale index, the chance of collision is still high.

![image](https://user-images.githubusercontent.com/4329072/89482298-227ae100-d7cc-11ea-8468-f0ea28cc67f2.png)

**Comment by hanxiao** [comment]
i understand. but
- it's easy to fix, just use uint64. make a new Counter that's it.
- we are talking about collisions and pseudo random number. no solution gives you 0% collisions.

don't overthink on this.

**Comment by nan-wang** [comment]
fair enough. `uint64` solution should be fine for the time being.

**Comment by JoanFM** [comment]
Closing the issue for the time being
