### ISSUE TITLE
add retry mechanism for port conflicts

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#741]
**Describe the bug** 
The zmq ports conflict in some cases.

```
2020-07-29T16:56:40.0807186Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 142, in init_sockets
2020-07-29T16:56:40.0807474Z     in_sock, in_addr = _init_socket(ctx, self.args.host_in, self.args.port_in, self.args.socket_in,
2020-07-29T16:56:40.0807935Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 657, in _init_socket
2020-07-29T16:56:40.0808130Z     raise ex
2020-07-29T16:56:40.0808347Z   File "/home/runner/work/jina/jina/jina/peapods/zmq.py", line 654, in _init_socket
2020-07-29T16:56:40.0808832Z     sock.bind('tcp://%s:%d' % (host, port))
2020-07-29T16:56:40.0809098Z   File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
2020-07-29T16:56:40.0809479Z   File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
2020-07-29T16:56:40.0809669Z zmq.error.ZMQError: Address already in use
```

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by hanxiao** [comment]
warning, this is not as easy as "change to another port and retry". The Flow has no clue about the port-change at Pea/Pod level and has no way but to re-orchestrate the whole stack.

non-trivial

**Comment by nan-wang** [comment]
> warning, this is not as easy as "change to another port and retry". The Flow has no clue about the port-change at Pea/Pod level and has no way but to re-orchestrate the whole stack.
> 
> non-trivial

Exactly, we have to rethink about the flow building process.

**Comment by hanxiao** [comment]
refactoring Flow just for solving port conflicting problem is over-engineering. 

need to think other ways

**Comment by nan-wang** [comment]
To fix this problem, we need to check the port conflicts. There are two options:

1. check when defining before running the flow
    *solution*: We scan all the available ports and check if the assigned ports is taken. If yes, a new port will be assigned **before** building the connections.
    - pros
        - No hassle to rebuild the flow
    - cons
        - the port might be **still** taken before running the flow
2. check when running the flow
    *solution*: We check whether the assigned port is available. If not, a new port will be assigned and **the flow will be re-built**.
    - pros
        - no worry about the port being taken before running the flow. New port will be assigned in the case of conflicts.
    - cons
        - the information of the new ports needs to be fed back from the pea level to the flow level
        - involves flow re-build for every conflict

**Comment by JoanFM** [comment]
It is not the right solution technically, but what if we try to add retry mechanism to the tests directly? It may do the jo After all is more a problem of too much concurrent tests right? It is not likely to happen in a prod env.

**Comment by hanxiao** [comment]
please notice that random_port already implement your 1


> To fix this problem, we need to check the port conflicts. There are two options:
> 
> 
> 
> 1. check when defining before running the flow
> 
>     *solution*: We scan all the available ports and check if the assigned ports is taken. If yes, a new port will be assigned **before** building the connections.
> 
>     - pros
> 
>         - No hassle to rebuild the flow
> 
>     - cons
> 
>         - the port might be **still** taken before running the flow
> 
> 2. check when running the flow
> 
>     *solution*: We check whether the assigned port is available. If not, a new port will be assigned and **the flow will be re-built**.
> 
>     - pros
> 
>         - no worry about the port being taken before running the flow. New port will be assigned in the case of conflicts.
> 
>     - cons
> 
>         - the information of the new ports needs to be fed back from the pea level to the flow level
> 
>         - involves flow re-build for every conflict

**Comment by hanxiao** [comment]
I agree with this. The best case is to have *each* test case inside a docker container, to avoid collided ports.

Note, we should not use parallelism when doing unit test. The original motivation of moving away from `pytest` is we want to use the process as a context manager so that when the process ends, it releases all resources. `pytest` runs all test cases in *one* process, and this is what we try to avoid.

> It is not the right solution technically, but what if we try to add retry mechanism to the tests directly? It may do the jo After all is more a problem of too much concurrent tests right? It is not likely to happen in a prod env.

**Comment by JoanFM** [comment]
We have `-n 1` option right? I am not familiar with the insights of `pytest` and `unittest`. But are we sure that `github` spins totally isolated environments for every run? Or could it be that the tests for python 3.7 and 3.8 collide?

**Comment by festeh** [comment]
I'm a pytest newbie, but quick Stackoverflowing shows that it can run each test in a separate process (need to install plugin), see https://stackoverflow.com/questions/48234032/run-py-test-test-in-different-process

**Comment by JoanFM** [comment]
> I'm a pytest newbie, but quick Stackoverflowing shows that it can run each test in a separate process (need to install plugin), see https://stackoverflow.com/questions/48234032/run-py-test-test-in-different-process

We are using that one actually.

**Comment by festeh** [comment]
Yeah, should have checked CI workflow. But what's interesting, you have `-n 1` option and in this page flag `--forked` is used instead. Maybe it's worth to try it? ( as I see it's now renamed to `--boxed`)

**Comment by JoanFM** [comment]
I do not know if the problem may come from the 2 runs of 'py37' and `py38` working in the same instance. Maybe `github actions` assigns one container per flow in a matrix?

**Comment by hanxiao** [comment]
https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

> Each job in a workflow executes in a fresh instance of the virtual machine. All steps in the job execute in the same instance of the virtual machine, allowing the actions in that job to share information using the filesystem.

@JoanFM

**Comment by JoanFM** [comment]
> https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
> 
> > Each job in a workflow executes in a fresh instance of the virtual machine. All steps in the job execute in the same instance of the virtual machine, allowing the actions in that job to share information using the filesystem.
> 
> @JoanFM

So unittest for py37 and py38 are steps of the unittest job that are run in the same instance in parallel right?

**Comment by nan-wang** [comment]
> > https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
> > > Each job in a workflow executes in a fresh instance of the virtual machine. All steps in the job execute in the same instance of the virtual machine, allowing the actions in that job to share information using the filesystem.
> > 
> > 
> > @JoanFM
> 
> So unittest for py37 and py38 are steps of the unittest job that are run in the same instance in parallel right?

yes, they are running in parallel.

**Comment by nan-wang** [comment]
hi, there. After tracking the record of ports, I think I've found the reason for the port collision, although I couldn't fully fixed in a single PR. To put it simple, the port assigned by socket in the `random_port()` is possible been taken by other usages before `zmq` initialization. This is more likely to happen on a machine that open and close port frequently. 

Check more details at the PR,
[https://github.com/jina-ai/jina/pull/750#issuecomment-667625165](https://github.com/jina-ai/jina/pull/750#issuecomment-667625165)
