### ISSUE TITLE
Improve type annotation in Jina

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#743]
**Describe the feature**
I think enforcing typing in **methods parameters** can be helpful for robustness, readability and stability of the code. 

**Important**
This issue is about slowly improving type annotation in jina. It is not about integrating any tool into jina systems. Please read below where type hinting is accepted and where not.

- **Things to take into account**
-Do not be too ambitious, target a couple of files.
-Do not change any functional logic (no matter how small) in a PR related only to type hinting.

## Type Annotation without Overdoing it

Though we encourage contributor to add type annotation, bear in mind that Python is not a static typed language, and we should not pretend as it is one.

Here is the guideline when it comes to type annotation for our Jina project:

- on public function signature: **good and necessary**
- on public class variables/attributes: **make sense, but I don't see it's necessary, so better not do that.**
- internal/private variables inside the function, and private attributes/variables inside the class, anything starts with `_`: **completely unnecessary**, it will increase the effort for maintaining and decrease the standardization .

Hope this helps. 🌮

# tooling
By using `mypy` static type checker, we can see potential improvements for `jina`:

Usage: 
```bash
pip install mypy
mypy --ignore-missing-imports jina
```

Do not get overwhelmed by the errors. Let's slowly keep improving until we can eventually have a perfectly typed-checked system! 

Consider `mypy` a tool, is not the intention of jina to optimize any metric regarding `mypy` reports.

**Comment by Arrrlex** [comment]
Hi @JoanFM ,

Looking through the errors generated by `mypy --ignore-missing-imports jina`, it looks like a large proportion are due to mypy being unable to type-check classes autogenerated by protobuf. I'd thus suggest that jina autogenerate type stubs at the same time as generating the python classes, e.g. using [mypy-protobuf](https://github.com/dropbox/mypy-protobuf).

**Comment by JoanFM** [comment]
Hey @Arrrlex ,

Thank you for your suggestions, however this ticket is about generally improving the type hinting to improve code readability and `mypy` is just a tool that can help with it. 

We want it to get constantly improving but we do not want to put too much effort on doing extra work.

**Comment by crysoar** [comment]
Hi, is this open? I'd like to try doing this.

**Comment by JoanFM** [comment]
> Hi, is this open? I'd like to try doing this.

Hey @crysoar, it is a general ticket to consistently improve the type hinting; you are welcome to work on it but do not be too ambtious and work in small portions of the code

**Comment by trsvchn** [comment]
Hi! I would like to join as well, may I?

**Comment by JoanFM** [comment]
> Hi! I would like to join as well, may I?

Hey @trsvchn , of course you are welcome to contribute, please just keep in mind my comment above to @crysoar

**Comment by trsvchn** [comment]
> > Hi! I would like to join as well, may I?
> 
> Hey @trsvchn , of course you are welcome to contribute, please just keep in mind my comment above to @crysoar

Great! Sure, no problem!
