### ISSUE TITLE
Search within sub-groups

### ISSUE THREAD

**Issue by sgaseretto** [jina-ai/jina#767]
**Discussion**

* Same architecture as cross-model search
* Do we need model for this or assimilate from existing example in cross-model?

**Description**

Is it planned to add a way to search only in a sub-group of vectors? This can be a very good feature if you want to implement some sort of multi-tenancy in searches, certain users can only access the images they have uploaded or want them to be public and available for other users to search them. I haven't tested, but I think that Milvus has a similar feature called [`collections`](https://milvus.io/docs/create_drop_collection_python.md) and [`partitions`](https://milvus.io/docs/v0.10.1/create_drop_partition_python.md), probably enabling in a certain way wile defining a flow will be an awesome feature!

# **Vision**
Using traditional filters to easily select what documents can be relevant or directly are undesirable is a very easy way to impact the performance of a search system.

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-147) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
hi, @sgaseretto Thanks for your comments! Yes, this is a key feature we'd love to have. This feature involves quite a few changes in jina. We've already added `tags` in `jina.proto` for labeling Documents. Stay tuned!

**Comment by hanxiao** [comment]
Hi thanks for your attention. We can (almost) do that already since 0.4.1. With newly added query language, you can do the search-and-then-filter. Let me give you an example later.

**Comment by hanxiao** [comment]
but i'm guessing @sgaseretto you are referring to filter-then-search?

**Comment by sgaseretto** [comment]
> but i'm guessing @sgaseretto you are referring to filter-then-search?

I think that it would be a little bit different than filtering, imagine having a bunch of representations from MNIST and another from Fashion-MNIST generated with the same encoder. I know that one is for numbers and the other is for clothes, so instead of building one index for all of them, I can specify that I want to search on which dataset. I think that this will be interesting in multi-tenancy setups, for example in a documents search engine, where users probably would not want to share their documents with the rest of the users. Also, building separate indexes for each `collection` or `partition` could improve the speed of search and facilitate things like sharding and distributing the representations for horizontal scaling.

**Comment by JoanFM** [comment]
I think this pattern is somehow already doable. With the current QueryLanguage capabilities; we can decide dynamically to index documents at different indexers depending on document content or metadata. The same could apply at querying time.

**Comment by JoanFM** [comment]
Hey @sgaseretto , A new example has been added recently to our list of examples that does this, it indexes and queries in different indexers depending on some grouping. You may find this useful: https://github.com/jina-ai/examples/tree/master/fashion-example-query
