### ISSUE TITLE
Transformer encoder is broken

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#773]
**Describe the bug**
The transformer with `distilbert-base-cased` is broken. It might be related to the latest change of #764 

```
ERROR:transformers.tokenization_utils:Using eos_token, but it is not set yet.
```

**Describe how you solve it**

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-149) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Tests are still passing despite the `warning`. Are we sure it was not there before?

**Comment by JoanFM** [comment]
> Tests are still passing despite the `warning`. Are we sure it was not there before?

I checked and in tag `v0.4.1` the message was not being shown

**Comment by nan-wang** [comment]
it is not a critical error, and therefore it won't break the tests.

https://github.com/jina-ai/jina/blob/master/jina/executors/encoders/nlp/transformer.py#L83
