### ISSUE TITLE
Request generator considering docs as a url, in fact is not an url.

### ISSUE THREAD

**Issue by Kavan72** [jina-ai/jina#776]
**Describe the bug**
Request generator is considering docs as a url if the docs is startwith url.

**Describe how you solve it**
https://github.com/jina-ai/jina/pull/775

**Environment**
jina                          0.3.8
jina-proto                    0.0.46
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.1
protobuf                      3.12.4
proto-backend                 cpp
grpcio                        1.31.0
ruamel.yaml                   0.16.10
python                        3.7.8
platform                      Linux
platform-release              5.4.0-42-generic
platform-version              #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020
architecture                  x86_64
processor                     x86_64
jina-resources                /media/kavan/WORK/Job/jina/venv/lib/python3.7/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)

**Traceback**
https://pastebin.com/a9nJbgXx

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-151) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
Is this the input data? 
```
'/MagicStack/uvloop/blob/master/uvloop/cbhandles.pyx December 1, 2016: Sirius Computer Solutions Acquires thinkASG Sirius Computer Solutions has acquired California-based IT solutions provider, thinkASG. The acquisition was finalized on November 30 and expands Sirius presence in the West Coast region.  thinkASG has built a strong organization by providing data center solutions and delivering superior consulting services to their clients. They have very talented employees with deep technical skills in servers and storage, which will offer additional expertise to our clients. Joe Mertens, President and CEO, Sirius  Founded in 1994 and headquartered in Lake Forest, California, thinkASG specializes in IBM-based infrastructure, including data center, storage management and cloud solutions. Several hundred active clients rely on thinkASG to provide expertise in building highly resilient IT architecture to support business-critical applications and systems, including:  SAP HANA and ERP systems Linux workloads Cognitive analytics High-performance computing  Combined with Sirius deep skills and expertise in data center solutions, software solutions, cloud and managed services, consulting services and digital marketing, thinkASG will be able to offer its clients a broader business solutions portfolio that includes security, mobility, analytics, commerce, social, digital and more.  Joining Sirius allows us to truly scale our business and offer our clients a more comprehensive portfolio of products, solutions and services. The values we share with Sirius, including putting clients first, investing in our people and partnerships, and fostering a culture of excellence, make it exciting for us to join forces. David Browning, CEO, thinkASG  thinkASG has over 300 clients, mainly in Southern California, and approximately $38 million in annual revenue. Sirius Computer Solutions is a privately held company, founded in 1980 and headquartered in San Antonio, TX. It has approximately 1,900 employees and more than 5,000 active clients across the United States, with gross revenues of approximately $2 billion in the last twelve months. Sirius invests significantly in the skills of its sales team, product specialists and consultants, who have achieved over 4,000 professional and technical certifications. It focuses on technology-based business solutions that span the data center and other lines of business, and is consistently recognized not only as a leader in the industry, but also as a company with a strong set of core values guiding its leaders and employees. More Information:'
```
