### ISSUE TITLE
url_pat: We can handle moving the `url_pattern` regex outside the function scope in a different PR

### ISSUE THREAD

**Issue by hanxiao** [jina-ai/jina#779]
LGTM! Just some minor issues. We can handle moving the `url_pattern` regex outside the function scope in a different PR

_Originally posted by @JoanFM in https://github.com/jina-ai/jina/pull/775#issuecomment-670393729_

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-153) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Closed by #780
