### ISSUE TITLE
docker: Error response from daemon: create $(pwd)/j: "$(pwd)/j" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path. See 'docker run --help'.

### ISSUE THREAD

**Issue by zhangyu1111** [jina-ai/jina#786]
**Describe the bug**

Configuration：win10 + docker desktop(version: 2.3.04 channel: stable)
according to [https://docs.jina.ai/chapters/helloworld/index.html](url), try Jina’s “Hello, World” , 
use command:
`docker run -v "$(pwd)/j:/j" jinaai/jina:devel hello-world --workdir /j --logserver && open j/hello-world.html`

But the following error occurred:
**docker: Error response from daemon: create $(pwd)/j: "$(pwd)/j" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.**

**Describe how you solve it**
`docker run -v "path/j:/j" jinaai/jina hello-world --workdir /j && open j/hello-world.html`   the "**path**" is the current directory path

## 

**Screenshots**
![image](https://user-images.githubusercontent.com/44194055/89708757-6a585e80-d9ac-11ea-93ab-bb9e212460df.png)

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-154) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Hello, 

I think the problem comes from the fact that "pwd" is a valid Unix command to access current directory, but it is not valid in Windows. So your solution is exactly what the command intends to do.

**Comment by zhangyu1111** [comment]
Yes, you are right.@JoanFM
But according to https://docs.jina.ai/chapters/helloworld/index.html, I did not realize that "pwd " is not applicable on windows.
So I filed this issue. The purpose is to remind windows users to pay attention when using this command.

**Comment by JoanFM** [comment]
> Yes, you are right.@JoanFM
> But according to https://docs.jina.ai/chapters/helloworld/index.html, I did not realize that "pwd " is not applicable on windows.
> So I filed this issue. The purpose is to remind windows users to pay attention when using this command.

Good idea! Thank you very much

**Comment by hanxiao** [comment]
> Yes, you are right.@JoanFM
> 
> But according to https://docs.jina.ai/chapters/helloworld/index.html, I did not realize that "pwd " is not applicable on windows.
> 
> So I filed this issue. The purpose is to remind windows users to pay attention when using this command.

this is out of the scope of Jina, it is basic computer skills
