### ISSUE TITLE
how to use the `Chunk2DocRankerDriver` with recursive Document structure

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#799]
**Describe the feature**
The core part of `Chunk2DocRanker` is to reduce the `k`th depth level `matches` into `k-1`th depth level ones. This requires to extract all `matches` at `k`th level, which is done by `Chunk2DocRankDriver`. The results should be written into the `k-1` th level. 

For simplicity, let's keep `k=1`. The input docs are 

```
doc0: {id: 0, level_depth=0}
├── chunks: {id:123456, level_depth=1}
|   ├── matches: {parent_id:1, score.ref_id:123456, id:198765, level_depth=1}
|   └── matches: {parent_id:2, score.ref_id:123456, id:298765, level_depth=1}
└── chunks: {id:123457, level_depth=1}
    ├── matches: {parent_id:1, score.ref_id:123457, id:187654, level_depth=1}
    └── matches: {parent_id:2, score.ref_id:123457: 287654, level_depth=1}

```

The expected output is 

```
doc0: {id: 0, level_depth=0}
├── chunks: {id:123456, level_depth=1}
|   ├── matches: {parent_id:1, score.ref_id:123456, id:198765, level_depth=1}
|   └── matches: {parent_id:2, score.ref_id:123456, id:298765, level_depth=1}
└── chunks: {id:123457, level_depth=1}
|   ├── matches: {parent_id:1, score.ref_id:123457, id:187654, level_depth=1}
|   └── matches: {parent_id:2, score.ref_id:123457: 287654, level_depth=1}
└── matches
    ├── matches: {score.ref_id:123456, id:1, level_depth=0}
    └── matches: {score.ref_id:123457, id:2, level_depth=0}

```
This is pattern is expected to be a common case for the rankers to reduce the `matches` from the `k`th level to `k-1`th level.

**Your proposal**

Add a unit test to illustrate the usage of `Chunk2DocRankerDriver`.  

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-156) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Just to be sure, `score.ref_id` should be always the same as the one it matches from?

Would it need to be like this?

```bash
doc0: {id: 0, level_depth=0}
├── chunks: {id:123456, level_depth=1}
|   ├── matches: {parent_id:1, score.ref_id:123456, id:198765, level_depth=1}
|   └── matches: {parent_id:2, score.ref_id:1234561, id:298766, level_depth=1}
└── chunks: {id:123457, level_depth=1}
    ├── matches: {parent_id:1, score.ref_id:123457, id:187654, level_depth=1}
    └── matches: {parent_id:2, score.ref_id:123457, id: 287655, level_depth=1}

```

**Comment by JoanFM** [comment]
> Just to be sure and be on the same page, `score.ref_id` should be always the same as the one it matches from?
> 
> Would it need to be like this?
> 
> ```shell
> doc0: {id: 0, level_depth=0}
> ├── chunks: {id:123456, level_depth=1}
> |   ├── matches: {parent_id:1, score.ref_id:**123456**, id:198765, level_depth=1}
> |   └── matches: {parent_id:2, score.ref_id:**123456**, id:298766, level_depth=1}
> └── chunks: {id:123457, level_depth=1}
>     ├── matches: {parent_id:1, score.ref_id:**123457**, id:187654, level_depth=1}
>     └── matches: {parent_id:2, score.ref_id:**123457**, id: 287655, level_depth=1}
> ```

**Comment by hanxiao** [comment]
> With traverse_on='chunks' and context_doc=None, the _apply_all func from Chunk2DocRanker will directly return empty results. It is also impossible to specify the context_doc because a list of docs are fed.

I don't understand this part. https://github.com/jina-ai/jina/blob/master/jina/drivers/__init__.py#L230 clearly shows that `context_doc` is given

**Comment by hanxiao** [comment]
> With traverse_on='matches' and context_doc=None, the _apply_all func from Chunk2DocRanker will directly return empty results. Plus, the _apply_all() has no access to the doc0.matches. The _apply_all has no access to the doc0.matches. Plus, it is not running on all the chunks of the doc0.

if you specify `traverse_on='matches'` then you should not expect the driver applies on `chunks`, same goes for `traverse_on='chunks'`, you don't expect that the driver applies on `matches`, *this is by design*. Please note that `BaseRecursiveDriver` is applied to all drivers not only RankDrivers.

Some Drivers may break this semantic by accessing `matches` and `chunks` simultaneously, such access is not prohibited but not considered as a good pattern. `Chunk2DocRankDriver` is an example.

**Comment by hanxiao** [comment]
All in all, for `Chunk2DocRankDriver`, having `traverse_on` set to `chunks` and depth level set to `[0, k]` where `k>=1` should work.

**Comment by JoanFM** [comment]
Hey @nan-wang , I totally agree that this pattern is really important to have it right, and we saw trying to get `urbandict` right that it posed some problems. I would need to dig much deeper into it to see if this change is needed.

**Comment by hanxiao** [comment]
I still don't get it. What's the problem here?

**Comment by hanxiao** [comment]
let's discuss this in the engineering all hands on Tuesday

**Comment by hanxiao** [comment]
can you reply to this and better provide a unit test to show my comment here https://github.com/jina-ai/jina/issues/799#issuecomment-671484296 does not work?

**Comment by JoanFM** [comment]
Comment under construction...

Let me see if I can put some light in the issue. We identified with @nan-wang a pattern that we did not see how to solve it (reference https://github.com/jina-ai/examples/pull/132).

Let's see a toy moment of the solution:
At some point the Ranker receives this request:

```bash
request {
  request_id: 1
  search {
    docs {
      id: 1
      weight: 1.0
      length: 100
      matches {
        id: 2542526931
        weight: 1.0
        length: 2
        mime_type: "text/plain"
        text: "a guys state of mind after he sees the girl of his dreams..."
        level_depth: 1
        parent_id: 4
        location: 0
        location: 60
        embedding {
          buffer: "NOISE"
          shape: 768
          dtype: "<f4"
        }
        score {
          op_name: "NumpyIndexer"
          ref_id: 1
        }
      }
      matches {
        id: 3327386325
        weight: 1.0
        length: 3
        mime_type: "text/plain"
        text: "a more polite alternative."
        level_depth: 1
        parent_id: 3
        location: 48
        location: 75
        offset: 2
        embedding {
          buffer: "NOISE"
          shape: 768
          dtype: "<f4"
        }
        score {
          op_name: "NumpyIndexer"
          ref_id: 1
        }
      }
      mime_type: "text/plain"
      text: "big cat"
      embedding {
        buffer: "NOISE"
        shape: 768
        dtype: "<f4"
      }
    }
  }
}

```

**Comment by nan-wang** [comment]
> provide

@hanxiao @JoanFM For simplicity, we assume the following case. 
![image](https://user-images.githubusercontent.com/4329072/89921746-a996e180-dc30-11ea-8f13-382a1ceb2c8c.png)

This is what we've implemented in https://github.com/jina-ai/examples/pull/132. The unit test is provided in https://github.com/jina-ai/jina/pull/813. 

A more reasonable case is as below.
![image](https://user-images.githubusercontent.com/4329072/89921856-d1864500-dc30-11ea-8aec-bd0985c37d36.png)

**Comment by JoanFM** [comment]
> > provide
> 
> @JoanFM Here is a simplified version of your cases. After discussion with Han, this case turns out to be a Pseudo demand. The design of #702 requires the `level_depth` of the `matches` must be the same as `Document`. Therefore the implementation is not correct in [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132).
> ![image](https://user-images.githubusercontent.com/4329072/90020664-b7a53a80-dce2-11ea-86e1-aa8c59d347f4.png)
> 
> A more reasonable case is as below, which is tested in #813.
> ![image](https://user-images.githubusercontent.com/4329072/90019071-7f046180-dce0-11ea-999b-d0322324c452.png)

So what is the correct implementation for jina-ai/examples#132? Do we need to force a `crafter` at `search` mode?

**Comment by nan-wang** [comment]
> > > provide
> > 
> > 
> > @JoanFM Here is a simplified version of your cases. After discussion with Han, this case turns out to be a Pseudo demand. The design of #702 requires the `level_depth` of the `matches` must be the same as `Document`. Therefore the implementation is not correct in [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132).
> > ![image](https://user-images.githubusercontent.com/4329072/90020664-b7a53a80-dce2-11ea-86e1-aa8c59d347f4.png)
> > A more reasonable case is as below, which is tested in #813.
> > ![image](https://user-images.githubusercontent.com/4329072/90019071-7f046180-dce0-11ea-999b-d0322324c452.png)
> 
> So what is the correct implementation for [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132)? I still have no clear vision of what is wrong there. It feels that what we are doing there fits the second schema. Do we need to force a `crafter` at `search` mode?
> 
> To me it seems that what we are intending there is a pretty common usecase and I think what we are trying to do there is the way that feels the more natural. Are we sure we want to force some extra steps to fit this?
> 
> In terms of `level depth`. If we reduce `matches` from `chunks` to their `parents` I would also consider that the `match` "loses" one level_depth.

As for https://github.com/jina-ai/examples/pull/132, the key issue is that we need a `crafter` to make the Document from `level_depth=0` to `level_depth=1`. Thereafter, the query Document should have consistent `level_depth` with the `matches`, which are in `level_depth=1`.

**Comment by JoanFM** [comment]
> > > > provide
> > > 
> > > 
> > > @JoanFM Here is a simplified version of your cases. After discussion with Han, this case turns out to be a Pseudo demand. The design of #702 requires the `level_depth` of the `matches` must be the same as `Document`. Therefore the implementation is not correct in [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132).
> > > ![image](https://user-images.githubusercontent.com/4329072/90020664-b7a53a80-dce2-11ea-86e1-aa8c59d347f4.png)
> > > A more reasonable case is as below, which is tested in #813.
> > > ![image](https://user-images.githubusercontent.com/4329072/90019071-7f046180-dce0-11ea-999b-d0322324c452.png)
> > 
> > 
> > So what is the correct implementation for [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132)? I still have no clear vision of what is wrong there. It feels that what we are doing there fits the second schema. Do we need to force a `crafter` at `search` mode?
> > To me it seems that what we are intending there is a pretty common usecase and I think what we are trying to do there is the way that feels the more natural. Are we sure we want to force some extra steps to fit this?
> > In terms of `level depth`. If we reduce `matches` from `chunks` to their `parents` I would also consider that the `match` "loses" one level_depth.
> 
> As for [jina-ai/examples#132](https://github.com/jina-ai/examples/pull/132), the key issue is that we need a `crafter` to make the Document from `level_depth=0` to `level_depth=1`. Thereafter, the query Document should have consistent `level_depth` with the `matches`, which are in `level_depth=1`.

Ok, that was my suspicion, I have a proposal though.

 I feel it is not natural to force the user to have a `crafter` just because he needs to match the `target` depth level. What if we allow the request generator, to generate `documents` at a specific `target depth level`?

After all, when using `urbandict` we are using `descriptions` (could be seen as `docs` at level 1, but the generator assigns level 0) to query the system, that contains `level 1` documents in the `vector index`. 

As explained in one pattern here https://docs.jina.ai/chapters/flow/index.html#common-design-patterns, this issue would appear really often, specially when targetting `text` data.

I would be really annoyed to be forced to `craft` a sentence, just to fit the `depth levels`.

**Comment by nan-wang** [comment]
The core issue is about where do we want to check/match the `level_depth`. As you see, there are two options,

1. use `Flow` api to smartly generate requests at the proper `level_depth`
2. force the user to add `crafter` for making a proper `level_depth`

I'd also like to go for the 1st option as you suggested. What about adding a new option for `flow.search_(level_depth=(1,2))`?

**Comment by JoanFM** [comment]
> The core issue is about where do we want to check/match the `level_depth`. As you see, there are two options,
> 
> 1. use `Flow` api to smartly generate requests at the proper `level_depth`
> 2. force the user to add `crafter` for making a proper `level_depth`
> 
> I'd also like to go for the 1st option as you suggested. What about adding a new option for `flow.search_(level_depth=(1,2))`?

It is definitely an option to offer this feature to the `user` through the `Flow` api. 

But I feel that this syntax and interface would not feel natural to `jina` current workflow. Let me explain myself.

Doing `flow.search_(level_depth=...)` seems like a `declarative language` statement, where you are describing what you want in output. However doing flow.search() as we regularly do, but with a `generator` setting the proper `level_depth` seems more like an imperative style that would `jina` flow run naturally. (I mostly refer to the `BaseRecursiveDriver` logic). Does this make sense?

**Comment by hanxiao** [comment]
> The core issue is about where do we want to check/match the `level_depth`. As you see, there are two options,
> 
> 
> 
> 1. use `Flow` api to smartly generate requests at the proper `level_depth`
> 
> 2. force the user to add `crafter` for making a proper `level_depth`
> 
> 
> 
> I'd also like to go for the 1st option as you suggested. What about adding a new option for `flow.search_(level_depth=(1,2))`?

can you follow the discussion in #team-engineering
