### ISSUE TITLE
Adding contributors to README

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#806]
**Describe the bug**
Not all contributors are on the README

**Describe how you solve it**
I'll call the bot from comments on this issue

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-160) by [Unito](https://www.unito.io/learn-more)

**Comment by alexcg1** [comment]
@all-contributors please add @JoanFM  for code

**Comment by alexcg1** [comment]
@all-contributors please add @nan-wang  for code
@all-contributors please add @alexcg1   for docs

**Comment by alexcg1** [comment]
@all-contributors please add @nan-wang  for code, doc, bug, example, ideas, review, infra and test

**Comment by alexcg1** [comment]
@all-contributors please add @alexcg1  for doc, bug, example, tutorial, blog

**Comment by alexcg1** [comment]
@all-contributors please add @alexcg1 for doc, tutorial, blog

**Comment by hanxiao** [comment]
@all-contributors please add @hanxiao

**Comment by alexcg1** [comment]
@hanxiao you need to add what the contributions are. e.g. `@all-contributors please add @alexcg1 for doc, tutorial, blog`

[contribution types here](https://allcontributors.org/docs/en/emoji-key)

**Comment by hanxiao** [comment]
yes, but it's a bad design. I will use CLI to add in bulk, and make a PR consider this issue as done. No need to proceed on this.

**Comment by hanxiao** [comment]
it's done
