### ISSUE TITLE
level_depth=(0, 0) is invalid

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#814]
**Describe the bug**
The default value of `BaseRecursiveDriver ` is `level_depth=(0, 0)`, which is an invalid option. The traverse range is **right exclusive**.

**Describe how you solve it**
change it to `(0, 1)`

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-163) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
This change leads to the failure of the following tests.

```
FAILED tests/unit/drivers/test_reduce_all_driver.py::ReduceAllDriverTestCase::test_merge_chunks_with_different_modality
FAILED tests/unit/drivers/querylang/test_querylang_drivers.py::QueryLangTestCase::test_filter_ql_modality
FAILED tests/unit/flow/test_flow.py::FlowTestCase::test_flow_with_modalitys_simple
```

**Comment by hanxiao** [comment]
pre_traverse and post_traverse work differently that's fine. [0,0] works on pre but not on the post. before we have a better idea, let's keep it in this way.
