### ISSUE TITLE
Request generator assumes same `mime type` for all documents in request

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#845]
Request generator assumes same `mime type` for all documents in request, should this be more flexible?

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-176) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
The `mime_type` of each document is deterministic. If the user want to index/query different type of data, they will need call the flow apis multiple times. Is this the pain point?
