### ISSUE TITLE
Add doc for keyword 'request on'

### ISSUE THREAD

**Issue by YueLiu-jina** [jina-ai/jina#850]
**Describe the feature**

Currently we have no doc for explaining the usage of 'request: on:' . I'll add some explanation into the doc

**Your proposal**

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-178) by [Unito](https://www.unito.io/learn-more)

**Comment by hanxiao** [comment]
`requests.on` is mentioned in the docstring of `CompoundExecutor`

You can also refer to that as well, at least from the syntax perspective.

**Comment by YueLiu-jina** [comment]
I find it now. I'll move and refactor it in the yaml chapter.

**Comment by hanxiao** [comment]
is it done?

**Comment by YueLiu-jina** [comment]
Not yet, will finish this quickly on Monday.
