### ISSUE TITLE
Docs: Using Docker images on Fedora

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/jina#869]
**Describe the feature**
I've recently started using Fedora 32 and hit some issues running the Jina Docker images. These are issues from Docker itself, but I still think we should mention them in the docs. Perhaps a new page - "Using anything **other** than Mac/Ubuntu? Check here!"

These aren't Jina's issues, but they will screw up using Jina on a new machine, so I think users should at least be aware

**Your proposal**

* [Inform users they need to add an extra kernel line](https://github.com/jitsi/docker-jitsi-meet/issues/618#issuecomment-636327655)
* [Inform them to disable SELinux](https://stackoverflow.com/questions/61527193/docker-and-permissionerror-errno-13-permission-denied-output-svg)

After fixing those, Jina's Hello World worked perfectly!

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-193) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
Good point! @alexcg1 Would you please put the logs under this issue?
