### ISSUE TITLE
changes of existing executors in jina-hub are not registered by `register_class()`

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/jina#882]
**Describe the bug**
local changes of executors in `jina-hub` are **NOT** registered by the `register_class()` method. Check more details at https://github.com/jina-ai/jina-hub/pull/295#issuecomment-683279092

**This will block the future maintenance of** `jina-hub`.

**Describe how you solve it**
https://github.com/jina-ai/jina-hub/pull/295#issuecomment-683279092

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-199) by [Unito](https://www.unito.io/learn-more)

**Comment by hanxiao** [comment]
I don't get it why only #295 face the problem while others don't?
