### ISSUE TITLE
why did we delete the equals sign in post traverse or pre traverse?

### ISSUE THREAD

**Issue by xiongma** [jina-ai/jina#887]
**Describe your problem**
in this code span, I don't know why we have to delete the equals sign in `_apply`?   is the current level depth never reach to `self._depth_end`?

    def post_traverse(_docs, traverse_on, context_doc=None):
        """
        :param _docs: list of docs
        :param traverse_on: "matches" or "chunks"
        :param context_doc: the owner of ``_docs``, if None, then it is at the very top-level
        :return:
        """
        if _docs:
            for d in _docs:
                # check if apply to next level
                if d.level_depth < self._depth_end:
                    post_traverse(getattr(d, traverse_on), traverse_on, d)
                # check if apply to the current level
                if self._is_apply and self._depth_start <= d.level_depth < self._depth_end:
                    self._apply(d, context_doc, traverse_on, *args, **kwargs)
    
            # check first doc if in the required depth range
            if self._is_apply_all and _docs[0].level_depth >= self._depth_start:
                self._apply_all(_docs, context_doc, traverse_on, *args, **kwargs)here is a example.
document has 2 levels, I want to use `ExcludeQL` to clear some fields in second level, if I set `depth_range` to `[1, 1]`.  it couldn't reach `ExcludeQL`'s `_apply`.

maybe it's my misunderstanding.

**What is your guess?**
change these codes

```
if self._is_apply and self._depth_start <= d.level_depth < self._depth_end
```

to 

```
if self._is_apply and self._depth_start <= d.level_depth <= self._depth_end
```

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-202) by [Unito](https://www.unito.io/learn-more)

**Comment by xiongma** [comment]
or the depth range just like index, like this `lst1[1: 3]`?

**Comment by nan-wang** [comment]
Hi, @xiongma This motivation behind this change is to keep consistent with the python convention. As for the range value, it is always left-inclusive and right-exclusive. Functionally, this is tested in the unit test.

As for your use case, you need to set `depth_range` to [0, 2] if the Document has two levels.

**Comment by xiongma** [comment]
ok, got it
