### ISSUE TITLE
Bug in Jina's Documentation User Interface.

### ISSUE THREAD

**Issue by hakerbaya** [jina-ai/jina#895]
**Describe your problem**
The Bug Lies on Jina's Documentation Page with a CARD "Title Of Contents", which gives user bad experience, as it is overlapping contents. See the Screenshot.

**What is your guess?**
I think this problem can be solved , when we scroll down the page, "Table of Contents" should remain hidden as it will not affect user experience.

- - -
**Environment**
Go to link: https://docs.jina.ai/chapters/install/via-pip.html

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-205) by [Unito](https://www.unito.io/learn-more)

**Comment by nan-wang** [comment]
hi, there. Many thanks for your comments. You can click on the hamburger button on the TOC to hide it. 
![image](https://user-images.githubusercontent.com/4329072/92667014-61f19b80-f33d-11ea-90c4-b0ec33a405e9.png)

**Comment by hakerbaya** [comment]
but it still overlaps content.

**Comment by hanxiao** [comment]
@JamesTang-jinaai previously worked on that, can @DavidSanwald follow on this thread. this should be a quick fix

**Comment by hanxiao** [comment]
#673

**Comment by hakerbaya** [comment]
Yea, @DavidSanwald  can follow on this thread, just fix it as soon as possible, my suggestion is to stick it to the top right corner, but when we scroll down hide it, and when we scroll up to the header show it. 🤔

**Comment by DavidSanwald** [comment]
I asked @imsergiy for advice. It's quite out of my comfort zone. I think it might be the same for Sergeiy but maybe he's quicker to see through.

**Comment by hakerbaya** [comment]
@DavidSanwald Nice Great Problem is solved. Thanks. 😊
