### ISSUE TITLE
add device map parameter for pod level

### ISSUE THREAD

**Issue by xiongma** [jina-ai/jina#896]
**Describe the feature**

if add `device_map` for `jina`, which level should I work on, `Pod`, `Flow`?
my opinion for this is it should be `Pod`, if that it will very flexible for user to set which devices should `Pod` work on.

**Your proposal**

- - -

**Environment**

**Screenshots**

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-206) by [Unito](https://www.unito.io/learn-more)

**Comment by xiongma** [comment]
ok.
**Problem with jina as below**
1. currently, if we set `on_gpu=True`, all `Peas` in `Pod` always work on firt GPU, except `HeadPea` and `TailPea`.
2. if we have more than 1 GPU, and `Pod`  `parallel` is greater than 1, `jina` doesn't have a strategy to distribute this `Peas` on this GPUs.

**Feature**
add a parameter called `device_map` in jina. in `device_map`, it contains all `Peas` device_id.

**Question**
1. I'm a little confuse about which level should I add `device_map` on?  
add it on `Pod` 
```
!Flow
pods:
  encoder:
    device_map: [1, 2, 3]
```
or add it on `Flow`
```
! Flow
with:
 device_map: [1, 2, 3]
```

**My strategy**
1. add `device_map` on `Pod`
2. add `device_id` on `Executor's metas`

**Comment by xiongma** [comment]
@hanxiao you mean the device id in metas can be this [1, 2, 3] or just a device number?

**Comment by hanxiao** [comment]
whatever makes sense is ok. but your previous PR adds too many interfaces to CLI and loading logics, which is completely unnecessary this i have to reject it.

Unfortunately i don't have time to follow on this topic for now, please don't expect me to give prompt reply on this thread
