### ISSUE TITLE
ConvertDriver to convert from `NdArray` to URI for proper access in jinabox

### ISSUE THREAD

**Issue by JoanFM** [jina-ai/jina#908]
**Functionality** 
Leveraged for debugging; after you have preprocessed pictures in NdArray, the ability to create URI out of it.
And can visualize chunk (NdArray) on any level of depth and the front-end can read it.

**Front-End** 
You could do document tracing (visually) know how the doc looks throughout the entire flow.

**Describe the feature**
Right now `Buffer2URI` driver assumes the data from the document is in the `document buffer`. It could be interesting to store in a KV index the result of some crafting (here I am thinking mostly on images). In order to do that and allow proper visualization on jinabox we need to get proper URI value.

Therefore I think it would be nice to have a new driver maybe a `NdArray2URI` or something similar to cover this need.

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-215) by [Unito](https://www.unito.io/learn-more)

**Comment by hanxiao** [comment]
so you basically want to visualize ndarray?

**Comment by hanxiao** [comment]
but how come an image is converted to a ndarray without storing the original `buffer` in the first place,

**Comment by JoanFM** [comment]
> so you basically want to visualize ndarray?
> 
> > t could be interesting to store in a KV index the result of some crafting (here I am thinking mostly on images)
> 
> so visualizing the intermediate results

Exactly, visualize a transformed image for instance,

**Comment by rutujasurve94** [comment]
Merged PR: https://github.com/jina-ai/jina/pull/982 for adding NdArray Driver.
@imsergiy will be testing the frontend with this new driver.

**Comment by nan-wang** [comment]
resolved by #982
