### ISSUE TITLE
Specifying port when using `jina flow` in command line

### ISSUE THREAD

**Issue by alasdairtran** [jina-ai/jina#924]
**Describe your problem**

When I create a flow with code, I can fix the port with

```python
flow = Flow(port_expose=12345)
```

The above code works well.

However I can't seem to find a way to fix the port when using the command line. I've tried

```sh
jina flow --yaml-path path/to/flow/config.yml
```

and specifying in the yml file

```yaml
!Flow
with:
  port_expose: "12345"
```

but this doesn't have any effect. The `port_expose` line in the yaml seems to get ignored.

Am I missing something?

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-217) by [Unito](https://www.unito.io/learn-more)

**Comment by JoanFM** [comment]
Have u tried setting `rest_api: true`?

**Comment by hanxiao** [comment]
fyi, you don't need a quote for int, simply `port_expose: 12345`

**Comment by hanxiao** [comment]
btw, i added a unit test here, so this should work without any problem
https://github.com/jina-ai/jina/pull/925/files#diff-4b9a2c9a9934b139fdb162f2a5a50ecfR511

**Comment by alasdairtran** [comment]
We only see the issue with the command line approach using `jina flow`. I think I found where the problem is. When I comment out [this line](https://github.com/jina-ai/jina/blob/9c27eaf4908ae65f1f63e4549049634830abc8ee/jina/main/api.py#L84), everything works fine - the port is fixed to the specified port in the yaml file. 

I don't know the code base well, so I'm not sure exactly what that line does. But I guess when you call `f._update_args(args)`, it deletes/overrides the existing args specified in the yaml file.

**Comment by hanxiao** [comment]
i see this is indeed the problem, the previous settings were overrode due to `f._update_args`. let me quickly fix it.

**Comment by hanxiao** [comment]
you are right, the line you pointed out is redundant, having it fix in #926

**Comment by hanxiao** [comment]
@alasdairtran it is fixed and we haven't rolled out to Pypi yet, at the latest you can expect on this Friday. see [release schedule](https://github.com/jina-ai/jina/blob/master/RELEASE.md) for details

**Comment by alasdairtran** [comment]
Thanks @hanxiao, but in PR #926,  I only see that a new test case is added. The line `f._update_args(args)` is still there in [api.py](https://github.com/jina-ai/jina/blob/1b5927645bb049f1ce718582fef297117d1fbb5c/jina/main/api.py#L84).

**Comment by hanxiao** [comment]
you are absolutely right, fixing it in #927
