### ISSUE TITLE
Horizontal scaling for loading big datasets

### ISSUE THREAD

**Issue by jmferrete** [jina-ai/jina#929]
Since the resolution of #867, thanks a lot guys for your great work there, we can now index our test datasets of ~190 GB without problems. But now, we have a new issue when querying the indices, our search process gives timeout errors even with increasing the `timeout_ready` property value to 1 hour.

As we can see here:

```bash
$> PREFETCH=5 PREFETCH_ON_RECV=1 BATCH_SIZE=50 PARALLEL=1 SHARDS=10 python app.py -t query
           JINA@35452[W]:parser Flow can not recognize the following args: ['--read-only', '--port-expose', '45678'], they are ignored. if you are using them 
from a global args (e.g. Flow), then please ignore this message
           JINA@35452[W]:parser FlowPod can not recognize the following args: ['--reducing-uses', '_merge_all'], they are ignored. if you are using them from 
a global args (e.g. Flow), then please ignore this message
           Flow@35452[S]:successfully built Flow from a yaml config
2020-09-07 12:03:41.195354: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcu
dart.so.10.1: cannot open shared object file: No such file or directory
2020-09-07 12:03:41.195392: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
        encoder@35508[I]:post initiating, this may take some time...
        encoder@35508[I]:post initiating, this may take some time takes 0.000 secs
        encoder@35508[S]:successfully built MyQueryEncoder from a yaml config
        encoder@35508[I]:setting up sockets...
        encoder@35508[I]:input tcp://0.0.0.0:48061 (PULL_BIND)   output tcp://0.0.0.0:47091 (PUSH_CONNECT)       control over tcp://0.0.0.0:46769 (PAIR_BIND)
        encoder@35508[S]:ready and listening
 vector_indexer@35512[I]:post initiating, this may take some time...
 vector_indexer@35512[I]:post initiating, this may take some time takes 0.000 secs
 vector_indexer@35512[S]:successfully built BaseExecutor from a yaml config
 vector_indexer@35512[I]:setting up sockets...
 vector_indexer@35512[I]:input tcp://0.0.0.0:47091 (PULL_BIND)   output tcp://0.0.0.0:32865 (PUB_BIND)   control over tcp://0.0.0.0:35741 (PAIR_BIND)
 vector_indexer@35512[S]:ready and listening
 vector_indexer@35515[I]:post initiating, this may take some time...
 vector_indexer@35515[I]:post initiating, this may take some time takes 0.000 secs
 vector_indexer@35515[S]:successfully built BaseExecutor from a yaml config
 vector_indexer@35515[I]:setting up sockets...
 vector_indexer@35515[I]:input tcp://0.0.0.0:42063 (PULL_BIND)   output tcp://0.0.0.0:54559 (PUSH_CONNECT)       control over tcp://0.0.0.0:39395 (PAIR_BIND)
 vector_indexer@35515[S]:ready and listening
 vector_indexer@35518[I]:post initiating, this may take some time...
 vector_indexer@35518[I]:post initiating, this may take some time takes 0.000 secs
 vector_indexer@35518[S]:restore AnnoyIndexer from ./data/doc_indexer-1/vecidx.bin
 vector_indexer@35518[I]:post initiating, this may take some time...
 vector_indexer@35518[I]:post initiating, this may take some time takes 0.000 secs
 vector_indexer@35518[S]:restore BinaryPbIndexer from ./data/doc_indexer-1/docidx.bin
 vector_indexer@35518[I]:post initiating, this may take some time...
 vector_indexer@35518[I]:post initiating, this may take some time takes 0.001 secs
 vector_indexer@35518[S]:successfully built CompoundIndexer from a yaml config
 vector_indexer@35518[I]:loading index from ./data/doc_indexer-1/vec.gz...
Traceback (most recent call last):
  File "app.py", line 122, in <module>
    main()
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "app.py", line 111, in main
    query(num_docs, top_k)
  File "app.py", line 64, in query
    with f:
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/flow/__init__.py", line 461, in __enter__
    return self.start()
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/flow/__init__.py", line 505, in start
    self.enter_context(v)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/peapods/pod.py", line 241, in __enter__
    return self.start()
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/peapods/pod.py", line 369, in start
    return super().start()
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/peapods/pod.py", line 211, in start
    self.enter_context(p)
  File "/home/ec2-user/.pyenv/versions/3.8.5/lib/python3.8/contextlib.py", line 425, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/peapods/pea.py", line 403, in __enter__
    return self.start()
  File "/home/ec2-user/.pyenv/versions/jina-0.5/lib/python3.8/site-packages/jina/peapods/pea.py", line 399, in start
    raise TimeoutError(
TimeoutError: <class 'jina.peapods.pea.BasePea'> with name vector_indexer-1 can not be initialized after 3600000.0ms
```

As you can see, it is taking more than 1 hour for loading 1 single shard. And in that run, we splitted our dataset into 10 shards. So it would means that it will potentially need more than 10 hours (we don't know really how much time would need due to we stop testing when we set the timeout to 1 hour) for loading the full dataset for querying it.

For giving more context about the test executed. These are the details:

* [This is a package with the jina setup used](https://com-ravenpack-nchan.s3.amazonaws.com/jina-ai-config-3.tar.gz).
* As commented above, the timeout problems arrives when trying to load the indices already generated with the ~190GB dataset mentioned in #867. For that, we are using the `flow-query.yml` flow that you will find in the package.
* These indices have been created by using the `flow-index.yml` flow that you can find in the same package.
* We've tried with different indexers (NmsLibIndexer, NumpyIndexer...). All of them with similar results.
* These are the params that we are using for indexing:
`PREFETCH=5 PREFETCH_ON_RECV=1 BATCH_SIZE=50 PARALLEL=10 SHARDS=10 python app.py -t index`
* And these are for querying:
`PREFETCH=5 PREFETCH_ON_RECV=1 BATCH_SIZE=50 PARALLEL=1 SHARDS=10 python app.py -t query`

We understand that it is caused by the volume of the shards that we are generating. But if this is true, I'd like to find some configuration that allows us to have a better scalable solution. Because we want to use Jina for much bigger datasets than the used in this test.

Following your documentation (sorry if I misunderstood something), I could see that we can delegate each flow step in a different micro-service via network connection. So, having the next query flow:

```yaml
!Flow
with:
  read_only: true
  port_expose: $JINA_PORT
pods:
  encoder:
    uses: pods/query-encode.yml
    parallel: $PARALLEL
    timeout_ready: 3600000
    read_only: true
  vector_indexer:
    uses: pods/index-vector.yml
    shards: $SHARDS
    separated_workspace: true
    timeout_ready: 3600000
    polling: all
    reducing_uses: _merge_all
  ranker:
    uses: MinRanker
```

If we migrate them to a network connected micro-service model, I understand that would be something like this:

```
(encoder) -> TCP connection -> (vector_indexer) -> TCP connection -> (ranker)
```

And that allows us to apply vertical scaling in each step node. Which is good.

* But, would be possible to have something like this?:

```
            |--> TCP connection -> (vector_indexer-1) -> TCP connection --|
(encoder) -----> TCP connection -> (vector_indexer-2) -> TCP connection -----> (ranker)
            |--> TCP connection -> (vector_indexer-3) -> TCP connection --|
```

So we can apply horizontal scaling to some specific micro-service. Like the `vector_indexer`.

* At same point, can we do the same at index step? so, if we have this:

```yaml
!Flow
with:
  prefetch: $PREFETCH
  prefetch_on_recv: $PREFETCH_ON_RECV
pods:
  reader:
    uses: pods/extract.yml
  encoder:
    uses: pods/encode.yml
    parallel: $PARALLEL
    timeout_ready: 1200000
    read_only: true
    needs: reader
  vector_indexer:
    uses: pods/index-vector.yml
    parallel: $PARALLEL
    shards: $SHARDS
    separated_workspace: true
```

* Would be possible to do some horizontal scaling like this?:

```
                       |--> TCP connection -> (vector_indexer-1)
(reader) ---(encoder) ----> TCP connection -> (vector_indexer-2)
                       |--> TCP connection -> (vector_indexer-3)
```

So we can spread our dataset into different indexers?. Each indexer with its own data and shards.

Our idea is to spread the big dataset shards into multiple nodes, so each node need to read less data rather than the full dataset.
Also to make lighter the queries performed in each node, due to they have lighter dataset to load, the startup time and the memory consumition when loading the dataset would be also lighter.

* And last question, what setup do you recommend for working with large datasets?

Please, let me know if you need more info.
Thanks in advance!

**Environment**

```bash
$> jina --version-full
jina                          0.5.2
jina-proto                    0.0.59
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.18.5
protobuf                      3.13.0
proto-backend                 cpp
grpcio                        1.31.0
ruamel.yaml                   0.16.10
python                        3.8.5
platform                      Linux
platform-release              4.14.146-93.123.amzn1.x86_64
platform-version              #1 SMP Tue Sep 24 00:45:23 UTC 2019
architecture                  x86_64
processor                     x86_64
jina-resources                /home/ec2-user/.pyenv/versions/3.8.5/envs/jina-0.5/lib/python3.8/site-packages/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_TEST_FAISS               (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)
```

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-218) by [Unito](https://www.unito.io/learn-more)

**Comment by hanxiao** [comment]
Hi, thanks again for the report, very good issue. We have put this under our radar.

There are many ways for scaling indexers, let's grab the low-hanging fruit first. As a start, could you tell us what is the file size under your shards?

![image](https://user-images.githubusercontent.com/2041322/92624023-519ed980-f2c7-11ea-8b2f-21b466284e73.png)

you may observe more or less this file structure on disk, could you print the size recursively, e.g.

```bash
➜  multires-lyrics-search git:(master) ✗ du -ah workspace | sort -r -h | head -n20
 42M	workspace
5.5M	workspace/chunk_compound_indexer-6
5.4M	workspace/chunk_compound_indexer-6/vec.gz
5.3M	workspace/chunk_compound_indexer-7/vec.gz
5.3M	workspace/chunk_compound_indexer-7
5.3M	workspace/chunk_compound_indexer-2/vec.gz
5.3M	workspace/chunk_compound_indexer-2
5.2M	workspace/chunk_compound_indexer-8
5.2M	workspace/chunk_compound_indexer-5/vec.gz
5.2M	workspace/chunk_compound_indexer-5
5.2M	workspace/chunk_compound_indexer-3/vec.gz
5.2M	workspace/chunk_compound_indexer-3
5.2M	workspace/chunk_compound_indexer-1/vec.gz
5.2M	workspace/chunk_compound_indexer-1
5.1M	workspace/chunk_compound_indexer-8/vec.gz
4.2M	workspace/chunk_compound_indexer-4
4.1M	workspace/chunk_compound_indexer-4/vec.gz
420K	workspace/doc.gzip
 32K	workspace/chunk_compound_indexer-7/chunk.gz
 32K	workspace/chunk_compound_indexer-6/chunk.gz
```

**Comment by jmferrete** [comment]
Sure, thanks for investigating this.

These are the files generated from the dataset that we are testing with (~190 GB of jsonl files):

```bash
$> du -ah data/ | sort -r -h | head -n20
54G	data/
5,5G	data/doc_indexer-9
5,4G	data/doc_indexer-8
5,4G	data/doc_indexer-7
5,4G	data/doc_indexer-6
5,4G	data/doc_indexer-5
5,4G	data/doc_indexer-4
5,4G	data/doc_indexer-3
5,4G	data/doc_indexer-2
5,4G	data/doc_indexer-10
5,4G	data/doc_indexer-1
5,3G	data/doc_indexer-9/vec.gz
5,2G	data/doc_indexer-8/vec.gz
5,2G	data/doc_indexer-7/vec.gz
5,2G	data/doc_indexer-6/vec.gz
5,2G	data/doc_indexer-5/vec.gz
5,2G	data/doc_indexer-4/vec.gz
5,2G	data/doc_indexer-3/vec.gz
5,2G	data/doc_indexer-2/vec.gz
5,2G	data/doc_indexer-1/vec.gz
```

**Comment by hanxiao** [comment]
@jmferrete just to let you know the team is working on this and list it as one of the high priority in this two weeks. Will keep you in the loop.

**Comment by jmferrete** [comment]
> @jmferrete just to let you know the team is working on this and list it as one of the high priority in this two weeks. Will keep you in the loop.

Thanks for advising!

**Comment by sibbsnb** [comment]
I have the same question, i don't see an architecture on how to scale Jina for huge datasets. Hopefully the solution to this issue will lead the path to that.

**Comment by janandreschweiger** [comment]
How good does jina perform in general on large datasets?
I'm curious about this issue, because my cooperation plans to implement jina for searching our documentation.

**Comment by JoanFM** [comment]
Hello @janandreschweiger.

We are happy to hear about your interest in jina. As you can see we are moving really fast but we did not have the chance to do stress testing at scale yet.

However, this is one of the top priorities in our roadmap for the near future. We would be very happy if you could share with us what is your intended usecase and the challenges you may face.

**Comment by JoanFM** [comment]
However, we have done some benchmarking in fashion-mnist dataset.

The process is explained here:
 https://hanxiao.io/2020/11/10/Optimizing-the-Overhead-of-a-Decentralized-Search-System/
And it uses this repo: https://github.com/jina-ai/latency-tracking

We will soon also provide better detailed documentation about how to ease the distribution of jina Pods in distributed environments, so please stay tuned.

**Comment by janandreschweiger** [comment]
Hi @JoanFM,

thank you for your answering my question. We've decided to give your framework a try.

Our goal is to build one central search engine for our entire documentation. In essence our documentation consists of a web-based wiki, git and some files (e.g. PDFs). Therefore, we only focus on searching the text content (and if possible the filenames).
Do you think your framework fits our use case well?

It would be great if you could publish a search example on longer texts in the future. As this is one of the most common applications in search.

Again thanks for helping me out. I really appreciate your support!

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

I do think that the framework fits very well ur case, I think our flexibility can cover all your needs. We can also extract text from PDF documents and do neural search at different semantic levels. 

We will keep in mind your suggestion to build such an example. Is there a specific challenge that you are struggling to cover?

**Comment by janandreschweiger** [comment]
Thanks @JoanFM, we've already found all the necessary informations that we need. I also think that your well structured architecture will fit our needs. Keep up the good work!

**Comment by nitinkumartech** [comment]
@jmferrete @hanxiao Just curious if you guys were able to solve the issue you were having? We were planning to use this framework to build a neural search on top of our dataset (2 million PDFs). Can you please share your findings/recommendations for adapting jina over a dataset this large?
