### ISSUE TITLE
Add visualize() method to Flow

### ISSUE THREAD

**Issue by ke-zhang-rd** [jina-ai/jina#949]
**Describe the feature**

When constructing a `Flow`, it isn't intuitive, at least for me, what the workflow will look like. 

```
f = (Flow().add(name='p1') 
           .add(name='p2')
           .add(name='p3', needs='p1') 
           .needs(['p2', 'p3']) 
           .add(name='p4'))
```

So It would be handy if Flow has a `visualize()` method which generates a graph of pods and their needs.

**Your proposal**

![image](https://user-images.githubusercontent.com/14223460/93186843-12c8b380-f70d-11ea-85d7-97042e7709bd.png)

This task might involve:

* Use [graphviz](https://pypi.org/project/graphviz/) for graph display.
* Reorganize with [build()](https://github.com/jina-ai/jina/blob/master/jina/flow/__init__.py#L410) of `Flow` since it constructs a graph internally already.
* Extra utility code to figure out backend of GUI integration.
* 
* 
* 

**Environment**

```
jina                          0.5.4
jina-proto                    0.0.59
jina-vcs-tag                  (unset)
libzmq                        4.3.2
pyzmq                         1.19.2
protobuf                      3.13.0
proto-backend                 cpp
grpcio                        1.32.0
ruamel.yaml                   0.16.12
python                        3.8.5
platform                      Darwin
platform-release              19.5.0
platform-version              Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64
architecture                  x86_64
processor                     i386
jina-resources                /Users/kz2249/jina/jina/resources
JINA_ARRAY_QUANT              (unset)
JINA_CONTRIB_MODULE           (unset)
JINA_CONTRIB_MODULE_IS_LOADING(unset)
JINA_CONTROL_PORT             (unset)
JINA_DEFAULT_HOST             (unset)
JINA_EXECUTOR_WORKDIR         (unset)
JINA_FULL_CLI                 (unset)
JINA_IPC_SOCK_TMP             (unset)
JINA_LOG_FILE                 (unset)
JINA_LOG_LONG                 (unset)
JINA_LOG_NO_COLOR             (unset)
JINA_LOG_PROFILING            (unset)
JINA_LOG_SSE                  (unset)
JINA_LOG_VERBOSITY            (unset)
JINA_POD_NAME                 (unset)
JINA_PROFILING                (unset)
JINA_SOCKET_HWM               (unset)
JINA_STACK_CONFIG             (unset)
JINA_TEST_CONTAINER           (unset)
JINA_TEST_GPU                 (unset)
JINA_TEST_PRETRAINED          (unset)
JINA_TEST_FAISS               (unset)
JINA_VCS_VERSION              (unset)
JINA_VERSION                  (unset)
JINA_WARN_UNNAMED             (unset)
JINA_BINARY_DELIMITER         (unset)
JINA_DISABLE_UVLOOP           (unset)
```

┆Issue is synchronized with this [Jira Task](https://jinaai.atlassian.net/browse/JINACORE-232) by [Unito](https://www.unito.io/learn-more)

**Comment by maximilianwerk** [comment]
Hey @ke-zhang-rd,
thanks a lot for your input. Apparently, that is exactly one of the features of our [Jina Dashboard ](https://dashboard.jina.ai/) [(repository)](https://github.com/jina-ai/dashboard). If you open it, you see the `Flow Designer` on the left hand side. When you start a jina flow with `--logserver`, you actually get you flow visualized quite nicely. I haven't tried yet to connect to the dashboard from an interactive python session, but will have a look tomorrow. Anyhow, if you create an `app.py` file like in one of our examples (e.g. the [southpark search](https://github.com/jina-ai/examples/tree/master/southpark-search)) it should work out of the box.

**Comment by hanxiao** [comment]
https://github.com/jina-ai/jina/pull/865

@ke-zhang-rd please refer to this PR and the reason why I close it.

In case you are interested, https://hanxiao.io/2019/10/18/GNES-Flow-a-Pythonic-Way-to-Build-Cloud-Native-Neural-Search-Pipelines/

**Comment by ke-zhang-rd** [comment]
Thanks @hanxiao. I didn't realize that history PR before. I'll leave you guys decide whether to skip this one. Below are just some of my thinking for maybe future reference:

I guess function name `visualize` confuse two visualizations:
- **visualization** in pipeline of data science(acquisition, management, analysis and visualization), I argree with you and I quote "it has to be handled separately for better maintainability and functionality."
- **visual correction**, when people write code line by line and want to confirm the code match their mind. It's `print` of graph. 

Clearly, first type of visualization is far richer than second one. However both are covered in comparable pkg [dask](https://docs.dask.org/en/latest/graphviz.html).
This feature could be a handy utility function(It never tries to handle whole visualization) as #865 pointed. And a typical scenario could be ensure the graph after writing the line of `add()` and `needs()`. Take myself as example, when I read flow construction code with multiple line of `add` and `needs` first time, I gotta manually draw a figure to double check it.

Glad **GRAPH** isn't lacking. it is just on different end(frontend/backend). Skip it and guide user to centralized dashboard, as @maximilianwerk mentioned, might also a good strategy.

**Comment by hanxiao** [comment]
> visual correction, when people write code line by line and want to confirm the code match their mind. It's print of graph.

@lusloher issue is about adding a graphical representation of the flow API,
- a CLI/ipython notebook-friendly 
- static jpg/png/svg output
- for the ease of debugging the flow

We had this function before: https://github.com/jina-ai/jina/pull/865#issuecomment-679020707 but for the high-level design reason I removed it and move all visualization to the dashboard.

As this is the second time the community asked for it (https://github.com/jina-ai/jina/pull/865), we may add more attention to it. Not really a big task though. Also have the legacy code here: https://gist.github.com/hanxiao/2ce064b6ff624a478a0bbd17e68714ae

**Comment by hanxiao** [comment]
@ke-zhang-rd we finally decided to add it back. Now it's there in the master, will be rolled out in the patch release this Sunday.

![image](https://user-images.githubusercontent.com/2041322/95297601-06062e00-087b-11eb-93e9-5ab6dc670bfd.png)

**Comment by theUnkownName** [comment]
Hi @ke-zhang-rd thanks for the input! was really valuable and we went for it! 
Take a look
![image](https://user-images.githubusercontent.com/3002344/95297718-3221af00-087b-11eb-918f-7f4cbcdc08ef.png)
